### ISSUE TITLE
Issues should be either in JIRA or here

### ISSUE THREAD

**Issue by bbannier** [root-project/root#1]
Hi,

I am not sure if having both the JIRA and github issue trackers is a good idea. It might create confusion, make it more work to follow developments, and might make historic investigations harder/impossible.

**Comment by Axel-Naumann** [comment]
New issues are now reported *only* on GitHub. We keep Jira open for existing issues. We will close Jira issue submission to the public in about a year; until then there's a message telling people to go to GitHub instead.

**Comment by AnirudhDagar** [comment]
This is great, will definitely help with open source contributions.
Thanks!
