### ISSUE TITLE
[MetaSema/TApplication] outdated .help message

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10065]
- [x] Checked for duplicates

### Describe the bug
In the ROOT prompt, `.?` prints a slightly outdated help message.

Both the Cling-specific part (MetaSema) and the ROOT-specific special commands (TApplication) need revision.

### Expected behavior
All options are documented, and outdated ones are removed.

- [ ] Update accordingly in https://github.com/root-project/web/blob/main/manual/cling/index.md
- [ ] Copy resulting output to https://github.com/root-project/web/blob/main/manual/first_steps_with_root/index.md
- [ ] https://github.com/root-project/NotebookPrimer/blob/master/notebooks/2-ROOT-Basics.ipynb
- [x] .![shell]
- [x] .qqqqq
- [x] "   " << metaString << "R [user@]host[:dir] [-l user] [-d dbg] [script]\t- Launch process in a remote host\n"
- [x] "   " << metaString << "demo\t- Launch GUI demo\n"
- [x] "   " << metaString << "credits\t- Show credits\n"
- [x] "   " << metaString << "license\t- Show license\n"
- [x] CTRL+D also works as a way to exit
- [x] CTRL+C can interrupt
- [x] CTRL+Z pauses job
- [x] CTRL+L clear screen
- [x] CTRL+Del Ctrl Left Ctrl Right Ctrol Backspace https://github.com/root-project/root/pull/10091
- [x] CTRL+S for forward search https://github.com/root-project/root/issues/10137
- [x] .exit
- [x] .quit
- [x] .typedef
- [x] .include
- [x] Specify also a new command, e.g. .flags, to show 
- [x] .undo / .U to unload the last n input lines doesn't seem to work
- [x] .O1 to set the optimization level is implemented even if .help says it's not
- [x] Translate 0x1F code etc to key name
- [x] Clarify what .files and .fileEx and .stats mean

### To Reproduce
`.?`

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 12 2022, 10:17:19                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
https://github.com/root-project/web/pull/764
https://github.com/root-project/root/pull/10055

**Comment by couet** [comment]
I'll check

**Comment by couet** [comment]
Does the pr #10055 address fully this issue ?

**Comment by ferdymercury** [comment]
> Does the pr #10055 address fully this issue ?

No. That PR only was for adding the shortcut of .help

This issue is for all the rest (ie the things in the description).

**Comment by couet** [comment]
Can you suggest a PR and an expert of that part of ROOT will examine it ? Several things you mentioned here do not work or are not clear to me.

**Comment by ferdymercury** [comment]
Yes, I can do this, but I think it's better if I wait for https://github.com/root-project/root/pull/10055 to be merged so that there are no merge conflicts.

**Comment by couet** [comment]
done

**Comment by ferdymercury** [comment]
@couet @jalopezg-r00t first draft of the PR is ready

**Comment by ferdymercury** [comment]
@eguiraud concerning .O1, should i change in MetaSema 
(not yet implemented) --> (implemented only for 0 and 1 ?)

**Comment by Axel-Naumann** [comment]
We don't need to implement things just because we have help pointing at them - we should remove the help then.

`.files` is useful, `.filesEx` and `.stats` isn't relevant for the average user; no need to document them in `.help`.
