### ISSUE TITLE
[doxy] qch and tag as compressed files

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10066]
### Explain what you would like to see improved
qch and tag files generated by doxygen and posted at https://root.cern/reference/ are big. It would reduce some space and make it nicer to download, especially in the case of the tag file, that is XML and the automatic browser parser gets easily stuck trying to read it instead of downloading it.

### Optional: share how it could be improved
Apply compression as already done for the html.

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 12 2022, 10:17:19                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
https://github.com/doxygen/doxygen/issues/9185#issuecomment-1059971803

**Comment by couet** [comment]
Yes good point.

**Comment by couet** [comment]
By the way on  https://root.cern/reference/  the ROOT.tag files are also not compressed and when clicking on them the browser tries to display them. It might be a good idea to compressed them also to force the download ?

**Comment by ferdymercury** [comment]
Yes. ( Although once compressed, the default is to download, there is no need to specifically set that.)

**Comment by couet** [comment]
I agree I do not want to set anything. Just provide compressed files.

**Comment by couet** [comment]
Done.
