### ISSUE TITLE
[doxy] upgrade to Mathjax3

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10067]
### Explain what you would like to see improved
Mathjax2 is used by documentation.

### Optional: share how it could be improved
Mathjax3 brings some performance improvements.

Maybe it can be even downloaded on the fly, rather than storing it as part of the ROOT source code?

### To Reproduce
https://root.cern.ch/doc/master/

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 12 2022, 10:17:19                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
https://github.com/doxygen/doxygen/issues/9185#issuecomment-1059971803

**Comment by couet** [comment]
I will look at it. I prefer to have a self consistent doc. Having it with the doc reduces the dependencies in case the remote website is down.

**Comment by couet** [comment]
By chance do you know where to download it from ? it does not seem obvious.

**Comment by ferdymercury** [comment]
> By chance do you know where to download it from ? it does not seem obvious.

I think from Git: https://docs.mathjax.org/en/latest/web/hosting.html#getting-mathjax-via-git

**Comment by ferdymercury** [comment]
> I will look at it. I prefer to have a self consistent doc. Having it with the doc reduces the dependencies in case the remote website is down.

I see. In that case, I would suggest to use a [git submodule](https://www.atlassian.com/git/tutorials/git-submodule). This way it is self-consistent and it would work without Internet.

**Comment by ferdymercury** [comment]
pinging @albert-github in case he has a better idea. (thanks!)

**Comment by albert-github** [comment]
No really another idea (I never tried to prune the MathJax version 3)
An alternative place might be: https://github.com/mathjax/MathJax/releases/

**Comment by couet** [comment]
> An alternative place might be: https://github.com/mathjax/MathJax/releases/

The file provided there for download does not work. It is not the equivalent of the `mathjax.tar.gz` file we have in the root repository. Formulae are not interpreted if I replace the original file but this one.

I will now try the URL way.

**Comment by albert-github** [comment]
@couet Did you update the `Doxyfile` for the MathJax version 3 (default for `MATHJAX_VERSION` is `MathJax_2` but you need `MathJax_3`)

**Comment by couet** [comment]
even with:
```
 MATHJAX_VERSION        = MathJax_3
```
The file downloaded from the URL previously mentioned, does not work.

**Comment by couet** [comment]
Oops wait .. I may have done a mistake ... brb

**Comment by ferdymercury** [comment]
> yes it works. Where do you gain in speed with mathjax 3 ?

https://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html#improved-speed

**Comment by couet** [comment]
PR here: https://github.com/root-project/root/pull/10074

**Comment by ferdymercury** [comment]
Thanks!! Shall I close the issue?

**Comment by couet** [comment]
Yes
