### ISSUE TITLE
RootMacros.cmake on macOS 12.2.1, root version v6-26

### ISSUE THREAD

**Issue by sa35** [root-project/root#10062]
If a project (using CMake) relies on the macro root_generate_dictionary provided by $ROOTSYS/cmake/RootMacros.cmake on macOS 12.2, it will fail since LD_LIBRARY_PATH is not recognised, only DYLD_LIBRARY_PATH seems to work. The following diff is working for me but I am not sure it will work on older macOS versions as well.

[RootMacros.cmake.diff.zip](https://github.com/root-project/root/files/8197640/RootMacros.cmake.diff.zip)

**Comment by Axel-Naumann** [comment]
Can you share how you determined that `DYLD_LIBRARY_PATH` works?

**Comment by sa35** [comment]
Hi,

I am not quite sure I understand what you would like to see. 
One thing which might be relevant: I install root here on a non-standard path.
Furthermore the project is relying on MacPorts.

root v6-26 without patch
------------------------
cd /Users/suter_a/Applications/musrfit/build/src/classes && /opt/local/bin/cmake -E env LD_LIBRARY_PATH=/Users/suter_a/Applications/root/root_exec/lib: /Users/suter_a/Applications/root/root_exec/bin/rootcling -v2 -f PUserFcnBaseDict.cxx -s /Users/suter_a/Applications/musrfit/build/src/classes/libPUserFcnBase.dylib -rml libPUserFcnBase.dylib -rmf /Users/suter_a/Applications/musrfit/build/src/classes/libPUserFcnBase.rootmap -inlineInputHeader -I/opt/local/include -I/Users/suter_a/Applications/musrfit/src/include -DPNEXUS_ENABLED -compilerI/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -compilerI/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -compilerI/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -compilerI/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -compilerI/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -compilerI/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -compilerI/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/suter_a/Applications/root/root_exec/include -I/opt/local/include -I/Users/suter_a/Applications/musrfit/src/include -I/Users/suter_a/Applications/musrfit/src/classes PUserFcnBase.h /Users/suter_a/Applications/musrfit/src/include/PUserFcnBaseLinkDef.h
dyld[7935]: Library not loaded: @rpath/libRIO.so
  Referenced from: /Users/suter_a/Applications/root/root_exec/bin/rootcling
  Reason: tried: '/usr/local/lib/libRIO.so' (no such file), '/usr/lib/libRIO.so' (no such file)
Subprocess aborted
make[2]: *** [src/classes/PUserFcnBaseDict.cxx] Error 1
make[1]: *** [src/classes/CMakeFiles/PUserFcnBase.dir/all] Error 2
make: *** [all] Error 2

root v6-26 with patch
---------------------
cd /Users/suter_a/Applications/musrfit/build/src/classes && /opt/local/bin/cmake -E env DYLD_LIBRARY_PATH=/Users/suter_a/Applications/root/root_exec/lib: /Users/suter_a/Applications/root/root_exec/bin/rootcling -v2 -f PUserFcnBaseDict.cxx -s /Users/suter_a/Applications/musrfit/build/src/classes/libPUserFcnBase.dylib -rml libPUserFcnBase.dylib -rmf /Users/suter_a/Applications/musrfit/build/src/classes/libPUserFcnBase.rootmap -inlineInputHeader -I/opt/local/include -I/Users/suter_a/Applications/musrfit/src/include -DPNEXUS_ENABLED -compilerI/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -compilerI/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -compilerI/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -compilerI/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -compilerI/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -compilerI/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -compilerI/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/suter_a/Applications/root/root_exec/include -I/opt/local/include -I/Users/suter_a/Applications/musrfit/src/include -I/Users/suter_a/Applications/musrfit/src/classes PUserFcnBase.h /Users/suter_a/Applications/musrfit/src/include/PUserFcnBaseLinkDef.h
cd /Users/suter_a/Applications/musrfit/build && /opt/local/bin/cmake -E cmake_depends "Unix Makefiles" /Users/suter_a/Applications/musrfit /Users/suter_a/Applications/musrfit/src/classes /Users/suter_a/Applications/musrfit/build /Users/suter_a/Applications/musrfit/build/src/classes /Users/suter_a/Applications/musrfit/build/src/classes/CMakeFiles/PUserFcnBase.dir/DependInfo.cmake --color=
Dependee "/Users/suter_a/Applications/musrfit/build/src/classes/CMakeFiles/PUserFcnBase.dir/DependInfo.cmake" is newer than depender "/Users/suter_a/Applications/musrfit/build/src/classes/CMakeFiles/PUserFcnBase.dir/depend.internal".
Dependee "/Users/suter_a/Applications/musrfit/build/src/classes/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/suter_a/Applications/musrfit/build/src/classes/CMakeFiles/PUserFcnBase.dir/depend.internal".
Scanning dependencies of target PUserFcnBase
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/classes/CMakeFiles/PUserFcnBase.dir/build.make src/classes/CMakeFiles/PUserFcnBase.dir/build
...

And all the further root_generate_dictionary work as well.

Does this help?

Cheers,
  Andreas

PS: Machine I have tested it on: 
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64

________________________________

Paul Scherrer Institut

Dr. Andreas Suter
Laboratory for Muon-Spin Spectroscopy
Swiss Muon Source SµS
WLGA/119
Forschungsstrasse 111
CH - 5232 Villigen PSI
Switzerland

Tel.: +41 (0)56 310 4238
________________________________

**Comment by Axel-Naumann** [comment]
Hi Andreas,

`dyld[7935]: Library not loaded: @rpath/libRIO.so` says that (as expected), macOS tries to find the library through the rpath mechanism. That's supposed to work - but doesn't, for you. If you run `otool -l /Users/suter_a/Applications/root/root_exec/bin/rootcling`, what does the section `cmd LC_RPATH` show?

Where did you get ROOT from?

Cheers, Axel

**Comment by sa35** [comment]
Hi Axel,

I cloned root.git from GitHub and compiled from source with the following configuration:

cmake ../ -Dgminimal=1 -Dasimage=1 -Dmathmore=1 -Dminuit2=1 -Dxml=1 -Dopengl=1 -Dbuiltin_glew=1 -DCMAKE_INSTALL_PREFIX=$HOME/Applications/root/root_exec
There is NO LC_RPATH (see the attached otool output.

Best,
  Andreas

**Comment by sa35** [comment]
Hi there,

I am wondering what is going on with my bug report. I always need to fix the RootMacro.cmake (see first message) in order to work whenever I update ROOT.

Best,
  Andreas
