### ISSUE TITLE
Difficult to configure Xrootd to use non-builtin openssl

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#10075]
### Explain what you would like to see improved
In `builtins/xrootd/CMakeLists.txt` we don't pass any openssl configuration over to Xrootd. This causes inconsistent builds for ROOT and xrootd.

### Optional: share how it could be improved
Maybe use
```
OPENSSL_CRYPTO_LIBRARY
OPENSSL_SSL_LIBRARY
OPENSSL_INCLUDE_DIR
```
as made available with Xrootd's `CMakeLists.txt`. 

### To Reproduce
See https://root-forum.cern.ch/t/building-from-source-root-v6-26-00-failing-with-openssl-on-macos-monterey/49078

**Comment by bellenot** [comment]
@Axel-Naumann  According to the [Xrootd README](https://github.com/xrootd/xrootd/blob/master/README), the only `OpenSSL` related variable we can pass is `OPENSSL_ROOT_DIR`. Not sure it would solve this issue...

**Comment by dpiparo** [comment]
@amadio what's your take on this?

**Comment by guitargeek** [comment]
Only one line of change needed to close an issue? Let's go:
  * https://github.com/root-project/root/pull/15697
