### ISSUE TITLE
TRint changes in 6.26.00 break existing use cases

### ISSUE THREAD

**Issue by olifre** [root-project/root#10090]
Disclaimer: I am not sure whether this is:
* 0 bug report (intented / wontfix),
* 1 or 2 bug reports. 

Depending on feedback, We can close and  / or I can create dedicated bugs. 

### Observations
There are two changes in 6.26.00:
* `TRint` exits hard for unknown arguments. 
* `TRint` crashes when instantiated with `*argc = nullptr` and / or `argv = nullptr` which are the default values for `TApplication` and hence may be used by existing users of the `TRint` constructor. 

### Affected use cases
Applications may do something like:
```cpp
TRint *app = new TRint("app", 0, NULL);
...
app->Run(kTRUE);
```
Applications may also use `TRint` during operation. One existing model some applications I use are employing is:
* Create a `TRint` shortly after startup, passing in `argc` and `argv`. 
* Allow the user to drop to a ROOT interpreter prompt. This is then done by calling `app->Run(kTRUE);`. A user can use the interpreter to inspect state of the analysis software, and exit it again to let the software continue. 

The latter approach is extremely useful for example to shell out after analysis software startup, or inside an event, such that the user can interactively analyze objects right from a ROOT interpreter shell. 

### Questions
* Is the use case "use TRint as class to drop into the interpreter" supported? 
The changelog of 6.26.00 reads like `TRint` is meant for internal use by `root.exe` only, but there seems to be no easy alternative. 
Depending on the reply, this could be a separate bug report, or a "wontfix". 
* If the use case is / should be supported, It would be useful to be able to allow unsupported arguments to pass through, for use in applications which are not `root.exe`. 
* For improved backwards compatibility and safety, not crashing when being passed `*argc = nullptr` and / or `argv = nullptr` would be nice. 

In case somebody else is hit by this, I am right now using this hack as workaround:
```cpp
                int dargc = 1;
                char** dargv = &argv[0];
                myApp = new TRint("myApp", &dargc, dargv, nullptr, 0, kTRUE);
                myApp->GetOptions(&argc, (argv));
                gSystem->SetProgname(argv[0]);
```
This allows to re-use the `TApplication` functionality as before, without triggering one of the two issues.

**Comment by olifre** [comment]
Thanks for the reference, @vepadulano ! 

If `TRint` is indeed purely for use in `root.exe`, this is news to me (and some other colleagues), since the documentation of the class does not seem to state it's internal — it's used in our analysis software, the analysis software we inherited from (a decade ago, from a different collaboration), various student analyses etc. 

As described above, the main use case is something for which no alternate class seems to exist:
* Start an application, and prepare an environment (e.g. an analysis framework). 
* Drop to the interpreter at some point later, e.g. during the first event. 
* Allow to interactively study the in-memory objects via the interpreter shell. 

Note that I fully agree with the notion that `root.exe` should exit when encountering unrecognized options. However, the class is actively and successfully used in many projects I know (due to it's usefulness), and there is no easy replacement. So if it's internal, I'd probably vote for something like `TApplicationInterpreter` which would be similar to `TRInt`, but without the newly added `root.exe` specifics, and could be used by external projects (to prevent the need for external projects to replicate `TRint`). 

Opinions welcome :-).

**Comment by olifre** [comment]
To provide one example, in additio to the more hadron-physics focussed cases I know, it's also used in one tool which is part of ATLAS's Athena:
https://gitlab.cern.ch/atlas/athena/-/blob/master/Simulation/RunDependentSim/RunDependentSimComps/src/RunPileUpOverlayReuseToys.cxx

**Comment by Axel-Naumann** [comment]
We can't retroactively make something internal :-) so indeed, TRint is part of ROOT's public API and thus we'll have to support the usage you describe. To get there, we'll need:
- [ ] PR https://github.com/root-project/root/pull/10094 - thank you!
- [ ] a test for this use case
- [ ] a mode where `TRint` used by ROOT exists on unknown arguments, but not for you, or decide that the old `TRint` behavior was a bug and `TRint::TRint` must be fed with only valid arguments for `TRint`.

Do you have a proposal for the latter? We can add a new boolean constructor argument, `failOnUnknownArgs = false` which we set to `true` in ROOT.

Could you create a PR for a test that simulates what you are doing? It would be wonderful to have that as unit test in `core/rint/test` - which currently doesn't exist, but it's trivial to set this up, just follow for instance what's in `core/foundation/test`. This would be very much appreciated - if you cannot do that please let me know and we'll propose something that you can review back and forth until we have something that represents your use case.

**Comment by olifre** [comment]
@Axel-Naumann Many thanks for the detailed and friendly reply! :+1: 

> Do you have a proposal for the latter? We can add a new boolean constructor argument, `failOnUnknownArgs = false` which we set to `true` in ROOT.

Indeed, I believe the additional constructor argument is best. 
The only other solution which comes to mind (if it would not be possible to add a parameter) would be to (once more) use magic numbers for the `numOptions` parameter (similar to how `TApplication` ignores `argc` and `argv` if `numOptions==-1`), but that is certainly not a design pattern leading to modern, readable code, so better not spread it more ;-).  
`failOnUnknownArgs` sounds like a great choice of name, it clarifies the intent clearly. 

> It would be wonderful to have that as unit test in `core/rint/test` [...]

It seems this does already exist, and has a unit test checking that errors are producted by `TRint` if unrecognitzed options are encountered ;-). Still, it seems I lack sufficient experience with `gtest`, since I don't understand why (for example) `TRint` with unsupported arguments does not `Terminate()` the test — so it's unclear to me how to write a test checking that it does not actually try to `Terminate()` when provided with a to-be-added `failOnUnknownArgs = false`. 

In pseudo-steps, I think possible changes / additions to the existing test in `core/rint/test/TRintTests.cxx` to cover the use case as completely as possible could be:
1. The existing test should be changed to set `failOnUnknownArgs = true` (after that is implemented). 
2. A second test could be added, not setting `failOnUnknownArgs` (i.e. the default of `false` is used). This test then needs to check that no `stderr` is produced, and `Terminate()` is not called (here I'm unsure how to do these with `gtest`). 
3. A third test could try to do the following, for complete coverage of the use case:
   i. Create a `TRint (let's name it `myApp for simplicity here)`, passing in supported and unsupported options. 
   ii. Check the unsupported options are accessible via `myApp->Argv()`. 
   iii. Call `myApp`->Run(kTRUE)`, inject `.q` via `stdin` and test that the execution flow returns to after that line. 

Does that sound reasonable? 
Since I am slightly at a loss on how to solve these ideas within `gtest`, I would be fine with going the back and forth approach (learning more `gtest` along the way so I can better contribute tests in the future) ;-).

**Comment by vepadulano** [comment]
The latest linked PR attempts to fix the second part of this issue. A new test is added to check that the unknown arguments are kept and accessible. As for test 3 described above, I'm not sure how to implement it (i.e. how to call `app.Run` and then stop the application programmatically without user input).

**Comment by vepadulano** [comment]
@olifre The two issues you describe should now be fixed (thank you so much for your contribution!). If you are able to build ROOT with latest master branch and confirm the fixes work, I will close this issue

**Comment by olifre** [comment]
@vepadulano That looks great, many thanks! 
I see the tests don't explicitly test that `TRint` does not call `Terminate()` due to an error, but probably there's no easy way to do so. 

I've right now pulled the patch and am recompiling my 6.26.00 installation with it, and will subsequently test several interactive programs (used in lab classes, an analysis framework on top of ROOT, and in some CLI tools) against it and report back. Hope to finish this either late today or tomorrow. From the code changes alone, I don't see what could go wrong — but better test ;-).

**Comment by olifre** [comment]
@vepadulano My teste went perfectly well, i.e. all broken applications I could get my hands on work again, including tiny labclass codes relying on {{TRint}} and the full analysis framework I once maintained most of my time. 
So indeed I think this can be closed, many thanks for the quick implementation of the fix and tests! :+1:

**Comment by vepadulano** [comment]
That's great! Yes indeed the main purpose of the new test was to check that unknown arguments are kept by default and accessible to you. The case where unknown arguments are not accepted already calls `Terminate()` internally and we check that by looking at what's printed in `stderr`. The other case that needed calling `app.Run` then injecting something like `.q` it's unfeasible right now, but I take your confirmation that everything works well as a green light to close this issue.

Thanks again for reporting and all your help, I will also make sure to backport the fixes so that you can benefit from them already in the next patch release :smile:
