### ISSUE TITLE
hs3 enabled despite histfactory off

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#10103]
`rootfit/CMakeLists.txt` does not check whether `HistFactory` is on, despite hs3 depending on it. This happens e.g. if there's no libxml2. See https://root-forum.cern.ch/t/installing-root-error-on-ubuntu/49146/8

**Comment by guitargeek** [comment]
A PR was opened to address the issue: I suggest to also build HistFactory without XML, only excluding the `hist2workspace` executable which depends on XML.
