### ISSUE TITLE
[textinput] CTRL+T eats prompt label

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10133]
### Describe the bug
Type "abcdefgh" in ROOT prompt. Start then pressing repeatedly Ctrl+T (transpose two characters).
You will end up "removing" the root[1] label.

### Expected behavior
It should stop before the root[1] label.

### To Reproduce
- Type "abcdefgh" in ROOT prompt without pressing Enter.
- Start then pressing repeatedly Ctrl+T (transpose two characters).
- You will end up "removing" the root[1] label.

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 12 2022, 10:17:19                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------

```
### Additional context
https://github.com/root-project/root/pull/10121#discussion_r827699644

**Comment by couet** [comment]
In addtition, doing that on Mac, I get the same character repeated. 
```
root [2] abcdef
```
Then the first ctrl T gives:
```
root [2] abcdfe
```
Then an few ctrl T later I get:
```
root [2] eeeeee
```
