### ISSUE TITLE
TEfficiency: missing doc/example about axis customization

### ISSUE THREAD

**Issue by petruccs** [root-project/root#10139]
Missing an explicit example or entry about how to customize the axis of a TEfficiency (e.g. xrange, xlabel, label font, etc.).

After digging into the ROOT forum I have discovered the GetPaintedGraph method which allowed me to customize my plot.
To be honest, I am not even sure this is the right solution but it works well.

I think t it would be nice to have a reference/example in the documentation.

**Comment by lmoneta** [comment]
Thank you @pretruccs for opening this issue and the feedback. You are right that one needs to use`GetPaintedGraph` for this.  I will improve the documentation and add a tutorial  example.
