### ISSUE TITLE
Hash name for macro inside temp build directory

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10147]
### Is your feature request related to a problem? Please describe.
Compiled libraries of a ROOT macro often end up in the same folder, taking some extra space, and I remove then later by hand to avoid polluting too much source code directories. It makes also files in a folder with many scripts, harder to found, as two of every three is 'dummy' (.so, .d).

### Describe the solution you'd like
It would be nice to have an option or flag 't' in [TSystem::CompileMacro](https://root.cern/doc/master/classTSystem.html#ac557d8f24d067a9b89d2b8fb261d7e18) that automatically:
- Outputs the compiled macro to the default temp directory using [std::temp_directory_path](https://en.cppreference.com/w/cpp/filesystem/temp_directory_path)
- It gives this file a hash-generated filename that is path-specific, to avoid that two macros called the same way overwrite each other.
 
The easiest way for this would be to remove all slashes from the full filename and transforms it to underscores. For example:  
`root -l my/full/path/to/folder/my_macro.C+t`
should give:
`/tmp/my_full_path_to_folder_my_macro.C_so`

Or alternatively, if a new flag is not wanted, that this could be specified via the rootrc.

Also, if /tmp/ is not wanted, it could maybe be instead a user-config directory (https://github.com/root-project/root/issues/10148)

### Describe alternatives you've considered
Using
`gSystem->SetBuildDir("/tmp/");`
in my `rootlogon.C`.
But this does not solve the overwrite problem.

### Additional context
https://root.cern/doc/master/classTSystem.html#ae8790897e77f60ff37876b944f9f0091

**Comment by pcanal** [comment]
> gSystem->SetBuildDir("/tmp/");
> in my rootlogon.C.
> But this does not solve the overwrite problem.

Doesn't this case store the libraries in sub-directories?

**Comment by ferdymercury** [comment]
You are right, thanks, I had overlooked the isFlat argument.

**Comment by ferdymercury** [comment]
Is there a way to specify this in the .rootrc or only in the rootlogon ?

**Comment by pcanal** [comment]
Yes,
```
config/rootrc.in:#ACLiC.BuildDir:        /where/I/would/like/my/compiled/scripts
```

**Comment by ferdymercury** [comment]
Thanks!
