### ISSUE TITLE
Cling fails to find (or properly find) the dictionary symbols on PowerPC .. sometimes

### ISSUE THREAD

**Issue by pcanal** [root-project/root#10162]
Hi,

When compiling and attempting to run the Celeritas example (see https://github.com/celeritas-project/celeritas) with a build of ROOT v6.26/00 with gcc 11 we get the following errors:
```
Error in <TCling::RegisterModule>: Dictionary trigger function for libCore not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libMathCore not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libThread not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libRIO not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libNet not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libTree not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libceleritas_root not found
Error in <TClass::LoadClassInfo>: no interpreter information for class celeritas::ImportData is available even though it has a TClass initialization routine.
```
A simple use of root works fine (eg. simple.root is created just fine).  However loading the celeritas library:
```
root[0] .L path_to_celeritas_build/libceleritas_root.so
```
leads to a weird error about not find `path_to_root_installation/*bin*/libNet_rdict.pcm`.

We trace is down to the line in `TCling.cxx`:
```
   std::string dyLibName = cling::DynamicLibraryManager::getSymbolLocation(triggerFunc);
```
for `libNet` returning the name of executable (`blahblah/bin/root.exe`)

However loading the slightly simpler library `libceleritas.root` (which is used by `libceleritas_root.so`), works just fine.

**Comment by hahnjo** [comment]
As far as I can see, just from looking at the code, this is the fallback code path to return the binary's location if there is no shared library with that `triggerFunc`:
https://github.com/root-project/root/blob/a94fcb370110eb848010ce5853906d0baf28ac52/interpreter/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp#L1353-L1379

Do you have a standalone example where this happens that does not involve the entire Celeritas code base?

**Comment by hahnjo** [comment]
1. `libceleritas_root.so` doesn't exist anymore, I think that's now `libceleritas_io.so` since https://github.com/celeritas-project/celeritas/commit/4bafeac9f78bf4800d59c79b38f9be86e12e37f7
2. Both of them load just fine in a PowerPC build of ROOT.
3. When trying to run `app/loop-demo` with `testem3-flat.root`, I get (both on x86 and PowerPC)
```
Error in <TObjArray::At>: index 100 out of bounds (size: 100, this: 0x179fb60)
```

Since I didn't get a reply within a week to my first comment above, I'm going to remove the priority label.

**Comment by pcanal** [comment]
> As far as I can see, just from looking at the code, 

I assume it should be in the generated dictionary and not in the code, isn't it?

**Comment by pcanal** [comment]
> libceleritas_root.so doesn't exist anymore, I

yes, indeed, to explore this issue, one needs to use the previous commit.  (the new code is to work-around/avoid this blocking issue)

**Comment by pcanal** [comment]
> Do you have a standalone example where this happens that does not involve the entire Celeritas code base?

No and it seemed like the number of libraries and/or code size mattered.

> Both of them load just fine in a PowerPC build of ROOT.

Do you mean both the `older` libceleritas_root.so and the new one or something else?

> Both of them load just fine in a PowerPC build of ROOT.

If you can not reproduce the problem with the older library and with your PowerPC then we need compare more carefully the hardware/OS you have and the one @sethrj is using (part of the Summit HPC).

**Comment by hahnjo** [comment]
> > As far as I can see, just from looking at the code,
> 
> I assume it should be in the generated dictionary and not in the code, isn't it?

My comment was about where this error is likely introduced.

> > Both of them load just fine in a PowerPC build of ROOT.
> 
> Do you mean both the `older` libceleritas_root.so and the new one or something else?

I tested both current `master` and the commit before the refactoring. In both cases, `.L src/libceleritas_root.so` or `.L src/libceleritas_io.so` work without warnings or errors.

> 
> > Both of them load just fine in a PowerPC build of ROOT.
> 
> If you can not reproduce the problem with the older library and with your PowerPC then we need compare more carefully the hardware/OS you have and the one @sethrj is using (part of the Summit HPC).

For a start, I would suggest not using Spack but building yourself and being aware which flags are used.

**Comment by pcanal** [comment]
Which cmake flags did you use to build ROOT on that PowerPC.  Which PowerPC generation is it?

@sethrj Same questions :)

**Comment by hahnjo** [comment]
> Which cmake flags did you use to build ROOT on that PowerPC. Which PowerPC generation is it?

`cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release -Dtesting=ON -Droottest=ON` on (the Docker image of) AlmaLinux 8. The host is a PowerPC 8+ (Minsky) running CentOS 7.

**Comment by hahnjo** [comment]
> `'-Dcxxmodules:BOOL=OFF' [...] '-Druntime_cxxmodules:BOOL=OFF'`

This sticks out as suspicious... I have `runtime_cxxmodules=ON`, which is the default I think.

**Comment by sethrj** [comment]
What does that feature do? C++ modules are a new feature in C++20... or is this something different?

**Comment by hahnjo** [comment]
> `Error in <TObjArray::At>: index 100 out of bounds (size: 100, this: 0x179fb60)`

FWIW this is happening since commit b124f17f7a8da81415acd4bdb47a0fd6d4eef795 @pcanal

**Comment by pcanal** [comment]
It is something slightly different.  For the purpose of the C++ runtime introspection implemented by Cling, `runtime_cxxmodules=ON` switches from reading and parsing the header files are run-time to using the pre-compiled module (the technology eventually used to implement the C++ module of C++20) to provide a pre-parsed binary-form of those headers.  `runtime_cxxmodules=OFF` is essentially deprecated/on-it-way-out.

**Comment by pcanal** [comment]
> FWIW this is happening since commit https://github.com/root-project/root/commit/b124f17f7a8da81415acd4bdb47a0fd6d4eef795 @pcanal

Grr :) ... This is indeed work in progress :( .... I'll have to re-try this as soon as I fix the other issues ...

**Comment by hahnjo** [comment]
I cannot reproduce the problem with `runtime_cxxmodules=OFF` either (tested on x86 and PowerPC), so it has to be something else.

**Comment by hahnjo** [comment]
Adding a point that @pcanal mentioned during yesterday's meeting: As far as I understood, this only happens after some other libraries have been loaded? I tested `.L libceleritas_root.so` as the first action in a fresh `root` REPL, what else did you execute before that to make the error appear?

**Comment by pcanal** [comment]
@seth  Could you retry with the following two changes to the ROOT configuration:
```
12c12
< '-Dpch:BOOL=ON'
---
> '-Dpch:BOOL=OFF'
15c15
< '-Druntime_cxxmodules:BOOL=OFF'
---
> '-Druntime_cxxmodules:BOOL=ON'
```
because the new option are the new defaults and may affect the code path we saw.

**Comment by sethrj** [comment]
OK, I'll give that a shot—perhaps adding a "modules" variant for root 6.26+ that turns cxxmodules on and pch off? The current additional options are:
```
            define('cxxmodules', False),
            define('exceptions', True),
            define('explicitlink', True),
            define('fail-on-missing', True),
            define_from_variant('fortran'), # false
            define_from_variant('gminimal'), # true
            define('gnuinstall', False),
            define('libcxx', False),
            define('pch', True),
            define('roottest', False),
            define_from_variant('rpath'), # true
            define('runtime_cxxmodules', False),
            define('shared', True),
            define('soversion', True),
            define('testing', self.run_tests), # false
            define_from_variant('thread', 'threads'),
```

**Comment by pcanal** [comment]
> As far as I understood, this only happens after some other libraries have been loaded? I tested .L libceleritas_root.so as the first action in a fresh root REPL, what else did you execute before that to make the error appear?

Nothing else :).   The 'more' libraries comes from the fact that `libceleritas_root.so` is explicitly linked to many library and we tested that loading any and all those dependent libraries by themselves does not introduce any (noticeable) problems.

**Comment by sethrj** [comment]
Sorry @pcanal , I didn't get around to trying your suggestion until today. Building with configuration args:
```
-Dcxxmodules:BOOL=OFF -Dexceptions:BOOL=ON -Dexplicitlink:BOOL=ON -Dfail-on-missing:BOOL=ON -Dfortran:BOOL=OFF -Dgminimal:BOOL=ON -Dgnuinstall:BOOL=OFF -Dlibcxx:BOOL=OFF -Dpch:BOOL=OFF -Droottest:BOOL=OFF -Drpath:BOOL=ON -Druntime_cxxmodules:BOOL=ON -Dshared:BOOL=ON -Dsoversion:BOOL=ON -Dtesting:BOOL=OFF -Dthread:BOOL=ON -DCLING_CXX_PATH:STRING=g++ -Dbuiltin_afterimage:BOOL=OFF -Dbuiltin_cfitsio:BOOL=OFF -Dbuiltin_davix:BOOL=OFF -Dbuiltin_fftw3:BOOL=OFF -Dbuiltin_freetype:BOOL=OFF -Dbuiltin_ftgl:BOOL=OFF -Dbuiltin_gl2ps:BOOL=OFF -Dbuiltin_glew:BOOL=OFF -Dbuiltin_gsl:BOOL=OFF -Dbuiltin_llvm:BOOL=ON -Dbuiltin_lz4:BOOL=OFF -Dbuiltin_lzma:BOOL=OFF -Dbuiltin_nlohmannjson:BOOL=OFF -Dbuiltin_openssl:BOOL=OFF -Dbuiltin_pcre:BOOL=OFF -Dbuiltin_tbb:BOOL=OFF -Dbuiltin_unuran:BOOL=OFF -Dbuiltin_vc:BOOL=OFF -Dbuiltin_vdt:BOOL=OFF -Dbuiltin_veccore:BOOL=OFF -Dbuiltin_xrootd:BOOL=OFF -Dbuiltin_xxhash:BOOL=OFF -Dbuiltin_zlib:BOOL=OFF -Dafdsmrgd:BOOL=OFF -Dafs:BOOL=OFF -Dalien:BOOL=OFF -Darrow:BOOL=OFF -Dasimage:BOOL=ON -Dastiff:BOOL=ON -Dbonjour:BOOL=OFF -Dcastor:BOOL=OFF -Dccache:BOOL=OFF -Dchirp:BOOL=OFF -Dcling:BOOL=ON -Dcocoa:BOOL=OFF -Ddataframe:BOOL=ON -Ddavix:BOOL=OFF -Ddcache:BOOL=OFF -Dfftw3:BOOL=OFF -Dfitsio:BOOL=OFF -Dftgl:BOOL=OFF -Dgdml:BOOL=ON -Dgenvector:BOOL=OFF -Dgeocad:BOOL=OFF -Dgfal:BOOL=OFF -Dgl2ps:BOOL=OFF -Dglite:BOOL=OFF -Dglobus:BOOL=OFF -Dgsl_shared:BOOL=OFF -Dgviz:BOOL=OFF -Dhdfs:BOOL=OFF -Dhttp:BOOL=OFF -Dimt:BOOL=OFF -Djemalloc:BOOL=OFF -Dkrb5:BOOL=OFF -Dldap:BOOL=OFF -Dmathmore:BOOL=OFF -Dmemstat:BOOL=OFF -Dminimal:BOOL=OFF -Dminuit:BOOL=ON -Dminuit2:BOOL=ON -Dmlp:BOOL=OFF -Dmonalisa:BOOL=OFF -Dmysql:BOOL=OFF -Dodbc:BOOL=OFF -Dopengl:BOOL=OFF -Doracle:BOOL=OFF -Dpgsql:BOOL=OFF -Dpythia6:BOOL=OFF -Dpythia8:BOOL=OFF -Dqt:BOOL=OFF -Dqtgsi:BOOL=OFF -Dr:BOOL=OFF -Drfio:BOOL=OFF -Droofit:BOOL=ON -Droot7:BOOL=OFF -Druby:BOOL=OFF -Dsapdb:BOOL=OFF -Dshadowpw:BOOL=OFF -Dspectrum:BOOL=OFF -Dsqlite:BOOL=OFF -Dsrp:BOOL=OFF -Dssl:BOOL=OFF -Dtable:BOOL=OFF -Dtbb:BOOL=OFF -Dtcmalloc:BOOL=OFF -Dtmva:BOOL=OFF -Dunuran:BOOL=ON -Dvc:BOOL=OFF -Dvdt:BOOL=ON -Dveccore:BOOL=OFF -Dvmc:BOOL=OFF -Dwebui:BOOL=OFF -Dx11:BOOL=OFF -Dxft:BOOL=OFF -Dxml:BOOL=ON -Dxrootd:BOOL=OFF -Dpyroot:BOOL=ON -DCMAKE_CXX_STANDARD:STRING=17
```
I got the following warning when building Celeritas' root dictionary (possibly unimportant):
```
[1/4] Generating CeleritasRootInterface.cxx, libceleritas_io_rdict.pcm, libceleritas_io.rootmap
Disabling gnu++: clang has no __float128 support on this target!
Disabling gnu++: clang has no __float128 support on this target!
```
and at runtime:
```
info: Opening ROOT file at /ccs/home/s3j/.local/src/celeritas-summit/test/io/data/geant-exporter-data.root
Disabling gnu++: clang has no __float128 support on this target!
Error in <TCling::RegisterModule>: Dictionary trigger function for libCore not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libMathCore not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libThread not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libRIO not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libNet not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libTree not found
Error in <TCling::RegisterModule>: Dictionary trigger function for libceleritas_io not found
Error in <TClass::LoadClassInfo>: no interpreter information for class celeritas::ImportData is available even though it has a TClass initialization routine.
```

**Comment by sethrj** [comment]
We just tried to replicate this on Summit today using the same toolchain as before, using both the latest and an older version of Celeritas, and we weren't able to replicate the error... so I guess this can be closed?
