### ISSUE TITLE
[textinput] Undo buffer misses one entry in the actual sequence

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10182]
### Describe the bug
The undo shortcut in the prompt editor misses one entry in the sequence (I guess it is not added to the buffer)

### Expected behavior
Entries where ENTER are pressed are also added to the undo buffer.

### To Reproduce
```
root -l
root [0] int x
(int) 0
root [1] float y
(float) 0.00000f
// Start then pressing repeatedly CTRL+_
```
--> Neither `x` nor `y` are shown when undoing.

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 12 2022, 10:17:19                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
https://github.com/root-project/root/pull/10121

**Comment by jalopezg-r00t** [comment]
Actually, I think that the correct behavior should be to clear the undo history after accepting a new input line (which also follows what GNU-readline does).
