### ISSUE TITLE
? wildcard broken in TChain::Add()

### ISSUE THREAD

**Issue by jasondet** [root-project/root#10239]
The TChain::Add() documentation says

`Wildcard treatment is triggered by any of the special characters: []*? which may be used in the file name`

While `[]` and `*` work, I have found that `?` does not. Consider a script `chTest.C` containing the following:
`{` 
`  TChain* ch = new TChain("ch", "ch");`
`  ch->Add("file?.root");`
`  ch->GetEntry(0);`
`}`

Then run the following lines at the terminal:
` % touch file1.root`
` % touch file1.root`
` % root chtest.C`

The output is:
`root [0]`
`Processing chtest.C...`
`Error in <TFile::TFile>: file /Users/jasondet/Work/Coding/chtest/file does not exist`

Replacing the line `ch->Add("file?.root");` with `ch->Add("file*.root");` or `ch->Add("file[12].root");` gives expected file read errors, indicating that those wildcards are working correctly.

I'm using:
` % root --version`
`ROOT Version: 6.26/00`
`Built for macosx64 on Mar 03 2022, 06:51:13`
`From tags/v6-26-00@v6-26-00`

**Comment by dpiparo** [comment]
I added @jolly-chen in the loop. The internal method `[ROOT::Internal::TreeUtils::ExpandGlob](https://root.cern.ch/doc/master/namespaceROOT_1_1Internal_1_1TreeUtils.html#ad88089339eb9543b3e73479ae4fff483)(`  resolves well the globbing, however the `TChain::Add` method does not. To be investigated.

**Comment by jolly-chen** [comment]
It seems this is not working because the part after the `?` is interpreted as a query string. However, I'm not sure when the `?` should be treated as a wildcard and when it should be treated as a query starter. Should `?` only be treated as not a wildcard if the part after contains `=` characters for query parameters or a `#` for a tree name? In addition, some files can have `?` as part of the file name: what do we do in this case? This needs to be discussed before making changes

**Comment by dpiparo** [comment]
@pcanal would you agree to the strategy of @vepadulano which foresees a very pragmatic way out?

**Comment by pcanal** [comment]
>  In addition, some files can have ? as part of the file name

Technically we should support `\?` for that but if we don't for '*' or '[]' then we should not either for '?'

**Comment by pcanal** [comment]
> if the ? is followed exactly by .root or it is the last character in the string, then it's a wildcard

`file?suf.root` is a valid wildcard.  So I would probably say "if the ? is before the .root".
