### ISSUE TITLE
https://root.cern/install/: add --depth=20 to git clone commands

### ISSUE THREAD

**Issue by klenze** [root-project/root#10238]
There are three ways to get the code of latest-stable:
a) git clone as suggested by https://root.cern/install/: 1.4GiB
b) git clone with --depth=20: 673MiB
c) unpacking the zip file download from github: 477MiB

I think for 99% of the users, option a offers no benefits over option b. If you are testing or writing feature branches, it might not be worth figuring out how to fetch only the relevant parts (--shallow-exclude?). And if you were writing a paper on the history of ROOT, you will want the full version history. 

Option c has some serious downsides as well. github just calls the directory root-latest-stable, which is a lot less specific than what you would get from a versioned tarball. (Apparently, the version is in build/version_number). Furthermore, lack of a git repository is bad for anyone who might change stuff locally -- reunpacking the zip file and running diff -r is a lot less fun than using git diff. 

I would thus argue that option b is the way to go by default: it reduces the space requirements by some 53% while also retaining the ability to make changes and easily contribute them, should the need arise. 

Of course, many users will not care about space requirements as any --human-readable output not containing by the Si prefix P is considered small fries anyhow. But for grad students working on their own laptops, or anyone fetching root with limited bandwidth, the difference might still matter.

**Comment by eguiraud** [comment]
Hi @klenze ,
thank you for the feedback, I tend to agree, my only doubt is that these days we don't expect the vast majority of users to have to compile ROOT from source, that's something for developers and contributors, who might want to checkout the full repo anyway.
Why do grad students working on their laptops have to compile ROOT from source?

(with that said, I think we would accept a PR that changes the commands as you suggest. Or maybe we can just mention it in a comment. There is a button the bottom-right of each page on our website which opens a new tab where you can suggest changes)

**Comment by jalopezg-r00t** [comment]
Thanks for commenting @eguiraud!

@klenze, actually, if one is interested only in building from sources _once_, I would actually suggest `--depth=1`, which will create a shallow clone having only the latest commit in `latest-stable`.

However, keep in mind that a `$ git pull` on that branch will, by default, unshallow the repository (as each commit in `latest-stable` has a second parent pointing to the commit-ish that references the latest tree, which will pull that object chain).

**Comment by jalopezg-r00t** [comment]
@klenze are you up for creating a PR or should I?

**Comment by jalopezg-r00t** [comment]
Documentation has been updated accordingly.
