### ISSUE TITLE
`RBrowser` should support Safari

### ISSUE THREAD

**Issue by ntadej** [root-project/root#10260]
### Explain what you would like to see improved
Apple computers are quite popular in HEP and Safari is a good browser. It is not listed as supported for `RBrowser` but it seems to work mostly fine. For now I only spotted one issue.

### To Reproduce
1. Open a histogram in RBrowser.
2. Hover the mouse over the canvas.
3. `ROOT Canvas` tooltip will show.
<img width="216" alt="Screenshot 2022-03-29 at 10 42 05" src="https://user-images.githubusercontent.com/805384/160570961-4c408700-1e33-471f-9dca-dab29c71abcf.png">

### Setup
1. ROOT version:  6.26/00
2. Operating system: macOS 12.3
3. Browser: Safari 15.4
4. How you obtained ROOT: home-brew

**Comment by linev** [comment]
It is just title which does not normally handled in Safari. 
After #10344 it will be no longer showed.

Thanks for pointing this out!

**Comment by linev** [comment]
Should be fixed now in master branch
