### ISSUE TITLE
"Same" option not working in `RBrowser`

### ISSUE THREAD

**Issue by ntadej** [root-project/root#10265]
- [x] Checked for duplicates

### Describe the bug
In old `TBrowser` one could plot histograms with `hist same` to plot on the same canvas. This does not seem to work in `RBrowser`.

### Expected behavior
Histograms are plotted on the same canvas.

### To Reproduce
1. Open a file with 2 or more histograms in `RBrowser`.
2. Double click on one histogram to plot.
3. Change `TH1` plotting mode to `hist same`.
4. Double click another histogram.
5. They should both be shown on the same canvas, but they are not (also no axis are shown now).

**Comment by linev** [comment]
Yes, it is not supported up to now.
In #10344 I implement exactly this feature.
In the settings dialog one can specify flag "Append to canvas", which does exactly the same as "same" draw option.

Thanks for providing useful feedback!

**Comment by linev** [comment]
Should be working now in master
