### ISSUE TITLE
[RooFit] RooDataSet incorrectly loads RooCategory values from TTree branch of type Short_t

### ISSUE THREAD

**Issue by tcuisset** [root-project/root#10278]
### Describe the bug
When importing a TTree in a RooDataSet, if a RooCategory is filled from a tree branch of type Short_t, incorrect values are silently loaded. The category is always the same (it seems that it picks the first label in alphabetical order). The same problem appears for other types, only Int_t and UChar_t seem to work correctly.

### Expected behavior
Either correctly load the data set or fail with an error.

### To Reproduce
```
TTree* tree = new TTree("test_tree", "Test tree");
Short_t cat_in;
tree->Branch("cat", &cat_in);

cat_in = 2; //category B
tree->Fill();

RooCategory cat("cat", "Category",{
    {"B_cat", 2},
    {"A_cat", 3}
});
RooDataSet data("data", "RooDataSet", RooArgSet(cat), RooFit::Import(*tree));

data.table(cat)->Print("v");
```
We should get an event in category cat_B but instead we get an event in category cat_A

### Setup
Latest ROOT from git, master branch, commit 8d87e2bb6e6a
Linux

### Additional context
It seems to come from [RooAbsCategory::attachToTree](https://github.com/root-project/root/blob/943706c005c6723500e00061872d6eff4967d262/roofit/roofitcore/src/RooAbsCategory.cxx#L454) where there should probably be an error message if the type of branch is neither Int_t or UChar_t.

**Comment by guitargeek** [comment]
Hi, thanks for bringing up this issue! I have opened a PR to fix this for the upcoming ROOT release.

Would you benefit from backporting this fix to any existing ROOT release branch to be included in the next patch release, e.g. ROOT 6.26 or older?

**Comment by tcuisset** [comment]
No, that is not necessary (I already have an easy workaround), but thanks !
