### ISSUE TITLE
TAxis::ChangeLabel documentation

### ISSUE THREAD

**Issue by NJManganelli** [root-project/root#10279]
https://root.cern/doc/master/classTAxis.html#afc19787e727c9e3c85be72eba03338da

Currently this method's doxygen contains:
```
<p>Define new text attributes for the label number "labNum". </p>
<p>It allows to do a fine tuning of the labels. All the attributes can be changed, even the label text itself.</p>
<dl class="params"><dt>Parameters</dt><dd>
  

[in] | labNum | Number of the label to be changed, negative numbers start from the end
-- | -- | --
[in] | labAngle | New angle value
[in] | labSize | New size (0 erase the label)
[in] | labAlign | New alignment value
[in] | labColor | New label color
[in] | labFont | New label font
[in] | labText | New label text


  </dd>
</dl>
<p>If an attribute should not be changed just give the value "-1".</p>
<p>If labnum=0 the list of modified labels is reset. </p>
```

Things which can be improved:
A note that 'deleting' a label is accomplished via setting the label size to 0
A note that the empty string is the '-1'/'do not change' for the label itself. Although the author might have felt it was obvious being the default value, to someone looking to modify labels, they might actually try to use an empty string to delete the label.
A note that you cannot change label sizes or alignments or rotations one-by-one, only one value takes precedence (whether first or last, probably last I'd expect, since one might only modify a single bin). 

### Setup
1. ROOT version = master (March 30, 2022)
2. Operating system = CentOS7
3. How you obtained ROOT, such as `dnf install` / binary download / you built it yourself. = LCG release

**Comment by couet** [comment]
Thanks for your input. I agree with your two first notes. Although there is more information in [TGaxis](https://root.cern/doc/master/classTGaxis.html#a8ef5ba035d846add3902cd714336eaac) I think it is good to repeat the info in both helps. I do not understand your third note. Can you explain a bit more ? what do you mean by "one-by-one" ?

**Comment by NJManganelli** [comment]
Apologies for the brevity before. In my attempts to set the alignment differently on the first and last labels, I found only one value seemed to be set. On trying to make a minimal reproducer, I'm finding that for certain, changing the LabelFont is not working if all labels are not set correctly.

```
python
>>> import ROOT
>>> h = ROOT.TH1D("h", "", 5, 0, 5)
>>> for bin in range(h.GetXaxis().GetNbins()+1):
...   h.GetXaxis().ChangeLabel(bin, 10*bin, 4*bin, -1, -1, -1, "")
...
>>> h.Draw()
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
>>> h = ROOT.TH1D("h", "", 5, 0, 5)
for bin in range(11):
...   if bin < 2:
...     align = 11
...   elif bin > 7:
...     align = 12
...   else:
...     align = 13
...   h.GetXaxis().ChangeLabel(bin, 15*bin, .1, align, -1, 43, "")
...
>>> h.Draw()
```
Produced the attached axis, so the rotations are working, but a separate test suggests that alignments are not when the rotation is different than 0 (setting the rotation to 90 seems to produce identical alignment for all labels, as far as I can tell). Setting the pixel size to e.g. 10, of course, blows up those labels to greater-than-canvas size, they're being interpreted as fractions still. That is actually related to a problem I had a few days ago, accidentally passing fractional instead of integer (>1) values for size when the font precision is changed to absolute scale, but I'm not sure it's worth a warning or error message when it's being set.

So, separate from the documentation: what is the appropriate way to find the number of labels? Trying to use the TAxis::GetLabels() method didn't lead me anywhere, maybe there's a good example somewhere though
<img width="694" alt="ChangeLabels" src="https://user-images.githubusercontent.com/38217274/161010205-85424185-a64a-4829-992e-1982f16588d5.png">
?

**Comment by couet** [comment]
Thanks for the additional details. I will look at you example.
Back soon with a more extensive reply.

**Comment by couet** [comment]
I made a macro:
```
void changelabelangle() {
  auto h = new TH1D("h", "", 5, 0, 5);
   int align = 13;
   for (int bin = 1; bin <=11; bin++) {
      if (bin < 2) {
         align = 21;
      } else if (bin > 7) {
         align = 22;
      } else {
         align = 23;
      }
      h->GetXaxis()->ChangeLabel(bin, bin*5, -1, align, -1, 43, "");
   }
   h->Draw();
}
```
I get this . It seems correct for me.
<img width="622" alt="Screenshot 2022-03-31 at 10 56 04" src="https://user-images.githubusercontent.com/4697738/161017385-98e9d4a8-c06f-4a00-b908-18598b6ad09a.png">

Labels are optimized. One way to retrieve the number of labels after optimization is:
```
void number_of_labels() {
   double x1 = -0.123;
   double x2 = 5.87;
   auto h = new TH1D("h", "", 5, x1, x2);
   h->Draw();
   Int_t divxo = 0;
   Double_t x1o  = 0.;
   Double_t x2o = 0.;
   Double_t bwx = 0;
   THLimitsFinder::Optimize(x1, x2,10,x1o,x2o,divxo,bwx,"");
   printf("number of labels = %d\n",divxo+1);
}
```

**Comment by NJManganelli** [comment]
I think that still means that label sizes are not being correctly accounted for, with font precision 43 one should change from e.g. 0.1 label size to some number of pixels like 20, right? In this case, the pre-font-precision size is still there, whatever its value (unless the conversion is entirely implicit, which is... well... I need to use this to harmonize labels across adjacent pads that do not share the same heights/widths, so avoiding attempts to match the fontprecision 42 sizes on those is the purpose of going to precision 43).

For the alignment, that was my mistake, I thought it was 10*vAlign + hAlign, and that's wrong, so it's working as expected.

I'll see what I can do from python, that's going to involve a fair amount of wrapping and ctypes, it looks like. Also, is that only going to work once the axis has been added to the paint list with Draw()? i.e. return inapplicable/incorrect numbers of labels beforehand?

**Comment by couet** [comment]
Yes there is an issue with the font, it seems it does not work at all. Looking at it.

**Comment by NJManganelli** [comment]
For posterity, usage of ctypes to do try this from python, though I'm a bit uncertain about the divisions argument (is the GetNdivisions going to give the right number?)
```
import ctypes

def getNumberOfLabels(hist):

    # Setup ctypes for the original limits and divisions for the histogram
    xLow = ctypes.c_double(hist.GetXaxis().GetBinLowEdge(1))
    xHigh = ctypes.c_double(hist.GetXaxis().GetBinLowEdge(hist.GetXaxis().GetNbins()+1))
    xDivisions = hist.GetXaxis().GetNdivisions()

    # Setup ctypes to be optimized by THLimitsFinder::Optimize
    xLowOptimized = ctypes.c_double(0.)
    xHighOptimized = ctypes.c_double(0.)
    xDivisionsOptimized = ctypes.c_int(0)
    xBinWidthOptimized = ctypes.c_double(0.)

    # Run the optimization
    # Optimize (Double_t A1, Double_t A2, Int_t nold, Double_t &BinLow, Double_t &BinHigh, Int_t &nbins, Double_t &BWID, Option_t *option="")
    ROOT.THLimitsFinder.Optimize(xLow, xHigh, xDivisions, xLowOptimized, xHighOptimized, xDivisionsOptimized, xBinWidthOptimized, "")
    return int(xDivisionsOptimized.value)
```

**Comment by couet** [comment]
Yes GetNdivisions is ok

**Comment by NJManganelli** [comment]
I'm finding that this number of divisions is, unfortunately, not matching up in a more involved script (a minimal reproducer is not easy... converting to a .C file produces over 4k lines that have to be fixed by hand and then of course stripped of sensitive experiment-data, as there are errors in the conversion by ROOT). It seems that it thinks there are 75, when only 4 printed labels are ultimately made. I'm calling this Optimize after it's drawn, so I'm not sure where to go from here

**Comment by couet** [comment]
I think it is better to had a Method to TAxis. I will think of it.
Meanwhile I [fixed the "font bug" in ChangeLabel.](https://github.com/root-project/root/pull/10284) Thanks to have seen it.

**Comment by couet** [comment]
I am now trying to implement `TAttAxis::GEtNlabels()`

**Comment by couet** [comment]
The PR for GetNLabels is ready: https://github.com/root-project/root/pull/10286

**Comment by couet** [comment]
The help has been update with this PR: https://github.com/root-project/root/pull/10290 .
So I think all your requests have been addressed. Can i close this Issue ?

**Comment by NJManganelli** [comment]
Yes, the PyROOT version with the modulo and offset works almost perfectly (It does seem to be the case that the label at index 0 just doesn't exist, and the one at index 1 is the first to be drawn, but this finally helps me solve the plotting inconsistency, so it's a success in my book!)

Thanks Olivier!

```
import ROOT
import ctypes

def get_number_of_labels(hist):
    xLow = hist.GetXaxis().GetBinLowEdge(1)
    xHigh = hist.GetXaxis().GetBinLowEdge(hist.GetXaxis().GetNbins()+1)
    xDivisions = hist.GetXaxis().GetNdivisions() % 100

    if xDivisions < 0:
        return -xDivisions + 1

    # Setup ctypes to be optimized by THLimitsFinder::Optimize
    xLowOptimized = ctypes.c_double(0.)
    xHighOptimized = ctypes.c_double(0.)
    xDivisionsOptimized = ctypes.c_int(0)
    xBinWidthOptimized = ctypes.c_double(0.)

    # Run the optimization
    # Optimize (Double_t A1, Double_t A2, Int_t nold, Double_t &BinLow, Double_t &BinHigh, Int_t &nbins, Double_t &BWID, Option_t *option="")
    ROOT.THLimitsFinder.Optimize(xLow, xHigh, xDivisions, xLowOptimized, xHighOptimized, xDivisionsOptimized, xBinWidthOptimized, "")
    return int(xDivisionsOptimized.value % 100) + 1
```

**Comment by couet** [comment]
> (It does seem to be the case that the label at index 0 just doesn't exist, and the one at index 1 is the first to be drawn.

Yes the labels are numbered starting at 1. I think it is kind of obvious as it is said in the help that: _If labnum=0 the list of modified labels is reset._
