### ISSUE TITLE
[CMake] Imported targets improperly forwarded

### ISSUE THREAD

**Issue by cburgard** [root-project/root#10283]
It seems that the exported targets in ROOT 6.26 changed. Some software ([corryvreckan](https://gitlab.cern.ch/corryvreckan/corryvreckan)) that was compiling without issues in older root versions encounters issues when running cmake (3.22.3). 

I believe that this is related to missing exported CMake targets.

### Describe the bug

    CMake Error at src/core/CMakeLists.txt:73 (ADD_LIBRARY):
      Target "CorryvreckanCore" links to target "Threads::Threads" but the target
      was not found.  Perhaps a find_package() call is missing for an IMPORTED
      target, or an ALIAS target is missing?
    
    
    CMake Error at src/core/CMakeLists.txt:73 (ADD_LIBRARY):
      Target "CorryvreckanCore" links to target "OpenMP::OpenMP_CXX" but the
      target was not found.  Perhaps a find_package() call is missing for an
      IMPORTED target, or an ALIAS target is missing?
    
    
    CMake Error at src/core/CMakeLists.txt:73 (ADD_LIBRARY):
      Target "CorryvreckanCore" links to target "MPI::MPI_CXX" but the target was
      not found.  Perhaps a find_package() call is missing for an IMPORTED
      target, or an ALIAS target is missing?

The dependency seems to be pulled in via Minuit2. 

The following additions to the CMakeLists of the project fix the issue:

```
if(NOT TARGET Threads::Threads)
  find_package(Threads)
endif()
if(NOT TARGET MPI::MPI_CXX)
  find_package(MPI)
endif()
if(NOT TARGET OpenMP::OpenMP_CXX)
  find_package(OpenMP)
endif()
```

### Setup

Compiling from source. Tested in master and using 6.26/00. Using archlinux, using CMake 3.22.3.

The issue seems to only be present on archlinux, probably because for other OSs, the dependencies are handled internally rather than being imported (?).

**Comment by cburgard** [comment]
@bellenot could you take a look at this?

**Comment by bellenot** [comment]
@cburgard I will take a look (and maybe also @lmoneta). And to reproduce the issue I should try to build Corryvreckan with ROOT v6.26.00?

**Comment by ferdymercury** [comment]
@amadio mentioned a potential way to solve this issue on https://mattermost.web.cern.ch/root/pl/bnywusota3dq8mmo191j87bnke

**Comment by cburgard** [comment]
> @cburgard I will take a look (and maybe also @lmoneta ?). And to reproduce the issue should I try to build Corryvreckan with ROOT v6.26.00?

that would be ideal, I'm able to reproduce this issue with the corryvreckan master and the root arch docker container

**Comment by bellenot** [comment]
> that would be ideal, I'm able to reproduce this issue with the corryvreckan master and the root arch docker container

OK, then I'll try

**Comment by bellenot** [comment]
It looks more complicated that what I thought with missing dependencies. I'll need to create a dedicated VM not to mess-up the environment of our build nodes, so it will take a bit of time...

**Comment by cburgard** [comment]
Sorry to hear that, can't you use the containers you use to make the ROOT arch docker images as a baseline?

**Comment by bellenot** [comment]
@cburgard I managed to reproduce the problem, a fix should come soon
