### ISSUE TITLE
/bin/sh: 166: bin/thisroot.sh: Bad substitution

### ISSUE THREAD

**Issue by raistmer** [root-project/root#10298]
Building from "master" branch.
Attempting to setup like:
 . bin/thisroot.sh

Got
/bin/sh: 166: bin/thisroot.sh: Bad substitution

Line is: SOURCE=${BASH_ARGV[0]}

**Comment by Axel-Naumann** [comment]
What does `sh --version` show? Which operating system / distro / version is this?

**Comment by ferdymercury** [comment]
maybe related: https://stackoverflow.com/questions/69571809/why-does-the-variable-bash-argv-have-a-different-value-in-a-function-depending

**Comment by raistmer** [comment]
> What does `sh --version` show? Which operating system / distro / version is this?

cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

sh --version

sh: 0: Illegal option --

**Comment by ferdymercury** [comment]
try maybe:
`apt-cache policy dash`

**Comment by Axel-Naumann** [comment]
@raistmer Your `sh` is peculiar. What's the output of these commands:
```
which sh
sh --help
sh -V
man sh
```

**Comment by ferdymercury** [comment]
On Ubuntu 18, (Linux Mint), at least for me, sh is redirected to dash

`lrwxrwxrwx 1 root root 4 Sep 23  2018 /bin/sh -> dash`

On dash, neither neither --help nor -V exist.

`man dash` --> https://linux.die.net/man/1/dash

**Comment by Axel-Naumann** [comment]
Thanks - sorry, I missed this is `dash`. IIUC luckily Ubuntu switched away from `dash` as default shell...

I don't think there's much we can do here as `dash` really does not give access to the sourced filename.

I'd rather invest time in rendering thisroot.sh unneeded for the general use case.

**Comment by ferdymercury** [comment]
> how we can address this with `dash`.

Maybe, a more meaningful error message could be printed in thisroot.sh.
For example, check if BASH_ARGV[0] does not exist, then print "Please change to another shell".

**Comment by raistmer** [comment]
> @raistmer Your `sh` is peculiar. What's the output of these commands:
> 
> ```
> which sh
> sh --help
> sh -V
> man sh
> ```

For the sake of completeness

which sh
/bin/sh

 sh --help
sh: 0: Illegal option -- sh --help

 sh -V
no output, just return to the prompt

man sh
man: warning: /usr/share/man/man1/sh.1.gz is a dangling symlink
SH(1POSIX)                 POSIX Programmer's Manual                SH(1POSIX)
PROLOG
       This  manual  page is part of the POSIX Programmer's Manual.  The Linux
       implementation of this interface may differ (consult the  corresponding
       Linux  manual page for details of Linux behavior), or the interface may
       not be implemented on Linux.
NAME
       sh — shell, the standard command language interpreter
SYNOPSIS
       sh [−abCefhimnuvx] [−o option]... [+abCefhimnuvx] [+o option]...
           [command_file [argument...]]
       sh −c [−abCefhimnuvx] [−o option]... [+abCefhimnuvx] [+o option]...
           command_string [command_name [argument...]]
       sh −s [−abCefhimnuvx] [−o option]... [+abCefhimnuvx] [+o option]...
           [argument...]

(and so on)

Not sure is it dash or not 
It's result of:

%%html
<div id=term_demo></div>
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery.terminal/js/jquery.terminal.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/jquery.terminal/css/jquery.terminal.min.css" rel="stylesheet"/>
<script>
  $('#term_demo').terminal(async function(command) {
      if (command !== '') {
          try {
              let res = await google.colab.kernel.invokeFunction('shell', [command])
              let out = res.data['application/json'][0]
              this.echo(new String(out))
          } catch(e) {
              this.error(new String(e));
          }
      } else {
          this.echo('');
      }
  }, {
      greetings: 'Welcome to Colab Shell',
      name: 'colab_demo',
      height: 250,
      prompt: 'colab > '
  });

I would agree with [ferdymercury](https://github.com/ferdymercury) regarding possible diagnostic error improvement.

If nothing can be done no objections vs closing this issue.

**Comment by ferdymercury** [comment]
> Not sure is it dash or not

you can check via:
`ls /bin/sh -l`

**Comment by raistmer** [comment]
> > Not sure is it dash or not
> 
> you can check via: `ls /bin/sh -l`

So yes, it is dash:

ls /bin/sh -l
lrwxrwxrwx 1 root root 4 Nov 19  2020 /bin/sh -> dashls /bin/sh -l

**Comment by raistmer** [comment]
> I have found a workaround that makes it work in dash now. You can give it a try by copying by hand the added parts into your thisroot.sh : https://github.com/root-project/root/pull/10332/files

Thank you. After implementing your fix  got:

 . bin/thisroot.sh
/bin/sh: 1: bin/thisroot.sh: root-config: Permission denied

**Comment by ferdymercury** [comment]
> could this broke some permissions and how could I restore them

Maybe try to copy instead with `scp -p`
