### ISSUE TITLE
TColor::GetColorTransparent() does not re-use previously defined transparent colors

### ISSUE THREAD

**Issue by svenmenke** [root-project/root#10299]
- [x] Checked for duplicates

### Describe the bug

In TColor::GetColorTransparent() (see https://root.cern.ch/doc/master/classTColor.html#ae666674d7087b2b709abebde22667c50)
a new color is defined each time a transparent color (with alpha channel) is requested. In graphics applications with many transparent objects this leads quickly to exhausting the available index space of colors. At some point the int returned turns negative and the colors displayed are not what they should be. 

There does not seem to be a way to reset the entire color space in use by ROOT to simply start over. This would not fix the underlying problem but would at least provide a workaround.

### Expected behavior

The expected behavior is that transparent colors are re-used like any other color and no new color index is needed when requesting an already used transparent color again. 
### To Reproduce

type 
TColor::GetColorTransparent(1,0.1)
repeatedly on the commandline in ROOT. Each time the function is called a higher integer is returned even though the same transparent color is wanted.

### Setup

ROOT version: 6.24/06
OS: linux  (opensuse TW)
How obtained: self compiled

**Comment by ferdymercury** [comment]
A workaround might be to use:

[TColor](https://root.cern.ch/doc/master/classTColor.html) *color = new [TColor](https://root.cern.ch/doc/master/classTColor.html#ab0757deb31d7b7f33f23493a58a87f18)(ci, 0.1, 0.2, 0.3);

and store those pointers in a dictionary ?

**Comment by svenmenke** [comment]
Hi @ferdymercury,

the color in your example does not have an alpha channel ... but yes, the idea of caching the color indices created by TColor::GetColorTransparent() is probably a way of fixing this in ROOT (and in the meantime a workaround for users).
Since most methods of setting a color (like TAttLine::SetLineColor() take a color index instead of a pointer to an actual TColor object, storing the pointers would be less practical ... 
So here's what I am using currently:

` static int nColors=0;
  static std::vector<int> alphacolors;
  static bool isFirst=true;
  if ( isFirst ) {
    isFirst = false;
    nColors = gStyle->GetNumberOfColors();
    alphacolors.resize(nColors);
    for(int i=0;i<nColors;i++) {
      int icolor = gStyle->GetColorPalette(i);
      alphacolors[i]=TColor::GetColorTransparent(icolor,0.7);
    }
  }`

and then taking the members of alphacolors as arguments to SetLineColor() et al instead of using SetLineColorAlpha() ...

Thanks & Cheers,
--Sven

**Comment by couet** [comment]
I think `GetColorTransparent` can be extended and scan the defined colors to check if the requested color with the same transparency already exist.

**Comment by ferdymercury** [comment]
> the color in your example does not have an alpha channel ...

I just edited so that it has

**Comment by couet** [comment]
I made a PR to solve this issue. https://github.com/root-project/root/pull/10314
Thanks for reporting.

**Comment by svenmenke** [comment]
Thank you @couet!

**Comment by couet** [comment]
PR merged. Thanks for the report.
