### ISSUE TITLE
[Doxygen] tutorials appear as namespaces

### ISSUE THREAD

**Issue by couet** [root-project/root#10317]
See: https://root.cern/doc/master/namespaces.html
The python tutorials appear as name spaces.

**This is a doxygen BUG**
An issue was created on doxygen repo: https://github.com/doxygen/doxygen/issues/9250

**Comment by dpiparo** [comment]
someone posted in December last year https://github.com/doxygen/doxygen/issues/9250#issuecomment-1868173316 . Perhaps we can do something about this now?

**Comment by dpiparo** [comment]
Did it work?

**Comment by couet** [comment]
Nope, but another trick was mentioned in the oxygen issue with FILTER_PATTERNS

**Comment by ferdymercury** [comment]
Btw the doc-build-job seems stuck: https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-master/3242/

**Comment by couet** [comment]
> Btw the doc-build-job seems stuck: https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-master/3242/

Build relaunched

**Comment by ferdymercury** [comment]
In the meanwhile, I think the following workaround/hack could be useful and not too much work:

- Generate the documentation
- Run a bash-script that analyzes the file https://root.cern/doc/master/namespaces.html
- Loop over the lines of this file
- "Grep" the linked href file: if the contents section is empty, this means it's a Python script, so remove the line from the namespaces.html file and overwrite the result.

(Python script contain this section here empty: `<div class="contents">\n</div><!-- contents -->`), so just grepping could work.

**Comment by couet** [comment]
Indeed it sounds a good way... let me investigate
