### ISSUE TITLE
Root Primer Figures not displaying

### ISSUE THREAD

**Issue by swissarthurfreeman** [root-project/root#10346]
Hello,

Following the root primer tutorials, the figures are not being properly 
displayed.

https://root.cern/primer/#motivation-and-introduction

![image](https://user-images.githubusercontent.com/53379583/162026759-3b0a3760-a4b1-4021-bc67-a7482719b391.png)

Inspecting element yields just an empty div. 
```
<div id="canvasesmultigraph" style="width:100%; height:350px">
</div>
```

**Comment by couet** [comment]
Thank for reporting. I'll check

**Comment by couet** [comment]
Indeed the figure are included in the primer using [this script](https://github.com/root-project/web/blob/main/_includes/figure_jsroot) based on jsroot. It might be that jsroot interface has changed. Let me ask @linev. Note that all the figures in the Manual also disappeared: https://root.cern/manual/graphs/#drawing-a-graph that's normal are they are included the same way.

**Comment by linev** [comment]
Problem was due to recent changes in JSROOT.
Should be working now.

**Comment by couet** [comment]
Yes the figures are back. thanks !

**Comment by swissarthurfreeman** [comment]
Dear All,

Thank you for your quick action and reply.
The figures appear to be rendering correctly
now.

Best,

A. Freeman
