### ISSUE TITLE
Solution to fix Windows WSL CMake error.

### ISSUE THREAD

**Issue by TomsonEinstein** [root-project/root#10381]
- [ ] Checked for duplicates

### Describe the bug

When you try to use CMake to build root in Windows newest WSL2(System:ubuntu20.04LTS),a problem will emerge.It says that 

/root/core/base/src/TSystem.cxx:44:10: fatal error: compiledata.h: No such file or directory
   44 | #include "compiledata.h"

### Expected behavior

There must be no error when l build root using CMake.
### To Reproduce

I have already succeeded in solving this problem.In folder(whether it is master or 6.26.00)"/root/core/base/inc",the expected headfile "compiledata.h" is missing.If you copy the existing files in root which is built before to this folder,the error disappears.
### Setup

1.ROOT version:I copy master to root folder instead of using the existing root 6.26.00 which is already built.
2.Operating System:Newest Windows 11;WSL2 Ubuntu 20.04 LTS
3.I am building newest root myself when I encounter this error and solve it myself.

### Additional context

I do not know whether the error is caused by mistake in project itself or my attempt to build root myself using master.But adding a headfile to that folder really solves my problem well,and maybe there exists a mistake.And I also think that adding a headfile to the folder mentioned before is harmless.

**Comment by gregoryfdel** [comment]
I was also getting issues with building inside WSL2 where XRootD was trying to compile with __declspec. This went away after I changed the PATH environment variable inside the WSL2 Ubuntu instance to exclude all of the windows populated paths and only include the Ubuntu paths. This leads me to believe that OS detection is broken by WSL2 and headers which shouldn't be included in Ubuntu compilations are getting included.
