### ISSUE TITLE
`RBrowser` does not list in-memory objects when written objects are present in `TDirectory` context

### ISSUE THREAD

**Issue by olifre** [root-project/root#10389]
### Describe the bug
Opening a file containing data (e.g. a `TTree`) and creating histograms in memory afterwards, finally opening a new-style `TBrowser`, the in-memory histograms are not accessible from the browser. 

### Expected behavior
Histograms can either be accessed in `root => ROOT Memory` or (as in the old-style `TBrowser`) in the list below the file (even if not yet written out), since they were created in the context of the file's `TDirectory`. 

### To Reproduce
Using ROOT 6.26.00 (or switching to the web-GUI via other ways) and executing the following macro:
```
{
        TFile *f = new TFile("bar.root", "RECREATE");
        TTree *foobar = new TTree("t", "t");
        foobar->Write();
        TH1D *foo = new TH1D("foo", "foo", 10, 0, 10);
        new TBrowser();
}
```
reproduces the behaviour: The tree `t` is visible in the browser, but the histogram `foo` is not. 

`.ls` shows (as expected):
```
root [1] .ls
TFile**         bar.root
 TFile*         bar.root
  OBJ: TTree    t       t : 0 at: 0x5617aee19b60
  OBJ: TH1D     foo     foo : 0 at: 0x5617afef9650
  KEY: TTree    t;1     t
```
The old `TBrowser` shows both objects. 

Either not writing out the `TTree` or writing out the histogram makes it visible. 

However, this breaks the use case of reading in a file with a `TTree` and creating histograms in-memory, then inspecting them via a `TBrowser`. 
(arguably, users should care about the `TDirectory` context...)

### Setup
1. ROOT version: 6.26.00
2. Operating system: Gentoo Linux
3. ROOT built via package manager :wink:

**Comment by linev** [comment]
Now both objects and keys from `TDirectory` listed in the `RBrowser`.
