### ISSUE TITLE
Cling crash on valid c++ code (stack variable pointer).

### ISSUE THREAD

**Issue by shangjiaxuan** [root-project/root#10386]
### Describe the bug
The following code when run with the interpreter crashes (on the line with std::seed_seq). Names are with underscore to avoid clashes.
```
constexpr uint32_t seed_bits = 19937;
constexpr uint32_t seed_32_count = 19937 / 32 + bool(19937 % 32);

std::random_device _dev;
uint32_t _seed[seed_32_count];
for (uint32_t i = 0; i < seed_32_count; ++i) {
	_seed[i] = _dev();
}
std::seed_seq _seq(_seed, _seed + seed_32_count);
```

This may be related to handling of stack variables. (Calling alloca will also crash the interpreter, but that is a corner case, I suppose.)

### Expected behavior
Initialize a seed sequence for use with `std::mt19937` (`TRandom3` should suffice? But that doesn't give the whole seed vector).

### To Reproduce
Input the above line by line into interpreter. Also note that writing `_seed` to see a pointer or content on the last line will also crash the interpreter. 

### Setup
ROOT 32 bit 6.26
Windows (Not yet tested on linux).
Binary install.

### Additional context
Should be sufficient here.

**Comment by shangjiaxuan** [comment]
`alloca` in the current version return only `nullptr`, which seems to be a reasonable workaround.

**Comment by shangjiaxuan** [comment]
A current workaround would be to use std::array instead of a raw array.

**Comment by bellenot** [comment]
It looks like the issue has been fixed in the master. Can you try with [root_v6.27.01.win32.vc16.zip](https://root.cern/download/nightly/root_v6.27.01.win32.vc16.zip)? It works for me:
```
C:\Users\bellenot\rootdev>root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for win32 on Apr 19 2022, 03:07:00                         |
  | From remotes/origin/master@v6-25-02-1027-g2aa0235                |
  | With MSVC 19.29.30141.0                                          |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] constexpr uint32_t seed_bits = 19937;
root [1] constexpr uint32_t seed_32_count = 19937 / 32 + bool(19937 % 32);
root [2]
root [2] std::random_device _dev;
root [3] uint32_t _seed[seed_32_count];
root [4] for (uint32_t i = 0; i < seed_32_count; ++i) {
root (cont'ed, cancel with .@) [5]  _seed[i] = _dev();
root (cont'ed, cancel with .@) [6]}
root [7] std::seed_seq _seq(_seed, _seed + seed_32_count);
root [8]
```

**Comment by shangjiaxuan** [comment]
Master branch has this fixed. Closing issue.
