### ISSUE TITLE
[RF] verbose printout of some RooFit classes broken

### ISSUE THREAD

**Issue by cburgard** [root-project/root#10385]
- [ ] Checked for duplicates

### Describe the bug

Using the `Print("v")` option causes a segfault for a few RooFit classes.

### Expected behavior

The printout happens.

### To Reproduce

Take a HistFactory made workspace, select a `FlexibleInterpVar` or a `RooProduct` and call `Print("v")`.

### Setup

current master, compiled on archlinux

### Additional context

The crash always happens in the `Proxies` section, possibly related to the `RooListProxy` rewrite by @hageboeck

**Comment by guitargeek** [comment]
Indeed I was able to reproduce this problem with the workspace produced by the histfactory tutorial as follows:
```C++
#include <RooAbsReal.h>
#include <RooWorkspace.h>

#include <TFile.h>

void crash() {

    TFile f{"example_UsingC_channel1_meas_model.root"};

    auto * channel1 = f.Get<RooWorkspace>("channel1");

    channel1->function("background1_channel1_scaleFactors")->Print("v");
}
```
