### ISSUE TITLE
[core] CleanCompiledMacros behavior

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10395]
### Explain what you would like to see improved
Following https://mattermost.web.cern.ch/root/pl/k6amdch7bfdm5d8isiguo4i5re
there were a number of things detected wrt the behaviour of `TSystem::CleanCompiledMacros`

### Optional: share how it could be improved
- [ ] In the doxygen documentation of `TSystem::CompileMacro`, it should be stated that the default behavior is to remove libraries after closing ROOT. Right now you only learn about this behaviour if you look closely at the `k` flag.
- [ ] Mention also in the doxygen documentation that, in contrast, even if functions do the same, the default behavior of `.L script.C+` is the opposite one, to leave things after closing, without removing. In other words, that `.L` always passes the `k` option behind the scenes.
- [ ] `TSystem::CleanCompiledMacros` should also remove also the `.d` and `.pcm`, not just the `.so`
- [ ] On Windows, `CleanCompiledMacros` should work, too, right now it does not. (Can not delete a "in-use file" and technically the code of `CleanCompiledMacros` should be updated to first unload the library.)

### To Reproduce
See reproducer at https://mattermost.web.cern.ch/root/pl/k6amdch7bfdm5d8isiguo4i5re

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 12 2022, 10:17:19                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

**Comment by ferdymercury** [comment]
@couet The first two points are documentation improvements
The fourth point maybe @bellenot knows how?

**Comment by dpiparo** [comment]
I would propose a strategy for this item:
1. We document better the method
2. We remove pcms and other files
3. We warn that on Win it does not work (it is my understanding it cannot because one cannot delete files which are in use - but perhaps I am wrong here)
Does it make sense?

**Comment by bellenot** [comment]
For the record: I tried to unload the DLL in `CleanCompiledMacros `, but that make several test crashing, so it needs more investigations
