### ISSUE TITLE
[ntuple] Re-allow type-erased reading

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#10408]
[This commit](https://github.com/root-project/root/commit/48bb3f69e0a7ab3641a5f10a189d89b214e0fb18#diff-1b09d441e22aa3d48c645df3c0ee3e713e400e82c58983e106fd58c6bfdb4d6fR184-R185) broke the following usecase by changing the return type of `RNTupleModel::GetField` from a non-const RFieldBase to a const RFieldBase.

```cpp
auto r = RNTupleReader::Open("r", fileGuard.GetPath());
const RFieldBase *rvecf = r->GetModel()->GetField("v");
// ERROR: GenerateValue is non-const, rvecf is a const pointer
auto rvecv = rvecf->GenerateValue();
ROOT::RVec<int> *v = rvecv.Get<ROOT::RVec<int>>();
```

Before that commit, the above snippet was valid code, and there is no simple alternative.

As per a discussion with @jblomer , the preferred solution would be to also make `RFieldBase::{GenerateValue,CaptureValue,DestroyValue}` const. However,

> reading an entry needs to be fixed up  in this case. Because currently, LoadEntry iterates over the RFieldValues and calls Read on their associated fields. RField::Read() is non-const because a new page may need to be mapped in

**Comment by jblomer** [comment]
Type-erased reading should work via the default entry (or new entries) of the reader's generated model. Like this

    auto r = RNTupleReader::Open("r", fileGuard.GetPath());
    auto v = r->GetModel()->Get<ROOT::RVec<int>>("v");
    r->LoadEntry(0);
    // v now points to an RVec with the data of field v in event 0

**Comment by eguiraud** [comment]
Here: https://github.com/root-project/root/pull/8770/files#diff-4fd6702ec1ca6f9b7321ba54d27cb888b3d227b7555ec01de46a7bec9b717d6dR137-R172

I'm basically trying to defer the time I have to specify the column type as much as possible, for writing and reading.
My actual goal here is to trigger I/O via the generic `RRVecField` instead of the specialized `RField<RVec<T>>`. In general my understanding is that RNTuple wants to provide type-erased APIs for I/O of arbitrary types and I thought that was it, but I might be missing something.

**Comment by eguiraud** [comment]
> I see, in this case, you can go with the code snippet I pasted above.

Alright, thank you! I guess I'm missing a manual or a cheat-sheet that shows what the different ways to read an RNTuple are. As a beginner user it seems that there are many ways in which I can mix up different ways to do things incorrectly.

**Comment by jblomer** [comment]
Appears expired with the latest interface changes. Please reopen if necessary.
