### ISSUE TITLE
thisroot.sh fails to identify shellname when running from executable script

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10417]
### Describe the bug
As found out by @couet, when running thisroot.sh on jenkins for building the docu (https://github.com/root-project/rootspi/blob/master/rdoc/makedoxy.sh#L38), the shell name is not properly found (probably bash?), it gets mixed by thinking that makedoxy.sh is an executable (trueExe=makedoxy.sh). That same function works otherwise well outside Jenkins with dash, bash or zsh.

This is because makedoxy.sh is run as an executable, rather than 'sourced', see https://github.com/root-project/rootspi/blob/5b8d1747ccd9a093322fbdc268cff960f2c1159d/rdoc/makedoc.sh#L57

```
+++ getTrueShellExeName
+++ local trueExe nextTarget
++++ ps -o comm= 2106668
+++ trueExe=makedoxy.sh
+++ '[' makedoxy.sh = makedoxy.sh ']'
+++ '[' makedoxy.sh '!=' makedoxy.sh ']'
++++ '[' -n '' ']'
++++ which makedoxy.sh
+++ trueExe=
++++ readlink ''
+++ nextTarget=
++++ basename ''
+++ printf %s ''
++ SHELLNAME=
```

### Expected behavior
It works also within Jenkins.

### To Reproduce
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-master/2650/console

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 12 2022, 10:17:19                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
It worked well until dash support was added. https://github.com/root-project/root/commit/d96ea9fb8f5b66bf95d7324de09c8a167b97a6c8

**Comment by couet** [comment]
The PR fixes the problem: https://lcgapp-services.cern.ch/root-jenkins/job/root-makedoc-master/2651/console
