### ISSUE TITLE
ROOT fails to compile on a fast mac

### ISSUE THREAD

**Issue by ktf** [root-project/root#10410]
On a M1 Max mac, ROOT fails to compile due to the fact it spawns too many processes too fast to copy the headers, going over the 256 file descriptors limit which is default on macOS. Changing ulimit via `ulimit -n 1024` fixes the issue, however it would be good to have some proper throttling, since the failure is really ambiguous.

**Comment by Axel-Naumann** [comment]
How do you build? GNU make or ninja?

**Comment by ktf** [comment]
make

**Comment by dpiparo** [comment]
I could not reproduce it on a M2 mac with 12 cores in several months: was this perhaps already addressed?

**Comment by ktf** [comment]
We switched to use ninja, so I cannot tell.
