### ISSUE TITLE
Recursion limits hit in pruning/serialisation of distributed RDF graph

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#10449]
# Original bug

The RDataFrame graph defined by the user in the local application is translated into a series of node objects. Each object stores a list of references to its children. When sending the tasks to a distributed scheduler, the head node of the graph is serialised (through pickle), and all its children are serialised with it (and their children, recursively).

This behaviour leads to recursion limits hit by pickle after a certain amount of operations is requested, I could reproduce it with 200 operations:

```python
import ROOT
RDataFrame = ROOT.RDF.Experimental.Distributed.Dask.RDataFrame

from dask.distributed import Client, LocalCluster

def many_defines(df):
# Maximum recursion depth exceeded at 200 iterations
    for i in range(200):
        df = df.Define(f"col_{i}", f"{i}")

    print(f"Total entries: {df.Count().GetValue()}")

if __name__ == "__main__":
    cluster = LocalCluster(n_workers=2, threads_per_worker=1, processes=True)
    client = Client(cluster)
    df = RDataFrame(100, daskclient=client)
    many_defines(df)
```
Which raises the following
```
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.
```

# Update

Fixing just the serialisation issue of the reproducer above unveiled another limitation of the current implementation. The distrdf graph locally needs to be pruned before being sent to the distributed scheduler. The pruning algorithm is also a recursive function, which by default have a limit of 1000 calls in Python. The reproducer above, when run with `990` Define nodes in the `many_defines` function, returns
```
$:  python test_many_defines.py
  File "/home/vpadulan/programs/rootproject/rootbuild/distrdf-percentage-ranges-distrdf-debug/lib/DistRDF/Node.py", line 177, in graph_prune
    if not n.graph_prune():
  [Previous line repeated 988 more times]
  RecursionError: maximum recursion depth exceeded
```

### Expected behavior

No error, as with local RDF:

```python
import ROOT

def many_defines(df):
    for i in range(1000):
        df = df.Define(f"col_{i}", f"{i}")
    print(f"Total entries: {df.Count().GetValue()}")

if __name__ == "__main__":
    df = ROOT.RDataFrame(100)
    many_defines(df)
```
```
$: python rdf_many_defines.py 
Total entries: 100
```

### Setup
Fedora 35
ROOT >= 6.26

**Comment by NJManganelli** [comment]
Just going to comment on the side:
I ran into I think the same issue with the old PyRDF prototype for distributed execution pretty easily when I was prototyping an analysis workflow ~2.5 years ago (presuming it's the same basic issue in cloudpickle)
My current analysis has, for some extreme workflows (i.e. zero intermediate datasets - almost complete end-to-end analysis, corrections to histograms), thousands of define and filter calls. Just to say 'yes, there are people out there (AB)using the system sufficiently to hit this limitation in the real world.' That is an extreme case, and the median is ~1/4 of that, and switching from 1D histograms to 3D histograms also reduces that by a large factor. Nevertheless, that's still past a limit of 200 fairly easily.

**Comment by vepadulano** [comment]
Indeed, I can imagine a real analysis needs quite more than 200, or even 1000 nodes. You'll be happy to know that we're merging the linked PR with a fix today :smile:
