### ISSUE TITLE
clang-format should not run on linkdef files

### ISSUE THREAD

**Issue by jblomer** [root-project/root#10448]
As discussed in #10336, `clang-format` does not work well on linkdef files. It may be best to skip them.

**Comment by guitargeek** [comment]
Clang-format has no inherent mechanism to skip specific files. It's the job of the script that selects the files to do this. In fact, this is already done in the CI:
https://github.com/root-project/root/blob/master/.ci/format_script.sh#L6

Locally, it's the job of the developer to make sure you don't run `clang-format` on the LinkDefs.

If you just want to conveniently grep all files and pipe them to `clang-format`, you can surround the LinkDef.h with `// clang-format off` and `// clang-format on` to make sure it's not getting formatted.
