### ISSUE TITLE
Weightfield2 5.3 not work

### ISSUE THREAD

**Issue by roany1** [root-project/root#10472]
- [ ] Checked for duplicates

### Setup
binary download

### Additional context
 creat with Weightfield2 5.2 or 5.3 

[bug weightfield53.txt](https://github.com/root-project/root/files/8573132/bug.weightfield53.txt)

**Comment by etejedor** [comment]
Hello, could you give more details about what you are executing to see that crash?

**Comment by bellenot** [comment]
@roany1 Since this doesn't look related to ROOT, you can maybe contact the Weightfield2 people or open a topic on the [ROOT forum](https://root-forum.cern.ch/)
