### ISSUE TITLE
openssl 3.0 support in xrootd

### ISSUE THREAD

**Issue by Zeff020** [root-project/root#10496]
### Explain what you would like to see improved

Ubuntu 22.04 was released recently and by default it ships with openssl 3.0. Since ROOT does not support this currently (as far as I understand) compilation with the newest Ubuntu (and derived OS such as pop!OS) out of the box fails. 

### Optional: share how it could be improved

I fixed this locally by setting "-DWITH_OPENSSL3=TRUE" in line 46 of root/builtins/xrootd/CMakeLists.txt. Ideally the user would have an option to set this version as a compiler flag directly when compiling ROOT, not within a CMAKE file. 

### To Reproduce

I can reproduce by compiling master branch root with Pop!OS 22.04

### Extra

I would be happy to create a pull request with the suggested improvement, but I can also imagine that more stuff needs to be changed in multiple places that I cannot foresee currently. Let me know if the suggested fix seems sufficient and I can open a pull request with it.

**Comment by ferdymercury** [comment]
Related: https://github.com/root-project/root/pull/10322

**Comment by Zeff020** [comment]
That is in fact exactly what I was referring to. I guess I was not using the latest master branch. Thanks!
