### ISSUE TITLE
Failure to build master branch due to xrootd SHA256 checksum mismatch

### ISSUE THREAD

**Issue by Zeff020** [root-project/root#10503]
- [x] Checked for duplicates

### Describe the bug

I currently cannot build the master branch due to the fact that the hardcoded SHA256 checksum in /builtins/xrootd/CMakeLists.txt is not the same checksum as the one obtained when downloading the file. There is a mismatch. There is a check that makes the build fail in this case.

### Expected behavior

The checksum in /builtins/xrootd/CMakeLists.txt is the same as the one obtained from the actually downloaded file

### To Reproduce

```
git clone https://github.com/root-project/root.git
mkdir build
cd build
cmake ../root/  -Droofit_multiprocess=ON -Dminuit2=ON -Dtesting=ON -DCMAKE_IGNORE_PATH="/home/zef/miniconda3/bin;/home/zef/miniconda3/include;/home/zef/miniconda3/lib" -Dccache=ON -DPYTHON_EXECUTABLE="/usr/bin/python3" -Dbuiltin_fftw3=On
```

Note that the checksum obtained by `sha256sum xrootd-5.4.2.tar.gz` is: 2b394270c55cb3d14f3c44b692311db99d2d25278882b513d4d564b68a58ed4a

The checksum hardcoded in the CMAKE file is: 84e8a9a2bcad116df479f94e985c287dd99fbac0613d4fbb61f4ccc0cef81fa3

### Setup

ROOT version: master branch as of now
Operating system: Pop!OS
Obtained root through git clone of master branch

**Comment by Axel-Naumann** [comment]
See also https://github.com/root-project/root/pull/10585
