### ISSUE TITLE
Build ROOT 6.24/06a or 6.24/08

### ISSUE THREAD

**Issue by elmsheus** [root-project/root#10515]
### Is your feature request related to a problem? Please describe.
As discussed in https://sft.its.cern.ch/jira/browse/SPI-2149 ATLAS would like to have a ROOT patch release 6.24/06a with the fix/patch for https://github.com/root-project/root/pull/10369. 

If this is not feasible can ROOT 6.24/08 be releases soon ? But due to the imminent data taking start we'd like avoid potential interferences due to other patches that might come with 6.24/08.

### Describe the solution you'd like

Release 6.24/06a

### Describe alternatives you've considered

Release 6.24/08

### Additional context

See https://sft.its.cern.ch/jira/browse/SPI-2149 for more details and the discussion with the CERN SFT SPI team experts.

Cheers, Johannes (for ATLAS)

**Comment by Axel-Naumann** [comment]
We should be able to tag still this week, possibly even tomorrow.

**Comment by krasznaa** [comment]
Hi Axel,

Do you mean `v6-24-06a` or `v6-24-08`? I would just like to stress once more that we would much prefer to get a `v6-24-06a` tag, if at all possible. Could you comment on that part of the question?

Cheers,
        Attila

**Comment by Axel-Naumann** [comment]
I missed that you dislike our releases ;-) Can you explain why? In principle a release has only advantages, such as a version check for cpp macros. And obviously a release has a tag.

**Comment by krasznaa** [comment]
What are you talking about?!?

We would like a release called v6-24-06a that is v6-24-06 with just the one update pointed out by Johannes. You could choose a different name as well. We only care about the content of the tag, not its name.

ROOT often created "special tags" in the past. Or would you for instance not call https://github.com/root-project/root/releases/tag/v6-01-03-CMS a release? 😕 

If the version macros of v6-24-06a declare the release to be v6-24-06, then so be it. I really don't care. But you could potentially come up with something better even for that.

**Comment by Axel-Naumann** [comment]
So your argument for a tag is that you can reduce the amount of commits. Thanks, we can certainly do that; I will let you know once it's there. (Just to state the probably obvious: the tag will still be on the v6-24-00-patches branch and thus contain commits prior to the ones pointed out by Johannes.)

**Comment by krasznaa** [comment]
> EDIT: just to make this explicit, the difference is marginal, one commit out of many, but since you seem totally convinced that you know what you want you will get your tag. I still find the rationale hard to understand.

Why is that? Is it really such an outlandish request for you to make a special branch/tag for us? I didn't appreciate that Git would make that difficult. :confused:

We will be using this version of ROOT as a drop-in patch at Point-1. With a lot of code that is using ROOT, not being re-compiled. So yes, we want to minimise the changes. And https://github.com/root-project/root/compare/v6-24-06...v6-24-00-patches is **not** a small amount of changes.

As you can see in https://sft.its.cern.ch/jira/browse/SPI-2149, it's not off the table that we would build a special LCG release with a hand-applied patch on top of v6-24-06 in case we can't convince you guys to make a tag for us. But that, unlike what we ask here, would indeed be a quite ugly solution.

**Comment by Axel-Naumann** [comment]
We have never created a branch off a release branch for a certain commit; our CI etc is not capable of handling this. If you want this please just apply the commits you need. Please note that this is not a version of ROOT that is tested, there might be interference with other commits that you would miss.

The release branch contains several fixes that are likely relevant also to ATLAS.

I can offer you a tag right after the commit Johannes mentioned, or a speedy patch release. Let me know, please.

**Comment by elmsheus** [comment]
Axel and I had a very quick chat:
* The preferred option for ATLAS is to have 6.24/06a which contains just the fix/commit for https://github.com/root-project/root/pull/10369 - Axel warns us that will not be tested at all at and that is his main worry - we did not conclude if this could done by the ROOT team or if this could be handled directly on top LCG build by the SPI team ?
* As a backup solution in addition we could get a full 6.24/08 release will all the commits/fixes since the ROOT 6.24/06 release.

**Comment by Axel-Naumann** [comment]
* Please talk to SPI to get a patched version of ROOT.
* I'm in the process of releasing 6.24/08.

**Comment by andresailer** [comment]
We, SPI, installed a patched version of 6.24.06 for ATLAS. I think this ticket can be closed.

**Comment by Axel-Naumann** [comment]
Thanks. And once I'm back in business we'll get 6.24/08 out the door.
