### ISSUE TITLE
v6-26-02 fails to build with XROOTD download hash mismatch

### ISSUE THREAD

**Issue by cgleggett** [root-project/root#10527]
Building ROOT with gcc 11.2.0 on a centos7 system with the following configuration:

cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_EXTENSIONS=Off -DCMAKE_INSTALL_PREFIX=/opt/root/v6-26-02_gc112_c17 -GNinja ../src

fails with the following error:
```
[2542/9705] Performing download step (download, verify and extract) for 'XROOTD'
FAILED: builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-download /bld6/root/bld/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-download 
cd /bld6/root/bld/builtins/xrootd/XROOTD-prefix/src && /bld4/opt/cmake/3.22.2/bin/cmake -P /bld6/root/bld/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-download-Release.cmake && /bld4/opt/cmake/3.22.2/bin/cmake -E touch /bld6/root/bld/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-download
CMake Error at XROOTD-stamp/XROOTD-download-Release.cmake:49 (message):
  Command failed: 1

   '/bld4/opt/cmake/3.22.2/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/bld6/root/bld/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-download-Release-impl.cmake'

```

attached are the XROOTD-download-err.log  and XROOTD-download-out.log
[XROOTD-download-err.log](https://github.com/root-project/root/files/8624870/XROOTD-download-err.log)
[XROOTD-download-out.log](https://github.com/root-project/root/files/8624872/XROOTD-download-out.log)

**Comment by ferdymercury** [comment]
Related: https://github.com/root-project/root/pull/10511 https://github.com/root-project/root/issues/10503

**Comment by bellenot** [comment]
Hi, this has been fixed in the master and v6-26-00-patches branches

**Comment by Axel-Naumann** [comment]
See also https://github.com/root-project/root/pull/10585
