### ISSUE TITLE
While running TMVA why I a getting an empty ROC plot.

### ISSUE THREAD

**Issue by Siddharth-IOP** [root-project/root#10533]
- [ ] Checked for duplicates

**Comment by bellenot** [comment]
Can you fill the missing bullets:
 - describe the bug
 - expected behavior
 - to reproduce
 - setup
 - additional context

**Comment by lmoneta** [comment]
Please post first in the ROOT Forum (https://root-forum.cern.ch) the problem and add a reproducer ?
It could be not a ROOT issue but a problem in the code. If we are sure that the problem is in the ROOT code then we can open a GitHub issue
Thank you!
