### ISSUE TITLE
6.26.02 doesn't build Netx component

### ISSUE THREAD

**Issue by telzhov** [root-project/root#10539]
- [x] Checked for duplicates

### Description

Files TXNetFile.h, TXNetFileStager.h, and TXNetSystem.h are missing in pre-built ROOT v6.26.02 from downloads.

Then I tried to build ROOT from both 6.24.06 and 6.26.02 git tags using exactly the same CMake flags and found that TXNetFile.h and two others are missing in 6.26.02 again.

### Expected behavior
The files enumerated above should be included in the pre-build ROOT archive, and also should be build and installed by `make install`

### To Reproduce
Download 6.26.02 release from https://root.cern/install/all_releases/ then call (all files are attached below)

`tar tzf root_v6.26.02.Linux-ubuntu20-x86_64-gcc9.4.tar.gz root/include | grep /TXNet`

it prints nothing

### Setup
1. ROOT version: 6.26.02
2. Operating system: Ubuntu 20
3. How you obtained ROOT: binary download and also built it

### Additional context

you may also notice that the headers list for 6.26.02 is considerably shorter:
```
$ wc -l root-v6.24.06-headers.txt root-v6.26.02-headers.txt
  2970 root-v6.24.06-headers.txt
  2840 root-v6.26.02-headers.txt
```
Headers included in 6.24.06 but missing in 6.26.02:
```
$ diff -u root-v6.24.06-headers.txt root-v6.26.02-headers.txt > root-headers-diff.txt
$ grep -c '^-\./' root-headers-diff.txt 
238
```
Headers missing in 6.24.06 but included in 6.26.02:
```
$ grep -c '^+\./' root-headers-diff.txt 
108
```
Thank you!
### Attachments
[root-v6.24.06-headers.txt](https://github.com/root-project/root/files/8646800/root-v6.24.06-headers.txt)
[root-v6.26.02-headers.txt](https://github.com/root-project/root/files/8646801/root-v6.26.02-headers.txt)
[root-headers-diff.txt](https://github.com/root-project/root/files/8646803/root-headers-diff.txt)

**Comment by bellenot** [comment]
@telzhov  so netx is for old versions of xrootd. With more recent versions, nexng is used (check for `TNetXNGFile.h`, `TNetXNGFileStager.h`, and `TNetXNGSystem.h`)
