### ISSUE TITLE
TTreeReader does not handle properly entry ranges where `beginEntry==endEntry`

### ISSUE THREAD

**Issue by ikabadzhov** [root-project/root#10540]
Consider the following minimal reproducer
```cpp
#include <ROOT/RDataFrame.hxx>
#include<TSystem.h>

using namespace ROOT;
using namespace ROOT::RDF;

int main() {
   auto dfWriter = RDataFrame(5).Define("x", [](ULong64_t e) { return int(e) + 10; }, {"rdfentry_"});
   dfWriter.Snapshot<int>("mytree", "myfile.root", {"x"});

   TFile *myFile = TFile::Open("myfile.root");
   TTreeReader myReader("mytree", myFile);
   myReader.SetEntriesRange(2, 2);                             // supposed to return empty tree

   TTreeReaderValue<int> x(myReader, "x");

   while (myReader.Next()) {                                         // supposed not to loop at all
      std::cout << *x << std::endl;
   }
}
```
The following reproducer gives a tree with elements 12, 13, 14, i.e. as if the range was (2,5). However, empty range is explicitly requested, and hence is supposed to give an empty tree.

Fyi: @vepadulano @eguiraud

**Comment by eguiraud** [comment]
This behavior is unfortunate (I'd go as far as to say it is wrong), but I am afraid TTreeReader is working as per its specification. From the docs of SetEntriesRange:

> If end <= begin, `end` is ignored (set to `-1`, i.e. will run on all entries from `begin` onwards).

As this has been the user-facing behavior for many years, I think there is little change to change it now. So if we want a different behavior for RDF+RDatasetSpec we have to implement it at the level of RDF.

cc: @pcanal @Axel-Naumann

**Comment by Axel-Naumann** [comment]
...or have a new interface in `TTreeReader` that behaves in a saner way.
