### ISSUE TITLE
[TMVA][SOFIE]Generated headers are missing include guards

### ISSUE THREAD

**Issue by swertz** [root-project/root#10586]
- [x] Checked for duplicates

### Describe the bug

SOFIE-converted models written out as `.hxx` header files do not have include guards. This causes problems when potentially loading the same model more than once, e.g. when creating several RDF graphs to process different samples in the same process.
While it is easy to add header guards manually (passing `#ifndef ...\n#define...\n#include...\n#endif` to `gInterpreter.Declare`), it would more user-friendly if they were directly included in the generated headers.

### To Reproduce
E.g. in [this tutorial](https://root.cern.ch/doc/master/TMVA__SOFIE__RDataFrame_8py.html), run `ROOT.gInterpreter.Declare('#include "' + generatedFile + '"')` twice.

### Setup

1. ROOT version: `master`
2. Operating system: CentOS7
3. How you obtained ROOT: LCG dev3 nightly

### Additional context

I'm happy to try to make a PR with a fix if you think it makes sense.

**Comment by lmoneta** [comment]
A PR is available now, please let me know if you would like this to be back ported to the 6.26 branch
