### ISSUE TITLE
Scatter plot combining Color Size and Alpha

### ISSUE THREAD

**Issue by couet** [root-project/root#10608]
Continuing the matplotib investigation, I found out there is a kind of scatter plot ROOT cannot do in a straight forward way.
The matplotlib script is:

```
import matplotlib.pyplot as plt
import numpy as np

x = np.random.randint(100, size=(100))
y = np.random.randint(100, size=(100))
colors = np.random.randint(100, size=(100))
sizes = 10 * np.random.randint(100, size=(100))

plt.scatter(x, y, c=colors, s=sizes, alpha=0.5, cmap='nipy_spectral')

plt.colorbar()

plt.show()
```

And it gives this plot:

<img width="538" alt="Screenshot 2022-05-18 at 17 19 17" src="https://user-images.githubusercontent.com/4697738/169078428-c311e8b2-3dd5-46ee-b079-74529cb2fc6d.png">

With ROOT it can be done with an ad-hoc macro but that's quite some programming. Therefore I made a prototype of a new class inheriting from TGraph: TScatter.

The script is:

```
void scatter()
{
   const int n = 100;
   double x[n];
   double y[n];
   double c[n];
   double s[n];

   // Define four random data set
   auto r  = new TRandom();
   for (int i=0; i<n; i++) {
      x[i] = 100*r->Rndm(i);
      y[i] = 100*r->Rndm(i);
      c[i] = 900*r->Rndm(i);
      s[i] = 1000*r->Rndm(i);
   }

   auto scat = new TScatter(n, x, y, c, s);
   scat->Draw();
}
```
And it gives:
<img width="693" alt="Screenshot 2022-05-18 at 17 21 53" src="https://user-images.githubusercontent.com/4697738/169079349-e0958d09-1091-4049-8cf3-6cdb4dec6e82.png">

Do you think that might be interesting to have ? @ferdymercury ? @lmoneta ? @linev ?

**Comment by couet** [comment]
Thanks for your input ! the plot you show do not vary the size of the marker. The plot I proposed in a 4 variables plot : x,y,c and s. I agree that's not urgent but that's also not too difficult to implement. I first did a macro emulating that plot then imported in a a new class. This new class needs some clean up to be delivered. That's why I am asking some input before going further. Also, going to mathplotlib is an option but you get the matplotlib style (see the axis for instance). If you want this kind of plot with the ROOT style then you need a dedicated way to do it in ROOT.

**Comment by ferdymercury** [comment]
(Yes, I had a variant that was also changing sizes, but it got too messy, so I drew it with fixed sizes.)

Your ROOT-style plot looks great to me. Can the border of all circles be controled via `scat->SetLineSize` and `scat->SetLineColor` ?

**Comment by couet** [comment]
> Can the border of all circles be controled via scat->SetLineSize and scat->SetLineColor ?

As I said it is a prototype. I do not want to invest to much time if we decide we do not need it. But yes that can be added.

**Comment by linev** [comment]
Some implementation question - 
if this class has X/Y coordinates (plus colors and sizes), should this class be derived from `TGraph`?
And looking on [matplotlib.scatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html) - one could use different markers.

**Comment by couet** [comment]
Now I implemented it this way, yes, derived from TGraph. It is a bit like TGraphErrors which also add two vectors to the initial TGraph. I do not see any other class from which to derive. TGraph can already draw scatter plot but not with size and color. Yes different markers is also a possibility no problem with that. We can even think to map a 5th variable on the marker style. The implantation in TGraphPainter is also convenient.

**Comment by lmoneta** [comment]
Looks nice, it would be nice to have it in ROOT. 
It would not be better to define it as a TGraph3D class ? 
In any case I am not sure if inheriting from TGraph is really needed.

**Comment by couet** [comment]
TGraph3D .... Well why not. But then that will imply we can draw x y and Z in 3D then we get two more variables mapped on color and size and we can end up with a TGraph4D . The inheritance from TGraph makes it very easy to implement as we have all the painter machinery available. The idea was to introduce a better implementation of what is called in the literature a "scatter plot". We do not have this concept in root. The scatter plot for histograms is a misleading disaster as we know ....

**Comment by linev** [comment]
> The scatter plot for histograms is a misleading disaster as we know ....

Real problem is that it is default drawing option for `TH2`

**Comment by couet** [comment]
> Real problem is that it is default drawing option for TH2

Yes, the real problem is that it exists !

**Comment by couet** [comment]
Introducing the new scatter plot might be also a good opportune to completely remove this misleading 2d histogram scatter pot....

**Comment by lmoneta** [comment]
I agree, we should remove it as the default option for drawing TH2 objects. 
If we have the TScatter class, if I have just two vector x and y, would then use this class to draw the scatter plot or TGraph ?

**Comment by couet** [comment]
> If we have the TScatter class, if I have just two vector x and y, would then use this class to draw the scatter plot or TGraph ?

Yes of course. in TScatter the  color and the size are optional. Is they both are null then that's a normal Scatter with only x and y. The nest level is x y and color the next one (presented here) is x y col and size and we can even think of x y col size and type.

**Comment by couet** [comment]
> I agree, we should remove it as the default option for drawing TH2 objects.

I would be even more drastic and remove it completely ... it is a real non sense.

**Comment by couet** [comment]
The new class TScatter is in ROOT.
