### ISSUE TITLE
RDataframe merging branches in the computation graph

### ISSUE THREAD

**Issue by riley-x** [root-project/root#10620]
### Is your feature request related to a problem? Please describe.
I have a dataset with "truth" and "reco" values, though not every event has both set of values. I define new variables respectively, for example
```cxx
truth = df.Filter(has_truth, ...).
           Define("truth_computation", expensive_computation_truth, ...);
reco = df.Filter(has_reco, ...).
           Define("reco_computation", expensive_computation_reco, ...);
```
I use both these dataframes to plot respective histograms. But then I'd also like to plot a 2D histogram that compares the values of `truth_computation` and `reco_computation` when both exist.

### Describe the solution you'd like
Ideally, one could then write something like
```cxx
both = ROOT::RDF::Intersection(truth, reco);
both.Histo2D(..., {"truth_computation", "reco_computation"});
```
Here, `both` consists of events that pass both filters, and has access to all definitions from both branches.

### Describe alternatives you've considered
I can calculate both quantities in the beginning
```cxx
pre = df.Filter(has_truth || has_reco, ...).
         Define("truth_computation", expensive_computation_truth, ...).
         Define("reco_computation", expensive_computation_reco, ...);
truth = pre.Filter(has_truth, ...);
reco = pre.Filter(has_reco, ...);
both = reco.Filter(has_truth, ...);
```
but this will
1. call the filters `has_truth` and `has_reco` extra times, which may be expensive
2. try to calculate reco quantities for truth events and vice versa, though this is probably not too bad if `expensive_computation_truth` can no-op on reco events and vice versa, but that's not always possible

**Comment by eguiraud** [comment]
Hi @riley-x ,
if there are no columns that appear/disappear between truth and reco this should work:

```cpp
auto df2 = df.Define("has_reco", has_reco, ...)
             .Define("has_truth", has_truth, ...)
             .Define("truth_computation", ...) // this is run lazily, as needed
             .Define("reco_computation", ...) // this is also run lazily
auto h_truth = df2.Filter("has_truth").Histo1D("truth_computation");
auto h_reco = df2.Filter("has_reco").Histo1D("reco_computation");
auto h_both = df2.Filter("has_reco && has_truth").Histo2D("truth_computation", "reco_computation")
```

**Comment by riley-x** [comment]
@eguiraud Thanks, that makes sense. Just to make sure I understand, the lazy evaluation means that the ordering between a call to `Define` and to `Filter` is irrelevant? Whereas the ordering between two `Filter`s is still relevant, since they're evaluated in order. I think taking advantage of the lazy evaluation covers all the use cases I imagined, so I'll close this.
