### ISSUE TITLE
[TTreeReader] Cannot read Float16_t branch

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#10645]
Reproducer:

```cpp
#include <TFile.h>
#include <TTreeReader.h>

int main() {
  {
    TFile f("f16.root", "recreate");
    TTree t("t", "t");
    float x = 42.f;
    t.Branch("x", &x, "x/f");
    t.Fill();
    f.Write();
  }

  {
    TFile f("f16.root");
    TTreeReader r("t", &f);
    TTreeReaderValue<Float16_t> rv(r, "x");
    r.Next();
  }
}
```

produces

```
Error in <TTreeReaderValueBase::CreateProxy()>: The branch x contains data of type Float16_t, which does not have a dictionary.
```

**Comment by Pawan-Johnson** [comment]
The same issue exists for the Double32_t data type.
```cpp
#include <TFile.h>
#include <TTreeReader.h>

int main() {
  {
    TFile f("d32.root", "recreate");
    TTree t("t", "t");
    double x = 42.;
    t.Branch("x", &x, "x/d");
    t.Fill();
    f.Write();
  }

  {
    TFile f("d32.root");
    TTreeReader r("t", &f);
    TTreeReaderValue<Double32_t> rv(r, "x");
    r.Next();
  }
  return 0;
}
```

Error produced:
```
Error in <TTreeReaderValueBase::CreateProxy()>: The branch x contains data of type Double32_t, which does not have a dictionary.
```

**Comment by Triple-S** [comment]
Some additional information on this: I also experienced this bug and found out that it is due to the types Float16_t and Double32_t missing in TDataType. I tried to add them there which fixes the issue, but results in an issue with the TStreamerInfo Compilation which I myself did not understand and therefore could not fix. Also see the corresponding PR: https://github.com/root-project/root/pull/9008

**Comment by eguiraud** [comment]
@Triple-S this issue should be fixed in `master`, `v6-26-00-patches` and `v6-24-00-patches`, is that not the case for you?

**Comment by Triple-S** [comment]
> @Triple-S this issue should be fixed in `master`, `v6-26-00-patches` and `v6-24-00-patches`, is that not the case for you?

@pcanal Has pointed me to the PR which implemented the fix https://github.com/root-project/root/pull/11261. I was just confused because this PR was neither mentioned nor connected to this issue which is why I thought this would still be an open issue, so nevermind my comment.
