### ISSUE TITLE
RAdoptAllocator uses deprecated type aliases

### ISSUE THREAD

**Issue by beojan** [root-project/root#10654]
`RAdoptAllocator` uses a number of `std::allocator` member type aliases which are [deprecated in C++ 17](https://en.cppreference.com/w/cpp/memory/allocator) and removed in C++ 20, namely
- `pointer`
- `const_pointer`
- `reference`
- `const_reference`

#8150 which migrated other parts of the implementation to `std::allocator_traits` didn't include these.

**Comment by eguiraud** [comment]
Hi @beojan , RAdoptAllocator has been removed from ROOT in v6.26.
