### ISSUE TITLE
TH2::SetShowProjectionXY

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10660]
### Is your feature request related to a problem? Please describe.
When working with TH2 histograms, it is very common to right-click on the canvas and use SetShowProjectionX or SetShowProjectionY.

There are cases where one needs to see both of these at the same time.

### Describe the solution you'd like
A function which plots the two projections at the same time, once a rectangular window has been defined.
Ideally, one should be able to add more (gdirectory-open) TH2s to the 'buffer' via a Combo, as it is very useful to compare several 2D images by looking at their 1D projections.
one of the projections could be rotated by 90deg, if needed, to make it fit with 2D axis orientation.

### Describe alternatives you've considered
I programmed back then this tool: https://root-forum.cern.ch/t/th2-x-y-projection-interactive-viewer/26335
but it would be nice if it were adopted by ROOT, and be accesible by the context menu of the TCanvas.

### Additional context
https://stackoverflow.com/questions/40641895/plot-aligned-x-y-1d-histograms-from-projected-2d-histogram
https://www.astrobetter.com/blog/2014/02/10/visualization-fun-with-python-2d-histogram-with-1d-histograms-on-axes/

**Comment by ferdymercury** [comment]
Thanks. Would such a PR be likely to be accepted? I programmed other things involving histograms two years ago and did not get feedback / revision (https://github.com/root-project/root/pull/8546) thus I am not sure if I should embark in new PRs at the moment, until the others are solved.

**Comment by couet** [comment]
The PR you are referring to had quite a lot of interactions seems to me. It is a histogram related and Lorenzo is the person to ping. Regarding this new functionality you are requesting, you produced a tool. Seems to me that's enough for now. May be @lmoneta can comment if it is something we want to be built in?

**Comment by ferdymercury** [comment]
Just lovely :)

**Comment by linev** [comment]
Implemented for `TWebCanvas` with #12534
