### ISSUE TITLE
GettingStarted thisroot misleading

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#10722]
### Explain what you would like to see improved
The Getting Started Guide is a bit misleading concerning the usage of thisroot.sh
https://github.com/root-project/root/blob/87a998d48803bc207288d90038e60ff148827664/documentation/users-guide/GettingStarted.md

### Optional: share how it could be improved
- Either add a 'watermark' on top saying "Users Guide is deprecated, check instead XYZ"
- Or remove the part about export ROOTSYS...
- Or make it very clear on top that the recommended thing is to use thisroot.sh, and then only below as 'backup' the manual variant.

### Additional context
See here: https://root-forum.cern.ch/t/syntax-error-in-thisroot-csh-during-installation/50312/4?u=ferhue

**Comment by couet** [comment]
And "Solaris" "HP-UX" "AIX"... do we want to keep those ???

**Comment by couet** [comment]
That's the user's guide... it is deprecated ... you should not use it.

**Comment by ferdymercury** [comment]
> That's the user's guide... it is deprecated ... you should not use it.

Hi, I am not using it, but forum users are doing, see https://root-forum.cern.ch/t/syntax-error-in-thisroot-csh-during-installation/50312/4?u=ferhue

So my suggestion is to put a big label on top informing anyone that it is deprecated.

The results still appear when googling, so it seems useful to add somrle deprecated mark

**Comment by ferdymercury** [comment]
> By the way, from the new ROOT website, I do not see what is the clicks-series leading to the Old Users Guide.

Yes, it seems the problem arises mainly when googling. The first two results lead you to the deprecated users guide.

![image](https://user-images.githubusercontent.com/10653970/172875715-28ccea27-c989-4658-80e8-7ef7bcb437ea.png)

**Comment by couet** [comment]
> Yes, it seems the problem arises mainly when googling. The first two results lead you to the deprecated users guide.
We need to watermark them in that case.

**Comment by couet** [comment]
The pr #10888 put a warning on each manual, chapter etc ...
