### ISSUE TITLE
[ntuple] Implement a collection proxy class

### ISSUE THREAD

**Issue by jalopezg-git** [root-project/root#10739]
### Explain what you would like to see improved
Implement a (templated) class that proxies access to STL collections.  A major difference w.r.t. `TVirtualCollectionProxy` is that template specializations will be provided to avoid going through `TClass` in case the type is known at compile-time.

This is a requirement for #10326, and enabling RField support for other STL collections.

**Comment by pcanal** [comment]
Please see: https://github.com/root-project/root/blob/07f313ed32a34dee2d9f381500fa18848fe164ce/core/cont/inc/TCollectionProxyInfo.h  which already contains essentially that.   Those templates contains the accelerator functions used to build the CollectionProxy.

**Comment by jblomer** [comment]
Closing for now.
