### ISSUE TITLE
`RBrowser` attempts and fails to launch `TBrowser` despite `--web=server:xxxx`

### ISSUE THREAD

**Issue by Moelf** [root-project/root#10748]
ssh'ed without `--Y` or `--X`

```
$ root --version
ROOT Version: 6.26/04
Built for linuxx8664gcc on Jun 07 2022, 16:01:16
From tags/v6-26-04@v6-26-04


$ root -l --web=server:8899
root [0] TBrowser()
Warning in <TBrowser::TBrowser>: The ROOT browser cannot run in batch mode
```

is this a known bug / fixed already? a quick search didn't yield anything.

**Comment by eguiraud** [comment]
Hi @Moelf , I think `-X` or `-Y` is required to use graphics. Do things work if you specify those options?

**Comment by linev** [comment]
Unfortunately, `TBrowser` does not work in batch mode.
But one can directly start `RBrowser` like:
```
root -l --web=server:8899 $ROOTSYS/tutorials/v7/browser.cxx
```

**Comment by linev** [comment]
It is old logic that `TBrowser` does not starts without `DISAPLAY` variable set or simply in batch mode.
One can solve this, but with some fine-tuning in "normal" `TBrowser`/`TBrowserImp` classes.
If @bellenot has nothing against it - I can propose PR.

**Comment by bellenot** [comment]
> It is old logic that `TBrowser` does not starts without `DISAPLAY` variable set or simply in batch mode. One can solve this, but with some fine-tuning in "normal" `TBrowser`/`TBrowserImp` classes. If @bellenot has nothing against it - I can propose PR.

Thanks @linev ! Feel free to open a PR if you want 😃

**Comment by linev** [comment]
@bellenot - here it is: https://github.com/root-project/root/pull/10783

**Comment by linev** [comment]
Mentioned PR will allow to run TBrowser in batch mode if `--web=server:port` argument will be used to start ROOT.
Only such combination makes sense to use browser in batch.
