### ISSUE TITLE
Error in REveBox.cxx while building root 6.26.04

### ISSUE THREAD

**Issue by catselbow** [root-project/root#10814]
- [x] Checked for duplicates

### Describe the bug
When building root 6.26/04 with  gcc 11.2.1 the build process fails while compiling REveBox.cxx:

   [ 89%] Building CXX object graf3d/eve7/CMakeFiles/ROOTEve.dir/src/REveBox.cxx.o
  In file included from /usr/src/root-6.26.04/graf3d/eve7/src/REveBox.cxx:18:
  /usr/include/nlohmann/json.hpp:847:7: error: redeclared with 9 template parameters
    847 | class basic_json;
        |       ^~~~~~~~~~

This is under CentOS 7, using devtoolset-11 and cmake3 (3.17.5).

### Expected behavior
It should compile without errors.

### To Reproduce

 wget https://root.cern/download/root_v6.26.04.source.tar.gz
 tar xzvf root_v6.26.04.source.tar.gz
 cd root-6.26.04
 cd build
 scl enable devtoolset-11 bash
 cmake3 ..
 make >& make.log

### Setup
root 6.26.04
CentOS 7, devtoolset-11 (gcc 11.2.1), cmake3 (3.17.5)
Building from source (https://root.cern/download/root_v6.26.04.source.tar.gz)

**Comment by catselbow** [comment]
I seem to have found the problem.  The system had an older version of json.hpp (version 3.6.1) installed, and the root build was trying to use that instead of the json.hpp (version 3.9.1) that was bundled with the root source.   Moving the installed file out of the way and replacing it with the version from the root source allowed me to build root.  (So far, it doesn't appear to have broken anything else.)

**Comment by linev** [comment]
I propose to set minimal version number when searching external nlohmann to 3.9 

https://github.com/root-project/root/pull/10817

I hope it should solve the problem

**Comment by eguiraud** [comment]
Thank you @linev , assigning this issue to you then, to close when the PR is merged.

@catselbow it's surprising (but a welcome surprise) to hear that compiling ROOT with devtoolset works for you, thank you for following up.

**Comment by catselbow** [comment]
> Ah, about devtoolset @Axel-Naumann points out that "Compiling should not be a problem. But interpreting anything that needs e.g. a move constructor will cause a missing symbol."

Is that with devtoolset-11 or with some other version?  Is there a minimal example that illustrates the problem?

**Comment by eguiraud** [comment]
> Is that with devtoolset-11 or with some other version?

We don't really track this as it's not a supported toolchain, so I don't know, sorry

> Is there a minimal example that illustrates the problem?

There are some instances of problems on the forum, see https://root-forum.cern.ch/search?q=devtoolset
