### ISSUE TITLE
Don't let classes with a non-zero `ClassDef` version compile if they have no IO constructor

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#10824]
Recently, we accidentally introduced a bug into RooFit when removing the IO constructor of `RooBernstein`, and we brought it back months later: https://github.com/root-project/root/pull/10816.

It's unexpected that a class with a `ClassDef` version greater than zero (meaning that it's clearly intended for IO) can even compile without an IO constructor, essentially breaking it for IO!

Could we add some checks at compile time to make sure that any class with a non-zero `ClassDef` version has an IO constructor implemented?

**Comment by pcanal** [comment]
I think we can make it a Warning but it is legal to have a ClassDef with non-zero class version and no I/O constructor.  For the example that particular class might be used only as a nested member of another class (hence the I/O never need to constructor directly that type of object).

**Comment by guitargeek** [comment]
Ah okay I see! Okay then it should not be a compile error, but indeed a warning would be very appreciated :+1:

**Comment by guitargeek** [comment]
I don't need this anymore at this point, it's been a long time since I forgot the IO constructor for the last time :slightly_smiling_face:
