### ISSUE TITLE
SaveGraph producing unclear results, when the TChain has no name

### ISSUE THREAD

**Issue by ikabadzhov** [root-project/root#10928]
If the underlying TChain has no name (""), then the output of SaveGraph is far from helpful.
The following script:
```cpp
#include<ROOT/RDataFrame.hxx>
#include<ROOT/RDFHelpers.hxx>
#include<TSystem.h>

using namespace ROOT;

int main(){
  ROOT::RDataFrame(1).Define("x", "42").Snapshot("t", "f.root");

  TChain ch("");
  ch.Add("f.root?#t");
  RDataFrame df(ch);
  auto df2 = df.Count();
  ROOT::RDF::SaveGraph(df, "res.dot");
  gSystem->Exec("dot -Tpng res.dot -o img_res.png");

  //df.Describe().Print();
}
```
Produces:
![img_res](https://user-images.githubusercontent.com/46775299/177795165-da210d75-b4c7-4e42-a66c-6a6bd233c105.png)

Example solution: if the chain has no name => call the source node `TChain with no name`.

(Remark, same comment is applicable for the `Describe()` action. The commented line would produce `Dataframe from TChain  in file f.root [...]`. Notice the 2 spaces after "TChain".)

CC: @eguiraud @vepadulano

**Comment by ikabadzhov** [comment]
I just took a quick look. Is there a mechanism to distinguish between TTree and TChain?

**Comment by ikabadzhov** [comment]
FYI: Added in Milestone 6.28. since this is the default behaviour in the RDatasetSpec when having a chain with different tree names.

I should solve it if noone comes before the release of 6.28.

**Comment by eguiraud** [comment]
Removed the 6.28 milestone, this is not severe enough to block the release.

**Comment by bernhardmgruber** [comment]
This might be affected/solved by #13088.

**Comment by bernhardmgruber** [comment]
Ah, I didn't check the implementation and assumed #13088 was implemented in `TChain`. I just had a look now. Sorry about the noise then.

**Comment by dpiparo** [comment]
Nice change. I proposed a simplification. The tests seem to fail because the change does what it is supposed to do and the reference would need to be adapted.
