### ISSUE TITLE
ROOT can't recognize components in `std::experimental`

### ISSUE THREAD

**Issue by junaire** [root-project/root#10924]
- [x] Checked for duplicates

### Describe the bug

ROOT can't recognize components like `std::experimental::tuple` ( Maybe it is because there're two `tuple`, one in `std` and one in `std::experimental`, so ROOT is confused)

![image](https://user-images.githubusercontent.com/77525145/177772823-0411a239-ecd0-4845-a5f9-966d628d4bb0.png)

### Expected behavior
works fine

### To Reproduce
type `std::experimental::tuple<int, double> T;` in the repl.

### Setup

* ROOT version: main
* Operating System: Ubuntu 22 LTS
* Build ROOT from source

**Comment by bellenot** [comment]
AFAICS, it should be `std::tuple`, not `std::experimental::tuple` https://en.cppreference.com/w/cpp/utility/tuple :
```
root [0] std::tuple<int, double> T;
root [1]
```

**Comment by bellenot** [comment]
I'll let @Axel-Naumann comment on this, once he's back next week

**Comment by junaire** [comment]
> I'll let @Axel-Naumann comment on this, once he's back next week

OK, sorry let you back and forth. If you do think this is a potential bug as well, maybe reopen it?

**Comment by pcanal** [comment]
Don't you need a 
```
#include <experimental/array>
```
?

**Comment by junaire** [comment]
Thanks! I thought we have load these modules automatically! It makes sense to me.
