### ISSUE TITLE
[RF] Improve the position of the legend in the RooMCStudy output

### ISSUE THREAD

**Issue by vlisovsk** [root-project/root#10931]
In the ROOT 6.26 the default position of the legend in the output of RooMCStudy is not optimal, as part of numbers is cut away: see the top-right plot in the rf801 example https://root.cern.ch/doc/v626/rf801__mcstudy_8C.html 

This used to be better positioned in 6.24: https://root.cern.ch/doc/v624/rf801__mcstudy_8C.html 

It would be great to make the position optimal by default. (In the meantime, is there an easy way to change it manually?)

Extra wish: would it be possible to invoke the Gaussian fit not only for the pull plot, but also for the "value" and "error" plots?  (The two other plots in the top row of the rf801 example).

**Comment by guitargeek** [comment]
Hi, thanks for opening the issue!

I have created a PR that improves the legend for the pull distribution plot. You like it better now? Let me know if you have any comments!

https://github.com/root-project/root/pull/10938

**Comment by vlisovsk** [comment]
Hi Jonas,
Thanks for the elegant fix and for the further suggestions!
