### ISSUE TITLE
Have the plotting canvas from experiments

### ISSUE THREAD

**Issue by munozariasjm** [root-project/root#10968]
Hi all!

I was thinking that it would be very nice to have the option to have the canvas for different **styles** from the most common experiments, this will allow you to easily match the style of your plots. 

For example, if you want your functions to look like the ones normally generated in ATLAS you should be able to do something like
```bash
root [0] TGraph g;
root [1] for (auto i : {0,1,2,3,4}) g.SetPoint(i,i,i*i)
root [2] g.SetCanvas("ATLAS")
root [3] g.Draw("APL")
```

This idea comes from the [mplhep](https://github.com/scikit-hep/mplhep) library. They support canvas from a variety of collaborations such as ATLAS, ALICE, CMS...

Best regards

**Comment by couet** [comment]
The style is now global. It is set by gStyle. All the canvases have the same style. I guess a proper TExec placed at the beginning of the TCanvas list of primitives should be a workaround. But this needs to be checked.

**Comment by couet** [comment]
Have you tried the TExec idea ?

**Comment by couet** [comment]
@munozariasjm can we close this request?
