### ISSUE TITLE
[CMake] troubles with ROOT 6.26.04 from CVMFS

### ISSUE THREAD

**Issue by cburgard** [root-project/root#10963]
- [ ] Checked for duplicates

### Describe the bug

When trying to compile a project against ROOT 6.26.04 sourced from CVMFS, cmake complains about nlohmann_json missing.

```
CMake Error at /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Cmake/3.21.3/Linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Could not find a configuration file for package "nlohmann_json" that is
  compatible with requested version "3.10.5".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/nlohmann_json/nlohmann_jsonConfig.cmake, version: 3.6.1
    /lib64/cmake/nlohmann_json/nlohmann_jsonConfig.cmake, version: 3.6.1

Call Stack (most recent call first):
  /cvmfs/sft.cern.ch/lcg/releases/LCG_102/ROOT/6.26.04/x86_64-centos7-gcc11-opt/cmake/ROOTConfig.cmake:114 (find_dependency)
  CMakeLists.txt:1 (find_package)
```

### To Reproduce

Use a CentOS7 machine and setup ROOT 6.26.04 from CVMFS
(/cvmfs/sft.cern.ch/lcg/releases/LCG_102/ROOT/6.26.04/x86_64-centos7-gcc11-opt/bin/root).

Create a CMakeLists.txt file with the following contents:

`find_package( ROOT REQUIRED COMPONENTS Core RIO MathCore Matrix HistFactory RooFitCore RooFit Hist RooStats Minuit2 Minuit )`

Go to an empty folder, and call `cmake` on that CMakeLists.txt file.

### Setup

1. ROOT version: 6.26.04
2. Operating system: CentOS7
3. How you obtained ROOT: ```setupATLAS; lsetup "root 6.26.04-x86_64-centos7-gcc11-opt"```

**Comment by bellenot** [comment]
@linev Since you introduced that dependency, can you take a look? Thanks!

**Comment by andresailer** [comment]
Hi everyone,
the problem arises because `/cvmfs/sft.cern.ch/lcg/releases/LCG_102/ROOT/6.26.04/x86_64-centos7-gcc11-opt/ROOT-env.sh` (or I guess whatever setupATLAS is doing) is not exporting the CMAKE_PREFIX_PATH to all dependencies.
exporting CMAKE_PREFIX_PATH to point to the folder for nlohmann_json fixes this.

I.e., this works
```
export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.23.1/Linux-x86_64/bin/:$PATH
source /cvmfs/sft.cern.ch/lcg/releases/LCG_102/ROOT/6.26.04/x86_64-centos7-gcc11-opt/ROOT-env.sh
export CMAKE_PREFIX_PATH=$JSONMCPP__HOME:$CMAKE_PREFIX_PATH

cat > CMakeLists.txt << EOF
cmake_minimum_required(VERSION 3.20)
project(test)
find_package( ROOT REQUIRED COMPONENTS Core RIO MathCore Matrix HistFactory RooFitCore RooFit Hist RooStats Minuit2 Minuit)

EOF

mkdir -p build
cd build
cmake ..
```

Cheers,
Andre

**Comment by bellenot** [comment]
Thanks @andresailer ! Then who should take care of this?

**Comment by andresailer** [comment]
I think @cburgard just needs to export the CMAKE_PREFIX_PATH.

I don't know what `setupATLAS` is doing, so I don't know if that relies on lcgenv, or does its own thing.

We can probably add the CMAKE_PREFIX_PATH exports to lcgenv, but this isn't going to show up on CVMFS for the existing releases.

**Comment by cburgard** [comment]
@andresailer I'm happy to try whatever you send me, but I'm not going to be the only person encountering this issue, `setupATLAS` is the default way the majority of ATLAS users setup root, unless they use an ATLAS analysis release that ships with ROOT.
I don't know who's in charge of doing this.

**Comment by linev** [comment]
@bellenot 
I guess issue is due to difference in shell environment between ROOT compilation and ROOT-based code.
One have to ensure that same `nlohmann/json.hpp` version is detected in both cases.
Actually it has nothing to do with my last change which only set minimal accepted version to 3.9.

**Comment by cburgard** [comment]
@andresailer This fixes it, which is great (for me), but perhaps you want to undertake some steps so that this obscure fix doesn't need to be performed by everyone in the future?

**Comment by andresailer** [comment]
Totally, this is what I refer to here https://github.com/root-project/root/issues/10963#issuecomment-1186980925

**Comment by cburgard** [comment]
Ok, great. Shall we close this issue here then or do you want to keep it open until this is done?

**Comment by andresailer** [comment]
I think we can close this here. We can follow up in https://sft.its.cern.ch/jira/browse/SPI-2197

**Comment by cburgard** [comment]
Ok, great. Thanks!
