### ISSUE TITLE
[hist] Fit to TH2 silently ignores the `"I"` option for bin integration

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#11016]
### Describe the bug

When using the `"I"` option for bin integration to fit a TH2, the result is identical to the fit result without that option, even though bin integration should change the fit result.

### Expected behavior

Either the bin integration should be done and therefore the fit result changes, or there should be warning printed and a note in the documentation that the bin integration option only supports 1-d histograms.

### To Reproduce

```C++
void script() {

    auto f2 = new TF2("f2","[norm]*(5-[coefx]*x)*(5-y)",0,5,0,5);
    f2->SetParameters(1.0, 1.0);

    int nBins = 10;

    auto h2 = new TH2D("h2", "h2", nBins, 0., 5., nBins, 0., 5.);

    h2->FillRandom("f2", 500000);

    gStyle->SetOptFit(1111);

    // kick parameters a bit before fitting
    f2->SetParameters(0.9, 0.9);

    h2->Fit(f2, "", "");
    // h2->Fit(f2, "I", ""); // gives exactly the the same result
}
```

### Setup

ROOT master on Arch Linux

### Additional context

I observed this unexpected behavior when trying to reproduce a problem on the ROOT forum:
https://root-forum.cern.ch/t/integrate-tf2-function-over-each-bin/50882

**Comment by lmoneta** [comment]
I think the option `I` works for multi-dimensional histogram.
The problem with the script above is that you are fitting a linear function in `x` and `y` and the bin integral of the function is equivalent to the approximation to evaluate the function at the bin centre. 
If you use an exponential function, like: 
`TF2 f2("f2","[A]*exp(-[B]*x -[C]*y)",0,5,0,5);`
you will see a difference in the fitted amplitude A.

**Comment by guitargeek** [comment]
Ah yes, silly of me! Thanks for checking!
