### ISSUE TITLE
[RF] RooDataSetHelper doesn't respect RooRealVar range

### ISSUE THREAD

**Issue by dcervenkov** [root-project/root#11017]
- [x] Checked for duplicates

### Describe the bug

I have some data in RDataFrame, and I want to fit them using RooFit. I book a `RooDataSet` using the `RooDataSetHelper` like this
```cpp
auto data_set = df.Book<double, double>(
    RooDataSetHelper("data_set", "title", RooArgSet(var1, var2)), {"var1", "var2"});
```
The fit is wrong because the `data_set` doesn't respect the limits on `var1` and `var2`, resulting in an incorrect normalization.

The only difference in the following simplified fits is that I used
```cpp
auto data_set = df.Book<double, double>(
```
for the first one, and 
```cpp
auto data_set = df.Filter("var2>2005 && var2<2020").Book<double, double>(
```
for the second one.

![all_wrong](https://user-images.githubusercontent.com/23052054/180235896-9f9d8cdb-5804-4567-9f0f-e1279c141777.png)
![all_right](https://user-images.githubusercontent.com/23052054/180235919-42ba997b-7bcb-4462-8b81-eab405454b1d.png)

### Expected behavior

I expected the RooDataSet to account for the RooRealVar range.

### To Reproduce

1. Get any `RDataFrame`
2. Create a `RooRealVar` with limits narrower than the corresponding data in the `RDataFrame`
3. Use `RooDataSetHelper` to book a `RooDataSet` from the `RDataFrame` using the `RooRealVar`
4. Fit the `RooRealVar` of the `RooDataSet`
5. The fit will be wrong unless you cut on the `RDataFrame` to match the limits of the `RooRealVar`

### Setup

ROOT 6.26/04
macOS 12.4
Brew install

**Comment by guitargeek** [comment]
Thank you very much for opening this issue! This is indeed very dangerous behavior. I have opened a PR to implement the skipping of out-of-range events, which is also consistent with what happens when you are reading in a RooDataSet from a TTree.

**Comment by dcervenkov** [comment]
@guitargeek Thanks for fixing it so quickly! Will this end up in the next ROOT release?

**Comment by guitargeek** [comment]
Yes, as this is a bugfix it will also make it to 6.26.06, which will come out in a few weeks
