### ISSUE TITLE
[RF] Segfault for RooMomentMorph for ROOT>6.24

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#11061]
- [ ] Checked for duplicates

There is a segfault in segfault for RooMomentMorph for ROOT>6.24 

I am using the example from https://gist.github.com/cranmer/46fff8d22015e5a26619 
it was OK for ROOT 6.24 but fails for e.g. dev3 LCG nightly build 

### Describe the bug

There is a segfault in segfault for RooMomentMorph for ROOT>6.24 

### Expected behavior

no segfault 

### To Reproduce

at lxplus: 
```
source /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/setup.sh
python test.py 
```
where `tst.py` is a content of https://gist.github.com/cranmer/46fff8d22015e5a26619  with a fixed print statement

### Setup

1. Fails for ROOT > 6.24 
2. lxplus 
3. LCG 

### Additional context

actuallt my examples are more complicated, but since it fails even for the example from the expert, I use his example

**Comment by VanyaBelyaev** [comment]
and a kind of "official" example/tutorial for the RooMomentMorph and RooMomentMorphND will be very useful

**Comment by guitargeek** [comment]
Hi, thanks a lot for reporting this! I opened a PR to fix this:
https://github.com/root-project/root/pull/11064

Are you sure the claim that the version specification "segfault for ROOT>6.24" is correct? I don't get the segfault with ROOT 6.26 for example, only with ROOT 'master`.

**Comment by VanyaBelyaev** [comment]
Thank you very much for the fix! 
I confirm that using  LCG nightlies dev3 slot my (more complicated) code with 
`RooMomentMorph` and `RooMomentMorphND` works perfectly now!
Thank you!
