### ISSUE TITLE
[RF] RooImproperIntegrator1D does not propagate RooNumIntConfig to RooIntegrator1D

### ISSUE THREAD

**Issue by tcuisset** [root-project/root#11067]
### Describe the bug
It is not possible to change the numerical integration configuration of RooIntegrator1D when computing an improper integral. RooImproperIntegrator1D does not forward RooNumIntConfig to RooIntegrator1D (which leads to default settings being used), except in the case of a non-improper integral :

https://github.com/root-project/root/blob/7694b13fc812bf8b533196a114ccf9930754b6ed/roofit/roofitcore/src/RooImproperIntegrator1D.cxx#L166-L178

### Expected behavior
RooImproperIntegrator1D forwards the configuration to RooIntegrator1D in all cases.

### To Reproduce
```cpp
RooRealVar x("x", "x", 0., -1e31, 1e8);
RooRealVar mean("mean", "Location parameter of Landau distribution", 5.);
RooRealVar sigma("sigma", "Scale parameter of Landau distribution", 5.);
RooLandau landau("landau", "landau", x, mean, sigma);

RooNumIntConfig intConfig(*RooAbsReal::defaultIntegratorConfig());
intConfig.getConfigSection("RooIntegrator1D").setRealValue("maxSteps", 30);
landau.setIntegratorConfig(intConfig);

RooAbsReal* integral = landau.createIntegral(x);
cout << integral->getVal() << endl;
```
Produces : `... did not converge after 20 steps` instead of 30 steps
Changing `-1e31` to `-1e-29` then produces the correct result (30 steps)

### Setup
ROOT v6.26/02

**Comment by guitargeek** [comment]
Hi @tcuisset, thank you very much for reporting this issue!

I have opened a PR that addresses this issue. It should be reviewed and merged next week.

Would it benefit you if this bugfix is also applied to the next 6.26.08 patch release?

**Comment by tcuisset** [comment]
Hi @guitargeek,
I do not need the fix in the next patch, but thanks for offering.
