### ISSUE TITLE
Backport the fix on computation of the radiation and nuclear interaction lengths to v6.24

### ISSUE THREAD

**Issue by bcouturi** [root-project/root#11080]
Would it be possible to backport:

https://github.com/root-project/root/pull/11060 (already merged into [root-project:master]) 
(from what I understand a followup PR is also needed).

to the v6.24 branch, and retag a new version of ROOT after that is done. 
This would use use it as part of a LCG 101 patch release.

Many thanks.

FYI @andresailer @bellenot

**Comment by bellenot** [comment]
Thanks @bcouturi . I think this should also be backported in the `v6-26-00-patches` branch

**Comment by agheata** [comment]
Already merged in v6-24-00-patches, still pending for v6-26-00-patches due to unrelated CI errors

**Comment by agheata** [comment]
Merged now also in v6-26-00-patches

**Comment by bellenot** [comment]
Thanks @agheata !
