### ISSUE TITLE
Misleading warning with `builtin_clang=OFF`

### ISSUE THREAD

**Issue by StefanBruens** [root-project/root#11136]
In case `builtin_clang=OFF` and/or `builtin_llvm=OFF` is passed to CMake, an awkward warning is generated

https://github.com/root-project/root/blob/69002fa23d19ad50ff8dd6c7678a6343748ba3fd/cmake/modules/RootBuildOptions.cmake#L391-L395

The `NOT`s seem to be incorrect.

**Comment by vgvassilev** [comment]
I think this warning intended to say that if one uses `-Dbuiltin_cling=Off` we do not need neither `-Dbuiltin_clang=On` nor `-Dbuiltin_llvm=On`. So indeed the `NOT` probably should go with `if (builtin_cling)`...

**Comment by StefanBruens** [comment]
That sounds much more reasonable.

**Comment by bellenot** [comment]
This is now fixed in master by commit 6da62c5601256eb8d304
