### ISSUE TITLE
Builtin libLLVM is broken when using GCC + LTO for building

### ISSUE THREAD

**Issue by StefanBruens** [root-project/root#11135]
- [x] Checked for duplicates

### Describe the bug
```
[ 1675s] [100%] Generating tutorials/hsimple.root
[ 1675s] cd /home/abuild/rpmbuild/BUILD/root-6.26.06/_builddir/tutorials && LD_LIBRARY_PATH=/home/abuild/rpmbuild/BUILD/root-6.26.06/_builddir/lib: ROOTIGNOREPREFIX=1 ROOT_HIST=0 /home/abuild/rpmbuild/BUILD/root-6.26.06/_builddir/bin/root.exe -l -q -b -n -x hsimple.C -e return
[ 1675s] 
[ 1675s] Processing hsimple.C...
[ 1675s] root.exe: /home/abuild/rpmbuild/BUILD/root-6.26.06/interpreter/llvm/src/include/llvm/IR/User.h:216: void llvm::User::setNumHungOffUseOperands(unsigned int): Assertion `HasHungOffUses && "Must have hung off uses to use this method"' failed.
```

The `HasHungOffUses` member is initialized in the overloaded `clang::User::operator new`, which may trigger undefined behavior. See e.g.:

https://github.com/llvm/llvm-project/issues/47560
https://stackoverflow.com/questions/34892732/error-when-call-createphi-in-llvm

### Expected behavior
Builtin libLLVM works correctly

Though this is an LLVM upstream issue, either force-disabling LTO, or adding a CMake option to pass this down to the LLVM build (similar to `LLVM_BUILD_TYPE`) might be an option.

### To Reproduce
CXXFLAGS=... -O2 -flto=auto
cmake -B _builddir -S .. && make

### Setup
1. ROOT version: 6.26.06
2. openSUSE Tumbleweed
3. build from source

**Comment by StefanBruens** [comment]
Disabling LTO for the whole build avoids the problem, but this is of course only a stopgap measure.

**Comment by hahnjo** [comment]
As said in https://github.com/root-project/root/issues/10777#issuecomment-1207995020, LTO is not a supported configuration for building ROOT. Some of that is probably due to the upstream LLVM issue, so I don't see what should be done from our side...

**Comment by StefanBruens** [comment]
Already mentioned that:
- Detect CXXFLAGS including LTO, issue a warning
- Provide an option to disable LTO for LLVM

LTO is more than just an optimization. It allows to find numerous coding issues which are only visible with whole program analysis, e.g. ODR violations, out-of-bound accesses across TUs, ...

**Comment by bellenot** [comment]
Could that be fixed with upcoming LLVM 13 @hahnjo @vgvassilev ?

**Comment by bellenot** [comment]
OK, thanks @hahnjo !

**Comment by dpiparo** [comment]
Closing since building with LTO is not supported.
