### ISSUE TITLE
[hist] Chi-square computation in Binned likelihood fits

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#11143]
As reported in https://root-forum.cern.ch/t/chi-square-definition-in-root/51083/3, 
the reported chi-square from `TF1::GetChisquare` and from `FitResult` is not correct. 
A Neyman chi-square is computed but using also the empty bins. 
See https://github.com/root-project/root/blob/master/math/mathcore/src/FitResult.cxx#L183

We should return in this case as chi-square the value suggested by Baker-Cousins, i.e. 2 * MinNLL. 

In addition we have also :
- Documentation for `TF1::GetChisquare` and `ROOT::Fit::FitResult::Chi2` is missing.
- `TH1::Chisquare` and `ROOT::Fit::Chisquare` should compute also the Pearson chi-square

**Comment by atolosadelgado** [comment]
Hi,

I have tested the method `TH1::Chisquare` and seems to calculate the Pearson Chi2 properly

```
// File: test.cxx
// test TH1::Chisquare function. Pearson Chi2 is calculated as expected
// To run the script: root test.cxx
void test()
{

    int nbins = 100;
    double xmin =-5;
    double xmax = 5;

    TF1 * f = new TF1("f","gausn");
    double nentries = 1000;
    double binwidth = (xmax-xmin)/nbins;
    f->SetParameters(nentries*binwidth,0.,1.);
    f->SetRange(-10,10);


    TH1D *h = new TH1D("h","", nbins, xmin,xmax);
    h->FillRandom("f2",nentries);
    h->Draw();
    f->Draw("same");

    //h.Chisquare( &f2 , "L");

    //-- Chi2 Pearson
    double chi2_th1 = h->Chisquare( f , "P");



    // note: below it is assumed that "bin error" = sqrt( f("bin center") )
    double chi2_P = 0.;
    for (int i = 1; i <= h->GetNbinsX(); i++) {
        double v = f->Eval(h->GetBinCenter(i));
        if (v) chi2_P += TMath::Sq(v - h->GetBinContent(i)) / TMath::Abs(v);
    }
    std::cout << "hand calculated Pearson chi2 = " << chi2_P << "\n";
    std::cout << "ROOT TH1::Chisquare     chi2 = " << chi2_th1 << "\n";

}
```


Question: Should `ROOT::Fit::FitResult::Chi2` call `TH1::Chisqure` to avoid writing the same piece of code in two different places?

**Comment by lmoneta** [comment]
ROOT::Fit::FitResult::Chi2() returns the chi2 after fitting, `TH1::Chisquare` calls the function `ROOT::Fit::Chisquare` which compute the chi2 with an arbitrary function and histogram. The implementation is the same using the `ROOT::Fit::Chi2FCN` class.
