### ISSUE TITLE
builtin_llvm=OFF broken, LinkedObjects member is private in upstream

### ISSUE THREAD

**Issue by StefanBruens** [root-project/root#11146]
- [x] Checked for duplicates

```
[   82s] /home/abuild/rpmbuild/BUILD/root-6.26.06/interpreter/cling/lib/Interpreter/IncrementalJIT.h: In member function 'llvm::Error cling::IncrementalJIT::RemovableObjectLinkingLayer::removeObject(llvm::orc::VModuleKey)':
[   82s] /home/abuild/rpmbuild/BUILD/root-6.26.06/interpreter/cling/lib/Interpreter/IncrementalJIT.h:118:49: error: 'std::map<long unsigned int, std::unique_ptr<llvm::orc::LegacyRTDyldObjectLinkingLayerBase::LinkedObject> > llvm::orc::LegacyRTDyldObjectLinkingLayer::LinkedObjects' is private within this context
[   82s]          = static_cast<const AccessSymbolTable*>(LinkedObjects[K].get());
[   82s]                                                  ^~~~~~~~~~~~~
[   82s] In file included from /home/abuild/rpmbuild/BUILD/root-6.26.06/interpreter/cling/lib/Interpreter/IncrementalJIT.h:22:0,
[   82s]                  from /home/abuild/rpmbuild/BUILD/root-6.26.06/interpreter/cling/lib/Interpreter/BackendPasses.cpp:12:
[   82s] /usr/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h:475:55: note: declared private here
[   82s]    std::map<VModuleKey, std::unique_ptr<LinkedObject>> LinkedObjects;
[   82s]                                                        ^~~~~~~~~~~~~
[   82s] make[2]: *** [interpreter/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/build.make:125: interpreter/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/BackendPasses.cpp.o] Error 1
```
https://github.com/root-project/root/blob/cd992545ae18f0d036e382408d4acfccfa16db48/interpreter/cling/lib/Interpreter/IncrementalJIT.h#L111-L112

Patched version in ROOT:
https://github.com/root-project/root/blob/cd992545ae18f0d036e382408d4acfccfa16db48/interpreter/llvm/src/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h#L473-L476

Upstream (LLVM 9.x):
https://github.com/llvm/llvm-project/blob/c1a0a213378a458fbea1a5c77b315c7dce08fd05/llvm/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h#L465
```
private:
  ExecutionSession &ES;

  ResourcesGetter GetResources;
  NotifyLoadedFtor NotifyLoaded;
  NotifyFinalizedFtor NotifyFinalized;
  NotifyFreedFtor NotifyFreed;

  // NB!  `LinkedObjects` needs to be destroyed before `NotifyFreed` because
  // `~ConcreteLinkedObject` calls `NotifyFreed`
  std::map<VModuleKey, std::unique_ptr<LinkedObject>> LinkedObjects;
```

**Comment by hahnjo** [comment]
This is expected, `builtin_llvm=OFF` can only be used with a patched version of LLVM from https://github.com/vgvassilev/llvm/commits/cling-patches. Same for `builtin_clang=OFF`, where Cling needs quite a number of patches: https://github.com/vgvassilev/clang/commits/cling-patches

**Comment by StefanBruens** [comment]
This is obviously not expected:
1. If it is incompatible, it should detect this when CMake runs
2. If if is known to be incompatible, it should be mentioned in the documenation. Compare https://root.cern/install/build_from_source/#all-build-options
> builtin_cling | Build bundled copy of Cling. Only build with an external  cling if you know what you are doing: associating ROOT commits with  cling commits is tricky.

> builtin_clang | Build bundled copy of Clang

**Comment by hahnjo** [comment]
> If it is incompatible, it should detect this when CMake runs

I don't think it's feasible to write CMake detection logic for every single patch that we distribute on top of LLVM and Clang.

> If if is known to be incompatible, it should be mentioned in the documenation. Compare https://root.cern/install/build_from_source/#all-build-options

I *think* this list of options is autogenerated, but not sure. We could add another warning similar to `builtin_clang`'s
https://github.com/root-project/root/blob/cd992545ae18f0d036e382408d4acfccfa16db48/interpreter/CMakeLists.txt#L2-L4
but the situation will again change with the upgrade to LLVM 13, where it should *hopefully* again be possible to build against vanilla LLVM...

**Comment by StefanBruens** [comment]
> > If it is incompatible, it should detect this when CMake runs
> 
> I don't think it's feasible to write CMake detection logic for every single patch that we distribute on top of LLVM and Clang.

Doing a catchall should be doable. Add some extra version variable to llvm-config, or similar.

But also, doing such detection for every single modification would actually help in long term maintenance, making any expected deviation in behavior explicit. Though, adding this in retrospective for something on the way out is probably not time spent well.
 
> > If if is known to be incompatible, it should be mentioned in the documenation. Compare https://root.cern/install/build_from_source/#all-build-options
> 
> I _think_ this list of options is autogenerated, but not sure. We could add another warning similar to `builtin_clang`'s
> 
> https://github.com/root-project/root/blob/cd992545ae18f0d036e382408d4acfccfa16db48/interpreter/CMakeLists.txt#L2-L4
> 
> but the situation will again change with the upgrade to LLVM 13, where it should _hopefully_ again be possible to build against vanilla LLVM...

Support for vanilla LLVM 13 (and hopefully newer) would be a very welcome change.
