### ISSUE TITLE
Wrong Xrootd SHA256 has in release v6-26-06

### ISSUE THREAD

**Issue by alusiani** [root-project/root#11160]
- [ ] Checked for duplicates

### Describe the bug

Compilation of Root v6-26-06 from github release fails.

The SHA256 hash is wrong and has been corrected after this release on
https://github.com/root-project/root/commit/ce4ca3e1537be6776b93ef7bf8cd39d942c7de27

### Expected behavior

Compilation of Root v6-26-06 from github release succeeds.

### To Reproduce

1. git clone http://root.cern.ch/git/root.git
2. rootvers="6-26-06"; git checkout v$rootvers
3. mkdir ../root-build; cd ../root-build
4. cmake -DCMAKE_INSTALL_PREFIX=$rootinstall -Dbuiltin_xrootd=ON -Droofit=ON -Dpythia8=ON -Dmysql=OFF ../root-sources

### Setup

1. ROOT version v6-26-06
2. Operating system Linux Fedora 36
3. git clone http://root.cern.ch/git/root.git

**Comment by hahnjo** [comment]
Hi @alusiani, thanks for reporting. We've restored the original xrootd archive on the server, so the hash should again be valid and the build should succeed.
