### ISSUE TITLE
h2root/g2root man pages should be excluded from install when fortran is disabled

### ISSUE THREAD

**Issue by StefanBruens** [root-project/root#11182]
- [x] Checked for duplicates

### Describe the bug
`make install` installs h2root.1 and g2root.1 man pages.
  
### Expected behavior
h2root.1 is not installed

### To Reproduce
```
cmake -Dfortran:BOOL=OFF ...
make
make install
```

### Setup
1. ROOT version: 6.26.06

### Additional context
https://github.com/root-project/root/blob/6018b5fd4598094ce75f8ab293ba5b115e8b66d8/CMakeLists.txt#L590-L595

`h2root.1` and `g2root.1` should be conditionally added to `MAN_PATT_EXCLUDE`.

**Comment by bellenot** [comment]
This is now fixed in master by commit 97521755fb35
