### ISSUE TITLE
TBrowser does not show TGeo volume names

### ISSUE THREAD

**Issue by sawenzel** [root-project/root#11191]
### Describe the bug

Recent versions of ROOT's TBrowser on MacOS do not display the geometry tree correctly. In particular, volume names are missing.

### Expected behavior
I expect volume names to be displayed correctly. This is working correctly in version 6.22.

### To Reproduce

1. `root geometryfile.root`
2. `new TBrowser`
3. click on the volume hierarchy

### Setup

1. ROOT version 6.26 (wrong); ROOT version 6.22 (ok)
4. MacOS
5. `brew install` or manual compile

### Additional information:

attaching screenshots demonstrating correct (6.22) and wrong (6.26) behaviour using the same
geometry file.

<img width="272" alt="CorrectBehaviour" src="https://user-images.githubusercontent.com/3536753/184670081-bb573972-3b2c-4e72-9960-4a51e5e6ef96.png">

<img width="266" alt="WrongBehaviour" src="https://user-images.githubusercontent.com/3536753/184670108-781c5318-d3e9-4e15-813f-ecaab4256eee.png">

**Comment by bellenot** [comment]
This was fixed by commit e839c9a01d651d25
