### ISSUE TITLE
an old bug in ROOT v6 TAB completion ?

### ISSUE THREAD

**Issue by pavel1murat** [root-project/root#11238]
There seems to be a very old bug in ROOT v6 TAB completion, which , as far as I can tell, was introduced in transition from v5 to v6.

Suppose I have two files, a1111111222.txt and  a22222222.txt in the current directory and am running a function **a(...)** below, passing to it the file names, one at a time. The first call looks as follows:
```
root [1] void a(const char* fn, const char* a2) { printf("%s\n",fn); }
root [2] a("a1111111222.txt","erased_by_tab_completion")
a1111111222.txt
```
At this point,  I retrieve the executed command from the command stack with an UP arrow and try to edit it in order to run on the second file. For that, I delete the part of the first file name, leaving only "a2" out of it, and do the TAB-complete:

` root [3] a("a2<TAB>","erased_by_tab_completion")`

The completion works, and the "a22222222.txt" string shows on the command line. 
However the rest of the command line, the " erased_by_tab_completion\")" part of it, gets erased. 

When that part is long, the result is quite disappointing, so I wonder if the problem has been reported before. 

-- thanks for looking into it, regards, Pavel Murat

**Comment by ferdymercury** [comment]
Still the case in master

**Comment by ferdymercury** [comment]
The culprit is: https://github.com/root-project/root/commit/9d459ce6141daf108587d85737bdc50e70c775d3
