### ISSUE TITLE
hadd doesn't recompress for different algorithm at same level

### ISSUE THREAD

**Issue by dkpoult** [root-project/root#11245]
- [x] Checked for duplicates

### Describe the bug

When changing the compression settings using hadd, using the same compression level used by the input file won't trigger a recompression of the branches in the output file, even with a different algorithm.

ie. Passing -f301 with a 101 compressed input file results in a "301" compressed file but with 101 compressed branches.

### Expected behavior

I would expect the output file's branches to be recompressed with the provided compression algorithm.

ie. Passing -f301 with a 101 compressed input file results in a genuine 301 compressed file with 301 compressed branches.

### To Reproduce

1. Get the compression settings of any .root file, for example the 101 compressed [dimuon dataset](http://opendata.web.cern.ch/record/12341).
2. Run `hadd` and change the compression to a different algorithm of the same level, for example 101 -> 201 or 403 -> 303:
`hadd -f201 fake_dimuon_201.root orig_dimuon_101.root`
3. You can validate the weird behaviour by performing an intermediate conversion:
`hadd -f202 real_202_out.root orig_dimuon_101.root` -> `hadd -f201 real_dimuon_201.root real_dimuon_202.root`

### Setup

1. ROOT Version 6.27/01
2. Linux CentOS 8 + Linux Debian 11
3. Built from source

**Comment by pcanal** [comment]
You should also be able work around this issue the `-O` option

**Comment by dkpoult** [comment]
Just confirming that the `-O` works
