### ISSUE TITLE
Draw options "X+" and "Y+" not working with TMultiGraph

### ISSUE THREAD

**Issue by dpnrlz** [root-project/root#11250]
### Is your feature request related to a problem? Please describe.
TGraphPainter is used to Draw both TGraphs and TMultiGraphs. However, the "X+" and "Y+" draw options, to put the axis ticks and labels on the top and right sides, respectively, do not currently work (not implemented?) with TMultiGraphs.

### Describe the solution you'd like
Implement the "X+" and "Y+" draw options for TMultiGraph so they work as for TGraphs.

### Additional context
See example and plot in the ROOT Forum post https://root-forum.cern.ch/t/draw-with-x-and-y-not-working-for-tmultigraph/51327

**Comment by couet** [comment]
Thanks! I will look.
As I said it is **not implemented for MultiGraphs**. The Multigraph Painting is done by `TMultiGraph::Paint`.

**Comment by dpnrlz** [comment]
The [TMultiGraph](https://root.cern/doc/master/classTMultiGraph.html) documentation says:
MultiGraphs' Drawing
The drawing options are the same as for [TGraph](https://root.cern/doc/master/classTGraph.html). Like for [TGraph](https://root.cern/doc/master/classTGraph.html), the painting is performed thanks to the [TGraphPainter](https://root.cern/doc/master/classTGraphPainter.html) class.

Maybe it could be clarified, or maybe it's just me that gets confused with that.

**Comment by couet** [comment]
Yes, I know. that covers the way the plotting is done: Line, curve marker... Any way the fact is that X+ and Y+ need to be implemented for multigraphs.
