### ISSUE TITLE
Investigate need for TROOT::EndOfProcessCleanups in PyROOT

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#11279]
As discussed at https://github.com/root-project/root/pull/10753#issuecomment-1155514143 , the current way we run `TROOT::EndOfProcessCleanups` twice when using PyROOT is necessary, but we don't understand why. The change in the PR removed the double use of the function and the original reproducer still works. It would be nice to have test coverage for this particular pattern used in PyROOT.

**Comment by will-cern** [comment]
Think we understand why the double call is needed now, could add example from https://github.com/root-project/root/issues/21912 as a minimal reproducer ....
Propose calling `TROOT::ShutDown()` now too, instead of `TROOT::EndOfProcessCleanups()`

**Comment by guitargeek** [comment]
> Think we understand why the double call is needed now, could add example from [#21912](https://github.com/root-project/root/issues/21912) as a minimal reproducer .... Propose calling `TROOT::ShutDown()` now too, instead of `TROOT::EndOfProcessCleanups()`

That would not work. I tried it out, reporting my findings here: https://github.com/root-project/root/issues/21912#issuecomment-4412553864
