### ISSUE TITLE
ROOT fails to compile with current VecGeom

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#11271]
The source file `geom/vecgeom/src/TGeoVGShape.cxx` currently includes VecGeom headers from their "old" locations:
https://github.com/root-project/root/blob/5f2ced2567e005b286ba3b726c356324119dcb39/geom/vecgeom/src/TGeoVGShape.cxx#L18-L35
The "new" location is prefixed by `VecGeom/` since January 2020 (see [commit](https://gitlab.cern.ch/VecGeom/VecGeom/-/commit/8eb16296d783518d30ae352740e5e899e10b257b)), so it's not possible to compile ROOT with VecGeom 1.1.6 or later.

**Comment by hahnjo** [comment]
I'm tentatively assigning @agheata (because it's geometry) and @Axel-Naumann as we briefly discussed during the team meeting if it makes sense to fix this or deprecate and drop the code if apparently nobody is using it.

**Comment by agheata** [comment]
I'll fix the compilation and provide a test for this interface.
