### ISSUE TITLE
[gui] Variable Explorer GUI class

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#11295]
### Is your feature request related to a problem? Please describe.
Sometimes, in the midst of a ROOT session, it would be helpful to get an overview of the local and global variables that have been declared.

cling allows `.g` for printing a list of global variables.
The option `.l` for local variables got lost in the migration from CINT to cling, but there is an open issue: https://github.com/root-project/root/issues/10191

### Describe the solution you'd like
Apart from `.l` for local variables, it would be nice if ROOT (or cling) had a graphical way of displaying variables with its value, potentially as a 'TreeView'. Something like:
`new TVariableBrowser()`
instead of
`new TBrowser()`

Or maybe, it could be just a new TGTab inside the already existing TBrowser.

If the variable is an std::vector, one could maybe right click on it and click on "Scan" or "Print" as if were a TTree. Or double-clicking on it could unfold the tree view, or open a new GUI dialog with the vector.

Something like:
https://docs.spyder-ide.org/current/panes/variableexplorer.html

### Describe alternatives you've considered
I use the QtCreator's debugger to see the list of variables, see https://root.cern/blog/code-horsepower-f1/#debugging-your-root-scripts-or-executables-with-gdb, but it would be nice to have this available directly from the TBrowser or from the terminal.

One could also use Python and Spyder, but that's not directly the ROOT terminal...

### Additional context

If the feature were helpful for cling users, it should not rely on ROOT, maybe just a python script behind the scenes using Tkinter as GUI, that can be run from the cling terminal?

**Comment by guitargeek** [comment]
Assigning @bellenot for now since he is the code owner of the GUI part. But feel free to reassign!

**Comment by ferdymercury** [comment]
Find here a very first / naive implementation of this GUI class

[TVariableBrowser.tar.gz](https://github.com/root-project/root/files/9820904/TVariableBrowser.tar.gz)

Run as `root -l -e 'int zzz=3;' -e '.x run_viewer.cpp+'`

**Comment by linev** [comment]
Hi @ferdymercury 

If you like, one can integrate this functionality into `RBrowser`.

**Comment by ferdymercury** [comment]
Sounds very good :)

**Comment by linev** [comment]
Then I will prepare preliminary PR this week.

**Comment by linev** [comment]
I create PR https://github.com/root-project/root/pull/11654, but using more advanced representation with `TreeTable` element of ui5

**Comment by linev** [comment]
I guess, we can close issue now
