### ISSUE TITLE
Usage of ROOT::Math::LorentzVector in TGenPhaseSpace

### ISSUE THREAD

**Issue by mhemmer-cern** [root-project/root#11300]
### Explain what you would like to see improved
Since TLorentzVector is stated as legacy class it would be nice to have TGenPhaseSpace use the newer ROOT::Math::LorentzVector.

### Optional: what do you think how this could be done
Either by overloading the [SetDecay](https://root.cern.ch/doc/master/classTGenPhaseSpace.html#ab3293036b681c3f59f9c5f6bf6cb300c) and adding a private array of ROOT::Math::LorentzVector, or by having a 2nd version of TGenPhaseSpace with ROOT::Math::LorentzVector instead of TLorentzVector.

**Comment by dpiparo** [comment]
Marked as legacy in the documentation.

**Comment by mhemmer-cern** [comment]
Are there any plans for a modern alternative to TGenPhaseSpace, now that it is marked as legacy?

**Comment by guitargeek** [comment]
Just for the context, the `TGenPhaseSpace` was first declared a legacy with no alternative in ROOT 6.28 by @Axel-Naumann:
https://github.com/root-project/root/commit/1b32e042e47f8684817b86b4b80f4563cb271191

The new legacy warning box with 6.32 was only added for consistency. See also the discussion here:
https://github.com/root-project/root/pull/14754#issuecomment-1948944502

**Comment by Axel-Naumann** [comment]
I have been provided with a set of contributed classes that can replace `TGenPhasespace`. I will share it with you, @guitargeek !

**Comment by Axel-Naumann** [comment]
I gave up ;-) More seriously, I have moved on, @dpiparo took over, let's see what he says!
