### ISSUE TITLE
Migrate to pcre2

### ISSUE THREAD

**Issue by spotrh** [root-project/root#11395]
### Explain what you would like to see improved

root uses pcre (8.45), while upstream no longer maintains or supports it. Fedora is in the process of actively removing pcre and moving to pcre2 (10.40). It would be extremely helpful if root could migrate to pcre2.

**Comment by guitargeek** [comment]
Hi, thanks for pointing this out. Let's assign the issue to @Axel-Naumann for now, maybe he knows what such a migration would mean for ROOT

**Comment by Axel-Naumann** [comment]
@osschar iirc you provided this implementation? If so - thoughts? :-)

**Comment by osschar** [comment]
I did TPMERegexp, not sure who did TPRegexp. It seem sit would not be a major issue to swap over to pcre2.

https://stackoverflow.com/questions/70273084/regex-differences-between-pcre-and-pcre2
