### ISSUE TITLE
[TTree] TTree::Draw does not fill histogram.

### ISSUE THREAD

**Issue by couet** [root-project/root#11440]
I am not sure if it is a real bug or a known issue but the following macro does not fill the histogram `hpx`:
```
void ntuple_example() {
   auto hpx  = new TH1F("hpx", "hpx", 100, -1., 1.);
   auto f    = new TFile("hsimple.root");
   auto tree = (TTree*)f->Get("ntuple");
   tree->Draw("px >> hpx","","goff");
   hpx->Draw();
}
```
To make it work it is enough to swap the histogram creation line and the TFile creation line.
So the workaround is simple but that might be confusing if people first create the histogram(s) and then attach the file(s) containing the tree(s): the histogram(s) will be empty. I see that on Mac. I see this issue until 6:20 at least (I was not able to install older versions)

**Comment by pcanal** [comment]
`TTree::Draw` can only find histogram in the current `TDirectory` which in the code snippet above is the `TFile`.

Try:
```
void ntuple_example() {
   auto currentDirectory = gDirectory;
   auto hpx  = new TH1F("hpx", "hpx", 100, -1., 1.);
   auto f    = new TFile("hsimple.root"); // We now have gDirectory == f
   auto tree = (TTree*)f->Get("ntuple");
   currentDirectory->cd();
   tree->Draw("px >> hpx","","goff");
   hpx->Draw();
}
```
Cheers,
Philippe.
