### ISSUE TITLE
Documentation of TH1::GetRMS does not mention the fact that it is not the RMS anymore

### ISSUE THREAD

**Issue by maxnoe** [root-project/root#11456]
### Is your feature request related to a problem? Please describe.

In previous versions of the ROOT documentation, it was clearly mentioned that e.g. `TH1::GetRMS` for historical reasons does not in fact calculate RMS but the standard deviation.

Now this section is just empty:
https://root.cern.ch/doc/master/classTH1.html#a8fdcbb1ef23f99d5b28c1f10e947c957

### Describe the solution you'd like

Re-introduce this documentation

**Comment by couet** [comment]
Fixed . Thanks
