### ISSUE TITLE
Cannot use globs with `?#` syntax in TChain::Add

### ISSUE THREAD

**Issue by ikabadzhov** [root-project/root#11483]
As the title reads: TChain Add does not properly resolve globs with `?#`. Consider:
  ```cpp
  auto dfWriter0 = ROOT::RDataFrame(5).Define("z", "42");
  dfWriter0.Snapshot<int>("tree", "specTestFile0.root", {"z"});
  dfWriter0.Snapshot<int>("tree", "specTestFile00.root", {"z"});
  dfWriter0.Snapshot<int>("tree", "specTestFile000.root", {"z"});

  TChain c{};
  c.Add("specTestFile0*.root?#tree");
  for(auto i = 0u; i < c.GetEntries(); ++i)
  	c.GetEntry(i);

  gSystem->Unlink(("specTestFile0.root"));
  gSystem->Unlink(("specTestFile00.root"));
  gSystem->Unlink(("specTestFile000.root"));
  ```
  Current behaviour --> invalid parsing:
  ```
Error in <TChain::LoadTree>: Cannot find tree with name  in file [...]/specTestFile0.root#tree
Error in <TChain::LoadTree>: Cannot find tree with name  in file [...]/specTestFile00.root#tree
Error in <TChain::LoadTree>: Cannot find tree with name  in file [...]/specTestFile000.root#tree
  ```
  
@vepadulano and I just saw [here](https://root.cern/doc/master/classTChain.html#a78a896924ac6c7d3691b7e013bcbfb1c) that the question mark is a valid wildcard in the glob expansion of `Add`.

Note that in this particular minimal reproducer, I can alternatively use:
```cpp
  TChain c{"tree"};
  c.Add("specTestFile0*.root");
```
I used precisely this example in order to show that even a single `Add` results in undesired behaviour.

**Comment by ikabadzhov** [comment]
The workaround that I just figured out is to create multiple temporary TChains with a name which would evaluate each single glob. And then in a "main" TChain add all these temporary TChains/

**Comment by vepadulano** [comment]
Another workaround is using the old syntax with `/` as separator for treename: `c.Add("specTestFile0*.root/tree");`. Apparently [`ParseTreeFilename`](https://root.cern.ch/doc/master/classTChain.html#a8c5fdf39b6ccebdd4b1c6bf38ca805e5) doesn't support the newer syntax when wildcarding is involved.

**Comment by pcanal** [comment]
@gganis Do you know the best way to handle/solve this?  Thanks.

**Comment by eguiraud** [comment]
@gganis @pcanal gentle ping :)

**Comment by eguiraud** [comment]
> Another workaround is using the old syntax with / as separator for treename: c.Add("specTestFile0*.root/tree");.

For future reference, I just realized/remembered why we stopped using the old syntax (and why we still shouldn't): it incurs in https://github.com/root-project/root/issues/8739 (a better explanation of the problem is at https://github.com/root-project/root/pull/8820 ).
