### ISSUE TITLE
roottest/root/meta/genreflex/ROOT-5768 needs to be enabled

### ISSUE THREAD

**Issue by pcanal** [root-project/root#11484]
The test roottest/root/meta/genreflex/ROOT-5768 currently include `boost` header files and thus is disable.

This test the `--interpreteronly` flag of genreflex.  See https://sft.its.cern.ch/jira/browse/ROOT-5768

The test needs to be trimmed down to no longer include the boost header files OR rewritten without them.

**Comment by dpiparo** [comment]
Fix here https://github.com/root-project/roottest/pull/1062
