### ISSUE TITLE
TBrowser non-ascii text scrambles on windows

### ISSUE THREAD

**Issue by shangjiaxuan** [root-project/root#11519]
- [x] Checked for duplicates

### Describe the bug
Windows running on non utf-8 code page will see scramble text for non-ascii folders and files in the current new html `TBrowser` implementation, and fails selection and opening. Older `TRootBrowser` did not have this issue but does not support 64 bit on windows.

### Expected behavior
TBrowser can see files and folders, select files and folders normally.

### To Reproduce
Used non-ascii windows system (should already have some non-ascii text in filesystem already), install root.

### Setup
1. ROOT version: 6.26/06
2. Operating system: Windows
3. How you obtained ROOT binary: download from cern site.

### Additional context
Should be self explanatory.

### Suggested fix:
A post-build step should fix this on newer windows systems, as this documentation says:
https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page

Tested and works on my machine.

Related forum topic:
https://root-forum.cern.ch/t/tbrowser-non-ascii-text-scrambles-on-windows/51899

**Comment by bellenot** [comment]
Fixed in master by commit a5cbb5d7796846c Thanks again for the hint!
