### ISSUE TITLE
[RF] Parameter desync in integral of `RooRealSumPdf` when using batchmode

### ISSUE THREAD

**Issue by elusian** [root-project/root#11578]
- [x] Checked for duplicates

### Describe the bug

I have a model containing a `RooRealSumPdf` which wraps a `RooAbsReal` with an analytical integral (I tested with `RooGaussModel` and `RooPolyVar`). One of the parameters of the `RooAbsReal` is a function of the actual fit parameter (a `RooProduct` containing a `RooRealVar` for example).
When using batchmode, in the computation of the integral of the `RooAbsReal` (which is internal to the `RooRealSumPdf`, since it overrides `analyticalIntegralWN`), the value of the transformed parameter is not synced with the changes of the `RooRealVar` it contains, leading to a wrong integral.
Inspecting the `RooFitDriver` contents shows that the dataMap entry corresponding to the transformed parameter has the correct value, it's just the integral which uses the wrong one.

### Expected behavior

Integral uses correct parameters

### To Reproduce

```C++
void testIntegralDesync() {
    using namespace RooFit;
    RooRealVar x("x", "", 0, 1);
    
    RooRealVar par("par", "", -0.005, -5, 5);
    RooProduct par_mod("par_mod", "", RooArgSet(par, RooConst(10)));
    
//    RooPolyVar fn("fn", "", x, RooArgList(RooConst(1), par_mod));
//    RooRealSumPdf pdf("pdf", "", fn, RooConst(1));
    
    RooGaussModel gm("gm", "", x, RooConst(0), RooConst(0.001));
    RooFormulaVar formula("formula", "exp(-@0/@1)", RooArgList(x, par_mod));
    auto fn = gm.convolution(&formula, &x);
    RooRealSumPdf pdf("pdf", "", *fn, RooConst(1));
    
    auto data = pdf.generate(x, NumEvents(1));
    
    auto nllBase = pdf.createNLL(*data);
    auto nllBatch = pdf.createNLL(*data, BatchMode("cpu"));
    
    gm.verboseEval(10); // printout helps showing the exact problem, since it prints the parameter
    
    double nllBaseVal = nllBase->getVal();
    double nllBatchVal = nllBatch->getVal();
    clog << "Before changing: " << nllBaseVal << " vs " << nllBatchVal << endl;
    
    par.setVal(-0.1);
    nllBaseVal = nllBase->getVal();
    nllBatchVal = nllBatch->getVal(); 
    clog << "After changing: " << nllBaseVal << " vs " << nllBatchVal << endl; 
}
```

### Setup

ROOT master from LCG dev3

### Additional context

I tested this with a `RooRealSumPdf` but I'm not sure it is the only one affected or if it is anything with an internal integral.

**Comment by guitargeek** [comment]
Hi @elusian, thank you so much as always for reporting this!

I haven't solved the problem yet, but just to track my progress here: the underlying problem is that the integrals of a `RooRealSumPdf` somehow have their client-server interface messed up. Here is a reproducer:

```C++
void repro() {
    using namespace RooFit;
    RooRealVar x("x", "", 0, 1);

    RooRealVar par("par", "", -0.005, -5, 5);
    RooProduct parMod("par_mod", "", RooArgSet(par, RooConst(10)));

    RooGaussian gauss("gauss", "", x, parMod, RooConst(2.0));
    RooGenericPdf pdf("pdf", "gauss", gauss);

    std::unique_ptr<RooAbsReal> integ1{gauss.createIntegral(x, *pdf.getIntegratorConfig(), nullptr)};
    integ1->Print("v");

    std::cout << std::endl;

    std::unique_ptr<RooAbsReal> integ2{pdf.createIntegral(x, *pdf.getIntegratorConfig(), nullptr)};
    integ2->Print("v");
}
```

The integral of the Gaussian has the correct value (`V`) servers (the parameters of the Gaussian):
```
    (0x7ffc9b9bf798,-S) RooRealVar::x ""
    (0x7ffc9b9bf240,--) RooGaussian::gauss ""
    (0x7ffc9b9bff68,V-) RooProduct::par_mod ""
    (0x55ac531cd470,V-) RooConstVar::2 "2"
```

The integral of the `RooGenericPdf` should have the same value servers plus the coefficient, but it doesn't:
```
    (0x7ffc9b9bf798,-S) RooRealVar::x ""
    (0x7ffc9b9bec88,--) RooRealSumPdf::pdf ""
    (0x7ffc9b9bfb80,V-) RooRealVar::par ""
    (0x55ac51984c50,V-) RooConstVar::10 "10"
    (0x55ac531cd470,V-) RooConstVar::2 "2"
    (0x55ac531eb3f0,V-) RooConstVar::1 "1"
```

For some reason, the direct value server, which is `par_mod` is **skipped** now, misrepresenting the client-server relationship.

The new BatchMode makes strong use of the value-server interface for the `RooFitDriver`, so it's very sensitive to `RooRealIntegrals` getting it wrong.

I need to fix this problem with the value servers registered for integrals on RooRealSumPdfs.

Further notes:

* The problem has always been there in RooFit, it's just that the BatchMode uncovered it
* Whatever the fix will be, it may be a too big change to the central `RooRealIntegral` class for a patch release...

**Comment by guitargeek** [comment]
I have opened a PR to fix the problem in RooRealIntegral.

It's a first step, but it will probably take more time before this gets merge, as the RooRealIntegral is not covered that well by unit tests yet, and I want to first write more tests for the part of the code that I changed. I already have added one test based on your example, but I still need to cover the case where the integrated function has shape clients .

**Comment by elusian** [comment]
Thank you for looking into this! 
Are you saying this is a first step due to the missing tests or because more work is needed after the PR?

**Comment by guitargeek** [comment]
Yes, just because of the missing tests to cover the code changes of RooRealIntegral. If it's tested well enough I could even backport it to the patch release maybe
