### ISSUE TITLE
cppyy does not retrieve correct size of type when pythonizing vector

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#11596]
```cpp
root [0] auto a = std::vector<const char*>::value_type();
root [1] a
(const char *) nullptr
```
Whereas it should return the correct `const char*` type https://godbolt.org/z/a3s95cex3

## Setup

ROOT master and 6.26
Fedora 36
GCC 12

Feel free to change assignees if needed

**Comment by vepadulano** [comment]
This was the original cause for https://github.com/root-project/root/issues/11581

**Comment by vepadulano** [comment]
Indeed, it's a bit more subtle. There is a pythonization happening [here](https://github.com/root-project/root/blob/07932d78211d0ac5fdb198ac2260c35530cb9647/bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx#L1158-L1160), which transforms the type given by `::value_type` to a string and sets the corresponding Python attribute. Probably for `const char *` the type is not properly parsed thus the attribute is not set.

**Comment by vepadulano** [comment]
The issue seems to be with [this line in particular](https://github.com/root-project/root/blob/07932d78211d0ac5fdb198ac2260c35530cb9647/bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx#L1152):
```cpp
const std::string& vtype = Cppyy::ResolveName(name+"::value_type");
size_t typesz = Cppyy::SizeOf(vtype);
```

In the reproducer case, this is equivalent to calling `Cppyy::SizeOf("const char *")`. This will call [`SizeOf(const std::string &)`](https://github.com/root-project/root/blob/e6fcad7d14d6a7ffa0b59e4557005d88b05ce948/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx#L626). In turn, this first calls `gROOT->GetType("const char *")`, which fails, then falls back to calling `SizeOf(GetScope(type_name))`.

In `GetScope`, we reach [this part](https://github.com/root-project/root/blob/e6fcad7d14d6a7ffa0b59e4557005d88b05ce948/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx#L531-L536) that calls `TClass::GetClass`. As we can see, this returns nullptr:
```cpp
root [0] auto cl = TClass::GetClass("const char *", true, true);
root [1] cl
(TClass *) nullptr
```
Thus, the final result of the initial call to `Cppyy::SizeOf(vtype)` is `0`. This means that cppyy thinks that the size of these types (including `const char *`, `const int *` and so on) is zero, thus the attribute is never pythonized.

In upstream cppyy, this is fixed by calling `SizeOf` with the original type, instead of the resolved one: https://github.com/wlav/CPyCppyy/blob/master/src/Pythonize.cxx#L1789-L1802

So this should be done in our cppyy too. Reassigning the issue to me, it's not related to cling but cppyy itself

**Comment by guitargeek** [comment]
Since this is fixed upstream, this will the fixed by the cppyy sync PR:
https://github.com/root-project/root/pull/14507
