### ISSUE TITLE
STARlight simulation

### ISSUE THREAD

**Issue by Anas-Alaali** [root-project/root#11626]
I installed root via this video [https://www.youtube.com/watch?v=pmfM4Zq6OQU&list=PLLybgCU6QCGWLdDO4ZDaB0kLrO3maeYAe&index=30](https://www.youtube.com/watch?v=pmfM4Zq6OQU&list=PLLybgCU6QCGWLdDO4ZDaB0kLrO3maeYAe&index=30) 

To build a starlight 
![Screenshot 2022-10-23 133107](https://user-images.githubusercontent.com/116489914/197387186-122e8d49-1751-4152-bc5c-c9ce70a8f60a.png)
I tried a lot to fix this error 
![Screenshot 2022-10-22 220723](https://user-images.githubusercontent.com/116489914/197386889-d40c094c-b457-4e2c-a549-caf0d6d39a61.png) 

Please help me

**Comment by pamputt** [comment]
Try `cmake ..` instead of `cmake root`

**Comment by Anas-Alaali** [comment]
I tried to run    cmake /home/physics/starlight   it's given the same error

**Comment by pamputt** [comment]
Where have you downloaded Starlight? Or where did you run svn co http://starlight.hepforge.org/svn/trunk? In which directory?

**Comment by guitargeek** [comment]
I don't see how this is a bug report for ROOT. Have you asked the starlight developers about this? In any case, if this relates to ROOT, let's discuss it on the forum. The GitHub issues are only for bugreports and improvement suggestions.
