### ISSUE TITLE
std::any in pyROOT with c++17

### ISSUE THREAD

**Issue by wxie2013** [root-project/root#11647]
`std::any` doesn't seem to be included in pyROOT built from source with c++17. I tried the following with root6.26.08.

```Python
import ROOT
a = ROOT.std.any()
```
```
Traceback (most recent call last):
File “”, line 1, in
AttributeError: <namespace cppyy.gbl.std at 0x558f5c6b83a0> has no attribute ‘any’. Full details:
type object ‘std’ has no attribute ‘any’
‘std::any’ is not a known C++ class
‘any’ is not a known C++ template
‘any’ is not a known C++ enum
```

**Comment by eguiraud** [comment]
The larger discussion about whether `ROOT.std.any` should be available by default is probably better suited for upstream cppyy (https://github.com/wlav/cppyy).

**Comment by wlav** [comment]
No, that discussion is not relevant upstream:

```
>>> import cppyy
>>> cppyy.gbl.std.any
<class cppyy.gbl.std.any at 0x113f04c30>
```

Any "larger discussion" should be on whether ROOT is ever going to upgrade to the latest version of cppyy? What you have in ROOT is at least 2 years or more behind in development.

**Comment by eguiraud** [comment]
Thank you for pointing out this is already solved upstream!
