### ISSUE TITLE
TFile plugins :: pass meta4 extension files to TNetXNGFile and process it

### ISSUE THREAD

**Issue by adriansev** [root-project/root#11653]
### Is your feature request related to a problem? Please describe.
Not a problem but a usage of XRootD feature that is not used by TFile::Open

### Describe the solution you'd like
It would be useful that .meta4 files in `TFile::Open("whatever_name.meta4")`
to be passed for processing to TNetXNGFile (XRootD)

### Describe alternatives you've considered
There are no alternatives, TFile::Open (TNetXNGFile::Open) does not know to pass
to XrdCl the meta file for processing

### Additional context
XRootD (XrdCl) know to use a meta file (`.meta4`) which is a virtual redirector. This allows not only fallback through a list a replicas to the same file but (at least for xrdcp) concurrent access (with `-y | --sources <n> `)

There would be 2 problems to be solved:
1. Add a signature to TNetXNGFile to allow to process a call like `TNetXNGFile::Open("whatever_name.meta4")`
2. Tell TFile to redirect an access to a `.meta4` file to TNetXNGFile

For reference, just in case the file type is identified by content (but from what i seen in TFile::GetType this is not the case) a meta4 file is an xml with the signature like:
```
<?xml version="1.0" encoding="UTF-8"?>
 <metalink xmlns="urn:ietf:params:xml:ns:metalink">

...

 </metalink>
```

I tried something on my own but i got entangled on my lack of knowledge of TFile mechanics, so i though to ask expert help here, maybe the solution is fast and simple (in expert eyes).
Adding here @simonmichal in case there are questions on XrdCl feature.
Thanks a lot!

**Comment by adriansev** [comment]
great! thanks a lot! only at your mention i noticed that [XRD_LOCALMETALINKFILE](https://xrootd.slac.stanford.edu/doc/xrdcl-docs/www/xrdcldocs.html#x1-230004.2.13) have a default of 0 and actually have indication on how should be used (for some reason in Python bindings this is not required, i can use directly a metafile as source, and the same is for xrdcp)

**Comment by dpiparo** [comment]
waiting for @amadio before closing.

**Comment by amadio** [comment]
@adriansev Can you now do all you wanted initially when filing this issue? I think that for really local metalink files we may still need a change in ROOT.

**Comment by dpiparo** [comment]
Closing as this is now possible to open `.meta4` files in ROOT.
