### ISSUE TITLE
TTask: unsafe cast in ExecuteTasks

### ISSUE THREAD

**Issue by klenze** [root-project/root#11663]
TTask exposes fTasks through (non-const) GetListOfTasks, so the invariant "fTasks only contains pointers to TTask" can not be enforced. 
This makes 
```    while((task=(TTask*)next())) {```
an unsafe type cast. dynamic_cast should be used instead to avoid undefined behavior. 

Generally, any C-style casts (or static_casts) should be avoided unless there is encapsulation to enforce an adequate invariant. 
C++ is a strongly typed language where type errors have to be caught at compile time because they will not lead to graceful failure at runtime.

**Comment by pcanal** [comment]
I agree that `TTask` and `TThread` are legacy.  `TFolder` is distinct from those 2 (closer tied to `TTree` usage)

**Comment by Axel-Naumann** [comment]
OK so @klenze we'd like to understand your use case.

@couet please mark `TTask` (and while you're at it also `TThread` and `TFolder`, still discussing with @pcanal on the latter) as legacy (i.e. doc), without deprecating them (i.e. code).

**Comment by klenze** [comment]
I ended up using it because our event processing framework happens to be build around TTask :-)

https://github.com/FairRootGroup/FairRoot/blob/master/base/steer/FairTask.h#L40

I concede that the potential for undefined behavior is limited. A user handling two TList* at once, one to GetListOfTasks() and  one to something else, and adding a TCanvas* to the former by mistake is not a terribly likely thing to happen. (I just am generally not a fan of static or C-style casts -- which are the casts mostly used in my collaboration. 95% of the time, the object is of the type you expected and nothing bad happens. But in the rare case it is not, I prefer an assert (or even a null pointer dereference)  to just reinterpreting the object as a different type and seeing where that takes the code.)

Marking it as deprecated works for me. 

I consider the issue resolved but will keep the issue open for a bit so that people have a chance to comment on my wall of text. Feel free to close it as resolved, otherwise I will do so in a few days. 

Thanks,
   Philipp

**Comment by Axel-Naumann** [comment]
Yeah totally, we still want to fix the cast. Your use case is the only legit one that I'm aware of ;-) Thanks for confirming!

**Comment by klenze** [comment]
Thanks again everyone.

**Comment by Axel-Naumann** [comment]
We still want to fix the cast.
