### ISSUE TITLE
Run STARlight 

### ISSUE THREAD

**Issue by Anas-Alaali** [root-project/root#11665]
How to run starlight in ubuntu after editing and saving a file?
![Screenshot 2022-11-06 105219](https://user-images.githubusercontent.com/116489914/200164679-946fb159-67ba-422c-b492-9ab0e6fe23ab.png)
![Screenshot 2022-11-06 105310](https://user-images.githubusercontent.com/116489914/200164687-f623ca0a-df68-4707-b1ba-664f3ca45b15.png)
![Screenshot 2022-11-06 110312](https://user-images.githubusercontent.com/116489914/200164692-434f9ae1-2653-4e68-86fe-249e20d200cd.png)

Please help me.

**Comment by guitargeek** [comment]
Hi @Anas-Alaali!

You have already opened these two previous issues that were not related to ROOT:

* https://github.com/root-project/root/issues/11636
* https://github.com/root-project/root/issues/11626

The ROOT GitHub issues are for bug reports, feature requests, and improvement ideas for ROOT.

If you have problems with the STARlight, please get in touch with the starlight authors or ask a colleague who might know about this.
