### ISSUE TITLE
[cling] GetClassSharedLibs fails to find several classes

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#11667]
- [x] Checked for duplicates

### Describe the bug
When linking external applications against ROOT classes, one needs to find in which library the used classes are defined. To know this info, it is useful to call e.g.:
```
gInterpreter->GetClassSharedLibs("TTreePlayer")
(const char *) "libTreePlayer.so"
```
But this function consistently fails with some classes:
```
gInterpreter->GetClassSharedLibs("TUrl")
(const char *) nullptr
gInterpreter->GetClassSharedLibs("TArray")
(const char *) nullptr
```

### Expected behavior
It works with all classes.

### To Reproduce
```
gInterpreter->GetClassSharedLibs("TUrl")
```

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.26/06                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jul 28 2022, 18:08:51                 |
  | From tags/v6-26-06@v6-26-06                                      |
  | With c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0                        |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
See full list of failing classes here: https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-master/lastBuild/consoleText
and search for "WARNING modifyClassWebpage.sh"

**Comment by ferdymercury** [comment]
Maybe related with this comment: https://github.com/root-project/root/blob/master/core/metacling/src/TCling.cxx#L6250

**Comment by ferdymercury** [comment]
@hahnjo not sure if this issue might also get improved with llvm16 ?

**Comment by hahnjo** [comment]
I don't really see how LLVM is involved with this; in any case, it's still returning `nullptr` as before for `TUrl` and `TArray`.

**Comment by ferdymercury** [comment]
This is the output when enabling gDebug=6

![image](https://github.com/root-project/root/assets/10653970/c4a8795c-fedd-4fee-90d7-36390bbb9ba6)

**Comment by ferdymercury** [comment]
Relevant lines in the trace: 
![image](https://github.com/root-project/root/assets/10653970/d3955eea-13b6-46a0-a2fc-5b984fc6e62d)

Maybe @vgvassilev can provide some insights on the mechanism.

**Comment by ferdymercury** [comment]
It seems that all classes in libCore.so return a nullptr

**Comment by ferdymercury** [comment]
PR is ready here: https://github.com/root-project/root/pull/14747
