### ISSUE TITLE
[ntuple] Pending optimizations for storage of classes with an associated collection proxy

### ISSUE THREAD

**Issue by jalopezg-git** [root-project/root#11671]
After pull-request #11525 is merged (which introduces `RField` support for user-defined classes that have an associated collection proxy), it is planned to apply further optimizations to the base implementation.

### Optional: share how it could be improved
Three different optimizations can be applied, in order:
- [ ] Iteration over collection elements: suggestion by @pcanal [here](https://github.com/root-project/root/pull/11525#discussion_r997334570) is to use iterators instead of relying in `TVirtualCollectionProxy::At()`.
- [ ] Reuse vs. destruct/reallocate for collection items: suggested by @pcanal [here](https://github.com/root-project/root/pull/11525#discussion_r997337292) and [here](https://github.com/root-project/root/pull/11525#discussion_r997343681).
- [ ] Maybe optimize the case of a `kSTLvector` collection, as elements are contiguous in memory (see [here](https://github.com/root-project/root/pull/11525#discussion_r997335574)).

**Comment by pcanal** [comment]
> Reuse vs. destruct/reallocate for collection items: suggested by @pcanal https://github.com/root-project/root/pull/11525#discussion_r997337292 and https://github.com/root-project/root/pull/11525#discussion_r997343681.

The 2nd one is actual about resize/pre-allocate in one go (instead of incrementally).
