### ISSUE TITLE
STARlight simulation

### ISSUE THREAD

**Issue by Anas-Alaali** [root-project/root#11694]
https://starlight.hepforge.org/ 

I found the error which run make but I can't fix that. 
![Screenshot 2022-11-12 141541](https://user-images.githubusercontent.com/116489914/201471628-4dc9d225-537d-40da-a2da-e8d6d4922a79.png)
![Screenshot 2022-11-12 141807](https://user-images.githubusercontent.com/116489914/201471631-aca47583-d887-475b-a267-5f21d44ee3d9.png)
![Screenshot 2022-11-12 141825](https://user-images.githubusercontent.com/116489914/201471634-b3fc3b8d-aa65-4afa-983c-5d1ad9fc7909.png)

Please, I need help.

**Comment by guitargeek** [comment]
Hi @Anas-Alaali!

You have already opened these three previous issues that were not related to ROOT bugs or feature and improvement requests! Can you **please** stop this spam?

* https://github.com/root-project/root/issues/11665
* https://github.com/root-project/root/issues/11636
* https://github.com/root-project/root/issues/11626

If you have problems with the STARlight, please get in touch with the starlight authors or ask a colleague who might know about this.
