### ISSUE TITLE
6.26.10 compilation fails with Python 3.11

### ISSUE THREAD

**Issue by chrisburr** [root-project/root#11728]
Compilation fails with Python 3.11 and 6.26.10 as https://github.com/root-project/root/pull/10734 was never backported.

**Comment by bellenot** [comment]
This is now fixed in v6-26-00-patches. Sorry for not backporting the fixes earlier.

**Comment by rlalik** [comment]
> This is now fixed in v6-26-00-patches. Sorry for not backporting the fixes earlier.

Perhaps python (different version) checks could be part of of your CI run?
