### ISSUE TITLE
[IO] TFile::DrawMap plots can be improved

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#11723]
This is what I get calling `DrawMap` on `hsimple.root` with current master:

![image](https://user-images.githubusercontent.com/10999034/202241538-7a33c2c6-aad8-4208-abb7-18076271374a.png)

**Comment by couet** [comment]
Yes, I see that. I will investigate. I was not aware of this "DrawMap". Thanks for the report.

**Comment by couet** [comment]
The issue is in TFileDrawMap.cxx. I rolled back to a version of 2008. The issue is still there. So that's not something introduced recently. Deeper investigations are needed.

**Comment by couet** [comment]
Ok, I talked to René, it seems that what we get is correct. This functionality shows where the objects in a file are, and their occupancy. It makes sense only if you turn on the "Event Statusbar" (as said in the doc). Then moving the mouse on the canvas you see where the objects are. According to René this functionality makes sense only for big files with many objects. I cannot tell wether it can be improved or not. There is no picture reference available.

**Comment by eguiraud** [comment]
> It makes sense only if you turn on the "Event Statusbar"

I guess that should be turned on by default when someone uses `DrawMap` then

**Comment by couet** [comment]
It makes more sense with a bit of tuning:
```
void drawmap() {
   auto f = new TFile("hsimple.root");
   TNtuple *n = (TNtuple*)f->Get("ntuple");
   n->GetBranch("px")->SetFillColor(kRed);
   n->GetBranch("py")->SetFillColor(kBlue);
   n->GetBranch("pz")->SetFillColor(kGreen);
   n->GetBranch("random")->SetFillColor(kYellow);
   f->DrawMap();
}
```
<img width="602" alt="Screenshot 2022-11-17 at 13 37 43" src="https://user-images.githubusercontent.com/4697738/202448606-6f176ce6-03e8-435a-adcd-109cd8bb32cf.png">

**Comment by eguiraud** [comment]
Shouldn't that be the default behavior? :smile: 

> It makes sense only if you turn on the "Event Statusbar" (as said in the doc)

Where in the doc? https://root.cern/doc/master/classTFile.html#abfd68d5396de59a1c3cf6a2e1bdb8563

**Comment by eguiraud** [comment]
sounds great! doing sensible things by default has always been in fashion :smile:
