### ISSUE TITLE
[ntuple] C-style array members of a user-defined class are stored/retrieved as a scalar

### ISSUE THREAD

**Issue by jalopezg-r00t** [root-project/root#11732]
### Describe the bug
Reported by @Nowakus via e-mail: user-defined classes having members whose type is a C-style array of type `T` are stored/retrieved as a scalar.  Thus, only the first element of the array is read/written.

Specifically, for the following member definition:
```c++
unsigned char m_8pack[8];
```
the corresponding attached field is:
```
      Field 1.3.3    : m_8pack (std::uint8_t)
```

### Expected behavior
In principle we should be throwing, as C-style arrays are currently not supported in RNTuple - i.e. we are missing [here](https://github.com/root-project/root/blob/master/tree/ntuple/v7/src/RField.cxx#L830) a
```c++
if (dataMember->Property() & kIsArray)
   throw /*...*/;
```

However, not supporting C-style arrays might be a problem - please, comment here on it @Nowakus.

Also, in principle, it should be fairly straightforward to add support for single dimension C-style arrays, so we probably should go this way in the fix for this issue.

**Comment by Nowakus** [comment]
Right, I am making this request on behalf of ATLAS, who are writing this type of data member as part of the Event Header structure (in the GUIDs to be exact) which means it is in every data format ever produced (except maybe end-user flat ntuple files). And we have a single global EDM for everything, so changing the Header definition would create a schema difference between the new class and the old one in files. I am a bit afraid to go in that direction, it may create a mess.   
I will still check if some clever ROOT schema evolution may help here.
