### ISSUE TITLE
TH2::Fill(const char *namex, const char *namey, Double_t w) doesn't update fTsumwxy

### ISSUE THREAD

**Issue by YSelfTool** [root-project/root#11746]
This line:
https://github.com/root-project/root/blob/7aab9a2be02967dc75342b4fb3c01c98f2a5a2c9/hist/hist/src/TH2.cxx#L485

Should be `fTsumwxy += z * x * y;` instead, as in the other versions `TH2::Fill`.
This was changed by 4465976d5da9b6c18adff75c430958112e79bf94, previously `fTsumwxy` was updated.

**Comment by lmoneta** [comment]
Hi, 
That commit changed that behaviour on purpose, since there is no defined x and y value when the axis is alphanumeric. The bin centre corresponding to an arbitrary axes does not make sense. 
What is your use case and why you need to have the histogram x and y statistics for the label case ?

**Comment by YSelfTool** [comment]
I don't need the axis statistics, I just think that incrementing `fTsumwx2` twice in this function isn't correct.
It might be that the code in the `if` rarely happens and that if they are calculated the value is meaningless, but since the code to update the weighted axis sums exists, I would assume it should be the same as in all the other `TH2::Fill` functions and increment `fTsum(w|w2|wx|wx2|wy|wy2|wxy)` once each.
Currently, TH2::Fill with two bin names doesn't do that, instead it increments `fTsumwx2` twice.
I'm sorry if I misunderstood the function, I just stumbled upon what seemed to be a typo when rebasing some other patches. If I'm wrong about this, please close the issue.

**Comment by lmoneta** [comment]
Ah I understand now, yes in the case the condition is true, `fTsumwxy` is not update.
This is certainly an error,  I will make a PR fixing this.
Thank you for finding this out!

**Comment by guitargeek** [comment]
Actually fixed in 6.28.00, but that project didn't exist anymore on GitHub.
