### ISSUE TITLE
FindXROOTD adds libraries to link against irrespective of xrootd version used

### ISSUE THREAD

**Issue by andresailer** [root-project/root#11750]
Dear ROOT devs,

These lines in the FindXROOTD

https://github.com/root-project/root/blob/323c21416cea9a64080698c23a7e2f6f6d1808bf/cmake/modules/FindXROOTD.cmake#L137-L149

make some root libraries, e.g., libNetxNG.so, link against old versions of xrootd if they are found on the system, even though one wants to build against the new version of xrootd.
We for SPI run into this problem when building on a machine which just happens to have this installed, and we cannot control the packages.

e.g. this is printed during configure:
```
-- Found Xrootd version num: 5.3.1 (setting -DROOTXRDVERS=500030001)
--
--              libXrdMain not found: xproofd will be a wrapper around xrootd
--              include_dirs: /data/sftnight/build/workspace/lcg_release_pipeline/install/xrootd/5.3.1/aarch64-centos7-gcc8-opt/include/xrootd;/data/sftnight/build/workspace/lcg_release_pipeline/install/xrootd/5.3.1/aarch64-centos7-gcc8-opt/include/xrootd/private
--              libraries: /data/sftnight/build/workspace/lcg_release_pipeline/install/xrootd/5.3.1/aarch64-centos7-gcc8-opt/lib64/libXrdUtils.so;/usr/lib64/libXrdClient.so;/data/sftnight/build/workspace/lcg_release_pipeline/install/xrootd/5.3.1/aarch64-centos7-gcc8-opt/lib64/libXrdCl.so

```
This then causes problem when our ROOT is used on some other machine.
So at the moment we just patch these lines out. If you could consider dropping them, or some check based on xrootd version?

Thanks,
Andre

**Comment by andresailer** [comment]
No, we don't want to use the builtin xrootd.

**Comment by bellenot** [comment]
And I suppose adding the XROOTD you want in `CMAKE_PREFIX_PATH` doesn't help either? So should we introduce a way of specifying which version and/or which location XROOTD is taken from? Does XROOTD provide a standard way of finding it with CMake?

**Comment by bellenot** [comment]
OK, then I'll need to set-up a VM and investigate...

**Comment by guitargeek** [comment]
Re-opened because the `XRootDConfig.cmake` from xrootd upstream didn't work after all, see:
https://github.com/root-project/root/pull/14170
