### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Es-said** [root-project/root#11819]
Hi,
i try to t install root, i get the cMakelists.text issue
CMake Error: The source directory "/home/said/Desktop/product/root" does not appear to contain CMakeLists.txt.

how i can fix this problem.

**Comment by pamputt** [comment]
What commands did you type exactly? And what error do you get, if any?

**Comment by eguiraud** [comment]
Hi @Es-said ,

this is not a ROOT bug. It looks like the ROOT source directory that you are passing to the cmake configuration command does not contain ROOT sources (which come with a `CMakeLists.txt` file).

Feel free to use https://root-forum.cern.ch for further user support.
