### ISSUE TITLE
[RF] Problem writing RooMomentMorphND to workspace in RooFit

### ISSUE THREAD

**Issue by amcdouga** [root-project/root#11876]
### The observed bug
I have been using the RooMomentMorphND (and RooMomentMorphFuncND) classes, where I am trying to save these functions to a workspace .root file. I am not able to do this, as an error occurs specifically when trying to write this class to a workspace. Note this error is not seen when I tested on the RooMomentMorph class, only in the ND case. 

### To Reproduce
I have prepared a small example in order to reproduce the error: 
```c++
#include <iostream>
#include <fstream>
#include<TRandom.h>

float input_lambda(float width){
    return -6.347e-07*width*width+0.0015*width+1.835;
}

void exampleND(){
    auto myy = new RooRealVar("myy", "myy", 110., 155.);
    myy->setBins(450.);

    auto w = new RooWorkspace("w");

    auto hist_1 = new TH1F("hist_1_125","hist_1_125", 450, 110., 155.);
    for(double i=0; i<10000; i++){hist_1->Fill(gRandom->Gaus(125., input_lambda(1.)));}
    auto hist_400 = new TH1F("hist_400_125","hist_400_125", 450, 110., 155.);
    for(double i=0; i<10000; i++){hist_400->Fill(gRandom->Gaus(125., input_lambda(400.)));}
    hist_1->Scale(1./hist_1->Integral());
    hist_400->Scale(1./hist_400->Integral());

    auto data_sig_1 = new RooDataHist("data_sig_1", "data_sig_1", RooArgList(*myy), hist_1);
    auto data_sig_400 = new RooDataHist("data_sig_400", "data_sig_400", RooArgList(*myy), hist_400);

    auto hist_pdf_1 = new RooHistPdf("hist_pdf_1", "hist_pdf_1", RooArgList(*myy), *data_sig_1);
    auto hist_pdf_400 = new RooHistPdf("hist_pdf_400", "hist_pdf_400", RooArgList(*myy), *data_sig_400);

    std::vector<float> Lambda_list = {1., 400.};
    auto Lambda = RooRealVar("lambda", "lambda", 1., 400.);
    auto paramVec = TVectorD(2);
    for (int j = 0; j < 2; ++j){
	paramVec[j] = Lambda_list[j];
    }

    auto morph_ND = new RooMomentMorphND("morph_ND","morph_ND", Lambda, RooArgList(*myy), RooArgList(*hist_pdf_1, *hist_pdf_400), paramVec, RooMomentMorphND::Linear);

    w->import(*morph_ND);
    w->Print();
    w->writeToFile("test_workspace.root");
}
```
If you run the code, you will see the the error occurs at line 40, where I see the error message cites the issue as being related to the "_referenceGrid" not able to be saved. 

The output seen is:
```
Warning in <TStreamerInfo::Build>: RooMomentMorphND: RooMomentMorphND::Grid has no streamer or dictionary, data member "_referenceGrid" will not be saved

 *** Break *** segmentation violation
    __boot()
    import os
```

### Setup
For the record, I am using ROOT Version: 6.24/06

**Comment by amcdouga** [comment]
Hi @guitargeek ,
Thanks for your response. Unfortunately as I mentioned in the description, I am also seeing a seg fault when using the RooMomentMorphFuncND class (though the error message is not the same as above related to the Grid being saved). 
I am only able to write this class to a workspace using the 1D versions - **not** the ND. 

Below you can find the example code I'm using to test the RooMomentMorphFuncND class, which creates the seg fault. 

`#include <iostream>
#include <fstream>
#include<TRandom.h>

float input_lambda(float width){
	return -6.347e-07*width*width+0.0015*width+1.835;
}

void exampleND_v2(){
    auto myy = new RooRealVar("myy", "myy", 110., 155.);

	myy->setBins(450.);

	auto w = new RooWorkspace("w");

	auto hist_1 = new TH1F("hist_1_125","hist_1_125", 450, 110., 155.);
	for(double i=0; i<10000; i++){hist_1->Fill(gRandom->Gaus(125., input_lambda(1.)));}
	auto hist_400 = new TH1F("hist_400_125","hist_400_125", 450, 110., 155.);
	for(double i=0; i<10000; i++){hist_400->Fill(gRandom->Gaus(125., input_lambda(400.)));}
	hist_1->Scale(1./hist_1->Integral());
	hist_400->Scale(1./hist_400->Integral());

	auto data_sig_1 = new RooDataHist("data_sig_1", "data_sig_1", RooArgList(*myy), hist_1);
	auto data_sig_400 = new RooDataHist("data_sig_400", "data_sig_400", RooArgList(*myy), hist_400);

    auto hist_func_1 = new RooHistFunc("hist_func_1", "hist_func_1", RooArgList(*myy), *data_sig_1);
    auto hist_func_400 = new RooHistFunc("hist_func_400", "hist_func_400", RooArgList(*myy), *data_sig_400);

	std::vector<float> Lambda_list = {1., 400.};
	auto Lambda = RooRealVar("lambda", "lambda", 1., 400.);

	auto paramVec = TVectorD(2);

	for (int j = 0; j < 2; ++j){
		paramVec[j] = Lambda_list[j];
	}

	auto morph_ND = new RooMomentMorphFuncND("morph_ND","morph_ND", Lambda, RooArgList(*myy), RooArgList(*hist_func_1, *hist_func_400), paramVec, RooMomentMorphFuncND::Linear);

	morph_ND->Print();
	w->import(*morph_ND);
	w->Print();
	w->writeToFile("test_workspace.root");
}`

Do you know if something can be done to fix this?

**Comment by guitargeek** [comment]
Ah, sorry I missed that!

Well, the `RooMomentMorphFuncND` makes the mistake of having a pointer to the last cached normalization set as a data member, and it is not excluded from IO:
https://github.com/root-project/root/blob/master/roofit/roofit/inc/RooMomentMorphFuncND.h#L133

You can therefore make the writing work if you first evaluate your function with a normalization set, and make sure that the normalization set is still alive during `writeToFile()` such that the pointer is not invalid:

```C++
    RooArgSet nset{*myy};
    morph_ND->getVal(&nset);
    
    morph_ND->Print();
    w->import(*morph_ND);
    w->Print();
    w->writeToFile("test_workspace.root");
```

This is of course annoying, and I will quickly fix this. The `_curNormSet` member should be excluded from IO.

**Comment by guitargeek** [comment]
Clearly, the original developers didn't care about IO for these classes. It's likely that you will run into other problems. If yes, please let me know here!

**Comment by amcdouga** [comment]
Ah great thanks! I confirm it works for me with the lines of code you mentioned to add. 
This will be fine for now, I'll keep you updated in case I have any further issues!
