### ISSUE TITLE
[RF]  RooAbsPdf::fitTo: would it be possible to add an option to control maximal number of calls? 

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#11875]
### Is your feature request related to a problem? Please describe.

Rather often for minimisation in `RooFit`,  using `RooAbsPDf::fitTo`,  for complicated functions a maximal number of calls is reached.  Since there is no direct war to access this parameter of `RooMinimiser` from  `RooAbsPDf::fitTo`,
for such cases I need to switch  from   `RooAbsPdf::fitTo` to  a manual creation of  `RooMinimiser` object, 
configure it and use it to minimize  (manually created) NLL. 

### Describe the solution you'd like

It will be very good to have a dedicated option(`RooCmdArg`)  to `RooAbsPdf::fitTo` function that allows to redefine the default number of calls, such that one can use it together with other options, e.g. 

```
dataset = ...
pdf = ...
result = pdf.FitTo ( dataset , ROOT.RooFit.Save() , ROOT.RooFit.MaxCalls( 10000 ) , ... )
```
 
### Describe alternatives you've considered

The standard way that I use , is in case `RooAbsPdf::fitTo` reaches maximal number of calls, switch 
to manual creation and configuration of `RooMinimiser`, manual creation of NLL and edssentially bypass very nice and convinient `RooAbsPdf::fitTo` interface.

**Comment by guitargeek** [comment]
Thanks, I think this is a good idea! I have opened a PR to add support for this:
https://github.com/root-project/root/pull/11903
