### ISSUE TITLE
PyROOT: wrong overload resolution for C++ functions from python 

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#11924]
- [ ] Checked for duplicates

### Describe the bug

For ROOT 6.27  (LCG dev23 nightly slot) I see a wrong overload resolution for pair of functions that takes argumentof type `double` and `std::complex<double>`. The complex veruison of function is invoked, whle `double` version is ignored:

see  [here](https://gist.github.com/VanyaBelyaev/2cd0280e1e5584a74652c9bfd8f2f2af)

### Expected behavior

I would expect the proper overleoad resolution: the `double` function is inviked for `double` argument 
and `std::complex<double>` version is invoked for the `complex` argument

### To Reproduce

 see the gist [here](https://gist.github.com/VanyaBelyaev/2cd0280e1e5584a74652c9bfd8f2f2af)

### Setup

 1. ROOT Version 6.27 
 2. LCG dev3 nightly cvmfs slot,  `x86_64-centos7-gcc12-opt` platform

**Comment by VanyaBelyaev** [comment]
The output is here:
```
Function(x):  myfun(1.0)=(1+0j)
Function(x):  myfun((1+1j))=(1+1j)
```
The first line demonstrates the problem: 
here I expect to obtain `double` value  instead of `complex`.  
For both argument type, `std::complex<double>` version of the function is invoked

**Comment by vepadulano** [comment]
Hi @VanyaBelyaev ,
Thanks for reaching out! I can't take a look at this right now, but I know the place where overload resolution happens and it is not the first time that I see this unexpected behaviour from cppyy. I assign this to myself, will let you know when I have news.
