### ISSUE TITLE
macOS linking `-flat_namespace` changes user-facing behavior

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#11937]
From @henryiii :

> ROOT can't pass homebrew's audit any more because it is now injecting `-flat_namespace`. Flat namespaces have been deprecated since the move to Intel. I believe this was done due to `-undefined dynamic_lookup` producing a warning - Apple plans to add something to replace this in the future, but it's not the old `-flat_namespace`. See [Homebrew/homebrew-core#114543 (comment)](https://github.com/Homebrew/homebrew-core/pull/114543#issuecomment-1330719444)
> Flat namespace makes major changes to the layout, is more deprecated than dynamic_lookup, and isn't supposed to even work in conda-forge. See also https://github.com/pybind/pybind11/pull/4301 .
> `-undefined dynamic_lookup` does silence the linker on missing symbols, that's what it's for. The problem is that the method it uses is deprecated, producing a warning (and already broken in iOS) `-flat_namespace` doesn't just silence the linker, it changes the binary layout for every symbol. You could always just silence the warning `-Wl,-w` or `-Wl,-no_fixup_chains`; this will eventually break, but is less deprecated than `-flat_namespace`.
> Apple's official statement is basically "live with the warning for now, we'll find a way to not break all CPython extensions eventually" from what I gather.

**Comment by henryiii** [comment]
Apple's solution was to default "no-fixup-chains" to on when `undefined dynamic_lookup` is passed; you can enable it for older versions to hide the warning as well, see https://github.com/pybind/pybind11/pull/4301#issuecomment-1446246379 and the linked CPython issue. Not sure yet if it causes issues for older versions that don't produce the warning in the first place.
