### ISSUE TITLE
[RF] Remove RooFormula code for gcc <= 4.8 when minimum standard is raised to C++17

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#11964]
This issue serves as a reminder that the code behind `#ifndef ROOFORMULA_HAVE_STD_REGEX` in [RooFormula.cxx](https://github.com/root-project/root/blob/master/roofit/roofitcore/src/RooFormula.cxx#L627) can be removed once the minimum C++ standard for ROOT is raised to C++17, because then gcc 4.8 is not supported anymore anyway. At that point, `std::regex` probably also works with visual studio, so the `#ifndef _MSC_VER` check can probably be removed in the same go.

See #8583 as a reference for what files to check to know what the minimum supported C++ standard of ROOT is.

**Comment by hahnjo** [comment]
I think already the switch to C++14 made GCC 4.8 effectively unsupported, so you may already be able to do this now?

**Comment by guitargeek** [comment]
Okay that may be, I don't remember this very well. I have opened a PR to remove it and I'll just ask in the daily or group meeting if anyone has objections. Thanks for pointing this out!
