### ISSUE TITLE
Is this line surplus to requirements? (or am I missing its purpose?)

### ISSUE THREAD

**Issue by HenryDayHall** [root-project/root#11971]
- [ x] Checked for duplicates

### Describe the bug

[Line 98 of root/tree/dataframe/src/RRootDS.cxx](https://github.com/root-project/root/blob/master/tree/dataframe/src/RRootDS.cxx#L98) looks like it might be left over from a previous incarnation. 

I'm interested in finding out if this is a bug because I'm trying to subclass RDataSource, and my subclass isn't working, so perhaps I'm not properly understanding how this one worked...

**Comment by ferdymercury** [comment]
It seems like a leftover from this commit https://github.com/root-project/root/commit/b1257ba27a7139e0c927693fded3b243b3f94b33

**Comment by eguiraud** [comment]
Hi @HenryDayHall ,

yes that line is a leftover and #11972 will remove it (thanks to @ferdymercury ).

I suggest looking at RCsvDS, RNTupleDS or RArrowDS (ordered from simpler to more complex) for existing implementations of data sources. RRootDS is unused and we might remove it in the future.
