### ISSUE TITLE
[ntuple] `RNTupleReader::Show()` produces empty output if user does not impose a model

### ISSUE THREAD

**Issue by jalopezg-git** [root-project/root#12031]
- [x] Checked for duplicates

### Describe the bug
Calling `RNTupleReader::Show()` on an instance where the model is generated from ntuple metadata on storage yields an empty JSON output.
However, as can be seen below, calling `LoadEntry()` triggers model generation from the ntuple descriptor and the following `Show()` call produces the expected output.  This results in surprising behaviour.

```c++
root [] auto ntuple = ROOT::Experimental::RNTupleReader::Open(“ntuple”, “/tmp/out.ntuple”);
root [] ntuple->Show(0);
{}
root [] ntuple->LoadEntry(0);
root [] ntuple->Show(0);
{
  “i”: 42,
  “f”: 12.2313
}
```

### Expected behavior
If `LoadEntry()` generates the model from the ntuple descriptor, most probably `Show()` should also do it.

**Comment by enirolf** [comment]
Hi Javier, I opened a PR that addresses this issue: #12026!
