### ISSUE TITLE
TSpline SaveAs not using equidistant and loss of precision

### ISSUE THREAD

**Issue by HelmutCERN** [root-project/root#12091]
The TSpline3::SaveAs and TSpline5::SaveAs methods have two types of bugs

1)
if (klow > fNp-1) klow = fNp-1      is generally true such that equidistant knots are not used.
if (klow > fNp-1) klow = fNp-1      looks ok, to be used in lines 931,  1737

2) double constants are written with %g  resulting in a major loss of precision.
Proposed fix :
replace %g with %.17g
replace  char numb[20]         -->   char numb[30]
replace  snprintf(numb,20,     -->    snprintf(numb,30,

Can be checked as follows :
```
const int n=11;
Double_t x[n],y[n];
for(int i=0; i<n; ++i) {
  x[i]=i*0.1;
  y[i]=sqrt(2.)*pow(x[i],2); // simple quadratic polynomial
}
//TSpline3* s=new TSpline3("spline", 0, 1, y, n);
TSpline5* s=new TSpline5("spline", 0, 1, y, n);
s->SaveAs("spline.cc");
int prec=15,wid=prec+7;
.L spline.cc
std::cout << "    x" << setw(wid) << "y" << setw(wid) << "spline" << setw(wid) << "diff" << '\n';
for(int i=0; i<n; ++i) {
  std::cout << setw(5) << x[i] << setw(wid) << y[i] << setw(wid) << spline(x[i]) << setw(wid) << y[i]-spline(x[i]) << std::endl;
}
```

With the proposed changes, function and spline values agree, diff = 0

Loss in precision by writing double values with an insufficient number of digits in root has been observed before, see  https://sft.its.cern.ch/jira/browse/ROOT-8844
Maybe a good idea to check this more generally

Cheers, Helmut Burkhardt

[TSpline.cxx.zip](https://github.com/root-project/root/files/10480476/TSpline.cxx.zip)

**Comment by ferdymercury** [comment]
PR solving these items here: https://github.com/root-project/root/pull/15067 and https://github.com/root-project/root/pull/15078
