### ISSUE TITLE
[ntuple] `RNTupleView`'s move ctor causes double delete

### ISSUE THREAD

**Issue by bernhardmgruber** [root-project/root#12136]
### Describe the bug
`RNTupleView` advertises a defaulted move constructor, but unconditionally frees state in it's destructor causing a double free in the destructor of the second instance. This is caused by the call to `fField.DestroyValue(fValue);` in the dtor. `fValue` is copyable and moveable since the copy special member functions are not deleted, but contains pointers to allocated memory which are not duplicated during copies or transferred during a move (with leaving the moved from pointer `nullptr`) and thus shared between two instances of `RNTupleView`. Although the documentation of `RFieldValue`, the type of `fValue`, claims that the class owns no memory, the class receives a heap allocated value during the call chain of the constructor initialization list of `RNTupleView`: `fValue(fField.GenerateValue())`.

Since the ownership model is convoluted to me, I cannot propose an easy fix. From the perspective of `RNTupleView`, `RFieldValue` would need a user-defined move ctor transferrign ownership of the heap-allocated pointer and `RNTupleView`'s dtor needs to be able to detect and handle a moved-from state. But the former is against the documented intent of the class, so I need to leave this to the designers of those classes :)

### Expected behavior
The move ctor of `RNTupleView` should let the dtors of both `RNTupleView` instances finish correctly.

### To Reproduce

Example:
```c++
        auto ntuple = RE::RNTupleReader::Open(RE::RNTupleModel::Create(), "DecayTree", "B2HHH~none.ntuple");
        {
            auto viewH1IsMuon = ntuple->GetView<int>("H1_isMuon");
            {
                auto copy{std::move(viewH1IsMuon)};
            } // dtor for copy, frees shared state
        } // dtor for viewH1IsMuon, double free
```

I assume the  problem does not depend on the input file, so it can probably be reproduced in a smaller setup.

### Setup
```
bgruber@graviola:$ root --version
ROOT Version: 6.29/01
Built for linuxx8664gcc on Jan 16 2023, 14:47:00
From remotes/origin/HEAD@v6-29-01-212-gc8ad008463
```
Built with g++-12 on Ubuntu 22.10.

**Comment by bernhardmgruber** [comment]
Thinking further about this, an `RNTupleView` seems to be a lightweight object, that stores some field meta data and a field value as a backup storage for reading `T`s that are not mappable. I see no big reason why an `RNTupleView` couldn't be copyable as well.

Conjecturing further, if RNTuple supported parallel reading form multiple threads, it would actually be great to pull an instance of `RNTupleView`  from an `RNTupleReader` and than pass a copy to each of N threads, which would then start reading non-overlapping subranges.

**Comment by jalopezg-git** [comment]
> From the perspective of `RNTupleView`, `RFieldValue` would need a user-defined move ctor transferrign ownership of the heap-allocated pointer and `RNTupleView`'s dtor needs to be able to detect and handle a moved-from state. But the former is against the documented intent of the class, so I need to leave this to the designers of those classes :)

I don't see why that is against the documented intent for the class.  Move-constructing (or move-assigning) are allowed to leave the original object in a valid but undetermined state, i.e. it should be okay if, upon move, we leave `RFieldValue::fRawPtr` to `nullptr`.

> Conjecturing further, if RNTuple supported parallel reading form multiple threads, it would actually be great to pull an instance of `RNTupleView` from an `RNTupleReader` and than pass a copy to each of N threads, which would then start reading non-overlapping subranges.

Actually, I think this can be done. @jblomer, anything against?

**Comment by silverweed** [comment]
I believe this issue was fixed by the various internal reworks of RField and RNTupleView (such as #13264 and #16556).
I tested the reproducer and it doesn't cause a double free anymore.
@jblomer could you please confirm this can be closed?
