### ISSUE TITLE
ROOT Head fails to compile on macOS(11, 12) since Jan 27, 2023

### ISSUE THREAD

**Issue by andresailer** [root-project/root#12130]
### Describe the bug
In the lcgcmake build system
Compiling ROOT master on macOS 11 (http://cdash.cern.ch/viewFiles.php?buildid=218660) or 12 (http://cdash.cern.ch/viewFiles.php?buildid=218674) fails to compile with the error message

```
[ 55%] Copying clang's __clang_hip_libdevice_declares.h...
In file included from /Users/sftnight/build/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/macosx/src/TMacOSXSystem.mm:12:
/Users/sftnight/build/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/macosx/inc/TMacOSXSystem.h:16:10: fatal error: 'TUnixSystem.h' file not found
[ 55%] Linking CXX static library ../../libLLVMDebugInfoCodeView.a
#include "TUnixSystem.h"
```

Seems related to #10690 Which was touching the related CMakeLists.txt files

### Expected behavior

Root compiles successfully on macOS

### Setup

1. ROOT version: master
2. Operating system: macOS 11, 12
3. git clone

**Comment by amadio** [comment]
Yes, I discussed this with @hageboeck and a fix is coming soon.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by andresailer** [comment]
Thanks!
