### ISSUE TITLE
Strange behaviour in interpreter in master/6.28 when initialising vectors

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#12164]
This simple code, gives a strange behaviour when running it within the ROOT prompt in 6.28 and master.
In ROOT master and 6,28 it seems the vector is initialised with the values used the first time and not with the new ones.  
It works fine in 6.26, where the second time the vector passed to the DummyBroadCast function is initialised correctly. 

```
.L testBroadCast.hxx
Test1::Session s1;
Test2::Session s2;
```

Here is the code : `testBroadCast.hxx`

```
#include <iostream>
#include <vector>

template<class T>
void DummyBroadCast(const T* data, std::vector<size_t> shape, std::vector<size_t> targetShape) {

   std::cout << "target shape ";
   for (size_t i = 0; i < targetShape.size(); i++) std::cout << targetShape[i] << " ";
   std::cout << std::endl;

}

namespace Test1 {

   struct Session {
      
   std::vector<float> fTensor_conv0bias = std::vector<float>(4);
   float * tensor_conv0bias = fTensor_conv0bias.data();
   std::vector<float> fTensor_conv0biasbcast = std::vector<float>(64);
   float * tensor_conv0biasbcast = fTensor_conv0biasbcast.data();

      Session() {

         std::vector<size_t> shape =  { 4 , 1 , 1 };
         std::vector<size_t> targetShape = { 2 , 4 , 4, 4 };
         DummyBroadCast(tensor_conv0bias, shape, targetShape);

      }

   };
}

namespace Test2 {

   struct Session {

   std::vector<float> fTensor_conv0bias = std::vector<float>(4);
   float * tensor_conv0bias = fTensor_conv0bias.data();
   std::vector<float> fTensor_conv0biasbcast = std::vector<float>(100);
   float * tensor_conv0biasbcast = fTensor_conv0biasbcast.data();

      Session() {

         std::vector<size_t> shape =  { 4 , 1 , 1 };
         std::vector<size_t> targetShape = { 2 , 4 , 5, 5 };
         DummyBroadCast(tensor_conv0bias, shape, targetShape);
         // DummyBroadCast(tensor_conv0bias, { 4 , 1 , 1 }, { 2 , 4 , 5, 5 });

      }

   };
}
```
 
This affects some failures seen in SOFIE test like 
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=ROOT-ubuntu2204,SPEC=soversion,V=master/lastCompletedBuild/testReport/projectroot.tmva.sofie/test/gtest_tmva_sofie_test_TestSofieModels/

**Comment by Axel-Naumann** [comment]
Thanks, I can reproduce this. :eyes:

**Comment by jalopezg-git** [comment]
Shorter reproducer below.  Investigating.
```c++
#include <iostream>
#include <vector>

struct Test1 {
  Test1() {
    std::vector<size_t> foo{4, 1 ,1};
    for (size_t i = 0; i < foo.size(); i++) std::cout << foo[i] << std::endl;
  }
};

struct Test2 {
  Test2() {
    std::vector<size_t> foo{2, 4, 5, 5};
    for (size_t i = 0; i < foo.size(); i++) std::cout << foo[i] << std::endl;
  }
};
```

**Comment by Axel-Naumann** [comment]
It's understood; Lorenzo will find a workaround for 6.28/00. We will still need to solve the underlying issue, but with lower urgency.

The issue is with llvm-IR using non-unique symbol names for the function-local constants, and re-using the already emitted symbols in subsequent modules (due to cling's "private" => "weak" symbol rewriting). A simple workaround is to use different variable names for the function-local constants.

**Comment by jalopezg-git** [comment]
> 

Thanks!  In particular, this seems to be happening for the underlying `std::initializer_list` used to initialize the vector.  Declaring a non-local `std::initializer_list` workarounds the problem.

**Comment by lmoneta** [comment]
This is another simple reproducible example: 
```
#include <iostream>
#include <vector>

void Dummy(const std::vector<size_t> & targetShape) {
   std::cout << "target shape ";
   for (size_t i = 0; i < targetShape.size(); i++) std::cout << targetShape[i] << " ";
   std::cout << std::endl;
}

struct Test1 {
      Test1() {
         Dummy({ 1 , 2 , 3, 4 });
      }
};

struct Test2 {
      Test2() {
         Dummy({ 5 , 6 , 7});
      }

};

**Comment by lmoneta** [comment]
And the result of doing
```
root [1] .L testDummy.hxx
root [2] Test1 t1;
target shape 1 2 3 4 
root [3] Test2 t2;
target shape 1 2 3 
```

**Comment by Axel-Naumann** [comment]
This seems to fix it for me: https://github.com/root-project/root/pull/12183
