### ISSUE TITLE
CI: log parsing

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#12185]
Can we add log parsing + PR commenting for the CI, e.g. using https://github.com/marketplace/actions/gcc-problem-matcher ?

**Comment by olemorud** [comment]
Log parsing (probably) causes memory leaks, will do some further investigation
https://github.com/olemorud/root/actions/runs/4242700680/jobs/7374536304#step:12:2483

![image](https://user-images.githubusercontent.com/82065181/220629069-bf6f6cd0-5ee8-4800-a95e-0509cf26cc7c.png)

The added action essentially just runs `echo ::add-matcher:: ./gcc_matcher.json`, where `gcc_matcher.json` contains
```json
{
    "problemMatcher": [
        {
            "owner": "gcc-problem-matcher",
            "pattern": [
                {
                    "regexp": "^(.*?):(\\d+):(\\d*):?\\s+(?:fatal\\s+)?(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            ]
        }
    ]
}
```
therefore this is likely an issue with github workflow problem matching in general and not this particular action

**Comment by Axel-Naumann** [comment]
Links to log files are wrong (line numbers are those of the source files having the warning). Possibly it just doesn't find the source file; see https://github.com/microsoft/vscode-cpptools/blob/a8285cbc0efb5b09c2d2229b0e0772dcb3b602df/Extension/package.json#L76-L94

**Comment by Axel-Naumann** [comment]
It would be super nice to have PR comments but that seems +/- impossible

**Comment by olemorud** [comment]
Managed to fix the file path thing, however it creates one annotation per matrix item. Will add an additional matrix option to enable/disable annotations so that only one build displays errors (probably the image with the latest gcc)
![image](https://user-images.githubusercontent.com/82065181/225619699-2781b334-7287-4660-95c4-9ddb63afd479.png)

**Comment by Axel-Naumann** [comment]
Please leave it as is, that's totally fine. Congrats for fixing it!
