### ISSUE TITLE
Directory Traversal Vulnerability

### ISSUE THREAD

**Issue by sarik-sarik** [root-project/root#12194]
My name is Mohammad Sarik, I am a Ethical hacker from INDIA. I found a Directory Traversal  Vulnerability in your website. There URL is this:- https://root.cern.ch/  and there  Parent Directory URL is this:- https://root.cern.ch/download/  Fix this Vulnerbility because it has very important Files & Data.I give you some proof in terms of screenshot.
![Screenshot_2023-02-01_12_44_54](https://user-images.githubusercontent.com/124130635/215976318-c8943307-7b48-46d7-8356-4828f8952432.png)
![Screenshot_2023-02-01_12_45_02](https://user-images.githubusercontent.com/124130635/215976326-32db3095-1b02-47dc-be54-9c64f8ffab0d.png)
![Screenshot_2023-02-01_12_45_18](https://user-images.githubusercontent.com/124130635/215976335-52ddb636-1931-4d5c-839b-44d10db7b90a.png)
 some proof in terms of screenshot.

**Comment by ferdymercury** [comment]
Did you read this part of the screenshot?

![image](https://user-images.githubusercontent.com/10653970/216037764-b54b0fdb-4ebf-40b0-b76d-e205753d5585.png)
