### ISSUE TITLE
`rootreadspeed --help` has "random" linebreaks

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#12224]
My terminal and `rootreadspeed --help` disagree on where the line breaks should be. I'd propose to not insert line breaks in rootreadspeed's text paragraph output and let the terminal handle that.

![image](https://user-images.githubusercontent.com/144675/216666135-5c556c9d-ac25-4e58-8467-673bf21f9bf9.png)

**Comment by couet** [comment]
PR here: https://github.com/root-project/root/pull/12241
