### ISSUE TITLE
No doc for `ROOT::RDF::Experimental::FromRNTuple`

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#12226]
IIUC, `ROOT::RDF::Experimental::FromRNTuple` is *the* main entry point for users to use `RNTuple`.

https://root.cern.ch/doc/master/namespaceROOT_1_1RDF_1_1Experimental.html#a1307bb3c667a2c5b77b09fb4ef2e161a

**Comment by eguiraud** [comment]
> is the main entry point for users to use RNTuple

I think that's the goal, but we are not there yet. We nevertheless need docs of course :)

**Comment by jblomer** [comment]
The main entry point is now actually identical for RNTuple and TTree. Fixed by #13090
