### ISSUE TITLE
Wrong conversion from Numpy Array to `std.vector` when using the wrong type

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#12230]
In PyROOT it is possible to convert a Numa array in a std.vector. However when the types are different instead of having an error, a wrong conversion happens. 
Here is an example:
```python
import ROOT
import numpy as np

x = np.array([1., 2., 3.])
v = ROOT.std.vector('float')(x)
print(v)
```
The obtained result is 
```
{ 0.00000f, 1.87500f, 0.00000f }
```
without getting any error. 

Instead if I use the correct type:
```
x = np.array([1.,2.,3.], dtype='float32')
v = ROOT.std.vector('float')(x)
print(v)
```
I obtain the correct result. 
This can cause give wrong results when calling from Python C++ functions taking std::vector as argument and the wrong type of Numpy array is passed.

**Comment by maximusron** [comment]
This issue is fixed by migrating to the new-style buffer interface:

 ```cpp
   if (PyObject_CheckBuffer(pyobject)) {
        Py_buffer bufinfo;
        memset(&bufinfo, 0, sizeof(Py_buffer));
```
      
Where we update the check to perform `if (check && bufinfo.itemsize != size)` determine incompatibility between the bit size of declared nd.array dtypes and the subscripted type in `cppyy.gbl.std.vector('type')` in CPyCppyy/src/Utility.cxx

@vepadulano

**Comment by vepadulano** [comment]
Fixed by https://github.com/root-project/root/pull/14507

**Comment by vepadulano** [comment]
Implemented upstream in https://github.com/wlav/CPyCppyy/blob/6539c24a1d8de7131a4c705cdf4d112faa19ed19/src/Utility.cxx#L808

**Comment by guitargeek** [comment]
The issue should be kept open until #14507 is merged, so we can set the correct milestone then
