### ISSUE TITLE
CI: releases

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#12272]
We need to be able to build release binaries. This is likely somehow connected also to the new CI :-) @smuzaffar I'd be interested to hear your thoughts on this...

Maybe we can address this (and still enable https://github.com/root-project/root/issues/12270) by the following sequence for the regular CI:

1. build ROOT
2. build the (tar.gz|rpm|deb|...) package
4. delete build and source dir
5. unpack the tar.gz package
6. run roottest
7. if release: make package available on root.cern

Installing a `.pkg` file on macOS, or an install package on Windows will be very intrusive, so maybe there we can only do steps 5 and 6 using a tar.gz / zip, but that's already better than what we have today. The goal should be to "test what we release".

**Comment by dpiparo** [comment]
Aren't we building those now? Is this item meant to refer to something else?

**Comment by ferdymercury** [comment]
Most of this issue is already solved. The remaining part is tracked here: https://github.com/root-project/root/issues/15861
