### ISSUE TITLE
[RF] Generation of RooKeysPdf fails if using protodata

### ISSUE THREAD

**Issue by elusian** [root-project/root#12286]
- [x] Checked for duplicates

### Describe the bug

`RooKeysPdf` do not have an internal generation method, and relies on numerical generation (e.g. `RooAcceptReject`).
However, if the call to generate contains `ProtoData`, the distribution of the generated data is not correct. 
I tried the same with other numerically generated pdf, specifically `RooGenericPdf`, but only `RooKeysPdf` seems to be affected.
This may be caused by a bad interaction between `RooKeysPdf` and `RooAcceptReject`, since adding a prototype switches the generator from `RooFoamGenerator` to `RooAcceptReject`.
I verified that forcing `RooFoamGenerator` (which I can only do by recompiling ROOT, as far as I know) solves the issue.

### Expected behavior

Generation works correctly regardless of prototype data

### To Reproduce

```
import ROOT

x = ROOT.RooRealVar('x', '', 0, 1)
pdf_x = ROOT.RooGenericPdf('pdf_x', 'x', [x])

# correct, of course
dt_base = pdf_x.generate({x}, NumEvents = 10000)

pdf_keys = ROOT.RooKeysPdf('pdf_keys', '', x, dt_base, ROOT.RooKeysPdf.MirrorBoth)

# also correct
dt_keys = pdf_keys.generate({x}, NumEvents = 10000)

y = ROOT.RooRealVar('y', '', 0, 1)
proto = ROOT.RooDataSet('proto_y', '', {y})
proto.add(ROOT.RooArgSet(y))

# still correct
dt_base_with_proto = pdf_x.generate({x}, NumEvents = 10000, ProtoData = proto)

# broken
dt_keys_with_proto = pdf_keys.generate({x}, NumEvents = 10000, ProtoData = proto)

frame = x.frame()
dt_base.plotOn(frame)
dt_keys.plotOn(frame, MarkerColor = 'b')
dt_keys_with_proto.plotOn(frame, MarkerColor = 'r')
dt_base_with_proto.plotOn(frame, MarkerColor = 'g')

frame.Draw()
```
Note that while in the example the prototype is useless this can easily happen when the `RooKeysPdf` is part of a larger pdf which does use the it

### Setup

ROOT master from LCG dev3

**Comment by guitargeek** [comment]
Thank you for reporting this!

**Comment by elusian** [comment]
Thank you for the fix! 
It appears that while forcing the use of `RooFoamGenerator` I simply skipped that code path...
