### ISSUE TITLE
ROOT 6.28.00 fails on s390x: Added modules have incompatible data layouts

### ISSUE THREAD

**Issue by ellert** [root-project/root#12293]
### Describe the bug

ROOT 6.28.00 fails on s390x

[100%] Generating tutorials/hsimple.root
cd /builddir/build/BUILD/root-6.28.00/s390x-redhat-linux-gnu/tutorials && LD_LIBRARY_PATH=/builddir/build/BUILD/root-6.28.00/s390x-redhat-linux-gnu/lib: ROOTIGNOREPREFIX=1 ROOT_HIST=0 /builddir/build/BUILD/root-6.28.00/s390x-redhat-linux-gnu/bin/root.exe -l -q -b -n -x hsimple.C -e return
[IncrementalJIT] addModule() failed: Added modules have incompatible data layouts: E-m:e-i1:8:16-i8:8:16-i64:64-f128:64-a:8:16-n32:64 (module) vs E-m:e-i1:8:16-i8:8:16-i64:64-f128:64-v128:64-a:8:16-n32:64 (jit)
Replaced symbol atexit cannot be found in JIT!
Replaced symbol at_quick_exit cannot be found in JIT!
Processing hsimple.C...
[IncrementalJIT] addModule() failed: Added modules have incompatible data layouts: E-m:e-i1:8:16-i8:8:16-i64:64-f128:64-a:8:16-n32:64 (module) vs E-m:e-i1:8:16-i8:8:16-i64:64-f128:64-v128:64-a:8:16-n32:64 (jit)
[IncrementalJIT] addModule() failed: Added modules have incompatible data layouts: E-m:e-i1:8:16-i8:8:16-i64:64-f128:64-a:8:16-n32:64 (module) vs E-m:e-i1:8:16-i8:8:16-i64:64-f128:64-v128:64-a:8:16-n32:64 (jit)

### Expected behavior

Working ROOT.

### To Reproduce

Build ROOT for s390x. Build fails when the hsimple.C macro is executed at the end of the build process with the above error.

### Setup

1. ROOT version 6.28.00
2. GNU/Linux on RHEL+EPEL 8, RHEL+EPEL 9, Fedora 36. Fedora 37, Fedora 38. Fedora 39 - same result on all
3. Package build from source.

### Additional context

This error is a regression wrt earlier versions that did not have this problem.

**Comment by vgvassilev** [comment]
@hahnjo, I remember seeing something similar in clang-repl and then having the TargetTriple be taken from clang instead of guessing: llvm/llvm-project@49f9532165f0cc0485a7da84662ebf63d155652c

**Comment by hahnjo** [comment]
@vgvassilev yes, and I recently implemented the same in Cling: https://github.com/root-project/root/pull/12218/commits/28853791e5070eb68034546f65f617911506e2cb

@ellert any chance you can test a fix interactively before we commit? The above commit probably doesn't apply cleanly, I will prepare a backport for `v6-28-00-patches`...

**Comment by hahnjo** [comment]
I had a deeper look and I think we need a second fix: In `clang-repl`, we propagate the entire `JTMB` which is used to create the `TargetMachine` and then the `DataLayout`. In Cling, we create one `TargetMachine` on our own and don't propagate the `JTMB` (yet -- we probably should!). So for now, we will also need to propagate the `DataLayout` manually, see https://github.com/root-project/root/pull/12335
