### ISSUE TITLE
[graphics] Consider adding legend to `TRatioPlot` example

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#12306]
Adding a legend to the first example in the [TRatioPlot documentation](https://root.cern.ch/doc/master/classTRatioPlot.html) would prevent recurring questions like these:

* https://root-forum.cern.ch/t/tlegend-disappears-when-i-add-a-tratioplot-pyroot/53609
* https://root-forum.cern.ch/t/creating-legend-for-upper-plot-in-tratioplot/35235

One should also add a not right at the example that the default drawing options for the histograms are `"hist"` and `"E"` for h1 and h2 respectively, and mention that these can be changed with `SetH1DrawOpt` and `SetH2DrawOpt` (as this also triggered questions on the forum).

**Comment by couet** [comment]
PR here: https://github.com/root-project/root/pull/12318 can you approve it?
