### ISSUE TITLE
[CI] Build is green even if tests are failing

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#12307]
See for example the centos8 build in this PR:
https://github.com/root-project/root/actions/runs/4161503868/jobs/7199554467

Here is a screenshot to archive what I saw there in case the results time out:
![Screenshot_2023-02-14_04-29-57](https://user-images.githubusercontent.com/6578603/218632202-07977e7b-1f5f-483e-a6f2-91093da019db.png)

**Comment by guitargeek** [comment]
Hi @olemorud and @Axel-Naumann, is this addressed now and the issue can be closed?

**Comment by olemorud** [comment]
Sorry for not addressing this issue earlier. Although I don't remember the reasoning, I believe it was concluded that the CI should not be red on test errors. If this is to be changed all there is to it is changing [this line](https://github.com/root-project/root/blob/aae1cd064679f440ad80f39e4ee56bb0c1d9d396/.github/workflows/root-ci-config/build_root.py#LL252C22-L252C22):

```diff

  251    if result != 0:
- 252       print_warning("Some tests failed")
+ 252       die(result, "Some tests failed", shell_log)
```

Would like @Axel-Naumann's input before closing

**Comment by Axel-Naumann** [comment]
Right - @smuzaffar was quite clear that we should separate build failures from test failures. But we now fail for build failures, too, so maybe including test failures in the failed state makes sense? Anyway, just pinging @smuzaffar for his recommendation + arguments before we decide what to do here!

**Comment by smuzaffar** [comment]
@Axel-Naumann , yes, for github actions, it makes sense to fail for every thing which should not happen either it is build or test failure.
My recommendation for not marking the job failed was for Jenkins type CI where a job failure should mean infrastructure issues which Jenkin's admins (or CI test developers) should look in to. Every other failure should be reported to the code developers.

**Comment by hahnjo** [comment]
Another implication is that binaries weren't uploaded anymore if testing failed; fixed in https://github.com/root-project/root/pull/12830
