### ISSUE TITLE
defect when drawing multiple histograms with Log Y axis

### ISSUE THREAD

**Issue by wright20** [root-project/root#12394]
### Expected behavior
The problem occurs when two histograms that were created with different upper edge of the last bin are drawn in the same pad with Log y axis.  I would expect that the edge of the last bin would be drawn as the minimum y value of the pad, instead it is always set to 1. This artifact is most noticeable when the histogram values are less than 1.

### To Reproduce
python3 demo.py  # produces demo.pdf
[demo.pdf](https://github.com/root-project/root/files/10851293/demo.pdf)

# demo.py
from ROOT import *

gStyle.SetOptStat(0)   # no statistics box
gStyle.SetOptTitle(0)  # no title

#....make two histograms with different xmax
h15 = TH1F('h15','test histogram', 15*2, 0, 15)
h25 = TH1F('h25','test histogram', 25*2, 0, 25)

gaus = gROOT.GetFunction('gaus')
gaus.SetParameters(1, 0, 15) # Constant, Mean, Sigma
h15.FillRandom('gaus', 10000)

gaus.SetParameters(1, 0, 25) # Constant, Mean, Sigma
h25.FillRandom('gaus', 10000)
h25.SetLineColor(2)

h15.Scale(.0005)
h25.Scale(.02)

h25.SetMaximum(10)
h25.SetMinimum(.01)

h25.Draw('hist')
h15.Draw('hist same')

gPad.SetLogy(1)
gPad.Print('demo.pdf')

### Setup
Root v6.26.10
Red Hat Enterprise Linux release 8.7 (Ootpa)
Installed and compiled from source

**Comment by couet** [comment]
```
   h15->Draw("hist same ][");
```
improves the plot.

**Comment by couet** [comment]
Simpler reproducer:
```
{
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);

   auto C = new TCanvas();
   C->Divide(2,1);

   auto h15 = new TH1F("h15","h15", 3, 10, 15);
   auto h25 = new TH1F("h25","h25", 5, 0, 25);

   h15->Fill(11,.5);
   h15->Fill(12,1.);
   h15->Fill(14,.5);
   h15->SetLineWidth(3);

   h25->Fill(1,1);
   h25->Fill(6,2);
   h25->Fill(11,3);
   h25->Fill(16,2);
   h25->Fill(23,1);
   h25->SetLineColor(2);
   h25->SetLineWidth(3);
   h25->SetMinimum(.05);

   C->cd(1);
   h25->Draw("hist");
   h15->Draw("hist same");
   gPad->SetLogy(1);
   gPad->SetGridx(1);
   gPad->SetGridy(1);

   C->cd(2);
   h25->Draw("hist");
   h15->Draw("hist same");
   gPad->SetGridx(1);
   gPad->SetGridy(1);
}
<img width="673" alt="Screenshot 2023-03-07 at 16 52 02" src="https://user-images.githubusercontent.com/4697738/223475015-4d72384f-e7d0-4d1c-8428-c3addbcd7973.png">

```

**Comment by couet** [comment]
Fix here: https://github.com/root-project/root/pull/12448
Thanks to have seen it.

**Comment by wright20** [comment]
Excellent! Thank you
