### ISSUE TITLE
pythonization problem with vector::operator== in 6.28.00.

### ISSUE THREAD

**Issue by scott-snyder** [root-project/root#12406]
hi -

We're seeing a problem with the pythonization of std::vector::operator==
with root 6.28.00 (at least with the version being built in dev4).

This was originally reported in the ATLAS context as ATEAM-885,
but i have reduced it here to a standalone reproducer in the attached
archive.

The included setup script should be appriate for lxplus7.
Run:

$ . ./setup
$ ./build.sh
$ python test.py

and it gives the errors:

IncrementalExecutor::executeFunction: symbol '_ZNSt7__equalILb0EE5equalIPK4TestS4_EEbT_S5_T0_' unresolved while linking symbol '__cf_13'!
You are probably missing the definition of bool std::__equal<false>::equal<Test const*, Test const*>(Test const*, Test const*, Test const*)
Maybe you need to load the corresponding shared library?

thanks,
sss

[pythonization-bug2.zip](https://github.com/root-project/root/files/10867231/pythonization-bug2.zip)

**Comment by vepadulano** [comment]
Hi, thanks for the report. A small update, this seems to be an issue since at least ROOT 6.24:

```
$: root --version
ROOT Version: 6.29/01
Built for linuxx8664gcc on Feb 26 2023, 17:20:00
From heads/master@v6-25-02-4093-g23b30e03c3
$: python test.py 
IncrementalExecutor::executeFunction: symbol '_ZNSt7__equalILb0EE5equalIPK4TestS4_EEbT_S5_T0_' unresolved while linking symbol '__cf_10'!
You are probably missing the definition of bool std::__equal<false>::equal<Test const*, Test const*>(Test const*, Test const*, Test const*)
Maybe you need to load the corresponding shared library?
```
```
$: root --version
ROOT Version: 6.26/10
Built for linuxx8664gcc on Nov 17 2022, 16:21:00
From @
$: python test.py
IncrementalExecutor::executeFunction: symbol '_ZNSt7__equalILb0EE5equalIPK4TestS4_EEbT_S5_T0_' unresolved while linking symbol '__cf_10'!
You are probably missing the definition of bool std::__equal<false>::equal<Test const*, Test const*>(Test const*, Test const*, Test const*)
Maybe you need to load the corresponding shared library?
```
```
$: root --version
ROOT Version: 6.24/06
Built for linuxx8664gcc on May 02 2022, 19:26:00
From @
$: python test.py 
IncrementalExecutor::executeFunction: symbol '_ZNSt7__equalILb0EE5equalIPK4TestS4_EEbT_S5_T0_' unresolved while linking symbol '__cf_9'!
You are probably missing the definition of bool std::__equal<false>::equal<Test const*, Test const*>(Test const*, Test const*, Test const*)
Maybe you need to load the corresponding shared library?
```

**Comment by scott-snyder** [comment]
Hm, yes --- maybe i reduced things too much.

As you said, the example here also fails with 6.26.08, which is what's used in the ATLAS development branch; however the full example that i started with does in fact work correctly with this version.

So, while there does seem to be an issue here, there seems to be something else going on as well...

**Comment by Axel-Naumann** [comment]
How much will it help ATLAS if I fix this reproducer? What is the actual failure's error message?

**Comment by elmsheus** [comment]
This problem is blocking ATLAS in adopting ROOT 6.28.x in production. 

We use an ATLAS specific pyROOT script 'diff-root' that compares AODs branch-by-branch in our CI and integration tests that is not working in ROOT 6.28.x with the symptoms described above. The original error message of this script is:

```
[..]
Py:diff-root         INFO comparing [2932] leaves over entries...
IncrementalExecutor::executeFunction: symbol '_ZNSt7__equalILb0EE5equalIPKN4xAOD28CaloClusterBadChannelData_v1ES5_EEbT_S6_T0_' unresolved while linking symbol '__cf_295'!
You are probably missing the definition of bool std::__equal<false>::equal<xAOD::CaloClusterBadChannelData_v1 const*, xAOD::CaloClusterBadChannelData_v1 const*>(xAOD::CaloClusterBadChannelData_v1
 const*, xAOD::CaloClusterBadChannelData_v1 const*, xAOD::CaloClusterBadChannelData_v1 const*)
Maybe you need to load the corresponding shared library?
cling JIT session error: Failed to materialize symbols: { (main, { _ZSteqISt6vectorIN4xAOD28CaloClusterBadChannelData_v1ESaIS2_EESaIS4_EEbRKS0_IT_T0_ESA_ }) }
IncrementalExecutor::executeFunction: symbol '_ZNSt7__equalILb0EE5equalIPK20TrigRoiDescriptor_p3S4_EEbT_S5_T0_' unresolved while linking symbol '__cf_452'!
You are probably missing the definition of bool std::__equal<false>::equal<TrigRoiDescriptor_p3 const*, TrigRoiDescriptor_p3 const*>(TrigRoiDescriptor_p3 const*, TrigRoiDescriptor_p3 const*, Trig
RoiDescriptor_p3 const*)
Maybe you need to load the corresponding shared library?
cling JIT session error: Failed to materialize symbols: { (main, { _ZN16__cppyy_internal8is_equalI30TrigRoiDescriptorCollection_p3S1_EEbRKT_RKT0_ }) }
cling JIT session error: Failed to materialize symbols: { (main, { _ZN16__cppyy_internal8is_equalI30TrigRoiDescriptorCollection_p3S1_EEbRKT_RKT0_ }) }
[..] 
```

**Comment by scott-snyder** [comment]
I've looked at this again, and in current dev4, anyway, the blocking issue is somewhat different, and it looks like we can avoid the issue on the ATLAS side.  Further details to follow.

**Comment by scott-snyder** [comment]
Further information from ATEAM-885:

Ok, i took another look at this.

Turns out we have problems with RootUtils::objetIsA:

{noformat}
TClass* objectIsA (PyObject* obj)
{
  PyObject* repr = PyObject_Repr (obj);
  if (!repr) return nullptr;
  const char* s = PyROOT_PyUnicode_AsString (repr);
  if (*s == '<') ++s;
  if (strncmp (s, "ROOT.", 5) == 0)
    s += 5;
  if (strncmp (s, "cppyy.gbl.", 10) == 0)
    s += 10;
  const char* p = strstr (s, " object ");
  if (!p) return nullptr;
  std::string name;
  name.reserve (p-s + 10);
  while (s < p) {
    if (*s == '.')
      name += "::";
    else
      name += *s;
    ++s;
  }
  TClass* cls = TClass::GetClass (name.c_str());
  Py_DECREF (repr);
  return cls;
}
{noformat}


We can identify at least three distinct problems here.

1. First, this code is stupid.  It's trying to get the TClass for a pyroot
   object.  It does this by calling repr on the object (which could result
   in something very large) and then trying to extract the class name
   and looking it up with TClass.  In fact, it looks like this hasn't
   actually been working for a while now, because the format of the repr
   string changed --- and now doesn't include the 'object' string.
   If i change this to instead use Py_TYPE(obj)->tp_name, then everything
   works (and much faster too!).

2. I originally added this code here, but from the comments, it was copied
   from the pyroot of the time.  The reason why we're doing this in this
   roundabout way to begin with is because the TPython interface doesn't
   supply any way to get the TClass from a pyroot object.  If it would
   add a call for that, than this could be streamlined.

3. Finally, there seems to have been a regression with finding the repr
   string for a pyroot object between 6.26.10 and dev4.  If i have a loop
   just calling repr for a vector<float> instance, it runs very slowly
   and eventually starts printing memory errors from cling.  But with 6.26.10,
   it runs much faster and does not start crashing.   It sounds sort of like
   code is now being repeatedly jitted each time with dev4, but i have
   not tried to verify that.

Anyway, this change gets at least the unit tests working.  Will try to get
that merged soon, and will try to report the repr issue separately.

**Comment by Axel-Naumann** [comment]
> will try to report the repr issue separately.

Thanks for investing your time here, much appreciated! I still want to debug this test failure here, so please leave this open independently of the progress you're making on the ATLAS side.

**Comment by wlav** [comment]
I can't imagine why you'd want to write a function like the above, certainly adding such a function to TPython would only be possible as a ROOT add-on (cppyy 4.0.0 will be free from `TClass` and already since 1.0.0, the CPython portion of cppyy is agnostic to it).

However, if you must, then `Py_TYPE(obj)->tp_name` isn't the ticket, but the `__cpp_name__` attribute is. The latter exists for the benefit of template instantiations and is the only place to guarantee you the correct (and valid) C++ name. In case of enums, Python-side derived classes, public typedefs of private nested classes, and probably some more corner cases, `Py_TYPE(obj)->tp_name` will fail.

**Comment by scott-snyder** [comment]
Thanks Wim; I had forgotten about __cpp_name__.  Changed to use that.

**Comment by guitargeek** [comment]
Thanks to the explanation of @wlav, this issue can be closed. If you have further issues with PyROOT, feel free to open new issues @scott-snyder!
