### ISSUE TITLE
CI: trigger custom config build for PRs through comments

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#12465]
E.g. if we have Fedora36 with no-imt and Fedora37 with imt, we see a failure in 37, we want to confirm that Fedora 36 work (or not) with imt.

Ideally `/build on Fedora36 with -Dimt-Off` (or whatever bot syntax)

**Comment by pcanal** [comment]
That feature has been replaced by the 're-run jobs' provided by the github GUI and by restarts when closing/re-opening a PR.
