### ISSUE TITLE
PyROOT: problems with Cling

### ISSUE THREAD

**Issue by Grufoony** [root-project/root#12481]
- [x] Checked for duplicates

### Describe the bug
When I run the Python script I get a cling warning:

    cling::DynamicLibraryManager::loadLibrary(): libGLU.so.1: cannot open shared object file: No such file or directory
    Error in <AutoloadLibraryMU>: Failed to load library /home/grufoony/root/lib/libEve.so.6.28.00cling JIT session error: Failed to 
    materialize symbols: { (main, { _ZeqRK7TStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE }) }

However, the code runs fine despite this error.

### To Reproduce
Run a python script from [this repository](https://github.com/SimonB00/WealthDistributionModel).
Also run a

    make all

command in order to compile and bind the c++ library.

### Setup
ROOT 6.28/00
Windows 11 - WSL2 Ubuntu 22.04.1

**Comment by dpiparo** [comment]
Hi @Grufoony , apologies for coming back so late to you. Would you be able to provide perhaps a minimal reproducer?

**Comment by dpiparo** [comment]
I cannot reproduce with 6.30 and master. Please do not hesitate to reopen if this is still an issue for you.
