### ISSUE TITLE
The problem with building ROOT v6-26-10 in debug mode on ubuntu 20.04

### ISSUE THREAD

**Issue by Denys-Klekots** [root-project/root#12492]
Dear developers,

I was trying to build ROOT v6-26-10 in debug mode, to be able to debug my custom projects that use the ROOT libraries.

At the moment of the compilation, I got the following error

```
In file included from /path/to/root_debug/root_src/graf3d/eve7/src/REveBoxSet.cxx:20:
/path/to/root_debug/root_src/builtins/nlohmann/json.hpp:2149:46: error: wrong number of template arguments (10, should be at least 0)
 2149 |     AllocatorType, JSONSerializer, BinaryType>
      |                                              ^
```
After this, there were a bunch of other errors and warnings, until the compilation was not crashed.

Here are the cmake flags I used
```
cmake -DCMAKE_BUILD_TYPE:STRING=Debug -G "Unix Makefiles" -DCMAKE_CXX_STANDARD:STRING=17 -DCMAKE_INSTALL_PREFIX:PATH=../root_debug/install -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON ../root_debug/root_src
```

I have installed nlohmann-json3-dev of version 3.7.3-1 in my machine.

Also, I compiled the same version of ROOT in release mode and it works.

Can you help me to build the root in debug mode, please?
With best regards,
Denys.

**Comment by bellenot** [comment]
I do't know... Can you try with this syntax:
```
cmake -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=../root_debug/install -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../root_debug/root_src
```
And if it still doesn't work, please provide the full log

**Comment by Denys-Klekots** [comment]
Dear Bertrand,

Here is the entire log of the cmake output and the make output. Here I used the C++17 standard. Please note, the command with which I called cmake is specified in the first line of the log file.
[cmake_debug.log](https://github.com/root-project/root/files/10993550/cmake_debug.log)
[make_debug.log](https://github.com/root-project/root/files/10993551/make_debug.log)

Here are also CMakeError.log and CMakeOutput.log.
[CMakeError.log](https://github.com/root-project/root/files/10993778/CMakeError.log)
[CMakeOutput.log](https://github.com/root-project/root/files/10993780/CMakeOutput.log)


I've also compiled the release mode with C++14, and it works just fine. Here are the output logs.
[cmake_release.log](https://github.com/root-project/root/files/10993654/cmake_release.log)
[make_release.log](https://github.com/root-project/root/files/10993655/make_release.log)

After this, I tried to compile the release mode with the C++17 standard, but it fails.

Meanwhile, I cannot use C++14 with the debug mode.
Here is the cmake output if I'm trying to configure the project in debug mode with C++14.

```
CMake Error at cmake/modules/RootBuildOptions.cmake:405 (message):
  >>> At least C++17 standard required with root7, please enable it using
  CMake option: -DCMAKE_CXX_STANDARD=17
Call Stack (most recent call first):
  CMakeLists.txt:157 (include)
```

So I suggest that the problem rather is with C++17.

With best regards,
Denys.

**Comment by bellenot** [comment]
So if you cannot use c++17, why not simply use c++14 and disable root7?

**Comment by linev** [comment]
Hi,

Can you check which version of `nlohmann/json.hpp` is installed on your system?

**Comment by Denys-Klekots** [comment]
Hello Sergey,

I'm using version 3.7.3-1 of `nlohmann/json.hpp`

Here is the output from the apt -s install nlohmann-json3-dev command.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nlohmann-json3-dev is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
```

Dear Bertrand,

I will definitely disable root7 and try to recompile ROOT. Thank you for this suggestion.

With best regards,
Denys.

**Comment by linev** [comment]
> I'm using version 3.7.3-1 of nlohmann/json.hpp

Versions below 3.9 are not supported. 
You should try to build ROOT with option `-Dbuiltin_nlohmannjson=ON`.

**Comment by linev** [comment]
> I will definitely disable root7

`nlomann/json.hpp` used also in i/o classes of ROOT, therefore one need to have proper configuration anyway

**Comment by Axel-Naumann** [comment]
@linev can we make CMake complain about nlohmann-json being too old?

**Comment by linev** [comment]
Actually, `cmake` makes warning if older `nlohmann/json.hpp` version installed on the system and automatically switching to built-in version. But seems to be system-wide include is preferred during compilation.

**Comment by dpiparo** [comment]
The issue has been solved.
