### ISSUE TITLE
Backport missing commits to our fork of the LLVM monorepo

### ISSUE THREAD

**Issue by vgvassilev** [root-project/root#12533]
Hi @Axel-Naumann,

  Could you backport [root-project/root#11874](https://github.com/root-project/root/pull/11874), [root-project/root#12179](https://github.com/root-project/root/pull/12179), [root-project/root#12418](https://github.com/root-project/root/pull/12418) to the monorepo. This currently makes theoretically impossible for https://github.com/root-project/root/pull/12523 to go in.

**Comment by hahnjo** [comment]
Done with https://github.com/root-project/root/pull/12834
