### ISSUE TITLE
[math] Mark `TRandom3::Rndm()` and similar functions `final` for performance

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#12547]
The fact that TRandom3::Rndm() etc. are not marked final is a sensible hit in performance for applications that call it in an event loop (because the compiler does not dare de-virtualize the call, so you always have a cache miss/data dependency when you encounter the call).

**Comment by Axel-Naumann** [comment]
See https://github.com/root-project/root/pull/12964

**Comment by dpiparo** [comment]
@lmoneta can now the PR be merged and the issue closed?

**Comment by guitargeek** [comment]
Closing as "won't fix" as discussed here:
https://github.com/root-project/root/pull/12964#issuecomment-2077004702
