### ISSUE TITLE
std::length_error exception when RDataFrame is created

### ISSUE THREAD

**Issue by dkasianov** [root-project/root#12540]
- [ ] Checked for duplicates

### Describe the bug

Exception is throwing std::length_error with message vector too long.

### To Reproduce

```
#include <ROOT/RDataFrame.hxx>
#include <TFile.h>
#include <TTree.h>

int
main(int argc, char* argv[])
{
    std::uint32_t v0 = 0;
    std::uint32_t v1 = 0;

    TFile file("sbx.root", "RECREATE");
    TTree tree("tree-name", "tree-title");
    tree.Branch("v0", &v0);
    tree.Branch("v1", &v1);

    for (std::size_t i = 0; i < 10; ++i)
    {
        v0 = i;
        v1 = i * 2;
        tree.Fill();
    }

    tree.Scan();
    tree.Write();

    try
    {
        ROOT::RDataFrame df(tree);
    }
    catch (std::length_error& ex)
    {
        std::cout << ex.what() << std::endl;
        std::cout << std::endl;
    }

    return 0;
}
```

### Setup

ROOT version 6.26.10 and 6.29.01
Operating system Windows Visual Studio 2022 64-bit x64 
How you obtained ROOT Downloaded exe installer

**Comment by pcanal** [comment]
As a side note, this example works perfectly on linux.

**Comment by dkasianov** [comment]
Is any workaround available?

**Comment by dkasianov** [comment]
Addition condition:
I actually build exe in Debug mode, that throws exception, Build Release is ok.

**Comment by bellenot** [comment]
Sorry for the delay. If you build in Debug with debug runtime libraries (`/MDd` compiler flag), that might be the issue. The ROOT debug build is linked with the Release runtime libraries (`/MD`), for several technical reasons, which is more or less equivalent to the `RelWithDebInfo` build type. Can you try to build in `RelWithDebInfo` instead and let us know?
This is not strictly speaking a bug, but a runtime libraries incompatibility...

**Comment by dkasianov** [comment]
Yes, RelWithDebInfo also works.
_And note you will also need the Debug version of all the external libraries. Please let me know if that is good enough for you._
I was not sure about that, I thought it was ok, at least in linux it was ok. And I never saw in documentation explicitly say saw. Because if different runtime is used it usually not compiled. I think it is good enough.

**Comment by bellenot** [comment]
OK, thanks, then I close this issue.
