### ISSUE TITLE
TTimeStamp skips days when using date and time constructor before 1970-01-01

### ISSUE THREAD

**Issue by ccorti87** [root-project/root#12569]
- [x] Checked for duplicates

### Describe the bug
For dates before Jan 1st, 1970, `TTimeStamp` sometimes gives incorrect results when it’s initialized with date and time, whether using the unsigned date and time constructor, or the explicit year, month, day, hours, minutes, and seconds constructor.
There are no problems if `TTimeStamp` is initialized from a `time_t`.

### Expected behavior
`TTimeStamp(19600822, 0u, 0u, true, 0).AsString("s")` returns `"1960-08-23 00:00:00"` instead of `"1960-08-22 00:00:00"`.
Similarly for `TTimeStamp(1960, 8, 22, 0, 0, 0)`.
Casting it to `time_t` yields `-295315200`, which is indeed the Unix time for `"1960-08-23 00:00:00"`.
`TTimeStamp(-295401600, 0).AsString("s")` returns correctly `"1960-08-22 00:00:00"`.

### To Reproduce
See code and various tests on the [ROOT forum](https://root-forum.cern.ch/t/bug-in-ttimestamp-days-are-skipped-when-using-date-and-time-constructor/54201/1).

### Setup
ROOT Version: 6.26/02, heads/latest-stable@c8d49336
Platform: Ubuntu 22.04.2
Compiler: linuxx8664gcc
Compiled with `cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE='RelWithDebInfo' -Dbuiltin_vc='ON' -Dcudnn='OFF' -Dcfitsio='ON' -Dgviz='ON' -Dqt5_web='ON' -Dunuran='ON' -Dvc='ON' -Dveccore='ON' ../git`

**Comment by ccorti87** [comment]
Analysis of the bug origin and proposed fix on the [ROOT forum](https://root-forum.cern.ch/t/bug-in-ttimestamp-days-are-skipped-when-using-date-and-time-constructor/54201/9).

**Comment by couet** [comment]
A simple workaround that does not involve modifying the TTimeStamp code is provided o the ROOT forum.
