### ISSUE TITLE
Wrong y zoom with empty hbar histogram

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#12567]
- [x] Checked for duplicates

### Describe the bug
Draw hbar is supposed to be the same as bar, but rotated. However, this fails if the histogram is empty.

### Expected behavior
hbar shows the same as bar, but rotated 90 degrees

### To Reproduce
```
auto c = new TCanvas()
c->Divide(2,1)
auto h = new TH1F()
c->cd(1)
h->Draw("bar")
c->cd(2)
h->Draw("hbar")

```
![unnamed](https://user-images.githubusercontent.com/10653970/228314987-1703ec18-e832-4509-a628-9b3eb64c7368.png)

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.26/06                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jul 28 2022, 18:08:51                 |
  | From tags/v6-26-06@v6-26-06                                      |
  | With c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0                        |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
https://github.com/root-project/root/pull/12566

**Comment by couet** [comment]
I see it also with master. Thanks to have reported.

**Comment by couet** [comment]
[This piece of code is the faulty one](https://github.com/root-project/root/blame/e6080327f4e6318692d3917152598126b76f4455/hist/histpainter/src/THistPainter.cxx#L7407). It looks weird ... I do not really understand the logic right now.

**Comment by couet** [comment]
Indeed there is [similar code in PaintInit](https://github.com/root-project/root/blame/e6080327f4e6318692d3917152598126b76f4455/hist/histpainter/src/THistPainter.cxx#L7215). It does not match. It should be similar I guess.

**Comment by couet** [comment]
Fix here: https://github.com/root-project/root/pull/12876
