### ISSUE TITLE
`RCompressionSetting` documented level 0 (`kUncompressed`) does not work

### ISSUE THREAD

**Issue by Moelf** [root-project/root#12606]
According to the docs:
https://github.com/root-project/root/blob/6fc4ddc223acc63eb4121c1aacfa470ce0e6cc1e/core/zip/inc/Compression.h#L31-L33

however upon trying:
```cpp
options.SetCompression(ROOT::Experimental::RCompressionSetting::EAlgorithm::kZLIB,0)
// or
options.SetCompression(ROOT::Experimental::RCompressionSetting::EAlgorithm::kUndefined,0)
```

Neither of them seems to write out uncompressed RNTuple.

**Comment by Moelf** [comment]
I don't think so, that's the first thing we tried.

**Comment by jblomer** [comment]
Ok, can you provide a minimal reproducer for the problem, i.e. the code surrounding `options.SetCompression()`?

**Comment by hahnjo** [comment]
As far as I can tell, there was nothing to fix here. Please adjust the "project" if I missed a PR.
