### ISSUE TITLE
[RF] Plots of nested `RooSimultaneous` ignore `ProjWData`

### ISSUE THREAD

**Issue by elusian** [root-project/root#12652]
- [x] Checked for duplicates

### Describe the bug

Nested `RooSimultaneous` are flattened  into a single `RooSimultaneous` with a `RooSuperCategory` as index. 
When plotting a `RooSimultaneous`, if the index category is derived its servers are searched inside the `ProjWData` set, and if not found the plot becomes a slice in the categories.
However, the only server of a `RooSuperCategory` is the internal `RooMultiCategory`, so in case of a nested `RooSimultaneous` the plot is always a slice.
This is basically https://github.com/root-project/root/issues/12020, except during plots and not generation. The solution is probably the same.

### Expected behavior

Categories are summed over and not sliced

### To Reproduce

```python
import ROOT

x = ROOT.RooRealVar('x', '', 0, 1)

c1 = ROOT.RooCategory('c1', '', {'c11': 0, 'c12': 1})
c2 = ROOT.RooCategory('c2', '', {'c21': 0})

u = ROOT.RooUniform('u', '', x)
g = ROOT.RooGaussian('g', '', x, ROOT.RooFit.RooConst(0.5), ROOT.RooFit.RooConst(0.1))
s1 = ROOT.RooSimultaneous('s1', '', {'c11': u, 'c12': g}, c1)
s2 = ROOT.RooSimultaneous('s2', '', {'c21': s1}, c2)

proto = ROOT.RooDataSet('proto', '', {c1, c2})
c1.setIndex(0)
for i in range(50):
    proto.add({c1, c2})
c1.setIndex(1)
for i in range(50):
    proto.add({c1, c2})
    
frame = x.frame()
s2.plotOn(frame, ProjWData = ({c1, c2}, proto)) # only gauss
c1.setIndex(0)
s2.plotOn(frame, ProjWData = ({c1, c2}, proto)) # only uniform
frame.Draw()
```

### Setup

ROOT master from LCG dev3

**Comment by guitargeek** [comment]
Thanks! Yes, the solution was exactly the same, and thanks to your reproducer I also found some other problem with nested RooSimultaneous pdfs that I fixed in the linked PR :+1:

**Comment by guitargeek** [comment]
I forgot to mention, in your reproducer code there is also a small problem. You are only specifying *how* c1 and c2 are projected, not *that* they are projected. For this, you also need to add the `Project` keyword arg:
```python
frame = x.frame()
s2.plotOn(frame, Project={c1, c2}, ProjWData = ({c1, c2}, proto), LineColor="r") # only gauss
c1.setIndex(0)
s2.plotOn(frame, Project={c1, c2}, ProjWData = ({c1, c2}, proto)) # only uniform
frame.Draw()
```

**Comment by elusian** [comment]
Thanks you for all the fixes!

You are of course correct about the reproducer bug. I am used to plotting the dataset too, since that sets the projection variables and categories for the frame. The example was _too_ minimal in this case.
