### ISSUE TITLE
[RF] Failed to get attribute RooMomentMorphND from ROOT

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#12653]
- [x] Checked for duplicates

### Describe the bug

My PyROOT scripts  uses `RooMomentMorphND` and I am using LCG dev3 nightly build   ( ROOT version 6.29/01)
Staring this morning  it fails to get RooMomentMorphND, reporting 

```

AttributeError: Failed to get attribute RooMomentMorphND from ROOT

```
 

### To Reproduce

LCG dev3 nightly slot at cvmfs 

```
import ROOT 
print ( ROOT.RooMomentMorphND)
```

### Setup

LCG dev3 nightly slot at cvmfs  ( ROOT version 6.29/01)

**Comment by guitargeek** [comment]
Hi! The RooMomentMorphND is gone, becuase it was almost an exact copy of RooMomentMorphFuncND and it became error prone to maintain the same code twice.

Please use the RooMomentMorphFuncND as described here:
https://root.cern/doc/master/release-notes.html#removal-of-roomomentmorphnd-class

Thanks for trying out ROOT master and let me know if the replacement works please!

**Comment by VanyaBelyaev** [comment]
Dear @guitargeek 

Thank you very much! 
The recipe from the link solves the problem.
The Issue can be closed.

**Comment by guitargeek** [comment]
Alright, thanks again for the feedback!
