### ISSUE TITLE
TBrowser doesn't open

### ISSUE THREAD

**Issue by AddahDraggon** [root-project/root#12721]
### Describe the bug
After updating ROOT from 6.26.06 to 6.28.02 TBrowser doesn't open

### Expected behavior
After opening ROOT and issuing ```TBrowser b``` command the TBrowser window was supposed to open

### To Reproduce
1. Open ROOT
2. Type ```TBrowser b```
3. Nothing happens (there was supposed to open TBrowser window)

### Setup
ROOT version: 6.28.02
Operating system: Nobara Linux 37
ROOT installed by ```sudo dnf install root```

### Additional context
ROOT launched locally, not by ssh or anything like that
Already checked if somehow is in batch mode (```gROOT->IsBatch()``` returns false)

**Comment by linev** [comment]
Do you have any web-browser - chrome or firefox?
Can you provide output in the shell where ROOT is running.

**Comment by AddahDraggon** [comment]
I do have Firefox, but neither of them were used.
Here is the console output (I tried both opening twice, with different methods):
![obraz](https://user-images.githubusercontent.com/57440874/235784236-35492efa-0253-42cf-9fc0-14072eaa07b9.png)

**Comment by linev** [comment]
From your console I do not see any attempts to start web-based browser implementation.
Do you have any custom `.rootrc' files? Or did you edit `$ROOTSYS/etc/system.rootrc` file?
After you starting root, can you check value: `gEnv->GetValue ("Browser.Name","")`

**Comment by AddahDraggon** [comment]
> From your console I do not see any attempts to start web-based browser implementation.

That's because I am trying to use a build-in `TBrowser`, not an `RBrowser` (or did something happend between 6.26.06 and 6.28.02 that requires `TBrowser` to use internet browser now?)

The ROOT install is fresh, not modified in any way.

Command `gEnv->GetValue ("Browser.Name","")` returns `(const char *) "ROOT::Experimental::RWebBrowserImp"`

**Comment by linev** [comment]
Starting from ROOT 6.28 `RBrowser` is used by default. 
You can disable it as described here: https://root.cern/for_developers/root7/#rbrowser
But from your output I see no any evidence that `RBrowser` is starting.
Can you just try directly
 ```
root --web=firefox $ROOTSYS/tutorials/v7/browser.cxx
```

**Comment by AddahDraggon** [comment]
It looks like I do not have any tutorials, also `echo $ROOTSYS` returns empty

**Comment by AddahDraggon** [comment]
TBrowser is working with `root --web=off`

**Comment by linev** [comment]
Can you try download tutorial from repository and run it?

Here is source code:  https://github.com/root-project/root/blob/master/tutorials/v7/browser.cxx

May be I am wrong, but seems to be you do not have libraries which are essential for  `webgui`.
Can you try to find libraries like:
```
libROOTBrowserv7.so
libROOTBrowserTCanvasWidget.so
libROOTBrowserGeomWidget.so
```
In any case you should have:
```
libCore.so
libRIO.so
```

**Comment by linev** [comment]
Seems to be, tutorials are in `root-tutorial` subpackage.
See: https://packages.fedoraproject.org/pkgs/root/root-tutorial/
But I have no idea where all examples installed.
`$ROOTSYS` typically is not configured for ROOT installed in system directories.
