### ISSUE TITLE
ACLiC doesn't properly forward C++20 flags

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#12747]
In a C++20 build (in this case using GCC 13):
```
 $ touch test.cpp
 $ ./bin/root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.29/01                        https://root.cern |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on May 02 2023, 08:25:11                 |
  | From heads/master@v6-29-01-1276-g12cf386128                      |
  | With g++ (GCC) 13.1.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] .L test.cpp++
Info in <TUnixSystem::ACLiC>: creating shared library /home/jhahnfel/ROOT/build-asserts-gcc13-cxx20/./test_cpp.so
In file included from /home/jhahnfel/ROOT/build-asserts-gcc13-cxx20/include/ROOT/RConfig.hxx:23,
                 from /home/jhahnfel/ROOT/build-asserts-gcc13-cxx20/test_cpp_ACLiC_dict.cxx:13:
/home/jhahnfel/ROOT/build-asserts-gcc13-cxx20/include/RConfigure.h:30:4: warning: #warning "The C++ standard in this build does not match ROOT configuration (202002L); this might cause unexpected issues" [-Wcpp]
 #  warning "The C++ standard in this build does not match ROOT configuration (202002L); this might cause unexpected issues"
    ^~~~~~~
In file included from /home/jhahnfel/ROOT/build-asserts-gcc13-cxx20/include/ROOT/RConfig.hxx:23,
                 from /home/jhahnfel/ROOT/build-asserts-gcc13-cxx20/test_cpp_ACLiC_dict.cxx:13:
/home/jhahnfel/ROOT/build-asserts-gcc13-cxx20/include/RConfigure.h:30:4: warning: #warning "The C++ standard in this build does not match ROOT configuration (202002L); this might cause unexpected issues" [-Wcpp]
 #  warning "The C++ standard in this build does not match ROOT configuration (202002L); this might cause unexpected issues"
    ^~~~~~~
```

This leads to many test failures because of the additional warning not expected in the reference output. All seems to work fine with C++17 for a compiler that defaults to C++14.

**Comment by pcanal** [comment]
What is the content of `include/compiledata.h` ?

**Comment by Axel-Naumann** [comment]
But `2a` != `20` - could that be it?

**Comment by pcanal** [comment]
> In ginclude/compiledata.h, I can see -std=c++2a correctly replacing -std=c++17 in both MAKEEXE and MAKESHAREDLIB

humm ... then it is weird.  You can see the actual command line used by typing:
```
.L test.cpp++kv
```
(with the 'k' the temporary files are kept and you can try re-running the command line shown in the log)

**Comment by hahnjo** [comment]
Umm yes, now I realize what is going wrong: `MAKEEXE` and `MAKESHAREDLIB` just call `g++` (or `clang++` for that matter) from the `PATH`, not caring that I'm trying to use a compiler installed to a non-standard directory... And then obviously GCC 8.5.0 defines the wrong `cplusplus` value with `c++2a` (we're lucky it knows about that).

**Comment by pcanal** [comment]
Yes, since that information must be machine independent (part of a relocatable package), we have to rely on the path ...

**Comment by hahnjo** [comment]
Okay, putting the "right" `gcc` into `$PATH` works, though I have to say this is *very* counter-intuitive...

**Comment by dpiparo** [comment]
@amadio why did you re-open this?

**Comment by amadio** [comment]
I do not remember, should have marked why after reopening. It may have been something in relation to #10693. Feel free to close again if you want.

**Comment by dpiparo** [comment]
I am closing. If that comes to mind again, do not hesitate to re-open!
