### ISSUE TITLE
possible dictionary problem in root 6 

### ISSUE THREAD

**Issue by etmachado** [root-project/root#12755]
- [x] Checked for duplicates

**Comment by etmachado** [comment]
I have been trying to move an app (Linux, RHAT/CentOS 6.7/7.1) we have from root 5 to root 6 (RHAT 8.7/9.1). In it we have some code that make use of the dictionary (included below). After verifying that our app compiles successfully in root 5 (5.34/36), I noticed that we had a problem with the generated "dict" file in version 6 (latest). Because of this, the compilation of the app is not able to go forward. 

As a summary of the problem, it shows up on the lines of m_vIntData and m_vIntDatSD, below:
```
class CytStatInfo : public TObject {
private:
	int m_iMachineSize;
	int m_bMachineSizeSet;
	double m_dMotorPos;
	int m_iFIndex;
	std::vector<int> m_vChNum;
	std::vector<int> m_vNoEv;
	std::vector<long long> m_vTsFirst;
	std::vector<double> m_vVel;
	std::vector<double> m_vOpPow;
	std::vector<double> m_vPulseMag;
	std::vector<double> m_vIntData[NUMBER_OF_COLORS];
	std::vector<double> m_vIntDataSD[NUMBER_OF_COLORS];
	std::vector<double> m_vPkRatio;
	std::vector<int> m_vEvtErr;
	std::vector<double> m_vEvRate;
	std::vector<double> m_vGEV;
	std::vector<int> m_vChEnbMask;

	bool m_bAllChannelsEnabled;
```

Here, NUMBER_OF_COLORS = 5.

The generated _dict file in root 5 show, at one point (note the vector declaration), 

```
      {
         for (Int_t R__l = 0; R__l < 5; R__l++) {
         vector<double> &R__stl =  m_vIntData[R__l];
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
    }
```

This seems to work well. But in root 6 it produces (note the [5] after vector<double>)

```
         for (Int_t R__l = 0; R__l < 5; R__l++) {
         vector<double>[5] &R__stl =  m_vIntData[R__l];
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
    }

```

this produces the compilation error:

```
g++ -O -Wall -fPIC  -pthread -std=c++14 -m64 -I/usr/include/root -I/home/vmecomp/Projects/Cytogate/CytCommon -I../../Include -I. -I/usr/include -I/home/vmecomp/Projects/Cytogate/Bus -I/home/vmecomp/Projects/Cytogate/Include -I/home/vmecomp/Projects/Cytogate/CytCommon -I/usr/include/root   -c -o CytStatInfo_dict.o CytStatInfo_dict.C
CytStatInfo_dict.C: In member function ‘virtual void CytStatInfo::Streamer(TBuffer&)’:
CytStatInfo_dict.C:202:25: error: expected identifier before numeric constant
          vector<double>[5] &R__stl =  m_vIntData[R__l];
                         ^
CytStatInfo_dict.C:202:25: error: expected ‘]’ before numeric constant
          vector<double>[5] &R__stl =  m_vIntData[R__l];
                         ^
                         ]
CytStatInfo_dict.C:202:24: warning: structured bindings only available with -std=c++17 or -std=gnu++17
          vector<double>[5] &R__stl =  m_vIntData[R__l];
```

It is possible that root is expecting better coding than my app shows, so if I'm doing something wrong please let me know. I include below the tar gzips with the little project in both versions, with results after compilation.

Thanks,

Emanuel

[test_v5.tar.gz](https://github.com/root-project/root/files/11390988/test_v5.tar.gz)
[test_v6.tar.gz](https://github.com/root-project/root/files/11390989/test_v6.tar.gz)

**Comment by pcanal** [comment]
The new code is indeed broken.   The ancient version of I/O is not well supported as the new version (`TStreamerInfo`) is faster and has more features).  In your linkdef file replace:
```
#pragma link C++ class CytStatInfo;
```
with (adding a trailing `+`)
```
#pragma link C++ class CytStatInfo+;
```
In addition update the line 
```
ClassDef(CytStatInfo, number);
```
to
```
ClassDef(CytStatInfo, number + 1);
```
in case you will need to schema evolve the class.

**Comment by etmachado** [comment]
Thanks for your quick evaluation. It does now compile properly, after I added the #pragma statement. The test program results seem to match the v5 results, so there is hope. My only raised brow comes with this warning:

In file included from CytStatInfo_dict.C:38:
CytStatInfo.cpp:56: warning: ignoring #pragma link C [-Wunknown-pragmas]
 #pragma link C++ class CytStatInfo+;


I'm struck to how different the _dict files are, though, so I'll have to do more testing on it. Would it be better for me to evolve the code towards the new TStreamInfo? Is there a tutorial or some doc that shows the process? Thanks!

Emanuel

**Comment by pcanal** [comment]
> Would it be better for me to evolve the code towards the new TStreamInfo? 

You would need it only if you need to read files produces by v5 *and* the reading actually fail.

> CytStatInfo.cpp:56: warning: ignoring #pragma link C [-Wunknown-pragmas]

Those should not be in the source file.   How to you invoke `rootcint` (and/or `rootcling`)?

**Comment by etmachado** [comment]
I use it within a makefile (you can also find it in the test_v6.tar.gz archive included above):

```
CytStatInfo_dict.C:	CytStatInfo.cpp CytStatInfo.hxx
			@echo "Generating Dictionary..."
			@rm -f CytStatInfo_dict*
			@rootcint CytStatInfo_dict.C -c -I$(CYTCOMMON_PATH) CytStatInfo.cpp CytStatInfo.hxx 
```
The pragma statement I added to CytStatInfo.cpp, at the beginning;

```
// this seems to be necessary for running in root6
#pragma link C++ class CytStatInfo+;

#include <CytStatInfo/CytStatInfo.hxx>

ClassImp( CytStatInfo );
```
I don't have a specific "linkdef" file (I wrote this code long, long time ago, so some of the details of why not escape me at the moment), What would you recommend?

Thanks very much for your help and insights!

Emanuel

**Comment by pcanal** [comment]
Instead create a file named CytStatInfoLinkDef.h contains
```
#pragma link C++ class CytStatInfo+;
```
and use
```
rootcling -f CytStatInfo_dict.C -I$(CYTCOMMON_PATH) CytStatInfo.hxx  CytStatInfoLinkDef.h
```

**Comment by etmachado** [comment]
Perfect, thank you!!
