### ISSUE TITLE
ROOT fails to include <boost/program_options.hpp> on macOS 13.3.1, XCode 13.3

### ISSUE THREAD

**Issue by ktf** [root-project/root#12762]
When running:

```c++
#include <boost/program_options.hpp>
```

I get the following [crash](https://github.com/root-project/root/files/11401279/crash.txt). This is on a macOS 13.3.1 M1 machine, using XCode 14.3 and the tip of the v6-28-00-patches branch, without any modifications on my side.

**Comment by pcanal** [comment]
The failing part is:
```
/Users/ktf/src/sw/osx_arm64/AliEn-Runtime/v2-19-le-local1/include/ApMon.h:59:9: note: expanding this definition of '_POSIX_VERSION'
#define _POSIX_VERSION 200101L
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/unistd.h:79:9: note: other definition of '_POSIX_VERSION'
#define _POSIX_VERSION          200112L
        ^
```
One of the two might be coming (indirectly) through a precompiled module (associated with a dictionary).

It is not clear why `ApMon.h` does not include `unistd.h` in the first place.

**Comment by ktf** [comment]
I actually see also different errors when including it from the rest of our software (where we probably have the missing include you refer to). E.g.:

In file included from /Users/ktf/src/sw/osx_arm64/O2/use-multithreading-local6/include/SimConfig/SimConfig.h:16:
In file included from /Users/ktf/src/sw/osx_arm64/boost/v1.75.0-local2/include/boost/program_options.hpp:17:
In file included from /Users/ktf/src/sw/osx_arm64/boost/v1.75.0-local2/include/boost/program_options/parsers.hpp:295:
In file included from /Users/ktf/src/sw/osx_arm64/boost/v1.75.0-local2/include/boost/program_options/detail/parsers.hpp:9:
/Users/ktf/src/sw/osx_arm64/boost/v1.75.0-local2/include/boost/program_options/detail/convert.hpp:36:55: error: reference to 'mbstate_t' is ambiguous
               const std::codecvt<wchar_t, char, std::mbstate_t>& cvt);
                                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__mbstate_t.h:44:9: note: candidate found by name lookup is 'std::mbstate_t'
using ::mbstate_t _LIBCPP_USING_IF_EXISTS;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cuchar:49:9: note: candidate found by name lookup is 'std::mbstate_t'
using ::mbstate_t _LIBCPP_USING_IF_EXISTS;
        ^
In file included from G__O2Generators dictionary payload:551:

**Comment by Axel-Naumann** [comment]
The actual / underlying error is probably right before:
```
In file included from ROOT_prompt_0:1:
In file included from /Users/ktf/src/sw/osx_arm64/boost/v1.75.0-local1/include/boost/program_options.hpp:17:
In file included from /Users/ktf/src/sw/osx_arm64/boost/v1.75.0-local1/include/boost/program_options/parsers.hpp:295:
In file included from /Users/ktf/src/sw/osx_arm64/boost/v1.75.0-local1/include/boost/program_options/detail/parsers.hpp:9:
/Users/ktf/src/sw/osx_arm64/boost/v1.75.0-local1/include/boost/program_options/detail/convert.hpp:36:55: error: reference to unresolved using declaration
               const std::codecvt<wchar_t, char, std::mbstate_t>& cvt);
                                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cuchar:49:1: note: using declaration annotated with 'using_if_exists' here
using ::mbstate_t _LIBCPP_USING_IF_EXISTS;
^
```
I'm afraid that this looks more like an issue with boost than something we can address on our side. Does a stand-alone compilation of `boost/program_options.hpp` and some use of it (to force the relevant instantiations) trigger the same error?

**Comment by ktf** [comment]
Yes, boost/program_options.hpp works just fine when it's compiled in our builds. The issue only appears at runtime when some root macro is invoked / dictionary loaded. Notice also this was working fine until recently.

**Comment by ktf** [comment]
> It is not clear why `ApMon.h` does not include `unistd.h` in the first place.

It actually does, but only later in the the compilation unit. I think this is some weird SunOS heritage (sigh). I am trying to see if I can simply get rid of that part.

**Comment by ktf** [comment]
Update on this. I managed to drop ApMon.h from our builds, but the other problem is still there. I also managed to hide boost/program_options.hpp from ROOT in our own code, so this is not a blocker for us anymore, at least at the moment. Still, I think this is actually a regression worth investigating.

**Comment by Axel-Naumann** [comment]
OK thanks for the update (and your helpful attitude of looking for a workaround). I will be looking at that source of this error - first I need to reproduce it. Do you happen to have a reproducer for this outside your build? Is this a C++20 build?

**Comment by Axel-Naumann** [comment]
FYI I can reproduce the issue.

**Comment by Axel-Naumann** [comment]
Same (minus the warnings) for boost 1.82.0:
```
root [0] gInterpreter->AddIncludePath("-I/Users/axel/build/boost/boost_1_82_0")
root [1] #include <boost/program_options.hpp>
In file included from ROOT_prompt_1:1:
In file included from /Users/axel/build/boost/boost_1_82_0/boost/program_options.hpp:17:
In file included from /Users/axel/build/boost/boost_1_82_0/boost/program_options/parsers.hpp:295:
In file included from /Users/axel/build/boost/boost_1_82_0/boost/program_options/detail/parsers.hpp:9:
/Users/axel/build/boost/boost_1_82_0/boost/program_options/detail/convert.hpp:36:55: error: reference to unresolved using declaration
               const std::codecvt<wchar_t, char, std::mbstate_t>& cvt);
                                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/cuchar:49:1: note: using declaration annotated with 'using_if_exists' here
using ::mbstate_t _LIBCPP_USING_IF_EXISTS;
^
```

**Comment by ktf** [comment]
I'd rather drop boost...

**Comment by Axel-Naumann** [comment]
Closing as there's literally nothing we can do - it's Apple's libc++ that's causing it. The issue continues to exist with Xcode 14.3.1.

**Comment by ktf** [comment]
Could you also change it as "Won't fix" rather than "Complete"?

**Comment by Axel-Naumann** [comment]
Can do, but we usually use "won't fix" for issues we can theoretically fix, i.e. issues in ROOT. Let me know whether your wasn't "won't fix" here nonetheless.

**Comment by ktf** [comment]
Well, my point is that somewhere you should state that you do not plan to support boost or anything using cuchar in clang on macOS for the time being.

**Comment by Axel-Naumann** [comment]
I do expect that Xcode will bump their libc++ to the version that has the fix. We generally don't support broken things, I really don't know what to do here... I.e. this is really completely independent of ROOT, the Xcode headers are broken, I just don't know what you want me to say about that, and where, which disclaimer would make the world any better... But sure, if you think this *does* make the word better I will mark this as "won't fix"!

**Comment by Axel-Naumann** [comment]
Changing closed state to won't fix

**Comment by Axel-Naumann** [comment]
Changing closed state to won't fix

**Comment by Axel-Naumann** [comment]
Changing closed state to "won't fix"
