### ISSUE TITLE
build problem with 6.28.04 on macos 13.3 

### ISSUE THREAD

**Issue by nefedov-yury** [root-project/root#12820]
At the very end of the build, there is a problem with linking libraries:

[100%] Linking CXX shared library ../../lib/libRMySQL.so
ld: library not found for -lzlib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libRMySQL.6.28.04.so] Error 1
make[1]: *** [sql/mysql/CMakeFiles/RMySQL.dir/all] Error 2
make: *** [all] Error 2

However, this library is present in the system and during the cmake it is found:
cmake:
-- Looking for ZLib
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/lib/libz.tbd (found version "1.2.11")

The temporary, one-time solution that worked for me was to edit the file created by cmake:
[build directory]/sql/mysql/CMakeFiles/RMySQL.dir/link.txt
I removed the "-lzlib -lzstd" part from the list of libraries and the link completed without problems.

It looks like the problem is in the build system
Best regards.
Yury

- [ ] Checked for duplicates

**Comment by nefedov-yury** [comment]
I'm sorry I forgot to include details:

> make VERBOSE=1
...
[100%] Linking CXX shared library ../../lib/libRMySQL.so
cd /opt/root/src/build/sql/mysql && /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake -E cmake_link_script CMakeFiles/RMySQL.dir/link.txt --verbose=1
/opt/homebrew/opt/ccache/libexec/c++  -std=c++17 -Wc++11-narrowing -Wsign-compare -Wsometimes-uninitialized -Wconditional-uninitialized -Wheader-guard -Warray-bounds -Wcomment -Wtautological-compare -Wstrncat-size -Wloop-analysis -Wbool-conversion -m64 -pipe -W -Wall -Woverloaded-virtual -fsigned-char -fno-common -Qunused-arguments -pthread -stdlib=libc++ -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -dynamiclib -Wl,-headerpad_max_install_names -m64 -single_module -Wl,-dead_strip_dylibs -compatibility_version 6.28.0 -current_version 6.28.4 -o ../../lib/libRMySQL.6.28.04.so -install_name @rpath/libRMySQL.6.28.so CMakeFiles/RMySQL.dir/src/TMySQLResult.cxx.o CMakeFiles/RMySQL.dir/src/TMySQLRow.cxx.o CMakeFiles/RMySQL.dir/src/TMySQLServer.cxx.o CMakeFiles/RMySQL.dir/src/TMySQLStatement.cxx.o CMakeFiles/G__RMySQL.dir/G__RMySQL.cxx.o  -Wl,-rpath,/opt/root/src/build/lib ../../lib/libNet.6.28.04.so ../../lib/libRIO.6.28.04.so -L/opt/homebrew/Cellar/mysql/8.0.33/lib -lmysqlclient -lzlib  -lzstd -L/opt/homebrew/opt/openssl@1.1/lib -lssl -lcrypto -lresolv ../../lib/libThread.6.28.04.so ../../lib/libCore.6.28.04.so
ld: library not found for -lzlib

You can see that the 'mysqlclient' is from homebrew, but the ' -lzlib  -lzstd ' parts come from somewhere else:
% pkg-config mysqlclient --libs
-L/opt/homebrew/Cellar/mysql/8.0.33/lib -lmysqlclient

**Comment by nefedov-yury** [comment]
Both libraries are installed, I think because of dependencies.

 But for zlib, the name of the library is different:
% pkg-config zlib --libs
-lz

In the case of libzstd, the path must be specified:
% pkg-config libzstd --libs
-L/opt/homebrew/Cellar/zstd/1.5.5/lib -lzstd

However, the fact that the libRMySQL is linked without specifying
these libraries means that they are not needed.
Checking the resulting library shows that the dependencies
are all satisfied:
v6.28.04-clang14.0/root/lib% otool -L libRMySQL.so 
libRMySQL.so:
        @rpath/libRMySQL.6.28.so (compatibility version 6.28.0, current version 6.28.4)
        @rpath/libNet.6.28.so (compatibility version 6.28.0, current version 6.28.4)
        /opt/homebrew/opt/mysql/lib/libmysqlclient.21.dylib (compatibility version 21.0.0, current version 21.0.0)
        @rpath/libCore.6.28.so (compatibility version 6.28.0, current version 6.28.4)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1500.65.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)

**Comment by bellenot** [comment]
OK, thanks for the info, I'll see what I can do about that

**Comment by nefedov-yury** [comment]
Well, I found that it's not a root issue, but a problem with the wrong mysql_config on macos.
 Running the 'mysql_config --libs' gives the wrong list of libraries:
% mysql_config --libs
-L/opt/homebrew/Cellar/mysql/8.0.33/lib -lmysqlclient -lzlib  -lzstd -L/opt/homebrew/opt/openssl@1.1/lib -lssl -lcrypto -lresolv

I replaced mysql with mariadb-connector-c and the problem is gone.
Thanks for helping me understand the issue.

**Comment by bellenot** [comment]
Good! Many thanks for the follow-up! So I suppose I can close this issue?

**Comment by nefedov-yury** [comment]
Yes. I hope no one else falls into this trap :)

**Comment by bellenot** [comment]
Yup, we'll see...
