### ISSUE TITLE
[RF] Change precision of RooAbsL EventSections tests

### ISSUE THREAD

**Issue by egpbos** [root-project/root#12832]
Following #12389, we should also change the `EXPECT_EQ`s in the two `EventSections` test cases in `testRooAbsL` to `EXPECT_DOUBLE_EQ`. The same explanation as for that case applies to them and should be added as a comment to the tests:

```
   // We cannot EXPECT_EQ in this test, because we compare actually different
   // calculations. The multiple additions and FMA operations involved in the
   // calculation of the multiple parts introduces different rounding errors
   // on the CPU level than the single calculation over all events at once.
```

**Comment by egpbos** [comment]
Almost all the tests in `testLikelihoodJob.cxx` have the same behavior. If we change the random seed, a bunch of them fail. We should change those to `EXPECT_DOUBLE_EQ` as well.

**Comment by hahnjo** [comment]
@guitargeek can you please take care of `testLikelihoodJob`? That one is failing on `mac13arm/cxx17` since forever...

**Comment by guitargeek** [comment]
Okay, I have opened a PR for this! Feel free to review if you have time, @hahnjo, Lorenzo is on vacation so if you don't review it it will take some time to get merged :)

**Comment by hahnjo** [comment]
@guitargeek I've adjusted the project. "not applicable" is for invalid reports that didn't lead to code changes.
