### ISSUE TITLE
Command Line Parameter Passing trailing comma problem

### ISSUE THREAD

**Issue by paulnord** [root-project/root#12840]
- [ √ ] Checked for duplicates

### Describe the bug

If the parameter list of a function has a trailing comma (e.g. funct(int a, int b,){} ) then the second parameter cannot be specified from the command line (e.g. root 'funct.C(1,2)' ).

### Expected behavior

Both parameters should be usable.

### To Reproduce

/* Bug Report
 * This works:
 *    root -b -q 'bug.C("asdf")'
 * This does not:
 *    root -b -q 'bug.C("asdf","xyzzy")'
 *
 *  You must remove the comma after param2 to fix this.
 */

void bug(
		    const Char_t *param1 = "input Text 1",
		    const Char_t *param2 = "input Text 2",  // The comma here breaks the code
)
{
   cout << param1 << endl;
   cout << param2 << endl;
}

### Setup

1. ROOT version
 Version   5.34/38     12 March 2018 
3. Operating system
NAME="Scientific Linux"
VERSION="7.3 (Nitrogen)"
4. How you obtained ROOT, such as `dnf install` / binary download / you built it yourself.
Installed on rcas node at Brookhaven National Lab.

**Comment by paulnord** [comment]
You are correct about the validity of the C++ code.
However, ROOT accepts the code without complaint.
That actually is the issue.

As for the ROOT version, analysis of the STAR data at Brookhaven National Lab is mature and sort of locked into this older ROOT version.  Surely EIC will update to a better code base and provide an integrated development environment.  Alas, progress is slow.

**Comment by vepadulano** [comment]
> However, ROOT accepts the code without complaint.
> That actually is the issue.

In your original post, you mention that the behaviour you expect to see is that both parameters should be usable. Implementing this would mean openly violating C++ standard (even further than CINT already did at the time of ROOT 5.34).

On the other hand, a proper fix would be raising a compiler error. I am unsure whether providing such a fix for CINT is what we want, cling already works properly and it's just a matter of updating the ROOT version. I will leave @Axel-Naumann the final say on this.

In any case, isn't it possible for you to declare functions on your application side that do not have a trailing comma?

**Comment by Axel-Naumann** [comment]
Interpreter errors of ROOT 5 were addressed by replacing CINT by cling, which means ROOT 6. I.e. thanks for the report on an old version, this has been addressed in the meantime.

**Comment by paulnord** [comment]
Makes sense.  Thanks for your attention.
