### ISSUE TITLE
quotes around class name in ClassDef in /manual/io_custom_classes/

### ISSUE THREAD

**Issue by jhsaren** [root-project/root#12869]
Hi,
The example in https://root.cern/manual/io_custom_classes/ has MyClass inside quotes. That gives errors and misleads people trying to follow the manual.
BR, 
Jan

**Comment by pcanal** [comment]
What error are you seeing? (i.e. can you print the complete compiler output?)

**Comment by guitargeek** [comment]
Thanks for reporting this! Indeed, it doesn't work if you put the class name inside double quotes.

I have opened a PR to fix this:

https://github.com/root-project/web/pull/858
