### ISSUE TITLE
root-6.28.04 fails to compile with gcc-13 under linux TW

### ISSUE THREAD

**Issue by svenmenke** [root-project/root#12897]
Dear all,

while root-6.28.03 compiled with the patch provided in response to issue #12659 a similar problem is back now in root-6.28.04 (retrieved via latest-stable from github today).  I just did (on suse TW):
```
git clone --branch latest-stable --depth=1 https://github.com/root-project/root.git root_src
mkdir root_build
cd root_build
cmake ../root_src -j4
```

and this produced:
```
...
[ 76%] Built target ClingUtils
[ 76%] Building CXX object core/rootcling_stage1/CMakeFiles/rootcling_stage1.dir/src/rootcling_stage1.cxx.o
[ 76%] Linking CXX shared library ../../../lib/libCling.so
[ 76%] Linking CXX executable src/rootcling_stage1
[ 76%] Built target rootcling_stage1
[ 76%] Generating G__Core.cxx, ../lib/Core.pcm
[ 76%] Built target Cling
While building module 'Core':
While building module 'std' imported from input_line_1:1:
In file included from <module-includes>:52:
In file included from /usr/include/c++/13/memory_resource:60:
In file included from /usr/include/c++/13/bits/memory_resource.h:46:
/usr/include/c++/13/bits/utility.h:219:27: error: redefinition of '__is_in_place_type_v<in_place_type_t<_Tp>>'
    inline constexpr bool __is_in_place_type_v<in_place_type_t<_Tp>> = true;
                          ^
./usr/include/c++/13/bits/stl_pair.h:62:11: note: '/usr/include/c++/13/bits/utility.h' included multiple times, additional include site in header from module 'std.bits/stl_pair.h'
# include <bits/utility.h> // for std::tuple_element, std::tuple_size
          ^
..
```

It's not the exact same error message as in #12659 but seems rather close in nature ...
Could you please have  look if the patch from 6.28.03 needs further additions to address this in 6.28.04?

Thanks & Cheers,
--Sven

**Comment by svenmenke** [comment]
sorry about the bad formatted post - I did not intend any font change nor the setting of the 'bug'-label. Apparently the copy-pasted g++ error output triggered both of these. I hope it does not distract from the actual issue that compiling fails again under g++-13.
Thanks,
--Sven

**Comment by hahnjo** [comment]
Sorry about that, we were missing a backport after applying other fixes: https://github.com/root-project/root/pull/12901

P.S.
> sorry about the bad formatted post - I did not intend any font change

You can disable formatting of pasted logs by surrounding them with three backticks on individual lines. I've edited the original issue summary accordingly :wink:
