### ISSUE TITLE
Add flag option "--web=off" for rootbrowse macro

### ISSUE THREAD

**Issue by dudarboh** [root-project/root#12922]
### Explain what you would like to see improved

Add flag option "--web=off" for rootbrowse macro

### How to reproduce?

Would be nice if the following would be possible:

```bash
rootbrowse --web=off myfile.root
```

analogous to

```bash
root --web=off
[0] new TBrowser
```

### ROOT version

6.28/00

### How did you install ROOT?

cvmfs LCG

### Which operating system are you using?

Centos7

**Comment by couet** [comment]
implemented here: https://github.com/root-project/root/pull/12963
