### ISSUE TITLE
Multithreading problem with Minuit2+RooFit

### ISSUE THREAD

**Issue by bendavid** [root-project/root#12940]
### Check duplicate issues.

- [ ] Checked for duplicates

### Describe the bug

When root is built with minuit2_omp=on then using RooFit with Minuit2 is broken out of the box because minuit2 multithreads the objective function evaluation, where the objective function is provided by RooFit and is in general not thread safe.

### What is the expected behaviour?

Probably RooFit should disable the minuit2 multithreading when it calls minuit2 (but actually I couldn't even figure out how to do this myself beyond the brute force solution of setting the environment variable OMP_NUM_THREADS=1.

### How to reproduce?

In a build with minuit2_omp (e.g. standard root package on arch linux)

```python

import ROOT
import time


def gaussian_minuit2():
    """
    """

    axis = ROOT.RooRealVar("x", "x", 50, 130)
    axis.setBins(100)
    axis.setRange(50, 130)

    mu = ROOT.RooRealVar("mu", "mu", 91.0, 85.0, 97.0)  # 91
    sigma = ROOT.RooRealVar("sigma", "sigma", 4.0, 0.5, 10.0)  # 4

    background = ROOT.RooGaussian("gauss_bkg", "Gaussian background",
                                  axis, mu, sigma)

    NDATA = 100000

    data = background.generateBinned({axis}, NDATA)
    data.SetName("Data_gauss")

    mu2 = ROOT.RooRealVar("mu2", "mu2", 97.0, 50.0, 130.0)  # 91
    sigma2 = ROOT.RooRealVar("sigma2", "sigma2", 6.0, 0.5, 10.0)  # 4

    bkg_fit = ROOT.RooGaussian("bkg_fit", "Gaussian background for fit",
                               axis, mu2, sigma2)

    expected_num = ROOT.RooRealVar(
        "nexp", "nexp", NDATA, 90000, 110000)

    model = ROOT.RooExtendPdf(
        "Extended", "extend", bkg_fit, expected_num)

    res2 = model.fitTo(data, 
                       ROOT.RooFit.Extended(True), 
                       ROOT.RooFit.Minimizer("Minuit2"),
                       ROOT.RooFit.Save(True), 
                       ROOT.RooFit.PrintLevel(0))

    print("***********************************")
    res2.Print()
    res2.correlationMatrix().Print()
    print(res2.status())
    print(res2.covQual())

    '''
    c = ROOT.TCanvas()
    c.cd()
    frame = axis.frame(Title="Title")
    data.plotOn(frame)
    model.plotOn(frame)
    frame.Draw()
    c.SaveAs("gaussian.png")
    '''

if __name__ == '__main__':

    ROOT.RooRandom.randomGenerator().SetSeed(42)
    gaussian_minuit2()

    print(ROOT.RooRandom.randomGenerator().GetSeed())

```

### ROOT version

6.28/04

### How did you install ROOT?

pacman

### Which operating system are you using?

Arch Linux

**Comment by guitargeek** [comment]
Using the `minuit2_omp` option restricts you to minimizing thread-safe functions, and RooFit models are not thread safe. Also the regular ROOT fitter interface is not thread-safe either, so this option basically breaks your build. It is intended for MInuit2 standalone builds for the specific case where you have an expensive thread-safe function where you want to parallelize the gradient calculation.

Adding a warning in the configuration step with CMake hopefully keeps people and package maintainers from using it in the future:
https://github.com/root-project/root/pull/12970

**Comment by bendavid** [comment]
Well it wouldn't be totally unreasonable to be able to enable/disable this at run time (without the global OMP_NUM_THREADS environment variable) but fine I don't feel very strongly about this.

**Comment by guitargeek** [comment]
Hi @bendavid, with this PR we are officially not supporting to build ROOT with these minuit omp or mpi build options anymore:
* https://github.com/root-project/root/pull/12970

I'll close this issue here, because not it's clear that RooFit can't be used with Minuit2 multithreading.

You are right that it's not unreasonable to expect that Minuit2 multithreading can be enabled/disabled at runtime, but this is another issue. Given the limited developer time we have, I think we need a better motivation than "we realized it would be nice to have" to implement this.

If you have any usecase for Minuit 2 multithreading in ROOT that is covered by these flags, then please go ahead and open a new issue whenever :slightly_smiling_face:
