### ISSUE TITLE
std::source_location not working in the interpreter

### ISSUE THREAD

**Issue by pikacic** [root-project/root#12993]
### Check duplicate issues.

- [X] Checked for duplicates

### Describe the bug

Trying to use `std::source_location` in a header exposed to cling result in an error.

See, for example, https://gitlab.cern.ch/gaudi/Gaudi/-/issues/266#note_6757681, where we had to hide `source_location` to cling as a workaround (https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1455/diffs#afb7337014c145ecb07b8ea11c702bcae52ff226_29_28).

### What is the expected behaviour?

I expect to be able to use `std::source_location` in a header that I pass to cling to generate a dictionary.

### How to reproduce?

On lxplus9.cern.ch
```
❯ . /cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/setup.sh 
❯ root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.28/05                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jun 10 2023, 00:28:00                 |
  | From heads/v6-28-00-patches@v6-28-04-94-gb7de1efc73              |
  | With g++ (GCC) 13.1.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] #include <source_location>
root [1] auto loc = std::source_location::current();
ROOT_prompt_1:1:17: error: 'source_location' is not a class, namespace, or enumeration
auto loc = std::source_location::current();
                ^
ROOT_prompt_1:1:17: note: 'source_location' declared here
root [2] 
```

### ROOT version

v6-28-00-patches

### How did you install ROOT?

LCG nightly builds in /cvmfs/sft-nightlies.cern.ch

### Which operating system are you using?

Linux Alma 9

**Comment by hahnjo** [comment]
From a quick look, the explanation seems to be that `source_location` in `libstdc++` relies on `__builtin_source_location` that was only implemented by https://github.com/llvm/llvm-project/commit/d61487490022aaacc34249475fac3e208c7d767e, released in LLVM 15 while ROOT uses LLVM 13...

**Comment by guitargeek** [comment]
So it will probably be fixed by:
* https://github.com/root-project/root/pull/13273

**Comment by hahnjo** [comment]
This works now after the upgrade to LLVM 16:
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.31/01                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Dec 11 2023, 13:58:33                 |
  | From heads/master@v6-31-01-496-g020287b02c                       |
  | With g++ (GCC) 13.2.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] __cplusplus
(long) 202002
root [1] #include <source_location>
root [2] auto loc = std::source_location::current();
root [3] loc
(std::source_location &) @0x7fde927b2000
root [4] loc.file_name()
(const char *) "ROOT_prompt_2"
root [5] loc.line()
(unsigned int) 1
root [6] loc.column()
(unsigned int) 12
root [7] loc.function_name()
(const char *) "void __cling_Un1Qu31(void *)"
```
