### ISSUE TITLE
Ambiguous default parameter in TF2::Integral documentation

### ISSUE THREAD

**Issue by YuryYury** [root-project/root#13005]
### Check duplicate issues.

- [X] Checked for duplicates

### Describe the bug

We see the following in [the documentation of `TF2::Integral(...)` for the `master` branch](https://root.cern.ch/doc/master/classTF2.html#aa1eaa5844fa258becc6286d9f7b01309):
<img width="632" alt="2023-06-13 15_43_20-ROOT_ TF2 Class Reference - Opera" src="https://github.com/root-project/root/assets/7541582/61fbc841-8a0d-4942-b15e-bf13cbd1a1a5">

`epsrel` is first mentioned to equal 1.e-6, and then it says that the "default value of eps is 1.e-9". So which one is it?

### What is the expected behaviour?

The default value of `epsrel` should be the same.

### How to reproduce?

Just click the link in the issue description.

### ROOT version

6.14, master

### How did you install ROOT?

does not matter, the issue is with the documentation

### Which operating system are you using?

does not matter, the issue is with the documentation

**Comment by YuryYury** [comment]
Yes, the documentation has to be changed. I do not know which of the two values is correct.

**Comment by DHRUVJ2003** [comment]
A common default value for relative accuracy in numerical integration algorithms is often around 1e-6 (0.000001) or 1e-8 (0.00000001). But at the same time can also depend on the desired precision . So, I believe that lesser value will be more preferable so that we get higher precision.

**Comment by couet** [comment]
Of course, the default value is the one mentioned in the signature as it is extracted from the code. The value mentioned in the help is a typo seems to me. @lmoneta can you confirm?

**Comment by couet** [comment]
PR here: https://github.com/root-project/root/pull/13012

**Comment by DHRUVJ2003** [comment]
So, defined by eps means 1e-6 ?

**Comment by couet** [comment]
yes, the value mentioned in the signature is the one coming from the code. it is the one used.

**Comment by couet** [comment]
see https://github.com/root-project/root/blob/3db7c5d0545e0614a7084d21ba98a259cf558f44/hist/hist/inc/TF2.h#L116

**Comment by couet** [comment]
if you need 1e-9 simply change it when you call Integral, that is what "defined by eps" means. You defined it, either by using the default value 1e-6 or by specifying this parameter.

**Comment by DHRUVJ2003** [comment]
Okay... okay got it .....Thanks
