### ISSUE TITLE
Slow reads via HTTP from EOS

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#13018]
### Check duplicate issues.

- [X] Checked for duplicates

### Describe the bug

It was reported at https://root-forum.cern.ch/t/reading-from-http-very-slow/53213 that reading a file via HTTP from EOS with ROOT takes much longer than simply downloading that file with wget.

From the original report,

```
root -l https://cernbox.cern.ch/remote.php/dav/public-files/ntHJKDVRTjlSkyS/test_ntuples_200123.root
root [0] Electrons_All->Draw("pt__NOSYS")
```

takes ~5 minutes (although the tree is very small, ~60k events, 4MB in total)

while

```
wget https://cernbox.cern.ch/remote.php/dav/public-files/ntHJKDVRTjlSkyS/test_ntuples_200123.root
root -l test_ntuples_200123.root 
```

takes 0.6s.

### How to reproduce?

See original report.

### ROOT version

6.26.10

### How did you install ROOT?

Does not matter

### Which operating system are you using?

Linux

### Additional context

Discussion on SNOW with the EOS folks at https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF2315805 .

**Comment by linev** [comment]
One potential reason - huge latency for simple request of 4 bytes. Just submitting simple request:
```
time curl -ik https://cernbox.cern.ch/remote.php/dav/public-files/1Cy1HIf03Ca76Dm/test_ntuples_200123.root -H "Range: bytes=0-4,100-104" --output -
```

Gives me: `1.423 sec` total time.

**Comment by eguiraud** [comment]
Unless we make something like `5*60 / 1.423 = 211` requests, one after the other, in order to retrieve those 60k events this doesn't add up.

**Comment by linev** [comment]
I have more strange effect.

I do not compile davix and therefore after opening the file with:
 `TFile::Open("https://cernbox.cern.ch/remote.php/dav/public-files/1Cy1HIf03Ca76Dm/test_ntuples_200123.root");` 
I getting instance of `TWebFile`. And if enable `gDebug=1`, one clearly sees ~1.5s per each http request.

Moreover, when I try to perform `TTree::Draw()` from the `TBrowser` (web and normal one), `TWebFile` submits multirange request, but not able to parse result of it. Producing several errors - it fully crashes, including my console.

Seems to be, it is another issue.

**Comment by linev** [comment]
Now I start understanding problem with cernbox http server.
It returns wrong http response header on multi-range request.
Therefore ROOT not able to recognize it and either fail or fall-back to single http requests - 
which is VERY slow method due to 1.5s latency per single request.

Here is example of "normal" response on multipart http request:
```
curl -ik https://root.cern/js/files/hsimple.root -H "Range: bytes=0-15,1000-1015" --output -                                                                                                                                     (15.06. 11:15:48) !11391 
HTTP/1.1 206 Partial Content
Date: Thu, 15 Jun 2023 09:16:57 GMT
Server: Apache/2.4.41 (Ubuntu)
X-Frame-Options: SAMEORIGIN
Last-Modified: Thu, 04 Jul 2013 08:21:05 GMT
ETag: "6521f-4e0ab42683e40"
Accept-Ranges: bytes
Content-Length: 177
Cache-Control: max-age=1800
Expires: Thu, 15 Jun 2023 09:46:57 GMT
Content-Security-Policy: frame-ancestors 'self';
Strict-Transport-Security: max-age=15768000
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: range
Access-Control-Expose-Headers: content-range,content-length,content-type,accept-ranges
Access-Control-Allow-Methods: HEAD,GET
Content-Type: multipart/byteranges; boundary=61c842e35204a0c7


--61c842e35204a0c7
Content-range: bytes 0-15/414239

root�mdR
--61c842e35204a0c7
Content-range: bytes 1000-1015/414239

1ZGqP��
--61c842e35204a0c7--
```

And here is result from cernbox:
```
curl -ik https://cernbox.cern.ch/remote.php/dav/public-files/1Cy1HIf03Ca76Dm/test_ntuples_200123.root -H "Range: bytes=0-15,1000-1015" --output -                                                                                (15.06. 11:15:25) !11380 
HTTP/1.1 206 Partial Content
Access-Control-Allow-Origin: *
Content-Disposition: attachment; filename="test_ntuples_200123.root"
Content-Length: 389
Content-Range: 
Content-Security-Policy: default-src 'none';
Content-Type: application/octet-stream
Date: Thu, 15 Jun 2023 09:15:48 GMT
Etag: "329762575417868288:9d274a18"
Last-Modified: Wed, 24 May 2023 12:22:19 +0000
Oc-Etag: "329762575417868288:9d274a18"
Oc-Fileid: eoshome-t!103034857
Server: nginx/1.20.1
Strict-Transport-Security: max-age=63072000
Vary: Origin
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-Xss-Protection: 1; mode=block

--1941f188e1f15cbc8af2c2ce8ba24411209981093834f193e96822568cbb
Content-Range: bytes 0-15/4667337
Content-Type: application/octet-stream

root��dG7�
--1941f188e1f15cbc8af2c2ce8ba24411209981093834f193e96822568cbb
Content-Range: bytes 1000-1015/4667337
Content-Type: application/octet-stream

.�J.�f6��M�����m
--1941f188e1f15cbc8af2c2ce8ba24411209981093834f193e96822568cbb--
```

That is wrong?
First of all content type must be: "Content-Type: multipart/<something>"
In the same line one should have boundary "like boundary=61c842e35204a0c7"
Such line is not present in cernbox response.
Without clearly specified "boundary" it is not possible to decode code afterwards.

My conclusion - malformed http response and large latency make impossible to use cernbox http server.

**Comment by linev** [comment]
I closing issue while it is problem with http server

**Comment by pcanal** [comment]
Does the problem still exist?  If so did we open an issue with the EOS and/or server support team?

**Comment by linev** [comment]
Yes, problem with EOS is still there - just check my `curl` command to see it.
