### ISSUE TITLE
Builtin TBB library sometimes not found (or more exactly the one install in /usr/lib sometimes take priority)

### ISSUE THREAD

**Issue by pcanal** [root-project/root#13079]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

When linking a dependent product (happens to be Celeritas but apriori it could be anything) against ROOT build with a builtin TBB, the link fails with:
```
/work1/celeritas/pcanal/geant-public/gcc12/install/opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
/work1/celeritas/pcanal/geant-public/gcc12/install/opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)'
/work1/celeritas/pcanal/geant-public/gcc12/install/opt/lib/libImt.so: undefined reference to `tbb::interface9::global_control::active_value(int)'
/work1/celeritas/pcanal/geant-public/gcc12/install/opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_terminate()'
/work1/celeritas/pcanal/geant-public/gcc12/install/opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_initialize()'
/work1/celeritas/pcanal/geant-public/gcc12/install/opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_execute(tbb::interface7::internal::delegate_base&) const
```

Notes

* Adding the `libtbb` installed by ROOT explicitly solves the problem.
* doing `ldd` on `libImt` prints the expected path for `libtbb`
* re-doing the failing link with `LD_LIBRARY_PATH` containing the directory where the builtin `libtbb` is solved the problem
* redoing the failing link adding to `-Wl,-rpath-link,` the directory where the builtin `libtbb` is solved the problem 
* The main difference is that when linking `libImt` with builtin the link line uses `-ltbb` while when linking against an external `tbb` it list the full pathname of the library (while the ROOT library use a relative path)

So the problem is might be either that
* we use `-ltbb` for the buitin
* the CMake fragment used by the dependent product does not add the ROOT library path to `rpath` (in contrast both Geant4 and VecGeom add their path to rpath or so it seems.

### Reproducer

build ROOT with buitin tbb
build Celeritas against that ROOT install

### ROOT version

at least v6.28/04 and master

### Installation method

hand build

### Operating system

linux

**Comment by guitargeek** [comment]
Hi @pcanal, maybe the upgrade of the builtin tbb version fixed this issue?
https://github.com/root-project/root/pull/13724

**Comment by pcanal** [comment]
Yes. It appears to have fixed the issue.  Thanks.

(`libtbb` now appears only in `libThread` link line with a relative path (i.e. no -l)).
