### ISSUE TITLE
TFormula error when loading gdml using matrix

### ISSUE THREAD

**Issue by noemina** [root-project/root#13074]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

Hello,
I am trying to load a GDML file using matrix and variables. Here in an extract from the gdml:

```
<matrix name="someNumbers" coldim="1" values="4 3 2 3"/>
<variable name="testVariable" value="someNumbers[1]"/>
```

ROOT complains when parsing the GDML, with the following error:

```
input_line_155:2:81: error: subscripted value is not an array, pointer, or vector
Double_t TFormula____id2222353222929674449(Double_t *x,Double_t *p){ return p[0][1] ; }
                                                                            ~~~~^~
Error in <prepareMethod>: Can't compile function TFormula____id2222353222929674449 prototype with arguments Double_t*,Double_t*
Error in <TFormula::InputFormulaIntoCling>: Error compiling formula expression in Cling
Error in <TFormula::ProcessFormula>: Formula "[someNumbers][1]" is invalid !
Error in <TFormula::Eval>: Formula is invalid and not ready to execute 
Fatal in <TGDMLParse::Value>: Got bad value nan from string 'someNumbers[1]'
aborting
```

It seems that the parser fails in understanding how to access the matrix element.  

Cheers,
Noemi

### Reproducer

[geometry_test.gdml.txt](https://github.com/root-project/root/files/11833941/geometry_test.gdml.txt)

Please note the attached file is `.txt`.

To reproduce the issue, you can do:

```
root -l
TGeoManager::Import("geometry_test.gdml")
```

### ROOT version

ROOT Version: 6.26/10

### Installation method

build from source using gcc 12.2.1

### Operating system

Linux Fedora 38

**Comment by lmoneta** [comment]
Thank you for reporting this issue. Unfortunately this is something not supported by ROOT GDML, you cannot use matrix inside and you will have to define each single value

**Comment by pbutti** [comment]
Thank you @lmoneta . However is there a strong reason why support for using matrix couldn't be added to ROOT GDML?

**Comment by lmoneta** [comment]
I think it requires some effort. We can change this issue in a feature requests and see if somebody can implement it

**Comment by agheata** [comment]
No strong reason, just lacking the person to implement it. And this is not really high priority because one can use either scalar variables or the Geant4 GDML writer to produce a file readable by ROOT.

**Comment by noemina** [comment]
Using G4 is indeed how we managed to work around this. I will close this issue. Thank you!
