### ISSUE TITLE
clip edit in GL viewer

### ISSUE THREAD

**Issue by gaponenko** [root-project/root#13081]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Hello,

A ROOT feature that allows to interactively edit the clipping region
in the GL viewer, which worked for me in the past, is broken in ROOT
6.28.  My OS is AlmaLinux 9.2.  I observe the breakage in both ROOT
version obtained by sourcing
/cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-centos9-gcc11-opt/setup.sh
and also in 6.28/04 compiled from source on my system.

To reproduce:  run

$ root $ROOTSYS/tutorials/geom/building.C

- in the GL window, click on the "Clipping" tab
- click "Box"
- check "Edit in Viewer"
- rotate to make the three clip box axes visible
- try to move the clip box along the axes.  It moves along one axis, but not along the other two.

### Reproducer

To reproduce:  run

$ root $ROOTSYS/tutorials/geom/building.C

- in the GL window, click on the "Clipping" tab
- click "Box"
- check "Edit in Viewer"
- rotate to make the three clip box axes visible
- try to move the clip box along the axes.  It moves along one axis, but not along the other two.

### ROOT version

------------------------------------------------------------------
| Welcome to ROOT 6.28/04                        https://root.cern |
| (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
| Built for linuxx8664gcc on Jun 20 2023, 15:28:00                 |
| From heads/latest-stable@49886c13                                |
| With c++ (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)                |
| Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
------------------------------------------------------------------

### Installation method

build from source

### Operating system

AlmaLinux 9.2

**Comment by couet** [comment]
I just tried it on my Mac with ROOT master. It works for me without problems. I can move the clipping box in the 3 directions.

**Comment by gaponenko** [comment]
I will try compiling from master instead of latest-stable.
I have tried using X11 (instead of default Wayland) on my laptop, it did not make a difference.
Andrei

**Comment by gaponenko** [comment]
I compiled from master today, heads/master@v6-29-01-1733-g0e9f93c4b2   
Still the same, can do only single axis moves.
Can someone else test this on Centos 9 or similar?
Andrei

**Comment by gaponenko** [comment]
An update:  if I compile and run ROOT on Scientific Linux 7,  clip editing works even when I use Alma 9 for remote display.
Andrei
