### ISSUE TITLE
wchar_t glyphs are too small on windows

### ISSUE THREAD

**Issue by Neumann-A** [root-project/root#13091]
### Explain what you would like to see improved and how.

https://github.com/root-project/root/blob/9935cb9cb7cf2476857a4d09779e8b399b6229e6/graf2d/mathtext/inc/mathtext.h#L153

is too small on windows to return the correct glyph calucated via e.g. 

https://github.com/root-project/root/blob/9935cb9cb7cf2476857a4d09779e8b399b6229e6/graf2d/mathtext/src/mathtextencode.cxx#L314

### ROOT version

some commit from a few months ago. But it shouldn't matter too much. 

### Installation method

build from source

### Operating system

Windows

### Additional context

I only noticed this since i tried to build root with clang-cl and it choked on the truncation msvc normally does (https://github.com/llvm/llvm-project/issues/63494)

```
E:\all\vcpkg\buildtrees\root\src\4777595a60-bb02050ae7\graf2d\mathtext\src\mathtextencode.cxx(174,33): error: character too large for enclosing character literal type
            default:   _glyph = L'\U0001d538' + (_code[0] - 'A');
```

**Comment by couet** [comment]
It looks like a bug in clan-cl. What do you expect from the ROOt team? we cannot fix a bug in clang-cl.

**Comment by Neumann-A** [comment]
> It looks like a bug in clan-cl. What do you expect from the ROOT team? we cannot fix a bug in clang-cl.

Even though clang-cl is not behaving like MSVC here the problem is that even if MSVC compiles the code it won't behave like ROOT plans it to behave (that is why https://github.com/llvm/llvm-project/issues/63494#issuecomment-1608917289 considers closing the issue I raised in llvm). 

>  What do you expect from the ROOT team?

Fix the bug using MSVC. `wchar_t` is too small on MSVC but compiles the code masking a bug.  
`_glyph = L'\U0001d538' + (_code[0] - 'A');` will never give the expected glyph with MSVC. 

Linux: wchar_t == char32_t
Windows: wchar_t == char16_t

The code needs to be changed to consistently use `char32_t` to be correct across platforms.

**Comment by couet** [comment]
`wchar_t` is used in 711 different places in ROOT. We cannot change all of them to `char32_t` moreover some methods signatures are using `wchar_t`, so, for backward compatibility, we cannot not change that. It seems that most compilers have `wchar_t` equivalent to `char32_t`. It seems only clang-cl has it equivalent to `char16_t`. We do not use clang-cl on Windows to compile ROOT (@bellenot can confirm). It seems this is a bad feature in clang-cl.

**Comment by couet** [comment]
Just to avoid the warning? That's a possibility ... but as `wchar_t` is used in so many places, how can we be sure, that,  in some other places of the code, a `wchar_t` will not be assigned with something too big? in other words, how can we trust ROOT compiled with clang-cl ?

**Comment by Neumann-A** [comment]
> t seems that most compilers have wchar_t equivalent to char32_t. It seems only clang-cl has it equivalent to char16_t

@couet: No the problem is windows: https://godbolt.org/z/4YbW4M4r8 . Even worse GCC and MSVC dues the truncation differently. Basically the code is broken for symbols requiring more than 16 bit and you'll get garbage. (I don't even understand why I have to explain that it has nothing to do with the compiler....)

@bellenot  I doubt it is enough. You basically have to modify all functions which input/output `wchar_t` instead of `wchar_t*`. maybe use a surrogate type like `glyph_t` and adjust it according to the platform in use.

**Comment by bellenot** [comment]
Well, as long as it doesn't break backward compatibility, anything can be done (i.e. internal methods). We **cannot** break user code (public interfaces), even if that means broken code on Windows...

**Comment by bellenot** [comment]
Hi, I have no warning at all on Windows. Can you provide the full log (all warnings and errors related to `wchar_t`), so we can try to fix them all at once? Thanks in advance!

**Comment by Neumann-A** [comment]
> Hi, I have no warning at all on Windows. Can you provide the full log (all warnings and errors related to wchar_t), so we can try to fix them all at once? Thanks in advance!

@bellenot: That is because you don't specify a warning flag (At least I don't see any in the nightly CI) which means MSVC will default to an unuseful `W1` according to `cl -?` (`/W<n> set warning level (default n=1)`). A reasonable warning level for MSVC is `/W3`. Setting that should make C4066 visible (and probably a lot more relevant ones.).

**Comment by Neumann-A** [comment]
@bellenot: You don't get the warning with MSVC because somebody deactivated it 11 years ago when the files where added here:
https://github.com/root-project/root/blob/416f75c9914f1ca35fdbad7d004f5c78cadf95a4/graf2d/mathtext/src/mathtextencode.cxx#L23
and here:
https://github.com/root-project/root/blob/416f75c9914f1ca35fdbad7d004f5c78cadf95a4/graf2d/mathtext/src/mathrender.cxx#L24

So re-enabling would be the first step to make them visible.

**Comment by bellenot** [comment]
Oh! Good catch! Thanks! (shame on me for not having seen this...)

**Comment by Neumann-A** [comment]
You might also want to take a look at these:
https://github.com/root-project/root/blob/416f75c9914f1ca35fdbad7d004f5c78cadf95a4/graf3d/eve7/glu/gluos.h#L62-L64
which seems to assume long is 64 bit. (at least I see `long size` in the code so I assume the correct type should be a signed size_t type and long on windows is only 32 bit and not 64 bit)

**Comment by bellenot** [comment]
OK, so I have a possible solution, using `char32_t` instead of `wchar_t` and replace all the character literals like `L'\U0001d656'` by `U'\U0001d656'` everywhere in `tmathtext`, I verified it works, but in another hand, it's a huge change which doesn't change anything for the rendering (just try the `tmathtext.C` and `tmathtext2.C` tutorials). Anyway, I'll create a PR with that, and we'll see what happens.
And thanks for the `root/graf3d/eve7/glu/gluos.h` info, I'll check.

**Comment by bellenot** [comment]
Note that replacing the offending only character literals like L'\U0001d656' by U'\U0001d656' would most probably work the same...

**Comment by bellenot** [comment]
Indeed, but for that we would need to change the public interfaces of (at least) `TLatex` and `TMathText`.
So now my question is the following: do we simply fix the compilation warnings/errors on Windows, or do we want to make it working with all possible characters, requiring new interfaces with `char32_t`?. I'll let @couet comment on that (BTW, that doesn't work on Linux or Mac either).

**Comment by couet** [comment]
I approved the PR. Once merged we might close this issue.

**Comment by bellenot** [comment]
@couet the PR doesn't work. And I don't see any good solution...

**Comment by couet** [comment]
So we might close the PR in that case. I do not see any good solution either.

**Comment by dpiparo** [comment]
is this a "won't fix" @couet @bellenot ?

**Comment by couet** [comment]
Yes it looks like....

**Comment by bellenot** [comment]
Sorry, but there is nothing we can  do about this...
