### ISSUE TITLE
TScatter plotting axis problem

### ISSUE THREAD

**Issue by cxwx** [root-project/root#13124]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

new TScatter feature is exciting, but I met a bug when I use `TScatter::Draw` and `gPad->DrawFrame()` at the same time.

### Reproducer

```
#include <TScatter.h>
#include <TCanvas.h>
#include <TPad.h>

void scatter()
{
	TCanvas * c1 = new TCanvas();
	c1->Divide(2,2);
	c1->cd(1);
	gPad->DrawFrame(-70, -70, 70, 70);
	const int n = 10;
	double x[n] = {-80, -70, -60, -50, -40, -30, -20, -10, 0, 10};
	double y[n] = {-80, -70, -60, -50, -40, -30, -20, -10, 0, 10};
	double c[n] = {-80, -70, -60, -50, -40, -30, -20, -10, 0, 10};
	double s[n] = {-80, -70, -60, -50, -40, -30, -20, -10, 0, 10};
	auto scatter = new TScatter(n, x, y, c, s);
	scatter->Draw("P same");

}
```
cause axis problem like below 
![截屏2023-06-29 20 49 30](https://github.com/root-project/root/assets/6235641/18584203-e407-4f80-90de-b112f2cd1bcb)

### ROOT version

   ------------------------------------------------------------------
  | Welcome to ROOT 6.29/01                        https://root.cern |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosxarm64 on Jun 21 2023, 03:10:00                   |
  | From heads/master@v6-29-01-1680-gffdc579bbc                      |
  | With Apple clang version 14.0.3 (clang-1403.0.22.14.1)           |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

Rint
version: 6.29/01
building time: 20230621 310
Version time:1150

### Installation method

building from source 

### Operating system

macos m1

**Comment by couet** [comment]
great you found it. I 'll check.

**Comment by couet** [comment]
It behaves like a TGraph. You do not need the option same:
```
void scat2()
{
   TCanvas * c1 = new TCanvas();
   gPad->DrawFrame(-70, -70, 70, 70);
   const int n = 10;
   double x[n] = {-80, -70, -60, -50, -40, -30, -20, -10, 0, 10};
   double y[n] = {-80, -70, -60, -50, -40, -30, -20, -10, 0, 10};
   double c[n] = {-80, -70, -60, -50, -40, -30, -20, -10, 0, 10};
   double s[n] = {-80, -70, -60, -50, -40, -30, -20, -10, 0, 10};
   auto scatter = new TScatter(n, x, y, c, s);
   scatter->Draw("P");
}
```
