### ISSUE TITLE
TMVA doesn't compile with pytorch 2.0.1

### ISSUE THREAD

**Issue by cburgard** [root-project/root#13155]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

The latest master of ROOT doesn't compile with pytorch 2.0.1 installed.

The error message is the following:
```
Torch Version: 2.0.1
RecursiveScriptModule(
  original_name=Model
  (fc1): RecursiveScriptModule(original_name=Linear)
  (fc2): RecursiveScriptModule(original_name=Linear)
  (relu): RecursiveScriptModule(original_name=ReLU)
  (sigmoid): RecursiveScriptModule(original_name=Sigmoid)
)
RecursiveScriptModule(
  original_name=Model
  (fc1): RecursiveScriptModule(original_name=Linear)
  (fc2): RecursiveScriptModule(original_name=Linear)
  (relu): RecursiveScriptModule(original_name=ReLU)
  (sigmoid): RecursiveScriptModule(original_name=Sigmoid)
)
<string>:1: FutureWarning: 'torch.onnx.symbolic_helper._set_onnx_shape_inference' is deprecated in version 1.13 and will be removed in 2.0. Please remove its usage and avoid setting internal variables directly.

Python error message:
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "<string>", line 6, in <dictcomp>
TypeError: 'torch._C.Node' object is not subscriptable
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Failed to run python code: for i in graph[0].nodes():
    globals().update(locals())
    nodeData={}
    nodeData['nodeType']=i.kind()
    nodeAttributeNames=[x for x in i.attributeNames()]
    nodeAttributes={j:i[j] for j in nodeAttributeNames}
    nodeData['nodeAttributes']=nodeAttributes
    nodeInputs=[x for x in i.inputs()]
    nodeInputNames=[x.debugName() for x in nodeInputs]
    nodeData['nodeInputs']=nodeInputNames
    nodeOutputs=[x for x in i.outputs()]
    nodeOutputNames=[x.debugName() for x in nodeOutputs]
    nodeData['nodeOutputs']=nodeOutputNames
    nodeDType=[x.type().scalarType() for x in nodeOutputs]
    nodeData['nodeDType']=nodeDType
    modelData.append(nodeData)
Subprocess aborted
make[2]: *** [tmva/pymva/test/CMakeFiles/SofieCompileModels_PyTorch.dir/build.make:70: SofieCompileModels_PyTorch] Error 1
make[1]: *** [CMakeFiles/Makefile2:62828: tmva/pymva/test/CMakeFiles/SofieCompileModels_PyTorch.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

### Reproducer

`cmake ../src -DCMAKE_BUILD_TYPE=RelWithDebInfo -Droofit=on -Dmysql=off -Dpgsql=off -Droostats=on -Dfortran=off -Dhistfactory=on -Dtmva=on -Dminuit2=on -Droottest=on -Droot7=on -Dtesting=on -Dbuiltin_llvm=on -Dbuiltin_tbb=off -Dbuiltin_nlohmannjson=on -DCMAKE_CXX_STANDARD=17 -DPYTHON_EXECUTABLE=$(which python) -Dfail-on-missing=on -Doracle=off -Dpythia6=off -Dpythia8=off -Dgfal=off -Dvdt=off -Ddavix=off -Droofit_hs3_yml=ON -Droofit_multiprocess=ON -Dbuiltin_zeromq=ON -Dbuiltin_cppzmq=ON`

### ROOT version

ROOT Version: 6.29/01
Built for linuxx8664gcc on Jul 03 2023, 09:06:02
From heads/master@v6-29-01-1847-g7f288f1ca8e

### Installation method

compiled with cmake from master

### Operating system

archlinux

**Comment by cburgard** [comment]
This issue here seems to face the exact opposite problem:
https://github.com/root-project/root/issues/9079
It's also almost 2 years now, so maybe it would be nice to address this :innocent:

**Comment by guitargeek** [comment]
ROOT nowadays works fine with PyTorch 2.0, as one can see in the CI results. Sorry for coming back to this so late!
