### ISSUE TITLE
documentation gives misleading examples

### ISSUE THREAD

**Issue by DarkoVeberic** [root-project/root#13157]
### Explain what you would like to see improved and how.

e.g. the two examples given in https://root.cern.ch/doc/master/classTKey.html#adb768880752e46818736f82b1532e54f are misleading since you cannot dynamically cast a pointer to an object. documentation should give examples that might actually be compiled and here we find just very lazy examples that were not given much thought.

### ROOT version

all versions

### Installation method

irrelewant

### Operating system

irrelevant

**Comment by eguiraud** [comment]
@couet @DarkoVeberic the examples are just missing proper formatting, you can tell from the _italic_ where the `*` symbols are supposed to be displayed. The code in the examples should be escaped.

**Comment by eguiraud** [comment]
Here's a PR that fixes the formatting issue: https://github.com/root-project/root/pull/13166

I think the docs were written for a documentation system predating doxygen that was formatting text as code if it was preceded by 4 spaces. Now we use `~~~{.cpp}` or similar.

@DarkoVeberic thank you for reporting and please do report other problems with the docs should you find them (or feel free to submit pull requests to fix these kind of things!).
