### ISSUE TITLE
[FreeBSD] hardcoded /bin/bash does not work on all platforms

### ISSUE THREAD

**Issue by mkrzewic** [root-project/root#13174]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

FreeBSD installs bash in /usr/local/bin
failing test can be fixed e.g. by either using `#!/bin/sh`  (I think that might work most of the time as I have not seen too many bashisms there) or `#!/usr/bin/env bash` which should be pretty generic (and works at least on linux as well).
What would be the preference?

### Reproducer

ctest

### ROOT version

master

### Installation method

source

### Operating system

freeBSD 13.2p1

**Comment by jalopezg-git** [comment]
Hi @mkrzewic,

Many thanks for reporting!  FWIW, my preference would be to go for the standard POSIX-compliant shell `/bin/sh` unless `bash` is absolutely required.

Cheers.
