### ISSUE TITLE
ScaledSolids in GDML export

### ISSUE THREAD

**Issue by andrmor** [root-project/root#13194]
### Feature description

Geometry module of ROOT (TGeo) features scaled solids, while support for them in TGDMLWrite class is extremely limited and inconsistent. For now, it is possible to export to GDML only two scaled solids: TGeoCone (directly, but only for a subset of possible scalings) and TGeoSphere (only if it has an intersection with a box). All remaining scaled solids are exported as non-scaled ones, which could be an ugly surprise of an unaware user.

One of the main roles of GDML export is for establishing an interface to Geant4. During a discussion with Andrei Gheata, he has mentioned that Geant4 is now natively supports scaled solids. The suggested feature is to update  TGDMLWrite class to use the “scaledSolid” tag.

**Comment by agheata** [comment]
Indeed this needs to be done now that Geant4 supports the `scaledSolid` tag, I'll be looking into it
