### ISSUE TITLE
Properly support macOS in `rootssh`

### ISSUE THREAD

**Issue by jalopezg-git** [root-project/root#13215]
### Explain what you would like to see improved and how.

From the forum: https://root-forum.cern.ch/t/rootssh-from-mac-os-with-homebrew-fails-with-netcat/55593.

Apparently, `rootssh` uses a couple of Linux-specific things that prevent it to work on macOS, namely:
- The script relies on the OpenBSD `netcat` (GNU variant does not support UNIX-domain sockets), which is usually available as `nc` on macOS.
On GNU/Linux, `nc` is typically a symlink to `netcat`; thus, I would advise to replace all occurrences of `netcat` to `nc` in the script.
- It also relies on `xdg-open`, that complies to the freedesktop.org's XDG specification, and that is expected to be present on most (all?) GNU/Linux systems.
However, `open` should be used instead in macOS.

### ROOT version

6.28/04

### Installation method

Not specified.

### Operating system

MacOS Ventura 13.4

**Comment by linev** [comment]
Hi, can you test changes from PR #13218?

**Comment by linev** [comment]
Should be fixed by #13218
