### ISSUE TITLE
warning: unknown attribute 'optional' on ubuntu 20.04

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#13265]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

I installed ROOT on ubuntu 20.04 via conda and I get the following warnings when `import`ing ROOT in a Python session

```
/root/mambaforge/envs/myenv/etc/cling/std.modulemap:257:29: warning: unknown attribute 'optional' [-Wignored-attributes]
  module "memory_resource" [optional] {
                            ^
/root/mambaforge/envs/myenv/etc/cling/std.modulemap:447:27: warning: unknown attribute 'optional' [-Wignored-attributes]
  module "bits/chrono.h" [optional] {
                          ^
/root/mambaforge/envs/myenv/etc/cling/std.modulemap:531:41: warning: unknown attribute 'optional' [-Wignored-attributes]
  explicit module "bits_ranges_base_h" [optional] {
                                        ^
/root/mambaforge/envs/myenv/etc/cling/std.modulemap:538:32: warning: unknown attribute 'optional' [-Wignored-attributes]
  module "bits/ranges_util.h" [optional] {
                               ^
/root/mambaforge/envs/myenv/etc/cling/std.modulemap:559:40: warning: unknown attribute 'optional' [-Wignored-attributes]
  module "bits/uses_allocator_args.h" [optional] {

``` 

I have seen issues with slightly similar problems, but it was regarding the missing module, not the unknown attribute. I will try to see if this behaviour is reproduced also on other ubuntu versions or distros.

### Reproducer

```
docker run --rm -it ubuntu:20.04
apt-get update && apt-get install curl
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
bash Mambaforge-$(uname)-$(uname -m).sh -b
source /root/mambaforge/bin/activate
mamba create -n myenv root
conda activate myenv
python -c "import ROOT"
```

### ROOT version

6.28.04

### Installation method

conda

### Operating system

ubuntu 20.04

**Comment by hahnjo** [comment]
The `optional` attribute was implemented via https://github.com/root-project/root/commit/aa874ab2417a1a9b2dc68bb132b47f7e19d99acf, so this likely means that the build is not using the right version of Clang!

**Comment by vepadulano** [comment]
Ok, probably I have to go check in the configuration of the conda builds about this... let's see what I find

**Comment by Pupoin** [comment]
@vepadulano  hi, I meet the same problem, have you ever solved it ?

**Comment by chrisburr** [comment]
@hahnjo It looks like that patch was never added to `http://root.cern/git/clang.git@ROOT-patches` (which is the source of the clang+root patches build used for conda-forge)?

**Comment by chrisburr** [comment]
From a cursorary it looks like there are 6 patches missing from the ROOT-patches branch of `clang` (I assume there still aren't any `llvm` patches for 6.28.x): https://github.com/conda-forge/clangdev-feedstock/pull/232/commits/17a083085b411d7d69e0f86b40b19a4a24a383dc

**Comment by hahnjo** [comment]
Hi @chrisburr, the individual `llvm.git` and `clang.git` will not be updated going forward. We migrated the patches to a fork of the monorepo: https://github.com/root-project/llvm-project/ This has all patches corresponding to ROOT `master`, "pinned" by `interpreter/llvm-project/llvm-project.tag`, which will also make things a lot easier for the next release cycle.

> I assume there still aren't any `llvm` patches for 6.28.x

There are: https://github.com/root-project/llvm-project/commits/ROOT-llvm13/llvm I don't know if you apply them for Conda nor if you need them, they are either for C++20 builds, Windows, or PowerPC...

**Comment by chrisburr** [comment]
Ah wonderful, that'll make my life easier!

A new conda-forge build of ROOT is currently working its way through the deployment chain which fixes the `unnown attribute 'optional'` issue.

**Comment by chrisburr** [comment]
This should now be fixed in the latest build on conda-forge.
