### ISSUE TITLE
Building fails with c++20: `RRangeCast.hxx`  and `std::span`

### ISSUE THREAD

**Issue by matLogh** [root-project/root#13270]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Dear experts,
I am trying to compile ROOT 6.28.04 with C++20 standard. It seems that the c++ standard gets downgraded during the compilation, because while compiling the `RRangeCast.hxx` it no longer recognize `std::span`. I am able to compile short C++ code involving `std::span`. This is the full error i get:

```
/opt/root6/root-6.28.04_src/core/foundation/inc/ROOT/RRangeCast.hxx:186:27: error: ‘span’ is not a member of ‘std’
  186 | RRangeCast<T, false, std::span<U>> RangeStaticCast(U (&arr)[N])
      |                           ^~~~
/opt/root6/root-6.28.04_src/core/foundation/inc/ROOT/RRangeCast.hxx:186:32: error: template argument 3 is invalid
  186 | RRangeCast<T, false, std::span<U>> RangeStaticCast(U (&arr)[N])
      |                                ^
/opt/root6/root-6.28.04_src/core/foundation/inc/ROOT/RRangeCast.hxx:186:33: error: expected unqualified-id before ‘>’ token
  186 | RRangeCast<T, false, std::span<U>> RangeStaticCast(U (&arr)[N])
      |                                 ^~
/opt/root6/root-6.28.04_src/core/foundation/inc/ROOT/RRangeCast.hxx:225:26: error: ‘span’ is not a member of ‘std’
  225 | RRangeCast<T, true, std::span<U>> RangeDynCast(U (&arr)[N])
      |                          ^~~~
/opt/root6/root-6.28.04_src/core/foundation/inc/ROOT/RRangeCast.hxx:225:31: error: template argument 3 is invalid
  225 | RRangeCast<T, true, std::span<U>> RangeDynCast(U (&arr)[N])
      |                               ^
/opt/root6/root-6.28.04_src/core/foundation/inc/ROOT/RRangeCast.hxx:225:32: error: expected unqualified-id before ‘>’ token
  225 | RRangeCast<T, true, std::span<U>> RangeDynCast(U (&arr)[N])
      |                                ^~
make[2]: *** [core/imt/CMakeFiles/Imt.dir/build.make:132: core/imt/CMakeFiles/Imt.dir/src/RTaskArena.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:32924: core/imt/CMakeFiles/Imt.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

### Reproducer

My [CMakeCache.txt](https://github.com/root-project/root/files/12080083/CMakeCache.txt) used for the build.

### ROOT version

ROOT 6.28.04

### Installation method

build from source

### Operating system

Ubuntu 20.04 running under WSL2

### Additional context

Trying to build from source ROOT 6.28.04 with gcc 10.3 on WSL2 running ubuntu 20.04

**Comment by hahnjo** [comment]
Hi @matLogh, this is weird since `RRangeCast.hxx` includes `#include "ROOT/RSpan.hxx"` which either includes the standard `<span>` or provides ROOT's "backported" copy for use with older C++ versions. It could be related to using GCC 10.3, some C++20 stuff is only there since GCC 11/12. I will need to do a test build later on...

In related matters, please note that one of the C++20 problems escaped us for 6.28/04 and a fix (https://github.com/root-project/root/pull/13242) will only released in August the earliest. In the mean time, you may try the `v6-28-00-patches` branch.

**Comment by matLogh** [comment]
Thanks for the update! I just managed to compile it with c++20 by purging my locally build TBB and using the build-in version of ROOT instead (I had problems with TBB while trying to recompile root 6.26). I don't understand however how those things are related, but from my side the issue is solved, or well, not reproducible anymore. Thanks for your time!
