### ISSUE TITLE
Primer wiki misspelling

### ISSUE THREAD

**Issue by strombolini** [root-project/root#13276]
### Explain what you would like to see improved and how.

![image](https://github.com/root-project/root/assets/67758577/ee0ba7fe-e7d0-40f1-878a-f7434e26232a)
https://root.cern/primer/#a-more-complete-example
In Primer > ROOT Macros > A More Complete Example, the graph's x units are misspelled.

### ROOT version

N/A

### Installation method

N/A

### Operating system

Linux

**Comment by ferdymercury** [comment]
Also here: https://root.cern/primer/graph_with_expectation.png

**Comment by dpiparo** [comment]
Thanks for reporting. I proposed a fix here: https://github.com/root-project/web/pull/872

**Comment by dpiparo** [comment]
Oh, I see a fix was already proposed. Please ignore the above.

**Comment by ferdymercury** [comment]
The fix i proposed only solves the script, but not the result, so your MR is still relevant :)
