### ISSUE TITLE
[cling] long double type incorrectly parsed by interpreter

### ISSUE THREAD

**Issue by cpp-deep-learning** [root-project/root#13288]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

I use the root's REPL to create my code.when my function return type is long double,the REPL report me error
![image](https://github.com/root-project/root/assets/54460355/d2762097-cbbc-4844-b5c9-f129eb9576ef)

### Reproducer

long double t(long double x) {
return x*x;
}

### ROOT version

ROOT 6.29/01 
     Built for linuxx8664gcc on Jul 20 2023, 11:06:00                 |
  | From tag , 21 December 2022                                      |
  | With c++ (GCC) 13.1.1 20230429

### Installation method

build from source

### Operating system

Manjaro Linux

**Comment by pamputt** [comment]
Indeed, "double d(long double x) { return x*x; }" is accepted but "long double d(long double x) { return x*x; }" is not.
