### ISSUE TITLE
TGraph does not re-compute minimum and maximum when a point is added

### ISSUE THREAD

**Issue by rzarr** [root-project/root#13340]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

When adding a point to a TGraph with the SetPoint() method, the object does not re-compute its minimum (fMinimum) and maximum (fMaximum). In the following macro I just added one point with random X and Y values to an empty TGraph and the printed minimum and maximum are still set at their default value (-1111)

### Reproducer

#include "TGraph.h"

void macro()
{
	TGraph* gr = new TGraph();
	gr->Set(gr->GetN()+1);
	gr->SetPoint(gr->GetN()-1, 2, 10);

	std::cout << gr->GetMinimum() << "\t" << gr->GetMaximum() << std::endl;
}

### ROOT version

root 6.26/10 

### Installation method

built from source

### Operating system

Ubuntu 20.04

**Comment by couet** [comment]
`GetMinimum` and `GetMaximum` returns de Minimum and Maximum of the frame in which the graph is drawn. You need to draw the graph to have them defined. What you need is:

### File `rzarr.C`:
```
double min(int n,double *x) {
   double min=x[0];
   for(int i=1; i<n; i++) {if (x[i]<min) min=x[i];}
   return min;
}

double max(int n,double *x) {
   double max=x[0];
   for(int i=1; i<n; i++) {if (x[i]>max) max=x[i];}
   return max;
}

void rzarr()
{
   TGraph* gr = new TGraph();
   gr->SetPoint(0,1,2);
   gr->SetPoint(1,3,5);
   gr->SetPoint(2,2,1);
   std::cout << min(gr->GetN(), gr->GetY()) << "\t"
             << max(gr->GetN(), gr->GetY()) << std::endl;
   std::cout << gr->GetMinimum() << "\t" << gr->GetMaximum() << std::endl;
}
```
which gives:
```
root [0] .x rzarr.C
1	5
-1111	-1111
root [1] 
```
