### ISSUE TITLE
Recommended Method of Opening TFile Prevents Drawing Histograms from Within The File

### ISSUE THREAD

**Issue by alex-gekow** [root-project/root#13369]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

The currently documented method of opening a TFile utilizes unique pointers:
`std::unique_ptr<TFile> myFile( TFile::Open("file.root", "RECREATE") );`

However, if a histogram is read from this file via and then drawn:
`TH1F* h1 = (TH1F*)file->Get("Hist");`
`TCanvas *c1 = new TCanvas("c1","Fitting Demo");`
`c1->cd()`
`h1->Draw()`

The canvas is empty and the histogram will not be drawn. This can be resolved by opening the file as a raw pointer. Either the documentation should consider this, or there is a bug with `unique_ptr` that should be addressed.

### Reproducer

1) Read a TFile as a unique_ptr
2) Get a histogram from the file
3) Draw the histogram

run like root -x myMacro.cxx
[inputFile.zip](https://github.com/root-project/root/files/12231406/inputFile.zip)

`void myMacro(){`
`    std::unique_ptr<TFile> file(TFile::Open("inputFile.root", "read"));`
`    TH1F* h1 = (TH1F*)file->Get("h1");`
`    TCanvas *c1 = new TCanvas("c1","Fitting Demo");`
`    c1->cd();`
`    h1->Draw()`
`}`

### ROOT version

Tested on:

Linux: 6.26
Linux: 6.28
MacOS: 6.26

### Installation method

pre-built binary, homebrew

### Operating system

MacOS, Linux

**Comment by lmoneta** [comment]
This is not a bug. The histogram read from a file is managed by the file, so it is deleted when the file is deleted. So if you use the unique_ptr the histogram will be deleted when exiting the macro and will also be deleted from the TCanvas. 
If your intention is to keep the histogram alive after executing the macro you should not use the unique_ptr to open the file.
