### ISSUE TITLE
Please recover `SrvAuthenticate` from libSrvAuth library

### ISSUE THREAD

**Issue by xkzl** [root-project/root#13387]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

A commit (https://github.com/root-project/root/commit/b327dd8fd159494666842607708140c429fa4055) deleted an important feature about authentication using local accounts from TServerSocket.

I think it is wrong that the file is not used. I guess SrvAuthenticate is defined in DaemonUtils.[h|cxx] and refers to the libSrvAuth !
```
$ grep srvauthenticate -i -R ../src
../src/net/net/src/TServerSocket.cxx:TVirtualMutex *gSrvAuthenticateMutex = 0;
../src/net/net/src/TServerSocket.cxx:   R__LOCKGUARD2(gSrvAuthenticateMutex);
../src/net/net/src/TServerSocket.cxx:   R__LOCKGUARD2(gSrvAuthenticateMutex);
../src/net/net/src/TServerSocket.cxx:      R__LOCKGUARD2(gSrvAuthenticateMutex);
../src/net/net/src/TServerSocket.cxx:      // Locate SrvAuthenticate
../src/net/net/src/TServerSocket.cxx:      Func_t f = gSystem->DynFindSymbol(srvlib,"SrvAuthenticate");
../src/net/net/src/TServerSocket.cxx:         Error("Authenticate", "can't find SrvAuthenticate");
```

Additionally, https://root.cern/doc/master/authserv_8C.html is not working due to this.

Knowing that there are all these ./src/net/net/ useful classes about remote connections.. why is that TSocket is being deprecated ? https://github.com/root-project/root/commit/8ef5d04e0102290cc2457c5a7cc40fc9874fa006 . This is incredibly useful feature.. same for all other basic communication protocol developped in `./net/net/` directory

```
$ grep srvauthenticate -i -R ../src
../src/net/net/src/TServerSocket.cxx:TVirtualMutex *gSrvAuthenticateMutex = 0;
../src/net/net/src/TServerSocket.cxx:   R__LOCKGUARD2(gSrvAuthenticateMutex);
../src/net/net/src/TServerSocket.cxx:   R__LOCKGUARD2(gSrvAuthenticateMutex);
../src/net/net/src/TServerSocket.cxx:      R__LOCKGUARD2(gSrvAuthenticateMutex);
../src/net/net/src/TServerSocket.cxx:      // Locate SrvAuthenticate
../src/net/net/src/TServerSocket.cxx:      Func_t f = gSystem->DynFindSymbol(srvlib,"SrvAuthenticate");
../src/net/net/src/TServerSocket.cxx:         Error("Authenticate", "can't find SrvAuthenticate");
```

### Reproducer

https://root.cern/doc/master/authserv_8C.html
https://root.cern/doc/master/authclient_8C.html

### ROOT version

2023/08/01

### Installation method

build form source

### Operating system

macos

**Comment by ferdymercury** [comment]
I proposed a PR to restore those two files.

> Knowing that there is all these ./src/net/net/ useful classes about remote connections.. why is that TSocket is being deprecated ? [8ef5d04](https://github.com/root-project/root/commit/8ef5d04e0102290cc2457c5a7cc40fc9874fa006) . This is incredibly useful feature.. same for all other basic communication protocol developped in `./net/net/` directory

I let @guitargeek comment on that particular commit.

**Comment by guitargeek** [comment]
Hi! TSocket is not deprecated, just considered as legacy:

https://github.com/root-project/root/pull/13357#pullrequestreview-1556318542

This means that we will not continue development of it anymore, but it will stay in ROOT. Deprecation would mean that it's staged for removal at some point, but this is not the case.
