### ISSUE TITLE
TTreePlayer::Scan printing incorrect unsigned long long, ULong64_t values

### ISSUE THREAD

**Issue by wdconinc** [root-project/root#13395]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

On (at least) ROOT 6.28.04, `TTree::Scan` does not print `unsigned long long` in the tree correctly, even when specifying the appropriate format `%llx` for `unsigned long long`. Printing incorrect values, in particular for types used for bit patterns, is very confusing.

Possibly related prior reports: unresolved https://sft.its.cern.ch/jira/browse/ROOT-8009 reports similar behavior in `Draw` but is listed as affecting only < 5.28.

### Reproducer

```
TTree t
ULong64_t llu = 0x4ac1500101113bLL
t.Branch("llu", &llu)
t.Fill()
t.Scan("llu:llu","","col=22llx:22lx")
printf("%llx %lx\n", llu, (unsigned long) llu)
sizeof(ULong64_t)
sizeof(unsigned long)
sizeof(unsigned long long)
```
which produces:
```
$ root -l
root [0] TTree t
(TTree &) Name:  Title: 
root [1] ULong64_t llu = 0x4ac1500101113bLL
(unsigned long long) 21041697634980155
root [2] t.Branch("llu", &llu)
(TBranch *) 0x55a244d5c5b0
root [3] t.Fill()
(int) 8
root [4] t.Scan("llu:llu","","col=22llx:22lx")
**************************************************************
*    Row   *                    llu *                    llu *
**************************************************************
*        0 *         4ac1500101113b *         4ac1500101113c *
**************************************************************
(long long) 1
root [5] printf("%llx %lx\n", llu, (unsigned long) llu)
4ac1500101113b 4ac1500101113b
(int) 30
root [6] sizeof(ULong64_t)
(unsigned long) 8
root [7] sizeof(unsigned long)
(unsigned long) 8
root [8] sizeof(unsigned long long)
(unsigned long) 8
```

The length of `ULong64_t`, `unsigned long`, and `unsigned long long` are all the same.

`printf` with format `%llx` (`unsigned long long`) and `%lx` (`unsigned long`) all print the right value.

Nevertheless, `TTree::Scan` prints a different (incorrect) value when printing as `%llx`.

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.28/04                        https://root.cern |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on May 08 2023, 02:44:07                 |
  | From tags/v6-28-04@v6-28-04                                      |
  | With g++-12 (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0                |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

Spack (develop)

### Operating system

Linux (Ubuntu 23.04)

**Comment by wdconinc** [comment]
This may be a duplicate of https://github.com/root-project/root/issues/7844, it seems.

**Comment by ferdymercury** [comment]
Yep, and of https://sft.its.cern.ch/jira/browse/ROOT-8009

**Comment by ferdymercury** [comment]
As it's a duplicate, let's close and use https://github.com/root-project/root/issues/7844 as tracker.
