### ISSUE TITLE
Artefact when drawing `TGraph2D` with "tri1" draw option

### ISSUE THREAD

**Issue by linev** [root-project/root#13424]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When drawing `TGraph2D` with "tri1" draw option and configure min/max Z values which do not fully covers existing range,
wrong drawing appears.
![c1](https://github.com/root-project/root/assets/4936580/fc74b088-f09b-499d-8181-07f8b436f5a7)

### Reproducer

Reproducer macro:
[gr2d.C.txt](https://github.com/root-project/root/files/12302619/gr2d.C.txt)

### ROOT version

master branch, most probably all previous branches as well

### Installation method

build from source

### Operating system

OpenSUSE Linux

**Comment by couet** [comment]
I see the artefact too. note that the following is ok:
```
   dt->SetMaximum(dt->GetZmax() + 0.1);
```

**Comment by couet** [comment]
Fix here: https://github.com/root-project/root/pull/13585
