### ISSUE TITLE
[DF] Add a warning if the second event loop on the same RDataFrame is started

### ISSUE THREAD

**Issue by martamaja10** [root-project/root#13440]
### Explain what you would like to see improved and how.

Sometimes the users unintentionally start a new event loop. This can cause issues in the MT mode, as lack of order in processing entries may impact the results. This is motivated by the issue discussed on the forum: https://root-forum.cern.ch/t/unstable-results-when-enabling-mt-and-filling-a-thnd-histogram-using-take/

### ROOT version

up to 6.28.04

### Installation method

built from source

### Operating system

MacOS

**Comment by vepadulano** [comment]
> Sometimes the users unintentionally start a new event loop. 

I see the point in warning for the particular case of the linked forum post. I am thinking whether we can actually distinguish when a second event loop is triggered unintentionally vs intentionally.

I imagine a prototyping session where I'm at a prompt (root, Python, Jupyter etc.) and I'm doing some preliminary data exploration on my RDF. In that case I may intentionally only run some operations first (e.g. a `Display` of some columns I've never seen before) and only afterwards I actually define some analysis steps.

**Comment by dpiparo** [comment]
Trying to wrap up: I agree that the interactive case is real, and more than one loop is triggered on purpose. Likewise, I tend to think that it's not really possible to distinguish this case from the case when subsequent, unintended, runtime performance degrading loops are triggered (how can we check we are not at the root prompt, python prompt, ipython, jupyter...).

Doesn't all this point to closing this issue?

**Comment by martamaja10** [comment]
True, I agree that we could close this issue, but I think we should instead improve documentation, maybe also with some "bad examples" so that the users are warned even better?

**Comment by dpiparo** [comment]
good idea. Let's close once this is done.
