### ISSUE TITLE
hadd help and manual describe inconsistently the "-f" option

### ISSUE THREAD

**Issue by gsportelli** [root-project/root#13445]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

when running `hadd -h` or `man hadd` I read the following for option `-f`:

% hadd -h
...
  -f     Gives the ability to specify the compression level of the target file(by default 4)
...

% man hadd
...
       The target file is newly created and must not exist, or if -f ("force") is given, it must not be one of the source files.
...
       -f     Gives the ability to specify the compression level of the target file(by default 4)

It is unclear what `-f` does then, does it force overwrite or specify compression level?

When I try the command with the -f option, I'm given the following prompt: Pass "-f" argument to force re-creation of output file.

Therefore I deduce that -f works as "force", however since the option deals with overwrites it would be better not to be ambiguous about it.

### Reproducer

Run `man hadd`

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.28/04                        https://root.cern |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosxarm64 on May 08 2023, 02:44:07                   |
  | From tags/v6-28-04@v6-28-04                                      |
  | With Apple clang version 13.1.6 (clang-1316.0.21.2.5)            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

(note that on MacOS I need to run  `root -b -q | pbcopy` instead of `root -b -q | xclip -sel clip`)

### Installation method

build

### Operating system

MacOS 12.6.7

**Comment by couet** [comment]
So it seems `man hadd` is correct and `hadd -h` is not. I will fix that.s

**Comment by couet** [comment]
@gsportelli 
Also, `hadd -h` is not wrong. The primarely function of the `-f` option is explained at the beginning:

_[...] The target file is
newly created and must not exist, or if -f ("force") is given, must
not be one of the source files._

**Comment by couet** [comment]
PR here: https://github.com/root-project/root/pull/13540

**Comment by couet** [comment]
Fix. Thanks for having seen it.
