### ISSUE TITLE
[RF] RooFit open issues and backports for 6.30 releases

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#13458]
# 6.30.00

**GitHub issue** that we still want to resolve before the release:

- [x] https://github.com/root-project/root/issues/11965
- [x] https://github.com/root-project/root/issues/13852

**Other items** that still need to be done without any associated GitHub issue:

- [x] This the problem with HistFactory component plotting [described on the forum](https://root-forum.cern.ch/t/problems-plotting-individual-components-with-roofit-histfactory/55151). Fixed in:
       #13464
- [x] Do some fix such we don't need to reduce the precision in this [HS3 simultaneous fit unit test](https://github.com/root-project/root/blob/master/roofit/hs3/test/testHS3SimultaneousFit.cxx#L118)

**Backports** that need to be made for the v6.30 branch (in this particular order from top to bottom, to not have a commit history too different from master):

- [x] https://github.com/root-project/root/pull/13812
- [x] https://github.com/root-project/root/pull/13784
- [x] https://github.com/root-project/root/pull/13853
- [x] https://github.com/root-project/root/pull/13813
- [x] https://github.com/root-project/root/pull/13879
- [x] https://github.com/root-project/root/pull/13881
- [x] https://github.com/root-project/root/pull/13883
- [x] https://github.com/root-project/root/pull/13890
- [x] https://github.com/root-project/root/pull/13896
- [x] https://github.com/root-project/root/pull/13911
- [x] https://github.com/root-project/root/pull/13914
- [x] https://github.com/root-project/root/pull/13109
- [x] https://github.com/root-project/root/pull/13905
- [x] https://github.com/root-project/root/pull/13925
- [x] https://github.com/root-project/root/pull/13912
- [x] https://github.com/root-project/root/pull/13915
- [x] https://github.com/root-project/root/pull/13918
- [x] https://github.com/root-project/root/pull/13929
- [x] https://github.com/root-project/root/pull/13986

The backports were grouped in a few PRs to `v6-28-00-patches`:

1. https://github.com/root-project/root/pull/13870
2. https://github.com/root-project/root/pull/13891
3. https://github.com/root-project/root/pull/13909
4. https://github.com/root-project/root/pull/13930
5. https://github.com/root-project/root/pull/13940
6. https://github.com/root-project/root/pull/13987

**Comment by Axel-Naumann** [comment]
That's probably 6.28? We might release 6.30 in September, approx, so that would be backporting from the future ;-) :skateboard:

**Comment by guitargeek** [comment]
# 6.30.02

**Backports** that need to be made for the v6.30 branch (in this particular order from top to bottom, to not have a commit history too different from master):

- [] https://github.com/root-project/root/pull/14021

The backports were grouped in a few PRs to `v6-30-00-patches`:

1. -

**Comment by guitargeek** [comment]
# 6.30.04

**GitHub issue** that we still want to resolve before the release:

- [ ] https://github.com/root-project/root/issues/11486
- [ ] https://github.com/root-project/root/issues/13729

**Other items** that still need to be done without any associated GitHub issue:

- [ ] Make sure that parameter ranges from "domains" are respected in HistFactory JSON import. Try for example customizing the range of the signal strength parameter.
- [ ] make sure that this complicated conditional fit also gives the same result in BatchMode:
      https://root-forum.cern.ch/t/strange-behaviour-for-multidimensional-pdf-with-conditional-observables/51012/3

**Backports** that need to be made for the v6.30 branch (in this particular order from top to bottom, to not have a commit history too different from master):

- [x] https://github.com/root-project/root/pull/13995
- [x] https://github.com/root-project/root/pull/14021
- [x] https://github.com/root-project/root/pull/14043
- [x] https://github.com/root-project/root/pull/14044
- [x] https://github.com/root-project/root/pull/13373 (as a dependency of the next PR on Minuit 2)
- [x] https://github.com/root-project/root/pull/14026
- [x] https://github.com/root-project/root/pull/13863
- [ ] https://github.com/root-project/root/pull/13822
- [ ] https://github.com/root-project/root/pull/13966

The backports were grouped in a few PRs to `v6-30-00-patches`:

1. https://github.com/root-project/root/pull/14008
2. https://github.com/root-project/root/pull/14047

**Comment by guitargeek** [comment]
# 6.30.06

**GitHub issue** that we still want to resolve before the release:

- [ ] https://github.com/root-project/root/issues/11486
- [ ] https://github.com/root-project/root/issues/13729

**Other items** that still need to be done without any associated GitHub issue:

- [ ] Make sure that parameter ranges from "domains" are respected in HistFactory JSON import. Try for example customizing the range of the signal strength parameter.
- [ ] make sure that this complicated conditional fit also gives the same result in BatchMode:
      https://root-forum.cern.ch/t/strange-behaviour-for-multidimensional-pdf-with-conditional-observables/51012/3

**Backports** that need to be made for the v6.30 branch (in this particular order from top to bottom, to not have a commit history too different from master):

- [ ] https://github.com/root-project/root/pull/14759
- [ ] https://github.com/root-project/root/pull/14762
- [ ] https://github.com/root-project/root/pull/13966

The backports were grouped in a few PRs to `v6-30-00-patches`:

1.
