### ISSUE TITLE
Assertion failure in TMVA with `vector iterators incompatible` error on Windows

### ISSUE THREAD

**Issue by bellenot** [root-project/root#13497]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

In `tmva/tmva/src/MethodLD.cxx`, line 177 and line 202, at `std::vector<Float_t>::const_iterator it = ev->GetValues().begin()`, `it` is initialised to `GetValues().begin()` and is then compared by `!=` to `GetValues().end()`. But `getValue()` returns a vector by value, not by reference, so it returns a copy, which means that every time we call `getValue()`, we get a different vector, so we get incompatible iterators. For the compiler, this does not make any difference. Type safety does not help, two iterators which belong to different container instances have the same type, so the code compiles. At run time, however, additional checks are made to ensure that two iterators that are being compared really belong to the same container object. (As explained [here](https://stackoverflow.com/questions/32978410/debug-assertion-vector-iterators-incompatible-c))
A possible fix is in the PR #13321

### Reproducer

Run the TMVA tests in debug mode with /RTC1 flag on Windows.

### ROOT version

master

### Installation method

built from source

### Operating system

Windows

### Additional context

This is visible on Windows with RTC1, but is relevant to all OSes

**Comment by guitargeek** [comment]
Closed by:
  * https://github.com/root-project/root/pull/13321
