### ISSUE TITLE
Compilation of `dataframe/test/datasource_arrow.cxx`  fails on standard linux distribution

### ISSUE THREAD

**Issue by linev** [root-project/root#13516]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

When compiles ROOT on OpenSUSE Linux, one gets following compilation failure:
```
/home/linev/git/json/tree/dataframe/test/datasource_arrow.cxx:14:10: fatal error: arrow/testing/builder.h: No such file or directory
   14 | #include <arrow/testing/builder.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Seems to be `/usr/include/arrow/testing` directory not exists at all when `arrow` installed as provided by linux distributions.

### Reproducer

Compilation with `-Darrow=ON` on OpenSUSE Tumbleweed

### ROOT version

master

### Installation method

build from source

### Operating system

OpenSUSE Linux

**Comment by ktf** [comment]
i will check later tonight. i think it might be trivial.

Ciao,
Giulio

**Comment by ktf** [comment]
#13523 should fix it.
