### ISSUE TITLE
Request _C++20_ module compatibility with ROOT 6.30/00

### ISSUE THREAD

**Issue by greenc-FNAL** [root-project/root#13536]
### Feature description

As C++20 goes mainstream, there are many reasons to start using C++20 modules in a non-ROOT context to provide well-designed and encapsulated APIs. Generated module files are compiler-specific, which would seem likely to lead to issues with interactions between Cling-generated PCM dictionaries and any C++20 modules used by the code upon which those dictionaries depend.

My request is for the upcoming ROOT with Clang 16 to be able to accommodate the generation and use of PCM dictionaries where dependencies thereof are or use C++20 modules. This may or may not involve transitioning PCM dictionary generation to use C++20 modules as opposed to Clang's original implementation of C++ modules.

### Alternatives considered

Short of having to operate under the constraint that no code depended upon by a ROOT dictionary be or use C++20 modules at any level (direct or indirect), I do not see an alternative to providing the requested feature, although it is certainly possible I am overestimating the complexity of the situation and that the feature request either is already implemented or, "just works" already in 6.28/04.

### Additional context

In dealing with https://github.com/root-project/root/issues/13461 it was suggested by @pcanal and later verified _in vitro_ that using PCM dictionaries vs `.rootmap` dictionaries would be a viable workaround. This led to thoughts about ROOT C++ modules vs non-ROOT C++20 module generation, and eventually this feature request.

**Comment by vgvassilev** [comment]
> @vgvassilev Thanks for your detailed and thoughtful reply. I'm confused about one thing in particular though: in the light of https://en.cppreference.com/w/cpp/language/modules#Global_module_fragment (as pointed out to me by my colleague @knoepfel), it would not seem to be a given in the general case that bottom-up modularization is required (or even desired). I think I understand your argument re serialization, but I'm not sure how that impacts our request to have ROOT support interacting with externally-generated C++20 modules.

That is correct since that is implementation/vendor-specific. You can follow the discussions on the [SG15](https://lists.isocpp.org/mailman/listinfo.cgi/sg15) side at isocpp.

> I will look at the materials you reference and attempt to do some further reading on the subject. It does seem though, that there's something of a chicken-and-egg problem here: unless ROOT is proactive in developing support for external use of C++20 modules, then it becomes difficult for ROOT-using projects to even consider using C++20 modules in their own projects if it is likely to intersect with their use of ROOT.

The C++ modules support in the dictionaries is based on "Clang modules". This is the very same implementation of the "C++ 20 modules". In the end the implementation in Clang has driven the standardization of the functionality. In practice, modulo the import/export syntax and a few quirks what ROOT uses is the basis of what you call here "C++20 modules".

If you provide a concrete, close-to-production example that works across various vendors (clang and gcc, lets exclude for now msvc) where ROOT is the blocker I can take a look at it and figure out how to support it.

**Comment by greenc-FNAL** [comment]
Thanks again for the thoughtful reply.
> If you provide a concrete, close-to-production example that works across various vendors (clang and gcc, lets exclude for now msvc) where ROOT is the blocker I can take a look at it and figure out how to support it.
I would like to do this; the question I have is, against what ROOT version/branch would it be most useful to work? Is 6.28/04 sufficient with LLVM/Clang 13, or  should I be using master or something else?

**Comment by vgvassilev** [comment]
Either branch should be sufficient. I'd prefer the master.

**Comment by dpiparo** [comment]
Is this issue to be considered closed for 6.32, @vgvassilev ?

**Comment by vgvassilev** [comment]
I do not think the outcome of the discussion was sufficient to make @greenc-FNAL happy. Although we should move their codes to use modules in dictionaries first …

**Comment by greenc-FNAL** [comment]
@vgvassilev @dpiparo @pcanal Please let me know when #15696 is merged and I will try to pick this up again with GCC14.

**Comment by dpiparo** [comment]
it's merged and happily working in master since more than one month @greenc-FNAL
