### ISSUE TITLE
`rootcling --genreflex` ignores `<field... transient="true"/>` in selection XML

### ISSUE THREAD

**Issue by greenc-FNAL** [root-project/root#13543]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

After following advice to transition from `genreflex` to `rootcling --genreflex`, we discovered that IO dictionaries generated for classes with transient (non-persistent) data members actually included stream information for those data members, in contrast both with the behavior of `genreflex` and our desire.

### Reproducer

1. Download, unpack and `cd` into the top level directory of [rootcling-genreflex-transient-bug.tgz](https://github.com/root-project/root/files/12439967/rootcling-genreflex-transient-bug.tgz)
2. `./makeit good`
3. `./makeit`

The output of the final `ROOT -b` command should be the same down to the checksum reported if the problem were not present.

### ROOT version

`ROOT 6.28/04@30598a8430`

### Installation method

UPS

### Operating system

SL7

### Additional context

Compiled with GCC 13.1.0/C++20.

May be related to the (insufficiently detailed) #13361.

**Comment by greenc-FNAL** [comment]
Bug is reproduced on https://github.com/root-project/root/commit/4f0450b46ecdc1710e4d3e9d00d2200b4fff7644.

**Comment by pcanal** [comment]
The problem is solved by passing the option `--reflex` to rootcling.

**Comment by pcanal** [comment]
@vgvassilev It is a bit surprising that `rootlcing --reflex ... selection.xml` works but `rootcling ... selection.xml` partially works but silently fails.   The current code will parse and use the selection.xml but a few internal part (of the selection.xml handling) are disabled without the `--reflex`.  See `rootcling_impl.cxx:406` for example.

**Comment by vgvassilev** [comment]
> @vgvassilev It is a bit surprising that `rootlcing --reflex ... selection.xml` works but `rootcling ... selection.xml` partially works but silently fails. The current code will parse and use the selection.xml but a few internal part (of the selection.xml handling) are disabled without the `--reflex`. See `rootcling_impl.cxx:406` for example.

Ah, yes, that makes sense. We have seen that on several occasions actually and that’s why we added this flag. Do you want to turn that logic on when we see selection.xml file? Is there a use case where we would want rootcling only behavior and still pass a selection.xml file?

**Comment by pcanal** [comment]
> Is there a use case where we would want rootcling only behavior and still pass a selection.xml file?

So far I don't see it.  Worst the behavior as-is is very surprising because part of the selection.xml is used (the part selection classes) and the other is ignored.  (I suppose that if this behavior is useful it should be opt-in (eg `--ignore-xml-attibutres-but-keep-the-selection` rather than the default).

**Comment by greenc-FNAL** [comment]
I can confirm that replacing `--genreflex` with `--reflex` resolves my immediate issue. I would be in favor of removing the option in favor of activating the same behavior upon the presence of selection XML, however.
