### ISSUE TITLE
[PyROOT] Iterating over list with ROOT objects messes up memory

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#13611]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Iterating over a Python list containing PyROOT proxies seems to mess up something, causing subsequent crashes when using the elements.

### Reproducer

The problem can be reproduced with some Python code inspired by this forum post, where the problem was originally reported:
https://root-forum.cern.ch/t/memory-leak-in-fits/56249/4

```python
import ROOT as r

x = r.RooRealVar("x", "x", 0, 10)
gm = r.RooRealVar("gm", "gm", 5, 0, 10)
pdf = r.RooGaussian("g", "g", x, gm, r.RooFit.RooConst(1))
data = pdf.generate({x}, 1000)

commands = [
    r.RooFit.PrintLevel(-1),
    r.RooFit.Save(),
]

# Iterating over the python list will break the code. Uncomment it and things
# will work. Say whaat?
for x in commands:
    pass

cmdList = r.RooLinkedList()

for i in range(len(commands)):
    commands[i].Print()
    cmdList.Add(commands[i])

# To get a more direct reproducer, we're not calling the pythonized version of
# fitTo(), but the original cppyy method that is available as _fitTo():
pdf._fitTo(data, cmdList)
```

### ROOT version

`master`

### Installation method

Building from source

### Operating system

Arch Linux

### Additional context

https://root-forum.cern.ch/t/memory-leak-in-fits/56249

**Comment by AlkaidCheng** [comment]
Interestingly, even if you don't pass any commands, it will still crash:

```
import ROOT as r

x = r.RooRealVar("x", "x", 0, 10)
gm = r.RooRealVar("gm", "gm", 5, 0, 10)
pdf = r.RooGaussian("g", "g", x, gm, r.RooFit.RooConst(1))
data = pdf.generate({x}, 1000)

commands = [
    r.RooFit.PrintLevel(-1),
    r.RooFit.Save(),
]

# Iterating over the python list will break the code. Uncomment it and things
# will work. Say whaat?
for x in commands:
    pass

pdf._fitTo(data)
```

**Comment by AlkaidCheng** [comment]
Ok I think I found the reason for the crash, it is because this line
```
for x in commands:
    pass
```
will delete the RooRealVar `x`.

If you replace it by, say,
```
for y in commands:
    pass
```
It will not crash

**Comment by guitargeek** [comment]
Thank you so much! This fell completely under by radar because I'm so used to C++ block scope!

So that's indeed a thing in Python, that the loop has no own scope and the iteration variable is not shadowing, but re-assigning the variable in the current scope:

https://stackoverflow.com/questions/3611760/scoping-in-python-for-loops

Thanks again :D
