### ISSUE TITLE
Different results using SetFillStyle using TCanvas and WebCanvas

### ISSUE THREAD

**Issue by martamaja10** [root-project/root#13678]
<img width="816" alt="Screenshot 2023-09-19 at 17 21 56" src="https://github.com/root-project/root/assets/80402204/cd5cf7e4-6920-4156-9695-f50da9e760d5">
### Check duplicate issues.

- [X] Checked for duplicates

### Description

I have an issue with the SetFillStyle - the result looks quite different for the TCanvas version and the WebCanvas version. In this particular case I'm doing 'SetFillStyle(3244)' and 'SetFillStyle(3254)'. Also, for both cases, while I save the canvas from the web, using the bottom right button, the hatched area becomes completely filled instead of remaining hatched. See the attached comparison. 

### Reproducer

Using SetFillStyle() with or without WebBrowse option

### ROOT version

current master

### Installation method

root from source

### Operating system

MacOS

**Comment by linev** [comment]
@martamaja10 Can you provide macros? Or just save canvas in ROOT file.

**Comment by martamaja10** [comment]
sure, here is the macro (also the python one in case you want to see it too) and the json file you'll need to run it

[df106_tutorial.zip](https://github.com/root-project/root/files/12681637/df106_tutorial.zip)

**Comment by linev** [comment]
Fill patterns will be fixed in #13706
