### ISSUE TITLE
TF1::DrawIntegral

### ISSUE THREAD

**Issue by xkzl** [root-project/root#13708]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

Hello, I have a compiled program that is crashing because of DrawIntegral in a specific context.
This issue is not happening when using interactive c++.

This program is crashing in my case with the following issue:

```
Install the project...
-- Install configuration: "Debug"
-- Installing: /Users/marcomeyer/Software/escalade/bin/pcp
-- Installing: /Users/marcomeyer/Software/escalade/bin/SignalTest

 *** Break *** segmentation violation
[/Users/marcomeyer/Software/root/20230831/lib/libCore.so] TUnixSystem::DispatchSignals(ESignals) /Users/marcomeyer/Software/root/src/core/unix/src/TUnixSystem.cxx:0
[/Users/marcomeyer/Software/root/20230831/lib/libCore.so] SigHandler(ESignals) /Users/marcomeyer/Software/root/src/core/unix/src/TUnixSystem.cxx:403
[/Users/marcomeyer/Software/root/20230831/lib/libCore.so] sighandler(int) /Users/marcomeyer/Software/root/src/core/unix/src/TUnixSystem.cxx:3604
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[/Users/marcomeyer/Software/root/20230831/lib/libCore.so] TVirtualPad::TContext::~TContext() /Users/marcomeyer/Software/root/src/core/base/src/TVirtualPad.cxx:62
[/Users/marcomeyer/Software/root/20230831/lib/libCore.so] TVirtualPad::TContext::~TContext() /Users/marcomeyer/Software/root/src/core/base/src/TVirtualPad.cxx:62
[/Users/marcomeyer/Software/root/20230831/lib/libHist.so] TF1::DrawIntegral(char const*) /Users/marcomeyer/Software/root/src/hist/hist/src/TF1.cxx:1415
[/Users/marcomeyer/Software/escalade/bin/SignalTest] main /Users/marcomeyer/Software/escalade/src/lib/OMU/tests/src/SignalTest.C:17
[/usr/lib/dyld] start (no debug info)
```

### Reproducer

```
[...]

int main() {

    TApplication *app = new TApplication("root", NULL, NULL);

    TCanvas *c = new TCanvas("c4", "", 720, 1024);
    // c->Divide(1, 2);
   
    TF1 *f = new TF1("lin", "x", -10, 10);
    c->cd(1);
    f->Draw();

    c->cd(2);
    f->DrawIntegral();
    
    while(1)
        gSystem->ProcessEvents();

    return 0;
}
```

### ROOT version

ROOT master branch (2023-08-31)

### Installation method

build from source

### Operating system

macos

**Comment by dpiparo** [comment]
Hi, thanks for reporting. Before we consider this a bug, could you add a minimal reproducer?

**Comment by couet** [comment]
I get the crash also with a simple C macro (extracted from your code) executed at the ROOT prompt. Reading the doc it looks like this functionality is meant to be used interactively from the context menu. Which means you need the graphics to be ready on the canvas. Therefore, to make it work in a ROOT script, you will need a few "Update()" to make sure the graphics id ready. Here is the working script:

```
{
   auto *c = new TCanvas("c4", "", 720, 1024);
   c->Divide(1, 2);

   auto f = new TF1("lin", "x", -10, 10);
   c->cd(1);
   f->Draw();
   gPad->Update();

   c->cd(2);
   gPad->Update();
   f->DrawIntegral();
}
```

**Comment by couet** [comment]
Indeed, to be complete, the real functionality you are using is[ this one](https://root.cern/doc/master/classTGraph.html#a6f557cc5d68e7328ef578c2b2d839c8d)

and the macro should be:
```
{
   auto *c = new TCanvas("c4", "", 720, 1024);
   c->Divide(1, 2);

   auto f = new TF1("lin", "x", -10, 10);
   c->cd(1);
   f->Draw();

   c->cd(2);
   auto g = new TGraph(f,"i");
   g->Draw("al");
}
```
DrawIntrgral is really meant to be used ONLY from the context menu.

**Comment by xkzl** [comment]
It would be good to have some warning here or extension of the initial use case.
I am mainly running compiled root in these days..

Is there any specific reasons why it is only meant to be used in interactive ?

**Comment by couet** [comment]
[The way it is implemented](https://root.cern.ch/doc/master/TF1_8cxx_source.html#l01408) makes it mandatory to have an active pad with the TF1 drawn in it. That's why you need to add these `gPad->Update()` if you really want to use this function (see my first example). My second reply does exactly the same thing as DrawIntegral without the `GetSelectedPad()`. That's the simpler/better way when you run compiled ROOT like you.

**Comment by guitargeek** [comment]
Just my 2 cents: the GitHub issues that were not actual issues should maybe be closed as "not planned"
