### ISSUE TITLE
Different PDF output `TCanvas` / `TWebCanvas`

### ISSUE THREAD

**Issue by jblomer** [root-project/root#13707]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Follow-up from #13693. I found a few more inconsistencies in the attached plotting scripts.

1: throughput-formats
  - Different ticks and label frequency in the left side y axis
  - Different error bar width

2: size-overview
  - Difference in `TPaveText` background (flat color vs shadow)
  - Title vs no title (this may be rather a bug in TCanvas because the plotting script does set a title for the upper histogram)
  - Y grid vs no y grid (again, perhaps rather a bug in TCanvas because there are calls to `TPad::SetGridy()`)

3: scaling
  - Different range and ticks/label frequency on x axis

### Reproducer

[03_scaling.zip](https://github.com/root-project/root/files/12704585/03_scaling.zip)
[02_size_overview.zip](https://github.com/root-project/root/files/12704586/02_size_overview.zip)
[01_throughput-formats.zip](https://github.com/root-project/root/files/12704587/01_throughput-formats.zip)

### ROOT version

master

### Installation method

Built from sources

### Operating system

Arch Linux, Chromium set as web GUI

**Comment by linev** [comment]
Generic comments about axis ticks.:

ROOT does not guarantee number of labels for the axis.
And JSROOT uses different algorithm, which can produce different position for the labels.

Like in the first example: ROOT makes 0, 0.2, 0.4, 0.8, 1 (5 divisions).
 JSROOT produced 0, 0.1, 0.2, 0.3, ..., 1 (10 divisions).

By default settings `TAxis` should produce 10 divisions. 

One can change it with `helper->GetYaxis()->SetNdivisions(508)` to get same results on web and plain ROOT.

**Comment by linev** [comment]
With histogram title is more complicated. 
If "AXIS" option is specified - title is not drawn by ROOT. 
Mean it is deviation from the ROOT functionality.
I will fix it in JSROOT.

**Comment by linev** [comment]
About drawing with two axes. 

Web graphics supports drawing of axes on both sides.
Therefore one can simplify drawing just doing:
```
graph->Draw("APL");
graphPerCore->Draw("PLX+Y+");
```

No need for extra transparent pads, no need for axis drawing emulation.
I attach macro and produced output. Also see `graph->GetXaxis()->SetNdivisions(nodes.size());` - as many divisions are required.

[scaling_new.C.txt](https://github.com/root-project/root/files/12724374/scaling_new.C.txt)
[scaling_new.pdf](https://github.com/root-project/root/files/12724375/scaling_new.pdf)

**Comment by linev** [comment]
To finalize:
1. Histogram title should not be drawn with "AXIS" draw option, will be fixed in next PR. One can draw such histogram just with empty draw option to get title drawn.
2. There is grid drawing problem in the ROOT, should be addressed by @couet 
3. Number of axis labels is defined by `TAttAxis::SetNdivisions()` call and may differ between ROOT and web graphics. Although web graphic makes exactly configured number of divisions - when possible.
