### ISSUE TITLE
TF1::SetParName

### ISSUE THREAD

**Issue by xkzl** [root-project/root#13709]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

Hello, I have been trying to play with parameter names with TF1 (and TFormula)

I need to draw a TF1 curve, for simplicity I want to include clear parameter names.
But I see some very strange behaviors.. I play with parameter names and my formula gets completely mess up..
How can this be ?

The output of the reproducer is the following:
My f0 gets modified into t0..
```
root [1] .x test.C
[f0] + [beta]*x
[t0]+[beta]*x <<<<< EXPECTED : "[f0] + [beta]*x"
```

### Reproducer

Here is the reproduced. My example just use f0 and beta, but my program use some other parameters also depending on if/else conditions. 

```
{
	double t0 = 0;
	double t1 = 10;
	
	double f0 = 12.5;
	double f1 = 2;

	double beta = (f1-f0)/t1;

	TString formulaStr = "[f0] + [beta]*x";
    TF1 *formula = new TF1("formula1", formulaStr);
         formula->SetParName  (0, "beta");
         formula->SetParameter(0, beta);
         formula->SetParName  (1, "t0");
         formula->SetParameter(1, t0);
         formula->SetParName  (2, "f0");
         formula->SetParameter(2, f0);
         formula->SetParName  (3, "t1");
         formula->SetParameter(3, t1);
         formula->SetParName  (4, "f1");
         formula->SetParameter(4, f1);

    std::cout << formulaStr << std::endl;
    std::cout << formula->GetFormula()->GetExpFormula() << std::endl;
}
```

### ROOT version

ROOT master 2023/08/31

### Installation method

build from source

### Operating system

macos

**Comment by ferdymercury** [comment]
Your formula has only two parameters (f0 and beta), but you try to name 4 parameters.

Try this instead and name parameters according to the numbers:

`TString formulaStr = "[0] + ([1]-[0])/[2]*x";`

**Comment by xkzl** [comment]
@ferdymercury as I mentioned I have a dynamic implementation involving these 4 parameters, but the string is not matching. This is not the point.

Please consider this example............ if you prefer
```
{
        TString formulaStr = "[f0] + [beta]*x";
        TF1 *formula = new TF1("formula1", formulaStr);
                formula->SetParName  (0, "beta");
                formula->SetParameter(0, 0);
                formula->SetParName  (1, "t0");
                formula->SetParameter(1, 0);

    std::cout << formulaStr << std::endl;
    std::cout << formula->GetFormula()->GetExpFormula() << std::endl;
}
```

**Comment by xkzl** [comment]
Also, I don't see why f0 is turning into t0. 
By extension, it would make much more sense to assign based on name in this case and therefore attribute the attribute value correspondingly.

**Comment by ferdymercury** [comment]
Ok, I got it now.

The point is: parameter names are sorted alphabetically. Not by the order of appearance in the formula.

```
TF1 *formula = new TF1("formula1", "[b]+[a]*x");
root [1] formula->GetParName(0)
(const char *) "a"
root [2] formula->GetParName(1)
(const char *) "b"
```

versus

```
TF1 *formula = new TF1("formula1", "[a]+[b]*x");
root [1] formula->GetParName(0)
(const char *) "a"
root [2] formula->GetParName(1)
(const char *) "b"
```

So in you original formula, beta will be parameter 0, and f0 will be parameter 1. If you change parameter 1 to t0, you will get:
`[t0]+[beta]*x`

**Comment by guitargeek** [comment]
Just my 2 cents: the GitHub issues that were not actual issues should maybe be closed as "not planned"
