### ISSUE TITLE
Different behaviour of new and old graphics

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#13719]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

I apologise in advance since I cannot clearly say whether this is the expected behaviour and my code should be fixed or if the new graphics is not behaving correctly.
The X axis labels are touching the plot with the new graphics while they are not with the old one.

### Reproducer

See attached root file: [timeseries.root.zip](https://github.com/root-project/root/files/12717037/timeseries.root.zip)

### ROOT version

master

### Installation method

build from sources

### Operating system

MacOS

**Comment by linev** [comment]
Problem is not only labels offset itself in the axis. 
It is very small - just 0.005 and therefore labels are very close to axis.
And ROOT adds extra offset to labels that they not touching axis line even when `offset == 0`.
I have to add such extras to web graphic. 

But main problem was significant difference in labels size for X axis.
Only now I found that `TGaxis` scale down labels size by factor 0.66666 - for custom labels.
This was not handled by web canvas. 
Once it is there - position and size of X axis labels will be ok.

**Comment by linev** [comment]
![c1](https://github.com/root-project/root/assets/4936580/f82825fc-15dd-4dfa-8665-78d07d5c94f1)
![Canvas](https://github.com/root-project/root/assets/4936580/5c48bb31-d6e8-4129-a466-377a02955b7a)

Now how canvas looks like
