### ISSUE TITLE
[math] Contour method has some problems with Minuit2

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#13729]
I the [RooFit interactive Minuit tutorial](https://root.cern.ch/doc/master/rf601__intminuit_8C.html), there is this line here:
```c++
   // The contour algorithm in Minuit2 does not work for this tutorial
   m.setMinimizerType("Minuit");
```
The implementation of `CONTOUR` in Minuit2 should be fixed such that this is not necessary.
The problem has something to do with the contours hitting the parameter boundaries.

If one tries to get different contours inside the boundary by changing the `contour()` to for example:
```c++
   RooPlot *frame = m.contour(frac, sigma_g2, 1, 1.4, 1.7);
```
the plot looks still a bit screwed up with out-of-place lines:

![rf601-crop](https://github.com/root-project/root/assets/6578603/33ef2fa5-08d1-458f-a169-63c2c28298ba)

Also this problem should be fixed.

**Comment by dpiparo** [comment]
@guitargeek @lmoneta just checking: can this be closed?

**Comment by dpiparo** [comment]
Closing as per discussion with @lmoneta

**Comment by guitargeek** [comment]
Nice. I also checked if the reproducer works now, and it's working fine.
