### ISSUE TITLE
[PyROOT] Can't trivially `gSystem.Load()` libraries compiled with ACLiC on macOS 14

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#13734]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

On macOS 14, if you compile a library with ACLiC, it is not possible to load it in PyROOT with `gSystem.Load()` without loading `libRint` before.

### Reproducer

```sh
# Creating a dummy library
echo "void foo() {}" > foo.C
root -l -b -q -e ".L foo.C+"

# With the ROOT interpreter, everything goes fine
root -l -b -q -e 'std::cout << gSystem->Load("foo_C") << std::endl;'

# Let's see with a compiled script
echo '#include <TSystem.h>
#include <iostream>
int main() { std::cout << gSystem->Load("foo_C") << std::endl; }' > main.cpp

g++ main.cpp $(root-config --cflags) -I $(root-config --incdir) -L $(root-config --libdir) -lCore -o main
./main


# But with PyROOT, it doesn't work on macos 14 beta
python3 -c 'import ROOT; print(ROOT.gSystem.Load("foo_C"))'

# With loading Rint before, it works!
python3 -c 'import ROOT; ROOT.gSystem.Load("libRint"); print(ROOT.gSystem.Load("foo_C"))'

```
The Python version without loading libRint first is failing on macos 14 beta with the following error message:
```txt
cling::DynamicLibraryManager::loadLibrary(): dlopen(/Users/sftnight/build/jenkins/night/LABEL/macbeta/SPEC/cxx20/V/master/build/roottest/python/pythonizations/foo_C.so, 0x0009): Library not loaded: @rpath/libRint.so
  Referenced from: <3831F8AB-C7D6-3522-AF78-6E908F97B77A> /Users/sftnight/build/jenkins/night/LABEL/macbeta/SPEC/cxx20/V/master/build/roottest/python/pythonizations/foo_C.so
  Reason: no LC_RPATH's found
-1
```

### ROOT version

ROOT `master`

### Installation method

build from source

### Operating system

macOS 14 (beta)

### Additional context

This problem makes several tests in the `macbeta` nighlies fail:
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=macbeta,SPEC=cxx20,V=master/lastBuild/#showFailuresLink

**Comment by dpiparo** [comment]
For some reason, the library needs to have the RPath also pointing to $ROOTSYS/lib. For example, if one patches the binary after linking with 
```
install_name_tool foo_C.so -add_rpath $ROOTSYS/lib
```
then, the command work w/o loading libRint by hand, i.e. the link to the lib is honoured (thanks to @vepadulano for the debugging session that led to this post!)

**Comment by pcanal** [comment]
So the equivalent to this `-add_rpath` is likely missing from the `ACLiC` command line.

In the original setup are `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` properly set?
