### ISSUE TITLE
[web canvas] No legend when running Python interactive session 

### ISSUE THREAD

**Issue by martamaja10** [root-project/root#13816]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When running a python macro with "python -i df106_HiggsToFourLeptons.py", the legend does not appear on web canvas. 
![Screenshot 2023-10-05 at 17 11 28](https://github.com/root-project/root/assets/80402204/411a96dc-e713-41a7-ab94-75c4bc5d5441)

### Reproducer

I'm attaching the macro and the spec file needed to run it. 

[reproducer.zip](https://github.com/root-project/root/files/12829592/reproducer.zip)

### ROOT version

current master 

### Installation method

source

### Operating system

macOS/all

**Comment by linev** [comment]
Thanks. It is really not updated. I will provide PR soon.

**Comment by linev** [comment]
https://github.com/root-project/root/pull/13817 will fix the problem.

Actually, it is missing `c1.Update()` at the end of such macro.

**Comment by martamaja10** [comment]
I see, ok, thanks!
