### ISSUE TITLE
builtin libpng too old

### ISSUE THREAD

**Issue by unelg** [root-project/root#13825]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

the libpng included in latest root/afterimage is 1.2.55 . The modern version is 1.6.40. This causes problems at run time:
libpng warning: Application was compiled with png.h from libpng-1.6.39
libpng warning: Application  is  running with png.c from libpng-1.2.55
libpng error: Incompatible libpng version in application and library

### Reproducer

I dont think a reproduced is needed.

### ROOT version

  | From tags/v6-28-06@v6-28-06                                      |

### Installation method

brew

### Operating system

macos

**Comment by couet** [comment]
When I install ROOT on macOS from sources the png library is found in:
```
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.40") 
```
And it works fine with ROOT.

**Comment by ferdymercury** [comment]
@couet I think he refers to the built-in libpng, not to the system-wide one. (i.e. when you turn on the builtin option)

See https://github.com/root-project/root/tree/master/graf2d/asimage/src/libAfterImage/libpng

**Comment by ferdymercury** [comment]
See also https://github.com/root-project/root/commit/3859b3efe198c444a1c4900f0f8cde6e0b1e34ab

**Comment by couet** [comment]
PR here: https://github.com/root-project/root/pull/13860

**Comment by unelg** [comment]
No. I dont think the problem is understood.

In my software I link with another library compiled with the system libraries which have a recent libpng.
At run time ROOT finds the old ones from libpng inside imagemagic.

It is not too hard to update the lib png. Do you want me to write what I do?

G.

**Comment by Axel-Naumann** [comment]
Hi @unelg - you missed my point, I'm trying to help you with your software stack. Even if we update libpng you still have a problem because you are mixing multiple libpng versions. Up to you :-) But please at https://root-forum.cern.ch/
