### ISSUE TITLE
Remove all traces of Python2 from the ROOT codebase in preparation for 6.32/00

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#13861]
### Explain what you would like to see improved and how.

Python2 is not supported since a while, and supporting in ROOT both Python2 and Python3, despite easing greatly the transition of users and experiments, incremented the maintenance cost of the codebase. 

All traces of Python2 should be removed from the ROOT codebase and all the simplifications deriving from this removal should be put in place.

### ROOT version

v6.32/00

### Installation method

All

### Operating system

All

**Comment by guitargeek** [comment]
One Python 2 specific code can be found in the CMake file of the Pythonizations
https://github.com/root-project/root/blob/master/bindings/pyroot/pythonizations/CMakeLists.txt

**Comment by pitkajuh** [comment]
FYI, I am working on this problem (please, see for example 73219de13ce63dbfc294353cd3d88c9abb3ec2de). As far as I can tell, there are a lot of files that need to be changed (at least Python, CMake and C). So far the changes have been mostly if and else statements which take into account, that the user might try to compile with either Python2 or Python3.

**Comment by vepadulano** [comment]
I believe we have removed all references of Python 2 in ROOT code we have direct control over. There are some leftover traces in `interpreter` and in `pyroot/cppyy` but I think there's no point in changing those
