### ISSUE TITLE
Root CMake configuration should check against C++ standard and compiler version

### ISSUE THREAD

**Issue by jade2k11598** [root-project/root#13886]
### Explain what you would like to see improved and how.

Root's CMake configuration should set requirements on the C++ standard and compiler used for the given branch. 

### ROOT version

On Ubuntu Linux, having git clone the root repository, and initially checked out (to the latest stable branch which was) `v6-28-06`, which didn't succeed to build (despite the configuration passing) when setting the C++ standard to C++20 and compiler gcc/g++ version 9.4.0.

### Installation method

build from source

### Operating system

Linux Ubuntu 20.04

### Additional context

I initially attempted to build from root branch `v6-28-06`, using compiler g++ 9.4.0, setting to the C++ standard to C++20.  CMake configuration was successful, [but errors occurred during compilation that wasn't obvious](https://root-forum.cern.ch/t/building-root-with-standard-set-to-c-20-results-in-compilation-errors-on-linux/56715/6?u=jade2).  It was then pointed out to me that[ I had the wrong branch that supports C++20 and the wrong compiler version](https://root-forum.cern.ch/t/building-root-with-standard-set-to-c-20-results-in-compilation-errors-on-linux/56715/7?u=jade2).

**Comment by guitargeek** [comment]
This is actually implemented now:
https://github.com/vepadulano/root/blob/518893cd5e3aef5d9992d5ad588c0ec3c2672896/cmake/modules/CheckCompiler.cmake#L172
