### ISSUE TITLE
Implementation of Clear command in place of .!cls

### ISSUE THREAD

**Issue by JRS296** [root-project/root#13958]
### Explain what you would like to see improved and how.

Hello there. I am a college senior and am interested in improving my C++ open source development, and would like to work on CERN's ROOT repo. I have noticed that there is no explicit 'clear' command for ROOT's CLI. It utilizes the .!cls command. 

I would like to know if I could implement the same to get me started here. @Axel-Naumann @couet . I would like to know if my proposed idea can be implemented, and would like the maintainer's thoughts on the same. Thanks once again.

### ROOT version

latest docker image

### Installation method

docker

### Operating system

Windows

### Additional context

- I would like to know if one would suggest that I build out ROOT in a linux environment, or in a windows environment.
- Would need some help in locating the CLI file within the repo.

**Comment by Axel-Naumann** [comment]
Thanks @JRS296 ! I'm not sure we need / want this, tbh: it's a really system specific implementation and it will have to be in a library that I'd like to replace anyway. And creating a test for it will be non-trivial :-) So I'd actually prefer to still with whatever the shell provides. Makes sense?

But yes *please* contribute! You could start with imlpementing
```c++
static std::unique_ptr<TFile> OpenU(const char *name, Option_t *option = "",
                            const char *ftitle = "", Int_t compress = ROOT::RCompressionSetting::EDefaults::kUseCompiledDefault,
                            Int_t netopt = 0);
```
internally calling `TFile::Open` but returning a `unique_ptr`. The name is subject to discussion but we want this interface in any case. This would allow you to exercise the contribution procedure! I'd recommend a Linux docker container for improved build speed.

**Comment by JRS296** [comment]
Cool, thanks a ton! Will get started 👍

**Comment by Axel-Naumann** [comment]
Why don't you join us at https://mattermost.web.cern.ch/root/channels/root-io to discuss - that seems more interactive than this GH issue :-) Thanks for your flexibility!

**Comment by Axel-Naumann** [comment]
Why don't you join us at https://mattermost.web.cern.ch/root/channels/root-io to discuss - that seems more interactive than this GH issue :-) Let me know if this doesn't work for you and I'll create a new issue where we can discuss this new interface.

Thanks for your flexibility!
