### ISSUE TITLE
`THnSparse::Scale()` unsparsifies

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#13962]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

`Scale()` scales all bins, even "non-existing" (i.e. sparse-skipped) ones. See https://root-forum.cern.ch/t/hadd-error-thnsparse/56444

### Reproducer

`h->Scale()` will do

### ROOT version

master

### Installation method

From source

### Operating system

Linux

**Comment by ferdymercury** [comment]
PR here: https://github.com/root-project/root/pull/15066
