### ISSUE TITLE
Allow zero-copy RNTuple bulk reading

### ISSUE THREAD

**Issue by ktf** [root-project/root#14030]
### Explain what you would like to see improved and how.

As discussed in the workshop, our (ALICE) number one request for RNTuple would be to have a way to avoid the currently needed copy when doing bulk reads.

During the meeting passing the allocator or some byte range was suggested as a possible solution, which I think would be doable on our side. We are open to any other solution which allows us to achieve writing directly in shared memory.

### ROOT version

master

### Installation method

aliBuild

### Operating system

any

**Comment by jblomer** [comment]
Fixed by #14649
