### ISSUE TITLE
`TPaveText` has problems when label is set

### ISSUE THREAD

**Issue by linev** [root-project/root#14032]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

After `TPaveText::SetLabel()` is called, drawing of such pave is corrupted.

First of all - label is not drawn.

If one tries move title after label is set for it, either part or complete canvas is white.

Also getting lot of failures like:
```
Error in <TTF::SetTextSize>: error in FT_Set_Char_Size
Error in <TTF::SetTextSize>: error in FT_Set_Char_Size
Error in <TTF::SetTextSize>: error in FT_Set_Char_Size
Error in <TTF::SetTextSize>: error in FT_Set_Char_Size
Error in <TTF::SetTextSize>: error in FT_Set_Char_Size
Error in <TTF::SetTextSize>: error in FT_Set_Char_Size
Error in <TTF::SetTextSize>: error in FT_Set_Char_Size
Error in <TTF::SetTextSize>: error in FT_Set_Char_Size
```

### Reproducer

Attached is reproducer. 
[hstack.C.txt](https://github.com/root-project/root/files/13294534/hstack.C.txt)

And this is how canvas look when try to move title:

![cst](https://github.com/root-project/root/assets/4936580/334dfe25-4cb7-41cc-b51e-491135db142a)

### ROOT version

master

### Installation method

build from source

### Operating system

OpenSUSE Linux

**Comment by couet** [comment]
For me, the title does not change but it does not crash. No error messages.

**Comment by linev** [comment]
It is not crash as well for me.  But if I try to move title using my mouse - I get corrupted drawing (as on screenshot) and
lot of error messages.

**Comment by couet** [comment]
I get nothing special when I move the title ... it moves nicely

**Comment by couet** [comment]
I cannot reproduce
