### ISSUE TITLE
[web graphics] Web graphics resizes canvas despite canvas size definition in the macro

### ISSUE THREAD

**Issue by martamaja10** [root-project/root#14051]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

When running the tutorials via "old" graphics, the set canvas size is correctly saved, but once the same macro is executed via the web graphics, the size is changed - it should be a square of 600x600 and it is a rectangle instead. (A few weeks ago this problem was resolved but it is back). 

![Screenshot 2023-11-14 at 13 28 59](https://github.com/root-project/root/assets/80402204/03fa92eb-06b7-4b2c-a506-b41bc2ace4f8)

### Reproducer

Higgs to 4 leptons tutorial (cpp or python versions) from the current master: 

https://github.com/root-project/root/blob/master/tutorials/dataframe/df106_HiggsToFourLeptons.C 

### ROOT version

current master

### Installation method

source

### Operating system

macOS

**Comment by linev** [comment]
How you start ROOT? 
Only with chrome browser which explicitly specified at start time one have possibility to set/change canvas dimensions.
If I start:
```
root --web=chrome tutorials/dataframe/df106_HiggsToFourLeptons.C 
```
I get drawing of 600x560 pixels. 

With normal ROOT graphics one get image 598x575 pixels.

**Comment by martamaja10** [comment]
ok, with chrome it works fine. My default browser is set to safari and then the mentioned issue appears (which wasn't there a few weeks ago). It is not a big issue then I guess, but do we then specify that the default web should be set to chrome? (sorry if it is very explicitly said somewhere and I missed it).

**Comment by linev** [comment]
There are pro and cons using chrome by default.

Main problem - is startup time when chrome not configured as default browser. In some situation it can takes ~30 sec.

But from functionality point of view - chrome is best possible choice.

**Comment by martamaja10** [comment]
sure, but I am now thinking of the user's perspective, if someone's default browser is "safari" and they are not aware that chrome, and hence always running "root --web=chrome" instead of just "root", provides the best functionality, they would also run into some issues like I did. I'm just thinking of how to communicate this well so that user issues are avoided (and I don't think this is explained anywhere yet, unless I am wrong, but then where is it explained?) 

I now also tried doing the same but with firefox and I also run into issues 

![Screenshot 2023-11-14 at 14 20 05](https://github.com/root-project/root/assets/80402204/02710082-1104-4cf4-9a08-1aec4575aa21)
<img width="1275" alt="Screenshot 2023-11-14 at 14 20 15" src="https://github.com/root-project/root/assets/80402204/7b55511e-ed78-4321-b279-7abd2d278f3d">

**Comment by linev** [comment]
Yes, up to now Firefox in ROOT not able to start with requested window size.
I trying right now to improve this.

**Comment by linev** [comment]
Marta, can you try https://github.com/root-project/root/pull/14054 in your environment?

It should improve a lot firefox behavior.

**Comment by vepadulano** [comment]
I believe the real issue here is about user experience. Suppose I'm a mac user, I only use safari and don't even have chrome installed. I have been using ROOT for 10+ years, I want to see my plot in a canvas. Now the default canvas is the web canvas, so it will go through the only browser it can find on my machine, safari. That breaks functionality w.r.t. how I was using the canvas before. So, that's something we want to fix, right?

In general, I would imagine that at the very least for the three most commonly used browsers i.e. Chrome, Safari, Firefox (Edge even?) we should be able to provide exactly the same functionality to users. Writing in the documentation that they need to install google chrome on their machine in order to have a properly working canvas is not an option in my opinion. Practically, that would imply that ROOT has a dependency on Chrome and I don't think that's what we want

**Comment by dpiparo** [comment]
@martamaja10 @linev is this issue fixed?

**Comment by martamaja10** [comment]
Hi, I have just re-run the df106 tutorial with 6.32. Both the interactive canvases and the saved ones with and without the web graphics look quite different

<img width="1146" alt="Screenshot 2024-06-03 at 13 57 58" src="https://github.com/root-project/root/assets/80402204/f8218023-ff61-4231-9dcb-b1b798e0e3d9">
<img width="1223" alt="Screenshot 2024-06-03 at 13 59 27" src="https://github.com/root-project/root/assets/80402204/85ad72f8-769d-458a-8141-4b1bcbb69385">

**Comment by martamaja10** [comment]
top figure is `root --web=chrome df106_HiggsToFourLeptons.C` and the bottom is: `root --web=chrome df106_HiggsToFourLeptons.C`

**Comment by linev** [comment]
Yes, I saw this difference. And trying to fix it. But it is new bug introduced recently and not concerning canvas size

**Comment by martamaja10** [comment]
ok, yes, the canvas size works fine now, so we can close this issue if the other problem is tracked elsewhere

**Comment by linev** [comment]
PR #15718 fixing problem with empty title

And Y axis range selection I investigating right now

**Comment by martamaja10** [comment]
As per original issue - the canvas size, this has been fixed. I will close the issue and we can follow up with the other problems in the other threads.

**Comment by linev** [comment]
#15718 and #15747 fixes issues with THStack drawing and zooming. 

Now canvas looks like:

![Canvas](https://github.com/root-project/root/assets/4936580/fa73962c-026e-4105-b445-10f05496b59e)

Small area below 0 due to issue #15740 and will be resolved/synced with ROOT changes later
