### ISSUE TITLE
ROOT 6.30/00 reports `root-config --version` as 6.30.00

### ISSUE THREAD

**Issue by olifre** [root-project/root#14068]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Compare the following output:
```
$ root   
   ------------------------------------------------------------------
  | Welcome to ROOT 6.26/04                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jun 07 2022, 16:01:16                 |
  | From tags/v6-26-04@v6-26-04                                      |
  | With g++ (GCC) 11.2.0                                            |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------

root [0] .q
$ root-config --version
6.26/04
```
Versions in the banner and returned by `root-config --version` match, but with 6.30/00 I get the following:
```
$ root                 
   ------------------------------------------------------------------
  | Welcome to ROOT 6.30/00                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Nov 14 2023, 23:16:19                 |
  | From heads/v6-30-patches@tags/v6-30-00                           |
  | With                                                             |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] .q
$ root-config --version
6.30.00
```
i.e. the versions do not match (note the second dot in the output from `root-config --version`). Since some old build macros of tools relying on ROOT tend to use `root-config`, this may break tooling (at least I have some legacy tooling which was broken :wink: ). 

### Reproducer

Run `root-config --version` and compare it to the banner. 

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.30/00                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Nov 14 2023, 23:16:19                 |
  | From heads/v6-30-patches@tags/v6-30-00                           |
  | With                                                             |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

Gentoo (Portage)

### Operating system

Gentoo Linux

### Additional context

Of course, switching to the two dot notation would be perfectly fine, but since banner and `root-config` output do not match, this is likely not intended and there might be a bug lurking somewhere.

**Comment by olifre** [comment]
Pinging @amadio in case this is specific to the early packaging of 6.30.00 on Gentoo (but I believe it is not, without looking to deeply, though).

**Comment by amadio** [comment]
Nothing Gentoo-specific as far as I can tell (the ebuilds are exactly the same). I think this has been changed on the ROOT side recently, but that's just my guess from reading stuff in Mattermost.

**Comment by olifre** [comment]
@amadio Thanks!

I have delved a bit into the recent changed, and I think it's this one:
https://github.com/root-project/root/commit/f45f2c283752de0a3a2fdc278b00d1653e116833
`ROOT_VERSION` appears to use the double-dot notiation, while most other user-exposed places (web page release announcements, banner etc.) use the other notiation. 
For example, the banner / logo uses `ROOT_RELEASE`, which still has the dot-slash notation:
https://github.com/root-project/root/blob/18b789c7ca051f09d84471fc948b410b61670f6e/core/base/src/TROOT.cxx#L699C23-L699C35

So probably, the main question is: Which notation is correct / should be used, and in case it's the double-dot notation, should `root-config` stay backwards-compatible? 

In case the actual change linked above was not intended, but was just about dropping the `sed` (which is a good thing to do! :+1: ), maybe defining a CMake variable using the dot-slash notation in https://github.com/root-project/root/blob/18b789c7ca051f09d84471fc948b410b61670f6e/cmake/modules/SetROOTVersion.cmake
and using it in `root-config` would be best.

**Comment by amadio** [comment]
For the record, here is the equivalent module I wrote for XRootD
https://github.com/xrootd/xrootd/blob/master/cmake/XRootDVersion.cmake

**Comment by ferdymercury** [comment]
Also, it seems that the compiler name is missing in the 6.30 variant. "With g++" is missing.

**Comment by wdconinc** [comment]
This breaks some downstream tools, e.g. the MC event generator sartre fails to parse the new version due to a hardcoded assumption in their bundled [FindROOT.cmake](https://phab.hepforge.org/source/sartresvn/browse/trunk/cmake/modules/FindROOT.cmake$70):
```
     51    COMPILER = GNU
     52    -- GSL using gsl-config /opt/software/linux-ubuntu23.10-skylake/gcc-13.2.0/gsl-2.7.1-r7c4v3f2nofy2brvoswxabdvracnocly/bin/gsl-config
     53    -- Using GSL from /opt/software/linux-ubuntu23.10-skylake/gcc-13.2.0/gsl-2.7.1-r7c4v3f2nofy2brvoswxabdvracnocly
     54    -- Looking for Root...
     55    -- Looking for Root... - found /opt/software/linux-ubuntu23.10-skylake/gcc-13.2.0/root-6.30.00-blmbnjbpk53omyunsd6mzd464sffkqc3/bin/root
     56    -- Looking for Root... - version 6.30.00
  >> 57    CMake Error at cmake/modules/FindROOT.cmake:80 (MATH):
     58      MATH cannot parse the expression: "6.30.00*10000 + 6.30.00*100 + 6.30.00":
     59      syntax error, unexpected exp_NUMBER, expecting end of file (5).
     60    Call Stack (most recent call first):
     61      src/CMakeLists.txt:57 (find_package)
```
I wouldn't be surprised if other tools have implicitly assumed that the version number separators were going to be stable.

**Comment by Axel-Naumann** [comment]
We'd like to move to semantic versioning - really the main missing part is replacing that `/` by `.`. Would it be acceptable to follow this change for v6.30 and up?

**Comment by olifre** [comment]
> Would it be acceptable to follow this change for v6.30 and up?

From my point of view, that's perfectly fine (and I'm welcoming this change!) — in the long run, that will also get rid of things like:
https://github.com/Homebrew/homebrew-core/blob/45a7698ed083556248e6c813436719f507f80a5e/Formula/r/root.rb#L13
and likely many other such constructions :wink:. 

Of course, it will need changes in the downstream tools which already showed up here (and likely more), and ideally, the change would be carried through all places in ROOT (i.e. the banner / logo, the website at https://root.cern/install/all_releases/ etc.), but that will probably take some iterations to catch everyting. 

To increase visibility, I guess a warning / announcement in the release notes would be sufficient — `root-config` and the website (which is parsed by some package management tooling, as shown above) are the changes which are most likely to cause breakage in tools which are not prepared for the change.

**Comment by dpiparo** [comment]
Sorry for resuming the discussion only now. I think it's big time to improve along the lines highlighted by @amadio and @olifre . I also think that semantic versioning is the most appropriate convention. However, ROOT still exhibits inconsistencies: the banner uses the "/", `TROOT::GetVersion()` as well, while `root-config --version` does not (as previously observed). 

Can we agree that this item could be closed once ROOT reports consistently its version with the same convention, i.e. Major.Minor.Patch?

**Comment by olifre** [comment]
Sure, I fully agree, both that this is the way to go and that it would be best to close this issue once all locations are consistent :+1: .
