### ISSUE TITLE
TTree Scan function on windows platform, using vscode to connect wsl connection jupyter reported a deadlock.

### ISSUE THREAD

**Issue by Esword618** [root-project/root#14076]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

On windows, when vscode is used to connect pyroot's jupyter of wsl subsystem, pyroot's TTree Sacn function is stuck. Other jupyter lab in wsl do not have this situation. Why is this, is there any solution?
Note that vscode is used to connect to jupyter lab in wsl.

### Reproducer

```
from ctypes import c_double, c_int
from ROOT import TFile, TTree,TCanvas
guan = TFile("guan.root", "recreate")

ming = TTree("ming", "This is my first tree")
i = c_int(1)
a = c_double(2.2)
b = c_double(0.0)

ming.Branch("i", i, "i/I")
ming.Branch("a", a, "a/D")
ming.Branch("b", a, "b/D")

for j in range(100):
    i = j
    a = i * 0.1
    b = a * a * 9
    ming.Fill()
    
ming.Write()
# BUG
ming.Scan()
```

### ROOT version

root_v6.30.01.Linux-ubuntu22-x86_64-gcc11.4

### Installation method

build

### Operating system

wls and ubuntu22.04

**Comment by guitargeek** [comment]
Hi! What happens when you do `Write()` at the end, and not before `Scan()`? Usually the write should happen only after interacting with the object, so maybe that's worth to try out. Otherwise I have no idea.

**Comment by Esword618** [comment]
The "write" function is normal, and the "scan" function is abnormal.

**Comment by guitargeek** [comment]
Yes I understand that, but is the `Scan()` still abnormal if you don't do the `Write()` before?

**Comment by Esword618** [comment]
The same is true when I read a root file, which is independent of the "Write" function.

**Comment by guitargeek** [comment]
Ok, then I think we can't help you without a reproducer. The only Windows user I know in the ROOT team is @bellenot, so I assigned the PR to him.

**Comment by bellenot** [comment]
> On windows, when vscode is used to connect pyroot's jupyter of wsl subsystem

Can you describe exactly how you connect from VS Code to PyRoot's Jupyter in WSL?

**Comment by Esword618** [comment]
My data volume is relatively large, and the one-time output of the Scan function is limited. I guess this is the reason. This uses jupyter lab for code editing in the browser, and using the Scan function is not a problem. Mainly in vscode, I use vscode to connect to the local wsl subsystem and use vscode's jupyter editor. Will this know the reason for the jupyter in vscode itself?

**Comment by bellenot** [comment]
> Mainly in vscode, I use vscode to connect to the local wsl subsystem and use vscode's jupyter editor.

Same here.


> Will this know the reason for the jupyter in vscode itself?

What do you mean? I tried your example and it works just fine...

**Comment by Esword618** [comment]
okk,thanks.

**Comment by bellenot** [comment]
OK, then I close this issue
