### ISSUE TITLE
Lazy multithread RDataFrame::Snapshot cause unnessary warning and break gDirectory

### ISSUE THREAD

**Issue by karuboniru** [root-project/root#14132]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

I am getting some `Warning in <Snapshot>: A lazy Snapshot action was booked but never triggered.` warning at the end of the program while found that all output files I expected to be present are present. What make things worse is that snapshot operation in this case can cause `TH1D::SaveAs` to stop working.

I did some test regarding the issue and found following minimal reproduce.

### Reproducer

Create `toy.cpp` with content:
```cpp
#include <ROOT/RDataFrame.hxx>
#include <TRandom.h>

void toy() {
  // comment this line out (i.e. single thread) won't reproduce the problem.
  ROOT::EnableImplicitMT();
  ROOT::RDataFrame emptydf{10000};
  auto df = emptydf.Define("x", []() { return gRandom->Gaus(); }, {});
  ROOT::RDF::RSnapshotOptions opts;
  opts.fLazy = true;
  auto act = df.Snapshot("treeout", "test3.root", "", opts);
  // this should triggr the snapshot
  *act;
  return;
}

int main() {
  toy();
  return 0;
}
```
Run it by `rool -l toy.cpp` or compile and run by `c++ toy.cpp -o t $(root-config --cflags --glibs)  && ./t`

Result: `Warning in <Snapshot>: A lazy Snapshot action was booked but never triggered.` warning is given but `test3.root` is present.

---

Create `toy.cpp` with content:
```cpp
#include <ROOT/RDataFrame.hxx>
#include <TRandom.h>

void toy() {
  // comment this line out (i.e. single thread) won't reproduce the problem.
  ROOT::EnableImplicitMT();
  ROOT::RDataFrame emptydf{10000};
  auto df = emptydf.Define("x", []() { return gRandom->Gaus(); }, {});
  ROOT::RDF::RSnapshotOptions opts;
  opts.fLazy = true;
  auto act = df.Snapshot("treeout", "test3.root", "", opts);
  // create a histogram and trigger the event loop
  df.Histo1D("x")->SaveAs("hist.root");
  return;
}

int main() {
  toy();
  return 0;
}
```
Run it by `rool -l toy.cpp` or compile and run by `c++ toy.cpp -o t $(root-config --cflags --glibs)  && ./t`

Result: `Warning in <Snapshot>: A lazy Snapshot action was booked but never triggered.` warning is given, `test3.root` is present.

But `hist.root` that should come from `TH1D::SaveAs` is missing. 

GDB suggest that control flow have reached `TObject::SaveAs`, I have no idea how to dig into the issue, but it looks to me as if 
https://github.com/root-project/root/blob/d245ee7889eb1ef1c30622356757a2731108abdc/core/base/src/TObject.cxx#L690
is skipped due to `gDirectory` being casted to `false` as `TDirectory::GetSharedLocalCurrentDirectory().get()._M_b._M_p` is `nullptr` in this case.

### ROOT version

Reproduced on 
```
ROOT Version: 6.28/08
Built for linuxx8664gcc on Oct 13 2023, 09:48:14
From tags/v6-28-08@v6-28-08
```
and
```
ROOT Version: 6.30/00
Built for linuxx8664gcc on Nov 26 2023, 23:25:40
From heads/v6-30-patches@tags/v6-30-00
```

### Installation method

6.28/08 from Fedora 39, self-compiled 6.30/00

### Operating system

Fedora release 39 (Thirty Nine)

**Comment by dpiparo** [comment]
Thanks for this report. I can reproduce. There is something to be figured out here.
The warning is triggered here https://github.com/root-project/root/blob/e46ffe837faf9a817144982d3b44bbe88830257d/tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx#L1702 . 
The condition
```
std::all_of(fOutputFiles.begin(), fOutputFiles.end(), [](const auto &f) { return !f; })
```
Is always true if `Finalize` is called before: fOutputFiles is always empty: https://github.com/root-project/root/blob/e46ffe837faf9a817144982d3b44bbe88830257d/tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx#L1817 .

**Comment by fnechans** [comment]
Was this followed up on? It's not a critical issue but the extra warnings are still annoying.

**Comment by dpiparo** [comment]
> Was this followed up on? It's not a critical issue but the extra warnings are still annoying.

I agree, and this is followed up in this PR, being tested now: https://github.com/root-project/root/pull/16550
