### ISSUE TITLE
Minuit2 standalone build: StandAlone.cmake looks for the wrong path for VERSION_FILE

### ISSUE THREAD

**Issue by badshah400** [root-project/root#14157]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When building minuit2 standalone with root 6.30/02 (`-Dminuit2_standalone=ON`), cmake errors out because it is unable to find the `RVersion.hxx` file. It tries to look for `core/foundation/inc/ROOT/RVersion.hxx` but of course that directory does not exist inside `math/minuit2` and the version file has been copied by `copy_standalone()` to the top-level dir (i.e. in `math/minuit2`) itself. As a results, cmake  does not find the version file and aborts. This is fixed by the following modification to `StandAlone.cmake`, whereupon the configuration and build proceeds without any error.

```patch
Index: root-6.30.02/math/minuit2/StandAlone.cmake
===================================================================
--- root-6.30.02.orig/math/minuit2/StandAlone.cmake
+++ root-6.30.02/math/minuit2/StandAlone.cmake
@@ -40,8 +40,8 @@ endfunction()
 include(copy_standalone.cmake)

 # Copy these files in if needed
-copy_standalone(SOURCE ../.. DESTINATION . OUTPUT VERSION_FILE
-                FILES core/foundation/inc/ROOT/RVersion.hxx)
+copy_standalone(SOURCE ../../core/foundation/inc/ROOT DESTINATION . OUTPUT VERSION_FILE
+                FILES RVersion.hxx)

 copy_standalone(SOURCE ../.. DESTINATION .
                 FILES LGPL2_1.txt)
```

Please let me know if this is the right fix. Thanks in advance.

### Reproducer

Running `cmake -Dminuit2_standalone:BOOL=ON` should be enough to bring up the issue.

### ROOT version

6.30/02

### Installation method

Build from source

### Operating system

Linux openSUSE Tumbleweed

### Additional context

Found when building RPMs for distro.

**Comment by guitargeek** [comment]
Thank you very much for the report! Since you already know the fix, can you please open a PR with this change?

Cheers!

**Comment by badshah400** [comment]
@guitargeek Done.
