### ISSUE TITLE
ROOT 6.30.X fails to configure due to missing `llvm.spec.in`

### ISSUE THREAD

**Issue by paulgessinger** [root-project/root#14169]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Building ROOT on macOS 14 with Xcode 15 fails to configure when trying to build LLVM with the following error:

```
CMake Error: File /Users/pagessin/dev/ci-dependencies/build_all_cpp20_15p0/root/src/root/interpreter/llvm/src/llvm.spec.in does not exist
```

### Reproducer

- Checkout ROOT
- Run cmake

### ROOT version

6.30.0 and 6.30.02

### Installation method

build from source

### Operating system

macOS 14 / Xcode 15

**Comment by hahnjo** [comment]
@paulgessinger this looks correct, `interpreter/llvm/` doesn't exist anymore (it moved to `interpreter/llvm-project/`). Is this an incremental build by any chance? If so, either please create a clean build directory, or take a look at https://mattermost.web.cern.ch/root/pl/za3ii4zi9pgi7cdokyqra8m4aa
