### ISSUE TITLE
cmake find_package ROOT broken with 6.30, nlohmann and vdt are builtin but not found

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#14163]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

CMake find_package(ROOT) worked well with 6.28.

Now it fails with 6.30 on Ubuntu 22.04 with the binary release.

First error was related to not finding the builtin nlohmann even if it's there.

```
CMake Error at /usr/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findnlohmann_json.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "nlohmann_json", but CMake did not find one.

  Could not find a package configuration file provided by "nlohmann_json"
  (requested version 3.10.5) with any of the following names:

    nlohmann_jsonConfig.cmake
    nlohmann_json-config.cmake

  Add the installation prefix of "nlohmann_json" to CMAKE_PREFIX_PATH or set
  "nlohmann_json_DIR" to a directory containing one of the above files.  If
  "nlohmann_json" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /tmp/newroot/cmake/ROOTConfig.cmake:122 (find_dependency)
  gui/CMakeLists.txt:28 (find_package)
```

A hack workaround is using sudo apt install nlohmann-json3-dev

Next error is:

```
cmake ../testroot/
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found nlohmann_json: /usr/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found suitable version "3.10.5", minimum required is "3.10.5") 
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Vdt (missing: VDT_INCLUDE_DIR VDT_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/root/cmake/modules/FindVdt.cmake:63 (find_package_handle_standard_args)
  /usr/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/root/cmake/ROOTConfig.cmake:132 (find_dependency)
  CMakeLists.txt:5 (find_package)
```

And not sure how to solve it.

### Reproducer

```
cmake_minimum_required(VERSION 3.25)

project(ProjectName)

find_package(ROOT 6.30 CONFIG REQUIRED)
```

### ROOT version

 ```
  ------------------------------------------------------------------
  | Welcome to ROOT 6.30/02                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Nov 27 2023, 19:50:38                 |
  | From tags/v6-30-02@                                              |
  | With c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0                   |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

Binary Release

### Operating system

Ubuntu 22.04

**Comment by ferdymercury** [comment]
See https://github.com/root-project/root/commit/b3644785104bfbc3c975e7680a7aa8077d197115

**Comment by ferdymercury** [comment]
Maybe related: https://github.com/root-project/root/commit/5473c5c1b06814575f60bfb8609cd30b2f3e1cee by @dpiparo @krasznaa

**Comment by olantwin** [comment]
I can reproduce this in our software stack (SHiP/snd@snd) as well, where ROOTSYS etc. are all set for dependencies that need ROOT at build and/or run-time (using ALICE's alibuild). ROOT and its `ROOTConfig.cmake` are found without issues, but the new way to deal with VDT breaks anyone trying to user `ROOTConfig.cmake`.

In our case, we use the `builtin_vdt` build option when building ROOT from source. This is a clear regression from 6.28.

**Comment by ferdymercury** [comment]
FindPackage in CMake always worked like that, you just tell Cmake your ROOT_DIR or BOOST_DIR or DCMTK_DIR and it does all the job. It prevents having to source all libraries beforehand and unnecessarily polluting your build env with executables, etc.

It worked well like this with 6.26 and 6.28, so with 6.30 it changed and now it cannot automatically find the builtin vdt and nlohmann

**Comment by krasznaa** [comment]
:thinking: As I wrote earlier, with `builtin_vdt` used for the build, `ROOTConfig.cmake` should indeed probably add the ROOT installation path as a search path for VDT.

To clarify: 6.30 now makes a dependency explicit, which was always there. And which required people **not** using `builtin_vdt` (for instance ATLAS...) to call `find_package(VDT)` in their own code, and link against `VDT::VDT` on their own, just to be able to use some of the ROOT libraries. So for some people the new ROOT version behaves a lot better now...

But yes, I didn't think of use-cases where people use a built-in version of VDT in ROOT, and they set up their build against ROOT without setting up the ROOT runtime environment. :thinking: (Does your build system set up the appropriate environment for running the dictionary generation, as part of the build commands? Since you do need the full ROOT runtime environment for that. Or do you just not generate any dictionaries in that particular build? :confused:)

**Comment by ferdymercury** [comment]
I understand, thanks for the clarification!

In my use case, I do use ROOT_GENERATE_DICTIONARY in the CMakelists, without needing to set up the ROOT runtime environment. It works well, I can then run my executable, which pops up a TGuiCommandPlugin, from which I can control the ROOT derived dictionaried classes via cling without problems. (in 6.28 at least)

A reproducer of my build-use-case can be found here: https://github.com/root-project/root/issues/8365#issue-914079362

**Comment by krasznaa** [comment]
Hmm... I'm now trying to reproduce the issue. But don't seem to be able to. :confused:

After building and installing ROOT with a built-in VDT, I see the following:

```
[bash][pcadp04]:buildtest > more ../findtester/CMakeLists.txt 

cmake_minimum_required(VERSION 3.20)
project(ROOTFindTester VERSION 0.0.1 LANGUAGES CXX)

find_package(ROOT 6.30 CONFIG REQUIRED)
[bash][pcadp04]:buildtest > cmake -DROOT_ROOT=/mnt/hdd1/krasznaa/projects/root/install ../findtester/
-- The CXX compiler identification is GNU 11.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Vdt: /mnt/hdd1/krasznaa/projects/root/install/include (found version "0.4") 
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/hdd1/krasznaa/projects/root/buildtest
[bash][pcadp04]:buildtest >
```

I.e. CMake (3.20, on RHEL9) is very happy to find the built-in VDT for me. Even without having done any environment setup at all. I'm just pointing CMake at ROOT's installation location using `ROOT_ROOT`.

Are you not pointing at ROOT's installed location in any shape or form? :confused: I didn't know that CMake would be looking for packaged under `/opt` automatically. :confused: So, how is this happening in your environment? How does CMake find ROOT, but not VDT in the same location? Since now that I read a little about it, when CMake is executing code "as part of a `find_package` call", it does consider paths that were used to find the package in question.

I'm very much planning to add a setting for `Vdt_ROOT` in https://github.com/root-project/root/blob/master/cmake/scripts/ROOTConfig.cmake.in. But for that I really need to be able to reproduce your issue first...

**Comment by ferdymercury** [comment]
Hi, thanks for the clarification. But I was speaking about downloading the binary release, not self-build and install.

**Comment by krasznaa** [comment]
Hmm... Okay, so you use `ROOT_DIR`. I could reproduce the issue with that finally. Though still a bit differently from what you posted just now.

```
[bash][pcadp04]:buildtest > cmake -DROOT_DIR=/mnt/hdd1/krasznaa/projects/root/install/cmake ../findtester/
-- The CXX compiler identification is GNU 11.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Vdt (missing: VDT_INCLUDE_DIR VDT_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /mnt/hdd1/krasznaa/projects/root/install/cmake/modules/FindVdt.cmake:63 (find_package_handle_standard_args)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /mnt/hdd1/krasznaa/projects/root/install/cmake/ROOTConfig.cmake:137 (find_dependency)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "/mnt/hdd1/krasznaa/projects/root/buildtest/CMakeFiles/CMakeOutput.log".
[bash][pcadp04]:buildtest >
```

I.e. One should not use `<Foo>_DIR` normally, as that needs to point at the directory holding the CMake code. While `<Foo>_ROOT` is a much easier-to-use variable.

I'll open a PR with the update, but I'm less and less convinced that the issue would be in ROOT at this point, and not in your build setup. :frowning:

**Comment by olantwin** [comment]
I'm still trying to figure out when exactly this issue pops up in our framework.

- sourcing `thisroot.sh` works
- exporting ROOT_ROOT or setting the ROOT_ROOT CMake variable works, but requires setting the cmake policy 0074 for some older packages.
- Without either, e.g. GenFit, VMC, vgm still finds ROOT (I assume via $ROOTSYS), but the VDT error is thrown.

Maybe this adds some useful information. I live with setting the cmake policy in the different build recipes as a workaround for now.

**Comment by ferdymercury** [comment]
> I'll open a PR with the update, but I'm less and less convinced that the issue would be in ROOT at this point, and not in your build setup. 😦

mm but it worked always well with ROOT 6.28 and earlier. I use 4 or 5 different XXX_DIR (CLI11_DIR, DCMTK_DIR, ROOT_DIR, ...)

Btw, I also noticed that at some point in ROOT 6.26 or 6.28, I was specifying ROOT_DIR=/opt/root/cmake while in others I had to put /opt/root, but cannot recall when the change happened.
