### ISSUE TITLE
Adding a couple of useful methods in THnD

### ISSUE THREAD

**Issue by jgalan** [root-project/root#14173]
### Explain what you would like to see improved and how.

I am missing a couple of methods inside `THnD` class that I use frequently when working with the usual `TH1D`, `TH2D`, ... classes.

I am missing something like: `std::vector <Double_t> GetBinCenter(std::vector<Int_t> idx)` that simply returns the center of the bin using the ranges and number of bins. Simple implementation such as for each component doing:

```
xMin + (xMax-xMin)*((double)bin-0.5)/Nbins;
```

where `xMin`, `xMax`, `Nbins` are known for each dimensions inside `THnD` and `bin` is the corresponding bin where we want to know its coordinate.

Perhaps there is another way to achieve this (please let me know), but it would be interesting that there would be coherence between `TH` and `THn` methods.

Also a method to get the integral would be interesting. See this post:

https://root-forum.cern.ch/t/method-to-calculate-integral-in-a-thnd/57276

Thanks for considering!

### ROOT version

ROOT 6.26/02

### Installation method

source

### Operating system

Linux

**Comment by Axel-Naumann** [comment]
Hi @jgalan ! Thanks for your proposals - do you think you could propose some of this code yourself, as a pull request? :-)

**Comment by jgalan** [comment]
Unfortunately I am not being paid by CERN, and I am quite overloaded. I have to dedicate my effort to work on the projects I am being paid for. Of course, I can just live with the classes as they are written. I just thought it would be good to dedicate a bit of my time to give you just some feedback/ideas so that you understand how to improve my own user experience. Of course, I understand that my user experience might be different to that of the average user experience, and the ROOT priorities are others. But it is not me who must push for CERN reputation.

**Comment by jgalan** [comment]
Perhaps if ROOT people contributes the PR, I could review and test it works (half the work). As a ROOT user I would enter into the development chain, at least I find it more natural. If I write to the root-forum, I am pointed towards GitHub issues, then towards creating myself the PR. Then, next time I will think twice about writing to the root-forum. This is I believe the natural average user thought. Of course, I understand the developer perspective too :) .

**Comment by Axel-Naumann** [comment]
Gzee Javier - I was just asking! I did not investigate whether you're e.g. a student who'd love a challenge. So no worries, the answer is "no", that's totally fine, and we'll go from there!

**Comment by ferdymercury** [comment]
@jgalan PR here https://github.com/root-project/root/pull/15200
