### ISSUE TITLE
[cling] Replace llvm::Optional and llvm::None with std::optional

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#14205]
With the upgrade to LLVM 16, `llvm::Optional` is a deprecated / legacy alias of `std::optional`: https://github.com/llvm/llvm-project/commit/2916b99182752b1aece8cc4479d8d6a20b5e02da Likewise, `llvm::None` / `llvm::NoneType` become `std::nullopt` / `std::nullopt_t`: https://github.com/llvm/llvm-project/commit/abfe65a12b77f9f0292d3ec70bd9fc3b9c13d905

These transitional aliases are removed with LLVM 17: https://github.com/llvm/llvm-project/commit/397f2e9ebee8d8e45547e90dd05228d7f965df67 To prepare for this, we should replace, in `core/metacling/` and `interpreter/cling`
 * [ ] all spellings of `llvm::Optional` with `std::optional`,
 * [ ] all spellings of `llvm::None` / `llvm::NoneType` with `std::nullopt` / `std::nullopt_t`

**Comment by devajithvs** [comment]
Self-assign
