### ISSUE TITLE
Implement value printing for `std::source_location`

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#14211]
### Feature description

It'd be great to have `std::source_location::current()` print out more than `(std::source_location) @0x...`! Just needs a `cling::printValue(const std::source_location *)` overload.

**Comment by devajithvs** [comment]
std::source_location was under the namespace `experimental` until recently. To use it under `std::` namespace will require C++20

https://en.cppreference.com/w/cpp/utility/source_location
