### ISSUE TITLE
String comparison operators defined in TString.h should be defined as constexpr

### ISSUE THREAD

**Issue by bachandi** [root-project/root#14244]
### Explain what you would like to see improved and how.

The comparison operators of `const char*` with `std::string_view` defined in [TString.h](https://github.com/root-project/root/blob/master/core/base/inc/TString.h) should be defined as `constexpr` to be consistent with the std definition.
```c++
constexpr inline Bool_t operator==(const char *s1, const std::string_view &s2)
{
  return std::string_view(s1) == s2;
}

constexpr inline Bool_t operator==(const std::string_view &s1, const char *s2)
{
  return s1 == std::string_view(s2);
}
```

### ROOT version

6.30/02

### Installation method

build from source

### Operating system

Ubuntu 22.04.3

**Comment by bachandi** [comment]
Any chance this could be backported to 6.30.x version?

**Comment by guitargeek** [comment]
Sure, why not! C++17 was already the minimum standard in that version, so the `string_view` backport was also not needed there.
