### ISSUE TITLE
TAxis::GetTicks and TAxis::SetTicks are inconsistent. Significantly so.

### ISSUE THREAD

**Issue by aharel** [root-project/root#14256]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

When creating a modified version of a histogram/graph it's useful to have the axis of the new variation emulate those of the original. Something like target.SetXXX( original.GetXXX()) should do the trick. And it does for almost everything. The exception are the Ticks. Where if idol has bits 9 & 10 (kTickPlus and kTickMinus) both false, GetTicks returns '+' which SetTicks encodes as bit 9 on and bit 10 off. This not only messes up the display of the ticks, but also the location of the tick labels and the axis' main title.
I'm working around that by manually called SetBit, so it's no longer a problem for me. But it just seems like an API bug.

### Reproducer

```
TAxis idol, target;
target.SetTicks( idol.GetTicks() )
cout<<idol.TestBits( 1<<9 )<<" --> "<<target.TestBits( 1<<9 )<<endl;
```

### ROOT version

```
6.26/06
Built for linuxx8664gcc on Jul 28 2022, 18:08:51
From tags/v6-26-06@v6-26-06                                    
With c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0       
```          

### Installation method

Built from source

### Operating system

Linux

**Comment by ferdymercury** [comment]
I proposed a fix, see link above.

**Comment by aharel** [comment]
Code looks good.
Not so sure about the comment.
When you create a histogram and draw it, the axes are created with both bits off and the ticks are drawn inside.

**Comment by ferdymercury** [comment]
Thanks, I just fixed the explanation.
