### ISSUE TITLE
Including <sys/stat.h> breaks ROOT 6.30.01 compiled on Centos7 when running on RHEL8

### ISSUE THREAD

**Issue by ktf** [root-project/root#14272]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

In our stack we have our own build of ROOT which is performed on CC7. We regularly use those builds on RHEL8 or any subsequent version, since the ABI stability always allowed us to do so (provided we override the compiler installation with one which was compiled on the runtime platform). This worked fine until v6.30.01. With such a version whenever we do:

```
#include <sys/stat.h>
```

it breaks on lxplus8 with:

```
[O2Physics/daily-20231219-0100-1] ~ > root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.30/01                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Dec 19 2023, 01:09:04                 |
  | From tags/v6-30-01-alice2@v6-25-02-6400-g526782cfe8              |
  | With c++ (GCC) 12.2.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] #include <sys/stat.h>
In file included from ROOT_prompt_0:1:
In file included from /usr/include/sys/stat.h:30:
/usr/include/bits/types/struct_timespec.h:9:8: error: redefinition of 'timespec'
struct timespec
       ^
/usr/include/time.h:120:8: note: previous definition is here
struct timespec
       ^
```

notice that running the same with v6.28.8 works just fine. Running a slc7 build  on slc7 also works fine. Compiling the same thing with GCC also works fine, including when mixing the platforms.

### Reproducer

On lxplus8:

```
/cvmfs/alice.cern.ch/bin/alienv enter VO_ALICE@O2Physics::daily-20231219-0100-1
root
#include <sys/stat.h>
```

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.30/01                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Dec 19 2023, 01:09:04                 |
  | From tags/v6-30-01-alice2@v6-25-02-6400-g526782cfe8              |
  | With c++ (GCC) 12.2.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

aliBuild

### Operating system

C7 running on RHEL8

### Additional context

This is a showstopper for ALICE to adopt ROOT 6.30.X and we will have to revert back to ROOT 6.28.8 immediately if a solution is not found by noon.

**Comment by ktf** [comment]
Notice that to trigger the issue is enough to have an header `bar.h`:

```
#ifndef _STRUCT_TIMESPEC
#define _STRUCT_TIMESPEC 1

/* POSIX.1b structure for a time value.  This is like a `struct timeval' but
 *    has nanoseconds instead of microseconds.  */
struct timespec
{
  int tv_sec;              /* Seconds.  */
  int tv_nsec;    /* Nanoseconds.  */
};

#endif
```

and simply include it with `#include "bar.h"`.

**Comment by ktf** [comment]
@dpiparo @vepadulano as discussed offline, the issue is that Centos 7 uses `_TIME_H` while RHEL 8 uses `_STRUCT_TIMESPEC` to guard against double definition of `struct_timespec`. The new ROOT seems to have the C7 version cached in some module, hence the issue when `<sys/stat.h>` is included. As discussed, I have protected the issue on our side with:

```C++
#ifdef _TIME_H
#define _STRUCT_TIMESPEC
#endif
```

and it works, however I guess this can happen also elsewhere / for other guards, so in the long term it would be good if a solution at the Cling / ROOT level can be provided.

As a sidenote we are indeed deprecating C7, however the process is always long and in general the ability to run a given build on different ABI compatible platforms strong desiderata on our side.

**Comment by dpiparo** [comment]
Dear @ktf , thanks for this change. It is great that the Alice users can benefit from all the nice features that ended up in 6.30! 
We are investigating on our side now whether this issue can be fixed in ROOT upstream.
