### ISSUE TITLE
qtweb gui prints warning in "Hide canvas while geometry too small w=0 h=0"

### ISSUE THREAD

**Issue by bachandi** [root-project/root#14300]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When using the qt web gui widget as shown in the qtweb tutorial with Qt5.15 I get strange warnings about the canvas geometry being too small. To reproduce this you can just run the qtweb tutorial.

When launching the qtweb tutorial these warning about too small canvas geometries are printed:
`
... rootscheme://root.server1/jsrootsys/modules/gpad/TPadPainter.mjs:602: Hide canvas while geometry too small w=0 h=0
`
`
... rootscheme://root.server1/jsrootsys/modules/gpad/RPadPainter.mjs:410: Hide canvas while geometry too small w=0 h=0
`
I did not manage to get rid of these warnings. Maybe some else has more insight on how to fix them?

### Reproducer

Run the `qtweb` from `tutorials/webgui/qtweb`. The `Hide canvas while geometry too small w=0 h=0` warnings will be printed to the console.

### ROOT version

6.31.01

### Installation method

build from source with Qt5.15

### Operating system

Ubuntu 22.04

**Comment by linev** [comment]
Message produced by JSROOT and printed out in the qtweb plugin.

It is side effect of canvas rendering in the beginning when HTML elements not yet fully layouted.

To disable such debug messages, one should insert following line into `ExampleMain.cpp` line:

    ROOT::Experimental::RLogManager::Get().SetVerbosity(ROOT::Experimental::ELogLevel::kFatal);

     QApplication myapp(argc, argv2); // Qt application

And also add include of:

    #include "ROOT/RLogger.hxx"

**Comment by bachandi** [comment]
Thank you for the workaround. 

But with this we ignore all warnings. As this geometry warning is anticipated shouldn't their messages console log level be reduced to info or debug?

```js
js/modules/gpad/RPadPainter.mjs:410:         console.warn(`Hide canvas while geometry too small w=${rect.width} h=${rect.height}`);
js/modules/gpad/TPadPainter.mjs:601:         console.warn(`Hide canvas while geometry too small w=${rect.width} h=${rect.height}`);
```

**Comment by linev** [comment]
You can set different debugging levels for `RLogManager`. See enum in `ROOT/RLogger.hxx`:

```
enum class ELogLevel : unsigned char {
   kUnset,
   kFatal,   ///< An error which causes further processing to be unreliable
   kError,   ///< An error
   kWarning, ///< Warnings about likely unexpected behavior
   kInfo,    ///< Informational messages; used for instance for tracing
   kDebug    ///< Debug information; only useful for developers; can have added verbosity up to 255-kDebug.
};
```

**Comment by bachandi** [comment]
Yes but to suppress the canvas geometry warning I need to set at least `ROOT::Experimental::RLogManager::Get().SetVerbosity(ROOT::Experimental::ELogLevel::kError);` so everyother warning issued is also suppressed not only the `Hide canvas while geometry too small`. 
That's why I was rasing the question if the warning level for the `Hide canvas while geometry too small` message is optimal.

**Comment by linev** [comment]
For the moment changing of global debug level is the only solution to suppress warning.

One changing RLogger debug level, which is not used for core ROOT components like I/O.
Therefore all other important warnings and error messages will be still there.

**Comment by bachandi** [comment]
Ok. Thanks for the response. Then we can close this issue.
