### ISSUE TITLE
Test failure with `nbconvert-7.14`

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#14303]
`roottest-python-JupyROOT-tpython_notebook` fails with `nbconvert-7.14`:
```diff
--- tpython.ipynb
+++ tpython_out.ipynb
@@ -16,7 +16,14 @@
      "name": "stdout",
      "output_type": "stream",
      "text": [
-      "1\n"
+      "1"
+     ]
+    },
+    {
+     "name": "stdout",
+     "output_type": "stream",
+     "text": [
+      "\n"
      ]
     }
    ],
```

For now, we avoid that version since https://github.com/root-project/roottest/pull/1041 / commit https://github.com/root-project/roottest/commit/a68af407d9577a055f44c58e42c42b1244b484cc.

**Comment by dpiparo** [comment]
Fixed by https://github.com/root-project/roottest/pull/1082
