### ISSUE TITLE
Char_t and UChar_t in plain ROOT and pyROOT

### ISSUE THREAD

**Issue by vlimant** [root-project/root#14361]
### Feature description

a TTree::Draw and Three::Scan on Char_t (and UChar_t in pyroot) saved values (initially as int8 and uint8) produce symbols instead of numbers. Since most likely these (Char_t and UChar_t) saved with numerical values intended, it would be great if root interpret those as numbers instead of symbols.

### Alternatives considered

I cannot think of any alternatives ; except not storing leaves as int8 or uint8 "types"

### Additional context

This is creating issues with leaves saved  in int8 and uint8 CMS NANO dataformat when reading files in plain root (using make class, or plain root) and in pyroot.

**Comment by ferdymercury** [comment]
> I cannot think of any alternatives ; except not storing leaves as int8 or uint8 "types"

`use +0`

https://root-forum.cern.ch/t/draw-short-integers-as-numbers-not-characters/52530/20?u=ferhue

**Comment by vlimant** [comment]
funny things is that UChar_t is seen as numerical, while Char_t is not. Best would be that they both get treated the same way ; numerically.

**Comment by pcanal** [comment]
This is historical and probably not changeable in a backward compatible way.  Arrays of `Char_t` have been historically used to store characters strings and that is the default for `TTree::Draw`.  

The solution (that works not matter what the underlying type is) is to force it to be numerical expression by appending `+0` to the leaf name.
