### ISSUE TITLE
The red frame around the selected pad of the webgui is not configurable

### ISSUE THREAD

**Issue by bachandi** [root-project/root#14401]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When using the webgui in Qt5 there is a red frame around the currectly selected pad:
<img width="337" alt="RedFrame" src="https://github.com/root-project/root/assets/62039342/c98e6a71-b86e-43e8-9b82-0bc7e19f7072">

Is there any way to disable this frame or possible to configure the color of the frame from within the C++ part?

It seems this color _red_ is hardcoded in `/js/modules/gpad/TPadPainter.mjs`
```js
let lineatt = this.is_active_pad && (cp?.highlight_gpad !== false) ? new TAttLineHandler({ style: 1, width: 1, color: 'red' }) : this.lineatt;
```
And I could not find a way to set _highlight_gpad_ from C++. Maybe I missed something?

### Reproducer

Launch the qtweb tutorial
Select the TCanvas tab
Divide the main canvas in multiple pads
Select one of the pads
You will see the red frame around the selected pad

### ROOT version

6.31.01 linuxx8664gcc

### Installation method

build from source

### Operating system

Ubuntu 22.04.3

**Comment by linev** [comment]
When you build ROOT master?
In the current master this option should be off by default.
You also can toggle this behavior by selecting "Options -> Highlight Pad" menu command.

**Comment by linev** [comment]
Probably you are doing incremental builds.
Flag set here:

https://github.com/root-project/root/blob/master/ui5/canv/controller/Canvas.controller.js#L89

You can check in your ROOT build directory in `$ROOTSYS/ui5/canv/controller/Canvas.controller.js` that:
```
cp.highlight_gpad = false;
```

It was changed by https://github.com/root-project/root/commit/5af4b57a376ce56fb738828806afdfd82b79d469 in September 2023.

**Comment by bachandi** [comment]
Yes this default is set to false. But when using for example the qtweb tutorial the `cp?.highlight_pad` is not false and triggeres the red frame.

**Comment by linev** [comment]
Now I see! 

It is because qtweb example uses ROOT6 canvas without openui5 gui - only plain graphics.
Therefore ui5 controller code is not invoked. 

You can manually add `painter.highlight_gpad = false` into `$ROOTSYS/ui5/canvas/canvas6.html` file in line around constructor:
```
...
        let painter = new TCanvasPainter(null, null);

         painter.online_canvas = true;
         painter.use_openui = is_ui5;
         painter.batch_mode = is_batch;
         painter.highlight_gpad = false;
...
```

I will later provide PR which will fix it.

**Comment by linev** [comment]
After recent update in JSROOT/webgui problem is resolved now.
