### ISSUE TITLE
[6.30] rootls and rootprint broken on Ubuntu 22.04 binary release

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#14416]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

rootls and rootprint no longer work on Ubu22.04 binary release 6.30.02

### Reproducer

```
rootls
/usr/bin/env: ‘/py-venv/ROOT-CI/bin/python3.10’: No such file or directory
```

### ROOT version

```
ROOT v6.30/02
Built for linuxx8664gcc on Nov 27 2023, 19:50:38
From tags/v6-30-02@
With c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Binary directory: /opt/root/bin
```

### Installation method

Binary Release

### Operating system

Ubuntu 22.04

**Comment by couet** [comment]
It looks like it is looking at some python version which is not is the same place on your machine... not sure how to fix that except by reinstalling root locally to get the right version. something should have changed if it worked before.

**Comment by ferdymercury** [comment]
Thanks for the swift reply. In case it helps:

```
python3 --version
Python 3.10.12
whereis python3
python3: /usr/bin/python3 /usr/lib/python3 /etc/python3 /usr/share/python3 /usr/share/man/man1/python3.1.gz
which python3
/usr/bin/python3
```

**Comment by bellenot** [comment]
Thanks! FYI the issue has been identified and will be fixed soon
