### ISSUE TITLE
TWebFile::GetFromWeb10 error - redirect without location from host

### ISSUE THREAD

**Issue by mvala** [root-project/root#14429]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Sometimes it happens (it is supported by http) that headers (like `Location`) can be with lower case `location`.

https://github.com/root-project/root/blob/e49a596254bab8610f5480aefe6d26c83c937c0b/net/net/src/TWebFile.cxx#L939

I think one needs to add to all `res.BeginsWith("<header name>")` eg. from `res.BeginsWith("Location:")` to  `res.BeginsWith("Location:", TString::ECaseCompare::kIgnoreCase)`  and it should be fine

```
⬢[mvala@toolbox [fc39] ~]$ curl -i https://eos.science.upjs.sk/eos/ndmspc/scratch/hsimple.root
HTTP/1.1 307 TEMPORARY_REDIRECT
server: XrootD/5.6.4
content-length: 0
date: Thu, 25 Jan 2024 08:01:05 GMT
etag: "12348030976:09c4618b"
location: https://eos.science.upjs.sk:9025/eos/ndmspc/scratch.....
....
```

### Reproducer

```
$ root https://eos.science.upjs.sk/eos/ndmspc/scratch/hsimple.root
root [0] 
Attaching file https://eos.science.upjs.sk/eos/ndmspc/scratch/hsimple.root as _file0...
Error in <TWebFile::GetFromWeb10>: error - redirect without location from host eos.science.upjs.sk
(TFile *) nullptr
```

### ROOT version

6.30/02

### Installation method

dnf

### Operating system

Linux

**Comment by linev** [comment]
@mvala 

Can you provide PR which works for you?

**Comment by mvala** [comment]
Currently i am busy with other things. I will do when i will have time

**Comment by linev** [comment]
Grate! 

There can be several other places like that, therefore code should be tested on real use-case.

**Comment by mvala** [comment]
Meanwhile it can be tested with this file https://eos.science.upjs.sk/eos/ndmspc/scratch/hsimple.root

**Comment by linev** [comment]
This server/file has much more problems. 
Server uses more complex redirection rules with `x-accel-redirect` and `x-sendfile` headers.
Plus redirected filename uses URI coding.
Simple change of upper/lower case does not help.

By default ROOT uses `TDavixFile` for http files reading and it only fails on this file.

**Comment by mvala** [comment]
File is working locally
```
⬢[mvala@toolbox [fc39] alice]$ curl -L https://eos.science.upjs.sk/eos/ndmspc/scratch/hsimple.root -o /tmp/hsimple.root
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  404k  100  404k    0     0   490k      0 --:--:-- --:--:-- --:--:--  490k
⬢[mvala@toolbox [fc39] alice]$ root /tmp/hsimple.root
root [0] 
Attaching file /tmp/hsimple.root as _file0...
(TFile *) 0x56205f931910
root [1] .q
```

**Comment by linev** [comment]
> File is working locally

Yes, `curl` and `wget` are able to download the file. 
But davix library used in `TDavixFile` is not working with it.

**Comment by mvala** [comment]
Since i understand that my case is special and i have alternative to use `root://` to access same file, it think we can close it.

**Comment by linev** [comment]
> Since i understand that my case is special and i have alternative to use root:// to access same file, it think we can close it.

It is very special case and need to be fixes in both `TWebFile` and `TDavixFile`. 
Also jsroot with standard `XMLHttpRequest` is not able to provide partial access to this file and only works after full download of the file into memory.

Therefore if there are other way to access such files I prefer to keep ROOT code as is
