### ISSUE TITLE
Parser for I/O customization rule is too strict.

### ISSUE THREAD

**Issue by pcanal** [root-project/root#14462]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

A rule like:
```
#pragma read sourceClass="userClass" targetClass="userClass" source="" target="transientMember" version="[1-]" code="{ transientMember = true; } "
```
fails because of the trailing space in code.  Instead:
```
code="{ transientMember = true; }"
```
works.

### Reproducer

With class:
```
class userClass
{
   bool transientMember;
};
```

### ROOT version

master

### Installation method

any

### Operating system

any

**Comment by Kamakshi8104** [comment]
hey can I work on this issue?

**Comment by gemmeren** [comment]
I am looking into this for Fixarhon. No promises.

**Comment by gemmeren** [comment]
I believe before line: [L198](https://github.com/root-project/root/blob/c30c4035f67bf6444ca89cd5d1bd5c38c521b9f9/core/foundation/src/RConversionRuleParser.cxx#L198)
one needs to insert:
`      command = TSchemaRuleProcessor::Trim( command );
`
Still struggling with running a reproducer :(

**Comment by gemmeren** [comment]
Of course, its not quite as easy... :( 
The parsing currently looks for `}"` without any white-space, similarly it check for the 2nd character to be `{` , meaning no space between the quote and brace here either. I'd suggest:
Split off the quotes, trim the string and check the first last characters to be `{` and `}`. But I am not totally convinced that this may not have bad side-effects...

**Comment by gemmeren** [comment]
I need to rethink this, since my initial PR lost command elements after code key. Part of the problem is code fragment can include either curly braces or quotes, so finding the end of the key isn't quite as trivial. Since any end marker could be allowed as legal piece of code, limiting things to the current `}"` may actually be the most proper.
