### ISSUE TITLE
TBrowser issue

### ISSUE THREAD

**Issue by xkzl** [root-project/root#14483]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Hello, 

I updated my root version to ROOT:
```
$ root --version
ROOT Version: 6.31/01
Built for macosxarm64 on Jan 13 2024, 10:58:11
From tags/v6-31-01@v6-31-01
```

Since then, I lost the TBrowser display (and don't want to use RBrowser for the moment).
<img width="798" alt="Screenshot 2024-01-30 at 17 55 46" src="https://github.com/root-project/root/assets/37673095/7188e7a8-c2f4-4130-9ce7-947d55a49ed0">

I have macOS Sonoma - last update. 
Is there any way to debug this or is it known issue ?

### Reproducer

```
root -l 
> new TBrowser
```

### ROOT version

```
$ root --version
ROOT Version: 6.31/01
Built for macosxarm64 on Jan 13 2024, 10:58:11
From tags/v6-31-01@v6-31-01```
```

### Installation method

build from source

### Operating system

macOS

**Comment by couet** [comment]
I just rebuilt ROOT on an arm machine with MacOS sonoma. It works for me:

<img width="1244" alt="Screenshot 2024-01-30 at 11 21 07" src="https://github.com/root-project/root/assets/4697738/bb4a873a-1135-4b63-b2fd-46e8a66c9e24">

**Comment by xkzl** [comment]
I have a MacBook Pro M2 Max (2022) 

I compiled a ROOT stable tagged version few days ago. May I ask which one you just compiled ?

What was the origin of the issue in the first place ? Perhaps it might help finding the reason why this happens again.

Thank you.

**Comment by couet** [comment]
I have tried on a Mac Mini with the M2 processor, MacOS 14.3 and clang 15. I used the master version of ROOT.
The PR fixing this issue is: https://github.com/root-project/root/pull/13885
@TimurP made it.

**Comment by xkzl** [comment]
Could you maybe point me a specific commit? 
```
-- Found OpenGL: /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/OpenGL.framework
-- Looking for GLEW
-- Found GLEW: /opt/homebrew/lib/cmake/glew/glew-config.cmake
CMake Error at cmake/modules/SearchInstalledSoftware.cmake:615 (message):
  Please enable builtin Glew due bug in latest CMake (use cmake option
  -Dbuiltin_glew=ON).
Call Stack (most recent call first):
  CMakeLists.txt:298 (include)
```

**Comment by xkzl** [comment]
My bad it is AppleClang15, but I can't figure out still.

**Comment by xkzl** [comment]
Except for the createCI() issue, the new compilation seems to work and the master from this morning is fine. 
Sorry for this issue. Do you have any idea about cling::createCI ?
