### ISSUE TITLE
Include the open source Tex Gyre Heros clone of Helvetica in ROOT fonts

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#14532]
### Explain what you would like to see improved and how.

As per discussion with CMS Common Analysis Tools team. The title of this issue says it all.

### ROOT version

all

### Installation method

All

### Operating system

all

**Comment by vepadulano** [comment]
Just FYI this is a duplicate of https://github.com/root-project/root/issues/14064

**Comment by dpiparo** [comment]
Duplicate.
