### ISSUE TITLE
[ROOT-6193] Editor for palette axis cannot set title properties

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14541]
### Explain what you would like to see improved and how.

From https://its.cern.ch/jira/browse/ROOT-6193

The style editor for the palette axis cannot change the title size, offset, etc of the palette axis, even though the title is displayed. Could this be added, please?

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by couet** [comment]
The Jira report says that it is possible to set the title of the palette. This is not true anymore. It has been recently fixed.

**Comment by dpiparo** [comment]
@couet is right. Please see the plot from hsimple.root below. The title of the palette was changed on the fly using the editor, as well as its offset.


![Image](https://github.com/user-attachments/assets/90c5f35b-9167-4d93-8d7f-21ec44d8555c)
