### ISSUE TITLE
[ROOT-9200] With Cocoa backend sometimes need two ProcessEvents to show Canvas

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14547]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-9200

See https://root-forum.cern.ch/t/canvas-will-not-show/27582/11

### Reproducer

As per description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by couet** [comment]
This PR fixes the problem: https://github.com/root-project/root/pull/14671

**Comment by vepadulano** [comment]
Related PR was merged, closing the issue
