### ISSUE TITLE
[ROOT-8132] TF1 with specified fill attributes produces binned plot

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14542]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-8132

I expect, when fill attributes are specified,  TF1 just fill area under the function.
But result is binned plot, like shown in attachment.
Macro reproduced the plot

![canvas](https://github.com/root-project/root/assets/15638895/85ad3901-aa51-4747-abef-648c0514edd7)

### Reproducer

```cpp
void tf1_fill() {
   TFile::Open("danilo6.root");
   gFile->Get("canvas;1")->Draw();
   TH1* hist = (TH1*) gPad->GetListOfPrimitives()->FindObject("Hist_x");
   TF1* ff = (TF1*) hist->GetListOfFunctions()->FindObject("fit_x");

   ff->SetFillStyle(1001);
   ff->SetFillColor(7);

   gPad->Update();
}
```

Find the input file in the Jira issue

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by lmoneta** [comment]
This is not a bug, the fill area is always binned, if you want to make it less visible, choose an higher number of points for the function by doing for example:
```
ff->SetNpx(10000);
```

**Comment by ferdymercury** [comment]
Reminder: close associated JIRA ticket.
