### ISSUE TITLE
[ROOT-3437] request feature to print stl container contents in TTree::Show()

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14555]
### Feature description

From https://its.cern.ch/jira/browse/ROOT-3437

TTree::Show() is one of my favorite commands because it allows one to investigate in one line the basic contents of a TTree. I find it frustrating, however, that STL containers of basic data types are not printed, and we merely get the class name (e.g. &amp;quot;vector&amp;lt;double&amp;gt;&amp;quot;) and the value of the pointer to the container, which tells you nothing more than that the container is allocated.

I think it is possible to add this feature with some minor edits to TStreamerInfo. I have attempted this myself for vector&amp;lt;double&amp;gt; (see the attached) and had success with the following:

\- A branch made directly from a vector&amp;lt;double&amp;gt;
\- A branch made out of a class (call it &amp;quot;TTestClass&amp;quot;) that derives from TObject and contains a vector&amp;lt;double&amp;gt; as a data member
\- A branch made out of a class containing a data member that is a TClonesArray of TTestClass's

The basic idea was to imitate the special-case-handling for the std::string class in the TStreamerInfo::PrintValue() and TStreamerInfo::PrintValueAux().

One issue is that for the STL classes, counter-intuitively TStreamerInfo::fLength = 1, no matter how many entries are in the container, so that PrintValueAux() always gets called with aleng = 1 instead of something related to the size of the array. Rather than mess with fLength, which appears to have important function outside of the PrintValue*() routines, I thought it would be better to simply add lenmax as an additional final parameter to PrintValueAux(), to be used in place of aleng by the stl classes. This could then be compared to the container length and used in the printf loop in the same way that aleng is used for arrays of basic data types.

The other issue I ran into is that it is not easy to format the output to make it look &amp;quot;nice&amp;quot;. The PrintCR() function used by other data types in PrintValueAux() works well for vector&amp;lt;double&amp;gt; in PrintValue(), so I suggest moving that function declaration up so that it can be used there. However, in PrintValueAux() the printing somehow always looks funny for the case of the TClonesArray of TTestClass's. My guess is that the printing looks funny as well for the other array types handled by PrintValueAux() so maybe this is considered to be okay? At any rate, I tried a number of options and left them in the file in my order of preference with all but the first one (no carriage returns) commented out. I also thought it was best to make the entry delimiter in PrintValueClones() and
PrintValueSTL() from &amp;quot;,&amp;quot; to &amp;quot;;&amp;quot;.

It should be simple to add this feature for other STL containers, such as vector&amp;lt;int&amp;gt;, vector&amp;lt;float&amp;gt;, vector&amp;lt;string&amp;gt;, etc. It would be nice to also add output for maps, e.g. if `map<keytype, valtype>` could print as

key1 => val1, key1 => val2, ...

**Comment by enirolf** [comment]
See https://its.cern.ch/jira/browse/ROOT-3437 for preceding discussion
After discussing offline with @pcanal, the conclusion is that since we have exactly this feature in RNTuple, and we want to ultimately encourage people to start using RNTuple instead of TTree, we won't make the effort to still add it to TTree. Therefore, the issue can be closed.
