### ISSUE TITLE
[ROOT-4839] TTree::Refresh and TTree::GetEntry causing crash

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14560]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-4839

Dear Rooters,

I was writing an online monitoring program. Our DAQ is constantly writing data to a temporary TTree, and a monitoring GUI is reading the tree periodically. I followed the instructions (AutoSave) from the reference page http://root.cern.ch/root/html534/TTree.html. The program occasionally crashes after a Refresh() followed by a GetEntry().

I was able to reproduce the problem with a static TTree. The script that generates the tree is below.
```cpp

{
gROOT->Reset();

TFile *f = new TFile("test.root","recreate");
TTree *tree = new TTree("test","my test tree");
TH1F *hh = new TH1F("hh","hh",100,-10,10);
Float_t x;

tree->Branch("x",&amp;amp;x,"x/F");
//tree->SetCircular(10000);
int count = 0;
for(size_t ii=0;ii<1000;ii++){
   x = gRandom->Gaus(0,2);
   tree->Fill();
   hh->Fill(x);
   count++;
   if(count%1000==0) {
      tree->AutoSave("SaveSelf");
      //hh->Write();
   }
}
tree->Write();
hh->Write();
f->Close();
}
```

Then I used a root session to open the file.

```cpp
jliu@jliu-VirtualBox:~$ root \-l test.root
root [0]
Attaching file test.root as _file0...
root [1] TTree *t = (TTree*)gDirectory->Get("test")
root [2] t->GetEntry(0)
(Int_t)4
root [3] t->Refresh()
root [4] t->GetEntry(0)
Error in <TObjArray::AddAt>: index \-1 out of bounds (size: 10, this: 0x9953a50)
```

This is very puzzling. Is there a way to get around this.

I was able to reproduce this on both ROOT 5.27 (SL5.5) and ROOT 5.34 (Ubuntu 11.04).

### Reproducer

As per the description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by enirolf** [comment]
I cannot reproduce the error with the provided reproducer, so I assume this issue has been fixed somewhere along the way.
