### ISSUE TITLE
[ROOT-10943] Multiple variable definition

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14568]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-10943

BDT.cxx line 33 and DecisionTreeNode.cxx line 61 define the same external variable
```cpp
bool     TMVA::DecisionTreeNode::fgIsTraining = false;
```
This is forbidden by C++ standard.

### Reproducer

As per the description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by vkucera** [comment]
Seems fixed in https://github.com/root-project/root/pull/6299
