### ISSUE TITLE
[ROOT-5138] Provide an implementation of Random123

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14564]
### Feature description

From https://its.cern.ch/jira/browse/ROOT-5138

Add an implementation of the thread safe random123 generator. 
Need to see if we need to add as a new TRandom class as well. 

use the patch provided in 
http://fc.isima.fr/~schweitz/schweitz/TRandom4.diff

see https://savannah.cern.ch/patch/?5528

**Comment by lmoneta** [comment]
I would avoid including the code in ROOT. Wrapper for GSL exists, I would use those if needed, see  
https://www.thesalmons.org/john/random123/releases/latest/docs/index.html

**Comment by lmoneta** [comment]
Link with patch is broken. I will close the issue, since users can use it via the GSL interface

**Comment by ferdymercury** [comment]
Reminder: close the JIRA ticket https://its.cern.ch/jira/browse/ROOT-5138
