### ISSUE TITLE
[ROOT-7155] Angular units used in HTML doc of TGLViewer::SetPerspectiveCamera are wrong

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14576]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-7155

https://root.cern.ch/root/html/src/TGLViewer.cxx.html#per4VC

The units of 'hRotate' and 'vRotate' should be radians. In addition the second 'hRotate' in the doc should be replaced with 'vRotate.'

### Reproducer

As per the description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by ferdymercury** [comment]
Thanks! Reminder: close the associated JIRA ticket :)
