### ISSUE TITLE
[ROOT-10213] Make RResultPtr<Object> behave more like Object*

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14578]
### Explain what you would like to see improved and how.

From https://its.cern.ch/jira/browse/ROOT-10213

Suppose to have an RDataFrame and call Histo1D on it. This will return an RResultPtr to a TH1D. There are some functions of TH1D that only accept pointers to TH1D, such as Add.

In the case that a user wants to add two histograms created with an RDataFrame computational graph, for instance:
```python
import ROOT
df_1 = ROOT.RDataFrame(10)
h_1 = df_1.Histo1D("rdfentry_")
df_2 = ROOT.RDataFrame(10)
h_2 = df_2.Histo1D("rdfentry_")
h_1.Add(h_2)
```
The Add function of h_1 will be correctly called, but it will give an error while trying to overload with h_2 that is of type RResultPtr.

This situation could be generalized to all functions of ROOT classes that accept pointers to ROOT objects.

It should be so that RResultPtr behaved like a pointer to the result of the computational graph, in order to be accepted by this kind of functions.

If a user wants to retrieve directly the result of the computational graph in Python, s/he can call the GetValue function. This is similar to how in C++ one can dereference the RResultPtr.

With the modifications written above, the GetValue function could be avoided, so that when a user types Histo1D s/he can actually use the result of that as if it were a TH1D object.

See the attached file for a specific situation in which the behaviour of GetValue is unclear.

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by guitargeek** [comment]
Hi! I thought about this also a few weeks ago, and just like Jason Turner I came to the conclusion that this is evil:
https://www.youtube.com/watch?v=T97QJ0KBaBU

In this case, the implicit conversion would even mean the lazy evaluation of the `RResultPtr`. So it becomes more in-transparent where the evaluation would actually happen.

So this suggestion sounds nice on paper, but I think in practice it will leas to more confusion than benefit by obscuring the triggering of the event loop.

**Comment by vepadulano** [comment]
@guitargeek love the reference to Jason! And of course I totally agree! This is one of those occasions where you look back at your own past opinions and realise you were wrong (since I was the OP).

The only other alternative would be providing explicit overloads for `RResultPtr<T>` wherever one would want this feature to be used, but that's really hard to scale and sounds unmantainable. I believe we can close this issue, thanks!
