### ISSUE TITLE
[ROOT-10355] Use GetDemangledTypeName instead of TypeID2TypeName

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14577]
### Explain what you would like to see improved and how.

From https://its.cern.ch/jira/browse/ROOT-10355

Currently, {{RDataFrame}} uses an own implementation of getting the typename as string, namely {{ROOT::Internal::RDF::TypeID2TypeName}}. However, we could reuse {{ROOT::Internal::GetDemangledTypeName}} from ROOT core, which has the same functionality and is the superior implementation.

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by maximusron** [comment]
@vepadulano 

`ROOT::Internal::GetDemangledTypeName(t)` calls `TClassEdit::DemangleName(t.name, status)`

We could also use `RDFInternal::DemangleTypeIdName` within the RDFInternal namespace which calls `TClassEdit::DemangleTypeIDName(ti, errcode)` -> `TClassEdit::DemangleName(ti.name(), errcode)`

**Comment by dpiparo** [comment]
This function has been optimized for RDF in order to avoid as much as possible contention, and therefore, slowdowns of RDF analyses: https://github.com/root-project/root/pull/16528

I would therefore *not* advise to move away from this tailored implementation.
