### ISSUE TITLE
[ROOT-10797] Seg fault and misleading error messages if system header files are missing

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14571]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-10797

Dear ROOT developers

I was not able to start ROOT 6.20 on a machine running standard CentOS 7. Opt version of ROOT produced seg fault without any hint what could be wrong, debug version of ROOT complained that SystemDir was missing, but did not say which directory exactly.

Error messages from ROOT 6.18 were more informative: it complained about missing header file ctype.h

Finally problem was solved by installing glibc-headers rpm, which was not installed initially, since we didn't plan to compile anything on this machine.

In future it would be nice to have clear error message that ROOT can not start because certain file is missing, especially if it's not missing shared library which can be checked by "ldd"

see details in

[https://root-forum.cern.ch/t/can-not-start-root-6-20-02-from-lcg-97-systemdir-is-missing/39594]

 

With best regards

Sanya

 

### Reproducer

As per the description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by dpiparo** [comment]
Cannot reproduce, and, as @vgvassilev says on the forum, solves this kind of issues.
