### ISSUE TITLE
[ROOT-10802] We need a clear explanation of cycle numbers in our docs

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14584]
### Explain what you would like to see improved and how.

From https://its.cern.ch/jira/browse/ROOT-10802

Users are continuously tripped up by multiple namecycles (for a non-exhaustive list of forum questions on the topic, see the forum threads that link to [this thread](https://root-forum.cern.ch/t/aux-1-aux-2-aux3/13345)).

 The only explanation I could find in our docs is in the ROOT users guide:

> Their cycle number, the number after the semicolon, differentiates objects on disk with the same name

which is true but insufficient to figure out what to do with those numbers. TFile's doxygen guide refers to the cycle number several times but never explains what it is.

It would be great if we could have a complete source of information for everything about namecycles, e.g.:
 * TTree namecycles only contain the metadata, but for other objects, the namecycles might be full copies
 * TObject::kOverwrite can be used to avoid writing multiple namecycles
 * retrieving an object from TFile by name automatically retrieves the highest namecycle
 * relation to TTree's autoflush and autosave settings

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by skkwan** [comment]
From a user point of view, the text in the ROOT manual now seems sufficiently clear:

- Behaviour for non-TTree objects [1]:

"By default, existing objects are not replaced when writing new objects with the same name. Instead, a new namecycle is created, denoted by ;2, ;3, etc. When retrieving the object from the file, ROOT will automatically pick the highest namecycle.

Some objects, such as histograms, automatically register themselves with the current TDirectory (e.g. the last TFile opened): these objects will appear as OBJ entries, without a namecycle. See also → [Object ownership](https://root.cern/manual/object_ownership).

For the particular case of TTree, cycles only store metadata, see [Baskets, clusters and the tree header](https://root.cern/manual/trees/#baskets-clusters-and-the-tree-header)."

- Behaviour for TTree objects [2]:

"Multiple updates of these headers can often be found in files (treename;1, treename;2 etc, called cycles, see → [Opening and inspecting a ROOT file](https://root.cern/manual/root_files/#opening-and-inspecting-a-root-file)). Only the last one (also accessible as treename) knows about all written baskets."


[1] https://root.cern/manual/root_files/#opening-and-inspecting-a-root-file
[2] https://root.cern/manual/trees/#baskets-clusters-and-the-tree-header
