### ISSUE TITLE
[ROOT-6317] using namespace statement does not provoke autoload

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14586]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-6317

Hi,

In roottest/root/meta/runnamespace.C, a namespace is declared in an ACLiC library and then a using statement is done for this namespace.

At the moment this does not provoke any auto parsing of the header (and/or all the headers) declaring the content of the namespace.  (In addition a direct call to gInterpreter->AutoParse(namespace_name) as no effect).

Cheers,
Philippe.

PS. Because of the potential-spread-over-multiple-header-files-and-library nature of namespace this test may actually be a concrete example of the weakness of the current auto parsing implementation.

### Reproducer

As per the description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by hahnjo** [comment]
@dpiparo can you link the PR? I couldn't find it, probably missed it somewhere...

**Comment by dpiparo** [comment]
Here: sorry https://github.com/root-project/roottest/pull/1057
