### ISSUE TITLE
[ROOT-5572] Handling of '.?' in TRegexp

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14585]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-5572

The handling of '.?' with the TRegexp class seems to be broken. Consider the following examples:

Two TStrings:
TString abc("abc")
TString ac("ac")

Using the regular expression '.?' I get the following output
abc.Contains(TRegexp("a.?c")) -> true
ac.Contains(TRegexp("a.?c")) -> false

while in the later case I would also expect true. Note that I obtain the result I would expect for the regular expression 'ab?c', so there seems to be something wrong only for the optional match to any character.

### Reproducer

As per the description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by ferdymercury** [comment]
Maybe it's not broken, but rather badly documented feature (and weird convention):

```
abc.Contains(TRegexp("a?c")) -> true
ac.Contains(TRegexp("a?c")) -> true
```

It's only explained in TRegExp::MakeWildcard:

`When using wildcards the regular expression is assumed to be preceded by a "^" (BOL) and terminated by a "$" (EOL). Also, all "*"'s and "?"'s (closures) are assumed to be preceded by a "." (i.e. any character, except "/"'s) and all .'s are escaped (so *.ps is different from *.eps). The special treatment of "/" allows the easy matching of pathnames, e.g. "*.root" will match "aap.root", but not "pipo/aap.root". `

I think TPRegexp (vs TRegexp) is working more like the traditional regexp.
