### ISSUE TITLE
Error value and context of call to FT_Set_Char_Size in TTF::SetTextSize should be in error message

### ISSUE THREAD

**Issue by PALoizeau** [root-project/root#14592]
**Context:**
I am working in CBM at GSI/FAIR and helping for the support of our CBMROOT CI chains.
One of our nodes was updated to Debian 12 and then had hundreds of errors in the logs of a test running without trouble on other nodes.
All errors are an identical `Error in <TTF::SetTextSize>: error in FT_Set_Char_Size`, which comes from [TTF.cxx l.574, in `TTF::SetTextSize`](https://github.com/root-project/root/blob/c6f4076e69beaa6283d520c365831dfb0149d083/graf2d/graf/src/TTF.cxx#L574)

**Problem:**
The error message helps neither
- to find out the call origin 
- to identify the root cause
- to fix the problem

as it provides 
1. neither the parameters used in the top call 
2. nor the actual error code returned by the underlying TTF library.

**Proposed solution:** 
(inspired by a quick look at handling in `graf3d/ftgl/[inc src]/FTSize.[h cxx] `)
```diff
diff --git a/graf2d/graf/src/TTF.cxx b/graf2d/graf/src/TTF.cxx
index b8acf771d9..2f844b98da 100644
--- a/graf2d/graf/src/TTF.cxx
+++ b/graf2d/graf/src/TTF.cxx
@@ -570,8 +570,9 @@ void TTF::SetTextSize(Float_t textsize)
    }
 
    Int_t tsize = (Int_t)(textsize*kScale+0.5) << 6;
-   if (FT_Set_Char_Size(fgFace[fgCurFontIdx], tsize, tsize, 72, 72))
-      Error("TTF::SetTextSize", "error in FT_Set_Char_Size");
+   FT_Error err = FT_Set_Char_Size(fgFace[fgCurFontIdx], tsize, tsize, 72, 72);
+   if (err)
+      Error("TTF::SetTextSize", "error in FT_Set_Char_Size: %d (input size %f, calc. size %x)", err, textsize, tsize);
 }
 
 ////////////////////////////////////////////////////////////////////////////////
```

Patch tested locally based on ROOT v6.26.10 under Debian 12 (as far as I can tell this part of the file was not changed since the initial commit so the ROOT version should not matter).
The one thing where I am unsure is whether the calculated size (`tsize`) should be printed in hexadecimal (as it is offseted by multiple bits) or as standard integer.

**Effect:**
In our case it allowed to find out that the automatic calculation of the TextSize value provided to the call was getting haywire due to a too small canvas (1x1 pixel), leading to large or negative values for `tsize`, maybe due to slightly different floating point calculations in Debian12

### ROOT version

At least `v6.22` to `v6.26.10` but corresponding block seems unchanged since the initial commit in 2003, local compilation test on `master` worked

### Installation method

Build from Source within FairSoft (v6.22 and v6.26), Build from source standalone (master)

### Operating system

Debian12, Ubuntu 20.04, Ubuntu 22.04

**Comment by couet** [comment]
Thanks for this detailed report!  I do not really understand how your "proposed solution" is different from what we had before. It looks like you only changed the way the error message is printed. Maybe I missed something...

**Comment by PALoizeau** [comment]
Indeed, this solution only improves the error message to solve the problem of 
1. losing the information of the error reported by the `TTF` library function
2. not knowing the context of the call (input values

In our case it was enough additional information to identify the origin of the error as being a bad input value and exclude troubles  at the `libTTF` packages level such as missing package(s) or mismatching versions (or also in the `tsize` calculation or in `libTTF`, but these were anyway unlikely given the 20+ years of usage)

It would probably be helpful to have in addition some info on the call stack, but I do not know enough of `ROOT` core methods to propose anything there.
As I could track the source of the bad values in our code with the old-school "add temp printouts around calls from top to bottom" method, I must confess I stopped my investigation here :sweat_smile:

**Comment by couet** [comment]
Thanks for the clarification. As you already have some proposed fixes, maybe you can do a PR so you will be properly quoted as having found and improved this issue.

**Comment by PALoizeau** [comment]
I did the PR and took the opportunity to fix a typo I had forgotten to take over from my test machine: the TTF docs use hexadecimal for their error code tables, so I match it in the printout.
