### ISSUE TITLE
The example th2polyUSA.C needs re-labelling

### ISSUE THREAD

**Issue by couet** [root-project/root#14599]
### Explain what you would like to see improved and how.

In https://root.cern/doc/master/th2polyUSA_8C.html (and example 50 in stressGraphics), the map is missing Hawaii and Alaska now that I look at the plot closely... We should also specify a year or update the population numbers (and fix a year)...

It turns out that we can elegantly call this map "Lower 48" (https://en.wikipedia.org/wiki/Contiguous_United_States) then we can figure out the year for completeness.

**Comment by ferdymercury** [comment]
It seems to be July 1st, 2009:

http://eadiv.state.wy.us/pop/st-09est.htm

**Comment by dpiparo** [comment]
PR on its way https://github.com/root-project/root/pull/14665
