### ISSUE TITLE
A "printf" change the behaviour of a macro ... 

### ISSUE THREAD

**Issue by couet** [root-project/root#14598]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

I was investigating why test number 50 of stressGraphics is failing when stressGraphics is run in interpreted mode on Mac.
In compiled mode mode it runs just fine.

I have extracted the failing test and made the following macro:

### Reproducer

```
void sg50b() {
   Int_t i;
   const Int_t nx = 48;
   const char *states [nx] = {
      "alabama",      "arizona",        "arkansas",       "california",
      "colorado",     "connecticut",    "delaware",       "florida",
      "georgia",      "idaho",          "illinois",       "indiana",
      "iowa",         "kansas",         "kentucky",       "louisiana",
      "maine",        "maryland",       "massachusetts",  "michigan",
      "minnesota",    "mississippi",    "missouri",       "montana",
      "nebraska",     "nevada",         "new_hampshire",  "new_jersey",
      "new_mexico",   "new_york",       "north_carolina", "north_dakota",
      "ohio",         "oklahoma",       "oregon",         "pennsylvania",
      "rhode_island", "south_carolina", "south_dakota",   "tennessee",
      "texas",        "utah",           "vermont",        "virginia",
      "washington",   "west_virginia",  "wisconsin",      "wyoming"
   };
   Double_t pop[nx] = {
    4708708, 6595778,  2889450, 36961664, 5024748,  3518288,  885122, 18537969,
    9829211, 1545801, 12910409,  6423113, 3007856,  2818747, 4314113,  4492076,
    1318301, 5699478,  6593587,  9969727, 5266214,  2951996, 5987580,   974989,
    1796619, 2643085,  1324575,  8707739, 2009671, 19541453, 9380884,   646844,
   11542645, 3687050,  3825657, 12604767, 1053209,  4561242,  812383,  6296254,
   24782302, 2784572,   621760,  7882590, 6664195,  1819777, 5654774,   544270
   };

   Double_t lon1 = -130;
   Double_t lon2 = -65;
   Double_t lat1 = 24;
   Double_t lat2 = 50;
   TH2Poly *p = new TH2Poly("USA","USA Population",lon1,lon2,lat1,lat2);
   gErrorIgnoreLevel = 9999;
   TFile::SetCacheFileDir(".");
   TFile *f = TFile::Open("http://root.cern/files/usa.root", "CACHEREAD");

   if (!f) {
      printf("Cannot access usa.root. Is internet working ?\n");
      return;
   }

   // Define the TH2Poly bins.
   TMultiGraph *mg;
   TKey *key;
   TIter nextkey(gDirectory->GetListOfKeys());
   while ((key = (TKey*)nextkey())) {
      TObject *obj = key->ReadObj();
      if (obj->InheritsFrom("TMultiGraph")) {
         mg = (TMultiGraph*)obj;
         p->AddBin(mg);
      }
   }

   // Fill TH2Poly.
   printf("nx = %d\n",nx);
   for (i=0; i<nx; i++) {
      printf("%s %f\n",states[i], pop[i]); // commenting this line make it fail
      p->Fill(states[i], pop[i]);
   }

   gStyle->SetOptStat(11);
   p->DrawClone("COL");
}
```

When the macro is run in compiled mode it is fine. The histogram has 48 entries.

```
root sg50b.C++
```

When it is run in interpreted mode it is fine if we keep the `printf` in the filling loop but it is failing if we comment it.
In that case only one bin is filled. The number of entries is 1 instead of 48.

### ROOT version

Master

### Operating system

MacOS - Intel Processor

**Comment by dpiparo** [comment]
The map is missing Hawaii and Alaska now that I look at the plot closely... We should also specify a year or update the population numbers (and fix a year)...

**Comment by couet** [comment]
ok .. that's an old test, it is like that for years and helps to check the stability of ROOT. We can make it better in the future, but now there is a cling issue with it it seems.....

**Comment by dpiparo** [comment]
It turns out that we can elegantly call this map "Lower 48" (https://en.wikipedia.org/wiki/Contiguous_United_States) then we can figure out the year for completeness

**Comment by couet** [comment]
May be easy enough for the fixathon ?

**Comment by dpiparo** [comment]
for the re-labelling yes, but for the failure of interpreted code on macos x86 not really (if that's the issue)

**Comment by hahnjo** [comment]
I can reproduce the different behavior when commenting out the `printf` on `macphsft21`. This is caused by https://github.com/root-project/root/pull/14267 (which is also the result of bisecting the original test failure of `stressgraphics-interpreted`). Setting `EXTRA_CLING_ARGS="-O0"` fixes the problem.

**Comment by devajithvs** [comment]
I can look into this. But I don't have access to an intel mac machine to reproduce this issue.

**Comment by hahnjo** [comment]
Final observations before I hand over to Dev:
 * printing just the iteration number shows that the code is properly executed
 * AFAICT it suffices to print the state so that all bins are actually filled
 * printing the passed name in `TH2Poly::Fill` shows that `alabama` is correctly passed, but the ones after are some random memory locations with invalid data, and definitely not the other states.

**Comment by devajithvs** [comment]
I found the issue; it's the RelLookupTableConverterPass that was causing the issue.

Before the passmanager update, the function `populateModulePassManager` was called instead of `buildPerModuleDefaultPipeline` to set the default passes. But the former did not have `RelLookupTableConverterPass` turned on by default.

Here's a fix by explicitly disabling `RelLookupTableConverterPass`:

```diff
diff --git a/interpreter/cling/lib/Interpreter/BackendPasses.cpp b/interpreter/cling/lib/Interpreter/BackendPasses.cpp
index 2f8249e132..67da4cc55e 100644
--- a/interpreter/cling/lib/Interpreter/BackendPasses.cpp
+++ b/interpreter/cling/lib/Interpreter/BackendPasses.cpp
@@ -378,6 +378,7 @@ void BackendPasses::CreatePasses(int OptLevel, llvm::ModulePassManager& MPM,
           P.equals("ModuleInlinerPass") || P.equals("InlinerPass") ||
           P.equals("InlineAdvisorAnalysis") ||
           P.equals("PartiallyInlineLibCallsPass") ||
+          P.equals("RelLookupTableConverterPass") ||
           P.equals("InlineCostAnnotationPrinterPass") ||
           P.equals("InlineSizeEstimatorAnalysisPrinterPass") ||
           P.equals("InlineSizeEstimatorAnalysis"))
@@ -385,6 +386,11 @@ void BackendPasses::CreatePasses(int OptLevel, llvm::ModulePassManager& MPM,
 
       return true;
     });
+  } else {
+    // Register a callback for disabling RelLookupTableConverterPass.
+    PIC.registerShouldRunOptionalPassCallback([](StringRef P, Any) {
+      return !P.equals("RelLookupTableConverterPass")
+    });
   }
```


When `CodeModel::Small` is set, `RelLookupTableConverterPass` was running as the target now supports relative lookup tables. When it is not set (fix suggested by Jonas), relative lookup tables are unsupported by default and not run.

I'm happy to open a PR with either of the fixes.

**Comment by hahnjo** [comment]
Short summary from our quick chat: We will go ahead and disable that pass (patch above) as it wasn't run before and it's causing issues. We need to investigate what causes that and report upstream or find a patch that fixes it.

Fun fact: We also understood why the `printf` "solved" the problem; a comment in the pass says "If lookup table has more than one user, do not generate a relative lookup table." So basically *any* second usage of `states[i]` would have cured the problem, for example just calling `p->Fill(states[i], pop[i]);` twice :facepalm: (yes, I tested)
