### ISSUE TITLE
THStack draws first histogram transparently if filled with white and noclear option used

### ISSUE THREAD

**Issue by will-cern** [root-project/root#14605]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Histogram is not shaded properly if first histogram is filled with white and stack is drawn with `noclear` option.

### Reproducer

```
TH1D h1("h","h",1,0,1); 
TH1D h2("h2","h2",1,0,1); 
h1.SetBinContent(1,4); h2.SetBinContent(1,6); 
h1.SetFillColor(kWhite);h2.SetFillColor(kRed); 
THStack hs; hs.Add(&h1); hs.Add(&h2); 
hs.Draw("noclear"); // drawing without noclear works, as will if bottom hist color is not white
```

### ROOT version

6.30

### Installation method

source

### Operating system

all

**Comment by couet** [comment]
Looking at it

**Comment by couet** [comment]
I think it behaves just as expected:

NOCLEAR By default the background of the histograms is erased before drawing the histograms. The option "noclear" avoids this behavior. This is useful when drawing a [THStack](https://root.cern/doc/master/classTHStack.html) on top of another plot. If the patterns used to draw the histograms in the stack are transparent, then the plot behind will be visible.

**Comment by will-cern** [comment]
But none of the histograms have transparent fills. This is a solid fill with the white color. It seems like ROOT is mistakenly interpreting that specific fill color on the first histogram as if the histogram should be drawn transparently. 
<img width="626" alt="Screenshot 2024-02-07 at 10 31 35" src="https://github.com/root-project/root/assets/18280829/dc8f48f0-c092-408d-a724-768334009ca5">
This is picture of it drawing incorrectly using the reproducer .... the bottom histogram should be filled white, right?

**Comment by couet** [comment]
What the help is: 

When the stack is drawn each histogram is painted twice: 

- First in the background color (most of the time white) to erase what is behind the histogram 
- and a 2nd time with the fill style and color of the histogram (in your case solid).  

But sometimes one wants to skip the first painting in the background color and do only the 2nd step. That is triggered with the option `noclear`. **That can be useful when the fill style of the histogram is hatched for instance**. 

Why do you want to have this option `noclear`? it makes no sense if your histogram fill style is solid.
What is your use case? do you have an example?

**Comment by will-cern** [comment]
This is in some generic code that is assembling a stack of histograms that are styled according to a user's preferences, so I wanted to use "noclear" so that the stack is see-through if the user opts for fill styles that are partially transparent, like hatching as you say. "noclear" felt like the most appropriate generic option to go for in my application.

I still maintain the behaviour is not consistent with what is written in the help - the first histogram is a solid white fill. If I draw that with "noclear" it should still be drawn as solid white color, right?

**Comment by couet** [comment]
Yes, white is a special case. If you use green it behaves as you expect. I will check if something can be done.

**Comment by couet** [comment]
Indeed that's not an issue with THStack. It comes from the fact kWhite = 0 and, since the very beginning of ROOT, a fill color equal to 0 meant "not filled"... I know it is bad but that's just like that for 30 years. You can see what I mean with the following example.
```
{
   auto h1 = new TH1D("h1","h1",10,0,11);
   auto h2 = new TH1D("h2","h2",10,0,11);
   auto h3 = new TH1D("h3","h3",10,0,11);
   h1->SetBinContent(2,1);
   h2->SetBinContent(4,1);
   h3->SetBinContent(6,1);
   
   h1->SetFillColor(kWhite);
   h2->SetFillColor(kRed);
   h3->SetFillColor(kGreen);
   
   auto c = new TCanvas();
   c->SetFillColor(30);
   c->DrawFrame(0., 0.,11.,1.5);
   h1->Draw("SAME");
   h2->Draw("SAME");
   h3->Draw("SAME");
}
```
The workaround in your case will be to define a white color not attached to index 0. Like:

```
 {
   auto h1 = new TH1D("h","h",1,0,1);
   auto h2 = new TH1D("h2","h2",1,0,1);
   h1->SetBinContent(1,4);
   h2->SetBinContent(1,6);

   int kWhite2 = 345;
   TColor *color = new TColor(kWhite2, 1., 1., 1.);

   h1->SetFillColor(kWhite2);
   h2->SetFillColor(kRed);
   auto hs = new THStack();
   hs->Add(h1);
   hs->Add(h2);
   hs->Draw("noclear");
}
```

**Comment by couet** [comment]
Actually such color exists, it is number 10 (it does not have a name defined in `core/base/inc/Rtypes.h`):
```
{
   auto h1 = new TH1D("h","h",1,0,1);
   auto h2 = new TH1D("h2","h2",1,0,1);
   h1->SetBinContent(1,4);
   h2->SetBinContent(1,6);
   h1->SetFillColor(10);
   h2->SetFillColor(kRed);
   auto hs = new THStack();
   hs->Add(h1);
   hs->Add(h2);
   hs->Draw("noclear");
}
```

**Comment by dpiparo** [comment]
Hi @couet . Is this an issue we fixed in the master/6.32 or do we still need to address something?

**Comment by will-cern** [comment]
I think the issue can be closed. The outcome from our user side is they need to use "10" rather than "kWhite" when they actually want white fill color. 
I guess I could ask the question "how bad would it be if we re-assigned kWhite to 10 rather than 0?" but I'm not gonna press for it.

**Comment by couet** [comment]
@will-cern ok I close it. Thanks
