### ISSUE TITLE
RNTuple collection writer only works in sequential writing with one REntry

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#14642]
Consider this basic example of using the RNTuple collection writer:
```c++
#include <ROOT/REntry.hxx>
#include <ROOT/RNTuple.hxx>
#include <ROOT/RNTupleModel.hxx>

using ROOT::Experimental::REntry;
using ROOT::Experimental::RNTupleModel;
using ROOT::Experimental::RNTupleReader;
using ROOT::Experimental::RNTupleWriter;

static void write() {
  auto particleModel = RNTupleModel::Create();
  auto energy = particleModel->MakeField<float>("energy");

  auto model = RNTupleModel::Create();
  auto particles = model->MakeCollection("particles", std::move(particleModel));

  auto writer = RNTupleWriter::Recreate(std::move(model), "events", "collection_entry.root");

  *energy = 1.0;
  particles->Fill();
  writer->Fill();
}

void collection_entry_default() {
  write();

  auto reader = RNTupleReader::Open("events", "collection_entry.root");
  reader->Show(0);
}

int main() {
  collection_entry_default();
  return 0;
}
```

This works reasonably as expected, with the following output:
```
{
  "particles": [{"energy": 1}]
}
```

However, a user may want to create non-default entries, ie `auto entry = writer->CreateEntry();` and then calling `writer->Fill(*entry);`.

<details>
<summary>Full code example</summary>

```c++
#include <ROOT/REntry.hxx>
#include <ROOT/RNTuple.hxx>
#include <ROOT/RNTupleModel.hxx>

using ROOT::Experimental::REntry;
using ROOT::Experimental::RNTupleModel;
using ROOT::Experimental::RNTupleReader;
using ROOT::Experimental::RNTupleWriter;

static void write() {
  auto particleModel = RNTupleModel::Create();
  auto energy = particleModel->MakeField<float>("energy");

  auto model = RNTupleModel::CreateBare();
  auto particles = model->MakeCollection("particles", std::move(particleModel));

  auto writer = RNTupleWriter::Recreate(std::move(model), "events", "collection_entry.root");
  auto entry = writer->CreateEntry();

  *energy = 1.0;
  particles->Fill();
  writer->Fill(*entry);
}

void collection_entry() {
  write();

  auto reader = RNTupleReader::Open("events", "collection_entry.root");
  reader->Show(0);
}

int main() {
  collection_entry();
  return 0;
}
```

</details>

This doesn't work right now, even for a single entry as in the code example above; when opening the ntuple, the code crashes:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

This is because `RNTupleModel::CreateEntry()` calls
https://github.com/root-project/root/blob/d52f98f56341edaa43bf03c16d218176afc5a17b/tree/ntuple/v7/src/RNTupleModel.cxx#L363-L365
for all top-level field. Conceptually it's possible to fix by applying the same logic as `RNTupleModel::MakeCollection`, something like
```diff
diff --git a/tree/ntuple/v7/src/RNTupleModel.cxx b/tree/ntuple/v7/src/RNTupleModel.cxx
index c652608bf1..ed02338e2b 100644
--- a/tree/ntuple/v7/src/RNTupleModel.cxx
+++ b/tree/ntuple/v7/src/RNTupleModel.cxx
@@ -347,7 +347,11 @@ std::unique_ptr<ROOT::Experimental::REntry> ROOT::Experimental::RNTupleModel::Cr
 
    auto entry = std::unique_ptr<REntry>(new REntry(fModelId));
    for (const auto &f : fFieldZero->GetSubFields()) {
-      entry->AddValue(f->CreateValue());
+      if (auto *collectionField = dynamic_cast<RCollectionField *>(f)) {
+         entry->AddValue(f->BindValue(std::shared_ptr<void>(collectionField->fCollectionWriter->GetOffsetPtr(), [](void *) {})));
+      } else {
+         entry->AddValue(f->CreateValue());
+      }
    }
    return entry;
 }
```
This makes the example work with a single non-default `REntry`, but highlights another problem: There is a 1:1 association of the `RCollectionNTupleWriter` to the `RCollectionField`, which prevents multiple `REntry`'s from working:
<details>
<summary>Full code example</summary>

```c++
#include <ROOT/REntry.hxx>
#include <ROOT/RNTuple.hxx>
#include <ROOT/RNTupleModel.hxx>

using ROOT::Experimental::REntry;
using ROOT::Experimental::RNTupleModel;
using ROOT::Experimental::RNTupleReader;
using ROOT::Experimental::RNTupleWriter;

static void write() {
  auto particleModel = RNTupleModel::CreateBare();
  particleModel->MakeField<float>("energy");

  particleModel->Freeze();
  auto particleEntry1 = particleModel->CreateEntry();
  auto energy1 = particleEntry1->GetPtr<float>("energy");
  auto particleEntry2 = particleModel->CreateEntry();
  auto energy2 = particleEntry2->GetPtr<float>("energy");

  auto model = RNTupleModel::CreateBare();
  auto particles = model->MakeCollection("particles", std::move(particleModel));

  auto writer = RNTupleWriter::Recreate(std::move(model), "events", "collection_entry.root");
  auto entry1 = writer->CreateEntry();
  auto entry2 = writer->CreateEntry();

  *energy1 = 1.0;
  particles->Fill(*particleEntry1);

  *energy2 = 1.0;
  particles->Fill(*particleEntry2);

  *energy2 = 2.0;
  particles->Fill(*particleEntry2);

  *energy2 = 3.0;
  particles->Fill(*particleEntry2);

  *energy1 = 2.0;
  particles->Fill(*particleEntry1);

  writer->Fill(*entry2);

  *energy1 = 3.0;
  particles->Fill(*particleEntry1);

  writer->Fill(*entry1);
}

void collection_entry_multiple() {
  write();

  auto reader = RNTupleReader::Open("events", "collection_entry.root");
  reader->Show(0);
  reader->Show(1);
}

int main() {
  collection_entry_multiple();
  return 0;
}
```
</details>
yields

```
{
  "particles": [{"energy": 1}, {"energy": 1}, {"energy": 2}, {"energy": 3}, {"energy": 2}]
}
{
  "particles": [{"energy": 3}]
}
```
while the expected output would be `[{"energy": 1}, {"energy": 2}, {"energy": 3}]` twice.

Moreover, thinking about parallel writing, there will be an additional complication: `RCollectionField::CloneImpl` doesn't clone the `fCollectionWriter`, so there is only a single instance across all cloned models:
https://github.com/root-project/root/blob/d52f98f56341edaa43bf03c16d218176afc5a17b/tree/ntuple/v7/src/RField.cxx#L3301

Again, this could be solved conceptually by remembering the original `collectionModel` passed to `RNTupleModel::MakeCollection` and deep-cloning the collection writer (modulo it still being associated to an `RField` instead of an `REntry`), but this imposes another problem: The user would have to get the cloned collection writer out of the cloned `RCollectionField` and create entries for its `collectionModel`. Even right now, the latter is only possible before passing the model to `MakeCollection`.

**Comment by jblomer** [comment]
As discussed, it will be more difficult than #16356 to correctly implement the (recursive) collection writer, and probably require the use of a specialized sink where the writer writes to.

Let's try a different approach:
- We map the leaf lists to a list of `std::vector`. Same page merging, in the vast majority of cases, will make sure that the on-disk size is comparable to the current importer result
- We drop the collection writer / collection field altogether.
