### ISSUE TITLE
[geompainter] Overlap threshold not used in TGeoChecker::CheckOverlapsBySampling (sampling mode of TGeoManager::CheckOverlaps)

### ISSUE THREAD

**Issue by PALoizeau** [root-project/root#14675]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

In the [documentation of `TGeoManager::CheckOverlaps`](https://root.cern.ch/doc/master/classTGeoManager.html#afa2bfedf7f02398fdf5867072a77a884) the first parameter `ovlp` is described as a limit for the overlap size (which we understand to be the minimal size before considering it as illegal and triggering the error).
This method lead through chained calls to either  `TGeoChecker::MakeCheckOverlap` (standard surface/edge/point check) or `TGeoChecker::CheckOverlapsBySampling` (sampling check):
```
TGeoManager::CheckOverlaps => TNode::CheckOverlaps => TGeoVolume::CheckOverlaps => TGeoPainter::CheckOverlaps => TGeoChecker::CheckOverlaps | => TGeoChecker::MakeCheckOverlap
                                                                                                                                            | => TGeoChecker::CheckOverlapsBySampling
```

However [the line using this parameter in the sampling case (l.1271) is commented out](https://github.com/root-project/root/blame/master/geom/geompainter/src/TGeoChecker.cxx#L1271).
It was commented in https://github.com/root-project/root/commit/406af49ee13e135d7c2f1268370ea83e0a99c729 and the commit message does not mention this change explicitly (maybe a consequence of the introduction of the usage of `Voxels`?).

The [corresponding line for the non-sampling method is in `TGeoChecker::MakeCheckOverlap` (l.1173) and not commented out](https://github.com/root-project/root/blame/master/geom/geompainter/src/TGeoChecker.cxx#L1173), which would indicate that the intended original usage is still valid.

We (CBMROOT) stumbled upon this as we started to find for some of our geometries overlaps with total integrated volume in the order of `10^-6 to 10^-10 cm3` when changing the sampling points number. We first started by adding exceptions in our CI but the list quickly grew as the sampling position is different with each change in the fully assembled geometry volume.
Having/restoring the possibility to ignore the "really small" overlaps would cure our problem with a single parameter

Proposed solutions:
- either un-comment the line to re-enable the threshold if it is not bringing other bugs (see simple patch in **Reproducer**).
  => This seems to work for me locally with a fresh copy of the master under Ubuntu 20.04
- or at least update the documentation to indicate that the parameter `ovlp` is used only in standard mode and ignored in sampling mode

--------------------------------
Potential related bug: some of these really small overlaps appear only when the number of samples is increased but disappear if it is further increased.
However for a given number the list of overlaps is stabled over re-running the macro (new ROOT session at each time).
The new overlaps also appear mostly in the "last volumes in the geometry" to be tested.
So it could be that something is not so stable in the sequence of random points:
- first volume getting always mostly the same points independent of the number of samples 
- while last volume getting set of points depending highly on number of samples

I did not manage to reliably reproduce it however so I would create a separate issue if I find the time to test and confirm it later.

### Reproducer

Files in archive: examine_mcbm_beam_2019_03.geo.root, check_overlaps.C, root_overlaps_samp_thr.patch
[check_overlaps.tar.gz](https://github.com/root-project/root/files/14261529/check_overlaps.tar.gz)

1. Run once the macro with master: some big overlaps, some known overlaps of size ~0.4, some overlap of size ~10^-8 only if higher number of samples provided, overlap threshold does not have an effect in sampling mode calls

2. Apply following patch
```diff
diff --git a/geom/geompainter/src/TGeoChecker.cxx b/geom/geompainter/src/TGeoChecker.cxx
index fc93cc8b82..0e77517729 100644
--- a/geom/geompainter/src/TGeoChecker.cxx
+++ b/geom/geompainter/src/TGeoChecker.cxx
@@ -1193,7 +1193,7 @@ TGeoOverlap *TGeoChecker::MakeCheckOverlap(const char *name, TGeoVolume *vol1, T
 /// Check illegal overlaps for volume VOL within a limit OVLP by sampling npoints
 /// inside the volume shape.

-void TGeoChecker::CheckOverlapsBySampling(TGeoVolume *vol, Double_t /* ovlp */, Int_t npoints) const
+void TGeoChecker::CheckOverlapsBySampling(TGeoVolume *vol, Double_t ovlp, Int_t npoints) const
 {
    Int_t nd = vol->GetNdaughters();
    if (nd < 2)
@@ -1268,7 +1268,7 @@ void TGeoChecker::CheckOverlapsBySampling(TGeoVolume *vol, Double_t /* ovlp */,
          }
          // The point is inside 2 or more daughters, check safety
          safe = shape->Safety(local, kTRUE);
-         //         if (safe < ovlp) continue;
+         if (safe < ovlp) continue;
          // We really have found an overlap -> store the point in a container
          iovlp++;
          if (!novlps) {
```

3. Recompile/Reinstall and Re-run: big overlaps unchanged as expected, known overlaps of size ~0.4 still there with low threshold but masked with sufficient threshold, overlap of size ~10^-8 cut in all cases as expected

### ROOT version

Original observation with `v6.22` to `v6.26`
Cross-check with current master, given source commit probably present from `v5-19-04` until current master

### Installation method

Built from source within Fairsoft, built from source standalone

### Operating system

Ubuntu 20.04, Debian 10 and 11

**Comment by agheata** [comment]
OK, I un-commented the safety check, I don't remember the reason why I disabled it in the first place. Please open a separate issue if needed with a macro to test for the random sequence. In principle, `gRandom->Rndm()` is used for sampling, which should produce the same sequence if not seeded elsewhere.

**Comment by PALoizeau** [comment]
> OK, I un-commented the safety check, I don't remember the reason why I disabled it in the first place.

Thanks for this

> Please open a separate issue if needed with a macro to test for the random sequence. In principle, `gRandom->Rndm()` is used for sampling, which should produce the same sequence if not seeded elsewhere.

Will do. This is low priority for us as we found some workaround in our test-chain, but the issue is kept open in our tracker with a long timeline and assigned to me, so probably the kind we dig out during the summer activity dip
