### ISSUE TITLE
Canvas is not displayed on secondary cell executions if `Print` method is used

### ISSUE THREAD

**Issue by dreykiman** [root-project/root#14689]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

TCanvas is not displayed in Jupyter notebook on secondary cell executions **if `Print` method is used in the cell**.

| **First time cell execution** | **Secondary cell executions (note the order execution number)**|
|-------------|--------------------
|![image](https://github.com/root-project/root/assets/44311461/1be434e1-f316-4045-8994-4c20138a1d09)|![image](https://github.com/root-project/root/assets/44311461/b7ea39c0-12b9-48df-ab34-af17c4a47491)|

See discussion here: https://github.com/root-project/root/issues/13631#issuecomment-1941706841

### Reproducer

```
c1 = ROOT.TCanvas("c1","c1",600,400)
c1.Draw()

h1 = ROOT.TH1F("h1","h1",100,-10,10)
h1.FillRandom("gaus",1000)

c1.Print("test.pdf")
```

### ROOT version

6.30/02

### Installation method

Arch linux package manager

### Operating system

Linux

**Comment by linev** [comment]
I cannot reproduce problem. Maybe @vepadulano can check.

To get proper drawing, one should do:
```

h1 = ROOT.TH1F("h1","h1",100,-10,10)
h1.FillRandom("gaus",1000)

c1 = ROOT.TCanvas("c1","c1",600,400)
h1.Draw()
c1.Draw()

c1.Print("test.pdf")
```

**Comment by linev** [comment]
I guess, one can close problem.
`%reset -f` does not cleanup ROOT, all histograms and canvases remains.
If executing correct macro again, one just get warnings about canvas with same name, but drawing works as expected.

**Comment by linev** [comment]
Issue with drawing new canvas with same name probably was resolved by https://github.com/root-project/root/pull/15943
