### ISSUE TITLE
`std::set` not working in Windows PyROOT

### ISSUE THREAD

**Issue by lobis** [root-project/root#14710]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

During https://github.com/root-project/root/pull/14669 a new test was added which tests `std::set` in PyROOT. This exposed an issue where creating a set in PyROOT on the windows builds fails.

A conditional windows test skip was added in `bindings/pyroot/pythonizations/test/CMakeLists.txt` to fix this (where the `stl_set.py` is added).

Whenever this issue is resolved this test skip should also be removed.

- [ ] Remove windows test skip for `stl_set.py`.

### Reproducer

`s = ROOT.std.set['int']()` (in windows).

### ROOT version

 6.31/01 (dev)

### Installation method

Build from source

### Operating system

Windows

**Comment by guitargeek** [comment]
Note this still doesn't work after yesterdays cppyy upgrade:
```txt
C:\root-dev\build\x64\debug>python
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> s = ROOT.std.set['int']()
Assertion failed: Loc.isValid() && "point of instantiation must be valid!", file C:\root-dev\git\master\interpreter\llvm-project\clang\include\clang/AST/DeclTemplate.h, line 2010
 *** Break *** abort
```
