### ISSUE TITLE
[cling] Undocumented behaviour of root macro_C.so

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#14772]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

It is not clear what `root macro_C.so` does.

It should be documented in these places:
- [x] https://github.com/root-project/web/blob/main/manual/root_macros_and_shared_libraries/index.md
- [x] https://github.com/root-project/web/blob/main/manual/first_steps_with_root/index.md
- [x] https://github.com/root-project/web/blob/main/manual/cling/index.md
- [x] https://github.com/root-project/root/blob/master/interpreter/cling/lib/MetaProcessor/MetaSema.cpp
- [x] core/base/src/root-argparse.py
- [x] TApplication.cxx if there is a custom change wrt cling

It's not clear if the call should also auto-run the macro or not like .x
Maybe it's an old remnant of CINT. Or maybe it should run it and right now there is a bug and it does not.

The only documented place seems to be: page 27 [of this document](https://root.cern.ch/root/htmldoc/guides/users-guide/ROOTUsersGuideA4.pdf) and it's not working on master.

### Reproducer

https://root-forum.cern.ch/t/cannot-run-shared-object-in-batch-mode/58213

### ROOT version

```
ROOT v6.30/04
Built for linuxx8664gcc on Jan 31 2024, 10:01:37
From heads/master@tags/v6-30-04
With c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Binary directory: /opt/root/bin
```

### Installation method

Binary Release

### Operating system

Ubuntu 22.04

### Additional context

https://root-forum.cern.ch/t/cannot-run-shared-object-in-batch-mode/58213

**Comment by guitargeek** [comment]
PR merged to master, keeping issue open right now to remind us of 6.32 backport.
