### ISSUE TITLE
[ntuple] Incorrect treatment of unsplittable classes

### ISSUE THREAD

**Issue by jblomer** [root-project/root#14809]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

The `TClass::CanSplit()` information is ignored where it shouldn't. E.g., it could be that the class uses a custom streamer.

### Reproducer

- Write an object to RNTuple that is unsplittable, e.g. `TH1F` (to be refined).

### ROOT version

master

### Installation method

From sources

### Operating system

Linux

### Additional context

Follow-up from https://github.com/root-project/root/pull/14728#discussion_r1489689085

**Comment by jblomer** [comment]
Why was this issue reopened?

**Comment by pcanal** [comment]
It was unclear whether the issue was only "throw when seeing unsplitable class in case split is requested"
 or if it was more "implement support for unsplit class (I.e. treat them properly)".  In the later case at least https://github.com/root-project/root/pull/14728 is needed.
