### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by theayon** [root-project/root#14902]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Can not compile root after xcode update: clang-1500.3.9.4

```
#include <vector>
         ^
Error: Building module 'std_vector' implicitly. If 'std_vector' requires a 
dictionary please specify build dependency: 'G__Core.cxx' depends on 'std_vector'.
Otherwise, specify '-mByproduct std_vector' to disable this diagnostic.
In file included from input_line_7:16:
In file included from /usr/local/root/root_build/include/ROOT/TExecutorCRTP.hxx:15:
In file included from /usr/local/root/root_build/include/ROOT/TSeq.hxx:15:
/usr/local/root/root_build/include/TError.h:37:10: remark: building module 'std_functional' as '/usr/local/root/root_build/lib/std_functional.pcm' [-Rmodule-build]
#include <functional>
         ^
Error: Building module 'std_functional' implicitly. If 'std_functional' requires a 
dictionary please specify build dependency: 'G__Core.cxx' depends on 'std_functional'.
Otherwise, specify '-mByproduct std_functional' to disable this diagnostic.
```

### Reproducer

cmake --build . -- install -j

### ROOT version

v-6-31-01, and also a similar error with the master branch

### Installation method

build from the source

### Operating system

MacOS 14.3.1

**Comment by dpiparo** [comment]
Dear @theayon ,

Thanks for this bug report. I am sorry you are experiencing this problem.

We are aware of this issue and are working on a fix. The current workaround, if that can work for you, is to revert the update, until the fix is merged in the repository. Or, and this is a really a kludge, you could try to configure ROOT without modules.

**Comment by theayon** [comment]
Dear @dpiparo 

Thank you for addressing the issue. I try the workaround in the meantime.

**Comment by dpiparo** [comment]
Hi @theayon , pinging you directly. Thanks again for this report. As you can see from the link above, thanks to @vgvassilev, we have a solution in the master branch of ROOT.

**Comment by theayon** [comment]
Hi @dpiparo,

Thank you for the update and @vgvassilev for the solution. I will clone and check it now.
