### ISSUE TITLE
ROOT Fails to build macOS 14.4 arm64 Xcode 15.3

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#14921]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

As reported on the [Forum](https://root-forum.cern.ch/t/root-6-30-04-build-failed-on-macos-14-4-arm64-xcode-15-3), ROOT does not compile any more on macos after the last update of version 14.
This due to a change in the way the module map for libstdc++ is organised, i.e. with many small modules instead of one big stl module.

### Reproducer

Try to build ROOT on macos >14.3

### ROOT version

all versions that support the usage of modules.

### Installation method

from sources

### Operating system

MacOS

**Comment by pcanal** [comment]
A workaround is to configure without module support: `-Druntime_cxxmodule=OFF`
