### ISSUE TITLE
[ntuple] Document more about how footer extension works

### ISSUE THREAD

**Issue by Moelf** [root-project/root#14949]
### Explain what you would like to see improved and how.

running into a bit of enigma at https://github.com/JuliaHEP/UnROOT.jl/issues/312

for the file at hand, I can see the footer contains extensions, and that the first cluster and second cluster have different number of columns to them. I suspect that I don't fully understand how to "insert" the field and columns descriptions found in footer into the header, thus I'm likely reading mis-matched field / column when I enter the second cluster.

Any additional clarification in the spec regarding how this works would be helpful

### ROOT version

master

### Installation method

nightly from cvmfs

### Operating system

Linux

**Comment by jblomer** [comment]
This may be easier to discuss in the I/O meeting.  AFAICS your comment in the UnROOT ticket is correct: the extension header only adds columns and fields (their IDs are larger than IDs from the real header).

There is information on deferred columns, which come as part of late model extension:
https://github.com/root-project/root/blob/master/tree/ntuple/v7/doc/specifications.md#column-description

And of course the actual extension frame:
https://github.com/root-project/root/blob/master/tree/ntuple/v7/doc/specifications.md#schema-extension-record-frame

**Comment by Moelf** [comment]
Ah, I think in my case I'm not doing anything for the 0x08 flag, and what I'm looking for here is if we can mention this flag in the Schema Extension section

**Comment by Moelf** [comment]
I think that might be red herring:
```julia
# remember Julia is 1-based index
julia> rf.header.field_records[182:201]
20-element Vector{UnROOT.FieldRecord}:
 FieldRecord(parent=181, role=2, name="AntiKt4TruthDressedWZJetsAux:", type="xAOD::JetAuxContainer_v1", repetition=0)
 FieldRecord(parent=181, role=2, name=":_0", type="xAOD::AuxContainerBase", repetition=0)
 FieldRecord(parent=182, role=2, name=":_0", type="SG::IAuxStore", repetition=0)
 FieldRecord(parent=183, role=2, name=":_0", type="SG::IConstAuxStore", repetition=0)
 FieldRecord(parent=182, role=2, name=":_1", type="SG::IAuxStoreIO", repetition=0)
 FieldRecord(parent=182, role=2, name=":_2", type="SG::IAuxStoreHolder", repetition=0)
 FieldRecord(parent=182, role=2, name=":_3", type="ILockable", repetition=0)
 FieldRecord(parent=181, role=1, name="pt", type="std::vector<float>", repetition=0)
 FieldRecord(parent=188, role=0, name="_0", type="float", repetition=0)
 FieldRecord(parent=181, role=1, name="eta", type="std::vector<float>", repetition=0)
 FieldRecord(parent=190, role=0, name="_0", type="float", repetition=0)
 FieldRecord(parent=181, role=1, name="phi", type="std::vector<float>", repetition=0)
 FieldRecord(parent=192, role=0, name="_0", type="float", repetition=0)
 FieldRecord(parent=181, role=1, name="m", type="std::vector<float>", repetition=0)
 FieldRecord(parent=194, role=0, name="_0", type="float", repetition=0)
 FieldRecord(parent=181, role=1, name="constituentLinks", type="std::vector<std::vector<ElementLink<DataVector<xAOD::IParticle> >>>", repetition=0)
 FieldRecord(parent=196, role=1, name="_0", type="std::vector<ElementLink<DataVector<xAOD::IParticle> >>", repetition=0)
 FieldRecord(parent=197, role=2, name="_0", type="ElementLink<DataVector<xAOD::IParticle> >", repetition=0)
 FieldRecord(parent=198, role=2, name=":_0", type="ElementLinkBase", repetition=0)
 FieldRecord(parent=199, role=0, name="m_persKey", type="std::uint32_t", repetition=0)

julia> collect(rnt.var"AntiKt4TruthDressedWZJetsAux:")
field.columnrecord = ColumnRecord(type=0x000e, nbits=64, field_id=188, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x0011, nbits=32, field_id=189, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x000e, nbits=64, field_id=190, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x0011, nbits=32, field_id=191, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x000e, nbits=64, field_id=192, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x0011, nbits=32, field_id=193, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x000e, nbits=64, field_id=194, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x0011, nbits=32, field_id=195, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x000e, nbits=64, field_id=196, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x000e, nbits=64, field_id=197, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x0014, nbits=32, field_id=200, flags=0, first_ele_idx=0)
field.columnrecord = ColumnRecord(type=0x0014, nbits=32, field_id=201, flags=0, first_ele_idx=0)
```

none of the columns touched have `flags=0x08` in this case.

**Comment by Moelf** [comment]
I'm not 100% sure if this is related to `0x08` flags, but I have narrowed down my problem a bit in https://github.com/JuliaHEP/UnROOT.jl/issues/312#issuecomment-1998723832

In summary, by using ROOT, I have confirmed that in the 2nd cluster I'm reading all the correct elements for
```
"AntiKt4TruthDressedWZJetsAux:.constituentLinks.:_0.m_persIndex"
```
Both the content and the number of elements completely agree.

The problem surfaces when I need to put this together with the `offset` vector, since the schema looks like this:
```julia
└─ :constituentLinks ⇒ Vector
                                                                    ├─ :offset ⇒ Leaf{UnROOT.Index64}(col=40)
                                                                    └─ :content ⇒ Vector
                                                                                  ├─ :offset ⇒ Leaf{UnROOT.Index64}(col=41)
                                                                                  └─ :content ⇒ Struct
                                                                                                └─ Symbol(":_0") ⇒ Struct
                                                                                                                   ├─ :m_persKey ⇒ Leaf{UInt32}(col=42) # <--- verified correct
                                                                                                                   └─ :m_persIndex ⇒ Leaf{UInt32}(col=43)
```

in this case, the `offset` is stored in `col=41`, if we look at the page descriptions associated with `col=41` in the 2nd cluster, we see something very surprising:
```julia
# Julia is 1-based index
julia> cluster_group.nested_page_locations[2][42]
8-element UnROOT.RNTupleListNoFrame{UnROOT.PageDescription}:
 PageDescription(num_elements = 0x00004000, Locator(num_bytes=38, offset=0x000000000196af81, ))
 PageDescription(num_elements = 0x00004000, Locator(num_bytes=38, offset=0x0000000001f361e0, ))
 PageDescription(num_elements = 0x00004000, Locator(num_bytes=38, offset=0x00000000024cac93, ))
 PageDescription(num_elements = 0x00004000, Locator(num_bytes=38, offset=0x0000000002ac8a47, ))
 PageDescription(num_elements = 0x00004000, Locator(num_bytes=38, offset=0x00000000030d9f71, ))
 PageDescription(num_elements = 0x00004000, Locator(num_bytes=38, offset=0x00000000036576d6, ))
 PageDescription(num_elements = 0x00004000, Locator(num_bytes=38, offset=0x0000000003c710aa, ))
 PageDescription(num_elements = 0x00003648, Locator(num_bytes=38, offset=0x0000000003f3f9a0, ))
```

you can see that these page locators claim to inflate 29 bytes (38 - 9 due to compression header) into `0x00004000` elements, because these offsets are `Index64`, that is `Int(0x00004000*8) = 131072 > 65536` bytes, which I thought is impossible due to "uncompressed size limit". And in any case, the ZS decompression library used here failed to give me back that many bytes when fed the 29 bytes payload.

Any insight is much appreaciated @jblomer

**Comment by Moelf** [comment]
ok, I have figured it out, it's because of
>0x01 	64 	Index64 	Mother columns of (nested) collections, counting is relative to the cluster
0x02 	32 	Index32 	Mother columns of (nested) collections, counting is relative to the cluster


specifically, "counting is relative to the cluster" was not clear to me. But what it means is, if you have 2 pages of `Index64` for a column in this cluster, after "de-split encoding" you will get these two arrays:

```julia
first page: [30, 4, 18, 14, 5, 8, 10, 7, 8, 18, ..., 22, 1, 16, 14, 14, 12, 4, 7, 15, 24]
first page after cumsum: [..., 81317, 81318, 81334, 81348, 81362, 81374, 81378, 81385, 81400, 81424]

second page: [81428, 13, 9, 7, 5, 20, 21, 4, 8, 6, ..., 128487, 128505, 128513, 128527, 128543, 128549, 128557, 128564, 128575, 128584]
``` 

you can see that the second page doesn't start with 4, instead, it starts with a huge number `81428`. I guess it means index pages are to be interpreted individually within the cluster.
