### ISSUE TITLE
ROOT_HEAD failed with error message: Fail to detect cryptographic random generator

### ISSUE THREAD

**Issue by cogevito** [root-project/root#14958]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

ROOT_HEAD failed in the nightlies in centos7 platfom
The reported error  estracted from the[ log file ](http://cdash.cern.ch/upload/43670d452f7f3ef813ce655ef9357e62800d1e7a/ROOT-HEAD-configure.log)is:
gnu/11.3.0/../../../../include/c++/11.3.0/x86_64-pc-linux-gnu:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos7/bin/../lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../include/c++/11.3.0/backward' at runtime.
-- And then fallback to: 'g++'
-- Performing Test CXX_HAS_fno_rtti
-- Performing Test CXX_HAS_fno_rtti - Success
-- Performing Test found_arc4
-- Performing Test found_arc4 - Failed
-- Performing Test found_arc4_bsd
-- Performing Test found_arc4_bsd - Failed
-- Performing Test found_getrandom
-- Performing Test found_getrandom - Failed
CMake Error at core/unix/CMakeLists.txt:42 (message):
  Fail to detect cryptographic random generator

### Reproducer

[lcg_nightly_pipeline](https://lcgapp-services.cern.ch/spi-jenkins/view/LCG%20Nightlies/job/lcg_nightly_pipeline/)

### ROOT version

master

### Installation method

build from source

### Operating system

centos7

**Comment by dpiparo** [comment]
@cogevito , centos7 EOL is June 30th 2024 (see [here](https://endoflife.software/operating-systems/linux/centos)). What would be the cost/benefit ratio of the fix?

**Comment by linev** [comment]
@cogevito 

For cryptographic random generator we try to use `arc4random_buf` function from `<stdlib.h>` and as fall-back - `getrandom` from `<sys/random.h>`. See here:

https://github.com/root-project/root/blob/master/core/unix/CMakeLists.txt

 Seems to be, none of them presented on CentOS.

Is there `libbsd` on this platform? 
It also can be used to get `arc4random_buf`.

**Comment by linev** [comment]
@cogevito 

Can you try to install `libbsd-dev` on your node?

**Comment by cogevito** [comment]
Hello Sergey,, Danillo

Thank you for your suggestions (that we took into consideration ), feedback and prompt response.

There is a new suggestion on how to solve this issue. Please check:

<https://its.cern.ch/jira/browse/SPI-2532>
its.cern.ch<https://its.cern.ch/jira/browse/SPI-2532>
[X]<https://its.cern.ch/jira/browse/SPI-2532>

We will keep you informed.
Best regards,
Ilias

On 14 Mar 2024, at 09:32, Sergey Linev ***@***.***> wrote:



@cogevito<https://github.com/cogevito>

Can you try to install libbsd-dev on your node?

**Comment by egpbos** [comment]
I just encountered this issue as well on CentOS 7 (main cluster at Nikhef). I will look into the `libbsd-dev` solution mentioned above.

> What would be the cost/benefit ratio of the fix?

There is an upgrade path that will make Alma 9 the default from 15 May and phases out CentOS 7 fully from 30 May, so on first sight not much benefit. However, it is foreseen that some people in the late stages of their research won't be able to upgrade their toolchain before this date and some container-based CentOS 7 support will probably remain for some time. I don't know whether this justifies the cost, of course.

**Comment by linev** [comment]
Can you try https://github.com/root-project/root/pull/15242

Provide -DLIBBSDINCPATH=/custom/path/to/bsd when invoking cmake.

**Comment by egpbos** [comment]
That doesn't seem to work. I tried setting that var to the install prefix (i.e. my home dir) and to the include directory under that prefix.

**Comment by egpbos** [comment]
Oh sorry, I misread! I will try the PR branch now...

**Comment by egpbos** [comment]
Looking at the PR btw I wonder whether it will link. Should the library location also be provided?

**Comment by linev** [comment]
> Should the library location also be provided?

Seems to be function is inlined and therefore linking with libbsd was not necessary up to now.
