### ISSUE TITLE
RVecs leak memory with np.asarray in pyROOT

### ISSUE THREAD

**Issue by dudarboh** [root-project/root#14981]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Using `np.asarray()` to convert an existing `RVec` object into the numpy array as suggested in the Documentation [here](https://root.cern/doc/master/classROOT_1_1VecOps_1_1RVec.html#RVecdoxyref) takes memory which is never freed.

Created `RVec` objects inside pyROOT are also not cleaned up by the garbage collector.

### Reproducer

```bash
python --version
Python 3.9.12
# Run as
python3 reproducer.py
```

```python
#reproducer.py
import ROOT
import os, psutil
import gc
import numpy as np
import matplotlib.pyplot as plt
import tqdm
process = psutil.Process()

# to cache a lot of things
ROOT.RVec('double')()

def get_mem_usage():
    gc.collect()
    return process.memory_info().rss  # in kbytes 


ROOT.gInterpreter.Declare("""
auto create_rvec(unsigned int n) {
    //return std::array<unsigned int, 3>({n, n, n});
    return ROOT::RVec<unsigned int>({n, n, n});
}
""")
df = ROOT.ROOT.RDataFrame(1000).Define("my_rvecs", "create_rvec(rdfentry_)")

# To trigger the event loop before measuring memory
my_rvecs = df.AsNumpy(["my_rvecs"])["my_rvecs"]

mem0 = get_mem_usage()
print(mem0)

#my_data is gone at the end of the loop, nice!
for rvec in my_rvecs:
    my_data = rvec
mem1 = get_mem_usage()
print(mem1)

#Does not free memory at the end of the loop!
for rvec in my_rvecs:
    my_data = np.asarray(rvec)
mem2 = get_mem_usage()
print(mem2)

#Creating RVecs in place also does not free memory!
for i in range(1000):
    ROOT.RVec('double')((42., 42., 42.))
mem3 = get_mem_usage()
print(mem3)
```

#### Output:

```
510033920
510033920
552292352
555728896
```

#### Expected:
No increase in memory usage over time!

#### Workaround

I guess this should work as a workaround.
```python
for rvec in my_rvecs:
    my_data = np.array([x for x in rvec])
```

P.S. Thanks, Jonas for the the nice reproducer!

### ROOT version

ROOT Version: 6.31/01
Built for linuxx8664gcc on Mar 11 2024, 23:52:46
From heads/master@v6-31-01-1407-gc76b8f7

### Installation method

source /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc11-dbg/setup.sh

### Operating system

CentOS Linux 7 (Core)

### Additional context

Initially submitted on the forum [here](https://root-forum.cern.ch/t/rvecs-memory-is-not-freed-by-a-garbage-collector-in-pyroot/58545/2)

**Comment by vepadulano** [comment]
Hi, some update on this.

First, let me try to clear a bit the context. I am not sure why `gc.collect` is being invoked here. Manually invoking the Python garbage collector is not going to give any guarantees on which objects are actually destroyed by the interpreter, it depends on the types and sometimes it's even undefined behaviour, as per the docs https://docs.python.org/3/library/gc.html#gc.collect

Second, even if we had that guarantee, the first and the second loops are doing two wildly different things.
```
my_data = rvec
```
Is doing a copy of an `RVec` to another `RVec`, with a thin Python proxy to present it to the user. The copy of an RVec is a well-defined operation in terms of memory management, i.e. it will call the copy-constructor of the `RVec`. Whereas
```
my_data = numpy.asarray(rvec)
```
Is creating a new numpy array object in memory which is an owning view on the contents of the RVec.

The management of the RVec in memory can be clearly seen with this simplified example
```
process = psutil.Process()

ROOT.gInterpreter.Declare("""
auto create_rvec(unsigned int n) {
    //return std::array<unsigned int, 3>({n, n, n});
    return ROOT::RVec<unsigned int>({n, n, n});
}
""")
df = ROOT.RDataFrame(100).Define("my_rvecs", "create_rvec(rdfentry_)")
rvecs = df.AsNumpy(["my_rvecs"])["my_rvecs"]

def get_mem_usage():
    return process.memory_info().rss  # in kbytes

mem0 = get_mem_usage()
print(mem0)

for v2 in rvecs:
    n = v2
    mem2 = get_mem_usage()
    print(mem2)
```

Which doesn't use `gc.collect` but will still show that the memory used is exactly the same at each iteration, no leaks.
