### ISSUE TITLE
[ci] Improve the caching of the nodes instead of more nodes

### ISSUE THREAD

**Issue by vgvassilev** [root-project/root#14987]
### Explain what you would like to see improved and how.

We can speed up the builds significantly by using the github actions cache system. More can be read here: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows 

Essentially we need a `actions/cache/restore@v3`. This is done in the clad CI here: https://github.com/vgvassilev/clad/blob/d2df9008e071f7f78d1606a040b21149ade66eea/.github/workflows/ci.yml#L637-L678

The idea is to cache the builds of ROOT up to cling and make a hash that will invalidate the cache only if something in cling is touched. In that case the system will regenerate the caches. We need to figure out if the 10GB storage is enough per project or we can store these things locally. For the Clad project it has been working flawlessly for ~1 year now. 

### ROOT version

N/A

### Installation method

N/A

### Operating system

N/A

**Comment by dpiparo** [comment]
I would propose to change the title to "[ci] Further speedup mac and linux builds by caching dependencies". The word "instead" can be misleading. Our goal is to have feedback from the CI as soon as possible. Having several nodes, allows to scale horizontally. We are not increasing the number of nodes in the CI because we are lazy, we just need many nodes AND fast CI, e.g. through caches or quicker tests :)

**Comment by vgvassilev** [comment]
> I would propose to change the title to "[ci] Further speedup mac and linux builds by caching dependencies". The word "instead" can be misleading. Our goal is to have feedback from the CI as soon as possible. Having several nodes, allows to scale horizontally. We are not increasing the number of nodes in the CI because we are lazy, we just need many nodes AND fast CI, e.g. through caches or quicker tests :)

The proposed rename works for me. It's not only for mac and linux, it covers any platform.

**Comment by amadio** [comment]
+1 for both adding nodes and for speedung up builds, any effort is good in this area. It takes very long for a pull request to run all the builds to completion.

**Comment by ferdymercury** [comment]
> +1 for both adding nodes and for speedung up builds, any effort is good in this area.

One attempt by Axel wrt build speed-up is here: https://github.com/root-project/root/issues/6432#issuecomment-2009372525

**Comment by dpiparo** [comment]
I am closing the issue as completed since now artifacts are used also on macos. This is an ongoing effort, we'll strive continuously to make our builds faster and more efficient.
