### ISSUE TITLE
Building ROOT with CMake 3.29.0 and Ninja 1.11.1 breaks

### ISSUE THREAD

**Issue by ktf** [root-project/root#15064]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

The new cmake changes some behavior WRT the ninja Generator (see https://cmake.org/cmake/help/latest/command/add_custom_command.html) and this seems to break root builds with:

```
2024-03-27@10:00:24:DEBUG:ROOT:ROOT:0: ++ cmake --build . --target install -j 28
2024-03-27@10:00:24:DEBUG:ROOT:ROOT:0: ninja: error: build.ninja:27137: multiple outputs aren't (yet?) supported by depslog; bring this up on the mailing list if it affects you
2024-03-27@10:00:24:DEBUG:ROOT:ROOT:0:
```

### Reproducer

Just update to the latest cmake and build root with the -G Ninja option.

### ROOT version

6.30.1

### Installation method

aliBuild

### Operating system

macOS

### Additional context

I think the issue is general and not related to macOS. Reverting back to Cmake 3.28 works around the issue. Using the makefile generator also works around the issue.

**Comment by ktf** [comment]
For the record, I am able to get things to work by doing:

```
sed -i.removeme '/deps = gcc/d' build.ninja
```

on the generated `build.ninja`. I think the issue is to be traced back to some spurious dependency added in `ROOT/interpreter/llvm-project/llvm/cmake/modules/TableGen.cmake`, but I am not quite sure how that happens.

**Comment by qweasdzxc787** [comment]
Also seeing this issue break Qt builds with target AUTOMOC and AUTOUIC. Reverting to CMake 3.28 fixes the issue.

Same underlying thing: "deps = gcc" in the moc targets.

**Comment by ktf** [comment]
Any news on this?

**Comment by bellenot** [comment]
Looking at it right now

**Comment by bellenot** [comment]
So I cannot reproduce the issue with ROOT master, cmake version 3.29.1, Ninja 1.10.0 on Ubuntu 20.04.6. Should I ask someone to try on MacOS?

**Comment by ktf** [comment]
Yes, please.

**Comment by bellenot** [comment]
@couet can you try on Mac, please?

**Comment by couet** [comment]
Yes, let me try to set up such an environment.

**Comment by couet** [comment]
It is working for me on MacOS

**Comment by ktf** [comment]
Cannot reproduce anymore.

**Comment by echristo** [comment]
> For the record, I am able to get things to work by doing:
> 
> ```
> sed -i.removeme '/deps = gcc/d' build.ninja
> ```
> 
> on the generated `build.ninja`. I think the issue is to be traced back to some spurious dependency added in `ROOT/interpreter/llvm-project/llvm/cmake/modules/TableGen.cmake`, but I am not quite sure how that happens.

btw, I just put up https://github.com/llvm/llvm-project/pull/179842/commits which solved the problem for me and has a decentish description of what the problem was. :)
