### ISSUE TITLE
Passing different floating point types to `RVec` utility functions

### ISSUE THREAD

**Issue by tmadlener** [root-project/root#15077]
### Explain what you would like to see improved and how.

(I will be using `DeltaPhi` for illustration here, but I suspect many functions have similar "limitations". The current way of doing things is perfectly valid and might even be preferable, this issue is also meant to gauge whether you would be willing to accept PR(s) with these changes in place).

The current interface of `DeltaPhi` in `RVec.hxx` looks like this:
https://github.com/root-project/root/blob/7a4af49dc65a812a3feea24c98a49b84cd85caaf/math/vecops/inc/ROOT/RVec.hxx#L2876

This means that calling it with
```cpp
auto dphi = DeltaPhi(3.14f, 1.23)
```
will lead to a template deduction error because both argument should have the same type. We have triggered this via RDataFrame from python by using the version that uses an `RVec` by passing a `vector<float>` and `vector<double>`. The error message you get at the moment tells us exactly that, but is also not the easiest to interpret if you are not too familiar with C++.

One way around this is to introduce a temporary variable that converts one of the two vectors into the same type as the other. While this obviously works it's also not really elegant to do so.

The "proper"(?) way to fix this would to make `DeltaPhi` a bit more "relaxed" with its template arguments, something along the lines of:
```cpp
template <typename T, typename U = T>
std::common_type_t<T, U> DeltaPhi(T v1, U v2, std::common_type_t<T, U> c = M_PI) { 
  // implementation unchanged apart from updated static_assert to take into account T and U
}
```
This would then have to be done also the the overloads taking an `RVec` to solve our issue.

Is this something you would be interested in at all? Then we could maybe also discuss who would be doing the actual work for this.

### ROOT version

6.18/00 onwards

### Installation method

any 

### Operating system

any

**Comment by dpiparo** [comment]
Dear @tmadlener , thanks for for pointing out this opportunity for improvement! We agree with your analysis and would warmly welcome your PR to change the current code.

**Comment by tmadlener** [comment]
What is the minimal c++ standard that should be supported in this case? It probably doesn't make a lot of difference, but the `xyz_t`  helper types that were introduced with c++14 are slightly nicer than having to do `typename xyz::type` everywhere. However, if c++11 is still a target, then there is not too much that can be done, I suppose.

**Comment by pcanal** [comment]
You can use up to C++17.
