### ISSUE TITLE
 [DF] Memleaks in case RDF jitted code is registered but the application never triggers an event loop

### ISSUE THREAD

**Issue by martamaja10** [root-project/root#15076]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Moving from JIRA: [ROOT-10724](https://its.cern.ch/jira/browse/ROOT-10724)
Most of the issue was solved - the remaining part is for a rare case: 

We still "leak" in the odd case in which RDF jitted code is registered but the application never actually triggers any RDF event loops, in which case the code to be lazily jitted remains in the pipeline until the end of the application, and parts of the computation graph are kept alive indefinitely by heap-allocated shared_ptrs.
I suppose we could forcibly trigger execution of the jitted code that performs the clean-up whenever the count of live RLoopManagers goes from >0 to 0.

### Reproducer

-

### ROOT version

any

### Installation method

any

### Operating system

any

**Comment by vepadulano** [comment]
Closing in favour of #15520 as now the situation is better understood and the fix proposed by the JIRA issue is already implemented in master
