### ISSUE TITLE
Turn off clang-format for Linkdef files

### ISSUE THREAD

**Issue by jblomer** [root-project/root#15108]
### Explain what you would like to see improved and how.

Linkdef files should not be subject to clang-format checks. They force us to write lines such as

```
#pragma link C++ class Event + ;
```

(Note the blanks around the `+`)

### ROOT version

master

### Installation method

n/a

### Operating system

n/a

**Comment by guitargeek** [comment]
Is this not the case already?

https://github.com/root-project/root/blob/master/.ci/format_script.sh

**Comment by jblomer** [comment]
It should match. Let me submit a test PR.

**Comment by jblomer** [comment]
The problem appears if _only_ linkdef files are changed. In this case, `git-clang-format` receives an empty list of files to check and looks all the changed files.
