### ISSUE TITLE
jsoninterface does not build if provided with RapidYAML

### ISSUE THREAD

**Issue by jan-busa** [root-project/root#15118]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

I have tried to build ROOT (v6.30.04, v6.30.06, master seems to be the same) with RapidYAML by setting variables ```RYML_LIBRARY``` and ```RYML_INCLUDE_DIR``` during the configuration step. Build of ROOT fails (jsoninterface step), first complaining that it can't find ```ryml.hpp``` and if fixed it can't link the libraries ```c4core``` and ```ryml```. Problem seems to be, that when searching for RapidYAML, ```cmake/modules/Findryml.cmake``` sets variables ```RYML_INCLUDE_DIR``` and ```RYML_LIBRARY_PATH```, but in ```roofit/jsoninterface/CMakeLists.txt``` different variables are used (```RYML_INCLUDE_DIRS``` and ```RYML_LIB_DIR```, respectively).

### Reproducer

Try to build ROOT, during configuration step set ```RYML_LIBRARY``` and ```RYML_INCLUDE_DIR``` variables to point to local RapidYAML installation.

### ROOT version

v6.30.04, v6.30.06, CMake v3.29.0, RapidYAML v0.5.0

### Installation method

build from source

### Operating system

CentOS7

**Comment by guitargeek** [comment]
Sorry! We should have not made the rapidyaml backend for RooFit JSON available in the release. It is not tested and only there for dev purposes. This PR will fix this:
https://github.com/root-project/root/pull/15247

I'll backport it to ROOT 6.32, 6.30 and 6.28.
