### ISSUE TITLE
How to specify a specific python version in the master...

### ISSUE THREAD

**Issue by FonsRademakers** [root-project/root#15136]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Using the following cmake statement specifying a specific python version works in v6.30.x but not in the master:

cmake -G Ninja -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3.9 ..

In the master python3 (i.e. Python 3.12.2) will be used

`-- PyROOT will be built for version 3.12.2`

 while in v6.30.x this, correctly, results in python3.9 (i.e. Python 3.9.19) to be used:

`-- PyROOT will be built for version 3.9.19`

Has the method to specify a specific python version to cmake been changed?

Thanks, Fons.

### Reproducer

Run this statement

`cmake -G Ninja -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3.9 ..`

on the master and v6-30-06.

### ROOT version

Use git `master` and `v6-30-06`.

### Installation method

Building from source

### Operating system

macOS

**Comment by bellenot** [comment]
Adding @vepadulano in the loop, since it looks like the faulty commit could well be [this one](https://github.com/root-project/root/commit/37b06ebc33fe192c20bee5d48a496d51ee591aa0#diff-dd81606cd750b320d9ed46d043eb5e5dceaf7e7dbcf2d4934cae69bbfc27138f)

**Comment by bellenot** [comment]
Ad let's add @guitargeek, since he changed also quite some PyROOT code recently...

**Comment by guitargeek** [comment]
Hi Fons! Thanks for opening this issue. It seems our instructions are out-of-date here:
https://root.cern/install/build_from_source/#root-python-and-pyroot

We don't have any of this multi Python anymore, support for Python 2 is dropped in ROOT 6.32.

What we use now is just the standard CMake `find_package(Python3 ...)`, which you can give [some hints](https://cmake.org/cmake/help/latest/module/FindPython3.html#hints) to find python. In your case, the `Python3_ROOT_DIR` should probably do the trick:

`cmake -G Ninja -DPython3_ROOT_DIR=/opt/homebrew/ ..`

Now, if you have multiple Python versions in that directory (I don't know if you do), then I think it will pick the newest one by default. In that case, you might have to [create a virtual environment with your desired specific Python version](https://stackoverflow.com/questions/1534210/use-different-python-version-with-virtualenv), and then pass the directory of the virtual environment as the `Python3_ROOT_DIR` (or via some other hints specific for virtual environments).

Let us know what works for you, and then I can update the website accordingly with the right instructions!

**Comment by guitargeek** [comment]
Closed by: https://github.com/root-project/web/pull/983
