### ISSUE TITLE
Segfault in TMVA::Experimental::SOFIE::RModel::Streamer

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#15156]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

TMVA tests sporadically fail in ROOT's integration buils (both PR and Nightly). Often the stack traces are not easily readable, for example when the test is steered through PyROOT. However, at least one clear problem emerged in the I/O of `TMVA::Experimental::SOFIE::RModel` instances.
In [this build](https://github.com/root-project/root/actions/runs/8568832804/job/23483489958) it can be clearly seen that the segfault happens when a `RModel` instance is read from a ROOT file.
The stack trace is the following:
```  
TMVA SOFIE Operator Conv:  asymmetric padding not supported. Assume an average padding 
  
   *** Break *** segmentation violation
  [/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
  [/Users/sftnight/ROOT-CI/build/lib/libROOTTMVASofie.so] TMVA::Experimental::SOFIE::InitializedTensor::CastPersistentToShared() (no debug info)
  [/Users/sftnight/ROOT-CI/build/lib/libROOTTMVASofie.so] TMVA::Experimental::SOFIE::RModel::Streamer(TBuffer&) (no debug info)
  [/Users/sftnight/ROOT-CI/build/lib/libRIO.so] TKey::ReadObjectAny(TClass const*) (no debug info)
  [/Users/sftnight/ROOT-CI/build/lib/libRIO.so] TDirectoryFile::GetObjectChecked(char const*, TClass const*) (no debug info)
  [/Users/sftnight/ROOT-CI/build/tmva/sofie/test/emitFromROOT] EmitModel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) (no debug info)
  [/Users/sftnight/ROOT-CI/build/tmva/sofie/test/emitFromROOT] main (no debug info)
  [/usr/lib/dyld] start (no debug info)
  make[2]: *** [SofieCompileModels_ROOT] Error 139
  make[1]: *** [tmva/sofie/test/CMakeFiles/SofieCompileModels_ROOT.dir/all] Error 2
  make: *** [all] Error 2
```

This bug could be affecting other ROOT branches (for sure at least master). Moreover, the I/O of those objects might be corrupt ( the class is in the `Experimental` namespace, but this issue is definitively blocking the promotion to ROOT proper).

### Reproducer

It's enough to do some IO of `TMVA::Experimental::SOFIE::RModel` instances.

### ROOT version

master and 6.32 but likely also other versions are affected.

### Installation method

from sources

### Operating system

mac, but likely others

**Comment by ferdymercury** [comment]
Maybe changing https://github.com/root-project/root/blob/master/tmva/sofie/inc/TMVA/RModel.hxx#L142 to `ClassDefOverride` helps?
