### ISSUE TITLE
ROOT generates CMake warnings when building from the tarball

### ISSUE THREAD

**Issue by amadio** [root-project/root#15178]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

If you build ROOT from a tarball, you'll see the message below during configuration:
```
-- Found Git: /usr/bin/git (found version "2.44.0")
CMake Warning at cmake/modules/SetROOTVersion.cmake:85 (message):
  GIT_DESCRIBE_ALL is ``·with a format unexpected for tags.  Not setting the
  commit.
Call Stack (most recent call first):
  cmake/modules/SetROOTVersion.cmake:99 (SET_ROOT_VERSION)
  CMakeLists.txt:77 (include)


-- Building ROOT version 6.30.06
```
Not a big deal, but might be worth fixing.

### Reproducer

Build ROOT from a tarball instead of a git clone.

### ROOT version

ROOT 6.30.06

### Installation method

Portage

### Operating system

Gentoo Linux

**Comment by dpiparo** [comment]
Hi, what tarball did you use?

**Comment by amadio** [comment]
This one: https://root.cern/releases/release-63006/#source-distribution

**Comment by bellenot** [comment]
I can reproduce the issue. This is most probably coming from [this commit](https://github.com/root-project/root/commit/a1f54ed694b330a3b2591807daa75445a39a76c3) @Axel-Naumann @guitargeek ?

**Comment by ntadej** [comment]
Probably setting `GIT_DESCRIBE_ALL=tags/v6-32-02`.
