### ISSUE TITLE
Errors with chi2FitTo in a new RooFit version

### ISSUE THREAD

**Issue by vayeroshenko** [root-project/root#15196]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

I've been using RooFit for my binned chi2 fits (with chi2FitTo). I use the `lb-conda` LHCb wrapper for python. Lately it seems that the `lb-conda` has updated and with the new version, my fits stopped working.
The old version of ROOT I was using is 6.28/04 (python 3.11.4), and the new one is 6.30/04 (python 3.11.8).

The new version finds a different minimum, returns status `MINIMIZE=-1 HESSE=302` and zero errors. The old version returns `MINIMIZE=1 HESSE=1 ` and meaningful errors.
I set ROOT.RooFit.Minimizer("Minuit2","migrad") option for both.

I didn't manage to reproduce the error in other conditions, so I packed my workspace in a reproducible example, found in my public lxplus area (`/afs/cern.ch/work/v/vyeroshe/public/test.root`)

### Reproducer

```
import ROOT as r

file = r.TFile("/afs/cern.ch/work/v/vyeroshe/public/test.root")
workspace = file.Get("w_test")

hist = workspace.data("jpsi_ppbar_mass")
pdf = workspace.pdf("model_Low")

result = pdf.chi2FitTo(hist, r.RooFit.Save(),r.RooFit.Minimizer("Minuit2","migrad"))
result.Print()
```

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.30/04                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Feb 06 2024, 23:27:10                 |
  | From heads/master@tags/v6-30-04                                  |
  | With                                                             |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

```

### Installation method

lb-conda

### Operating system

CentOS Linux 7

**Comment by guitargeek** [comment]
Hello! I see that your dataset has bins with negative weights. That's not a good start.
![plot](https://github.com/root-project/root/assets/6578603/f213df07-1c68-4453-9e6e-5f9cbb24787c)
In newer ROOT versions, the Chi2 are more consistent with the likelihood fits. Meaning that if you have an extendible pdf, it will automatically do an extended fit (i.e., a Poisson term to constrain the number of predicted events is added).

However, if you have weights this is not meaningful anymore. I guess you don't even want to do an extended fit in your case. You can explicitly pass `RooFit::Extended(false)` to get back the old behavior:
```c++
using namespace RooFit;

TFile file{"test.root"};
auto workspace = file.Get<RooWorkspace>("w_test");

auto hist = static_cast<RooDataHist *>(workspace->data("jpsi_ppbar_mass"));
auto x = workspace->var("Jpsi_m_fitted");
auto pdf = workspace->pdf("model_Low");

auto result = pdf->chi2FitTo(*hist, Save(), Extended(false));
result->Print();
```

But your fit has also has a different problem (any status other than `MINIMIZE=0` means an error in Minuit). You use a RooAddPdf for the model. This class inherits from RooAbsPdf, and a pdf in RooFit is forced to be positive everywhere. Therefore, you can't fit the your data with the negative bin contents at all. You need to create a RooAbsReal-derived function, maybe a [RooRealSumFunc](https://root.cern.ch/doc/master/classRooRealSumFunc.html).

Or maybe can you avoid the negative bin content all together? Where does it even come from, from subtracting a background? IN this case this is the wrong thing do do for statistical analysis. I would rather keep the background in the data and add a component to the model, maybe a fixed RooHistPdf for that part that exactly corresponds to the background estimation.
