### ISSUE TITLE
cppyy now fails to call a static method on an object instance

### ISSUE THREAD

**Issue by Nowakus** [root-project/root#15217]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

The new cppyy in ROOT 6.32 has a problem calling a static class method when the call is done on an instance of that class. It worked before and I think conceptually it should still be ok, right?

Edit: actually, I now see that it has something to do with the optional parameter, because a call with 2 arguments works OK
### Reproducer
```
import cppyy
cppyy.cppdef("""
   class MyClass {  public:
   void static statMethod(const std::string& astr, const std::string& path = "") {}
   };""")
obj = cppyy.gbl.MyClass()
obj.statMethod("first")
TypeError: static void MyClass::statMethod(const string& astr, const string& path) =>
    TypeError: could not convert argument 1
```

### ROOT version

6.32-patches

### Installation method

lcg dev3/dev4

### Operating system

alma9

**Comment by wlav** [comment]
https://github.com/wlav/CPyCppyy/blob/master/src/CPPClassMethod.cxx#L27

**Comment by wlav** [comment]
Fixed with: https://github.com/wlav/CPyCppyy/commit/e40a3fbab87304deb4ed37e217f66d87cc3ceba7

**Comment by guitargeek** [comment]
Fixed in "not applicable" because to ROOT release included the cppyy version without support for this.
