### ISSUE TITLE
cppyy - wrong object type when iterating over a polymorphic container

### ISSUE THREAD

**Issue by Nowakus** [root-project/root#15234]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When looping over a polymorphic collection, type() always reports the base class type, not the actual object type

### Reproducer

```python
import cppyy
cppyy.cppdef("""
   class vertex {  public:
     virtual std::string idself() { return "I am vertex"; }
   };
   class Mvertex : public vertex {  public:
     virtual std::string idself() { return "I am Mvertex"; }
   };
   class vCont { public:
     std::vector< vertex* > verts { new vertex(), new Mvertex() };
     const std::vector<vertex*>& vertices() { return verts; }
   };
""")
cont = cppyy.gbl.vCont()
verts = cont.vertices()
for v in verts:
    print( v.idself(), v.__class__, type(v), "Am I Mvertex?", isinstance(v, cppyy.gbl.Mvertex) )
```

### ROOT version

6.32-patches

### Installation method

lcg dev3/dev4

### Operating system

alma9

### Additional context

The output of the reproducer looks like this:
`I am vertex <class cppyy.gbl.vertex at 0x8d58190> <class cppyy.gbl.vertex at 0x8d58190> Am I Mvertex? False   
 I am Mvertex <class cppyy.gbl.vertex at 0x8d58190> <class cppyy.gbl.vertex at 0x8d58190> Am I Mvertex? False`
which means the virtual methods resolution works fine, but the __class__ of the iteration variable is not set correctly.

**Comment by wlav** [comment]
Yes, the current implementation uses the `NoCast` binding: https://github.com/wlav/CPyCppyy/blob/master/src/CustomPyTypes.cxx#L414

**Comment by wlav** [comment]
This should do: https://github.com/wlav/CPyCppyy/commit/9a792b231c73452d08686ea83c6588f5e98ca9a7

**Comment by Nowakus** [comment]
That looks promising. Thank you for handling it so quickly @wlav !
Btw, that was the last issue I was seeing with ROOT 6.32 so I will get out of your hair for now.
