### ISSUE TITLE
Webgraphics: different behaviour wrt classic graphics with 2 canvases

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#15353]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

There is a difference in the behaviour of the 2 graphics backends, when drawing on 2 canvases an updated historgam.

### Reproducer

```
TCanvas c1;
TH1F h("h","h", 64, -4,4);
h.FillRandom("gaus");
h.Draw();
TCanvas c2;
h.FillRandom("gaus",10000);
h.Draw();
```
Classic graphics: One histo with 5k entries and one with 15k entries
Web graphics: Two histos with 15k entries

### ROOT version

master

### Installation method

sources

### Operating system

MacOS

**Comment by linev** [comment]
It is time glitch between web canvas and normal canvas. 
Web canvas requires some time to be started - and during this time one get histogram fill to the end.
If one do `c1.SaveAs("c1.png")` and `c2.SaveAs("c2.png")` one get expected values.

**Comment by dpiparo** [comment]
Thanks. Nevertheless the problem is there also if commands are run interactively, waiting seconds after the first canvas is drawn.

**Comment by linev** [comment]
Problem is extra `gPad->Modified()` call when new TCanvas is created. 

In the macro it marks first canvas always as modified. And at the end of macro execution both canvas are updated to latest histogram content. I create PR #15518 which fixes such bogus behavior. After PR merged one can do:

```
TCanvas c1;
TH1F h("h","h", 64, -4,4);
h.FillRandom("gaus");
h.Draw();
c1.Update(); // ensures histogram displayed as exists at this point
TCanvas c2;
h.FillRandom("gaus",10000);
h.Draw();
```

**Comment by linev** [comment]
I checked again. With the master branch last macro produces two canvases - with 5000 and 15000 entries.

With the 6.32 ROOT code one have to add `gPad = nullptr;` before creating second canvas.

**Comment by linev** [comment]
With current master both canvases show 15000 entries for histogram.
Looks like after recent changes in ROOT canvases are modified at the end of macro execution.
Same behavior seen in master and 6.32 branch in normal and web graphics
