### ISSUE TITLE
[RF] ExternalConstraints documentation incorrect for RooMCStudy

### ISSUE THREAD

**Issue by goi42** [root-project/root#15405]
### Explain what you would like to see improved and how.

The [documentation](https://root.cern.ch/doc/v632/classRooMCStudy.html#a8123a2ac2bfc1d97796224571b9e0e4a) for the `RooMCStudy` constructor says for the argument `ExternalConstraints`: "Apply internal constraints on given parameters in fit and sample constrained parameter values from constraint p.d.f for each toy." This is not correct. Looking at the [source code](https://root.cern.ch/doc/v632/RooMCStudy_8cxx_source.html#l00171), it appears that the `ExternalConstraints` are simply added to the fit options that are eventually passed internally to `fitTo`.

It would be better, I think, to simply eliminate this as an argument to `RooMCStudy`. It should instead just be allowed as part of the arbitrary `FitOptions`. This would be more transparent.

### ROOT version

v6.32

### Installation method

N/A

### Operating system

N/A

**Comment by guitargeek** [comment]
Thanks for noticing this! I have opened a PR to update the docs. However, I kept the logic of forwarding to the fit options for backwards compatibility.
