### ISSUE TITLE
[RF] investigate and fix MultiProcess::Queue test timeout

### ISSUE THREAD

**Issue by egpbos** [root-project/root#15494]
### Explain what you would like to see improved and how.

In https://github.com/root-project/root/pull/15376#issuecomment-2099245931, in the ubuntu20 CI build, we saw a timeout of the Queue test, seemingly at the first test (FIFOQueue.TaskOrder), giving the following output:

```
  2535/2551 Test  #265: gtest-roofit-multiprocess-test-test-RooFit-MultiProcess-Queue .....................................***Timeout 1500.10 sec
  Running main() from /build/googletest-j5yxiC/googletest-1.10.0/googletest/src/gtest_main.cc
  [==========] Running 5 tests from 3 test suites.
  [----------] Global test environment set-up.
  [----------] 1 test from FIFOQueue
  [ RUN      ] FIFOQueue.TaskOrder
```

It's unclear what is causing this. It seems to be spurious. We should investigate what is going on and then fix it.

### ROOT version

Master + PR https://github.com/root-project/root/pull/15376.

### Installation method

build from source

### Operating system

Ubuntu20

**Comment by dpiparo** [comment]
I take this failure very seriously and I am thankful that @egpbos went through the hurdle of reporting. 
In the last several weeks, I did not see this issue in any of the nightlies though. What could be a good process to decide when to close this issue if the failure is not seen any more for a certain time interval?

**Comment by guitargeek** [comment]
I was running the test 1000 times in a loop and never hit the problem once. Maybe it was just a bad day on the GitHub actions runners.

I would suggest to close this issue. Is that okay for you @egpbos? Thanks for documenting this though!

**Comment by egpbos** [comment]
Yep, let's close! The logs of old runs like this are lost anyway and are not very informative in any case. The chances of it being something weird having to do with GitHub Actions runner particulars is also non-negligible. I will put it on my own todo list to look a bit more into this at some point.
