### ISSUE TITLE
Memory leak in TTree __getattr__ pythonization

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#15610]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

https://root-forum.cern.ch/t/memory-leak-in-pyroot-when-using-user-defined-c-macros-from-python-and-ttree-friends/59432

### Reproducer

Please see the forum post

### ROOT version

at least 6.26 onwards

### Installation method

all

### Operating system

all

**Comment by guitargeek** [comment]
I checked by running the reproducer in the PR thread on ROOT 6.20 vs 6.22 on `lxplus7`. This regression was indeed introduced with the PyROOT upgrade in 6.22:
https://root.cern/doc/v622/release-notes.html#pyroot

ROOT 6.20.00:
```txt
(0, 'memory usage', 191016L, 695956L)
(10000, 'memory usage', 206324L, 696336L)
(20000, 'memory usage', 206488L, 696336L)
(30000, 'memory usage', 206488L, 696336L)
(40000, 'memory usage', 206488L, 696336L)
(50000, 'memory usage', 206488L, 696336L)
(60000, 'memory usage', 206488L, 696336L)
(70000, 'memory usage', 206488L, 696336L)
(80000, 'memory usage', 206488L, 696336L)
(90000, 'memory usage', 206488L, 696336L)
```
ROOT 6.22.00:
```txt
(0, 'memory usage', 225244L, 737080L)
(10000, 'memory usage', 245352L, 741968L)
(20000, 'memory usage', 249948L, 746252L)
(30000, 'memory usage', 254428L, 751900L)
(40000, 'memory usage', 259000L, 756108L)
(50000, 'memory usage', 263708L, 760456L)
(60000, 'memory usage', 268092L, 764408L)
(70000, 'memory usage', 274440L, 772668L)
(80000, 'memory usage', 277480L, 775772L)
(90000, 'memory usage', 281936L, 779724L)
```
