### ISSUE TITLE
TGFileContainer crashes in pyroot 

### ISSUE THREAD

**Issue by PPaye** [root-project/root#15643]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

In `pyroot`.
Right after declaring an instance of `TGFileContainer`, ROOT crashes.

### Reproducer

import ROOT
myContainer = ROOT.TGFileContainer()

### ROOT version

6.30/06
Built for linuxx8664gcc
From heads/latest-stable@

### Installation method

build from source

### Operating system

Linux

**Comment by dpiparo** [comment]
thanks for the report. It's there, I see this also in C++. The crash happens in `root/gui/gui/src/TGFSContainer.cxx:634`. Investigating.

**Comment by dpiparo** [comment]
While we look into it, I would like to ask a question: why are you calling the default constructor?

**Comment by bellenot** [comment]
I can add a protection, but can I ask the same question: why are you calling the default constructor?
