### ISSUE TITLE
[RF] SegFault in RooBernstein::fillBuffer

### ISSUE THREAD

**Issue by will-cern** [root-project/root#15690]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

running some tests on 6.32 with the CMS Higgs workspace I am getting a crash with the top of the stack trace pointing to `RooBernstein::fillBuffer()` which was introduced in https://github.com/root-project/root/commit/50a1bddacc1cbd22d7ce0e184db42bc04e9b0088

I can confirm that I don't see the crash when I use a version of ROOT master from just before this commit. 

Looking at the commit, it has introduced a new data member, `_buffer` ... but has not done any schema evolution. 

I'm wondering if the crash is that the `_buffer` in the auto-evolved instance is empty, and then the `fillBuffer` method is trying to fill into this? The resize of `_buffer` only happens in the non-default-constructor, I note.

### Reproducer

In 6.32:
```
import ROOT.Experimental.XRooFit as XRF
w = XRF.xRooNode("/afs/cern.ch/work/w/will/public/cms_higgs_ws.root")
w["model_s"][0].Draw()
```
or in C++:
```
using namespace ROOT::Experimental::XRooFit;
xRooNode w("/afs/cern.ch/work/w/will/public/cms_higgs_ws.root");
w["model_s"]->at(0)->Draw();
```

### ROOT version

6.32

### Installation method

source

### Operating system

el9

**Comment by guitargeek** [comment]
I opened a PR to fix this. Sorry for the amateur mistake!
It has nothing to do with schema evolution because the `_buffer` is a transient data member.

 * https://github.com/root-project/root/pull/15695
