### ISSUE TITLE
Leaking memory though strings in PyROOT

### ISSUE THREAD

**Issue by amete** [root-project/root#15703]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

It looks like we're leaking memory dynamically allocated through `std::string`, e.g., `std::string::reserve` and/or `std::string::append` etc. It seems to be reproducible via vanilla `cppyy` as shown below. Can someone take a look, please? Many thanks.

cc: @scott-snyder 

### Reproducer

```
import cppyy

cppyy.cppdef("""
  #include <string>
  class foo {
    public:
      const std::string leak (std::size_t size) const {
        std::string result;
        result.reserve(size);
        return result;
      }
  };
""")

obj = cppyy.gbl.foo()
for i in range(1000000):
  s = obj.leak(2048)
```

### ROOT version

Tested in both tags/v6-28-12@v6-28-12 and heads/master@v6-31-01-2207-gbeb5aead7a

### Installation method

LCG_104d_ATLAS_15 and LCG dev3 nightly

### Operating system

AlmaLinux release 9.4 (Shamrock Pampas Cat)

**Comment by wlav** [comment]
> It seems to be reproducible via vanilla cppyy as shown below. 

The example above isn't a proper leak check b/c the `range()` call will have Python cache integers, the first `obj.leak` call will compile a wrapper (loading all kinds of stuff the first time around) etc. Below is an actual test, which doesn't leak on "vanilla cppyy" although it may still be on the one included in ROOT as there are differences:

```
import cppyy, gc, os, psutil

cppyy.cppdef("""
  #include <string>
  class foo {
    public:
      const std::string leak (std::size_t size) const {
        std::string result;
        result.reserve(size);
        return result;
      }
  };
""")

process = psutil.Process(os.getpid())

# warmup
obj = cppyy.gbl.foo()
for i in range(1000000):
  s = obj.leak(2048)

gc.collect()

last = process.memory_info().rss

for i in range(1000000):
  s = obj.leak(2048)

gc.collect()
assert last == process.memory_info().rss
```

**Comment by amete** [comment]
Thanks a lot @wlav. I really meant the {{cppyy}} included in the ROOT. Running your example against {{tags/v6-28-12}}, the last assertion fails, where the `last` RSS reads 2,565,689,344 and the `current` reads `4,629,704,704`.

**Comment by wlav** [comment]
Yes, that's real, alright: I'll add that the total memory usage I see for cppyy proper is around ~120MB on Mac and ~168MB on Linux (>98% of which is startup of Python and Cling), so those numbers being in GBs definitely indicates a problem.
