### ISSUE TITLE
Windows CMake project cannot find_library() after integrating with ROOT.

### ISSUE THREAD

**Issue by petrmanek** [root-project/root#15727]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Ever since integrating with ROOT, my cmake project cannot find a dependency using `find_package()`. It seems that `ROOTConfig.cmake` [reconfigures](https://github.com/root-project/root/blob/v6-32-00/cmake/scripts/ROOTConfig.cmake.in#L148) the value of `CMAKE_FIND_LIBRARY_PREFIXES` in order to find ROOT libraries with the `lib` prefix. However, the original value is never put back. Later on, this breaks e.g. `find_library(ZLIB)`, which relies on the existence of a file called `zlib.lib` (not `libzlib.lib`). This was discussed in [another issue](https://github.com/microsoft/vcpkg/issues/39099).

### Reproducer

1. Create a hello world C++ project with cmake build system.
2. Add dependency on ROOT using `find_package(ROOT CONFIG REQUIRED)`.
3. Add dependency on ZLIB using `find_package(ZLIB REQUIRED)`.
4. Attempt to configure the project with cmake.

Expected result: the project configures successfully and can be built.
Actual result: the configuration fails, see [the issue referenced earlier](https://github.com/microsoft/vcpkg/issues/39099) for detailed logs.

### ROOT version

My build environment uses ROOT v6.26.10, but I confirmed that the bug is present in v6.32.00 as well.

### Installation method

pre-built binary

### Operating system

Windows

**Comment by petrmanek** [comment]
The following mitigation works in my code:

```cmake
# Find and configure ROOT
if(MSVC)
  # ROOT appears to mess up values of cmake variables, here we save their values so that we can later restore them
  set(TL_SAVED_FIND_LIBRARY_PREFIXES ${CMAKE_FIND_LIBRARY_PREFIXES})
  set(TL_SAVED_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
endif()
find_package(
  ROOT 6
  CONFIG
  REQUIRED
  COMPONENTS Core RIO Thread
)
if(MSVC)
  # ...and here we put them back
  set(CMAKE_FIND_LIBRARY_PREFIXES ${TL_SAVED_FIND_LIBRARY_PREFIXES})
  set(CMAKE_FIND_LIBRARY_SUFFIXES ${TL_SAVED_FIND_LIBRARY_SUFFIXES})
endif()
```

However, it would be super nice if `ROOTConfig.cmake` did this for us, since it changes cmake environment in the first place.

**Comment by bellenot** [comment]
Thanks for the report and the suggestion, the PR is on the way.

**Comment by petrmanek** [comment]
@bellenot Brilliant, thanks for prompt resolution! :rocket:

**Comment by bellenot** [comment]
> @bellenot Brilliant, thanks for prompt resolution! 🚀

You're very welcome!
