### ISSUE TITLE
[df] ProgressBar reporting on number of files is now broken 

### ISSUE THREAD

**Issue by martamaja10** [root-project/root#15736]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

While running a dataframe tutorial with the current master branch: df106_HiggsToFourLeptons, the number of files is now shown as 0 instead of 9 as expected. The issue arrises from this line: https://github.com/root-project/root/blob/00693233c08b5c63f684717a15115b96d5e60417/tree/dataframe/src/RInterfaceBase.cxx#L32 inside the GetNFiles function that is used by the ProgressBar. It was introduced with this commit: https://github.com/root-project/root/pull/15653/commits/bd5096500cda5cb98c8d87c17d3aef25424407ab# 

### Reproducer

root tutorials/dataframe/df106_HiggsToFourLeptons.C

### ROOT version

current master

### Installation method

na

### Operating system

na

**Comment by vepadulano** [comment]
Thanks for the report @martamaja10 ! Could you check that the linked PR also fixes the ProgressBar example?
