### ISSUE TITLE
`THStack` does not automatically shows negative bins

### ISSUE THREAD

**Issue by linev** [root-project/root#15740]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

If the first stack histogram has negative bin content - it will not be shown automatically.
The only chance to see negative bins is to set min/max values for THStack. 

`df106` macro draws such a stack and one bin is hidden from the drawing

### Reproducer

Here is a simple reproducer macro:
[hstack.C.txt](https://github.com/user-attachments/files/15551454/hstack.C.txt)

### ROOT version

master

### Installation method

build from source

### Operating system

OpenSUSE linux, Mac ...

**Comment by couet** [comment]
Thanks Serguei. I am on it.

**Comment by couet** [comment]
PR here: https://github.com/root-project/root/pull/15761/files

**Comment by couet** [comment]
Stacks with negative content generally don't function well. They are built by stacking bricks (1D histograms) or bins (1D histograms) on top of each other. If there's a negative brick in the middle, what should we do? This might need more explanation in the reference guide..

**Comment by linev** [comment]
> even a protection to forbid histograms with negative minimum.

If we do not want to support negative bins - one should issue warning in the code.

And you can reopen PR - for normal use-case first stacked histogram should be checked for minimal value

**Comment by couet** [comment]
I am making a new PR with an update of the doc and protection in the `THStack::Add`
