### ISSUE TITLE
[RF][HS3] ATLAS ttbar workspaces roundtrip

### ISSUE THREAD

**Issue by cburgard** [root-project/root#15756]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

An ATLAS analysis using top quarks is currently struggling to publish the HEPdata entry because of issues with the HS3 roundtrip-capability.

This needs to be fixed in a patch release ASAP.

This issue is WIP.

### Reproducer

@guitargeek has received the neccessary inputs.

### ROOT version

6.32.00

### Installation method

any

### Operating system

any

**Comment by dpiparo** [comment]
Thanks for reporting. Is this perhaps a duplicate of https://github.com/root-project/root/issues/15755 ?

**Comment by guitargeek** [comment]
No, we already know that these are separate problems, unfortunately

**Comment by dpiparo** [comment]
Thanks for the clarification and to @cburgard for the reports.
