### ISSUE TITLE
[RF][HS3] Higgs discovery workspaces roundtrip

### ISSUE THREAD

**Issue by cburgard** [root-project/root#15755]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

The 2012 Higgs discovery workspaces are currently not fully able to round-trip via the HS3 JSON format due to an issue with the way the Constraint Terms are encoded. 

This needs to be fixed in a patch release ASAP.

This issue is WIP.

### Reproducer

@guitargeek has received the neccessary inputs.

### ROOT version

6.32.00

### Installation method

any

### Operating system

any

**Comment by guitargeek** [comment]
Closed by #14733.
