### ISSUE TITLE
Where can I get arm64 linux binary build?

### ISSUE THREAD

**Issue by Real-YuZhe** [root-project/root#15782]
### Feature description

where can I get arm64 linux binary build on Ubuntu port (arm64)

**Comment by dpiparo** [comment]
Hi, thanks for reporting. At the moment we do not provide ARM images for linux. We plan to add arm nodes to our CI, but it will take a bit of time. In the meanwhile, you can rely on the various package managers providing ROOT or build it from sources (https://root.cern/install/#build-from-source). We will provide the needed support in case you encounter difficulties here https://root-forum.cern.ch/
