### ISSUE TITLE
JS ROOT does not draw tprofile2d correctly with "TEXT" draw option

### ISSUE THREAD

**Issue by will-cern** [root-project/root#15791]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

If you go to: https://root.cern/js/latest/examples.htm#misc_profile2d and select "TEXT" for the "Draw with" option, instead of drawing the bin contents, it will draw the bin entries. 

While I'm here I will perhaps say it would be nice if it were possible to draw the bin entries for tprofiles and tprofile2d, so while this is a bug, adding a way to do the entries would still be appreciated

### Reproducer

See above

### ROOT version

latest

### Installation method

pre-built

### Operating system

all

**Comment by linev** [comment]
Fixes are in #15826 and #15827 PRs for `master` and `6.32` branches respectively

**Comment by will-cern** [comment]
Thanks. Did you see my feature request for having a way to draw the BinEntries histogram for TProfile and TProfile2D as well? Or would you like me to open a separate feature request issue for that? Essentially I'd like a way to do the equivalent of the following in the JSROOT widget: `prof->ProjectionXY("_pxy","B")->Draw("....")` ... this will allow us to draw the denominator distribution in cases where we use profiles for efficiencies (where the weight is 1 for a pass and 0 for a fail).

**Comment by linev** [comment]
> Or would you like me to open a separate feature request issue for that

Yes please.
