### ISSUE TITLE
[Hist] Backwards compatibility broken for `THnSparseL` in 6.32

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#15874]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Backwards compatibility for `THnSparseL` was broken in 6.32 by #8546, @ferdymercury @vepadulano.

### Reproducer

Write a `THnSparseL` to a file e.g. with ROOT 6.30.06:
```c++
void write_thnsparse_l()
{
   std::unique_ptr<TFile> file{TFile::Open("hist.root", "RECREATE")};
   Int_t bins[2] = {10, 20};
   Double_t xmin[2] = {0., -5.};
   Double_t xmax[2] = {10., 5.};
   THnSparseL hist{"hist", "hist", 2, bins, xmin, xmax};
   file->WriteObject(&hist, "hist");
}
```
Try to read it with ROOT 6.32.00 (or `master`):
```bash
root hist.root -e 'hist'
```
You'll get this error:
```txt
Error in <TClingCallFunc::make_ctor_wrapper>: Failed to compile
  ==== SOURCE BEGIN ====
__attribute__((used)) extern "C" void __ctor_0(void** ret, void* arena, unsigned long nary)
{
   if (!arena) {
      if (!nary) {
         *ret = new THnSparseT<TArrayL>;
      }
      else {
         *ret = new THnSparseT<TArrayL>[nary];
      }
   }
   else {
      if (!nary) {
         *ret = new (arena) THnSparseT<TArrayL>;
      }
      else {
         *ret = new (arena) THnSparseT<TArrayL>[nary];
      }
   }
}

  ==== SOURCE END ====
Error in <TClingCallFunc::ExecDefaultConstructor>: Called with no wrapper, not implemented!
Error in <TClingClassInfo::New()>: Call of default constructor failed to return an object for class: THnSparseT<TArrayL>
Error in <TClass::New>: cannot create object of class THnSparseT<TArrayL>
Error in <TKey::ReadObj>: Cannot create new object of class THnSparseT<TArrayL>
IncrementalExecutor::executeFunction: symbol '_ZN10THnSparseTI7TArrayLE5ClassEv' unresolved while linking [cling interface function]!
You are probably missing the definition of THnSparseT<TArrayL>::Class()
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN10THnSparseTI7TArrayLE8StreamerER7TBuffer' unresolved while linking [cling interface function]!
You are probably missing the definition of THnSparseT<TArrayL>::Streamer(TBuffer&)
Maybe you need to load the corresponding shared library?
```

### ROOT version

ROOT 6.32.00 upwards.

### Additional context

Thanks do @philippe554 for catching this! This issue is important for project HighLO because we're using `THnSparseL` as a container for reduced data.

**Comment by ferdymercury** [comment]
Yep, I know. I warned about this problem up to 3 times in that PR, insisting that it had nothing to do with the new feature that I wanted to add:

https://github.com/root-project/root/pull/8546#issuecomment-1279199373
https://github.com/root-project/root/pull/8546#issuecomment-1320906798
https://github.com/root-project/root/pull/8546#issuecomment-1952708524

**Comment by pcanal** [comment]
I also missed it at the time.  Sorry.  

To avoid this, we should also add test of the backward compatibility (especially the reading of older file).

**Comment by vepadulano** [comment]
It's enough to add back the dictionary for `THnSparse<TArrayL>` to read back the histogram. Now I'm also working on a trasparent conversion from `THnSparseL` written as `THnSparse<TArrayL>` to `THnSparseL` read as `THnSparse<TArrayL64>`, let's see if I can make that work.
