### ISSUE TITLE
Initialize TRatioPlot margins from Pad margins set in the current style

### ISSUE THREAD

**Issue by Zehvogel** [root-project/root#15883]
### Explain what you would like to see improved and how.

At the moment the Pad margins of a TRatioPlot are always initialised with fixed values
https://github.com/root-project/root/blob/0a395208b9cb64188b11fd48eaa81128dd9c0acf/graf2d/gpad/inc/TRatioPlot.h#L128-L136
resulting in the plots having different margins than other plots and therefore also a different aspect ratio, making quick by-eye comparisons harder. (When using a custom style that changes the Pad margins)

While I understand that the Top and Bottom margins require a bit more tuning for this kind of plot, at least the Left and Right margin could be set from the PadLeftMargin and PadRightMargin values in gStyle.

This would result in TRatioPlots having the same horizontal width as other plots (histograms, graphs, etc.) by default.

### ROOT version

any

### Installation method

any

### Operating system

any

**Comment by dpiparo** [comment]
Hi @Zehvogel , thanks for the suggestion. I assigned this to @couet . Would you be willing to give this improvement a try and submit a PR? We'd help you in the process...

**Comment by Zehvogel** [comment]
I can give it a try, I cannot say how long it will take though
