### ISSUE TITLE
Broken plot .C macros for default Name() argument in plotOn()

### ISSUE THREAD

**Issue by lmeyergarcia** [root-project/root#15887]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Dear experts,

I noticed that sometimes, when trying to produce .C macros for my figures, the `SaveAs()` function would return broken macros. I narrowed it down to the `Name()` arguments passed to the `plotOn()` function when plotting RooFit pdf's. The problem seems to be that the default `Name()` value contains special characters (`[` and `]`, in this case), and these characters end up in variable names in the .C macro.

I have included a reproducer below (`test_plot_macros.cpp`) which produces three .C macros, two of which are broken as described above.
For instance, in `plot1.C` (one of the produced macros), one can find invalid code such as 
```cpp
Double_t pdf_Norm[x]_fx1[114] = {
   -10.2002,
   -10.2,
...
```

Would it be possible to filter these special characters when producing the macros?

### Reproducer

Create a file `test_plot_macros.cpp` containing the script below and run `root test_plot_macros.cpp`.

```cpp
#include "TCanvas.h"

#include "RooArgSet.h"
#include "RooDataSet.h"
#include "RooGaussian.h"
#include "RooPlot.h"
#include "RooRealVar.h"

using namespace RooFit;

void test_plot_macros() {
    // Create a PDF
    RooRealVar x("x", "x", -10, 10);
    RooRealVar mean("mean", "mean", 0, -10, 10);
    RooRealVar width("width", "width", 2, 0, 5);
    RooGaussian gaus("pdf", "pdf", x, mean, width);

    // Generate some data
    RooDataSet* data = gaus.generate(RooArgSet(x), Name("data"), NumEvents(2000));

    // Plots
    TCanvas* c = new TCanvas("c");

    // Plot 1
    // Broken .C macro because of default pdf "Name()"
    RooPlot* frame1 = x.frame();
    data->plotOn(frame1);
    gaus.plotOn(frame1);
    frame1->Draw();
    c->SaveAs("./plot1.png");
    c->SaveAs("./plot1.C");

    // Plot 2
    // Not broken .C macro because of explicit (and safe) "Name()" configuration
    RooPlot* frame2 = x.frame();
    data->plotOn(frame2);
    gaus.plotOn(frame2, Name("gaus"));
    frame2->Draw();
    c->SaveAs("./plot2.png");
    c->SaveAs("./plot2.C");

    // Plot 3
    // Broken .C macro again because special charecters are not filtered from "Name"
    RooPlot* frame3 = x.frame();
    data->plotOn(frame3);
    gaus.plotOn(frame3, Name("a+b"));
    frame3->Draw();
    c->SaveAs("./plot3.png");
    c->SaveAs("./plot3.C");
}
```

### ROOT version

6.24.06

### Installation method

Built from source

### Operating system

Ubuntu 22.04

**Comment by dpiparo** [comment]
Thanks for the report: I see this issue in 6.32 and master as well. @couet , could you please take care of this?

**Comment by couet** [comment]
Sure, I will take care.

**Comment by couet** [comment]
Your macro generates three .C scripts: plot1.C, plot2.C, and plot3.C. I ran each of them separately, and they all executed successfully with the ROOT master version installed on my Mac. I recently made some fixes in that area, so it's possible that these changes have resolved your issue as well. To confirm, could you please send one of your non-working plot[1,2,3].C files? This way, I can compare it with the corresponding file I just generated on my Mac.

**Comment by lmeyergarcia** [comment]
Sure, here's the plot1.C macro I obtain:  [plot1.C.txt](https://github.com/user-attachments/files/15913609/plot1.C.txt)

Please note I've added `.txt` to the file name because github won't let me upload .c files ¯\\_(ツ)_/¯

**Comment by couet** [comment]
Indeed we clarified with @dpiparo . I am using the master version in which the problem is fixed. The variable name I get is `Double_t pdf_NormoBxcB_fx1[114] ` ... so the brackets have been replaced. I will backport the fix to 6.32.

**Comment by lmeyergarcia** [comment]
Thanks!

**Comment by couet** [comment]
PR is done.
