### ISSUE TITLE
[Docs] Incorrect URL in github release for git tag v6.32.02

### ISSUE THREAD

**Issue by op3** [root-project/root#15881]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

The [github release for git tag v6.32.02](https://github.com/root-project/root/releases/tag/v6-32-02) contains an incorrect URL:

The *Release notes* (at the very top) links to `https://root.cern/doc/v630/release-notes.html#release-6.32.02`, but obviously it should be `https://root.cern/doc/v632/release-notes.html#release-6.32.02` instead.

(`s/v630/v632/`)

It’s correct for [v6.32.00](https://github.com/root-project/root/releases/tag/v6-32-00).

### Reproducer

See `https://github.com/root-project/root/releases/tag/v6-32-02`

### ROOT version

6.32.02

### Installation method

N/A

### Operating system

N/A

**Comment by ferdymercury** [comment]
Thanks for the catch. It has been fixed now.
