### ISSUE TITLE
ROOT reference docs are getting increasingly unhandy....

### ISSUE THREAD

**Issue by MarkusFrankATcernch** [root-project/root#15906]
### Explain what you would like to see improved and how.

In the old times, the list of classes implemented by ROOT was 1-2 clicks away from the main ROOT page. Now on the 
ROOT reference doc page, there is no useful information anymore except for beginners.
I tried all links and nowhere I would bet to the class list and the doxygen pages.
Sorry, but this is somehow sub-optimal.

### ROOT version

Doc bad since 6.16. ROOT 6.16 was still OK: the "All Classes" link was there:  https://root.cern/doc/v616/

### Installation method

Main ROOT home page

### Operating system

Linux

**Comment by couet** [comment]
Thanks, Markus for your remark. I will check and try to improve.

**Comment by MarkusFrankATcernch** [comment]
@couet Thanks a lot Olivier. The doxygen info is really good and important. It is a real pity since it looks gone (or I could not find it anymore).

**Comment by ferdymercury** [comment]
> (or I could not find it anymore).

On the left panel, there is the link to "All Classes"

![image](https://github.com/root-project/root/assets/10653970/1065ede3-efa2-4741-af5e-369e395f2260)

**Comment by couet** [comment]
@MarkusFrankATcernch, as @ferdymercury mentioned, the link to all classes is still available on the left side, along with all the other links that were previously in the top bar (in version 6.16). Only the placement has changed.

**Comment by MarkusFrankATcernch** [comment]
Yes. Issue is clarified.

- I can see the classlist on the browser at home and in the office.
- I cannot see it at the pit .... but this all hints to a funny browser setup there. I have to investigate.

Thanks a lot to all for the clarification and please take my apologies for 
creating noise about an issue which was clearly my fault!

Thanks a lot!

**Comment by ferdymercury** [comment]
You are welcome!

The left panel bar is 'draggable' with the mouse, so it might have happened that it's too narrow to be seen on a screen. This usually happens also if you enter from your phone. But there, you can drag it wider, too.

![image](https://github.com/root-project/root/assets/10653970/8c13278d-91d2-4d81-bc19-bc376d7d6199)

**Comment by couet** [comment]
> I cannot see it at the pit 

Can you post a screen dump of what you see at the pit?

**Comment by MarkusFrankATcernch** [comment]
I have found it. It was the script blocker.
