### ISSUE TITLE
Clad issues with `MacOSX15.0.sdk`

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#15912]
After https://github.com/root-project/root/pull/15900, there should be four failing tests due to Clad:
```
The following tests FAILED:
        206 - gtest-math-mathcore-test-CladDerivatorTests (Failed)
        232 - gtest-roofit-histfactory-test-testHistFactory (Failed)
        235 - gtest-roofit-hs3-test-testRooFitHS3 (Failed)
        267 - gtest-roofit-roofitcore-test-testRooFuncWrapper (Failed)
```

They seem somehow related to `__builtin_pow`. For this reason, to keep green builds, clad was disabled for mac-beta in https://github.com/root-project/root/pull/15910.

### Reproducer

Install `MacOSX15.0.sdk`, build ROOT and try to run all tests.

### ROOT version

`master`

### Installation method

build from source

### Operating system

macOS

**Comment by vgvassilev** [comment]
This should be fixed now, can you check and close that issue?

**Comment by hahnjo** [comment]
We need a Clad release (or apply a patch in the ROOT sources), and re-enabled the `clad` on `mac-beta` before this issue can be closed

**Comment by vgvassilev** [comment]
A new release is planned on Aug 9th.
