### ISSUE TITLE
roottest-root-hist-h2root broken on Alma9 march=native builds

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#15936]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

The test roottest-root-hist-h2root broken on Alma9 march=native builds. This PR https://github.com/root-project/root/pull/15935 deactivated FORTRAN on Alma9 march=native to avoid confusing developers with "expected failures" (broken windows). The test should be fixed and the PR reverted ASAP.

### Reproducer

Just run the aforementioned test on the aforementioned platform.

### ROOT version

master

### Installation method

from sources

### Operating system

Linux, Alma9, march=native on modern Intel/AMD

**Comment by hahnjo** [comment]
see also https://github.com/root-project/root/issues/14155

**Comment by couet** [comment]
and https://github.com/root-project/root/pull/15915

**Comment by dpiparo** [comment]
The PR above did not fix anything. Anyway, consolidating into one single issue https://github.com/root-project/root/issues/14155
