### ISSUE TITLE
AttributeError: Failed to get attribute CreateScopeProxy from ROOT 

### ISSUE THREAD

**Issue by kamranahmmed786** [root-project/root#15957]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

I’m a beginner so apologies if this is an annoying question, I’m trying to run Delphes which uses ROOT for Analysis

here is the command: DelphesAnalysis/ControlPlots.py -i …/…/delphes_output.root -o controlPlots_demo.root --all -c topConfig.py

i get following error:

“File “/media/kami/Backup/MG5_aMC_v3_5_4/pp-tt/Events/run_01_decayed_1/Delphes/python/DelphesAnalysis/ControlPlots.py”, line 45, in
from DelphesAnalysis import Delphes
File “/home/kami/1Me/Tools/MG5_aMC_v2_9_19/Delphes/python/DelphesAnalysis/Delphes.py”, line 17, in
root.CreateScopeProxy( “Event” ).str = Event__str
File “/home/kami/1Me/Tools/root/root_install/lib/ROOT/_facade.py”, line 164, in _fallback_getattr
raise AttributeError(“Failed to get attribute {} from ROOT”.format(name))
AttributeError: Failed to get attribute CreateScopeProxy from ROOT”

when i checked ROOT library, there’s no CreateScopeProxy.h file there

### Reproducer

you can reproduce the issue with running this command while in Delphes/python directory,

DelphesAnalysis/ControlPlots.py -i …/…/delphes_output.root -o controlPlots_demo.root --all -c topConfig.py

### ROOT version

ROOT 6.32.02

### Installation method

Built from source, Compiler: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Operating system

Ubuntu 22.04.4 LTS

**Comment by hahnjo** [comment]
Let's follow up on this in the forum: https://root-forum.cern.ch/t/attributeerror-failed-to-get-attribute-createscopeproxy-from-root/60053
