### ISSUE TITLE
outdated help links

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#15962]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Most of the links in the source code starting with http://root.cern.ch/root/html/  point to a no longer existing URL

### Reproducer

grep -r 'root/html' /opt/root_src/*

Another way to reproduce it is to go open a TRootBrowser, right click on a tree, "Scan", then click on "Online Help" button.

### ROOT version

```
ROOT v6.32.00
Built for linuxx8664gcc on May 28 2024, 05:02:02
From tags/v6-32-00@v6-32-00
With c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Binary directory: /opt/root/bin
```

### Installation method

Binary Release

### Operating system

Ubuntu 22.04

### Additional context

It could be that changing to `root/htmldoc` solves most of the 404s.

**Comment by ferdymercury** [comment]
Thanks a lot!! Missing a couple of occurrences in one file, now after: https://github.com/root-project/root/pull/16276/files

**Comment by dpiparo** [comment]
Thanks @ferdymercury ! Given this change https://github.com/root-project/root/pull/16267/files#diff-dd81606cd750b320d9ed46d043eb5e5dceaf7e7dbcf2d4934cae69bbfc27138fR406 , which deprecates THtml (it will be dropped in 6.36), I would like to close this item nevertheless: would it be ok for you?
