### ISSUE TITLE
Problems with TUri compilation

### ISSUE THREAD

**Issue by MarkusFrankATcernch** [root-project/root#15986]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

I use often the `TUri` class to precompile file names when opening files.
In the past all this worked:
```
TUri uri1("EcalBarrel.gdml");
TUri uri2("file://EcalBarrel.gdml");
TUri uri3("file://./EcalBarrel.gdml");
```
now after sync'ing with master this does not work anymore. Any invocation results in a SEGV.
- Is this a real problem in ROOT  or
- What do I wrong
I know one should not complain about the HEAD, but this looks to be very substantial....

Thanks a lot for clarifying.

### Reproducer

from the ROOT prompt:

```
$> root.exe
   ------------------------------------------------------------------
  | Welcome to ROOT 6.33.01                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jul 04 2024, 12:35:26                 |
  | From heads/master@v6-31-01-2515-g03703814ef                      |
  | With g++-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0                |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root[0] TUri uri("blabla.txt")
```

Result:
```
Error in <Compile>: compilation of TPRegexp(^(/(?:[[:alpha:][:digit:]-._~!$&'()*+,;=:@]|%[0-9A-Fa-f][0-9A-Fa-f])*)*$) failed at: 25 because invalid range in character class

 *** Break *** segmentation violation
```

### ROOT version

Head

### Installation method

Build from source (HEAD)

### Operating system

Linux / Ubuntu

**Comment by MarkusFrankATcernch** [comment]
@ferdymercury Thanks for chasing up!

**Comment by ellert** [comment]
@MarkusFrankATcernch @ferdymercury See #15988 for a fix.
