### ISSUE TITLE
`thisroot.sh` tries to drop the wrong lib paths from the existing environment

### ISSUE THREAD

**Issue by wshanks** [root-project/root#16024]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

`thisroot.sh` has a `clean_environment` function that tries to remove previously added ROOT entries from various path variables:

https://github.com/root-project/root/blob/0d47873e53e2cbf6980146fd2e657629890c15d6/config/thisroot.sh#L32-L47

However, for the lib paths the entry removed is the `lib` subdirectory:

https://github.com/root-project/root/blob/0d47873e53e2cbf6980146fd2e657629890c15d6/config/thisroot.sh#L41

while the path that gets added is the `@libdir@` variable:

https://github.com/root-project/root/blob/0d47873e53e2cbf6980146fd2e657629890c15d6/config/thisroot.sh#L101

For my installation (which I think is pretty standard), `@libdir@` resolves to the `lib/root` subdirectory. So the path entries do not match and no entry was removed. This means that sourcing `thisroot.sh` multiple times causes the path variables to accumulate ROOT entries.

### Reproducer

I am using ROOT built from source like this:

```
cmake3 /opt/src/root \
       -DCMAKE_INSTALL_PREFIX=/opt/root \
       -DPYTHON_EXECUTABLE=${python_executable} \
       -DPYTHON_INCLUDE_DIR=${python_include_dir} \
       -DPYTHON_LIBRARY=${python_include_dir} \
       -Dpython3:BOOL=ON \
       -Dsoversion:BOOL=ON \
       -Dtmva:BOOL=OFF \
       -Dgnuinstall:BOOL=ON \
       -Wno-de
cmake3 --build . --clean-first --target install
```

I think this is pretty standard and that I am not doing anything special to cause the build to use the `lib/root` subdirectory instead of the `lib` subdirectory. My memory from experimenting in the past is that the `root` subdirectory under `lib/` gets added when using `gnuinstall=OFF` (and if `gnuinstall=ON` then I don't think you usually need to run `thisroot.sh` since it is a system wide installation).

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.30/02                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jun 19 2024, 14:56:30                 |
  | From heads/master@tags/v6-30-02                                  |
  | With c++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)                 |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
  ------------------------------------------------------------------
```

### Installation method

Build from source

### Operating system

Linux (RHEL 8)

**Comment by ferdymercury** [comment]
It's because of https://github.com/root-project/root/blob/master/cmake/modules/RootInstallDirs.cmake#L53

**Comment by wshanks** [comment]
Thanks @ferdymercury! Reading things again after looking at the line you pointed to, I realized that I had `gnuinstall=ON` when it would be more correct to have it set to `gnuinstall=OFF` when using `thisroot.sh`  :disappointed: but it has been working fine for me other than not cleaning the paths properly.
