### ISSUE TITLE
TColor::GetFreeColorIndex()  returns index that is already used

### ISSUE THREAD

**Issue by bgrube** [root-project/root#16051]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

There seems to be a subtle bug in the way colors are registered, which in the case described below makes `TColor::GetFreeColorIndex()` return a color index that is already used by a user-defined color. 

This happens when I load a canvas from a `.root` file where the canvas was saved in a separate ROOT session that defined a new fill color AND a palette using `gStyle->SetPalette()`.

The bug appears in 6.32.00 and 6.32.02 but NOT in 6.30.08.

### Reproducer

1. Download minimal reproducible example at https://gist.github.com/bgrube/a939a059fd397129efacb8f0643ae022
2. `source /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.32.02/x86_64-almalinux9.4-gcc114-opt/bin/thisroot.sh`
3. `python3 ./TColorBug.py`
4. Output
	```
	Creating test file in a separate process
	Color:1179  Red=1.000000 Green=1.000000 Blue=1.000000 Alpha=1.000000 Name=myColor
	Info in <TCanvas::SaveAs>: ROOT file TColorBug.root has been created
	Reading test file
	ROOT.TColor.GetFreeColorIndex() = 1179
	Color:1179  Red=1.000000 Green=1.000000 Blue=1.000000 Alpha=1.000000 Name=myColor
	Wrong behavior: index 1179 returned by ROOT.TColor.GetFreeColorIndex() is already used
	```

### ROOT version

6.32

### Installation method

pre-built binary

### Operating system

Linux

**Comment by dpiparo** [comment]
Thanks: I can reproduce the problem.

**Comment by couet** [comment]
I have tried the following C macro:
```
void createTestFile() {
  auto myColor = new TColor(TColor::GetFreeColorIndex(), 1, 1, 1, "myColor", 1);
  myColor->Print();
  int myColorIndex = myColor->GetNumber();
  gStyle->SetFillColor(myColorIndex);
  gStyle->SetPalette(kViridis); // <- if this line is commented out, the bug does not occur
  auto canv = new TCanvas("canv", "canv");
  canv->SaveAs("TColorBug.root");
}

void readTestFile() {
  auto file = new TFile("TColorBug.root", "READ");
  TCanvas *c = (TCanvas *)file->Get("canv");
  int freeColorIndex = TColor::GetFreeColorIndex();
  printf("TColor::GetFreeColorIndex() = %d\n", freeColorIndex);
}

void TColorBug() {
   createTestFile();
   readTestFile();
   TColor::ListColors(0,0,kTRUE);
}
```
Seems to me the behavior is correct in both cases, without without kViridis defined.

**Comment by dpiparo** [comment]
Hi @bgrube , would you have a comment?

**Comment by bgrube** [comment]
Many thanks Danilo and Olivier for picking this up so quickly! The issue appears only when `TColorBug.root` is loaded in a new ROOT session. Sorry for not being clear about this in my original post. If I first run `createTestFile();` from Olivier's macro to create the .root file and then close ROOT and start a new ROOT session that only runs `readTestFile();`, `TColor::GetFreeColorIndex();`returns the index of the already defined `myColor`. So the problem seems to be related to how custom colors that are not yet existing in  the ROOT session are restored from a .root file.

**Comment by ferdymercury** [comment]
> that are not yet existing in the ROOT session are restored from a .root file.

I proposed a PR: https://github.com/root-project/root/pull/16139 in case you want to try.

**Comment by bgrube** [comment]
#16139 fixes the problem for me. Thanks a lot!

**Comment by couet** [comment]
merged !
