### ISSUE TITLE
[ntuple] Cannot create RFieldBase for signed char

### ISSUE THREAD

**Issue by amete** [root-project/root#16135]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Since last Friday's dev3LCG nightly (i.e. from 26/7) we cannot create a field for `signed char`. This used to work fine w/ the LCG dev3 nightly from 25/7.

Here is the error message:

```
Error in <TRint::HandleTermInput()>: ROOT::Experimental::RException caught: unknown type: signed char (unchecked RResult access!)
At:
  ROOT::Experimental::RFieldBase::Create(const std::string&, const std::string&, const std::string&, bool)::<lambda(const std::string&)> [/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/tree/ntuple/v7/src/RField.cxx:629]
  static ROOT::Experimental::RResult<std::unique_ptr<ROOT::Experimental::RFieldBase> > ROOT::Experimental::RFieldBase::Create(const std::string&, const std::string&, const std::string&, bool) [/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/tree/ntuple/v7/src/RField.cxx:852]
  static ROOT::Experimental::RResult<std::unique_ptr<ROOT::Experimental::RFieldBase> > ROOT::Experimental::RFieldBase::Create(const std::string&, const std::string&) [/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/tree/ntuple/v7/src/RField.cxx:592]

```

### Reproducer

To setup ROOT:
```
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
lsetup "asetup Athena,main--dev3LCG,latest"; # any version after r26 (inclusive)
```

To reproduce the error:
```
root [0] using namespace ROOT::Experimental;
root [1] auto field = RFieldBase::Create("foo", "signed char").Unwrap();
```

### ROOT version

dev3/Fri/ROOT/HEAD (from 26/7)

### Installation method

LCG dev3 nightly build

### Operating system

AlmaLinux release 9.4 (Shamrock Pampas Cat)

**Comment by hahnjo** [comment]
Hi @amete, I intentionally removed support for `signed char` in commit https://github.com/root-project/root/commit/4a2fca87c5d95b07d412617f4af641054398db4e. As noted, it was the only special case where the `signed` modifier in `signed <type>` was normalized to `<type>`. What is the use case for `signed char`, can you just pass `char`?
