### ISSUE TITLE
Python string from RCutFlowReport

### ISSUE THREAD

**Issue by toicca** [root-project/root#16138]
### Feature description

Currently there's no native way to get the output of a `RCutFlowReport::Print()` as a string object in PyROOT, which would allow for users to use string manipulation to pick out information from the efficiencies and do other processing on the cutflow information. The string could be given as a separate method from `Print()` (~`RCutFlowReport::GetString()`) or as a return value of the `Print()`.

See [discussion on the ROOT forum](https://root-forum.cern.ch/t/saving-the-print-of-a-root-rcutflowreport-in-python/60351)

### Alternatives considered

@devajithvs gave a temporary solution as a Python function in the ROOT forum discussion:
```
# Python implementation of the C++ Print method
def cut_info_string(report):
    begin = report.begin()
    end = report.end()
    
    allEntries = 0 if begin == end else begin.__deref__().GetAll()
    result = ""
    it = begin
    while it != end:
        ci = it.__deref__()
        name = ci.GetName()
        pass_val = ci.GetPass()
        all = ci.GetAll()
        eff = ci.GetEff()
        cumulativeEff = 100.0 * float(pass_val) / float(allEntries) if allEntries > 0 else 0.0
        
        result+=f"{name:10}: pass={pass_val:<10} all={all:<10} -- eff={eff:.2f} % cumulative eff={cumulativeEff:.2f} %"
        
        it.__preinc__()
    return result
```

**Comment by dpiparo** [comment]
Hi,

Thanks for the report. 
` pick out information from the efficiencies and do other processing on the cutflow information.`
What is missing in the solution offered on the forum? The correct way to programmatically access the information about the cuts has been showcased by @devajithvs and should be enough for all use cases (there is nothing more to access in the CutFlowReport).
Could you elaborate on the use case for which the string is required?

**Comment by toicca** [comment]
The solution given in the forum works for all the use cases I can think of, so nothing is really missing. I just feel it would be good to have this function as a part ROOT instead of something that needs to picked out from the forums.

As you point out, there's really nothing crucial missing and everything can be implemented starting from the current methods of CutFlowReport, so if you feel that the feature would just add bloat it's OK for me to dismiss this request.

On a side note, can you maybe explain why redirecting the output as in 
```
import sys
import ROOT
rdf = ROOT.RDataFrame("Events", "root://eospublic.cern.ch//eos/opendata/cms/Run2016H/SingleMuon/NANOAOD/UL2016_MiniAODv2_NanoAODv9-v1/120000/61FC1E38-F75C-6B44-AD19-A9894155874E.root")
rdf = rdf.Filter("nMuon == 2", "2 muons")
original_out = sys.stdout
with open("output.txt", "w") as file:
    sys.stdout = file
    print("hello") # this will be in the file
    rdf.Report().Print() # output of this will be in terminal

sys.stdout = original_out
```
doesn't work?

**Comment by dpiparo** [comment]
Hi,

Thanks for the input. I think it's because you are trying to capture from Python an output which is printed from a C++ library (see e.g. https://stackoverflow.com/questions/24277488/in-python-how-to-capture-the-stdout-from-a-c-shared-library-to-a-variable). I think the best option at the moment is really to have a report2string function if needed.
E.g. (following the example of Dev)
```python
import ROOT

def Report2Str(report):
    begin = report.begin()
    if begin == report.end(): return ""
    allEntries = begin.GetAll()
    result = ""
    for ci in report:
        name = ci.GetName()
        pass_val = ci.GetPass()
        all = ci.GetAll()
        eff = ci.GetEff()
        cumulativeEff = 100.0 * float(pass_val) / float(allEntries) if allEntries > 0 else 0.0
        result+=f"{name:10}: pass={pass_val:<10} all={all:<10} -- eff={eff:.2f} % cumulative eff={cumulativeEff:.2f} %"
    return result

rdf = ROOT.RDataFrame(128)
rdf = rdf.Define("nMuon", "int(gRandom->Uniform(10.))")
rdf = rdf.Filter("nMuon == 2", "2 muons")
rep = rdf.Report()

myStr = Report2Str(rep)
```
