### ISSUE TITLE
Build can not recover from partial 'cleanup'

### ISSUE THREAD

**Issue by pcanal** [root-project/root#16227]
Is It 'just me' or does the master (intentionally ?) no longer re-download the tar files for the builtins.  I.e.:

```
cmake
ninja
rm -rf *-prefix builtins
ninja
```
used to work and does not work anymore (and no I don't remember when was the last time I saw it worked).

**Comment by bellenot** [comment]
It works for me...

**Comment by dpiparo** [comment]
The very command
```
cmake
ninja
rm -rf *-prefix builtins
ninja
```
works also on macos14.
I propose to close the issue and to rediscuss the matter after collecting more info.

**Comment by pcanal** [comment]
Indeed, I can't re produce it anymore either.  Thanks for checking
