### ISSUE TITLE
JSROOT not drawing bins with content=0 but entries > 0 in TProfile2D

### ISSUE THREAD

**Issue by will-cern** [root-project/root#16244]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

JSROOT isn't drawing the bins of TProfile2D that have a content of 0 but non-zero entries. This is different behaviour to regular ROOT (see reproducer).
I'll also perhaps remark here that it would be good if the tooltip for JSROOT over TProfile2D would show both the 'content' and 'entries' of the bin, at the moment it shows the content, but misleadingly shows it under entries, e.g. shows "entries=X" for a bin with content=X. 

### Reproducer

Here's a reproducer:

```
%jsroot on
import ROOT
p2 = ROOT.TProfile2D("p2","p2",10,0,10,10,0,10)
p2.Fill(4,4,-1);p2.Fill(6,6,0);p2.Fill(3,3,1)
p2.Draw("COL1Z")
ROOT.gPad.GetCanvas().Draw()
```
vs drawing with jsroot off -- the bin that has a value of 0 in it is drawn in regular ROOT, but not in jsroot

![Screenshot 2024-08-15 at 14 00 16](https://github.com/user-attachments/assets/6c6d717e-f779-4476-bdc3-43c4b842adf1)
![Screenshot 2024-08-15 at 14 00 23](https://github.com/user-attachments/assets/65c72733-fcc3-4d3c-aee5-18bbb3c4b468)

### ROOT version

latest

### Installation method

pre-built

### Operating system

all

**Comment by dpiparo** [comment]
Thanks for the feedback @will-cern ! The expert is now in the loop.

**Comment by linev** [comment]
It was pure JSROOT problem. Fixed in https://github.com/root-project/jsroot/commit/5480b2aaca1ab46438f259540f219abb81905a41 commit. Will be applied soon into the master

**Comment by linev** [comment]
I add provided TProfile2D example to JSROOT testing: https://jsroot.gsi.de/dev/examples.htm?more#tprofile2d_neg
