### ISSUE TITLE
Iterating with a range for does one extra iteration

### ISSUE THREAD

**Issue by ktf** [root-project/root#16249]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

The following code:

```
void foo() {
  std::unique_ptr<TFile> digitfile(TFile::Open("emcaldigits.root", "READ"));
  auto treereader = std::make_unique<TTreeReader>(static_cast<TTree*>(digitfile->Get("o2sim")));
  std::cout << treereader->GetEntries() << std::endl;
  TTreeReaderValue<std::vector<o2::emcal::Digit>> digitbranch(*treereader, "EMCALDigit");
  TTreeReaderValue<std::vector<o2::emcal::TriggerRecord>> triggerbranch(*treereader, "EMCALDigitTRGR");
  for (auto &d : *treereader) {
    std::cout << "Foo" << std::endl;
  }
}
```

iterates once on an empty tree (0 entries). Is that expected?

### Reproducer

See above.

### ROOT version

6.30.0x

### Installation method

aliBuild

### Operating system

Linux on ARM, macOS

**Comment by dpiparo** [comment]
Thanks @ktf  for reporting this. We are looking into this.

**Comment by ktf** [comment]
Using `while (treereader->Next())` works as expected.

**Comment by dpiparo** [comment]
Thanks, that's indeed correct, and that is why for example there is no trace of this in RDataFrame usages/tests. We'll figure this out.

**Comment by ktf** [comment]
Thanks!
