### ISSUE TITLE
tutorial-rcanvas-df104-py

### ISSUE THREAD

**Issue by pcanal** [root-project/root#16252]
> 1261 - tutorial-rcanvas-df104-py (Failed)

This failure seems to be linked to memory limitation.  On my node there is 48 cores but the `ulimit` is set to 16Gb.  When reducing the number of cores down to 35 cores then the test starts to sometimes complete sometimes fails.
The error output sometimes contains:
```
RDataFrame::Run: event loop was interrupted
RDataFrame::Run: event loop was interrupted
RDataFrame::Run: event loop was interrupted
RDataFrame::Run: event loop was interrupted
RDataFrame::Run: event loop was interrupted
```
and always contains:
```
Traceback (most recent call last):
  File "/github/home/ROOT-CI/build/tutorials/rcanvas/df104.py", line 89, in <module>
    ROOT.RDF.RunGraphs([hists[s] for s in ["ggH", "VBF", "data"]])
cppyy.gbl.std.bad_alloc: unsigned int ROOT::RDF::RunGraphs(vector<ROOT::RDF::RResultHandle>) =>
    bad_alloc: std::bad_alloc
```

**And indeed, the process easily reaches 16Gb.  With 32 cores, the peak is 15Gb.**

**Comment by pcanal** [comment]
The problem also affects:
* `tutorials/dataframe/df102_NanoAODDimuonAnalysis.py`
* `tutorials/dataframe/df104_HiggsToTwoPhotons.py`

**Comment by dpiparo** [comment]
I assigned the issue to @linev .

**Comment by dpiparo** [comment]
does the reproducer requires the new graphics?

**Comment by dpiparo** [comment]
@pcanal , I made some profiling. The new graphics is not to blame. I profiled the process with memray on a machine with 12 workers and the memory peaks at about 5.5 GB total heap size.
<img width="1548" alt="image" src="https://github.com/user-attachments/assets/9b14cf7f-6f06-4091-bd27-ad9495cd0591">
This could be probably be reduced, but it looks very reasonable. 
Have you tried profiling the run to see how we reach the 16 GB limit?

If this is something we cannot workaround, we could limit the size of the pool to 8 cores, which is very reasonable and does not reduce at all the value of the tutorial. What do you think?

**Comment by pcanal** [comment]
> 12 workers and the memory peaks at about 5.5 GB total heap size.

This is the same scale as what I see.  .5 GB per core.  I see the 16Gb once I use 32 cores or more.
