### ISSUE TITLE
Compiler warning in Bytes.h: casts away qualifiers

### ISSUE THREAD

**Issue by DanielGeerts** [root-project/root#16366]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

/root/root/include/Bytes.h: In function ‘void tobuf(char*&, ULong_t)’:
/root/root/include/Bytes.h:109:15: warning: cast from type ‘const ULong_t*’ {aka ‘const long unsigned int*’} to type ‘char*’ casts away qualifiers [-Wcast-qual]
  109 |    char *sw = (char *)intermediary;
      |               ^~~~~~~~~~~~~~~~~~~~
/root/root/include/Bytes.h: In function ‘void tobuf(char*&, Long_t)’:
/root/root/include/Bytes.h:148:15: warning: cast from type ‘const Long_t*’ {aka ‘const long int*’} to type ‘char*’ casts away qualifiers [-Wcast-qual]
  148 |    char *sw = (char *)intermediary;
      |               ^~~~~~~~~~~~~~~~~~~~

In both cases, "intermediary" is defined as "const", which is indeed cast away by the C-style cast. As far as I can see, "sw" isn't written to, so that probably should be "const" as well? Otherwise, a const_cast could be an option.

### Reproducer

If you try to compile anything that (indirectly) includes include/Bytes.h with -Wcast-qual enabled.

### ROOT version

6.32.04

### Installation method

Pre-built binary

### Operating system

AlmaLinux 9.4

**Comment by dpiparo** [comment]
Hi @DanielGeerts , thanks for the report. We'll look into this, but it might take some time. Would you feel like proposing a solution for this issue?

**Comment by DanielGeerts** [comment]
I'm currently not (yet) set-up to compile ROOT myself, but I think changing both lines to:
`const char *sw = (const char *)intermediary;`
should work.
