### ISSUE TITLE
cppyy no aggregate initialization constructor

### ISSUE THREAD

**Issue by m-fila** [root-project/root#16469]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Python bindings done with ROOT's cppyy lack the aggregate initialization constructor
```python
>>> import ROOT
>>> ROOT.gInterpreter.ProcessLine("struct Foo {float x,y,z;};")
0
>>> ROOT.Foo(1,2,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: none of the 3 overloaded methods succeeded. Full details:
  Foo::Foo(Foo&&) =>
    TypeError: takes at most 1 arguments (3 given)
  Foo::Foo() =>
    TypeError: takes at most 0 arguments (3 given)
  Foo::Foo(const Foo&) =>
    TypeError: takes at most 1 arguments (3 given)
>>> print(ROOT.Foo.__init__.__doc__)
Foo::Foo(Foo&&)
Foo::Foo()
Foo::Foo(const Foo&)
```
same errors when directly using cppyy shipped with ROOT.

But the same code run with the stock cppyy taken from pip works fine
```python
>>> import cppyy
>>> cppyy.__version__
'3.1.2'
>>> cppyy.cppdef("struct Foo {float x,y,z;};")
True
>>> cppyy.gbl.Foo(1,2,3)
<cppyy.gbl.Foo object at 0x59dc0cbddc50>
>>> print(cppyy.gbl.Foo.__init__.__doc__)
Foo::Foo(Foo&&)
Foo::Foo()
Foo::Foo(const Foo&)
void __cppyy_internal::init_Foo(Foo*& self, const float& x = 0, const float& y = 0, const float& z = 0)
```

### Reproducer

```python
import ROOT
ROOT.gInterpreter.ProcessLine("struct Foo {float x,y,z;};")
ROOT.Foo(1,2,3)
print(ROOT.Foo.__init__.__doc__)
```

### ROOT version

Built for linuxx8664gcc on Sep 09 2024, 22:50:44 
From heads/master@tags/v6-32-04 

### Installation method

LCG dev4 nightly

### Operating system

 almalinux9

**Comment by aaronj0** [comment]
The support for aggregate constructors is linked to enabling the pythonization currently disabled by [this](https://github.com/root-project/root/blob/master/bindings/pyroot/cppyy/patches/CPyCppyy-Disable-initializer-style-construction.patch) patch.

Landing https://github.com/root-project/root/pull/16338 should fix this issue.
