### ISSUE TITLE
Add THStack/TH1 constructor for TRatioPlot

### ISSUE THREAD

**Issue by BethLong06** [root-project/root#16479]
### Feature description

It would be good to have the constructor:
`TRatioPlot	(TH1 *h1, THStack *st, Option_t * 	option = "pois" )`
Currently `TRatioPlot (THStack *st, TH1 *h1, Option_t * 	option = "pois" )` exists but it would be helpful to have the opposite option

[see here](https://root-forum.cern.ch/t/bumping-tratioplot-th1-thstack-instead-of-thstack-th1-in-ratio-plot/61616?u=bethlong06) for root forum post

**Comment by couet** [comment]
The PR is applied. Thanks for your suggestion.
