### ISSUE TITLE
Problem in PDF output of latex `g^{*}` 

### ISSUE THREAD

**Issue by linev** [root-project/root#16527]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Simple latex `g^{*}` with symbol font is not correctly stored in the PDF file.
```
   auto l = new TLatex(0.5, 0.5, "g^{*}");
   l->SetTextFont(122);
   l->SetTextAlign(22);
   l->SetTextSize(0.2);
```

### Reproducer

[latex1.cxx.txt](https://github.com/user-attachments/files/17132728/latex1.cxx.txt)

![c1](https://github.com/user-attachments/assets/79403060-5242-41ea-81b5-545df114afa8)

[c1.pdf](https://github.com/user-attachments/files/17132733/c1.pdf)

### ROOT version

Master branch

### Installation method

build from source

### Operating system

OpenSUSE linux

**Comment by linev** [comment]
It is problem with some PDF viewers - as usual

**Comment by couet** [comment]
@linev I do not see any problem on Mac with "preview". Which viewer has problems ?

**Comment by linev** [comment]
It is `okular` - default PDF viewer on my Linux.
If I take firefox - symbol show properly

**Comment by couet** [comment]
Ok, but what can we do ? it is a bug in okular, not in TPDF ....

**Comment by linev** [comment]
I closed issue
