### ISSUE TITLE
OpenGL doesn't work on macosx

### ISSUE THREAD

**Issue by fuhlig1** [root-project/root#16523]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

OpenGL isn't working at least for the following versions of macosx and command line tools when compiled from source.
The issue was also seen for some older macosx versions and for me it is not clear if this is problem of the macosx or XCode version and with which version it was introduced. The problem is seen with ROOT 6.30.08 as well as the latests 6.32.06.

macosx         | CLT
14.6.1 (x86)  | 15.3
14.6.1 (arm)  | 15.3
13.6.7 (x86)  | 15.1
14.3    (x86)  | 15.1
14.3.   (arm)  | 15.1

The problem is for example visible when executing the tutorial share/doc/root/tutorials/eve/box.C from the installation directory. The expected behaviour is that a shape is displayed in the viewer. The seen behaviour is that only a blavk screen is displayed and the following warning is printed  

`Warning in <TGLLogicalShape::Draw>: display-list registration failed.`

When installing root using brew the problem is gone and the expected behaviour is seen when running the above mentioned macro. Unfortunately when using brew to compile root from the sources the problem appears again. On only gets a black screen and the warning. So obviously there must be some difference between the machine used to generate the brew bottles and the machines used by me and my colleagues.

Do you have any idea what the problem could be and how to fix it. 

### Reproducer

Install root from sources using brew

`brew install -s root`

Execute the following macro

`$HOMEBREW_PREFIX/Cellar/root/6.32.06/bin/root 
 $HOMEBREW_PREFIX/Cellar/root/6.32.06/share/doc/root/tutorials/eve/box.C `

The command should open a viewer where only a black screen is displayed with the warning 

`Warning in <TGLLogicalShape::Draw>: display-list registration failed.`

in the terminal.

### ROOT version
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.32.06                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosx64 on Sep 21 2024, 18:21:53                      |
  | From tags/6-32-06@6-32-06                                        |
  | With Apple clang version 16.0.0 (clang-1600.0.26.3)              |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

build from source or brew

### Operating system

macosx (several versions mentioned above)

**Comment by couet** [comment]
Indeed the examples in the GL folder are also not working. We will check.

**Comment by couet** [comment]
I did some tries. I have a Mac mini with MacOS 13.7 and CTL 15.1 and it is working. The CPU of the machine is an Apple one M2. Which kind of CPU do you have ?

I will now try on some other machines.

**Comment by osschar** [comment]
Oh, do you guys have XQuartz or some other source of libGL installed? The configure step is too eager to pick this up over the proper OSX framework. I noticed this when testing the latest SDF font changes for the web display.

**Comment by osschar** [comment]
This is the comment from that PR:
https://github.com/root-project/root/pull/15812#issuecomment-2252641668

I assume the correct fix is to change cmake for osx to only pick the AGL framework.

**Comment by couet** [comment]
@osschar

Thanks for your help Matezv, 
"AGL Framework" ? I do not see some concrete solution in the PR you pointed.

**Comment by couet** [comment]
I see also the problem with any graphics if I do `gStyle->SetCanvasPreferGL(kTRUE)`

**Comment by couet** [comment]
according to [this post ](https://forums.developer.apple.com/forums/thread/725247#:~:text=You%20essentially%20can't%20install,other%20recent%20APIs%20out%20there.) on the apple forum, it seems  "OpenGL is dead on Mac".

**Comment by couet** [comment]
I am in conntact with Timur (the author of this code). he tried on 15.1 and for him it seems ok. I tried also on the same OS (i is beta) and for me it does not work. We are investigating.

**Comment by couet** [comment]
We have a macos 14, arm, clt 15.3 on which it is working ....

**Comment by fuhlig1** [comment]
Hi,

thanks for your investigations. In my opinion the problem somehow is due to the system. As I said already when using root from homebrew bootles (binary package) I don't see a problem. If I use the formula to compile root from the sources OpenGL isn't working. Since the root bootle is created with the same formula I expect that something on the build host for the bootle is different from my systems. 

I will try to check the generated libraries if I can spot any obvious differences.

**Comment by couet** [comment]
Yes, That would help us. Note that all our test are done with root build from sources.

**Comment by fuhlig1** [comment]
Okay. I think I found a difference. When comparing libRGL.so the working version links to the system OpenGL, whereas my version compiled from sources links to to the mesa installation from Homebrew.

Working:
```
	/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Error:	
```
         /usr/local/opt/mesa/lib/libGL.1.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/opt/mesa-glu/lib/libGLU.1.dylib (compatibility version 5.0.0, current version 5.1.0)
```

I will try to deinstall mesa from brew and recompile root to see if this fixes the problem.

**Comment by couet** [comment]
On my laptop (not working) I see:
```
% otool -L libRGL.so 
libRGL.so:
	@rpath/libRGL.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/X11/lib/libGL.1.dylib (compatibility version 4.0.0, current version 4.0.0)
	/opt/X11/lib/libGLU.1.dylib (compatibility version 5.0.0, current version 5.1.0)

```

**Comment by fuhlig1** [comment]
In my opinion the problem is the search order for libraries on macosx. The value of the variable CMAKE_FIND_FRAMEWORK which defines the order is LAST when checking for OpenGL such that any other OpenGL installation is found before the framework one. Since the default setting is FIRST there must be a reason why this is changed. To work around the problem for OpenGL I would propose to change the setting temporarily such that the framework version of OpenGL is taken.
I will prepare a fix after I am sure that this is the issue.

**Comment by fuhlig1** [comment]
Uninstalling the brew packages mesa and mesa-glu and recompiling root from source fixed the issue. LibRGL.so is no linked to the framework version of OpenGL and the macro runs as expected.

**Comment by couet** [comment]
Ok, problem solved. I removed the faulty GL on my MacBook , cmake again and recomplie. I will now to the same operetion on the SFT mac minis

**Comment by couet** [comment]
@fuhlig1 
As I said I removed the faulty OpenGL doing `rm /opt/X11/lib/libGL.dylib`. Then reinstalling from ROOT sources worked. I can see the GL output. But doing that I have another problem [here](https://github.com/root-project/root/actions/runs/10852318554/job/30697011619?pr=16348):
```
make[2]: *** No rule to make target `/usr/X11R6/lib/libGL.dylib', needed by `lib/libGLEW.dylib'.  Stop.
make[1]: *** [builtins/glew/CMakeFiles/GLEW.dir/all] Error 2
```
To cure that I had to reinstall XQuartz but then my ROOT installed from the sources points to the wrong OpenGL.

Did you manage to make sure ROOT points the right OpenGL with XQuartz installed?

**Comment by fuhlig1** [comment]
@couet ,

I think I could fix the problem in CMake but I need more testing. Hope I can finish the tests today.

**Comment by couet** [comment]
I have tried the following in `cmake/modules/SearchInstalledSoftware.cmake`:

```
#---Check for OpenGL installation-------------------------------------------------------
if(opengl)
  message(STATUS "Looking for OpenGL")
  if(APPLE)
    set(CMAKE_FIND_FRAMEWORK FIRST)
    find_package(OpenGL)
    set(CMAKE_FIND_FRAMEWORK LAST)
  else()
    find_package(OpenGL)
  endif()
```
It seems it finds the right OPgengl GL like that. I am now compiling to see it really fixes the GL graphics

**Comment by fuhlig1** [comment]
@couet,

that is more or less the solution I came up with. For me a similar fix with the same logic solved the problem.

**Comment by couet** [comment]
we eneded up with the same solution. I will make a PR once I verified it is working on my laptop

**Comment by couet** [comment]
The PR is here

**Comment by couet** [comment]
The PR is merged. Thanks for having seen this problem.
