### ISSUE TITLE
ROOT now always(?) requires gtest to build but doesn't check in configure step

### ISSUE THREAD

**Issue by andresailer** [root-project/root#16612]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

The change in https://github.com/root-project/root/pull/16568 causes gtest to be always required, or at least in the config we use for LCG stacks in Release mode.

See
https://lcgapp-services.cern.ch/cdash3/build/34617/file/1275

```
In file included from /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/testsupport/src/TestSupport.cxx:14:
/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/testsupport/inc/ROOT/TestSupport.hxx:28:10: fatal error: gtest/gtest.h: No such file or directory
   28 | #include "gtest/gtest.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```
Therefore this should fail in the configure step already.

### Reproducer

lcgcmake

### ROOT version

master

### Installation method

build from source

### Operating system

linux

**Comment by andresailer** [comment]
This needs some fixing for gtest to be available:

https://github.com/root-project/root/blob/78936428fb4bc7767e8486b6cadfd319dfac6d2b/cmake/modules/SearchInstalledSoftware.cmake#L1773-L1778

**Comment by guitargeek** [comment]
Oh, I was not on my mind that I introduced this new dependecy on `gtest`! I have to discuss with the other ROOT core team members if we really want this. But I think nowadays, `getst` is available basically everywhere.

**Comment by smuzaffar** [comment]
cmssw tests also failed due to missing gtest requirement. I guess we can use the builtin gtest?

**Comment by andresailer** [comment]
> cmssw tests also failed due to missing gtest requirement. I guess we can use the builtin gtest?

The cmake cited above only gets called with testing=ON, so this is broken even with builtin gtest.

**Comment by guitargeek** [comment]
Ok, the solution that we suggest is that the test support library will only be built if gtest is found on the system or `builtin_gtest` is switched on. Like this, we don't force a dependency on `gtest`, but if you want the test support library from ROOT without building all tests with `testing=ON`, then you can get it.

**Comment by andresailer** [comment]
as long as `if(fail-on-missing)` is still respected?

**Comment by guitargeek** [comment]
That will be hard to respect, because that means unless we introduce a new `testsupport=OFF` configuration flag, gtest would always be a dependency of ROOT with `-fail-on-missing=ON` then.

I don't see at the moment how I can respect all of these constraints:

1. Keep configuration simple by not introducing new build flags
2. Make `ROOT_ADD_GTEST` fully usable in downstream code even if ROOT was not built with unit tests
3. Don't add `gtest` as an unavoidable build dependency of ROOT if you have `fail-on-missin=ON`
4. Respect `fail-on-missing`

Which of these constraints should be relaxed?

**Comment by andresailer** [comment]
If you ask me, relax on number 1, who imposes that constraint?

**Comment by guitargeek** [comment]
You're right, that's indeed the weakest constraint. I'll suggest `-Dtestsupport`
