### ISSUE TITLE
Loss of floating point precision when saving TCanvas as ROOT macro

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#16687]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Floating point precision should be preserved when saving plots as ROOT macros with `TCanvas::SaveAs()`. This can probably be achieved with not too much effort using `std::setprecision`:
https://en.cppreference.com/w/cpp/io/manip/setprecision

### Reproducer

Run this code, which works fine:

```c++
TCanvas *c = new TCanvas("c", "c");
TH1D *histo = new TH1D("histo", "histo", 1, 595780500.110732, 595780531.878908);
histo->Draw();
c->SaveAs("plot.C");
```

The resulting macro will not preserve the precision on the floating point numbers:
```c++
   TH1D *histo__1 = new TH1D("histo__1","histo",1,5.957805e+08,5.957805e+08);
```
And you'll get an error when running it:
```txt
Processing plot.C...
Error in <TCanvas::Range>: illegal world coordinates range: x1=595780500.000000, y1=-0.131250, x2=595780500.000000, y2=1.181250
Error in <TCanvas::RangeAxis>: illegal axis coordinates range: xmin=595780500.000000, ymin=0.000000, xmax=595780500.000000, ymax=1.050000
root [1] Error in <TCanvas::Range>: illegal world coordinates range: x1=595780500.000000, y1=-0.131250, x2=595780500.000000, y2=1.181250
Error in <TCanvas::RangeAxis>: illegal axis coordinates range: xmin=595780500.000000, ymin=0.000000, xmax=595780500.000000, ymax=1.050000
```

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.32.06                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Sep 21 2024, 18:21:53                 |
  | From tags/6-32-06@6-32-06                                        |
  | With g++ (GCC) 13.3.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

Nix

### Operating system

NixOS (Linux)

### Additional context

Can easily happen in the analysis of timeseries, where one often has large axis values because they represent time with respect to some reference point far back in time (e.g. astrophysics, finance, ...).

**Comment by couet** [comment]
@guitargeek yes you are right. I see that, now, in `TH1::SavePrimitive` we have:
```
      out << "," << GetXaxis()->GetXmin()
      << "," << GetXaxis()->GetXmax();
```
So, the precision is not defined. But, the `setprecision` method requires an int `n` as parameter, defining the precision. What would be the value `n` in the general case ? We can surely make your example work with a proper value of `n` but that does not mean it will work in all cases. In the example on the reference page you pointed Pi is printed with different precision. Up to 19. We can put 19, but that's kind of arbitrary.

**Comment by guitargeek** [comment]
The value of `n` is well defined, you can get it for any given type with `max_digits10`:
https://en.cppreference.com/w/cpp/types/numeric_limits/max_digits10

To cite from the linked docs: "The value [..] is the number of base-10 digits that are necessary to uniquely represent all distinct values of the type T, such as necessary for serialization/deserialization to text."

I think that's perfect for us!

For `double`, `std::numeric_limits<double>::max_digits10` would be 17.
