### ISSUE TITLE
Missing TMVA::Experimental::SOFIE::RModelParser_ONNX class in some 6.32/XX pre-compiled binaries

### ISSUE THREAD

**Issue by GiacomoXT** [root-project/root#16774]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

It seems that in several 6.32/XX pre-compiled binaries the class `TMVA::Experimental::SOFIE::RModelParser_ONNX` is missing.

With 6.32/06 on Ubuntu 24.04:
```
root [0] TMVA::Experimental::SOFIE::RModelParser_ONNX()
ROOT_prompt_0:1:28: error: no member named 'RModelParser_ONNX' in namespace 'TMVA::Experimental::SOFIE'
TMVA::Experimental::SOFIE::RModelParser_ONNX()
~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```
while it works perfectly fine on Ubuntu 20.04.

I quickly checked that the header file `RModelParser_ONNX.hxx` is missing in the folder `include/TMVA` in 6.32/XX pre-compiled binaries for both Ubuntu 22.04 and Ubuntu 24.04, while it is present in the pre-compiled binaries for Ubuntu 20.04, Almalinux 8.9 and Almalinux 9.4.

Unless there are good reasons why `RModel_ONNX` class should be missing in Ubuntu 22.04 and Ubuntu 24.04 binaries, I assume there is something fishy in the build system.

### Reproducer

On an Ubuntu 24.04 machine:
```
wget wget https://root.cern/download/root_v6.32.06.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz
tar -xzf root_v6.32.06.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz
source root/bin/thisroot.sh
root
(from the ROOT shell) TMVA::Experimental::SOFIE::RModelParser_ONNX()
```

### ROOT version

```
 ------------------------------------------------------------------
| Welcome to ROOT 6.32.06                        https://root.cern |
| (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
| Built for linuxx8664gcc on Sep 21 2024, 19:19:59                 |
| From tags/v6-32-06@v6-32-06                                      |
| With c++ (Ubuntu 13.2.0-23ubuntu4) 13.2.0                        |
| Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
 ------------------------------------------------------------------
```

### Installation method

pre-built binaries

### Operating system

Ubuntu 22.04, Ubuntu 24.04

**Comment by dpiparo** [comment]
Hi @GiacomoXT , we enabled SOFIE on all ubuntus. This will propagate to all released binary versions of ROOT. Let me know if you need a release of ROOT that includes sofie for Ubuntu: we were planning a 6.32 release anyway, and we can adjust the timeline according to the needs.

**Comment by GiacomoXT** [comment]
Thanks a lot! From my side, there is no urgency to have a release for Ubuntu 22 and 24: for our tests we switched to a RHEL9 machine.

**Comment by dpiparo** [comment]
@GiacomoXT thanks for the feedback. Let us know how that goes!
