### ISSUE TITLE
TLorentzVector.h cannot be used in 63206

### ISSUE THREAD

**Issue by zhengchenliang** [root-project/root#16891]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

TLorentzVector.h cannot be included in ROOT version 6.32.06 with the error: 'Math/Vector4D.h' file not found

### Reproducer

root [0] .L M8pre0orig.cxx++
Info in <TUnixSystem::ACLiC>: creating shared library /afs/desy.de/user/z/zhliang/simpleCondor/src/./M8pre0orig_cxx.so
In file included from input_line_9:6:
In file included from ././M8pre0orig.cxx:22:
/usr/include/root/TLorentzVector.h:27:10: fatal error: 'Math/Vector4D.h' file not found
#include "Math/Vector4D.h"
         ^~~~~~~~~~~~~~~~~

M8pre0orig.cxx:

#include <iostream>
#include <iomanip>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "TH1.h"
#include "TH2.h"
#include "TProfile.h"
#include "TCanvas.h"
#include "TPad.h"
#include "TStyle.h"
#include "TGraph.h"
#include "TAxis.h"
#include "TLegend.h"
#include "TFile.h"
#include "TChain.h"
#include "TTree.h"
#include "TROOT.h"
#include "TGaxis.h"
#include "TLatex.h"
#include "TBufferFile.h"
#include "TLorentzVector.h"
#include "TPaveStats.h"

### ROOT version

root -b -q
   ------------------------------------------------------------------
  | Welcome to ROOT 6.32.06                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Sep 23 2024, 00:00:00                 |
  | From tags/6-32-06@6-32-06                                        |
  | With g++ (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)                |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

### Installation method

it is on DESY naf-cms22

### Operating system

Linux naf-cms22.desy.de 5.14.0-427.42.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 18 14:35:40 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lmoneta** [comment]
Hi, 
It looks to me a problem in your installation of ROOT. Are you missing the file:
`/usr/include/root/Math/Vector4D.h`  ?

**Comment by dpiparo** [comment]
I tried also on macOS (master) and 6.32 (lxplus installation) and I cannot reproduce.
