### ISSUE TITLE
Double shadow in `TPaveText` 

### ISSUE THREAD

**Issue by linev** [root-project/root#17076]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

When producing images, double shadow for TPaveText is produced.
Which normally should not happen.

### Reproducer

From $ROOTSYS, starts:
```
root --web=off tutorials/hsimple.root -e 'gStyle->Reset(); hpx->Draw(); c1->SaveAs("hpx.png")' 
```

Screenshot of the canvas with marked problematic regions:
![Screenshot_20241126_174603](https://github.com/user-attachments/assets/755e8b1d-fbad-49ae-8102-f3be78f888c8)

Also created image file has same artifact:
![hpx](https://github.com/user-attachments/assets/61ccc9c6-38e2-45a6-a72d-4660621852a9)

Double shadow disappears when TCanvas modified - like after resize

### ROOT version

ROOT master branch

### Installation method

Build from source

### Operating system

OpenSUSE Linux

**Comment by couet** [comment]
As Serguey mentioned elsewhere the following lines also show the problem:
```
{
   auto h1 = new TH1I("h1","histogram title", 100, -5, 5);
   h1->FillRandom("gaus", 10000);
   gStyle->SetTitleBorderSize(5);
   h1->Draw();
}
```

**Comment by couet** [comment]
Fixed here: https://github.com/root-project/root/pull/17152
