### ISSUE TITLE
Add Alias transformation to distributed RDataFrame

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#17135]
### Explain what you would like to see improved and how.

The Alias transformation should be added to distributed RDataFrame

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by VISHESH0932** [comment]
Hello @vepadulano , I would love to work on this issue.

**Comment by vepadulano** [comment]
Thanks @VISHESH0932 for your availability, much appreciated! This particular issue is fixed by https://github.com/root-project/root/pull/17171 , but I'm sure your help will be quite useful in one of the other issues!
