### ISSUE TITLE
Compiler error (GCC 14.2.0 on Linux)

### ISSUE THREAD

**Issue by maxaehle** [root-project/root#17190]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Compilation fails

### Reproducer

Following the instructions from [https://root.cern/install/build_from_source/](https://root.cern/install/build_from_source/):
```
git clone --branch latest-stable --depth=1 https://github.com/root-project/root.git src
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install ../src
make -j 24
```
on a Rocky Linux 8.10 system with GCC 14.2.0, GLIBC 2.28, Clang 18.1.8 gives a compiler error 
```
[ 62%] Building CXX object interpreter/llvm-project/llvm/tools/clang/lib/CodeGen/CMakeFiles/obj.clangCodeGen.dir/CGObjCRuntime.cpp.o
CMake Error at /home/aehle/g/build/builtins/davix/DAVIX-prefix/src/DAVIX-stamp/DAVIX-build-.cmake:49 (message):
  Command failed: 2

   'make'

  See also

    /home/aehle/g/build/builtins/davix/DAVIX-prefix/src/DAVIX-stamp/DAVIX-build-*.log
```
The first error in the log referenced here is 
```
/home/aehle/g/build/builtins/davix/DAVIX-prefix/src/DAVIX/src/libs/rapidjson/document.h: In member function ‘rapidjson::GenericStringRef<CharType>& rapidjson::GenericStringRef<CharType>::operator=(const rapidjson::GenericStringRef<CharType>&)’:
/home/aehle/g/build/builtins/davix/DAVIX-prefix/src/DAVIX/src/libs/rapidjson/document.h:319:82: error: assignment of read-only member ‘rapidjson::GenericStringRef<CharType>::length’
  319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
      |                                                                           ~~~~~~~^~~~~~~~~~~~
```
Logs:
[cmake.log](https://github.com/user-attachments/files/18005948/cmake.log)
[make.log](https://github.com/user-attachments/files/18005951/make.log)
[DAVIX-build-err.log](https://github.com/user-attachments/files/18005949/DAVIX-build-err.log)
[DAVIX-build-out.log](https://github.com/user-attachments/files/18005950/DAVIX-build-out.log)

### ROOT version

commit 1b923a47801d73194d763212d2290b878f3b8908 (current latest-stable)

### Installation method

build from source

### Operating system

Rocky linux 8.10 (Green Obsidian)

### Additional context

Seems to be related to an old rapidjson bug https://github.com/Tencent/rapidjson/issues/2277 that was fixed in 2016 but there has not been a rapidjson release since. ROOT's version of Davix comes with a copy of rapidjson that contains this bug (reported in https://github.com/cern-fts/davix/issues/130).

**Comment by dpiparo** [comment]
@amadio

**Comment by andresailer** [comment]
cf. https://github.com/cern-fts/davix/pull/129

**Comment by andresailer** [comment]
Hi @maxaehle 

can you try with #17192 ?

**Comment by maxaehle** [comment]
works, thanks!

**Comment by mpatrascoiu** [comment]
Hello,

Good to hear confirmation that #17192 works!
I have created an internal ticket for this: [DMC-1426|https://its.cern.ch/jira/browse/DMC-1426].

In the long-term, I see us dropping the rapidjson dependency.
For the short-term, we can apply the changes in https://github.com/cern-fts/davix/pull/129 / https://github.com/cern-fts/davix/issues/130

Cheers,
Mihai
