### ISSUE TITLE
TFileMerger leaves files open resulting in corrupt metadata

### ISSUE THREAD

**Issue by chrisburr** [root-project/root#17223]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

In LHCb we've seen that some files have been corrupted (at the 1% level) due to `TFileMerger` leaving the files open. The symptom is:

```
Error in <TDirectoryFile::ReadKeys>: reading illegal key, exiting after 0 keys
```

In summary from PyROOT we use `TFileMerger` with `PartialMerge` to create a ROOT file. We later open the file with `UPDATE` and call `TDirectory(File).Purge` to remove any empty directories and clear old cycles (as they cause confusion).

It turns out if you don't explicitly call `del merger` ROOT doesn't close the file. Maybe there is a good reason for this but naively it seems like an error prone API that could possibly be improved. If not feel free to close this.

cc @ryuwd in case I got any details wrong

### Reproducer

I don't have a clear reproducer as it seems to be depenedent on the exact input data but the full code is here: https://gitlab.cern.ch/lhcb-core/lbexec/-/blob/v0.5.3/src/LbExec/workflows.py?ref_type=tags#L106-285

### ROOT version

   ------------------------------------------------------------------
  | Welcome to ROOT 6.32.02                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Sep 18 2024, 20:01:03                 |
  | From heads/master@tags/v6-32-02                                  |
  | With                                                             |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

### Installation method

conda-forge

### Operating system

Linux (alma 9)

**Comment by chrisburr** [comment]
That sounds perfect to me, espeically if there could be a pythonization to have the context manager (could this also be added to TFile? Maybe it already exists?).

For now we've added the `del merger` line but we're happy to move to something more Pythonic once that's available (especially as I don't fully trust `del` to call the destructor).

`Close` was the thing I searched for when I was debugging but the need for this would have to be prominently documented. A even better solution would be to absorb the functionality to clean up rather than calling `TDirectory(File).Purge` manually.

@ryuwd might have more opinions/feedback as he wrote this code.

**Comment by silverweed** [comment]
> (could this also be added to TFile? Maybe it already exists?)

Hi @chrisburr, `TFile` can already act as a context manager :)

> A even better solution would be to absorb the functionality to clean up rather than calling TDirectory(File).Purge manually.

Purging the lower cycles is not the default behavior of TDirectory(File), so I think having to call `Purge` manually is the right thing to do here.

**Comment by chrisburr** [comment]
I seem to recall there was some distinction between how `hadd` behaved and how `TFileMerger` was working. I've asked @ryuwd to clarify.

**Comment by ryuwd** [comment]
> I seem to recall there was some distinction between how hadd behaved and how TFileMerger was working

I had a feeling that `hadd` seemed to do a `Purge` of the cycles or altogether avoided writing the lower cycles in the merged output. Certainly back when we were using `hadd` as the our merger, I couldn't recall seeing local cycles included in our merged output files. I can't see immediately at a glance what `hadd` does differently, nor any calls to `TDirectory(File)::Purge` - apologies I can't give a more concrete account.

**Comment by vepadulano** [comment]
Let me also add @pcanal in the conversation to help shed some light. The current discussion is about this bit from the issue description

> We later open the file with UPDATE and call TDirectory(File).Purge to remove any empty directories and clear old cycles (as they cause confusion)

and the question is whether there is some different behaviour in `hadd` vs `TDirectory(File)` that deals with that. Maybe a second question is whether we should include this behaviour in the cleanup routine we are introducing for `TFileMerger`, although intuitively that sounds risky and probably out of scope.
