### ISSUE TITLE
[RDF] 'DistRDF.Ranges' has no attribute 'get_clusters_and_entries'

### ISSUE THREAD

**Issue by jlidrych** [root-project/root#17263]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Hello Root team,

while working with the distributed RDF,  I encountered a bug.
This [PR](https://github.com/root-project/root/commit/08ef067250ed06de772579cbe8cb4c9c95a4dd10#diff-49294aaf61ddd05ba43b40ae651b081a608ee7b27e3c716e9b3a2d928cbf7ebfL363) changed the ownership model of external objects in distributed RDataFrame and now the module 'DistRDF.Ranges' does not include the attribute 'get_clusters_and_entries'.
However, ```Ranges.get_clusters_and_entries()``` is still being called in  ```DistRDF.HeadNode.py```( [line486](https://github.com/root-project/root/blob/master/bindings/experimental/distrdf/python/DistRDF/HeadNode.py#L486), [line 666](https://github.com/root-project/root/blob/master/bindings/experimental/distrdf/python/DistRDF/HeadNode.py#L666) )

The fix for this issue is straightforward:
Replace ```Ranges.get_clusters_and_entries(treename, filename)``` with ```ROOT.Internal.TreeUtils.GetClustersAndEntries(treename, filename)```.
I would be happy to open a PR to address this if you would like.

Best,
Jindrich

```
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_106/x86_64-el9-gcc13-opt/lib/DistRDF/Proxy.py", line 201, in _call_action_result
    return getattr(self.GetValue(), self._cur_attr)(*args, **kwargs)
                   ^^^^^^^^^^^^^^^
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_106/x86_64-el9-gcc13-opt/lib/DistRDF/Proxy.py", line 193, in GetValue
    execute_graph(self.proxied_node)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_106/x86_64-el9-gcc13-opt/lib/DistRDF/Proxy.py", line 58, in execute_graph
    node.get_head().execute_graph()
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_106/x86_64-el9-gcc13-opt/lib/DistRDF/HeadNode.py", line 247, in execute_graph
    returned_values = self.backend.ProcessAndMerge(self._build_ranges(), mapper, distrdf_reducer)
                                                   ^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_106/x86_64-el9-gcc13-opt/lib/DistRDF/HeadNode.py", line 522, in _build_ranges
    clusters, entries = Ranges.get_clusters_and_entries(self.subtreenames[0], self.inputfiles[0])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'DistRDF.Ranges' has no attribute 'get_clusters_and_entries'
```

### Reproducer

I can provide a piece of code if needed.

### ROOT version

   ```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.32.06                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Oct 03 2024, 16:08:18                 |
  | From tags/6-32-06@6-32-06                                        |
  | With g++ (GCC) 13.1.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
   ```

### Installation method

source from LCG

### Operating system

Linux

**Comment by vepadulano** [comment]
Hi @jlidrych,

Nice catch! Just to confirm, in your application you are creating a Python logger via the `logging` module and explicitly setting the log level to `DEBUG`, right? Could you in general send a snippet of your code to as a reproducer of the issue?

In any case I will be glad to accept your contribution to the project! Feel free to submit a PR.
