### ISSUE TITLE
Veccore won't compile with clang 19

### ISSUE THREAD

**Issue by abarton5** [root-project/root#17274]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Compiling my program works with gcc but switching to clang causes errors coming from veccore

```
/cernroot/buildroot6340/include/VecCore/Backend/Implementation.h:147:40: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  147 |   LoadStoreImplementation<T>::template Load(v, ptr);
 ```
and
```
In file included from /cernroot/buildroot6340/include/TF1.h:30:
In file included from /cernroot/buildroot6340/include/TFormula.h:19:
In file included from /cernroot/buildroot6340/include/Math/Types.h:27:
In file included from /cernroot/buildroot6340/include/VecCore/VecCore:16:
/cernroot/buildroot6340/include/VecCore/Backend/ScalarWrapper.h:155:57: error: no member named 'val_ptr' in 'WrappedScalar<type-parameter-0-0>'
  155 |   WrappedScalar(const WrappedScalar *const s) : fVal(s->val_ptr) {}
      |                                                      ~  ^
5 errors generated.
```

Veccore is not being used directly. It seems to be just from including TF1.h

### Reproducer

Compile root with veccore enabled

create a trivial program that includes TF1.h
```c++
#include "TF1.h"
int main(){
return 0;
}
```
compile with clang
`clang++ \`root-config --cflags\` test.cxx`

### ROOT version

ROOT 6.34.00
cmake  -DCMAKE_INSTALL_PREFIX="${ROOT_INSTALL_DIR}" -Dmathmore=ON   -Droofit=ON   -Dimt=ON -DCMAKE_C_FLAGS="-march=native"  -DCMAKE_CXX_FLAGS="-march=native" -Dxml=OFF -Dbuiltin_afterimage=OFF -Dvc=ON -Dvdt=ON -Dveccore=ON  -Dbuiltin_vdt=ON -Dxrootd=OFF -Dsqlite=OFF -Doracle=OFF -Ddavix=OFF -Dpythia6=OFF -Dpythia8=OFF -Doracle=OFF -Dmysql=OFF -DCMAKE_CXX_STANDARD=20

### Installation method

built from source

### Operating system

Ubuntu 24.10

**Comment by dpiparo** [comment]
Thanks for the report. While the version of the builtin veccore is updated to 0.8.5, that fixes the issue, you can compile ROOT with veccore by building your own veccore 0.8.5 and make it available on your system. ROOT will find it and build against it instead of relying on the builtin one.
