### ISSUE TITLE
The marker of the second TGraphErrors in the pad overlays its error bar

### ISSUE THREAD

**Issue by wxzhan** [root-project/root#17319]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

The markers covers its error bar. Specifically, when the error bars are shorter than the diameter of the marker, I wish it could be drawn inside the marker.

The anomaly that makes me suspect if it's a bug is that, in the first graph drawn with option "AP", everything is fine. But in the second and later graphs drawn with "P", their markers cover the error bars.

I found a similar issue https://github.com/root-project/root/issues/14549 but it doesn't really answers my question why the error bar in the first graph is not overlaid.

### Reproducer

[testgraph.pdf](https://github.com/user-attachments/files/18206278/testgraph.pdf)

```
void testgraph()
{
	gROOT->SetBatch();
	double x1[1] = {1};
	double x2[1] = {2};
	double y[1] = {1};
	double ex[1] = {0};
	double ey[1] = {0.005}; // try this with small values so that error bars are delibrately made to be smaller than the marker
	auto graph1 = new TGraphErrors(1, x1, y, ex, ey);
	auto graph2 = new TGraphErrors(1, x2, y, ex, ey);
	auto canvas = new TCanvas();
	graph1->SetMinimum(0);
	graph1->SetMaximum(2);
	graph1->SetMarkerStyle(kFullCircle);
	graph2->SetMarkerStyle(kFullCircle);
	graph1->SetMarkerSize(0.5);
	graph2->SetMarkerSize(0.5);
	graph1->SetMarkerColor(kRed);
	graph2->SetMarkerColor(kBlue);
	graph1->Draw("AP");
	graph2->Draw("P"); // you can see errorbars in graph1, but not in graph2
	canvas->SaveAs("testgraph.pdf");
}
```

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.30/02                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Aug 26 2024, 07:41:41                 |
  | From heads/master@tags/v6-30-02                                  |
  | With g++ (GCC) 13.1.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

build from source

### Operating system

CentOS Linux release 7.9.2009 (Core)

**Comment by ferdymercury** [comment]
Related PR: https://github.com/root-project/root/pull/16372

**Comment by couet** [comment]
This has been fixed by the PR mentioned above.
