### ISSUE TITLE
Fedora 32 test failures

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#6331]
After https://sft.its.cern.ch/jira/browse/ROOT-10849 is fixed, we are now left with three test failures:

* projectroot.roottest.root.io.uniquePointer.roottest_root_io_uniquePointer_simpleWriteRead
* projectroot.roottest.root.io.uniquePointer.roottest_root_io_uniquePointer_simpleRead
* projectroot.roottest.root.meta.ROOT-7462.roottest_root_meta_ROOT_7462_make

**Comment by Axel-Naumann** [comment]
Still fails in master, see e.g. https://github.com/root-project/root/pull/6961#issuecomment-747595647

**Comment by ferdymercury** [comment]
@dpiparo is this issue still relevant?

**Comment by guitargeek** [comment]
I don't know, @Axel-Naumann? At lest it doesn't seem to be actually critical, since there was not activity for a while.

**Comment by Axel-Naumann** [comment]
Fedora 32 is dead, current fedoras don't have this problem. I.e. this seems fixed.
