### ISSUE TITLE
[ntuple] Off-by-one-byte error when deserializing arrays as RVecs

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#6347]
Reading `RVecs` with `RNTuple` incurs in an off-by-one-byte error, because all `RVec<T>` are deserialized as `std::vector<char>`, but the position of the data buffer is different for `RVecs`:

```
>>> p ((ROOT::VecOps::RVec<int>*)0x5555596c72a0)->data()
$983 = (int *) 0x5555581b2918
>>> p ((std::vector<char, std::allocator<char> > *)0x5555596c72a0)->data()
$984 = 0x5555581b2910
```

I think the problematic logic is [here](https://github.com/root-project/root/blob/8d5b55f51ad8449d83fc0db8f49217e556c34036/tree/ntuple/v7/src/RField.cxx#L660).

A second issue related to RVecs is that at RField.cxx:638 we use RVectorField for reading RVecs, but this means that the parent RField will have type name `std::vector<...>` even if it should (probably?) be `RVec<...>`.

#6336 contains a reproducer.

**Comment by jblomer** [comment]
Looking into this, isn't the problem rather that we don't expose collections necessarily as `RVec` columns in RNTupleDS but instead we use the collection type that was used to originally store them (such as `std::vector`)? If a field of type `RVec<T>` is created, we are actually not using `RVectorField` but an [RVec specialization](https://github.com/root-project/root/blob/master/tree/ntuple/v7/inc/ROOT/RField.hxx#L967), for which we unfortunately don't have a type-erased version yet.

Put in another way, why should [the `RVec` cast](https://github.com/root-project/root/pull/6336/files#diff-36fd7a2e2d24a398e279578a4a3705c8R109) of the "jets" column work if it is in fact an `std::vector<float>`.

**Comment by eguiraud** [comment]
> why should the RVec cast of the "jets" column work if it is in fact an std::vector<float>

I understand why it currently doesn't, but I believe we agree that reading any collection as an RVecs via RNTupleDS _should_ work

I think we agreed to:
- [ ] throw an exception from RNTupleDS in case type on disk and type requested do not match -- this will make the bug noisy instead of silent and will possibly catch other issues in the future
- [ ] wait for the RVec redesign that adds a small vector optimization and then provide a type-erased deserialization function for RVecs which RNTupleDS can take advantage of -- the redesign will make it simpler to implement such a function in a robust way
