### ISSUE TITLE
[Docs] Missing figures in RDF tutorials 10[5,6,7] on doxygen

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#6360]
You can find the doxygen pages with the missing figures here:

https://root.cern/doc/master/df105__WBosonAnalysis_8py.html
https://root.cern/doc/master/df106__HiggsToFourLeptons_8py.html
https://root.cern/doc/master/df107__SingleTopAnalysis_8py.html

**Comment by stwunsch** [comment]
@couet Could you verify that the linked PR fixes the issue?

**Comment by stwunsch** [comment]
@couet Could we follow up on this?

**Comment by stwunsch** [comment]
Unfortunately the docs are still broken (see the links above).

**Comment by stwunsch** [comment]
@couet Since yesterday the images are there again. Have you found the issue?

**Comment by couet** [comment]
The figures are back. I close this issue.
