### ISSUE TITLE
[IMT] ROOT::GetThreadPoolSize does not reflect tbb::global_control settings

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#6363]
## Describe the bug

Calling `tbb::global_control c(tbb::global_control::max_allowed_parallelism, 3);` followed by `ROOT::GetThreadPoolSize()` or `TThreadExecutor::GetPoolSize()` results in the incorrect number of threads reported (hardware concurrency rather than what was set via `tbb::global_control`.

## Expected behavior

`ROOT::GetThreadPoolSize` should report the real TBB thread pool size or the real number of threads that ROOT will use.

## To Reproduce

This code prints 8 two times on my 8-core workstation, but CPU usage is actually 300%, i.e. TBB's thread pool has size 3 but we ROOT reports 8.

```cpp
#include <ROOT/TThreadExecutor.hxx>
#include <tbb/global_control.h>
#include <tbb/task_scheduler_init.h>
#include <iostream>
#include <TROOT.h>

int main() {
  tbb::global_control c(tbb::global_control::max_allowed_parallelism, 3);
  ROOT::EnableImplicitMT();
  std::cout << ROOT::GetThreadPoolSize() << std::endl;
  ROOT::TThreadExecutor pool;
  std::cout << pool.GetPoolSize() << std::endl;
  auto busyLoop = [](int x) { int i = 0; for (; i < 1000000000+x; ++i); return i; };
  pool.Foreach(busyLoop, {1,2,3,4,5,6,7,8});
  return 0;
}
```

**Comment by eguiraud** [comment]
Maybe we could check `tbb::global_control::active_value(tbb::global_control::max_allowed_parallelism)` in https://github.com/root-project/root/blob/178dd7fde68aca357e5a821f7cb6b4c4753d4499/core/imt/src/RTaskArena.cxx#L69-L81

**Comment by xvallspl** [comment]
Makes sense, can do. I would expect tbb::task_arena::max_concurrency() to check that

**Comment by eguiraud** [comment]
uhm on the other hand `tbb::global_control` is a RAII kind of thing, so it can come and go. Maybe it's on at the point ROOT's task arena is constructed but not at the point tasks are spawned, and users now get less threads in the arena for "no reason". Not sure.

**Comment by xvallspl** [comment]
Solved in https://github.com/root-project/root/pull/6814
