### ISSUE TITLE
Creating RooDataSet causes SegFault

### ISSUE THREAD

**Issue by dcervenkov** [root-project/root#6408]
## Describe the bug

The following code works fine with 6.20.04, but segfaults with 6.22.02.

```cpp
#include "RooDataSet.h"
#include "RooRealVar.h"
#include "TFile.h"
#include "TTree.h"

int main(int argc, char* argv[]) {
    TTree* tree = new TTree("tree", "tree");
    double var = 1;
    tree->Branch("var", &var, "var/D");
    tree->Fill();

    RooRealVar* roovar = new RooRealVar("var", "var", 0, 10);
    TFile* output_file = new TFile("test.root", "RECREATE", "output_file");

    output_file->Print();
    RooDataSet* data_set = new RooDataSet("data_set", "data_set", tree, RooArgSet(*roovar));
    output_file->Print();

    return 0;
}
```

The segfault happens on the last `output_file->Print();` line - it seems the creation of the `RooDataSet` somehow destroys the object pointed to by `output_file`.

## Expected behavior

I expect the code to run without segfaulting.

## To Reproduce

1. Save the quoted code to `mwe_tfile.cc`
2. Build with `g++ mwe_tfile.cc -o mwe_tfile $(root-config --cflags --glibs) -lRooFitCore`
3. Run `./mwe_tfile`

## Setup

Ubuntu 18.04
Binary ROOT installs
Works with 6.20.04
Doesn't work with 6.22.02

**Comment by dcervenkov** [comment]
Adding `gROOT->GetListOfFiles()->Print();` calls supports my claims. Before creating the `RooDataSet` the output of the `Print()` is
```
Collection name='Files', class='TList', size=1
 TFile: name=test.root, title=output_file, option=CREATE
```
after
```
Collection name='Files', class='TList', size=0
```

**Comment by hageboeck** [comment]
Needs backport. Github is too aggressive in closing ...
