### ISSUE TITLE
Without memstat support, `root -memstat` should not be available

### ISSUE THREAD

**Issue by jblomer** [root-project/root#6410]
## Describe the bug
As discussed in the [ROOT forum](https://root-forum.cern.ch/t/root-memstat-doesnt-work/41455):
WIthout the memstat feature, `root.exe` still offers the `-memstat` option but produced failures like
```
input_line_11:2:6: error: unknown type name 'TMemStat'
 new TMemStat("",100000,5000000);
```

## Expected behavior
If memstat is not part of the build, the memstat option should not be offered or there should be a clearer error message.

## To Reproduce
1. Compile with `cmake -Dmemstat=off`
2. Run `root -l`

## Setup
1. Master
2. Arch Linux
3. Built from sources

**Comment by Harshalzzzzzzz** [comment]
@jblomer  Dear Mentor ,
I would like to work on this issue, can you please guide me further on what needs to be done and how I can approach this issue and contribute to the project?
I have already completed the setup of ROOT and other dependencies.

Thank you

**Comment by Axel-Naumann** [comment]
"Fixed" by removing memstat :-P
