### ISSUE TITLE
io: streamer for std::bitset appears to be relying on endian-ness

### ISSUE THREAD

**Issue by sbinet** [root-project/root#6412]
this is a repeat of https://root-forum.cern.ch/t/std-bitset-streamer-endianness-issue/41529

---

hi there,

I was adding support for reading/writing `std::bitset<N>` to [groot](https://go-hep.org/x/hep/groot) when I noticed the following behaviour:

```
$> cat ./Event.h
#ifndef MYEVT_H
#define MYEVT_H 1

#include <bitset>

struct Event {
	std::bitset<16> Bs;
};

#endif // MYEVT_H

$> cat ./run.C
#include "Event.h"

void run() {
	gSystem->Load("./libEvent.so");

	auto f = TFile::Open("std-bitset.root", "RECREATE");
	auto t = new TTree("tree", "tree");

	int bufsize = 32000;
	int splitlvl = 99;

	Event e;
	e.Bs = std::bitset<16>("0001010111101010");

	t->Branch("evt", &e, bufsize, splitlvl);

	t->Fill();
	f->Write();
	f->Close();

	exit(0);
}

$> root -b -q ./run.C
```

reading back the file with `groot`, I see the following bit patterns:

```
$> root-dump testdata/std-bitset.root 
>>> file[testdata/std-bitset.root]
key[000]: tree;1 "tree" (TTree)
[000][evt]: {[0 1 0 1 0 1 1 1 1 0 1 0 1 0 0 0]}
```

_ie:_ it seems endianness of the bitset isn't handled when writing the bitset (and it's whatever it happens to be on the writing machine).
(I was expecting: `[0 0 0 1 0 1 0 1 1 1 1 0 1 0 1 0]` as the on-disk bytes)

or are `bitset<N>` values always little-endian encoded?

I was also a bit surprised to see a `std::bitset<N>` to take (N+4)bytes on disk (instead of "just" N**bits** +4bytes, or, even, just N**bits**).

is there an underlying reason I am missing here? (it's also quite possible I am completely mistaken, of course)

thx,
-s
___
_Please read [tips for efficient and successful posting](https://root-forum.cern.ch/t/tips-for-efficient-and-successful-posting/28292) and [posting code](https://root-forum.cern.ch/t/posting-code-read-this-first/28293)_

ROOT Version: 6.22/02
Built for linuxx8664gcc on Aug 17 2020, 12:46:52
From tags/v6-22-02@v6-22-02
___

**Comment by sbinet** [comment]
ping?

**Comment by pcanal** [comment]
> I was also a bit surprised to see a std::bitset<N> to take (N+4)bytes on disk (instead of "just" Nbits +4bytes, or, even, just Nbits).

Indeed, it is currently stored the same way as the other collection of bool ... using one 'char' per bool :(.

> (I was expecting: [0 0 0 1 0 1 0 1 1 1 1 0 1 0 1 0] as the on-disk bytes)
> or are bitset<N> values always little-endian encoded?

You may have missed the fact that the std::bitset constructor from a string is in "reverse":
```
root [0] std::bitset<16> b("0001010111101010")
(std::bitset<16> &) @0x7f8e977e7010
root [1] for(int i = 0; i < 16; ++i) cout << std::hex << b[i] << '\n';
0
1
0
1
0
1
1
1
1
0
1
0
1
0
0
0
```

Cheers,
Philippe.

**Comment by ferdymercury** [comment]
> or are `bitset<N>` values always little-endian encoded?

See https://stackoverflow.com/a/29483339/7471760

**Comment by ferdymercury** [comment]
> is there an underlying reason I am missing here?

https://stackoverflow.com/a/12459988/7471760
