### ISSUE TITLE
Proposal to unify logging in Minuit2

### ISSUE THREAD

**Issue by HDembinski** [root-project/root#6421]
Probably due to historical reasons, the Minuit2 code uses several systems to report errors, warnings, and debug info. Some of these only work when certain compile flags are set (WARNINGMSG and DEBUG). I would like to unify these systems and use the MnPrint facilities consistently everywhere. This would have the advantage that debug info can be turned on at any time without recompiling and it has additional advantages for frontends to Minuit2, like [iminuit](https://github.com/scikit-hep/iminuit).

I would like to work on this, but need some feedback before I invest time.

### Proposed changes

Currently, there are three systems to report info, errors, warnings, and debug messages. The latter two need to be enabled with compile flags (WARNINGMSG and DEBUG).

Examples from VariableMetricBuilder.cxx:

Direct use of the MnPrint facilities (this is the "proper" way)
```c++
if (PrintLevel() > 1) {
  MnPrint::PrintState(std::cout, result.back(), "VariableMetric: Iteration # ",result.size()-1);
}
```
Use of MnPrint macros for info messages that are only enabled when WARNINGMSG is set
```c++
#ifdef WARNINGMSG
      MN_INFO_MSG("VariableMetricBuilder: initial matrix not pos.def.");
#endif
```
Use of DEBUG and std::cout
```c++
#ifdef DEBUG
   std::cout<<"VariableMetricBuilder convergence when edm < "<<edmval<<std::endl;
#endif
```
The latter two need to be enabled at compile-time. If they are enabled, there is no fine-grained run-time control, because the MnPrint system only distinguishes two verbosity levels 0 and 1. On level 0, only errors are reported. On level 1, errors and "info" are reported.

I propose to enhance this by two more levels

- level 0: report errors
- level 1: all of level 0 + warnings
- level 2: all of level 1 + info
- level 3: all of level 2 + debug

and add the corresponding macros
```c++
MN_WARN_MSG
MN_WARN_MSG2
MN_WARN_VAL
MN_WARN_VAL2
MN_DEBUG_MSG
MN_DEBUG_MSG2
MN_DEBUG_VAL
MN_DEBUG_VAL2
```
in addition to the existing MN_INFO_* and MN_DEBUG_* macros.

Level 1 would enable the warning messages that are currently only available when the compiler flag WARNINGMSG is defined. Level 3 would enable the debug messages that are currently only available when the compiler flag DEBUG is defined.

In my experience, trouble with minimizing some function is common so it would be a great asset to enable more debug output at anytime by just increasing the print level without recompiling ROOT.

The DEBUG messages are particularly problematic in the current system, because they use std::cout while MnPrint uses the compile-time configurable MNLOG (which defaults to std::cerr).

#### Breaking changes?

This proposal does not change the output for print level 0, but there is a minor change for print level 1.

It changes the output of scripts/software that uses print level 1, because previously level 1 meant "print errors and info" while in the new hierarchy it means "print errors and warnings". I think this is a minor effect, which has to be documented in the next changelog but it cannot cause backward incompatibilities or breakage.

#### Reduced performance?

The impact on performance is expected to be negligible.

I propose to place additional calls into the compiled code for everyone, but these calls are not executed unless the user picks a high print level. For a low print level, there is just the minor additional cost of a branch, which moreover can be predicted very well by the CPU, so the added cost should be almost zero. Furthermore, these branches do not happen in hot code paths. Hot paths are inside the cost function (which are unaffected) and in the linear algebra routines that Minuit2 uses (which are not instrumented with debug messages).

### Positive side-effects for wrappers and frontends

An important positive side effect for wrappers like iminuit is that we could show our users debug messages, too. Right now, we cannot, because DEBUG messages can only be enabled at compile-time, not at run-time.

The DEBUG messages are also problematic in the current system, because they use std::cout while MnPrint uses the compile-time configurable MNLOG (which defaults to std::cerr). For wrappers like iminuit, it is important to redirect the log to its own streams that can be readout and displayed in Python, for example in a Jupyter notebook session (std::cerr and std::cout always go to the terminal and are invisible in a Jupyter notebook).

**Comment by HDembinski** [comment]
@lmoneta I would be very interested in your thoughts on this.

**Comment by lmoneta** [comment]
Hello Hans, 
Thank you for your proposal. I think is a good improvement, the current situation I agree is a bit messy and what you propose is a good step forward. 
We should see if we do not enable too many messages in printlevel=1, which is often used.
I think also level 3 is used often (for example when fitting histograms in ROOT with the verbose option). In that case we might want to use instead level 2 and keep level 3 only for debugging. 

Some work will also be needed to clean-up some of the debug messages

 Thanks for opening this issue, 
Best regards

Lorenzo

**Comment by HDembinski** [comment]
@lmoneta I would be happy to work on this, since I spend already some time thinking about how to do it.

**Comment by lmoneta** [comment]
This word be great ! Thank you for this!!

**Comment by HDembinski** [comment]
Implemented now, so closing this.
