### ISSUE TITLE
Typo in void TEnv::SetValue(const char *name, double value) implementation

### ISSUE THREAD

**Issue by dramoz** [root-project/root#6425]
Branch:  v6-22-00-patches (I checked master has the same issue)

On file:
  **root_src/core/base/src/TEnv.cxx**

in the implementation of the function: **TEnv::SetValue**
**line#: 784**

```
void TEnv::SetValue(const char *name, double value)
{
   SetValue(name, Form("%g", value));
}

```
the argument value should be **Double_t** as declared in the correspoinding TEnv.h file.

Regards,
Danilo.

**Comment by eguiraud** [comment]
Thanks for reporting this!
