### ISSUE TITLE
Debug builds in nightlies (and releases)

### ISSUE THREAD

**Issue by andriish** [root-project/root#6430]
# Problem
It is more efficient to debug applications relying on ROOT having a debug ROOT build.

# Solution I would like

Provide debug builds for nightlies (and optionally for releases).

# Alternatives 

 - Debug on Linux with released ROOT works perfectly for standard RedHat distros ( the others are less relevant ).
 This is a very good alternative (thanks to Mattias!), but Linux-only and release-only. 

- Building from the sources is a very-very bad alternative, as the created builds cannot be transferred elsewhere, i.e. shared with collaborators.  Another reason why this is a bad alternative: building with the full configuration on Mac in a reasonable time requires a lot of CPU power, much more than a single user laptop can provide.

**Comment by andriish** [comment]
Hi  @Axel-Naumann ,

I understand that this "feature" is quite time consuming to implement.

But this is actually crucial for Mac. While for the other platforms one can have a reproduciable or common build with debug information (e.g. using on Linux the root-debug packages from EPEL) for Mac it is not possible. Some packages on Mac could come from homebrew, others from system, macports or from elsewhere.
As a result, if someone sees a problem in the official release for Mac, it is not possible to debug it --  the attempts to have a build that "same as the official, but with debug info" are futile.

Can something be done concerning this at least for a single Mac version?

Best regards,
Andrii

**Comment by Axel-Naumann** [comment]
I have enabled this for macOS 10.15 in the nightlies - they should arrive starting tomorrow. Let me know if that helps!

**Comment by andriish** [comment]
Thanks! Will try once it is there!

**Comment by andriish** [comment]
Hi @Axel-Naumann ,

are the debug builds for 10.15 actually there? When I try to use the 	root_v6.22.99.macosx64-10.15-clang120.tar.gz  the system reports no debug symbols. Do I miss something?
Also, from a brief look at 10.15 build vs 10.14 build I see they have the same size, which would be strange if one would have some debug info and the other would not.

Best regards,

Andrii

**Comment by Axel-Naumann** [comment]
Finally! See https://root.cern/download/nightly/?C=M;O=D - for instance https://root.cern/download/nightly/root_v6.23.01.macos-10.15-x86_64-clang120.debug.tar.gz

**Comment by andriish** [comment]
Thanks!!!
