### ISSUE TITLE
`\brief`s have disappeared from the tutorials

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#6433]
## Describe the bug
Listings in the tutorials groups were showing `\brief`s in the past. Compare
https://root.cern/doc/master/group__tutorial__roofit.html
https://root.cern/doc/v622/group__tutorial__roofit.html
with
https://root.cern/doc/v620/group__tutorial__roofit.html

**Comment by couet** [comment]
I sse: it is working for some other: https://root.cern/doc/master/group__tutorial__fit.html

**Comment by couet** [comment]
The fix in simple: we should not use the keyword `\brief`  it is not needed.
If That's ok wit you I can make a PR to remove it .

**Comment by hageboeck** [comment]
My current theory is that this works:
```
 /// \file
 /// \ingroup tutorial_graphics
 /// \notebook -js
 /// Draw ellipses.
```
and this doesn't:
```
 /// \file
 /// \ingroup tutorial_graphics
 /// \notebook -js
 ///
 /// Draw ellipses.
```
Maybe that's why Enrico and me needed to add the `\brief`s before doxygen was updated.

**Comment by couet** [comment]
Most the tutorials are working without \brief (see the graphics ones for instance) . I will check with a local build and create a PR.
