### ISSUE TITLE
Windows CI runs roottest despite build failure

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#6441]
roottest / testing should not be done if the build failed.

**Comment by dpiparo** [comment]
Is this a "Won't fix" because of this cause de force majeure?

**Comment by bellenot** [comment]
I guess so, but I can cross-check again...

**Comment by pcanal** [comment]
Is there an possible work-around? (for example create a special file is case of success and check for that in lieu of the error code of the script)

**Comment by dpiparo** [comment]
I would favour that: @bellenot would that be possible?

**Comment by bellenot** [comment]
I think this was on Jenkins only, so not valid anymore with the new CI. To be confirmed

**Comment by dpiparo** [comment]
Can this be confirmed, e.g. with a PR that make the build fail (e.g. invalid c++ in a random file)? It would be nice to close this item.

**Comment by bellenot** [comment]
So this is confirmed by PR #15327: This issue was for Jenkins and not relevant anymore with the new CI, therefore I close this issue.
