### ISSUE TITLE
ROOT signed-char convertion issue on AARCH64

### ISSUE THREAD

**Issue by smuzaffar** [root-project/root#6465]
Hi,
  One unit test in CMSSW is failing on `aarch64` ( https://github.com/cms-sw/cmssw/issues/31194 ) . We noticed that root is treating `char` as `unsigned` while root is build with `-fsigned-char` e.g. in root interactive shell we get this
1. aarch64
```
root [0] static_cast<int>(static_cast<char>(-1))
(int) 255
``` 

2. amd64
```
root [0] static_cast<int>(static_cast<char>(-1))
(int) -1
```

https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/root.spec#L40 is how we configure and build root for both amd64 and aarch64. 

Is it a known issue? Any suggestion how to fix/avoid this.

Thanks

**Comment by Axel-Naumann** [comment]
Do you want this in v6.22?

**Comment by smuzaffar** [comment]
yes please, v6.22 is default cmssw development release.

**Comment by Axel-Naumann** [comment]
Merged, apologies for the delay and thanks for pinging me by means of a PR! :-)
