### ISSUE TITLE
Documentation of TDirectory::TContext.

### ISSUE THREAD

**Issue by pcanal** [root-project/root#6500]
## Explain what you would like to see improved

TDirectory::TContext should be documented more explicitly.  Currently the "documentation" is spread through-out release notes and git logs.  See the releases notes for v5.34 patches and v6.06 as well as the commit log for
843a15939587b0f730ce81d668ae0358b8d89cf6
af78af292ca467334ebb175e1d437a02abcc7d83
135e659287a8b7199b4bdf7bd7c0baac514f8258

**Comment by couet** [comment]
@JohannesHentrich can you have a look at that one ?

**Comment by couet** [comment]
This PR improves the TContext doc: https://github.com/root-project/root/pull/7564
@pcanal can you approve it ?

**Comment by couet** [comment]
fixed
