### ISSUE TITLE
Thread safety in TPad

### ISSUE THREAD

**Issue by andriish** [root-project/root#6510]
## Describe the bug
Crash.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff59494f8 in TPad::ShowGuidelines (this=0x249da40, object=0x249da40, event=21, mode=114 'r', cling=true) at /home/andriish/Projects/ROOT/root/graf2d/gpad/src/TPad.cxx:6248
6248	      tmpGuideLinePad->Delete();
(gdb) bt
#0  0x00007ffff59494f8 in TPad::ShowGuidelines(TObject*, int, char, bool) (this=0x249da40, object=0x249da40, event=21, mode=114 'r', cling=true) at /Projects/ROOT/root/graf2d/gpad/src/TPad.cxx:6248
#1  0x00007ffff5932f5f in TPad::ExecuteEvent(int, int, int) (this=0x249da40, event=21, px=412, py=186) at  /Projects/ROOT/root/graf2d/gpad/src/TPad.cxx:2159

```

## Expected behavior
No crash.

## To Reproduce
No working standalone reproducer so far.

## Setup
master ROOT with gcc4.8.5 on CentOS7

## Additional context
The relevant code is 

```
   static TPad * tmpGuideLinePad;

   //delete all existing Guidelines and create new invisible pad
   if (tmpGuideLinePad) {
      if (object == tmpGuideLinePad) { // in case of funny button click combination.
         tmpGuideLinePad->Delete();
         tmpGuideLinePad = 0;
         return;
      }
      tmpGuideLinePad->Delete();
      tmpGuideLinePad = 0;
   }

```
Obviously the code if completely ok for a single thread application.
However, a protection for multithread apps is needed when dealing with tmpGuideLinePad.

Tag @couet

**Comment by andriish** [comment]
No, there are cases when I still have crash.

**Comment by pcanal** [comment]
How is this uses in a multi-thread enviroment?  I.e. I seem to see a description of the crash but not a description of what is being run.

**Comment by andriish** [comment]
Hi @pcanal  ,

> How is this uses in a multi-thread enviroment

That is used in  a multi-thread program.

>not a description of what is being run.

Yes, that is a kind of "collaboration" code for event display. It is not very large but not very small.
So far I haven't managed to mage a standalone reproducer, but as far as I understand there should be a general approach in ROOT how to deal with static variables within a class, so I've expected this will be quite an easy case for the ROOT experts even w/o a reproducer code.


Best regards,
Andrii

**Comment by andriish** [comment]
Should I try to make a standalone reproducer?

**Comment by pcanal** [comment]
What I don't understand yet is why 2 threads would be executing something that seems to be (usually) only triggered by a user action/GUI.  

If/Since creating the standalone reproducer is not trivial, a first step would be to get the full stack trace of when/where this portion of the code is called (i.e. the stack trace of the at least 2 threads that are running this code at the same time).

**Comment by pcanal** [comment]
> o I've expected this will be quite an easy case for the ROOT experts even w/o a reproducer code.

Taking the one global lock is a heavy/costly solution is should be reserved to the last resort but to properly address it we need to understand what is coming (see also my potential fix (which may or may not break the single thread case) suggested on the PR)

**Comment by andriish** [comment]
Hi @lmoneta ,


thanks for setting a high priority.
Will try to provide more info. In the best case maybe even a standalone reproducer.

Sorry for some silence

Andrii

**Comment by andriish** [comment]
Hi @couet , @lmoneta , @pcanal ,

here is a reproducer.
```

#include <TCanvas.h>
#include <TBox.h>
#include <thread>
#include <vector>

TCanvas* C=nullptr;
void test_function(const int& id)
{
    C->cd(id);
    TPad* p= new TPad();
    p->Draw();
    p->cd();
    TBox *x =  new TBox( );
    for (int i=0; i<10; i++) p->ShowGuidelines(x, kButton1Down, 'l', true );
    delete x;
    delete p;
    return;
}
int main(int argc, char **argv) {
    C= new TCanvas("C","C",1024,768);
    const int N=20;
    C->Divide(1,N);
    std::vector<std::thread> threads;
    std::vector<int> ids;
    for (int j=0; j<N; j++) ids.push_back(j+1);
    for (size_t j=0; j<ids.size(); j++)
        threads.push_back(std::thread(test_function,ids[j]));
    for (auto& th : threads) th.join();
    threads.clear();
    delete C;
    return 0;
}
```
I do

```
g++ $(root-config  --glibs --cflags ) -g pad9.cxx -o pad9.exe
./pad9.exe
````
and get
```
*** Error in `./pad9.exe': double free or corruption (fasttop): 0x00007f125c001100 ***
*** Error in `./pad9.exe
 *** Break *** segmentation violation
Aborted (core dumped)
```
if I comment line with ``p->ShowGuidelines`` everything is fine.

ROOT 6.22.02/gcc 4.8.5/CentOS7 x64_64.

Best regards,

Andrii









Sorry if there are more crashes.

**Comment by andriish** [comment]
Hi @couet ,

> a "normal" user program

Yes. The event display.

The whole set of pull requests and bug reports I did over the last month is about it.


Best regards,

Andrii

**Comment by couet** [comment]
_The whole set of pull requests and bug reports I did over the last month is about it._

Do youyou have a specific PR for that one ?

**Comment by andriish** [comment]
Hi @couet ,

> The event display.
6373
I mean zevis, the codebase from https://github.com/root-project/root/issues/6344

> Do youyou have a specific PR for that one ? 

So no, it looks it is more efficient to split all the issues into independent PRs. 
There were many small issues occurring here and there and many are already closed  (Thank you!).
There are couple that still remain.  Of course if I see some other 'easy' issues I report them, but honestly to say I'm happy with ROOT as it is (Thanks again). So the reported issues and PRs are quite thematic and are mostly about graphics.

The issues:  #6373   #6375 #6446 #6510  
The PR:     #6505 #6511 #6537   (and partially #6547)


Best regards,

Andrii

**Comment by andriish** [comment]
Hi @couet,

the reproducer from this thread now hangs. Better than a crash, but still bad.

Anrii

**Comment by couet** [comment]
can we close this ?

**Comment by andriish** [comment]
Hi @couet ,

I don't know. I cannot check anything with nightlies/master  because of #7202 , so it makes sense to keep it open.

Honestly to say I don't event know where to get that package from #7202 in /cvmfs. Any searches in the internet don't provide any useful info.


Best regards,

Andrii

**Comment by andriish** [comment]
OK, 
I've checked with 
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-centos7-gcc8-opt/bin/root
and the issue is still there.

Of course, I know how to fix that for *my* case   -- I just have to disable the `ShowGuidelines` and I'm happy to do that.
So I don't mind if you close this issue, even if the reproducer still crashes.

In short: I don't mind if you close it.

Best regards,

Andrii
