### ISSUE TITLE
[TreeReader] When looping over a TTree with a friend with a larger number of entries, the loop spans all entries in the friend

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#6518]
## Expected behavior

Just like TTree does, TTreeReader should limit the event loop to the number of entries in the main tree.

## To Reproduce

The following self-contained reproducer should print 10 (number of entries in the main tree), but prints 20 (number of entries in the friend tree).

```cpp
#include <ROOT/RDataFrame.hxx>
#include <TTreeReader.h>
#include <TTreeReaderValue.h>
#include <TFile.h>
#include <TTree.h>
#include <iostream>

int main() {
   ROOT::RDataFrame(10).Define("x", "42").Snapshot("main", "main.root", {"x"});
   ROOT::RDataFrame(20).Define("y", "1").Snapshot("friend", "friend.root", {"y"});

   TFile fmain("main.root");                                                      
   auto tmain = fmain.Get<TTree>("main");     
   TFile ffriend("friend.root");
   auto tfriend = ffriend.Get<TTree>("friend");

   tmain->AddFriend(tfriend);  

   int counter = 0;
   TTreeReader r(tmain);  
   while (r.Next())
      ++counter;
   std::cout << "should be 10: " << counter << std::endl;

   return 0;
}   
```

This becomes problematic when comparing e.g. the output of `TTree::Draw` with the output of `RDataFrame::Histo1D`:

```cpp
tmain->Draw("x"); // fills the histogram with 10 entries
ROOT::RDataFrame(*tmain).Histo1D("x")->DrawClone(); // fills the histogram with 20 entries, 10 of which are bogus
```

## Additional context

The problem was first reported [on the forum](https://root-forum.cern.ch/t/add-friend-with-rdataframe/41652/10) and via TTreeReader it affects RDataFrame analyses too (but only if implicit multi-threading is disabled).

**Comment by eguiraud** [comment]
(might even be critical priority since it can result in wrong data being silently read)

**Comment by eguiraud** [comment]
Hi,
I double-checked the behavior of `TTree::Draw` and `TTreeReader` when reading "misaligned" friends in a number of situations: as `TTrees`/`TChains`, friends longer/shorter than the main tree, friends with/without a `TTreeIndex`.

With the path at https://github.com/root-project/root/pull/7131, which avoids an infinite loop with `TTreeReader` + indexed friend tree, `TTreeReader` and `TTree::Draw` behave the same in all cases except the one reported here. This means e.g. that switching from using a `TTree` to using a `TChain` to read the same data can change the number of entries `TTreeReader` reads in case of a friend that's larger than the main `TTree`.

The problematic logic is that of `TTree::LoadTree(entry)`, which does not return an error if `entry` is larger than the number of entries in the main tree as long as the friend tree has enough entries (again note that `TChain` behaves differently, ending the event loop as soon as the main tree entries are over, and `TTree/TChain::Draw` also behaves like that).

In particular, these lines are what causes `TTree::LoadTree` to not return an error:

https://github.com/root-project/root/blob/8d616f45e399d3a918b6a78edf98aa54219eb5d2/tree/tree/src/TTree.cxx#L6447-L6452

<hr>

Now, should `TTree::LoadTree` behave differently, or should `TTreeReader::SetEntryBase` not rely (just) on the return value of `LoadTree` to decide whether the event loop is over?

**Comment by pcanal** [comment]
Semantically the right termination condition is "no more entries in the branch **actually** used" .... which none of the tool does properly if I understand correctly ...

**Comment by eguiraud** [comment]
Correct, that doesn't seem to be a thing. 

This is my repro: https://gist.github.com/eguiraud/f5b8f045d993acd1c62a242a957c1a94

**Comment by pcanal** [comment]
Yes, I agree ... more work :(

**Comment by eguiraud** [comment]
Do you actually want to change the behavior of TTree::Draw and TTreeReader so the stopping condition depends on the branches that are being read? That is a lot more work than "just" making the behavior of TTreeReader+TTree consistent with TTree::Draw and TTreeReader+TChain.

**Comment by pcanal** [comment]
I think we __eventually__ should but in the short term you plan is good enough (in my humble opinion)
