### ISSUE TITLE
root.cern marked as "unsafe" by Google 

### ISSUE THREAD

**Issue by cozzyd** [root-project/root#6539]
Currently, when I visited any page hosted at root.cern  (but not root.cern.ch...) I get a big scary warning (on Firefox) which directs me to https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2Froot.cern%2F

![image](https://user-images.githubusercontent.com/9206569/94927540-0b810400-0488-11eb-995d-0eb9ac4e9faf.png)

This started this morning. I assume this will eventually be fixed, but as a workaround to make the documentation usable it might be worth changing all the internal links to point to root.cern.ch.

**Comment by cozzyd** [comment]
Oops, I see that there is another repository for the web site. I think an admin can transfer to there, or otherwise I'll close and reopen.

**Comment by couet** [comment]
yes, better close and reopen
