### ISSUE TITLE
Crash message should point to github

### ISSUE THREAD

**Issue by andriish** [root-project/root#6540]
## Explain what you would like to see improved
The current crash message of root applications contains
```
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs
```

## Optional: share how it could be improved
The message could be updated to point the users to https://github.com/root-project/root

## To Reproduce
Crash root in any way.

## Setup
Any

**Comment by couet** [comment]
Good point. We can also make sure http://root.cern.ch/bugs goes to the GitHub issues.

**Comment by couet** [comment]
@Axel-Naumann It looks like http://root.cern.ch/bugs is an alias pointing to Jira. I am not sure where such aliases are defined. Is it possible to make it point to the ROOT Github Issues instead ?

Also I guess we should change "http" to "https" in that message (I can do it if you agree)

**Comment by Axel-Naumann** [comment]
http://root.cern.ch/bugs is now fixed. Yes please change to https.

**Comment by couet** [comment]
done: https://github.com/root-project/root/pull/6541
Can you approve ?

**Comment by Axel-Naumann** [comment]
So then this is fixed? If so, @couet please close the issue once #6541 is merged.

**Comment by couet** [comment]
yes it is fixed. I just merged.
