### ISSUE TITLE
PyROOT (de)serialization using pickle (or  dill)  fails without pre-import of ROOT for new PyROOT  

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#6552]
[ ] Checked for duplicates

## Describe the bug

*New PyROOT* fails to (de)serialize the ROOT   objects  using `pickle`  (or  `dill`) if  `ROOT` module is not pre-imported. 
If one pre-imports `ROOT` module, deserialization is successful, otherwise it results in  the segmentation fauilt. 
It is definitely related to  *new PyROOT* - with  *old PyROOT*, deserialization is successfull both with `pickle`  and `dill`.
 

(For `python3` there is another problem  described in  [issue#6370](https://github.com/root-project/root/issues/6370)  )
## Expected behavior

Deseriazation should  *not* depend on pre-import of `ROOT`

## To Reproduce

see this  [gist](https://gist.github.com/VanyaBelyaev/1403e2ea8853ad68d7a7fba1e3496f67) where there are reproducers both  for `pickle`  and for `dill`

The  first  lines in the scritps show  the test matrix: It   fails for `LCG_98` and for lcg-dev3-slot, while is it  successful for LCG versions from  LCG_95 to  LCG_97a.   (see the environment part in the reproducers) 
 
## Setup

1. ROOT version      6.22-6.23
2. Operating system  lxplus 
3. How you obtained ROOT: lxplus  , cvmfs, LCG  

## Additional context

It could have something common   with [issue#6370](https://github.com/root-project/root/issues/6370), but  those issue is `pyton3`-specific, while this one for  `python2.7+new PyROOT`

**Comment by etejedor** [comment]
Thank you for reporting this difference. The reason is that new PyROOT has split in a few libraries, when it used to be only one in the old PyROOT. In this case, the deserialization causes the loading and initialization of `libROOTPythonizations`, but `libcppyy` has not been loaded yet, leading to the crash you see. `import ROOT` makes sure everything is loaded and initialized by the time you deserialize.

Is it an issue though that you need to import ROOT prior to deserializing ROOT objects in Python?

**Comment by VanyaBelyaev** [comment]
Hi Enric, 
Thank you very much! 
Indeed it is a kind of problem
I rely on pickling in my project   for two cases:

1. implicitely, where I use the `parallel python`/`multiprocess`/`multiprocessing`/`pathos` to split  the task into subtasks that can be executed in parallel in different processes or even on different nodes. Behind the scene such stuff relies on serialization/deserialization of objects via `pickle` or `dill`
2.  explicitely  where I store my data into custom  `shelve`-like database, that relies  on serialization of objects via pickling.

- for (1) I do not know if I  can properly inject "import ROOT" into the code flow at all vital occurances. 
- for (2) of course I can pre-import `ROOT` for all manipulations with custom database, but it is rather  unnatural solution.  E.g. opening a  (originally `ROOT`-blind) database I need to know that it contains some  `ROOT`-objects, and in this case use `import ROOT` before accessing objects from the database. Currently  I've added `import ROOT` just in the code of database,  but it is not a perfect solution. It is acceptable  as kind of a temporary patch, but if possible I'd like to avoid it in  the long-term future.

**Comment by etejedor** [comment]
Thank you for the clarification.

I had a closer look to this. The problem resides in that, during the deserialization, `libROOTPythonizations` is loaded, which in turn triggers the loading of `libcppyy`. Both libraries are extension modules. During the module initialization of `libROOTPythonizations`, it calls into `libcppyy`, but the latter has not been initialized yet (it has not been imported as a module), which causes the error.

What I can try to do is ensure `libcppyy` is imported during the initialization of `libROOTPythonizations`. Let's see how that goes.

**Comment by etejedor** [comment]
I made a PR with a possible solution: https://github.com/root-project/root/pull/6654 .

Could you please test it and let me know if it makes your use case work?

**Comment by etejedor** [comment]
I don't see the segmentation fault in your reproducer anymore if I apply the fix of the aforementioned PR. I am merging. Please let me know if you have any further problem.

**Comment by VanyaBelyaev** [comment]
Hi Enric, 
Thank you very much.
How can I test the fix? 
I still see seg.fault for `source /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc9-opt/setup.sh`

**Comment by etejedor** [comment]
I just merged it, so you should be able to test it in dev3 tomorrow.

**Comment by VanyaBelyaev** [comment]
Excellent! Thank you very much!
