### ISSUE TITLE
RVec docs do not show DOI banner

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#6565]
If you go to https://root.cern/doc/master/classROOT_1_1VecOps_1_1RVec.html, you'll see that the DOI banner is not shown. I'll attach a screenshot below.
![Screenshot from 2020-10-06 15-09-59](https://user-images.githubusercontent.com/6951222/95205799-2c2dbe80-07e6-11eb-9144-e7765d3f5963.png)

**Comment by couet** [comment]
I do not see this problem. The banner is visible for me:
<img width="912" alt="Screenshot 2020-10-12 at 16 31 25" src="https://user-images.githubusercontent.com/4697738/95758205-6e547580-0ca8-11eb-837e-6cba235cea34.png">

**Comment by couet** [comment]
Can I close ? this issues seems to be irrelevant now.
