### ISSUE TITLE
Build option exceptions is broken

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#6569]
The option can be found here: https://github.com/root-project/root/blob/master/cmake/modules/RootBuildOptions.cmake#L120

**Comment by hahnjo** [comment]
According to #9114, this option should be deprecated / removed.

**Comment by guitargeek** [comment]
Correct, and we don't want to fix something that should not be used anyway.

**Comment by hahnjo** [comment]
FWIW I don't agree with just closing this: the option is currently broken and it needs some action to deprecate / remove it. The issue should only be closed afterwards.

**Comment by Axel-Naumann** [comment]
Well, we have a dedicated issue for *that* part, so if we keep this one open because we want to do what's in the other issue then it feels like a duplication. But details, happy to reopen this one :-)

**Comment by guitargeek** [comment]
I try to close this again, now that this is merged:
https://github.com/root-project/root/pull/13856
:slightly_smiling_face:
