### ISSUE TITLE
The new -Dasserts=ON flag breaks standalone roottest

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#6575]
### Describe the bug

Our nightly conda builds are affected.

An example of the broken tests is [here](https://lcgapp-services.cern.ch/root-jenkins/view/conda/job/conda-nightlies/183/testReport/junit/projectroot.cling/array/roottest_cling_array_runarray1/). The relevant part of the output:

```
cd /test_job/roottest_build/cling/array
/usr/bin/timeout -s USR2 270s /opt/conda/envs/test-root/bin/root -e '#define NDEBUG' -e '#define ClingWorkAroundMissingDynamicScope' -e '#define ClingWorkAroundUnnamedInclude' -e '#define ClingWorkAroundMissingSmartInclude' -e '#define ClingWorkAroundNoDotInclude' -e '#define ClingWorkAroundMissingAutoLoadingForTemplates' -e '#define ClingWorkAroundAutoParseUsingNamespace' -e '#define ClingWorkAroundTClassUpdateDouble32' -e '#define ClingWorkAroundAutoParseDeclaration' -e '#define ClingWorkAroundMissingUnloading' -e '#define ClingWorkAroundBrokenUnnamedReturn' -e '#define ClingWorkAroundUnnamedDetection2' -e 'gSystem->SetBuildDir("/test_job/roottest_build/cling/array",true)' -e 'gSystem->AddDynamicPath("/test_job/roottest_build/cling/array")' -e 'gROOT->SetMacroPath("/test_job/roottest/cling/array")' -e 'gInterpreter->AddIncludePath("-I/test_job/roottest_build/cling/array")' -e 'gSystem->AddIncludePath("-I/test_job/roottest_build/cling/array")' -q -l -b /test_job/roottest/cling/array/runarray1test.C
-- BEGIN TEST OUTPUT --

ROOT_cli_0:1:9: warning: 'NDEBUG' macro redefined [-Wmacro-redefined]
#define NDEBUG
        ^
<command line>:1:9: note: previous definition is here
#define NDEBUG 1
        ^
```

### To Reproduce

To reproduce it's sufficient to compile ROOT with `-DCMAKE_BUILD_TYPE=Release -Droottest=OFF` and then compile roottest separately against this build of ROOT. 

### Additional context

As far as I understand, that ` -e '#define NDEBUG'` in the invocation of `root.exe` used by roottest was not there before, and it's what's causing the issue.

roottest takes the `-e '#define ...'` arguments from cmake's `COMPILE_DEFINITIONS` (a quick `git grep COMPILE_DEFINITIONS` in the roottest repository shows where this happens).

I could not figure out where the _other_ definition of `NDEBUG` comes from.

**Comment by stwunsch** [comment]
I think that the issue comes from the fact that we do not pick up our own defaults for `CMAKE_CXX_FLAGS_${BUILD_TYPE}$ (see the issue https://github.com/root-project/root/issues/6574) and then `asserts=OFF` adds another `NDEBUG`. Then we have two `-DNDEBUG` ending up in the sum of all compiler flags.

**Comment by stwunsch** [comment]
Here some example (including the PR https://github.com/root-project/root/pull/6572 which prints the actual compiler flags):

```
-- ROOT Configuration 

System          Linux-5.8.13-arch1-1
Processor       2 core Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (x86_64)
Build type      RelWithDebInfo
Install path    /usr/local
Compiler        GNU 10.2.0
Compiler flags:
C                -Wno-implicit-fallthrough -pipe -Wall -W -pthread -DNDEBUG -O2 -g -DNDEBUG
C++              -std=c++17 -Wno-implicit-fallthrough -Wno-noexcept-type -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -DNDEBUG -O2 -g -DNDEBUG
Linker flags:
Executable       -rdynamic
Module          
Shared           -Wl,--no-undefined -Wl,--hash-style="both"
```

**Comment by stwunsch** [comment]
Let's keep this open until we have the confirmation from the CI that the issue is fixed.

**Comment by eguiraud** [comment]
Running [here](https://lcgapp-services.cern.ch/root-jenkins/view/conda/job/conda-nightlies/184/)

**Comment by stwunsch** [comment]
Fixed!
