### ISSUE TITLE
Use CMAKE_CXX_FLAGS_${BUILD_TYPE}_INIT to overwrite cmake defaults

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#6577]
The current setup of the defaults for `CMAKE_CXX_FLAGS_${BUILD_TYPE}` are not picked up (also see https://github.com/root-project/root/issues/6574). To change the defaults for ROOT **and** allowing users to set their own `CMAKE_CXX_FLAGS_${BUILD_TYPE}` flags, the definition of the ROOT specific defaults have to move before we invoke `project(ROOT)`.

Geant4 has a proper implementation of such a mechanic [here](https://github.com/Geant4/geant4/blob/67ba86d073ec6366df0de75a0f5b5d57920d0b7e/CMakeLists.txt#L24-L32). The proper approach is overwriting `CMAKE_CXX_FLAGS_${BUILD_TYPE}_INIT` (note the `_INIT`) before invoking `project(ROOT)`.

**Comment by hageboeck** [comment]
@stwunsch your "fix" #6574 broke cmake conventions. If you break it, I think you should take care that it gets fixed in time.

When my builds didn't do what they should, I didn't really expect that it's *again* the cache variables, which Guilherme and me had fixed before in order to customise builds.
You should be nicer towards users who want to customise their builds to report bugs to you guys with exact code locations etc (#7903). :-)

@Axel-Naumann @oshadura ping?

**Comment by stwunsch** [comment]
> @stwunsch your "fix" #6574 broke cmake conventions. If you break it, I think you should take care that it gets fixed in time.
> 

💥 

> When my builds didn't do what they should, I didn't really expect that it's _again_ the cache variables, which Guilherme and me had fixed before in order to customise builds.
> You should be nicer towards users who want to customise their builds to report bugs to you guys with exact code locations etc (#7903). :-)
> 
> @Axel-Naumann @oshadura ping?

So the approach lined out in this issue is correct, we want the `*_INIT` thingy, right? The violation of the cmake conventions is using `FORCE`, do I understand this correctly?

I don't remember why it hasn't been done like that in the first place, because we were definitely aware of this (because this issue exists).

**Comment by hageboeck** [comment]
> So the approach lined out in this issue is correct, we want the `*_INIT` thingy, right? The violation of the cmake conventions is using `FORCE`, do I understand this correctly?

Yes, users should be able to configure (and reconfigure, therefore `CACHE`) with `-DCMAKE_CXX_FLAGS_DEBUG=-O1 -g` if the want to. With `FORCE` ROOT just overwrites it.
And the `_INIT`s should set those variables to what ROOT wants, and then users can overwrite them as they see fit. 👍

**Comment by stwunsch** [comment]
Ah I start to remember why it's so complicated. We set the flags in the `SetUp(Linux|MacOS|Windows).cmake` scripts called in the `CheckCompiler.cmake` [here](https://github.com/root-project/root/blob/master/CMakeLists.txt#L130). But we have to call this after figuring out all the build flags, which is way after we call `project(ROOT)` [here](https://github.com/root-project/root/blob/master/CMakeLists.txt#L32).

The questions is for me now whether we can "just" move the `project(ROOT)` after figuring out the build flags and then use the `*_INIT` instead of forcing the variable. Currently, we have to force it because otherwise we cannot change the defaults for which we want asserts in `RelWithDebInfo`.

**Comment by hageboeck** [comment]
I don't see where the `asserts` BuildOption is used?! I only see that it's defined and set.

The assert yes/no problem might be solved either by setting the flags manually as users would do it `cmake -DCMAKE_CXX_FLAGS_RELEASE="-O2"` or by a string replacement:
```cmake
foreach(flag_var
    CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
    CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
  if(${flag_var} MATCHES "NDEBUG")
    string(REGEX REPLACE "-DNDEBUG" "" ${flag_var} "${${flag_var}}")
  endif()
endforeach()
```

**Comment by stwunsch** [comment]
Any build option, like `dev` [here](https://github.com/root-project/root/blob/master/cmake/modules/SetUpLinux.cmake#L40) or whatever you find in these scripts, may be subject to change during the lines https://github.com/root-project/root/blob/master/CMakeLists.txt#L33-L128. If this happens, we would break the current behaviour if we move the `CheckCompiler` macro before calling `project(ROOT)`. I think if any of these flags is dependent on finding a package, which has to happen after `project(ROOT)`.

**Comment by stwunsch** [comment]
Ah hell breaks loose, just tried to move things around. E.g. `find_package` calls like [here](https://github.com/root-project/root/blob/master/cmake/modules/CheckCompiler.cmake#L183) prevent to move full macros around, meaning in front of `project(ROOT)`. So we have to dissect these and then move parts out of it.

**Comment by hageboeck** [comment]
This might be a solution. The point is that those things are loaded after cmake's defaults, but before the information is put to use.

### MyInitFlags.cmake
```cmake
 # Overwrite the init values choosen by CMake
 if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
     set(CMAKE_CXX_FLAGS_DEBUG_INIT "-ggdb3 -O0")
 endif()
```
### CMakeLists.txt
```cmake
 set(CMAKE_USER_MAKE_RULES_OVERRIDE "MyInitFlags.cmake")

 project(your_project C CXX)
```

From [here](https://stackoverflow.com/questions/28732209/change-default-value-of-cmake-cxx-flags-debug-and-friends-in-cmake)


An alternative, also from that post, is to check whether users tried to alter the variables. That's probably less work for ROOT's setup:
```cmake

 project(your_project C CXX)

 if (DEFINED CMAKE_CXX_FLAGS_DEBUG_INIT AND  
     "${CMAKE_CXX_FLAGS_DEBUG_INIT}" STREQUAL "${CMAKE_CXX_FLAGS_DEBUG}")
     # Overwrite the init values choosen by CMake
     if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
         set(CMAKE_CXX_FLAGS_DEBUG "-ggdb3 -O0" CACHE STRING "" FORCE)
     endif()
 endif()
```

**Comment by stwunsch** [comment]
@hageboeck I've linked a fix following the second proposal. However, it seems just to prepend the provided flags, not completely replaces them:

```
/usr/bin/cmake3 -DCMAKE_CXX_FLAGS_RELEASE_INIT="foo" /path/to/src

...
-- Compiler flags for CMAKE_CXX_FLAGS_RELEASE are not set to the default values because CMAKE_CXX_FLAGS_RELEASE_INIT was explicitely set.
...
-- ROOT Platform: linux
-- ROOT Compiler: GNU 4.8.5
-- ROOT Processor: x86_64
-- ROOT Architecture: linuxx8664gcc
-- Build Type: 'Release' (flags = 'foo -O2 -DNDEBUG')
...
```

Does this make sense?

**Comment by stwunsch** [comment]
@hageboeck Ok, here:

```
/usr/bin/cmake3 -DCMAKE_CXX_FLAGS_RELEASE="foo" /path/to/src

...
-- Compiler flags for CMAKE_CXX_FLAGS_RELEASE are not set to ROOT's default values because the variable was explicitely set.
-- Performing Test GLIBCXX_USE_CXX11_ABI
-- Performing Test GLIBCXX_USE_CXX11_ABI - Failed
-- ROOT Platform: linux
-- ROOT Compiler: GNU 4.8.5
-- ROOT Processor: x86_64
-- ROOT Architecture: linuxx8664gcc
-- Build Type: 'Release' (flags = 'foo')
-- Compiler Flags:  -std=c++11 -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread foo
...
```

I've updated the PR. Does this look good to you?

**Comment by hageboeck** [comment]
Ok, I had another look -- also at the cmake documentation --, and I'm wondering now:
Why are we setting the optimisation flags at all?

A "clean" way is probably this:
- We remove the setting of the flags from `SetUpLinux` and `SetUpMac`. They didn't have an effect in the past, and nobody complained other than not being able to override them.
- If we think that `-O2` is better than `-O3`, it's fine to do it [here](https://github.com/root-project/root/blob/f040e05154c9f4c9899cd6e2262c68a0af944ea5/CMakeLists.txt#L14) by setting one of the `*_INIT` variables.
  - We seem to be able to use the same for linux as for Mac, so less configs, and for Windows we just don't do anything. CMake will figure it out.
- If you want asserts, there's two easy ways to get them:
  1. Configure with `cmake -DCMAKE_CXX_FLAGS_RELEASE="-O2 -g" ...`
  2. We create a custom build type assert using `set(CMAKE_CXX_FLAGS_ASSERT_INIT "-O2 -g")`


Thoughts?

**Comment by stwunsch** [comment]
Actually, I agree. In particular because we haven't using the defaults in these files for years and it just came up due to our assert fiasco.

But you see, it's going to be a larger surgery to remove the `SetUp*.cmake` files. And stuff will just break if we don't use the build in our CI. That's why I'm hesitant to touch too much of these internals.

@oshadura @Axel-Naumann Now it's your turn to dive into this and state your opinion :)

**Comment by stwunsch** [comment]
Probably to summarize: Following cmake best practise, all `CMAKE_CXX_FLAGS*` should be set **before** calling `project(ROOT)`. Indeed, this could be ok if no build flag relies on finding a package and then changes its behaviour. **After** `project(ROOT)` we should change `CMAKE_CXX_FLAGS*` just by doing string manipulation.

@hageboeck Is this correct?

**Comment by hageboeck** [comment]
It's sufficient to set the `CMAKE_CXX_*_INIT` versions of the build-type related flags *if* we want to change the defaults. Then, cmake will populate the actual flags for us, and users can override them as they see fit.

After `project(root)`, string manipulations are OK, but **not** overriding the entire string.
Appending the whole chain of warning and linker flags can still be done in those `SetUp*` files. I would leave them mostly intact, and would just remove the "cache force" lines.

@stwunsch I *think* those flags were in effect for quite a while, because they weren't `CACHE` flags before I had trouble overriding them. When I made them `CACHE` in 2019 3c42b07168b8315ac1ed1abbf69f89d5f4e99099, the config lines stopped having an effect, but you were able to set them from the outside again.

**Comment by hageboeck** [comment]
> Edit: So this means, we should just remove the `-DNDEBUG` flag via string matching if we enable asserts.

Yes, you can either remove any debug-related string:
```cmake
string(REGEX REPLACE "-.NDEBUG" "" CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE} "${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}}")
```
or the lazy clutter-the-string version
```cmake
set(CMAKE_BUILD_TYPE_RELEASE "${CMAKE_BUILD_TYPE_RELEASE} -UNDEBUG")
```

**Comment by hageboeck** [comment]
Let me do a PR, since I tested it already.
