### ISSUE TITLE
Cannot set TPaveText text color to white

### ISSUE THREAD

**Issue by janTOffermann** [root-project/root#6593]
Hi ROOTers!

### Description
When setting text color in TPaveText (via TAttText::SetTextColor()), text that is set to white displays as black.

### To Reproduce
I produced this unexpected behavior by running the PyROOT code below (Python3). I was _also_ able to reproduce the error by running the equivalent C++ code in the ROOT interactive prompt.
```
import sys, ROOT as rt
def main(args):
    c = rt.TCanvas('c','c',800,600)
    pave = rt.TPaveText(0.25,0.25,0.75,0.75,option='NDC')
    pave.AddText('This line is in black.')
#    pave.GetListOfLines().Last().SetTextColor(rt.kBlack) # redundant (black is default)
    pave.AddText('This line is in red.')
    pave.GetListOfLines().Last().SetTextColor(rt.kRed)
    pave.AddText('This line is in white.')
    pave.GetListOfLines().Last().SetTextColor(rt.kWhite)
    pave.Draw()
    c.Draw()
    c.SaveAs('color_pave.png')
    return
if __name__ == '__main__':
    main(sys.argv)
```

### Output
[Here is what I see as output from the code above (color_pave.png).](https://drive.google.com/file/d/16rtJc1gQtYeifRwNi4ZjDEOvg0TTVqQa/view?usp=sharing)

### Setup
ROOT version: 6.22/02 (built from source)
Operating system: macOS 10.14.6

---------------------------------------------
Let me know if you have any questions.

**Comment by couet** [comment]
Color index 0 (kWhite) has a special status. 0 means "default", and you fall back to black.
One way is:
```
void jant(){
   auto c    = new TCanvas("c","c",800,600);
   auto pave = new TPaveText(0.25,0.25,0.75,0.75,"NDC");
   pave->AddText("This line is in black.");
   pave->AddText("This line is in red.");
   TLatex* t1 = (TLatex*)(pave->GetListOfLines()->Last());
   t1->SetTextColor(kRed);
   pave->AddText("This line is in white.");
   TLatex* t2 = (TLatex*)(pave->GetListOfLines()->Last());
   //TColor MyWhite
   Int_t ci = 12345;
   TColor *color = new TColor(ci, 1., 1., 1.);
   t2->SetTextColor(ci);
   pave->Draw();
   c->Draw();
}
```

**Comment by janTOffermann** [comment]
Thank you for the quick response, @couet, your example code helps!
However, is this peculiarity mentioned in the ROOT documentation? This behavior was not so clear to me from the [TAttText documentation](https://root.cern.ch/doc/master/classTAttText.html), and it looks like setting the text color to white in my naïve way does work in some other contexts, e.g.:
```
void jant2(){
   auto c    = new TCanvas("c","c",800,600);
   auto pave = new TPaveText(0.25,0.25,0.75,0.75,"NDC");
   pave->SetTextColor(kWhite); // setting all text to white this time (not line-by-line changes)
   pave->AddText("This line is in white.");
   pave->AddText("This line is also in white.");
   pave->Draw();
   c->Draw();
}
```

**Comment by couet** [comment]
This peculiarity is mentioned here: https://root.cern/doc/master/classTColor.html#C02
