### ISSUE TITLE
TClassEdit::GetNormalizedName does not strip std::allocator on Windows

### ISSUE THREAD

**Issue by jblomer** [root-project/root#6607]
### Describe the bug
The type name normalization `TClassEdit::GetNormalizedName` does not strip the allocator off STL classes on Windows. On Linux, it works.

### Expected behavior
On both, Windows and Linux the following should be true

```
std::string n;
TClassEdit::GetNormalizedName(n, "std::vector<float, class std::allocator<float>>");
n == std::string("vector<float>");
```

Note that even on Windows the allocator _is_ stripped for `std::vector<float, std::allocator<float>>` (i.e. without prefixing `std::allocator` by `class`)

### Additional context
The issue was found while testing PR #6548

**Comment by pcanal** [comment]
There is code to explicitly detect and remove the allocator.  Most likely `TClassEdit::IsDefAlloc` needs to be updated to take into account that the word `class` might be prefixed.  Albeit it is odd/unexpected that Clang would put the class keyword there (it is supposed be configured not to).
