### ISSUE TITLE
[JupyROOT] ROOT C++ Kernel only working as superuser

### ISSUE THREAD

**Issue by kllp** [root-project/root#6608]
- [x ] Checked for duplicates

### Describe the bug

`sudo root --notebook --log-level 10 --allow-root` works
`root --notebook --log-level 10` does not, jupyter is trying to reconnect to the kernel every few seconds.
There is no helpful debug output.

For debugging I put some print statements around that line but that doesn't help much:
`/usr/lib/python3.8/site-packages/JupyROOT/kernel/rootkernel.py`
and noticed that the kernel freezes on line 57:
`MetaKernel.__init__(self,**kwargs)`

With sudo it does not freeze.

### Setup

1. ROOT Version: 6.22/02
2. arch linux
3. I tried both the package manager version and the [manual installation](https://root.cern/install).

I also gave miniconda and anaconda a try but both don't work for ROOT because of dependency conflicts.

The python kernel works flawlessly.

**Comment by etejedor** [comment]
Thanks for the report, I did a quick test with master and I can't reproduce on an Ubuntu18, compiling ROOT from sources.

Can it be a permissions issue? E.g. the `kernel.json` of the ROOT kernel should be readable. Let's assume you compile from sources, you do `source bin/thisroot.sh` in the build directory and then run `root --notebook`. This should have created `$HOME/.rootnb/kernels/root/kernel.json`, which should be readable. Can you confirm that with these steps you also reproduce the error?

On the other hand, I'm using `metakernel` 0.24.4, what is the version you are using?

Finally, if you run `jupyter kernelspec list`, what does it say?

**Comment by etejedor** [comment]
The `cling::CIFactory` error you get it when opening the ROOT C++ kernel from Jupyter?

@stwunsch could you please try if you can reproduce this on arch?

**Comment by kllp** [comment]
@etejedor yes exactly, the first time it occurs is right after `root --notebook`

**Comment by stwunsch** [comment]
Hi @kllp,

I'm also running Arch, let me share with you my setup using conda:

```bash
source /path/to/miniconda3/bin/activate
conda create -c conda-forge --name test-jupyroot root
conda activate test-jupyroot
root --notebook --log-level 10
```

Unfortunately, I cannot reproduce your issues. Could you retry with the setup lined out above (see [here](https://root.cern/install/#conda) for more information)?

Best
Stefan

**Comment by kllp** [comment]
@stwunsch thanks for tuning in. I installed a clean miniconda3 and ran your commands.
I get the same result like before. It only works with `sudo`.
`Python 3` or `xeus-cling c++17` kernels work but `ROOT C++` does not. No useful debug output. `Kernel starting, please wait...` shows forever. 
`Timeout waiting for kernel_info reply`
And I can't evaluate cells. Could be a hard to find permission issue. Closing.
