### ISSUE TITLE
Writing an RVec to a TTree via TBufferMerger omits its streamer infos

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#6611]
### Describe the bug

First reported [on the forum](https://root-forum.cern.ch/t/missing-tstreamerinfo-for-branches-of-rvec/41805).
`RDataFrame` creates `TTree` branches containing `RVecs` as `tree.Branch("rvec", &rvec.AsVector())`.
When writing to a classic `TFile`, the output file contains streamer infos related to RVecs such as `vector<float,ROOT::Detail::VecOps::RAdoptAllocator<float> >`. When using `TBufferMerger`, the output file does not contain such streamer infos.

ROOT can read the data back anyway, but third party libraries such as `uproot` reportedly have a harder time.

### To Reproduce

A reproducer that only depends on `RVec` and `TBufferMerger`:

```cpp
#include <ROOT/TBufferMerger.hxx>
#include <ROOT/RVec.hxx>
#include <TTree.h>
#include <TFile.h>
#include <iostream>

int main()
{
   // output file has vector<float, RAdoptAllocator<float>> in the streamerinfolist
   {
      TFile f("standardwrite.root", "recreate");
      TTree t("t", "t", 99, &f);
      ROOT::RVec<float> rv{1, 2, 3};
      t.Branch("v", &rv.AsVector());
      t.Fill();
      f.Write();
   }

   std::cout << "***** standard write ******" << std::endl;
   auto f2 = TFile::Open("standardwrite.root");
   for (auto e : *f2->GetStreamerInfoList()) {
      std::cout << e->GetName() << std::endl;
   }

   // output file does not have vector<float, RAdoptAllocator<float>> in the streamerinfolist
   {
      ROOT::Experimental::TBufferMerger bm("buffermerger.root", "recreate");
      auto f = bm.GetFile();
      TTree t("t", "t", 99, f.get());
      ROOT::RVec<float> rv{1, 2, 3};
      t.Branch("v", &rv.AsVector());
      t.Fill();
      f->Write();
   }

   std::cout << "\n\n***** TBufferMerger ******" << std::endl;
   auto f = TFile::Open("buffermerger.root");
   for (auto e : *f->GetStreamerInfoList()) {
      std::cout << e->GetName() << std::endl;
   }

   return 0;
}
```

**Comment by pcanal** [comment]
Since RVec 2.0 leverage the CollectionProxy infrastructure, it should not need a StreamerInfo (i.e. it is implicit like all the STL collections)

**Comment by eguiraud** [comment]
Closing as this is (now, with RVec 2.0) the expected behavior.
