### ISSUE TITLE
CMake ExternalProject: add `TIMEOUT`

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#6635]
### Explain what you would like to see improved
We had CI builds stuck in downloading dependencies, e.g. VecCore. That should timeout.

### Optional: share how it could be improved
Add the `TIMEOUT` parameter to all `ExternalProject` calls downloading sources.

**Comment by Harshalzzzzzzz** [comment]
@Axel-Naumann  @oshadura 
Dear Mentors,
I would like to take up this issue, and since I'm new to this project could you please explain a bit more about what I can do to fix this?
Thank you

**Comment by Axel-Naumann** [comment]
Check the CMake `TIMEOUT` parameter for `ExternalProject`. Not sure what else to add. If this is unclear for you then maybe pick a different issue to start with?

**Comment by Harshalzzzzzzz** [comment]
@Axel-Naumann @oshadura Pull Request : https://github.com/root-project/root/pull/7136

**Comment by Harshalzzzzzzz** [comment]
@Axel-Naumann @oshadura Pull Request : https://github.com/root-project/root/pull/7141

**Comment by oshadura** [comment]
fixed in: #7141
