### ISSUE TITLE
Misleading warning from TTreeReader::GetEntries

### ISSUE THREAD

**Issue by andrey-popov** [root-project/root#6641]
In certain cases `TTreeReader::GetEntries` gives an inappropriate warning. Here is a minimal example:
```C++
// test.C

#include <iostream>
#include <string>

#include <TChain.h>
#include <TFile.h>
#include <TTreeReader.h>
#include <TTreeReaderValue.h>

void WriteTestFiles() {
  for (int i = 0; i < 2; ++i) {
    TFile file(("test" + std::to_string(i + 1) + ".root").c_str(), "recreate");
    TTree tree("tree", "");

    int n = 1;
    TBranch *branch = tree.Branch("n", &n);
    branch->SetTitle("Title");
    tree.Fill();

    tree.Write();
    file.Close();
  }
}

void test() {
  WriteTestFiles();

  TChain chain("tree");
  chain.Add("test*.root");
  TTreeReader reader;
  reader.SetTree(&chain);

  TTreeReaderValue<int> n{reader, "n"};
  std::cout << reader.GetTree()->GetBranch("n")->GetTitle() << std::endl;
  std::cout << reader.GetEntries(true) << std::endl;  // Gives warning
}
```
Running this as `root -q -b -l test.C` in ROOT 6.20/04 or 6.22/02 gives the following warning:
```
Warning in <TTreeReader::SetEntryBase()>: The current tree in the TChain tree has changed (e.g. by TTree::Process) even though TTreeReader::SetEntry() was called, which switched the tree again. Did you mean to call TTreeReader::SetLocalEntry()?
```
I believe the code in the snippet is valid and hence the warning should not be printed. The warning disappears if the calls to `reader.GetTree` and `reader.GetEntries` are swapped or if another call to `reader.GetEntries` is inserted before `reader.GetTree`.

This might be related to the issue reported [here](https://root-forum.cern.ch/t/warning-in-ttreereader-with-tchain/34484), which has since been fixed.

**Comment by eguiraud** [comment]
Hi @andrey-popov ,
TTreeReader has a built-in assumption that it is the only one modifying the state of its internal tree.
The `GetBranch` call changes the state of the tree in a way that confuses TTreeReader when it looks at it at the next line.

You can/should do this instead:

```
  TChain chain("tree");                                                                                                 
  chain.Add("test*.root");                                                                                              
  std::cout << chain.GetBranch("n")->GetTitle() << std::endl;                                                           
  TTreeReader reader;                                                                                                   
  reader.SetTree(&chain);                                                                                               
                                                                                                                        
  TTreeReaderValue<int> n{reader, "n"};                                                                                 
  std::cout << reader.GetEntries(true) << std::endl;  // no warning
```

and only have read-only interactions with the TTree/TChain as long as TTreeReader is working with it (`GetBranch` sounds like a read-only operation, but it's not).

**Comment by eguiraud** [comment]
(another alternative is calling `reader.Restart()` after you perform non-read-only operations on the object returned by `reader.GetTree()`, before `TTreeReader` itself accesses the object).

**Comment by eguiraud** [comment]
Hi,
as per my comments above, and discussion with @Axel-Naumann , this sequence of calls without a `Restart` in the middle is not supported. Closing.
