### ISSUE TITLE
crash after installing root version v6-22-00 on suse Leap 15-2

### ISSUE THREAD

**Issue by kurbatov-lang** [root-project/root#6645]
- [ ] Checked for duplicates

### Additional context

[bugs.txt](https://github.com/root-project/root/files/5383141/bugs.txt)

**Comment by etejedor** [comment]
Thank you for the report @kurbatov-lang ! Could you please provide a reproducer of how you get that crash?

**Comment by kurbatov-lang** [comment]
Thanks for quick reaction!

First, how I installed root - I followed
instructions on https://root.cern/install/,
originally fulfilling all required dependencies
for suse and up to the end. All went smoothly.
At the end I issued the command source ../root_install/bin/thisroot.sh
and strted root.  After invoking root
I entered the command new TBroser( it is shown in bug report)
and it crashed!
  Waiting for you response, V.Kurbatov

**Comment by couet** [comment]
I think you should build root using some kind of "built-in-png" ... I guess @oshadura might know.

**Comment by kurbatov-lang** [comment]
How to use built-in-png?

Should I ask @oshadura ? If yes,
send me,please, his e-mail, or I may
use https://github.com/oshadura?
  Thanks

**Comment by oshadura** [comment]
@kurbatov-lang  What are a CMake flags you used for building ROOT?

**Comment by oshadura** [comment]
@kurbatov-lang  I see `libpng warning: Application built with libpng-1.2.55 but running with 1.6.34` which means that you build ROOT with one libpng and trying to use it with different.  Can you please recheck it?

**Comment by kurbatov-lang** [comment]
Recheck - what does it mean?
Thanks

**Comment by kurbatov-lang** [comment]
Exactry as it is recommended in build
instructions in https://root.cern/install/(for build
from source)!
  Thanks

**Comment by oshadura** [comment]
It looks like you have two different versions of libpng installed in your system (probably it could be libpng and libpng16 packages installed in the same time). Can you please post here the full output of ``` cmake ``` comand you were using? I need to see which libpng ROOT picks.

**Comment by oshadura** [comment]
I am looking for the next line in cmake output: ``` -- Found PNG: /usr/lib64/libpng.so (found version "1.6.34")  ```

**Comment by kurbatov-lang** [comment]
Dear Oksana!
My colleague(D.Cyrkov) solved this problem.
He is ready to give all the details. His e-mail -
cyrkov@jinr.ru.
  Best wishes,V.Kurbatov
