### ISSUE TITLE
segfault in TClass::InheritsFrom() depending on linking order

### ISSUE THREAD

**Issue by britzger** [root-project/root#6670]
In our analysis package we obtain a segfault without traceback when calling InheritsFrom() on an object derived from a TObject. The awkward issue is dependent on the ordering of the objects and dictionaries in the shared library. 
Note: important is the fact, that another class has a static member of that TClass(). The compiled object of the other class can then not be linked before the Dictionary-object of the first class. Maybe it's just my ignorance of a deeper understanding of the whole concept, or maybe it is a bug somewhere.

A rather minimum example is attached would look like:
int main() { 
 TMyDerivedClass::Class()->InheritsFrom(TObject::Class());
}

Please run `make all`, then `test1` (works) and `test2` does not work, while the difference is only in the order of the objects in the shared library.
I have included into that example another class that works well (as it is not a static member elsewhere.)
I have included a Dump() call, and one recognizes the differences for identical objects in the two shared libraries (e.g. fTitle="", *fData=0, ...)

[root_issue.tar.gz](https://github.com/root-project/root/files/5405256/root_issue.tar.gz)

We tested with root 6.20 and gcc9.2 (from lcg) and 6.22 and gcc4.8, both on EL7.
The code previously worked well with ROOT 5.34.

**Comment by pcanal** [comment]
Thanks for the complete report.   Indeed there was a problem triggered by a change in order of initialization.  The fix (PR #6680) will be merge shortly in the main branch as well as the v6.20 and v6.22 patch branches.

**Comment by britzger** [comment]
Thanks for this quick patch. We have observed similar issues also at other places of the code, when calling TClass::New(), but we always found simple workarounds there as well. Together with #6535 (where we have a patch as well) these were the *only* issues in the entire H1@HERA analysis packages when going from ROOT5.34 to ROOT6.20. albeit it was initially developed for ROOT2.25 and CINT. Congrats to the ROOT developers!
