### ISSUE TITLE
RDataFrame.Histo1D of many columns uses excessive amount of memory

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#6676]
The following reproducer uses an excessive amount of memory:

```python
import ROOT
ROOT.gROOT.SetBatch(True)
ROOT.EnableImplicitMT()

h = {}
df = ROOT.RDataFrame('Events', 'DYJetsToLL.root')

# Types with vector<bool> are broken, see #6675
columns = [str(col) for col in df.GetColumnNames() if not 'Bool' in str(df.GetColumnType(col))]

for col in columns:
    h[col] = df.Histo1D(col)

for col in columns:
    c = ROOT.TCanvas(col, col, 600, 600)
    h[col].Draw()
    c.SaveAs(col + '.png')
```

I could not let the script finish without filling 16GB memory + 20GB swap. Here's the max res size from the interrupted run:

```bash
$ /usr/bin/time python rep.py 
Command terminated by signal 15
769.89user 56.57system 3:57.31elapsed 348%CPU (0avgtext+0avgdata 13316884maxresident)k
17064208inputs+0outputs (215131major+12346853minor)pagefaults 0swaps
```

And two screenshots of `htop` during the run of the script and right after killing the process. So it's not chrome which fills my memory ;)
![Screenshot from 2020-10-20 14-17-01](https://user-images.githubusercontent.com/6951222/96585018-4df76d00-12df-11eb-921c-eea94afbd06b.png)
![Screenshot from 2020-10-20 14-17-28](https://user-images.githubusercontent.com/6951222/96585045-55b71180-12df-11eb-8001-75f12d2f3030.png)

I've used ROOT from conda v6.22/02. You can download the file here (http://opendata.web.cern.ch/record/12353#).

**Comment by stwunsch** [comment]
I wonder whether the file itself is broken?

**Comment by eguiraud** [comment]
Please check where the allocations come from with `valgrind --tool=massif` (I think you need to use a debug build, i.e. not a conda package for this to work).

**Comment by eguiraud** [comment]
My guess is that because a binning is not specified RDF is storing `std::vector<double>`s with all entries of all columns and that's just too much. I don't think anyone ever tried to fill so many histograms with so many entries each (no filters) without specifying a binning.

We could do something like `TTree::Draw` does and estimate the binning from the first N entries, but we always avoided it because it requires locking during a multi-thread event loop. Let's see what massif says first though.

**Comment by stwunsch** [comment]
> My guess is that because a binning is not specified RDF is storing `std::vector<double>`s with all entries of all columns and that's just too much. I don't think anyone ever tried to fill so many histograms with so many entries each (no filters) without specifying a binning.
> 
> We could do something like `TTree::Draw` does and estimate the binning from the first N entries, but we always avoided it because it requires locking during a multi-thread event loop. Let's see what massif says first though.

Ah, thanks for the explanation. That makes sense, the file has around 8 GB (compressed size).

**Comment by stwunsch** [comment]
Here's the test program for which I'm doing the massif profile:

```cpp
#include "ROOT/RDataFrame.hxx"
#include "ROOT/RVec.hxx"
#include "ROOT/RDF/RInterface.hxx"
#include "TH1D.h"
#include "TCanvas.h"

#include <string>
#include <vector>
#include <iostream>

int main() {
    using namespace std;
    using namespace ROOT;

    RDataFrame df("Events", "DYJetsToLL.root");

    vector<string> cols;
    for (auto& col: df.GetColumnNames()) {
        const auto type = df.GetColumnType(col);
        if (type.find("RVec<Float_t>") != string::npos) {
            cols.emplace_back(col);
            cout << "Select column " << col << " with type " << type << endl;
        }
    }

    vector<RDF::RResultPtr<TH1D>> hists;
    for (auto& col: cols) {
        hists.emplace_back(df.Histo1D<RVec<float>>(col));
    }

    for (auto i = 0u; i < hists.size(); i++) {
        auto c = new TCanvas(cols[i].c_str(), cols[i].c_str(), 600, 600);
        hists[i]->Draw();
        c->SaveAs((cols[i] + ".png").c_str());
        delete c;
    }
}
```

You can find the profile attached, but it's not very clear to me what we can learn from it. We have 3GB from malloc/new, but it's not clear where it's coming from.
[ms_print_cpp.log](https://github.com/root-project/root/files/5437832/ms_print_cpp.log)

**Comment by eguiraud** [comment]
Some debug symbols seem to be missing so we don't have line number information, but this log is already enough to confirm my hypothesis above: 2.9 GB come from std::vector allocations performed by `RDF::FillHelper::Exec<ROOT::VecOps::RVec<float>, 0>`.

The simplest workaround is to specify a binning for the histograms. I am not sure whether this is a common enough problem to warrant a fix in RDF if the fix involves thread synchronization or other potential performance pessimizations. Alternatively, if we can come up with a mutex-free algorithm to automatically select binnings that are compatible among threads that might be the best option -- some related discussion on this topic is [here](https://sft.its.cern.ch/jira/browse/ROOT-8883).

Moving this to priority "default" since there is a workaround.

**Comment by stwunsch** [comment]
I wonder why the information is missing, it's a `RelWithDebInfo` build and no jitting involved :thinking: 
But I agree that combined with your knowledge about the code, it's clear where it comes from.

It's not clear to me whether it's an issue or not. Definitely, it's confusing to see your machine blow up for no reason and I'm sure it's a pain to figure this out. What about a warning if you use histograms without a binning? But I don't see how we could do this so that the exploratory analysis in the shell isn't messed up with warnings all the time.

**Comment by eguiraud** [comment]
> Edit: And I would call the code above exploratory ;) It's a smallish sample in terms of HEP data and you just want to see the distribution of each column.

Yes, that should make it ok to run on fewer events right?

We could add warnings like "please specify a binning" if vectors become too large, but it's quite unclear what "too large" is (in principle in depends on the exact runtime behavior of the analysis, e.g. whether events are filtered a lot or not, but that would require that RDF monitors its own RAM usage which is tricky).

So I'm not sure how to proceed. Ideas? :D

**Comment by stwunsch** [comment]
No ideas :/

**Comment by eguiraud** [comment]
Closing as "won't fix", please specify a binning to avoid accumulation of a large number of values in memory.

**Comment by ShamrockLee** [comment]
I encountered similar issue, and found a workaround by dropping the `ROOT::EnableImplicitMT()` line (in C++).

**Comment by ShamrockLee** [comment]
> Hi @ShamrockLee , specifying a binning for the histogram is often better than disabling multi-threading (which potentially implies a large performance decrease), but yes that also works :D
> 
> The fundamental problem here is the lack of a good multi-thread auto-binning algorithm that does not require synchronization between threads (which we want to avoid at all costs in order to scale well to large amounts of cores and large amounts of histograms produced).

Hi @eguiraud , thanks for replying.
I do specify a binning for every histogram being generated. However, the bin number is about ~20000 each histogram in order to guarantee there's no unexpected overflow/underflow.
