### ISSUE TITLE
Support UTF-8 encoding in ROOT7

### ISSUE THREAD

**Issue by pamputt** [root-project/root#6681]
### Is your feature request related to a problem? Please describe.

Hello, as described in [ROOT-7859](https://sft.its.cern.ch/jira/browse/ROOT-7859), ROOT does not handle UTF8 encoding for characters in the current ROOT version (6.22).

### Describe the solution you'd like
It would be really nice to have such support since as shown on the sreenshot [here](https://sft.its.cern.ch/jira/secure/attachment/18752/TBrowser.png), characters with diacritics (here is the "é" character) are not correctly displayed.
It already exists some workarounds for the graphics (see the forum post) but it does not work in the case of the TBrowser for example.

**Comment by linev** [comment]
For the moment JSROOT and all ROOT7 widgets enforce `utf-8` on produced web pages.
But it should be possible to extend  ROOT7 functionality and support other encodings as well.

We also have to investigate usage of `wchar` type on C++ side if different encodings  has to be used at the same time.

Thanks for pointing it out!

**Comment by anerokhi** [comment]
> We also have to investigate usage of `wchar` type on C++ side

Really hope `wchar` is a typo and `char8_t` was meant.

**Comment by linev** [comment]
Finally after https://github.com/root-project/root/pull/8344 merged into the master, UTF-8 is properly supported in TBufferJSON and therefore can be transferred to the client without problems. In all ROOT-based web widgets UTF-8 set as default and therefore directly works without any limitation for any kind of elements like `RText`, `RAxis` titles and so on.

**Comment by linev** [comment]
As a side effect. also ROOT6 TCanvas with utf-8 text inside, should also properly works when displayed in the web-browser with JSROOT. Like with `root --web hsimple.C`
