### ISSUE TITLE
Unable to install pytest on MacOS with python2

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#6686]
We removed the pytest shipped with roottest because the source code was from 2014 and incompatible with py3.9 (see #6597). However, this poses now the issue on MacOs with python2 that we have to install pytest. Without a virtual environment, MacOS does not allow to pip packages. Since roottest fails on configuration level without pytest, roottest is currently broken in this configuration.

@axel @oshadura What should we do? Our CI always runs roottest against python3, so we currently don't see the issue in our infrastructure. I see three options:
1. Ditch testing of python2 on MacOS and rely on the test coverage of other platforms (python2 is anyway dead)
2. Use a venv overlay in Jenkins for the MacOS nodes (haven't tested but it should work and is binary compatible with the system python)
3. We change the hard failure of roottest to a soft failure.

**Comment by oshadura** [comment]
I will say the first option is very reasonable for me (yes python2 is dead anyway!!!), but what if some experiment didn't manage to move to python3? How hard is to implement the second option?

**Comment by stwunsch** [comment]
Wrt to the experiments, I think it's not so critical. Mac isn't used anyway for any experiment specific usage of ROOT. I guess, @axel please correct me, MacOS is purely a platform used by analysts. I think we could drop py2 for MacOS, however, since there's no system python3 we cannot build reliably any binaries against python. So it's a convoluted thing :)

**Comment by stwunsch** [comment]
Regarding option 2 (using a venv to overcome the installation issue): Technically, I'm rather sure we can make it work. However, I'm more scared of the additional complexity added to the CI. Someone has to maintain all these fixes on the long run!

**Comment by Axel-Naumann** [comment]
Not testing py2 on MacOS is probably reasonable. There is a system py3 as of Xcode 12.

> Without a virtual environment, MacOS does not allow to pip packages

I'm very surprised about that - not even `pip --user` or whatever it's called?

**Comment by stwunsch** [comment]
> Not testing py2 on MacOS is probably reasonable. There is a system py3 as of Xcode 12.
> 
> > Without a virtual environment, MacOS does not allow to pip packages
> 
> I'm very surprised about that - not even `pip --user` or whatever it's called?

Well, the actual issue is that there is no `pip` for the system python2 installation. The virtualenv is the solution to get `pip` easily. I think installing `pip` manually is the least favored solution.

**Comment by stwunsch** [comment]
But ok, if we agree that we build with python2 and python3 on MacOS, but test only against python2, then we are fine. Feel free to close the issue!
