### ISSUE TITLE
gROOT->ProcessLine("#include ... ") faster loaded

### ISSUE THREAD

**Issue by cxwx** [root-project/root#6719]
### Explain what you would like to see improved
Hi all,
It takes long time for loading rootlogon.C about(20s)
I've test for the reason
It seems I've a line
```
gROOT->ProcessLine("#include <ROOT_cx.hh>");
```
[ROOT_cx.hh.zip](https://github.com/root-project/root/files/5453842/ROOT_cx.hh.zip)
I include all of the header file I've used in this header
I cannot find a faster way doing this

### Optional: share how it could be improved

 precompile rootlogon.C
or other ways. 

### Setup

1. ROOT version 6.22.02
2. Operating system Mac OS X 10.15 lastest
3. How you obtained ROOT,  from homebrew

### Additional context

see https://root-forum.cern.ch/t/groot-processline-include-slower-than-before/42031

**Comment by jalopezg-uc3m** [comment]
The user claims that processing the aforementioned line is slower w.r.t. ROOT 6.20.02.  No run time measurements are provided, though.

Requested to add an issue here, but this is still to be confirmed.

**Comment by dpiparo** [comment]
Dear @cxwx, in absence of a reproducer, I will close the issue: if you think this should not be done please re-open it with a comment.
However, let me try to propose a solution, even if a lot of guessing is done without knowing anything about the header file you want to include. Why don't you generate a dictionary and "precompile"that header in the form of a pcm? Alternatively, you could refactor the code inside it and create a library and a very thin header to then load the library and include the header at startup. I hope this helps.
