### ISSUE TITLE
Add TEnum::GetSize

### ISSUE THREAD

**Issue by pcanal** [root-project/root#6721]
### Is your feature request related to a problem? Please describe.

Since C++11, the user can select a in-memory size for the enum, when constructing the list of data member of offset directly from clang/core-meta this is properly taken into account (i.e we ask each member for its offset) but when recalculating the offset "by hand" (eg in the on-the-fly pseudo dictionary generation for std::pair) we need to know the actual size of the enum given its typename ...

This information is currently not available from core meta (i.e. missing TEnum::GetSize) so we have to "assume" (incorrectly) 4 bytes in R__CreateEmulatedElement.

**Comment by Axel-Naumann** [comment]
Why not `TDataType *TEnum::GetUnderlyingType() const`?

**Comment by pcanal** [comment]
Missed it ... :(
So problem already solved :)

**Comment by pcanal** [comment]
> Why not TDataType *TEnum::GetUnderlyingType() const?

Well in part because it very indirect:
```
TEnum *e = ....
auto dtype = e->GetUnderlyingType();
auto datatype = TDataType::GetDataType(dtype);
size_t size = datatype ? datatype->Size() : sizeof(int);
```
