### ISSUE TITLE
TBrowser slowed down when used through X-forward

### ISSUE THREAD

**Issue by britzger** [root-project/root#6730]
Since newer releases, TBrowser considerably slowed down when used through an X-forward.

I tried on SL7, root6.20, gcc9.2, C++17 (LCG_97a)  &  SL7, root6.22, gcc4.8,C++11. These versions have considerably slowed down.

All worked well until at least 6.08 (SL6,gcc4.9,c++1y,LCG_88).

Minimum example (try from home):
```
ssh -C -X lxplus.cern.ch
root -l
new TBrowser
```
-> Slow !

Better:
```
ssh -C -X lxplus.cern.ch
cd /cvmfs/sft.cern.ch/lcg/releases/LCG_80/ROOT/6.04.06/x86_64-cc7-gcc48-opt/bin
. thisroot.sh
root -l
new TBrowser
```
-> good.

This issue is probably related to the new --web option, or some anti-aliasing.

**Comment by bellenot** [comment]
I don't think anything relevant really changed in the GUI, but I'll try. And that has most probably nothing to do with the `--web` option. Did you try with and without it, to check if it does any difference?

**Comment by bellenot** [comment]
@britzger can you check if changing the `X11.UseXft` value in your `${HOME}/.rootrc` fixes the issue? Thanks!

**Comment by britzger** [comment]
When using `X11.UseXft:  no` in $HOME/.rootrc , then all is back to normal. Very good! Could this become default again, then I don't have to maintain a local .rootrc file. Thanks.

**Comment by bellenot** [comment]
> When using `X11.UseXft: no` in $HOME/.rootrc , then all is back to normal. Very good! Could this become default again, then I don't have to maintain a local .rootrc file. Thanks.

Well, unfortunately no, it's most of the time more convenient to have Xft on, and might only cause trouble when using ssh connection with X11 forwarding

**Comment by bellenot** [comment]
I think this is clarified, so closing this issue.
