### ISSUE TITLE
[DF] When dataset is specified as treename/filename, the TTree is read without its friends

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#6741]
### Describe the bug

First reported on the forum [here](https://root-forum.cern.ch/t/rdataframe-and-friend-and-python/41923).
TTrees written to file preserve knowledge of their friends, and if they are also present in the file reading one TTree recovers the full friendship chain.

When constructing an RDF object as `RDataFrame(treename, filename)`, friends are not automatically made available as they are if the TTree is read from file manually and then passed to RDF's ctor.  

### To Reproduce

```cpp
root [0] TFile f("f.root", "recreate")
T(TFile &) Name: f.root Title: 
root [1] TTree t1("t1", "t1")
(TTree &) Name: t1 Title: t1
root [2] TTree t2("t2", "t2")
(TTree &) Name: t2 Title: t2
root [3] int x = 42
(int) 42
root [4] t2.Branch("x", &x)
(TBranch *) 0x5575916824d0
root [5] t2.Fill()
(int) 4
root [6] t1.AddFriend(&t2)
(TFriendElement *) 0x557591f09790
root [7] t1.Write()
(int) 231
root [8] t2.Write()
(int) 343
root [9] f.Close()
root [10] ROOT::RDataFrame("t1", "f.root").Max<int>("t2.x").GetValue()
Error in <TRint::HandleTermInput()>: std::runtime_error caught: Unknown column: t2.x
```

Note that extracting the TTree from file manually and then constructing RDF from the tree works:

```cpp
auto t1 = file.Get<TTree>("t1");
ROOT::RDataFrame(*t1).Max<int>("t2.x").GetValue() // prints 42
```

**Comment by pcanal** [comment]
Yes this is the intentional behavior.

Only the TTree list of friends is relevant per se because the friend could be from the TChain or from the TTree.  (Only infrastructure code that might need to do something 'different' in case the friend in chain wide, should worry about the TChain's list of friend).

> but chain.FindBranch("t2.x") does return the friend's 

By definition the Branch is TTree specific so indeed it will find something.

**Comment by eguiraud** [comment]
Thanks @pcanal , does this mean that the following line, in the RDF code that builds the list of all possible valid branch names, should be `t.GetTree()->GetListOfFriends()` instead of `t.GetListOfFriends()`? (`t` is almost always a `TChain`).

https://github.com/root-project/root/blob/5961bdd1fbd2773b052ede308ed7c55040b809d2/tree/dataframe/src/RDFInterfaceUtils.cxx#L319

**Comment by pcanal** [comment]
> should be t.GetTree()->GetListOfFriends() instead of t.GetListOfFriends()? (t is almost always a TChain).

Yes, as long as LoadTree have been already called.  Note that this syntax will work for both TChain and TTree object.

**Comment by eguiraud** [comment]
The RDF part should be fixed in https://github.com/root-project/root/compare/master...eguiraud:df_autofriends , but TTreeReader seems to also have a problem with this scenario (see issue linked above).

**Comment by eguiraud** [comment]
WIP at https://github.com/root-project/root/pull/6995

**Comment by eguiraud** [comment]
The fix is in master.
