### ISSUE TITLE
Add RDataFrame tutorial with systematics

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#6746]
Add `RDataFrame` tutorial which shows how to handle the computation of typical systematics. The idea is to have an example analysis such as the [Higgs to four leptons](https://root.cern.ch/doc/master/df103__NanoAODHiggsAnalysis_8C.html) and add an uncertainty band to the expectation:

![](https://root.cern.ch/doc/master/pict1_df103_NanoAODHiggsAnalysis.C.png)

We should showcase following types of systematics:

- Shifting an expectation with a duplicate dataset
- Shifting an expectation with a weight column
- Shifting an expectation with an ad-hoc expression (actually same than a weight column)

**Comment by stwunsch** [comment]
A WIP can be found [here](https://github.com/stwunsch/root/tree/df-tut-sys).

**Comment by martamaja10** [comment]
Possibly also continue/finish work from https://github.com/root-project/root/pull/11200
