### ISSUE TITLE
Pickling functions using the ROOT module with cloudpickle breaks

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#6764]
cloudpickle is the pickling package, which is used in dask and PySpark to serialize and distribute the work, e.g., functions or lambdas. The following reproducer breaks with cloudpickle (but is fine with the standard pickle) and throws the error `TypeError: cannot pickle 'ROOTFacade' object`, which is highly confusing.

```python
import ROOT
import cloudpickle


def foo():
    ROOT.TH1F()
    return 42

import cloudpickle as pickle # breaks with cloudpickle
#import pickle # works fine with the standard pickle

with open('f.pkl', 'wb') as f:
    pickle.dump(foo, f)
```

A workaround is moving the `import ROOT` line inside the function `foo`, which seems to omit the underlying issue in cloudpickle. We have submitted a bug report to the cloudpickle repository, see cloudpipe/cloudpickle#397.

**Comment by eguiraud** [comment]
Assigning low priority at least for now as it looks like we have a workaround and we anyway need to see if things move on the cloudpickle side.

**Comment by vepadulano** [comment]
There has been discussion on a cloudpickle issue very similar to this one, https://github.com/cloudpipe/cloudpickle/issues/405 .
In that issue they suggest a fix/workaround, that is to define a custom `__reduce__` method for the facade class that practically does the `import ROOT` automatically. I tried it with this reproducer
```python
import ROOT
import cloudpickle as pickle

def foo():
    return ROOT.TH1F()

print(pickle.loads(pickle.dumps(foo)))
print(pickle.loads(pickle.dumps(foo())))
```
and it works
```
$ python cloudpickle_root_th1f.py 
<function foo at 0x7f76c62679d0>
Name:  Title:  NbinsX: 1
```

I have opened a draft PR related to this issue to show the fix
