### ISSUE TITLE
An error when using Minuit in tutorial_tmva_TMVARegression

### ISSUE THREAD

**Issue by Binbin-Qi** [root-project/root#6773]
- [yes] Checked for duplicates

### Describe the bug

When I run the TMVARegression (root tutorial/tmva/TMVARegreession.C), I found the results by using FDA_GA and FDA_MT are different, but they use same function to do regression. The fit parameters from FDA_MT are always equal to zero. 

### Expected behavior

I have found the following ways to avoid this problem: 
In class TMVA::MinuitFitter, change the code at line 103 as shown bellow, and then reinstall root. Then the results from FDA_MT, FDA_SA and even FDA_GAMT are same.`

    void TMVA::MinuitFitter::Init()
    {
        .......... 
        //fMinWrap = new MinuitWrapper( fFitterTarget, 2*GetNpars() );
        fMinWrap = new MinuitWrapper( fFitterTarget, GetNpars() );
        ..........
    }
`

### To Reproduce

root tutorial/tmva/TMVARegreession.C

In TMVARegression.C, I use the FDA method as bellow: `  

    if (Use["FDA_MC"])
       factory->BookMethod( dataloader,  TMVA::Types::kFDA, "FDA_MC",
                           "!H:!V:Formula=(0)+(1)*x0+(2)*x1:ParRanges=(-100,100);(-100,100);(-100,100):FitMethod=MC:SampleSize=100000:Sigma=0.1" );
                                                                                                                                                                        
    if (Use["FDA_GA"]) // can also use Simulated Annealing (SA) algorithm (see Cuts_SA options) .. the formula of this example is good for parabolas
       factory->BookMethod( dataloader,  TMVA::Types::kFDA, "FDA_GA",
                            "!H:!V:Formula=(0)+(1)*x0+(2)*x1:ParRanges=(-100,100);(-100,100);(-100,100):FitMethod=GA:PopSize=100:Cycles=3:Steps=30:Trim=True:SaveBestGen=1" );
 
    if (Use["FDA_MT"])
       factory->BookMethod( dataloader,  TMVA::Types::kFDA, "FDA_MT",
                           "!H:!V:Formula=(0)+(1)*x0+(2)*x1:ParRanges=(-100,100);(-100,100);(-100,100):FitMethod=MINUIT:ErrorLevel=1:PrintLevel=-1:FitStrategy=2:UseImprove:UseMinos:SetBatch" );
 
    if (Use["FDA_GAMT"])
       factory->BookMethod( dataloader,  TMVA::Types::kFDA, "FDA_GAMT",
                            "!H:!V:Formula=(0)+(1)*x0+(2)*x1:ParRanges=(-100,100);(-100,100);(-100,100):FitMethod=GA:Converger=MINUIT:ErrorLevel=1:PrintLevel=-1:FitStrategy=0:!UseImprove:!UseMinos:SetBatch:Cycles=1:PopSize=5:Steps=5:Trim" );
`
### Setup

root-6.18.00, centos7, built it by myself.

**Comment by Binbin-Qi** [comment]
In TMVARegression.C, I use the FDA method as bellow: `  

    if (Use["FDA_MC"])
       factory->BookMethod( dataloader,  TMVA::Types::kFDA, "FDA_MC",
                           "!H:!V:Formula=(0)+(1)*x0+(2)*x1:ParRanges=(-100,100);(-100,100);(-100,100):FitMethod=MC:SampleSize=100000:Sigma=0.1" );
                                                                                                                                                                        
    if (Use["FDA_GA"]) // can also use Simulated Annealing (SA) algorithm (see Cuts_SA options) .. the formula of this example is good for parabolas
       factory->BookMethod( dataloader,  TMVA::Types::kFDA, "FDA_GA",
                            "!H:!V:Formula=(0)+(1)*x0+(2)*x1:ParRanges=(-100,100);(-100,100);(-100,100):FitMethod=GA:PopSize=100:Cycles=3:Steps=30:Trim=True:SaveBestGen=    1" );
 
    if (Use["FDA_MT"])
       factory->BookMethod( dataloader,  TMVA::Types::kFDA, "FDA_MT",
                           "!H:!V:Formula=(0)+(1)*x0+(2)*x1:ParRanges=(-100,100);(-100,100);(-100,100):FitMethod=MINUIT:ErrorLevel=1:PrintLevel=-1:FitStrategy=2:UseImpr    ove:UseMinos:SetBatch" );
 
    if (Use["FDA_GAMT"])
       factory->BookMethod( dataloader,  TMVA::Types::kFDA, "FDA_GAMT",
                            "!H:!V:Formula=(0)+(1)*x0+(2)*x1:ParRanges=(-100,100);(-100,100);(-100,100):FitMethod=GA:Converger=MINUIT:ErrorLevel=1:PrintLevel=-1:FitStrat    egy=0:!UseImprove:!UseMinos:SetBatch:Cycles=1:PopSize=5:Steps=5:Trim" );
`

**Comment by dpiparo** [comment]
Hi @lmoneta : is this still an issue?

**Comment by dpiparo** [comment]
@lmoneta is this still an issue in 6.30?

**Comment by dpiparo** [comment]
I finally got  to this item. The parameters are different for 6.32.
How to reproduce:
```
g++ -o a tutorials/tmva/TMVARegression.C  `root-config --libs --cflags` -lTMVAUtils -lTMVAGui -lTMVA
./a -b FDA_GAMT >& fda_gamt.out
./a -b FDA_MT >& fda_mt.out
diff fda_gamt.out fda_mt.out 
```
Gives:
```
<                          : Elapsed time for evaluation of 1000 events: 0.00143 sec       
< TFHandler_FDA_GAMT       : Variable        Mean        RMS   [        Min        Max ]
---
>                          : Elapsed time for evaluation of 1000 events: 0.00146 sec       
> TFHandler_FDA_MT         : Variable        Mean        RMS   [        Min        Max ]
207c201
<                          : datasetreg           FDA_GAMT       :    -64.4    -58.1     83.7     77.4  |  -0.000  -0.000
---
>                          : datasetreg           FDA_MT         :    -76.1    -69.6     87.3     80.9  |  0.914  0.893
215c209
<                          : datasetreg           FDA_GAMT       :    -61.5    -54.3     84.0     76.6  |  0.000  0.000
---
>                          : datasetreg           FDA_MT         :    -73.0    -65.6     87.7     80.0  |  0.923  0.872
```
