### ISSUE TITLE
Error in <TGLWidget::CreateWindow>: No good OpenGL visual found!

### ISSUE THREAD

**Issue by ThomasRuf** [root-project/root#6774]
I am working with root 6.22/02, virtual machine in cern openstack. glxgears runs, glxinfo below. I would like to know what I am missing to get TEve to work.

best regards,
Thomas Ruf

name of display: localhost:10.0
display: localhost:10  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.2
server glx extensions:
    GLX_ARB_multisample, GLX_EXT_import_context, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_OML_swap_method, GLX_SGIS_multisample, 
    GLX_SGIX_fbconfig, GLX_SGIX_hyperpipe, GLX_SGIX_swap_barrier, 
    GLX_SGI_make_current_read
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.2
GLX extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_import_context, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_MESA_query_renderer, 
    GLX_OML_swap_method, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGI_make_current_read
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: VMware, Inc. (0xffffffff)
    Device: llvmpipe (LLVM 10.0.0, 256 bits) (0xffffffff)
    Version: 20.0.8
    Accelerated: no
    Video memory: 7279MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
...

Full error:
Error in <TEveViewer::SpawnGLViewer>: Insufficient support from the graphics hardware. Aborting.
 *** Break *** segmentation violation
 Generating stack trace...
 0x00007fd360487563 in TEveViewer::SpawnGLViewer(TGedEditor*, bool, bool) at /media/disk1/SHiPBuild/sw/SOURCES/ROOT/5479ddb618_FAIRSHIP/0/graf3d/eve/src/TEveViewer.cxx:182 from /media/disk1/SHiPBuild/sw/ubuntu2004_x86-64/ROOT/5479ddb618_FAIRSHIP-1/lib/libEve.so.6.22
 0x00007fd360430693 in TEveManager::SpawnNewViewer(char const*, char const*, bool) at /media/disk1/SHiPBuild/sw/SOURCES/ROOT/5479ddb618_FAIRSHIP/0/graf3d/eve/src/TEveManager.cxx:327 (discriminator 4) from /media/disk1/SHiPBuild/sw/ubuntu2004_x86-64/ROOT/5479ddb618_FAIRSHIP-1/lib/libEve.so.6.22
 0x00007fd360433458 in TEveManager::TEveManager(unsigned int, unsigned int, bool, char const*) at /media/disk1/SHiPBuild/sw/SOURCES/ROOT/5479ddb618_FAIRSHIP/0/graf3d/eve/src/TEveManager.cxx:175 (discriminator 1) from /media/disk1/SHiPBuild/sw/ubuntu2004_x86-64/ROOT/5479ddb618_FAIRSHIP-1/lib/libEve.so.6.22
 0x00007fd360433885 in TEveManager::Create(bool, char const*) at /media/disk1/SHiPBuild/sw/SOURCES/ROOT/5479ddb618_FAIRSHIP/0/graf3d/eve/src/TEveManager.cxx:916 (discriminator 2) from /media/disk1/SHiPBuild/sw/ubuntu2004_x86-64/ROOT/5479ddb618_FAIRSHIP-1/lib/libEve.so.6.22
...

**Comment by linev** [comment]
I guess, @osschar has much more ideas that could happen here

**Comment by ThomasRuf** [comment]
in the meantime, I found a solution, although looks a bit strange:
export LIBGL_DRIVERS_PATH="/usr/share/bug/libgl1-mesa-dri" 

The event display works, there are only two errors appearing, but they don't stop the graphics:
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/share/bug/libgl1-mesa-dri)
libGL error: failed to load driver: swrast
and
Error in <TGLViewerBase::RenderOpaque - pre exit check>: GL Error invalid operation

**Comment by linev** [comment]
Seems to be, it is OpenGL configuration on your machine.
@ThomasRuf , can we close the issue?

**Comment by ThomasRuf** [comment]
almost. I still need to find out what "Error in <TGLViewerBase::RenderOpaque - pre exit check>" means and how to fix it, because this stops the execution of other code in my python script and returns to the command prompt.

**Comment by dpiparo** [comment]
Dear @ThomasRuf , I am closing the issue assuming your last checks went well. Please do not hesitate to reopen in case you are still encountering problems.
