### ISSUE TITLE
RootMacros.cmake does not support target's compile features for dictionary when creating it

### ISSUE THREAD

**Issue by rlalik** [root-project/root#6777]
### Describe the bug
The `ROOT_GENERATE_DICTIONARY` function from cmake creates dictionary `G_xxx_cc.cxx` and compieles it with different flags than rest of the target sources.

### Expected behavior
The `ROOT_GENERATE_DICTIONAR` body copies various properties of the target into new target for dictionary, and should also copy the compile features properties.

### To Reproduce
1. Create target with some non-standard feature, e.g. c++17 (requires root compiled against c++17, then `std::string_view` breaks compatibility with pre c++17 build)
```
target_compile_features(${ARG_TARGET} PRIVATE cxx_std_17)
```
2. Generate dictionary
```
ROOT_GENERATE_DICTIONARY(G__${ARG_TARGET}_cc
    ${ARG_HEADERS}
    MODULE ${ARG_TARGET}
    LINKDEF Linkdef.h
)
```
3. Compile such dictionary, the dict will not compile against c++17 and various errors related to `std::string_view` will appear.

### Setup
1. ROOT 6.22.02
2. Operating system - GNU/Linux
3. Compiled from source

### Solution
In line 667 of `RootMacros.cmake` add following lines:

```
target_compile_features(${dictionary} PRIVATE
        $<TARGET_PROPERTY:${ARG_MODULE},COMPILE_FEATURES>)
```

See also https://root-forum.cern.ch/t/rootmacros-cmake-should-also-support-target-features-for-dictionary/42159

**Comment by rlalik** [comment]
Can I do anything to speed up this bugfix? Like merge request? I still have some projects which suffer from this problem and require manual patching after each root fresh installation/upgrade.

**Comment by eguiraud** [comment]
@rlalik sorry for the late reply, was ROOT compiled with `CMAKE_CXX_STANDARD=17`? Downstream applications are expected to use the same C++ standard than ROOT was compiled with (for interpreter-related reasons).

@oshadura what do you think?

**Comment by rlalik** [comment]
> @rlalik sorry for the late reply, was ROOT compiled with `CMAKE_CXX_STANDARD=17`? Downstream applications are expected to use the same C++ standard than ROOT was compiled with (for interpreter-related reasons).

@eguiraud  Exactly, but and this is what happens for all source files, but the dictionary (`G__XXX_cc.cxx` file) is not compiled with the same standard like the ROOT due to missing these files. And then takes compiler either default flags, or (perhaps, would need to check) the one specified with `CMAKE_CXX_FLAGS`. Which might be different, or by chance the same and you will not notice it.

**Comment by oshadura** [comment]
@rlalik sorry for such late reply... (I think I just lost it in my to-do list). I think your fix totally make sense for me (cc: @vgvassilev ) Could you please open PR with the proposed changes, we could see if the test suite will be 'green'?
