### ISSUE TITLE
rootbrowse is not tested

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#6785]
### Explain what you would like to see improved

`rootbrowse` [was broken](https://sft.its.cern.ch/jira/browse/ROOT-10774) by the upgrade to the new PyROOT but as we do not test it we never noticed.

(I am not sure how to test that the GUI starts and works correctly though)

**Comment by guitargeek** [comment]
I don't think we need an open issue for everything that is not tested. And is coming up with a way to test the GUI launch from PyROOT worth it?

**Comment by dpiparo** [comment]
I agree with @guitargeek
