### ISSUE TITLE
TCling::UpdateListOfLoadedSharedLibraries() Linux thread safety

### ISSUE THREAD

**Issue by dan131riley** [root-project/root#6797]
- [x] Checked for duplicates

`TCling::UpdateListOfLoadedSharedLibraries()` iterates through the linked list of dynamic libraries maintained by glibc and saves a pointer into the middle of the list:

https://github.com/root-project/root/blob/49c45b3291c71ffc7f603ae4267f112fdaf77ac4/core/metacling/src/TCling.cxx#L3285-L3290

This is a linked list that can be modified by the activity of other threads, so access to it needs to be protected by a glibc internal `dl_load_write_lock`.  glibc provides an interface for this purpose, `dl_iterate_phdr(3)`:

https://linux.die.net/man/3/dl_iterate_phdr

which should be used instead of iterating through the list without the appropriate locking.

This bug is not trivial to reproduce, but is believed to be responsible for crashes observed in CMS relval tests https://github.com/cms-sw/cmssw/issues/30359

**Comment by Axel-Naumann** [comment]
@dan131riley could you confirm that the PR fixes it?

**Comment by Axel-Naumann** [comment]
Fixed, thanks for the confirmation!
