### ISSUE TITLE
Bug displaying several 3D objects such as TGraph2D on the same canvas 

### ISSUE THREAD

**Issue by romainbqt** [root-project/root#6811]
Hello, 

When displaying several 3D objects the same canvas there is a problem, 
it was reported in old versions of ROOT 
https://root-forum.cern.ch/t/multiple-tgraph2d-in-a-single-plot/7409
and seems to be still there in the most recent versions.

From my understanding, when two 3D objects do not have the same range hence axis when displaying them on the same canvas ROOT does not adapt them. 
Below is an example of something going wrong, I plot the parabola `x^2 + y^2` and as you can see on the plot the parabola takes negative values which is not possible. 

<img width="400" alt="frame_parabola" src="https://user-images.githubusercontent.com/29270790/99190276-e9a4bd80-2765-11eb-97e5-016d018dd6c6.png">

This wrong display is because I plotted the TGraph2D on top of a frame with `z` values going from -10 to 10. 
But same would happen displaying two TGraph2D with different range I think as reported in the root forum. 

Below is the code to reproduce the error, I execute it doing `root -l test_tgraph2d.cpp+`
```C++
#include "TStyle.h" 
#include "TH1.h"
#include "TH2.h"
#include "TH3F.h" 

#include "TGraph.h" 
#include "TGraph2D.h" 
#include "TCanvas.h" 
#include "TView3D.h"
#include "TAxis3D.h" 

#include<iostream> 
#include<vector> 

double f( const double & x, const double & y)
{
  //return 1/(1+std::exp(-x)) * 1/(1+std::exp(-y)) ; 

  return x*x + y*y ; 
}

std::vector<double> linspace(
  const double         & vmin   , 
  const double         & vmax   , 
  const unsigned int   & npoints)
{
  // regular linspace 
  double dx = (vmax - vmin)/double(npoints-1.) ; 
  std::vector<double> vlinspace = {} ; 
  for (unsigned int i = 0 ; i < npoints ; i++)
  {
    vlinspace.push_back( vmin + double(i) * dx ) ; 
  }

  return vlinspace ;
}


void test_tgraph2d()
{
  std::vector<double> 
    vect_x , 
    vect_y ;

  vect_x = linspace(0.,10,100) ; 
  vect_y = linspace(0.,10,100) ; 

  // nominal 
  TGraph2D * gr = new TGraph2D( vect_x.size() * vect_y.size() ) ; 
  gr->SetDirectory(0) ; 

  unsigned int iPoints= 0 ; 
  double x,y,z ; 
  for (unsigned int iX = 0 ; iX < vect_x.size() ; iX++)
  { 
    for (unsigned int iY = 0 ; iY < vect_y.size() ; iY++)
    { 
      x = vect_x[iX] ; 
      y = vect_y[iY] ; 
      z = f(x,y) ; 

      gr->SetPoint(iPoints, x, y, z) ; 
      iPoints +=1 ; 
    }
  }  

  double 
    xmin = 0.      ,
    xmax = 11.     , 
    ymin = 0.      , 
    ymax = 11.     , 
    zmin = -10.    , 
    zmax = 10.     ; 

  gStyle->SetOptStat(0);
  TH3F *frame3d = new TH3F("frame3d","frame3d",1,xmin,xmax,1,ymin,ymax,1,zmin,zmax);  
  frame3d->Draw();

  gr->Draw("surf same" ) ; 
}
```

Many thanks in advance for fixing this problem, 
Best regards, 
Romain Bouquet

**Comment by couet** [comment]
Yes the 3D objects can be superposed correctly only when they have the same range ("SAME" option).
This is a known feature. We can try to think of some solutions.

**Comment by romainbqt** [comment]
Hello @couet, 
If it is possible to find a solution it would be a really nice and very useful improvement!    
Thanks a lot in advance,

**Comment by couet** [comment]
I am not sure yet what the behaviour should be. But we can try.

**Comment by couet** [comment]
Sorry for the very long delay. I do not have a patch yet in ROOT itself but a small prototype implemented in your macro:
```
double f( const double & x, const double & y)
{
   return x*x + y*y ;
}

std::vector<double> linspace(
  const double         & vmin   ,
  const double         & vmax   ,
  const unsigned int   & npoints)
{
  // regular linspace
  double dx = (vmax - vmin)/double(npoints-1.) ;
  std::vector<double> vlinspace = {} ;
  for (unsigned int i = 0 ; i < npoints ; i++)
  {
    vlinspace.push_back( vmin + double(i) * dx ) ;
  }

  return vlinspace ;
}

void DrawSame(TGraph2D *g)
{
   gPad->Update();
   TView *view = gPad->GetView();
   if (view) {
      Double_t *rmin = view->GetRmin();
      Double_t *rmax = view->GetRmax();
      g->SetMaximum(rmax[2]);
      g->SetMinimum(rmin[2]);
      g->GetXaxis()->SetRangeUser(rmin[0],rmax[0]);
      g->GetYaxis()->SetRangeUser(rmin[1],rmax[1]);
      g->Draw("P0 same" ) ;
   }
}

void test_tgraph2d()
{
  std::vector<double>
    vect_x ,
    vect_y ;

  vect_x = linspace(0.,10,100) ;
  vect_y = linspace(0.,10,100) ;

  // nominal
  TGraph2D * gr = new TGraph2D( vect_x.size() * vect_y.size() ) ;
  gr->SetDirectory(0) ;

  unsigned int iPoints= 0 ;
  double x,y,z ;
  for (unsigned int iX = 0 ; iX < vect_x.size() ; iX++)
  {
    for (unsigned int iY = 0 ; iY < vect_y.size() ; iY++)
    {
      x = vect_x[iX] ;
      y = vect_y[iY] ;
      z = f(x,y) ;

      gr->SetPoint(iPoints, x, y, z) ;
      iPoints +=1 ;
    }
  }

  double
    xmin = 0.      ,
    xmax = 8.     ,
    ymin = 0.      ,
    ymax = 4.     ,
    zmin = -10.    ,
    zmax = 10.     ;

  gStyle->SetOptStat(0);
  TH3F *frame3d = new TH3F("frame3d","frame3d",1,xmin,xmax,1,ymin,ymax,1,zmin,zmax);
  frame3d->Draw();

  DrawSame(gr);
}
``` 
Instead of drawing the 2D graph with option `same` this new version uses the function `DrawSame` which changes the TGraph2D axis limits to be the same as the current 3D plot (current TView). It gives the following picture. If that answer your question we can consider to put it in TGraph2DPainter.

<img width="679" alt="Screenshot 2021-07-30 at 11 01 31" src="https://user-images.githubusercontent.com/4697738/127629318-75a9f14b-33a7-4f52-8c1a-45e9b58263fc.png">

**Comment by romainbqt** [comment]
HI @couet, 
Sorry for the late reply, 
many thanks this looks good to me   
and yes if it could be added to ROOT `TGraph2DPainter` 
it would be amazing

**Comment by dpiparo** [comment]
Hi @couet what is the status of this issue?

**Comment by couet** [comment]
I do not see it implemented in `TGraph2DPainter`. I must say I dunno why. Maybe it was not possible at the end, or maybe it was just forgotten because of other matters showing up. I can have a look and implement it (or not in `TGraph2DPainter`).

**Comment by romainbqt** [comment]
Hi @couet,   
Many thanks for having provided a fix to this issue,   
Best,    
Romain Bouquet

**Comment by couet** [comment]
Sure ! ... after all that sorry... sorry for the long delay ...

**Comment by romainbqt** [comment]
No problem I'm sure it will be useful in the future to many persons! :)

**Comment by couet** [comment]
PR merged.
