### ISSUE TITLE
Problems with parsing VS 16.8 headers

### ISSUE THREAD

**Issue by andriish** [root-project/root#6820]
### Describe the bug
It looks like ROOT/Clang is not able to parse the VS headers from the recent 16.8.
It emits multiple errors about undefined symbols.

### Expected behavior
Dictionaries are generated.

### To Reproduce
Try to generate a dictionary using VS 16.8 

### Setup
ROOT 6.22 zip tarbal for Win32 from the ROOT site
Windows10

### Additional context
Not sure that this is the largest problem on Windows.
Also, the same dictionaries work fine with  VS 16.7.5 when I set extra flags 
-D_HAS_CONDITIONAL_EXPLICIT=0 -D__CUDACC__ for the dictionary generation.

**Comment by bellenot** [comment]
We are aware of this issue. There is nothing we can do about it, only hoping that the llvm upgrade will fix the issue...

**Comment by andriish** [comment]
Hi @bellenot ,

> We are aware of this issue. 

you mean  general problems with VS or problems with this specific version? Asking while 16.8 is quite recent, e.g. github has 16.7 on runners. And 16.7 can be tweaked to produce the dictionaries.  So these could be separate issues.

>only hoping that the llvm upgrade will fix the issue...

In my opinion VS and llvm separately are not nice things to deal with and their combination should not be easier to handle.
That is outside of scope of this issue, but maybe one can try to look at some alternatives to VS.  NVIDIA/PGI could be a good candidate once it is released in the free HPC suite for Windows as they promise. But I don't know how do they organize their headers on Windows and how much VS machinery they use. Someone with more experience should evaluate this idea.

**Comment by bellenot** [comment]
> you mean general problems with VS or problems with this specific version?

I mean these specific versions (v16.8.0 and v16.8.1). I saw the problem the day they released it

> In my opinion VS and llvm separately are not nice things to deal with and their combination should not be easier to handle.
> That is outside of scope of this issue, but maybe one can try to look at some alternatives to VS. NVIDIA/PGI could be a good candidate once it is released in the free HPC suite for Windows as they promise. But I don't know how do they organize their headers on Windows and how much VS machinery they use. Someone with more experience should evaluate this idea.

I'll keep the VS option, and don't want to spend time trying all possible alternatives out there (I did it in the past and don't want to waste my time anymore). Most people use Visual Studio on Windows

**Comment by andriish** [comment]
Hi @bellenot, 

>  these specific versions

Then, if you are aware of it, does it makes sense to keep the issue open?
If you think not, either of us can close it.

Thanks a lot,

Andrii

**Comment by bellenot** [comment]
Hi @andriish, no problem to keep it open, at least until we upgrade llvm.

**Comment by andriish** [comment]
Today github  updated VS and now the default compiler is  'MSVC 19.28.29333.0', which has this problem.

**Comment by bellenot** [comment]
How is this relevant to us?

**Comment by andriish** [comment]
Hi @bellenot ,

sorry if that looks like noise. This is technically irrelevant, of course.  The update would just mean that anyone using github CI to build dictionaries will see this problem. So there might be more affected people.

Best regards,

Andrii

**Comment by bellenot** [comment]
OK, I see, this is obviously an issue, like for people (like me) who update their version of Visual Studio every time there is a new release... (but now I do that on a dedicated VM to prevent this kind of "deadlock")

**Comment by bellenot** [comment]
OK, latest version of Visual Studio (v16.10.0) is broken again, and this will not be the last time. I close this issue since it is not up to date anyway (the failures are different at each VS update...)

**Comment by andriish** [comment]
I know. Makes sense. Thanks.
