### ISSUE TITLE
TH2D saving bug

### ISSUE THREAD

**Issue by LongLI-SDU** [root-project/root#6822]
Hello everyone,
I met a bug for histogram saving. I create a TH2D Drawing with ("COLZ2"), When I try to save the histogram as *.pdf or *.eps, the color in the bin disappears. My root version is 6.18/04, the bug remains in 6.22/02. When I try it in ROOT 5.34, the pdf file of hist is ok.
[DC.pdf](https://github.com/root-project/root/files/5550941/DC.pdf)

**Comment by linev** [comment]
Yes, I can confirm a problem. At the same time "colz" works properly.

**Comment by LongLI-SDU** [comment]
OK, I tried in "colz", it woks!

**Comment by linev** [comment]
> OK, I tried in "colz", it woks!

It is not fully ok, "colz2" have to work too.

**Comment by couet** [comment]
Col2 option is a bitmap Representation of the histogram to make the col option very fast when the histogram has many bins and the bin size is close to one pixel. But this bitmap graphics and ps and pdf are vector graphics. So col2 produces an empty plot. This is not a bug. This feature is explained in the THistPainter reference guide (look at it) in the COL Option section.

**Comment by LongLI-SDU** [comment]
Yeah, I found it in the guide. Thanks a lot




Best Regards，
             Long LI
--------------------------------------------------------------------------
Institute of Frontier and Interdisciplinary Science, Shandong University


Addr：NO.72 Binhaidadao,Jimo,Qindao,PRC
E-mail: longli@mail.sdu.edu.cn
Tel: +86 13176405608 
 





On 11/17/2020 16:28，Olivier Couet<notifications@github.com> wrote：


Col2 option is a bitmap Representation of the histogram to make the col option very fast when the histogram has many bins and the bin size is close to one pixel. But this bitmap graphics and ps and pdf are vector graphics. So col2 produces an empty plot. This is not a bug. This feature is explained in the THistPainter reference guide (look at it) in the COL Option section.

**Comment by linev** [comment]
Olivier, can one just automatically switch to col option when doing batch output with `gVirtualPS`? 
Just to avoid confusion in the future?

**Comment by couet** [comment]
That was already discussed many time in the past. The problem is that doing that de pdf and ps  files generated will be super huge and people will not realize it if they are running in batch. Some people had disk saturated. Col2 was explicitly created for that. So if we do what we suggest we do exactly what we wanted to avoid. All that is explained in de reference guide

**Comment by linev** [comment]
Ok, I see.
