### ISSUE TITLE
Visual Studio error C2026 with dictionaries.

### ISSUE THREAD

**Issue by andriish** [root-project/root#6824]
### Describe the bug
Cling produces in the dictionary files code like this:

```
static const char* fwdDeclCode = R"DICTFWDDCLS(
#line 1 
```
Which is invalid for VS if the string is longer than ~16000 characters.
In these cases either the C2026 is issued 
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2026?view=msvc-160
or, much worse, the code is silently truncated and then the compiled executables crash in runtime on code parsing.

### Expected behavior
Cling should take into account this limitation in VS.

### To Reproduce
Generate relatively large dictionary or, optionally manually increase the size of string literal in a small generated dictionary.

Sorry that I don't provide a reproducer. My primary goal was to avoid this behavior when I saw it and not to debug it.

### Setup
1. ROOT 6.22, VS 16.8? ( not sure actually, I've tried many builds, some worked, other didn't)
2. Windows
3. Official site.

### Additional context
One can try to use an array of char* like that is done `classesHeaders[]`  for the  and add `TROOT::RegisterModule()`` that would accept it. But I cannot submit a PR. Sorry.

**Comment by bellenot** [comment]
We are aware of such kind of issue, but we will have hard time trying to fix all Windows/VS limitations... I'll keep it in my list anyway

**Comment by dpiparo** [comment]
I propose to close this issue because:
1. This is a string containing the fwd declarations of the selected classes in a dictionary. The limit of 16k chars is very high
2. In case it's encountered, one can always split the dictionary in 2 dictionaries
3. It's a limitation of VS not of ROOT.

@bellenot

**Comment by dpiparo** [comment]
Assuming the proposal is accepted. Please do not hesitate to re-open in case I am wrong.
