### ISSUE TITLE
build/unix/compiledata.sh assumes macOS will always have major version 10

### ISSUE THREAD

**Issue by ktf** [root-project/root#6838]
While on Big Sur it returns 11, unless `export SYSTEM_VERSION_COMPAT=1`.

**Comment by Axel-Naumann** [comment]
O but that's fixed since ages - Oct 30, https://github.com/root-project/root/commit/132b72c2000b9f942cc77b5cddec4e9c7161f836 ;-)

I am planning on backporting this to 6.22, see https://github.com/root-project/root/pull/6849

OK to close?

**Comment by ktf** [comment]
yes

--
Ciao,
Giulio
