### ISSUE TITLE
Compilation fails on macosx 11.0 with arm processor

### ISSUE THREAD

**Issue by fuhlig1** [root-project/root#6839]
- [ x] Checked for duplicates

### Describe the bug

when trying to compile ROOT on the new arm64 platform of Apple I get the following error when running rootcling

[ 44%] Generating G__Core.cxx, ../lib/libCore.rootmap
error: unknown target triple 'unknown-apple-macosx10.16.0', please use -triple or -arch
Could not determine compiler target.
Compiler instance could not be created.
0  rootcling_stage1         0x000000010439eb84 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 52
1  rootcling_stage1         0x000000010439f0dc SignalHandler(int) + 460
2  libsystem_platform.dylib 0x00000001974abc64 _sigtramp + 56
3  rootcling_stage1         0x0000000102803048 RootClingMain(int, char**, bool) + 14852
4  rootcling_stage1         0x0000000102810a00 ROOT_rootcling_Driver + 392
5  rootcling_stage1         0x00000001027a18bc main + 76
6  libdyld.dylib            0x00000001975a1418 start + 4
Stack dump:
0.	Program arguments: /opt/fairsoft/source/nov20/build/Build/root/core/rootcling_stage1/src/rootcling_stage1 -v2 -f G__Core.cxx -s /opt/fairsoft/source/nov20/build/Build/root/lib/libCore.so -excludePath /opt/fairsoft/source/nov20/build/Source/root -excludePath /opt/fairsoft/source/nov20/build/Build/root -rml libCore.so -rmf /opt/fairsoft/source/nov20/build/Build/root/lib/libCore.rootmap -I/opt/fairsoft/source/nov20/build/Source/root -I/opt/fairsoft/source/nov20/build/Build/root/etc/cling/ -I/opt/fairsoft/source/nov20/build/Build/root/include -I/opt/fairsoft/nov20/include -I/opt/local/include -I/opt/fairsoft/source/nov20/build/Source/root/core/base/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/base/v7/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/clib/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/cont/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/foundation/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/macosx/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/unix/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/winnt/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/clingutils/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/meta/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/gui/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/textinput/inc -I/opt/fairsoft/source/nov20/build/Source/root/core -I/opt/fairsoft/nov20/include -I/opt/local/include -I/opt/fairsoft/source/nov20/build/Source/root/core/base/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/base/v7/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/clib/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/cont/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/foundation/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/macosx/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/unix/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/winnt/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/clingutils/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/meta/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/gui/inc -I/opt/fairsoft/source/nov20/build/Source/root/core/textinput/inc -I/opt/fairsoft/source/nov20/build/Build/root/include -I/opt/fairsoft/source/nov20/build/Source/root -I/opt/local/include -I/opt/fairsoft/source/nov20/build/Source/root/builtins/xxhash -I/opt/local/include -I/opt/local/include -writeEmptyRootPCM ROOT/StringConv.hxx ROOT/TExecutor.hxx ROOT/TSequentialExecutor.hxx Buttons.h Bytes.h Byteswap.h KeySymbols.h MessageTypes.h Riostream.h Rtypes.h TApplication.h TAtt3D.h TAttAxis.h TAttBBox2D.h TAttBBox.h TAttFill.h TAttLine.h TAttMarker.h TAttPad.h TAttText.h TBase64.h TBenchmark.h TBuffer3D.h TBuffer3DTypes.h TBuffer.h TColor.h TColorGradient.h TDatime.h TDirectory.h TEnv.h TError.h TException.h TExec.h TFileCollection.h TFileInfo.h TFolder.h TInetAddress.h TMacro.h TMathBase.h TMD5.h TMemberInspector.h TMessageHandler.h TNamed.h TNotifyLink.h TObject.h TObjString.h TParameter.h TPluginManager.h TPoint.h TPRegexp.h TProcessID.h TProcessUUID.h TQClass.h TQCommand.h TQConnection.h TQObject.h TRedirectOutputGuard.h TRefCnt.h TRef.h TRegexp.h TRemoteObject.h TROOT.h TRootIOCtor.h TStopwatch.h TStorage.h TString.h TStringLong.h TStyle.h TSysEvtHandler.h TSystemDirectory.h TSystemFile.h TSystem.h TTask.h TThreadSlots.h TTime.h TTimer.h TTimeStamp.h TUri.h TUrl.h TUUID.h TVersionCheck.h TVirtualAuth.h TVirtualFFT.h TVirtualGL.h TVirtualMonitoring.h TVirtualMutex.h TVirtualPadEditor.h TVirtualPad.h TVirtualPadPainter.h TVirtualPerfStats.h TVirtualPS.h TVirtualQConnection.h TVirtualRWMutex.h TVirtualTableInterface.h TVirtualViewer3D.h TVirtualX.h ROOT/RLogger.hxx ROOT/RDirectoryEntry.hxx ROOT/RIndexIter.hxx strlcpy.h snprintf.h ROOT/TSeq.hxx TArrayC.h TArrayD.h TArrayF.h TArray.h TArrayI.h TArrayL64.h TArrayL.h TArrayS.h TBits.h TBtree.h TClassTable.h TClonesArray.h TCollection.h TCollectionProxyInfo.h TExMap.h THashList.h THashTable.h TIterator.h TList.h TMap.h TObjArray.h TObjectTable.h TOrdCollection.h TRefArray.h TRefTable.h TSeqCollection.h TSortedList.h TVirtualCollectionProxy.h ESTLType.h RStringView.h TClassEdit.h ROOT/RIntegerSequence.hxx ROOT/RMakeUnique.hxx ROOT/RNotFn.hxx ROOT/RSpan.hxx ROOT/RStringView.hxx ROOT/span.hxx ROOT/TypeTraits.hxx TMacOSXSystem.h TUnixSystem.h root_std_complex.h TClingRuntime.h GuiTypes.h TApplicationImp.h TBrowser.h TBrowserImp.h TCanvasImp.h TClassMenuItem.h TContextMenu.h TContextMenuImp.h TControlBarImp.h TGuiFactory.h TInspectorImp.h TObjectSpy.h TToggleGroup.h TToggle.h TBaseClass.h TClassGenerator.h TClass.h TClassRef.h TClassStreamer.h TDataMember.h TDataType.h TDictAttributeMap.h TDictionary.h TEnumConstant.h TEnum.h TFileMergeInfo.h TFunction.h TFunctionTemplate.h TGenericClassInfo.h TGlobal.h TInterpreter.h TInterpreterValue.h TIsAProxy.h TListOfDataMembers.h TListOfEnums.h TListOfEnumsWithLock.h TListOfFunctions.h TListOfFunctionTemplates.h TMemberStreamer.h TMethodArg.h TMethodCall.h TMethod.h TProtoClass.h TRealData.h TSchemaHelper.h TSchemaRule.h TSchemaRuleSet.h TStatusBitsChecker.h TStreamerElement.h TStreamer.h TVirtualIsAProxy.h TVirtualRefProxy.h TVirtualStreamerInfo.h TVirtualArray.h TVirtualObject.h Getline.h /opt/fairsoft/source/nov20/build/Source/root/core/base/inc/LinkDef.h 
Segmentation fault
make[2]: *** [core/G__Core.cxx] Error 1
make[1]: *** [core/CMakeFiles/G__Core.dir/all] Error 2
make: *** [all] Error 2

### Expected behavior

Running rootcling-stage1 should find the correct target triple which is arm-apple-darwin20.1.0. This triple is already found by llvm

. interpreter/llvm/src/cmake/config.guess
arm-apple-darwin20.1.0
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

### To Reproduce

Remove the build directory and start with a new compilation

### Setup

1. ROOT version: 6.20.08
2. Operating system: macosx 11.0
3. How you obtained ROOT: git clone from github

**Comment by Axel-Naumann** [comment]
We are not planning to backport Apple Silicon support to 6.20. master works fine; 6.22 will work soon, too, see https://github.com/root-project/root/pull/6849

Please let us know should you see any issues with master - which works for us.
