### ISSUE TITLE
JSON I/O (not object serialisation)

### ISSUE THREAD

**Issue by cholmcc** [root-project/root#6889]
Here is a suggestion for a class to input and output JSON data.   It is _not_ meant for (`T`)object serialisation (there's `TBufferJSON` for that) - but for use cases where one wants to import or export JSON data into ROOT-based code.  Examples could be 

- Input and output of HEPData data.  For example, one may want to read in some table via JSON and visualize, or one has produced a result one wants to upload to HEPData 
- Interoperability with Python.  Python has support for many data format - not least JSON. 

The attached class `TJSON` allows for this in a relatively straight forward manner.  For example, one can do 

```c++
  TJSON null;
  TJSON b(true);
  TJSON s("RawString");
  TJSON s2(std::string("C++String"));
  TJSON i(42);
  TJSON f(3.14);
  TJSON a = TJSON::Array();
  TJSON o = TJSON::Object();
```
for null, boolean, string, numbers (int and float), arrays or objects (associative container). 

A more complex object can be created like 

```c++ 
  TJSON o2 = std::map<std::string,TJSON>{
    {"key1","value"},
    {"key2",true},
    {"key3",
     {"key4", TJSON::Array("This","is","an","array"),
      "key5",
      {"boolean", true}
     }
    }
  };
```

and elements are accessed via `operator[]` 

```c++
assert o2["key1"] == "value";
assert o2["key3"]["key4"][1] == "is"
```

One can loop over arrays or objects via `TJSON::ArrayRange` or `TJSON::ObjectRange` respectively. 

```c++
  TJSON a = TJSON::Array();
  TJSON o = TJSON::Object();

  for (size_t i = 0; i < 4; i++)
    a[i] = "Test"+std::to_string(i);

  o["key0"] = "value1";
  o["key1"] = a;
  o["key2"] = 123;

  std::cout << "Array: " << std::endl;
  for (auto& e : a.ArrayRange())
    std::cout << e << std::endl;

  std::cout << "Object: "  << std::endl;
  for (auto& kv : o.ObjectRange())
    std::cout << "o[" << kv.first << "] = " << kv.second << std::endl;
```

JSON can be read and written to streams 

```c++
 std::cout << "=== Loading ===" << std::endl;
  std::string s("{\"key1\":\"string\","
		" \"key2\": true,"
		" \"key3\":     1234,"
		" \"key4\":null}");

  std::stringstream str(s);

  TJSON j;
  str >> j;
  std::cout << j << std::endl;
  
  TJSON j2 = TJSON::Load(s);
  std::cout << j2 << std::endl;
```

I attach `TJSON.h` and `TJSON.cxx` as well as a script with examples `Example.C`.   Note, objects of the class are clearly not meant to by stored in ROOT files and thus there is no call to the `ClassImp` macro

. 

Feel free to incorporate the code as you see fit. 

Yours, 

Christian
[TJSON.zip](https://github.com/root-project/root/files/5614520/TJSON.zip)

**Comment by linev** [comment]
Hi Christian,

`TBufferJSON` class of ROOT uses https://github.com/nlohmann/json parser for reading of JSON files.
In current ROOT master one can just include "hlohmann/json.hpp" and use all its features directly - also directly from **cling**. I guess, your TJSON class will have very similar functionality, or I missing something?

**Comment by cholmcc** [comment]
Hi Sergey, 

The class `TJSON` is indeed similar to the library of _nlohmann_  except a whole lot more lean (_nlohmann_ is 14,748 lines of code, while `TJSON` is 962 lines of code - as per `sloccount`).  _nhlohmann_ tries to be very general and in fact expands upon the JSON standard, while `TJSON` tries to be as simple as possible. 

Also, for `TJSON` I tried to do a bit of ROOT integration.  For example, one can get arrays as `TArrayD` or `TArrayI` if possible, or one can assign from `TParameter<T>`.   This is simple to make life a little easier for people.  

That said, I have no particular preference for either.  However, you should consider in the build system to use system available installation of _nlohmann_ instead of using built-in copy.  You really don't want different versions of the same code floating around on a given machine. 

Yours,

Christian

**Comment by linev** [comment]
> However, you should consider in the build system to use system available installation of nlohmann instead of using built-in copy. 
> You really don't want different versions of the same code floating around on a given machine.

It is already possible now, but disable by default. 
Use of external `nlohmann/json.hpp` has some side effects on build system, therefore should only be enabled when really needed.

> Also, for TJSON I tried to do a bit of ROOT integration. For example, one can get arrays as TArrayD or TArrayI if possible

Support of special ROOT classes provided with `TBufferJSON`, including support of all ROOT containers. 
Concerning `TArrayD` or `TArrayI` - these are old-fashion ROOT arrays; for new classes one should better use standard containers like `std::vector`, which are supported by `nlohmann/json.hpp` anyway.

Size is important, but nlohmann already parsed by cling and can be used from interpreter without extra costs.

**Comment by linev** [comment]
Closing in favor of using `nlohmann/json.hpp`
