### ISSUE TITLE
Bug in RooSimultaneous::extendMode()

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#6894]
When a simultaneous pdf is composed by a not-extended pdf and an extended pdf, RooSimultaneous::extendMode() returns 
   `MustBeExtended` or ` CanNotBeExtended` depending on the initial category value. 

See example and report on 
https://root-forum.cern.ch/t/use-of-roosimultaneous-pdf-with-mustbeextended-and-cannotbeextended-pdfs/42462

**Comment by lmoneta** [comment]
A related problem is also in RooNLLVar::create  that is called by  RooAbsTestStatistic::initSimMode,
https://root.cern/doc/master/RooAbsTestStatistic_8cxx_source.html#l00500

When the sub-likelihood is created using the component pdf, one should pass the extend flag only if the pdf  canBeExtended()

**Comment by jbdvdr** [comment]
Hello,

In root-6.24, I have the impression that this fix unfortunately seems to imply a crash in evaluate : when there is a non-extendable category and an extendable one in the RooSimultaneous, canBeExtended() will be true, and then expectedEvents will be called also for the non extendable category, and this will make the code crashes, I think. 

Running the macro posted here https://root-forum.cern.ch/t/use-of-roosimultaneous-pdf-with-mustbeextended-and-cannotbeextended-pdfs/42462 within 6.24, I get
RooSimultaneous::fsbBA[ indexCat=catBA A=fsbA B=fsbB ] = [#0] FATAL:Generation -- Requesting expected number of events from a RooProdPdf that does not contain an extended p.d.f
Error in <TRint::HandleTermInput()>: std::logic_error caught: RooProdPdf fsbA could not be extended.

Best,

Jean-Baptiste
