### ISSUE TITLE
libguide.so problem

### ISSUE THREAD

**Issue by jiefeng007** [root-project/root#6904]
- [x] Checked for duplicates

The bug is not reported.

### Describe the bug

When I compile my code using TMVA reader, I got the following message.

ld: warning: libguide.so, needed by /cvmfs/ams.cern.ch/Offline/root/Linux/root6-14-04-icc19/lib/libTMVA.so, not found (try using -rpath or -rpath-link)

Then, I execute my .exe file, and get:
error while loading shared libraries: libguide.so: cannot open shared object file: No such file or directory

### Expected behavior

No warning during compiling. No error when running

### To Reproduce

#include <cstdlib>
#include <iostream>
#include "TString.h"
#include "TTree.h"
#include "TGraph.h"
#include "TFile.h"
#include <TMVA/Reader.h>
#include "TF1.h"
using namespace std;
int main(int argc, char *argv[]){
        int t_i = 19;
        float mu, Delta, Ng, Ec, h, epsilon_c, ng, Gamma, L_M_5;
        TMVA::Reader *reader = new TMVA::Reader("!Color:!Silent");
        reader->AddVariable( "mu", &mu );
        reader->AddVariable( "Delta", &Delta );
        reader->AddVariable( "Ng", &Ng );
        reader->AddVariable( "Ec", &Ec );
        reader->AddVariable( "h", &h );
        reader->AddVariable( "epsilon_c", &epsilon_c );
        reader->AddVariable( "ng", &ng );
        reader->AddVariable( "Gamma", &Gamma );
        reader->AddVariable( "L-5", &L_M_5 );
        reader->BookMVA( "MLP method",  Form("/eos/user/j/jfeng5/work/quantum_computing/mc/tmva/weights/qc_MLP_%d.weights.xml",t_i ));
        TFile tf_fi(Form("/afs/cern.ch/work/j/jfeng/private/quantum_computing/analysis/tmva/regression/t_%d.root",t_i));
        TF1 * tf = (TF1*) tf_fi.Get("tf");
        double var_mean[8] = {-700, 250, 0.1, 100, 400, 6000, 0.1, 0.8};
        mu = -700;
        Delta = 250;
        Ng = 0.1;
        Ec = 100;
        h = 400;
        epsilon_c = 6000;
        ng = 0.1;
        Gamma = 0.8;

double MLP = reader->EvaluateMVA( "MLP method" );
double PI = tf->Eval(MLP);
cout << "MLP = " << MLP << endl;
cout << "PI = " << PI << endl;
        //TFile fo(Form("%10d.root",irun), "recreate");
        //fo.Close();
        return 0;
}

In the MakeFile:

CXX=$(shell root-config --cxx)
ROOTLIB=$(shell root-config --libs --glibs)
ROOTLIB += -lRFIO -lMinuit -lNetx -lGeom -lEG -lXMLIO -lTreePlayer -lMLP -lTMVA -DUSEGENFIT
FLIBS  := -lifcore -static-libgcc -static-libstdc++ -std=c++11

all: generate
generate: 
        $(CXX) generate.C -D__ROOTSHAREDLIBRARY__ -I$(ROOTSYS)/include -I./ $^ -o $@.exe $(ROOTLIB) $(FLIBS) -lMathMore -lCling
dump:
        @echo $(ROOTSYS)
clean: rm *.exe

I run it like:
make;
./generate.exe

### Setup

ROOT version: root6-14-04-icc19
Operating system: cc7 in lxplus7.cern.ch machines
ROOT is at /cvmfs/ams.cern.ch/Offline/root/Linux/root6-14-04-icc19/

**Comment by lmoneta** [comment]
Hi, 
I am not sure this is a bug in ROOT, but it could be some configuration problems on your system or  a problem in root-config. 
 I see you are using a build done with the Intel compiler. If I am not mistaken libguide is a library needed when using the Intel compiler. 
Are you sure you have set up correctly the environment (e.g. LD_LIBRARY_PATH) to use the Intel compiler ? 
What is the output of `root-config --cxx` ? 

Lorenzo

**Comment by Axel-Naumann** [comment]
And do *not* link against `-lCling` please! `-lCore` is enough.

**Comment by jiefeng007** [comment]
If I use -lCore instead of -lCling, I got one more error:

icpc generate.C -D__ROOTSHAREDLIBRARY__ -I/cvmfs/
ams.cern.ch/Offline/root/Linux/root6-14-04-icc19/include -I./  -o
generate.exe -L/cvmfs/ams.cern.ch/Offline/root/Linux/root6-14-04-icc19/lib
-lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTDataFrame
-lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics
-lMathCore -lThread -lMultiProc -pthread -limf -lm -ldl -L/cvmfs/
ams.cern.ch/Offline/root/Linux/root6-14-04-icc19/lib -lGui -lRFIO -lMinuit
-lNetx -lGeom -lEG -lXMLIO -lTreePlayer -lMLP -lTMVA -DUSEGENFIT -lifcore
-static-libgcc -static-libstdc++ -std=c++11 -lMathMore -lCore
ld: warning: libguide.so, needed by /cvmfs/
ams.cern.ch/Offline/root/Linux/root6-14-04-icc19/lib/libTMVA.so, not found
(try using -rpath or -rpath-link)
/cvmfs/ams.cern.ch/Offline/root/Linux/root6-14-04-icc19/lib/libCore.so:
undefined reference to `TCling::TCling(char const*, char const*, char
const* const*)'
make: *** [generate] Error 1

**Comment by jiefeng007** [comment]
The output is as the following:

$ root-config --cxx
icpc

**Comment by Axel-Naumann** [comment]
So there are a couple of issues:
- please use `root-config --libs` and its flags instead of hard-coding lags and libraries. This fixes the issue of `libCore` which should be allowed to have unresolved symbols into `libCling`.
- according to https://community.intel.com/t5/Intel-C-Compiler/libguide-so/m-p/769697/highlight/true#M512 `icpc` needs libguide.so, i.e. you likely did not set up your compiler correctly.

Please let us know whether there's something else we can do.

In the future, please post questions like these at https://root-forum.cern.ch instead of opening a bug report unless you're really sure it's our bug ;-)

**Comment by Axel-Naumann** [comment]
Let us know if there's something to be addressed by us and I'll reopen.
