### ISSUE TITLE
ROOT 6.22 should reject TBB 2021.1.1 and above during configuration (fails to compile)

### ISSUE THREAD

**Issue by amadio** [root-project/root#6933]
The fix for newer TBB versions is in master, but 6.22.06 and below cannot use TBB 2021 and above, so CMake should reject these versions during the configuration phase. The error at compilation is known (usage of deprecated functionality which is dropped in TBB 2021.1.1):
```
root-6.22.06/core/imt/src/TPoolManager.cxx:10:10: fatal error: tbb/task_scheduler_init.h: No such file or directory
 #include "tbb/task_scheduler_init.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by mrodozov** [comment]
@amadio @oshadura could we expect 6-22 and master to be updated for integrating with 2021.1.1 tbb ?

**Comment by oshadura** [comment]
@mrodozov does ROOT master works for you with 2021.1.1? (cc: @xvallspl )

**Comment by xvallspl** [comment]
@mrodozov The deprecated functionality was removed a while ago and the fix will be included in the next release.

**Comment by mrodozov** [comment]
> @mrodozov does ROOT master works for you with 2021.1.1? (cc: @xvallspl )

I started testing it for master just now. I didn't check before asking :D that's because 6.22 is of greater importance

> @mrodozov The deprecated functionality was removed a while ago and the fix will be included in the next release.
> 
> I will bring up backporting it to 6.22

great, we use 6.22 for our main releases

**Comment by Axel-Naumann** [comment]
@mrodozov is this an official CMS request or "just" an issue you discovered personally? (Trying to sort out priorities here...)

**Comment by mrodozov** [comment]
it's official request, we want to integrate TBB 2021.1.1 and the ROOT tag for cmssw master is 6.22.06

**Comment by mrodozov** [comment]
the integration attempt (to build master) failed with 

```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01-725b5e05650d8bf8cd995e6f1f38ca75/root-6.23.01/core/imt/src/RTaskArena.cxx: In constructor 'ROOT::Internal::RTaskArenaWrapper::RTaskArenaWrapper(unsigned int)':
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01-725b5e05650d8bf8cd995e6f1f38ca75/root-6.23.01/core/imt/src/RTaskArena.cxx:70:79: error: reference to 'task_arena' is ambiguous
```

maybe I have to add something to our cmake config ? 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-623c54/12317/lcg/root/6.23.01-725b5e05650d8bf8cd995e6f1f38ca75/log

**Comment by xvallspl** [comment]
that is something I haven't seen yet. I'll take a look :)

**Comment by xvallspl** [comment]
Reading the log, it seems like the moment we feared arrived and tbb::task_arena is not an alias of `tbb::interface7::task_arena` but of `tbb::detail::d1::task_arena`

**Comment by xvallspl** [comment]
@mrodozov I just merged PR https://github.com/root-project/root/pull/7062. Can you build against master again?

**Comment by mrodozov** [comment]
I already did, it is building.

**Comment by mrodozov** [comment]
@xvallspl can we have the TBB 2021 interface backported to 6.22 ?

**Comment by xvallspl** [comment]
Yes, I'll work on it next. I assume then it worked also on your side?

**Comment by mrodozov** [comment]
I didn't tried backporting only the 7062 commit to our 6.22 because I assumed the cmake etc for tbb 2021 is not backported yet from master. I can try if only 7062 is what's needed

**Comment by xvallspl** [comment]
Dealt with in https://github.com/root-project/root/pull/7065
