### ISSUE TITLE
Return pointer to XXX object in DrawXXX methods.

### ISSUE THREAD

**Issue by rafopar** [root-project/root#6966]
Unlike to TLine or TLatex, the DrawArc method of TArc is void, will be good to have it to return the pointer to the drawn object.

This issue is created based on the suggestion of @couet in the root forum
https://root-forum.cern.ch/t/pointer-of-drawing-tarc-object/42778

**Comment by couet** [comment]
Yes, that should be uniformed. I would even be in favour to break the backward compatibility for that as such methods are utilities.

**Comment by couet** [comment]
Fix applied.
