### ISSUE TITLE
 pyROOT doesn't work with ipyparallel

### ISSUE THREAD

**Issue by TatianaOvsiannikova** [root-project/root#6974]
### Describe the bug

ROOT fails inside the ipyparallel.directView.map method.

### Expected behavior

pyRoot should work with ipyparallel  

### To Reproduce

Please find bellow the steps to reproduce the issue:

    source /cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-centos7-gcc8-opt/setup.sh
    ipcluster start -n 3 --daemonize
    ipython test_ipp.py
the gist for test_ipp.py script:
https://gist.github.com/TatianaOvsiannikova/eb8065352b3605cbebf547e7d2465c37

it fails with an error:

NameErrorTraceback (most recent call last)<string> in <module>()
<ipython-input-1-a67452f95d83> in f(x)
/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-centos7-gcc8-opt/lib/ROOT.pyc in <module>()
    823    ip = get_ipython()
    824    if hasattr(ip,"kernel"):
--> 825       import JupyROOT
    826       import JsMVA
    827 
/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-centos7-gcc8-opt/lib/ROOT.pyc in _importhook(name, *args, **kwds)
    520       except Exception:
    521          pass
--> 522    return _orig_ihook( name, *args, **kwds )
    523 
    524 __builtin__.__import__ = _importhook
/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-centos7-gcc8-opt/lib/JupyROOT/__init__.py in <module>()
      1 from JupyROOT.helpers import cppcompleter, utils
      2 
      3 if '__IPYTHON__' in __builtins__ and __IPYTHON__:
----> 4     cppcompleter.load_ipython_extension(get_ipython())
      5     utils.iPythonize()
NameError: name 'get_ipython' is not defined
-->

### Setup

1. ROOT 6.20/02
2. centos 7, lxplus7.cern.ch
3. LCG_97 via cvmfs

**Comment by etejedor** [comment]
Thank you for the report @TatianaOvsiannikova , it looks like it's not finding `get_ipython`, which should be put by IPython in the global scope by default since you are running your code with `ipython` (it seems it's not the case).

Workaround: can you use `python` instead of `ipython`?

I'll check if explicitly importing `get_ipython` solves this.

**Comment by TatianaOvsiannikova** [comment]
Unfortunately this  issue still exist in head version, but now the error appears for JsMVA.py file:

the gist for test_ipp.py script:
https://gist.github.com/TatianaOvsiannikova/eb8065352b3605cbebf547e7d2465c37
now fails with an error:

NameErrorTraceback (most recent call last)<string> in <module>()
/afs/cern.ch/work/t/tovsiann/public/test_multi/ipp.py in f(x)
----> 2     import ROOT # script works, if remove this line
      3     return x
      4 
      5 from ipyparallel import Client
      6 pool = Client()
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python2/Tue/x86_64-centos7-gcc8-opt/lib/ROOT/__init__.pyc in <module>()
     88     if hasattr(ip,"kernel"):
     89         import JupyROOT
---> 90         import JsMVA
     91 
     92 # Register cleanup
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python2/Tue/x86_64-centos7-gcc8-opt/lib/ROOT/_facade.pyc in _importhook(name, *args, **kwds)
    160                 except Exception:
    161                     pass
--> 162             return _orig_ihook(name, *args, **kwds)
    163         __builtin__.__import__ = _importhook
    164 
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python2/Tue/x86_64-centos7-gcc8-opt/lib/JsMVA/__init__.py in <module>()
     10     ip     = get_ipython()
     11     extMgr = ExtensionManager(ip)
     12     extMgr.load_extension("JsMVA.JsMVAMagic")
     13 
---> 14 loadExtensions()
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python2/Tue/x86_64-centos7-gcc8-opt/lib/JsMVA/__init__.py in loadExtensions()
      8 ## This function will register JsMVAMagic class to ipython
      9 def loadExtensions():
---> 10     ip     = get_ipython()
     11     extMgr = ExtensionManager(ip)
     12     extMgr.load_extension("JsMVA.JsMVAMagic")
NameError: global name 'get_ipython' is not defined

**Comment by etejedor** [comment]
Hi @TatianaOvsiannikova thanks for reporting, I made a PR to add the explicit import of `get_ipython` in JsMVA too.

**Comment by etejedor** [comment]
@TatianaOvsiannikova I merged the fix, it should be ok in tomorrow's LCG dev3.

**Comment by TatianaOvsiannikova** [comment]
> @TatianaOvsiannikova I merged the fix, it should be ok in tomorrow's LCG dev3.

Thank you! I'm checking tomorrow.

**Comment by etejedor** [comment]
@TatianaOvsiannikova is all ok now?

**Comment by TatianaOvsiannikova** [comment]
Sorry for the slow response. I've been out of network few days. Now, it seems to work. Thank you again!

**Comment by etejedor** [comment]
Good to hear! Closing this ticket then.
