### ISSUE TITLE
THStack::GetXaxis->SetRange does not auto-zoom Yaxis range

### ISSUE THREAD

**Issue by goi42** [root-project/root#6991]
- [x] Checked for duplicates

### Describe the bug

If I call `TH1::GetXaxis()->SetRange`, the Yaxis range automatically adjusts to zoom in on the selected bins. For `THStack::GetXaxis()->SetRange`, however, this is not the case–the Yaxis retains the same range it had before.

Originally reported in the [forum](https://root-forum.cern.ch/t/yaxis-range-does-not-adjust-when-zooming-xaxis-of-thstack/42953?u=mwilkins).

### Expected behavior

`THStack::GetXaxis()->SetRange` should result in a re-zoom of the Yaxis so that the bins in-range are visible.

### To Reproduce

See [forum](https://root-forum.cern.ch/t/yaxis-range-does-not-adjust-when-zooming-xaxis-of-thstack/42953?u=mwilkins).
```python
import ROOT as r
h1 = r.TH1F("h1", "h1", 100, 0, 100)
for i in range(int(1e6)):
    h1.Fill(r.gRandom.Gaus(20, 5))
c = r.TCanvas()
h1.Draw()  # full range shown
h1.GetXaxis().SetRange(1, 6)
c.Update()  # Yaxis zooms in to show content in bins 1 to 6
h2 = r.TH1F("h2", "h2", 100, 0, 100)
for i in range(10):
    h2.Fill(r.gRandom.Gaus(9, 5))
hs = r.THStack()
hs.Add(h1)
hs.Add(h2)
hs.Draw()  # note Yaxis range
hs.GetXaxis().SetRange(1, 6)
c.Update()  # Yaxis range has not changed, making it difficult to see the bins
```

### Setup

_ROOT Version_: 6.22/06
_Platform_: macOS
_Compiler_: conda-forge

**Comment by couet** [comment]
As said in the forum, this can be reproduced doing a simple zoom on the X axis of a THStack plot.

**Comment by couet** [comment]
```
{
   auto h1 = new TH1F("h1", "h1", 100, 0, 100);
   for (int i=0; i<1e6; i++) h1->Fill(gRandom->Gaus(20, 5));
   auto c = new TCanvas();
   c->Divide(2,1);
   c->cd(1); h1->Draw();  // full range shown;
   h1->GetXaxis()->SetRange(1, 6);
   c->Update();   // Yaxis zooms in to show content in bins 1 to 6;
   auto h2 = new TH1F("h2", "h2", 100, 0, 100);
   for (int i=0; i<10; i++) h2->Fill(gRandom->Gaus(9, 5));
   auto hs = new THStack();
   hs->Add(h1);
   hs->Add(h2);
   c->cd(2); hs->Draw(); // note Yaxis range;
   hs->GetXaxis()->SetRange(1, 6);
}
```
