### ISSUE TITLE
Fill attribute is not fully reflected in THStack

### ISSUE THREAD

**Issue by akira-okumura** [root-project/root#6997]
```
root [0] auto h1 = new TH1D("h1", "h1", 50, -5, 5)
root [1] auto h2 = new TH1D("h2", "h2", 50, -5, 5)
root [2] h1->FillRandom("gaus")
root [3] h2->FillRandom("gaus")
root [4] auto hstack = new THStack("hstack", "")
root [5] hstack->Add(h1)
root [6] hstack->Add(h2)
root [7] h1->SetFillStyle(0)
root [8] h2->SetFillStyle(0)
root [9] hstack->Draw("c")
root [10] gPad->SetGrid()
```

The above code draws correct h1 and h2 distributions, but the fill attribute 0 is not fully reflected in the canvas.

![image](https://user-images.githubusercontent.com/2981330/103875205-7d1abf00-5115-11eb-9359-afb7cde03e73.jpeg)

Please also see this thread in the ROOT forum.
https://root-forum.cern.ch/t/fill-attribute-is-not-fully-reflected-in-thstack/42987

**Comment by couet** [comment]
Thanks. Here is the code re-formatted (easier to copy/paste in a macro)

```
{
   auto h1 = new TH1D("h1", "h1", 50, -5, 5);
   auto h2 = new TH1D("h2", "h2", 50, -5, 5);
   h1->FillRandom("gaus");
   h2->FillRandom("gaus");
   auto hstack = new THStack("hstack", "");
   hstack->Add(h1);
   hstack->Add(h2);
   h1->SetFillStyle(0);
   h2->SetFillStyle(0);
   hstack->Draw("c");
   gPad->SetGrid();
}
```

**Comment by couet** [comment]
Actually this behaviour is documented [here](https://root.cern/doc/master/classTHStack.html#a6294f58bebce2f1ce5d6dced8e22bc1e). One should use the option "noclear" . May be the painting option should be made more visible at the top of the THStack class. Just do:

```
   hstack->Draw("c noclear");
```

**Comment by couet** [comment]
THStack documentation has been clarified.

**Comment by akira-okumura** [comment]
Thank you Olivier. I did not expect that THStack had drawing options in addition to those for TH1.

I do not understand why the "noclear" option is needed. 

> If the patterns used to draw the histograms in the stack are transparents, then the plot behind will be visible.

Always enabling "noclear" will not change the behaviors of all use cases, I guess.
