### ISSUE TITLE
fifo in $CWD causes TCanvas to hang on macOS

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7010]
### Describe the bug

See https://root-forum.cern.ch/t/root-hangs-when-creating-tcanvas/42827/3

### Additional context

Tried on Linux; no problem there.

**Comment by nlurkin** [comment]
Thank you, but actually the problem was originally spotted on linux (Ubuntu 20.04) with ROOT6.22/00

**Comment by Axel-Naumann** [comment]
Humm. I cannot reproduce it on Linux then. Can you give the actual command you use to create the FIFO?

**Comment by nlurkin** [comment]
I created the fifo with 
```
mkfifo myfifo
```
Then 
```
root -l 
root [0] new TCanvas()
```
never returns.

**Comment by AdvaitDhingra** [comment]
> root [0] new TCanvas()
Isn't it 

```diff
- root [0] new TCanvas()
+ root [1] new TCanvas
```

Or am I mistaken?

**Comment by Axel-Naumann** [comment]
Doesn't matter, just like `new std::string` vs `new std::string`.

**Comment by AdvaitDhingra** [comment]
> Doesn't matter, just like `new std::string` vs `new std::string()`.

Ah ok, got it

**Comment by Axel-Naumann** [comment]
Reproducer:
```
cd
mkfifo TEST
tail +1f /var/log/syslog >> TEST
```
and let it sit. Then, in a different terminal:
```
cd
root
root [0] TH1F h;
```
and it hangs. PR coming up.
