### ISSUE TITLE
Memory leak during schema evolution of some classes

### ISSUE THREAD

**Issue by knoepfel** [root-project/root#7016]
### Describe the bug

The DUNE experiment ran into a situation where instances of class `recob::Track` were written to disk with version 13, but were read with a dictionary whose class version was 17.  Although an I/O rule was written, it appears to not have been applied, possibly because version 13 was not specified in selection XML file.  Philippe would know the exact reason.

Significant memory growth was observed, and Philippe confirmed that a memory leak is encountered.

### Reproduction and setup

Philippe already has the appropriate setup instructions for diagnosing this error.  This bug report was opened at his request.

**Comment by pcanal** [comment]
Indeed, not listing class version 13 in the rule means it would not be applied.

**Comment by pcanal** [comment]
The leak is related to the handling of conversion from unversioned class from MathCore (namely from ```ROOT::Math::Cartesian3D<double>``` to ```ROOT::Math::Cartesian3D<Double32_t>``` and ```"ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::GlobalCoordinateSystemTag>"```` to ```"ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::GlobalCoordinateSystemTag>"```

In some circumstances (involving which StreamerInfo was recorded in an acceleration structure/cache), TClass was not remembering that it already created the Conversion StreamerInfo from one to the other and recreating from each object read.

**Comment by knoepfel** [comment]
At the very least, it sounds like the LArSoft dictionary should be fixed to enable the I/O rule to be applied.

**Comment by pcanal** [comment]
Indeed.  Given the current understanding, fixing the rule (even-though it is necessary for LArSoft to read the data properly) should not prevent the memory leak.

**Comment by knoepfel** [comment]
@pcanal, it appears my understanding of the file was incorrect.  The on-disk version of the class in the file was 15, which is specified in the XML file.  However, the XML file looks like:

```.xml
  <class name="recob::Track" ClassVersion="17">
   <version ClassVersion="17" checksum="738708267"/>
   <version ClassVersion="16" checksum="1293628079"/>
   <version ClassVersion="15" checksum="2420564911"/>
   <version ClassVersion="14" checksum="2345363916"/>
  </class>
  ...
  <ioread
    version="[-14]" ...>
  ...
  </ioread>
```
Am I correct that because no version older than 14 is specified in the version list, the IO rule can be changed to:

```.diff
  <ioread
-  version="[-14]
+  version="[14]"
   ...
```

**Comment by pcanal** [comment]
I will need to investigate further why the rule was (apparently) not run in the example we had since it is unrelated to the memory growth I discovered.

**Comment by pcanal** [comment]
> Am I correct that because no version older than 14 is specified in the version list, the IO rule can be changed to:

yes, but it also should have no practical effect :)

> The on-disk version of the class in the file was 15, which is specified in the XML file. However, the XML file looks like:

Indeed, that is what I see also.  So it is the expected/intended behavior that the rule is not called :)

**Comment by knoepfel** [comment]
Yes.  Thanks Philippe, and sorry for steering you in the wrong direction with the dictionary issue.
