### ISSUE TITLE
cling depends on exact macOS SDK headers

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7021]
### Describe the bug

See e.g. https://root-forum.cern.ch/t/homebrew-and-latest-macos-sdk/43049:

```
warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk'
```
despite 11.1 being there

### Expected behavior
Picks up 11.1 SDK.

Possibly use generic MacOSX.sdk directory instead.

### To Reproduce
Download binaries built with 11.0 SDK while you have a newer Xcode / cmd line tools.

**Comment by Axel-Naumann** [comment]
https://root-forum.cern.ch/t/binary-installation-of-root-with-macos-11-1/43359/9

**Comment by eguiraud** [comment]
https://root-forum.cern.ch/t/segmentation-violation-on-big-sur-11-2-3/43950
