### ISSUE TITLE
[RF] Runtime optimisations in RooFit

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#7032]
### Explain what you would like to see improved
List of things that can be vectorised / speeded up in RooFit.

- [x] Vectorise https://github.com/root-project/root/blob/bd6bb9f6f62f08eba591edfc7e25b8f45857a562/roofit/roofitcore/src/RooAbsPdf.cxx#L373-L378
- [x] Same for computing logarithms in same class (getLogProbabilities())
- [x] RooNLLVar::computeBatched()
- [x] Investigate if norm and logs can be contracted.

- [ ] Generation of events. Unless specialised generator functions are implemented, RooFit employs accept/reject sampling. Since this has to evaluate the PDF many times, one could think about using the batch interface to generate e.g. 2x the requested number of events, and do accept/reject on those. Repeat until enough events have been generated, and throw away the rest.

**Comment by guitargeek** [comment]
Hi @hageboeck, thanks for opening this issue! I investigated the first item (vectorization of normalization in RooAbsPdf), and according to the compiler (`-fopt-info-vec-optimized`) it is already vectorized:
```
roofit/roofitcore/src/RooAbsPdf.cxx:375:26: optimized: loop vectorized using 16 byte vectors
```
Am I missing something, or can we consider this part of the issue to be solved?

**Comment by hageboeck** [comment]
It is vectorised on the machine where you compile. In cvmfs, where most people get their ROOT from, it is not. That's the reason that Manos' mini library exists, which is compiled a few times for different architectures.
If the computations for normalisation and the logarithms are pulled over into that library, every user gets a speed boost, and not only the ones that compiled ROOT manually.

**Comment by hageboeck** [comment]
@manolismih

**Comment by guitargeek** [comment]
Thank you for the explanation! What about the loop in `[getLogProbabilities()](https://github.com/root-project/root/blob/master/roofit/roofitcore/src/RooAbsPdf.cxx#L733)`? It doesn't get vectorized when I compile it. So for that part of the issue I need to adapt RooAbsPdf itself, right?

**Comment by hageboeck** [comment]
> What about the loop in getLogProbabilities()?

It used to work. Either your compiler is too anxious about it or this commit d72f241f792 broke it or you don't have VDT activated such that the `std::log` is used.

If this is moved over to the mini library, it's not so critical.

**Comment by hageboeck** [comment]
I actually think that `BatchCompute::fast_log` is a misnomer, because it doesn't have to do with batch computing. It's just a fast, inlinable logarithm provided by VDT.

**Comment by guitargeek** [comment]
Cool, I didn't know that vdt can vectorize! If there is no VDT, `BatchCompute::fast_log` will do the exponential by the way: https://github.com/root-project/root/blob/master/roofit/batchcompute/inc/RooVDTHeaders.h#L56

**Comment by hageboeck** [comment]
I know, since I made it like this. :-) If you don't have VDT, you will still have all the computations working, but they will not be vectorised because the `std::` functions may have side effects (unless you use special compiler flags, fast math, ... rabbit hole! :-) )

The entire point of VDT is to provide fully inlinable, vectorisable functions, see introduction here:
https://github.com/dpiparo/vdt

**Comment by hageboeck** [comment]
On the topic of vectorisation, maybe you want to pull in this commit (and maybe do something analogous for Manos' new libraries):
https://github.com/hageboeck/root/commit/ad514958b76533f577948bf29817aedde86bd6db

I was running with this since months, but never merged it to master. Nobody needs the stupid side effects of the `std::` functions, and the experiments were happy with us disabling it for RooFit.
Once the side effects are gone, clang happily vectorises a lot more things.

**Comment by guitargeek** [comment]
Wow I didn't know about these side effects! I guess some people rely on them somewhere. I'll make a PR with this useful change to the `CMakeLists`.

**Comment by manolismih** [comment]
@hageboeck @guitargeek The important flags for facilitating auto-vectorization are `-fno-signaling-nans` and `-fno-trapping-math`. Clang has this on by default (that's why it's better than gcc in vectorizing) while gcc has this off by default. That's the reason why I have this flag in my computing libraries here: https://github.com/root-project/root/blob/447affc3323b6abacc97b56935a2ad3335aaa6c9/roofit/batchcompute/CMakeLists.txt#L38

**Comment by dpiparo** [comment]
hello, reviving a bit the discussion here. Did the new batch evaluation improve the situation? Can this item be closed?

**Comment by guitargeek** [comment]
There is still the a final optimization proposal here, in the initial post:
> Generation of events. Unless specialised generator functions are implemented, RooFit employs accept/reject sampling. Since this has to evaluate the PDF many times, one could think about using the batch interface to generate e.g. 2x the requested number of events, and do accept/reject on those. Repeat until enough events have been generated, and throw away the rest.

But I migrated this to the general "Ideas for RooFit" issue (into the initial post of Stephan), so this one can be closed:
https://github.com/root-project/root/issues/6557

Like this, we have a better overview on the possible improvements and ideas.
