### ISSUE TITLE
TExecutor: handling of non-IMT/... case

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7039]
### Explain what you would like to see improved
TExecutor.h currently contains:
https://github.com/root-project/root/blob/ace7d797ecb3df6916f7a328ca01f488755b7914/core/imt/inc/ROOT/TExecutor.hxx#L191:L200
```c++
#ifdef R__USE_IMT
   std::unique_ptr<ROOT::TThreadExecutor> fThreadExecutor;
#else
   #define fThreadExecutor fSequentialExecutor
#endif
#ifndef R__WIN32
   std::unique_ptr<ROOT::TProcessExecutor> fProcessExecutor;
#else
   #define fProcessExecutor fSequentialExecutor
#endif
```
This should be improved to not rely on CPP macros rewriting code, i.e. the `#define fThreadExecutor` / `#define fProcessExecutor` are problematic.

### Optional: share how it could be improved

A possibility might be:
```c++
#ifdef R__USE_IMT
# define R__EXECUTOR_THREAD ROOT::TThreadExecutor
#else
# define R__EXECUTOR_THREAD ROOT::TSequentialExecutor
#endif
#ifndef R__WIN32
# define R__EXECUTOR_PROCESS ROOT::TProcessExecutor
#else
# define R__EXECUTOR_PROCESS ROOT::TSequentialExecutor
#endif
   std::unique_ptr<R__EXECUTOR_THREAD> fThreadExecutor;
   std::unique_ptr<R__EXECUTOR_PROCESS> fProcessExecutor;
```
possibly followed by a clean-up:
```c++
#undef R__EXECUTOR_THREAD
#undef R__EXECUTOR_PROCESS
```
unless those are needed for constructors / initializers / ...

### Additional context

Brought up by @hahnjo in https://github.com/root-project/root/pull/7033#issuecomment-759494622

**Comment by hahnjo** [comment]
> A possibility might be:
```c++
#ifdef R__USE_IMT
# define R__EXECUTOR_THREAD ROOT::TThreadExecutor
#else
# define R__EXECUTOR_THREAD ROOT::TSequentialExecutor
#endif
#ifndef R__WIN32
# define R__EXECUTOR_PROCESS ROOT::TProcessExecutor
#else
# define R__EXECUTOR_PROCESS ROOT::TSequentialExecutor
#endif
   std::unique_ptr<R__EXECUTOR_THREAD> fThreadExecutor;
   std::unique_ptr<R__EXECUTOR_PROCESS> fProcessExecutor;
```
Hm, but you cannot have multiple `std::unique_ptr` reference the same object on the heap, which is what the current `define`s do. Maybe that's fine though, I didn't look into the code...

**Comment by xvallspl** [comment]
> > A possibility might be:
> 
> ```c++
> #ifdef R__USE_IMT
> # define R__EXECUTOR_THREAD ROOT::TThreadExecutor
> #else
> # define R__EXECUTOR_THREAD ROOT::TSequentialExecutor
> #endif
> #ifndef R__WIN32
> # define R__EXECUTOR_PROCESS ROOT::TProcessExecutor
> #else
> # define R__EXECUTOR_PROCESS ROOT::TSequentialExecutor
> #endif
>    std::unique_ptr<R__EXECUTOR_THREAD> fThreadExecutor;
>    std::unique_ptr<R__EXECUTOR_PROCESS> fProcessExecutor;
> ```
> 
> Hm, but you cannot have multiple `std::unique_ptr` reference the same object on the heap, which is what the current `define`s do. Maybe that's fine though, I didn't look into the code...

In this solution we would only have a single `std::unique_ptr` reference. The ifdef conditions are on definitions that depend on the configuration of the root build

**Comment by Axel-Naumann** [comment]
@hahnjo 
> Hm, but you cannot have multiple std::unique_ptr reference the same object on the heap
I don't see that being the case, neither for master nor for my proposed change. What am I overlooking?

@xvallspl 
> In this solution we would only have a single std::unique_ptr reference.
I don't know what you mean by "reference", I don't have lvalue references anywhere here. With my proposal, for all ROOT configuration cases we'd have a definition of three members, `fSequentialExecutor`, `fThreadExecutor`, `fProcessExecutor`. Their types differ depending on ROOT's configuration. Note that I'm using the (assumed) feature that having one or many `ROOT::TSequentialExecutor` doesn't make any difference; that might be wrong.

**Comment by hahnjo** [comment]
@Axel-Naumann 

> > Hm, but you cannot have multiple std::unique_ptr reference the same object on the heap
> 
> I don't see that being the case, neither for master nor for my proposed change. What am I overlooking?

The current `define`s make `fThreadExecutor` and `fProcessExecutor` aliases of `fSequentialExecutor`, ie they access the very same (sequential) executor. You cannot do this with three `std::unique_ptr`s, but maybe that's not needed?

**Comment by xvallspl** [comment]
> @hahnjo
> 
> > Hm, but you cannot have multiple std::unique_ptr reference the same object on the heap
> 
> I don't see that being the case, neither for master nor for my proposed change. What am I overlooking?
> 
> @xvallspl
> 
> > In this solution we would only have a single std::unique_ptr reference.
> 
> I don't know what you mean by "reference", I don't have lvalue references anywhere here. With my proposal, for all ROOT configuration cases we'd have a definition of three members, `fSequentialExecutor`, `fThreadExecutor`, `fProcessExecutor`. Their types differ depending on ROOT's configuration. Note that I'm using the (assumed) feature that having one or many `ROOT::TSequentialExecutor` doesn't make any difference; that might be wrong.

Shouldn't make any difference. These ifdefs are for compilation purposes. The execution policies available in these specific cases will ensure we never call a method from the fallbacks to TSequentialExecutor.

**Comment by Axel-Naumann** [comment]
@hahnjo the master's `define`s (for non-IMT or Windows) do not declare one of the `unique_ptr`s. Instead, all usages of the now undeclared member get rewritten to usages of the `fSequentialExecutor` member. Agreed? :-) So while not beautiful, the current `#define` setup should work (modulo modules, which dislike leaks of CPP defines our of modules).

OK and anyway, there seems to be no counter-argument against what I propose, or am I missing something? If yous think it's fine: please open a PR, thanks!

**Comment by hahnjo** [comment]
@xvallspl shall we close this?

**Comment by xvallspl** [comment]
Yes, I merged Axel's proposal today
