### ISSUE TITLE
[DF] RResultPtr::Release

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#7047]
### Explain what you would like to see improved

It would be nice if RDataFrame's `RResultPtr` type offered the option to return the result while releasing its ownership. This is useful e.g. to transfer ownership of that result to ROOT7 graphics interfaces. E.g. `RResultPtr<T>::Release() -> unique_ptr<T>`.

**Comment by Harshalzzzzzzz** [comment]
@eguiraud Dear Mentor, 
I'm interested in contributing to the Root project and I would like to work on this issue. Can you please elaborate more on what needs to be done, since I'm a new to the project?
Thanks!

**Comment by eguiraud** [comment]
Hi @Harshalzzzzzzz ,
ROOT has a high-level data analysis interface called [RDataFrame](https://root.cern/doc/master/classROOT_1_1RDataFrame.html), you can take a look at the docs and try reading and running some of the tutorials [here](https://root.cern/doc/master/group__tutorial__dataframe.html).

`RDataFrame` returns results wrapped in the [RResultPtr](https://root.cern/doc/master/classROOT_1_1RDF_1_1RResultPtr.html) type, through which we implement lazy execution (data processing is triggered when a user accesses the contents of a `RResultPtr`, _not_ when they request the result).

RResultPtr has interface and semantics similar to [std::shared_ptr](https://en.cppreference.com/w/cpp/memory/shared_ptr), but currently it's missing a way to release ownership of its contents. `RResultPtr<T>::Release` is a simple method that would mimic the semantics of `std::shared_ptr::release`: it must return a `T*` and empty the `RResultPtr`.

What needs to be done concretely:

- [ ] add the RResultPtr::Release method in RResultPtr.hxx. It should be implemented in terms of `fObjPtr.release()` and it should also set `fActionPtr` and `fLoopManager` to null
- [ ] add tests for the feature in `tree/dataframe/test/dataframe_resptr.cxx`, in particular making sure that `Release` and the ResultPtr's move-constructor have consistent behavior
- [ ] add logic to the current method `RResultPtr::GetValue` to throw an exception if it's called on a null `RResultPtr`

**Comment by Harshalzzzzzzz** [comment]
@eguiraud If possible can you indicate any other Release methods I can refer to in other modules or files so that I can follow proper conventions and methods for adding the same for RResultPtr while creating the PR .

**Comment by eguiraud** [comment]
I don't think there are other Release methods in ROOT. RResultPtr behaves similarly to a std::shared_ptr, and RResultPtr::Release should release its ownership of `fObjPtr`, something like:

```
fActionPtr = nullptr;
fLoopManager = nullptr;
auto ptr = fObjPtr.get();
fObjPtr.reset();
return ptr;
```

For the coding conventions: you can probably figure out the naming conventions from the surrounding code, and you should format the code with `clang-format` before committing (if you run `clang-format` from inside the root sources, it will automatically pick up our `.clang-format` style file).

**Comment by Harshalzzzzzzz** [comment]
@eguiraud Pull Request :  https://github.com/root-project/root/pull/7142

**Comment by eguiraud** [comment]
#7142 is merged, thank you @Harshalzzzzzzz !

Before closing the issue I'll go through `RResultPtr`'s API one last time because I think there are a couple more places where we should check for a null `fActionPtr` before dereferencing it, but this is an issue we already had.

**Comment by eguiraud** [comment]
#7267 improved the behavior or null RResultPtrs a bit. Closing this.
