### ISSUE TITLE
Fatal error after running "make install" when built against LLVM 9

### ISSUE THREAD

**Issue by chrisburr** [root-project/root#7055]
Moved from https://github.com/root-project/root/pull/6385 as there are too many bot comments in that PR. cc @vgvassilev

When testing the LLVM 9 PR for conda-forge and had a few issues with external LLVM/Clang/Cling so I temporarily switched to the builtins. This works from the build directory but it then has issues once `make install` is ran. More details are in the comment copied at the end of this issue. I think this is an issue with root's install commands rather than the conda-recipe, but you can reproduce what I'm doing it docker by running:

```bash
git clone https://github.com/conda-forge/root-feedstock.git
git checkout llvm90-install-error
# Adjust CPU_COUNT as required
CPU_COUNT=192 ./build-locally.py --debug --output-id '*root_base*' linux_64_numpy1.16python3.8.____cpython
# When the container launches, look at the output and run the suggested command
# which will be of the form:
cd xxxxx && source xxxxx/build_env_setup.sh
source $RECIPE_DIR/build_root-base.sh
# Anything with ROOT will now fail, e.g.
root
# Rather than waiting to build again, you can roll back to before
# "make install" was ran by running
cd ../..
rm -rf $PWD/*
cp -rp $PWD.bak/* $PWD/
cd -
```

>The command I'm running was simply `root` to get the interactive prompt. The full output of trying to run `1+2` is below:
>```log
>$ root -b -q -x -e 1+2
>input_line_1:1:2: fatal error: module 'libc' imported by AST file '/home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/std.pcm' found in a different module map file (/home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/etc/cling/libc.modulemap) than when the importing AST file was built (/home/cburr/mambaforge/conda-bld/root_1609268594446/work/build-dir/etc/cling/libc.modulemap)
>#include <new>
> ^
>input_line_1:1:2: note: imported by module 'std' in '/home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/std.pcm'
>Warning in cling::IncrementalParser::CheckABICompatibility():
>  Failed to extract C++ standard library version.
>'at_quick_exit' not defined
><<< cling interactive line includer >>>: fatal error: module file '/home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libc.pcm' is out of date and needs to be rebuilt
>Failed to load module libc
>Failed to load module std
>Failed to load module _Builtin_intrinsics
>Failed to load module ROOT_Foundation_C
>Failed to load module ROOT_Rtypes
>Failed to load module ROOT_Foundation_Stage1_NoRTTI
>Failed to load module Core
>Failed to load module Rint
>Failed to load module RIO
>Failed to load module MathCore
>Failed to load module Hist
>Failed to load module ROOTBrowsable
>Failed to load module Unfold
>Failed to load module RHTTPSniff
>Failed to load module Imt
>Failed to load module HistPainter
>Failed to load module PyMVA
>Failed to load module RDAVIX
>Failed to load module RHTTP
>Failed to load module FitPanel
>Failed to load module ROOTVecOps
>Failed to load module ProofDraw
>Failed to load module Quadp
>Failed to load module ROOTNTuple
>Failed to load module ROOT_Foundation_Stage1_NoRTTI
>Failed to load module Genetic
>Failed to load module Eve
>Failed to load module GeomPainter
>Failed to load module TreeViewer
>Failed to load module Physics
>Failed to load module EG
>Failed to load module Tree
>Failed to load module HistFactory
>Failed to load module Spectrum
>Failed to load module Matrix
>Failed to load module Html
>Failed to load module Hist
>Failed to load module GuiHtml
>Failed to load module _Builtin_intrinsics
>Failed to load module Gpad
>Failed to load module TMVAGui
>Failed to load module Postscript
>Failed to load module ROOTEve
>Failed to load module RGL
>Failed to load module Fumili
>Failed to load module Net
>Failed to load module Geom
>Failed to load module RooFitMore
>Failed to load module ROOTGpadv7
>Failed to load module X3d
>Failed to load module Cling_Runtime
>Failed to load module SPlot
>Failed to load module EGPythia8
>Failed to load module RooFit
>Failed to load module RCsg
>Failed to load module Rint
>Failed to load module XMLParser
>Failed to load module MultiProc
>Failed to load module RooStats
>Failed to load module GeomBuilder
>Failed to load module Proof
>Failed to load module FITSIO
>Failed to load module Ged
>Failed to load module Recorder
>Failed to load module FFTW
>Failed to load module GuiBld
>Failed to load module ROOTWebDisplay
>Failed to load module RooFitCore
>Failed to load module Gui
>Failed to load module SQLIO
>Failed to load module XMLIO
>Failed to load module ROOT_Rtypes
>Failed to load module std
>Failed to load module ROOTHistDraw
>Failed to load module GX11TTF
>Failed to load module RIO
>Failed to load module ProofPlayer
>Failed to load module ASImage
>Failed to load module libc
>Failed to load module ROOT_Foundation_C
>Failed to load module MathMore
>Failed to load module Foam
>Failed to load module RSQLite
>Failed to load module SpectrumPainter
>Failed to load module Minuit2
>Failed to load module Core
>Failed to load module MLP
>Failed to load module ROOTDataFrame
>Failed to load module GenVector
>Failed to load module NetxNG
>Failed to load module ROOTBrowserv7
>Failed to load module Minuit
>Failed to load module RootAuth
>Failed to load module Graf3d
>Failed to load module TMVA
>Failed to load module ASImageGui
>Failed to load module Graf
>Failed to load module GX11
>Failed to load module Gdml
>Failed to load module ProofBench
>Failed to load module Cling_Runtime_Extra
>Failed to load module MathCore
>Failed to load module Gviz3d
>Failed to load module WebGui6
>Failed to load module ROOTTPython
>Failed to load module ROOTHist
>Failed to load module TreePlayer
>Failed to load module Gviz
>Failed to load module ROOTGraphicsPrimitives
>Failed to load module ROOTFitPanelv7
>Failed to load module Smatrix
>Failed to load module SessionViewer
>Failed to load module Thread
>input_line_4:1:2: error: unknown type name 'ifdef'
>#ifdef complex
> ^
><<< cling interactive line includer >>>:1:1: error: expected unqualified-id
>input_line_5:1:2: error: unknown type name 'ifdef'
>#ifdef PI
> ^
><<< cling interactive line includer >>>:1:1: error: expected unqualified-id
>input_line_6:1:2: error: unknown type name 'ifdef'
>#ifdef ERROR
> ^
><<< cling interactive line includer >>>:1:1: error: expected unqualified-id
>
> *** Break *** segmentation violation
>
>
>
>===========================================================
>There was a crash.
>This is the entire stack trace of all threads:
>===========================================================
>#0  0x00007fad7d33546c in waitpid () from /lib64/libc.so.6
>#1  0x00007fad7d2b2f62 in do_system () from /lib64/libc.so.6
>#2  0x00007fad7d8ebf8f in TUnixSystem::StackTrace() () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCore.so.6.23
>#3  0x00007fad7d8e8857 in TUnixSystem::DispatchSignals(ESignals) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCore.so.6.23
>#4  <signal handler called>
>#5  0x00007fad77e65e25 in ROOT::TMetaUtils::TNormalizedCtxtImpl::keepTypedef(cling::LookupHelper const&, char const*, bool) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#6  0x00007fad77e6659e in ROOT::TMetaUtils::TNormalizedCtxtImpl::TNormalizedCtxtImpl(cling::LookupHelper const&) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#7  0x00007fad77e66db3 in ROOT::TMetaUtils::TNormalizedCtxt::TNormalizedCtxt(cling::LookupHelper const&) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#8  0x00007fad77f341df in TCling::TCling(char const*, char const*, char const* const*) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#9  0x00007fad77f35ab2 in CreateInterpreter () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#10 0x00007fad7d789243 in TROOT::InitInterpreter() () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCore.so.6.23
>#11 0x00007fad7d789740 in ROOT::Internal::GetROOT2() () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCore.so.6.23
>#12 0x00007fad7d797df6 in TApplication::TApplication(char const*, int*, char**, void*, int) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCore.so.6.23
>#13 0x00007fad7dc8f49b in TRint::TRint(char const*, int*, char**, void*, int, bool) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libRint.so.6.23
>#14 0x0000563c1fb240d2 in main ()
>===========================================================
>
>
>The lines below might hint at the cause of the crash.
>You may get help by asking at the ROOT forum https://root.cern.ch/forum
>Only if you are really convinced it is a bug in ROOT then please submit a
>report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
>from above as an attachment in addition to anything else
>that might help us fixing this issue.
>===========================================================
>#5  0x00007fad77e65e25 in ROOT::TMetaUtils::TNormalizedCtxtImpl::keepTypedef(cling::LookupHelper const&, char const*, bool) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#6  0x00007fad77e6659e in ROOT::TMetaUtils::TNormalizedCtxtImpl::TNormalizedCtxtImpl(cling::LookupHelper const&) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#7  0x00007fad77e66db3 in ROOT::TMetaUtils::TNormalizedCtxt::TNormalizedCtxt(cling::LookupHelper const&) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#8  0x00007fad77f341df in TCling::TCling(char const*, char const*, char const* const*) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#9  0x00007fad77f35ab2 in CreateInterpreter () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCling.so
>#10 0x00007fad7d789243 in TROOT::InitInterpreter() () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCore.so.6.23
>#11 0x00007fad7d789740 in ROOT::Internal::GetROOT2() () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCore.so.6.23
>#12 0x00007fad7d797df6 in TApplication::TApplication(char const*, int*, char**, void*, int) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libCore.so.6.23
>#13 0x00007fad7dc8f49b in TRint::TRint(char const*, int*, char**, void*, int, bool) () from /home/cburr/mambaforge/conda-bld/root_1609268594446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libRint.so.6.23
>#14 0x0000563c1fb240d2 in main ()
>===========================================================
>```
>
>_Originally posted by @chrisburr in https://github.com/root-project/root/issues/6385#issuecomment-752250076_

**Comment by vgvassilev** [comment]
Thanks for the report. Should be fixed in the new version of the #6385
