### ISSUE TITLE
TBB moved to CMake-only in version 2021 and builtin TBB needs to be adapted for the future

### ISSUE THREAD

**Issue by xvallspl** [root-project/root#7063]
### Explain what you would like to see improved and what isn't as good as it could be and why

By @amadio's words in https://mattermost.web.cern.ch/root/pl/xu1a5816u3rizqe68hi3n6nn1o:

"This new version of TBB only uses CMake as build system, so the builtin TBB logic will also need to be updated, as that relies on the Makefile-based build system up to now."

**Comment by AlexVeprev** [comment]
Hi, I've found this proposal in scope of https://github.com/spack/spack/issues/22616 investigation.
I'd vote for such improvement and can help with it from TBB side.

First, I can confirm that TBB 2021 (now it's oneTBB 2021) has CMake build system.

Second, oneTBB integration to CMake project may be done in two major ways:
1. Source integration (`add_subdirectory`) - oneTBB is just built from sources together with user project.
2. Binary integration (`find_package`) - user project relies on pre-built oneTBB, it is supported through TBBConfig files inside oneTBB packages, for some distributions/versions it will work out-of-the-box, but for others it may require additional CMake variable to be set. [Here ](https://github.com/oneapi-src/oneTBB/blob/master/cmake/README.md#tbbconfig---integration-of-binary-packages)is a short description of binary integration.

The (1) way is supported only starting from oneTBB 2021, while the (2) way was [introduced](https://github.com/oneapi-src/oneTBB/tree/tbb_2020/cmake#binary-package-integration) in TBB 2017 U7 and slightly changed in oneTBB 2021.

What way is preferable? In theory we can think about some kind of mixed approach.

**Comment by AlexVeprev** [comment]
BTW, current FindTBB can't handle oneTBB under spack: https://github.com/spack/spack/issues/22616#issuecomment-811374256

**Comment by Axel-Naumann** [comment]
We need to offer `find_package`, and - if no external package is found or if configured to use builtin tbb - pull tbb from somewhere and build it as part of ROOT ("builtin"). @oshadura will correct me / add to this.

**Comment by guitargeek** [comment]
Thanks to @dpiparo, we are not using the Makefile-based build anymore in the tbb builtin!

* https://github.com/root-project/root/pull/13724
