### ISSUE TITLE
RooFit RooAbsArg::graphVizTree produces invalid dot files for graph titles including spaces

### ISSUE THREAD

**Issue by richard-lane** [root-project/root#7067]
- [x] Checked for duplicates

### Describe the bug

.dot file generated with RooAbsArg::graphVizTree produces an invalid .dot file if the graph title contains spaces.

### Expected behavior

RooAbsArg::graphVizTree should produce a valid .dot file even when the names of the elements contain spaces.

### To Reproduce

ROOT macro, save to graphvizMWE.C and run with `root graphvizMWE.C`:
```
void graphvizMWE(void){
    // Create a simple dependency tree
    RooRealVar x{};
    RooRealVar sigma{};
    RooRealVar mu{};

    RooGaussian Gaussian("my_gaussian", "Gaussian", x, mu, sigma);
    RooGaussian GaussianWithSpace("my gaussian", "Gaussian", x, mu, sigma);

    // Create GraphViz trees
    Gaussian.graphVizTree("tree_example.dot");
    GaussianWithSpace.graphVizTree("tree_example2.dot"); // Produces invalid output
}
```
Then attempt to convert the produced `.dot` files to images using
`dot -Tpng tree_example.dot -o example1.png  # Produces an image`
`dot -Tpng tree_example2.dot -o example2.png  # Error!`

The first of these will produce a .png image, the second will fail with a message like: `Error: tree_example2.dot: syntax error in line 1 near 'gaussian'`

Can be fixed by enclosing the graph title in quotes: i.e. changing line 1 of `tree_example2.dot` from
`digraph my gaussian{`
to
`digraph "my gaussian"{`

### Setup

ROOT built from source

ROOT Version: 6.23/01
Built for linuxx8664gcc on Jun 05 2020, 15:06:16
From heads/master@v6-23-01-229-gd4ac502837

Ubuntu 18.04.5 LTS

**Comment by Axel-Naumann** [comment]
Thanks - PR welcome :-) Generally we recommend not to add spaces to names, neither for histograms etc.
