### ISSUE TITLE
`cmake -Droottest=On` tests wrong ROOT build!

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7081]
### Describe the bug
Configuring a build with a different ROOT build already in the environment causes CTest to test the wrong build. I wonder how many devs are not testing their changes but that of some completely unrelated build :-(

### Expected behavior
`cmake -Droottest=On` should have `ctest` test *that* build.

### To Reproduce
```
$ which root
$ mkdir ../1
$ cd ../1
$ . /home/axel/build/root/master/deb/bin/thisroot.sh
$ cmake -Droottest=On ../src
$ grep ROOTSYS CMakeCache.txt 
ROOTSYS:INTERNAL=/home/axel/build/root/master/deb
```

### Setup
1. ROOT version: master
2. Operating system: Ubuntu 20.04
3. How you obtained ROOT: I built it myself.

**Comment by oshadura** [comment]
@Axel-Naumann you source `. /home/axel/build/root/master/deb/bin/thisroot.sh` and `ROOTSYS:INTERNAL=/home/axel/build/root/master/deb` in roottest is as expected. Am I missing something?

**Comment by Axel-Naumann** [comment]
Well yes - if I build `1/` and enable roottest for that build I'd expect that roottest would test that build, no? I think that's a fairly common thing to "have a build of X with tests enabled" - and if I do that I don't expect that to test something else than the build for which I'm enabling the tests?

**Comment by Axel-Naumann** [comment]
I was hit by this two more times since I opened this (as I now know I have to check for this).

My teminal sessions are long-lived; I debug an issue (with some ROOT build), then I need to build ROOT from scratch - and now that ROOT build is not testing itself. That's really really terrible :-/ Can we *please* have this fixed?
