### ISSUE TITLE
Apple M1: bug in jitting argument of type short

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7090]
### Describe the bug
`new TPad("p","p",0.,0.,1.,1.)` on the prompt (or anything jitted by the interpreter) will pass 65535 for `color` even though the constructor is declared as `TPad (const char *name, const char *title, Double_t xlow, Double_t ylow,
Double_t xup, Double_t yup, Color_t color=-1, Short_t bordersize=-1,
Short_t bordermode=-2)` where `Color_t` is `short`.

Apparently, cling and the compiled library disagree on the size of `short`?

### Expected behavior
`TPad()` should see `color == -1` being passed, as per the default argument.

### To Reproduce
`new TPad("p","p",0.,0.,1.,1.)` shows the wrong background color.

### Setup
Apple M1, ROOT master built with clang.

**Comment by couet** [comment]
This bug makes stressGraphics fail on Apple M1 machines.

**Comment by hahnjo** [comment]
Want to see something funny? I had a ROOT build in `Debug` mode laying around on `macphsft25`, added a `std::cout` to print the color value in `TPad::TPad` - and was very surprised to see `-1`. Rebuilt in `Release` mode and now it's `65535` :thinking:

**Comment by Axel-Naumann** [comment]
Hmm that would hint at an ABI issue - and that should be reproducible with `lli`, even though it might need a JIT -> compiled library call to expose the ABI incompatibility. FYI and in case you don't know, you can load a .so into `lli` with `-load=` - that's not what the argument was invented for, but it works like a charm :-)

**Comment by hahnjo** [comment]
Yep, it's an ABI issue: On AArch64, integers with less than 32 bits (including `short`s) are promoted to 32 bits - so far, so good, everybody agrees on that. Where things start to differ is *how* to do that, Darwin expects extension whereas the generic method is "direct". I suppose the latter means filling with zeros in practice, so `(short)-1 = 0xffff -> 0x0000ffff = 65535`. Setting up the target triple in a different way in #7787 allows Clang's Driver logic to compute the ABI correctly.
