### ISSUE TITLE
Incorrect work of the 'TPgSQLStatement::SetBinary' function

### ISSUE THREAD

**Issue by kgertsenberger** [root-project/root#7127]
- [x] Checked for duplicates

### Describe the bug
Hi, may I discuss possible solutions of the incorrect work of the 'TPgSQLStatement::SetBinary' function.
In our experiment, we've used 'TPgSQLStatement::SetLargeObject' with PostgreSQL 8, but now we've moved to PostgreSQL 12 and discover that since PostgreSQL 9 the developers limited access to pg_largeobject, which leads to some problems.
So now we are using TPgSQLStatement::SetBinary' instead and i've found some bugs.
The original 'SetBinary'  function includes the following main lines:
```
unsigned char* escape_ptr = PQescapeBytea((const unsigned char*)mem, sz, &mxsz);
unsigned char* binary_ptr = PQunescapeBytea((const unsigned char*)escape_ptr, &mxsz);
```
1. 'PQunescapeBytea' conversion is not exactly the inverse of 'PQescapeBytea': 'PQescapeBytea' doubles quotes, but  'PQunescapeBytea' doesn't change quotes (doesn't remove added quotes).
So double quotes should be reduced to single ones after the conversion. Otherwise, a bytea field stored in the database has two quotes instead of original single ones.
2. The solution works for PostgreSQL 8 (except 1. cases), because it escapes special characters with two backslashes, but since PostgreSQL 9.3 the special characters are escaped with one backslash. It means that PQunescapeBytea returns the special characters to original symbols refused by database encoding (UTF8 by default).
e.g. for CREATE TABLE test ( d bytea NOT NULL );
```
TSQLStatement* stmt = my_db->Statement("insert into test(d) values ($1)");
int d = 8332;
stmt->NextIteration();
stmt->SetBinary(0, &d, sizeof(int));
stmt->Process();
...
stmt = my_db->Statement("select d from test");
stmt->Process();
stmt->StoreResult();
while (stmt->NextResultRow()) {
   void* mem = 0;   Long_t size_mem = 0;
    stmt->GetBinary(0, mem, size_mem);
    int* val = new int;
    memcpy(val, mem, size_mem);
    cout<<"Binary size: "<<size_mem<<". Int value: "<<*val<<endl;
}
```
PostgreSQL 8 works well:

> 8c2000 // before PQescapeBytea
> \\\\214 \\\\000\\\\000 // before PQunescapeBytea
> 5c323134205c3030305c303030 // after PQunescapeBytea
> Binary size: 4. Int value: 8332 // original value

but PostgreSQL 12 refuses to write data:

> 8c2000 // before PQescapeBytea
> \214 \000\000 // before PQunescapeBytea
> 8c2000 // after PQunescapeBytea
> Error in <TPgSQLStatement::Process>: Code: 7  Msg: ERROR:  invalid byte sequence for encoding "UTF8": 0x8c

I see 3 possible solutions:
1. Check PostgreSQL version, and if it is higher or equal than 9.3, then exclude
`unsigned char* binary_ptr = PQunescapeBytea((const unsigned char*)escape_ptr, &mxsz);`
Without unescaping bytea data are saved well.
2. Check PostgreSQL version, and if it is higher or equal than 9.3, then add second backslash, as it was done in PostgreSQL 8 (or vice versa, if Postgresql version is less than 9.3, delete second backslashes and remove PQunescapeBytea).
3. Rewrite TPgSQLStatement in a such way that binary data are transferred not as a string, but as binary in this function (fParamFormats):
```
fStmt->fRes= PQexecPrepared(fStmt->fConn,"preparedstmt",fNumBuffers,
                               (const char* const*)fBind,
                               0,//fParamLengths,
                               0,//fParamFormats,
                               0);
```

Can you advice solution and what to do with the problems?

### Setup
ROOT 6, master branch
Ubuntu 20.10
ROOT was built from source code.

**Comment by linev** [comment]
Hi,

I am not pgsql expert, but somehow maintain these SQL plugins in ROOT.
Looking into [pgsql docu](https://www.postgresql.org/docs/9.1/libpq-exec.html), I guess variant 3 will be preferable. `PQexecPrepared` allows to specify type and length of each parameter. One can use 0 as default and only for binary use 1 - in this case binary can be used as is and do not need any escape characters.

Can you create PR for such functionality and test it?
In my mind, it should work for all recent `pgsql` versions.

Regards,
Sergey

**Comment by kgertsenberger** [comment]
Hello, 
I am agree with you, Sergey. In my opinion, the third solution is the best, it does not require to convert binary data into string values by escaping special characters, which leads to the above problems with double backslashes, quotes etc. 
Unfotunately at the moment i have no time to carefully implement it and test for different versions of PostgreSQL.
If it can wait until the end of the spring, i can return to it and implement in three monthes or try to find a student to be supervised for this task before.

With respect, Konstantin.

**Comment by linev** [comment]
Hi Konstantin,

Implementation is relatively simple, but I have no possibility to test the code.
If you can test changed code, I can provide it very soon

**Comment by linev** [comment]
@kgertsenberger 
Can you test https://github.com/root-project/root/pull/7134
It also includes two other bugfixes.
Please try statement with binary and without binary data - if it still works

**Comment by kgertsenberger** [comment]
Indeed, I am afraid to use fParamFormats variable in the 'PQexecPrepared' for working database of our experiment because it was not used before. So, we will switch to the solution after complete tests of all the database content a little bit later.
But ok, i will use a set of tests to check the solution for PostgreSQL 8 and 12 deployed on our servers.
Thank you.

**Comment by kgertsenberger** [comment]
Hello, Sergey.
I have tried to write test records, and i found that PQexecPrepared in TPgSQLStatement::Process() should be corrected in the same way as in the 'NextIteration()' function:
```
fStmt->fRes= PQexecPrepared(fStmt->fConn,"preparedstmt",fNumBuffers,
                                 (const char* const*)fBind,
                                 fParamLengths,
                                 fParamFormats,
                                 0);
```
After this additional correction the new solution works well.

With respect, Konstantin.

**Comment by linev** [comment]
Hi Konstantin,

I modify code once again, adding parameters in `TPgSQLStatement::Process()`
I also add in all setter methods special checks for parameter index and allocated memory - old implementation was error-prone.

Can you check once again?
Did you checking with both PgSQL version?

Regards,
Sergey

**Comment by kgertsenberger** [comment]
Hi,
Ok, i'll test it again. Yes, with both version 8 and 12.

With respect, Konstantin.

**Comment by kgertsenberger** [comment]
Hi, Sergey.
Oh, it took time to understand a new error while my tests:
```
 *** Break *** segmentation violation
munmap_chunk(): invalid pointer
```
because it doesn't contain any information on line codes.

Finally, i found that it happens because of this new function:  "TPgSQLStatement::SetSQLParamType". The function doesn't take into account all possible cases that have been accounted for before, e.g. if in 'SetBinary(Int_t npar, void* mem, Long_t size, Long_t maxsize)' the 'size' variable is greather than 'maxsize'.

With respect, Konstantin.

**Comment by linev** [comment]
> the 'size' variable is greater than 'maxsize'. 

In principle, it is wrong set of arguments. `maxisze` is intend to be allocated memory size. 
But now I add check for such situation.

> The old error-prone implementation worked at all my tests :)

It was by chance. With old code if one call  `SetNull(0)` and then `SetInt(0,0)` was causing segmentation violation.

If I understand correct, all other tests fine for you.
If yes, I will merge changes in master.

Do you need these fixes in older branches - like 6.22 or 6.20?

**Comment by linev** [comment]
Also fixed in 6.20 and 6.22 branches

**Comment by kgertsenberger** [comment]
Thank you much, Sergey.
Have you returned the check, when 'size' variable is greater than 'maxsize', in the new version?

With respect, Konstantin.

**Comment by linev** [comment]
> Have you returned the check, when 'size' variable is greater than 'maxsize', in the new version?

Yes, here is it: https://github.com/root-project/root/commit/e550ca8

**Comment by kgertsenberger** [comment]
I see. Thank you for your help.
