### ISSUE TITLE
Cannot build ROOT if another ROOT at /usr/local

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7128]
### Describe the bug
We must be able to build ROOT even if there's another ROOT installation at `/usr/local`. https://root-forum.cern.ch/t/problem-building-6-22-00-on-osx-10-14-with-clang-11/40652/9 seems to suggest that this is currently not the case.

This is relevant for
- sanity: separating the build and its artifacts from other, pre-existing ROOT artifacts allows us to be certain we build what we think we build and we test the build and not a combination of the build and whatever other ROOT there is;
- people building ROOT on shared resources for which they don't have admin powers

### Expected behavior
ROOT builds should be the same whether or not there are other ROOT installs / binaries no the system

### To Reproduce
See forum.

### Setup
See forum.

### Additional context
Loosely related to https://github.com/root-project/root/issues/7081

**Comment by Axel-Naumann** [comment]
Assigning to @vgvassilev as modulemap contamination seems to be the only blocker. Maybe `--rootbuild` should refrain from loading all the world's modulemaps?

**Comment by amadio** [comment]
See also https://sft.its.cern.ch/jira/plugins/servlet/mobile#issue/ROOT-10250

**Comment by guitargeek** [comment]
> Assigning to @vgvassilev as modulemap contamination seems to be the only blocker. Maybe `--rootbuild` should refrain from loading all the world's modulemaps?

I don't think this is the only blocker. There is also the problem that header files from the existing build can be picked up in the compilation:
* https://github.com/root-project/root/issues/13101
