### ISSUE TITLE
TTreeProcessorMT: Fails when iterating over different treenames within same ROOT file

### ISSUE THREAD

**Issue by phi-mah** [root-project/root#7143]
Hi, 

Some time ago, I have had issues when invoking an `RDataFrame` analysis on a `TChain` that consisted of trees with **different names** in the **same file** (the canonical thing is just the other way around...).

I first described the problem [here in the ROOT forum, rather long read, not absolutely necessary to understand this issue](https://root-forum.cern.ch/t/really-solved-rdataframe-for-tchain-loaded-with-ttrees-with-different-names/41756). Unluckily only my entire analysis chain was able to trigger the bug; i.e. I was not able to produce a condensed reproducer of the problem.

The clearest indicator of the occurring mismatch was the following line repeatedly being printed on the terminal:
```
Error in <TTreeReader::SetEntriesRange()>: first entry out of range 0..946274
```

I also found a work-around, but the problem was still bothering me, which is why I invested some time in debugging it:

* The number of the error statement is identical to the number of entries in the *first* tree, which has fewer entries than its partner. It only occurs once `EntryClusters` from the second tree are being processed. I.e. the tree-switch is insufficient.
* The error seems to be caused by the following line:
https://github.com/root-project/root/blob/312dacbfdb2b76bfb1fa7af9532a01b3b08d03f1/tree/treeplayer/src/TTreeProcessorMT.cxx#L143
* Changing it as shown in this diff here seems to solve the problem:
```
--- a/tree/treeplayer/src/TTreeProcessorMT.cxx	2021-02-07 20:22:19.290883093 +0000
+++ b/tree/treeplayer/src/TTreeProcessorMT.cxx	2021-02-07 20:32:00.000483321 +0000
@@ -140,8 +140,12 @@
                          const std::vector<Long64_t> &nEntries, const std::vector<std::vector<Long64_t>> &friendEntries)
 {
    const bool usingLocalEntries = friendInfo.fFriendNames.empty() && entryList.GetN() == 0;
-   if (fChain == nullptr || (usingLocalEntries && fileNames[0] != fChain->GetListOfFiles()->At(0)->GetTitle()))
+   if (fChain == nullptr || ( usingLocalEntries && (
+			  (fileNames[0] != fChain->GetListOfFiles()->At(0)->GetTitle()) ||
+			  (treeNames[0] != fChain->GetListOfFiles()->At(0)->GetName()) ))
+   ) {
       MakeChain(treeNames, fileNames, friendInfo, nEntries, friendEntries);
+   }
 
    std::unique_ptr<TTreeReader> reader;
    std::unique_ptr<TEntryList> localList;
```

At least, multi and single-threaded mode  deliver now consistent results for my analysis. I still don't have a reproducer to offer (except my entire analysis) and my findings are solely based on the  *v6.20 branch*. However, it would explain how 17c9cf9bad028208e858509665320a01bfafa538 could offer support for different tree names within the same `RDataFrame`, but failed in my particular case. 

What are your thoughts?

Cheers, Philipp

**Comment by eguiraud** [comment]
Hi Philipp,
thank you for the thorough report! Given the lack of a reproducer I have to ask you to help out a bit more.

What is your exact ROOT version? The commit you mentioned is included in 6.20/06 but e.g. not in 6.20/02.

Could you check whether the problem is still present in ROOT master? You can install a ROOT nightly build via conda or source it as an LCG release, see the instructions at https://root.cern/install/nightlies .

Cheers,
Enrico

**Comment by eguiraud** [comment]
Also, how do you create the TChain exactly?

**Comment by eguiraud** [comment]
> Changing it as shown in this diff here seems to solve the problem:

ah, definitely, that's a _bug_! that logic assumes that different trees are stored in files with different names :/

**Comment by phi-mah** [comment]
Hi Enrico,

with the underlying mechanism now unveiled, could you reproduce the behavior with https://github.com/eguiraud/root/commit/97dbdbb6a1a38d8d4706c4b459ff9a8368eb0769? I'm still wondering why the test you suggested in the ROOT forum in November did not trigger it? Although I tried to build up various other test-cases, unluckily they all worked. I finally found it by running a stripped and compiled version of my anaylsis under gdb. 

The root version used is: 6.20/08. In principle I could also test against the current master branch, but my computer at university still runs Debian 9 and I don't have access to the CERN computing infrastructure: --> Building a new ROOT version is always a bit cumbersome. As you seem to have taken over this bug, is still neeeded?

Philipp

**Comment by eguiraud** [comment]
_Should_ be fixed (and tested), let me know if you have any feedback (it would be great if you could pick that branch and check it fixes your usecase, or alternatively a nightly build tomorrow -- I plan to merge the fix today).

**Comment by phi-mah** [comment]
Hi Enrico, I just wanted to report that the master branch after merge (#6199f0610da0b97b99500803ac3d9af44b0bc955)  indeed solves the problem I originally came up with.

Took me a bit longer to check -- I don't have such a nice build pipeline, ;-).
But finally, this thing should be really fixed

**Comment by eguiraud** [comment]
Alright, thank you very much for confirming. v6.22/08 (next 6.22 patch release) and v6.24 (upcoming release, ETA a few weeks) will have the fix.
