### ISSUE TITLE
TGLedIndicator

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#7156]
### Is your feature request related to a problem? Please describe.
I would really like to have an LED status indicator class when I create my GUI windows with ROOT. I have found that the TGSpeedo class already contains an LED, but I did not find a standalone equivalent class.

### Describe the solution you'd like
Something equivalent to https://doc.qt.io/qt-5/qml-qtquick-extras-statusindicator.html or https://github.com/melanholly/qt5-led-indicator-widget, where on and off color can be set, but adding an optional 'label' as description. Something like:
* [LED] Busy
* [LED] Communication
* [LED] Ethernet

### Describe alternatives you've considered
Using Qt instead, but I would prefer staying with ROOT.

### Additional context
TGSpeedo LED that could be reused:
![image](https://user-images.githubusercontent.com/10653970/107345106-3d872000-6a91-11eb-88f6-044f21aabd05.png)

**Comment by eguiraud** [comment]
Assigning Bertrand as original author of TGSpeedo.

**Comment by bellenot** [comment]
@ferdymercury you can simply use a TGPictureButton with your own enabled/disabled LED picture

**Comment by ferdymercury** [comment]
Thanks, I understand. But I think it would still be much nicer to have a dedicated class, so that one can specify the color as a hex number or TColor or something similar, rather than having N different pictures stored for all colors you would think to use...

**Comment by bellenot** [comment]
Well, sorry but since we are in the process of moving to a Web based GUI (using openUI5), and since this is quite simple to be implemented on the user side, I don't think we're going to create a new widget. But we'll discuss this and I'll come back to you.

**Comment by ferdymercury** [comment]
Thanks for the hint. Maybe a combination of TGEllipse + TGLabel could also do the work?

**Comment by bellenot** [comment]
I don't know where this is coming from, I've never seen a `TGEllipse` class in ROOT (only `TEllipse`)

**Comment by ferdymercury** [comment]
Mmm ok, it looks it does not belong to ROOT, but to Taligent's OS (1995) https://twitter.com/stroughtonsmith/status/1130868274298871810 http://www.wildcrest.com/Potel/Portfolio/InsideTaligentTechnology/WW29.htm

**Comment by bellenot** [comment]
Anyway, as I said, we are focusing now on the new, Web based GUI, and not going to extend the existing one, especially for classes that are most probably not widely used...

**Comment by bellenot** [comment]
So sorry, but as explained, I close this feature request. Thanks anyway for the suggestion!

**Comment by ferdymercury** [comment]
Thanks, I understand, no problem.
Please add an LED indicator to the OpenUI5 feature-suggestion list, if it's not already in there ;)
