### ISSUE TITLE
TGSpeedo mean value calculation

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#7164]
### Explain what you would like to see improved
TGSpeedo class is quite helpful, but it lacks the ability of auto-calculating the mean value (a mean mark is there, but is up to the user to put a senseful value there on each update).

### Optional: share how it could be improved
I would propose to let the user define a circular buffer size, so that the TGSpeedo class autocalculates the mean value of the last N entries. The default value would be N=0 to keep old behaviour and save memory, but the user could call for example SetMeanBufferSize(10) to do an average of the last 10 entries.

Could be implemented for example using https://root.cern/doc/master/circular_8C.html
or just with this simple header class: https://github.com/jnk0le/Ring-Buffer/blob/master/ringbuffer.hpp

And then the average just as `std::sum(begin(...), end(...), 0)/N`

### To Reproduce
1. EnableMeanMark in TGSpeedo
2. The Mean value is not calculated automatically

### Setup
1. ROOT 6.23/01
2. Linux
3. Self-built

**Comment by bellenot** [comment]
@ferdymercury FYI, a [PR](https://github.com/root-project/root/pull/7170) has been created

**Comment by bellenot** [comment]
Fixed by https://github.com/root-project/root/pull/7170
