### ISSUE TITLE
TGCommandLinePlugin Up-Down Arrows and Tab Keys

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#7180]
### Explain what you would like to see improved
The TGCommandLinePlugin is great for external CMake/C++ applications that use some ROOT classes / TApplication and GUI classes TGFrame, where you want to have some interactive debugging options via Cling. To make it even more user-friendly, it would be nice if the following things were improved:
- Pressing Up and Down Arrow Keys changes the selected command in the ComboBox.
- Pressing Tab Key propagates to the command line to give command suggestions / autocompletion, as it happens in the real ROOT terminal
- Typed commands are added to the ROOT history file, so that the next time 

### Optional: share how it could be improved
Changes in TGTextEntry:
```
    virtual  void        UpDownArrowsPressed(Int_t);                           //*SIGNAL*

case kKey_Down:
          CursorOutDown();
          UpDownArrowsPressed(1);
          break;
case kKey_Up:
          CursorOutUp();
          UpDownArrowsPressed(0);
          break;
```

Changes in TGCommandLinePlugin
```
fCommand->Connect("TabPressed()", "TGCommandPlugin", this,
                      "HandleTab()");
fCommand->Connect("UpDownArrowsPressed()", "TGCommandPlugin", this,
                      "HandleArrows()");

void TGCommandPlugin::HandleTab()
 {
  //redirect CLI suggestions back to terminal
}


void TGCommandPlugin::HandleArrows()
 {
  //Scroll one up or down in combobox
}

if (app->InheritsFrom("TRint") || fForceFlag ) // accept also if a user set an fForceFlat explicitly?
          Gl_histadd((char *)string);
```

### To Reproduce
- Open tutorials/gui/guiWithCINT.C
- Try to use up and down arrow keys to scroll between line commands

### Setup
1. ROOT 6.23/01
2. Linux
3. Self-built

**Comment by bellenot** [comment]
> * Pressing Up and Down Arrow Keys changes the selected command in the ComboBox.

I'll take a look if and how that could easily be implemented

> * Pressing Tab Key propagates to the command line to give command suggestions / autocompletion, as it happens in the real ROOT terminal

Sorry, but I don't think I will embark in such development in the current GUI.

> * Typed commands are added to the ROOT history file, so that the next time

I'll cross-check, but I think it should already be the case...

**Comment by bellenot** [comment]
@ferdymercury check [root-project#7180](https://github.com/root-project/root/issues/7180)

**Comment by ferdymercury** [comment]
Thanks so much.

I checked it, it works great, I saw just a couple of issues:
- If I go all the way down to the last entry, I need press twice 'up' key to go the second entry. Probably, some issue between index 0 and index 1.
- Maybe, index 0 should correspond to the 'empty' comannd line window, or whatever the user had typed in the beginning before pressing the arrows. For example,    if (te) {      fCommand->SetText(te->GetText()->GetString());   } else { fCommand->SetText(temporaryString); }, where temporaryString was whatever was in the TGTextEntry before scrolling in the history.
- The ROOT history is still not saved even if I call plugin->SetHistAdd(); which means that somehow Gl_histadd((char *)string); is not working in a standalone CMake TApplication?

Thanks for the excellent support.

**Comment by bellenot** [comment]
> * If I go all the way down to the last entry, I need press twice 'up' key to go the second entry. Probably, some issue between index 0 and index 1.

I'll check

> * Maybe, index 0 should correspond to the 'empty' comannd line window, or whatever the user had typed in the beginning before pressing the arrows. For example,    if (te) {      fCommand->SetText(te->GetText()->GetString());   } else { fCommand->SetText(temporaryString); }, where temporaryString was whatever was in the TGTextEntry before scrolling in the history.

OK, I'll see what I can do



> * The ROOT history is still not saved even if I call plugin->SetHistAdd(); which means that somehow Gl_histadd((char *)string); is not working in a standalone CMake TApplication?

That might well be. But if it's the case then I'm afraid there is not much I can do..

**Comment by ferdymercury** [comment]
For the tab-completion, I checked and it looks it could be done in a more or less simple way I guess:

```
fCommand->Connect("TabPressed()", "TGCommandPlugin", this, "HandleTab()");

void TGCommandPlugin::HandleTab()
{
   const std::string line = fCommandBuf->GetString();
   const size_t cur = fCursorIX; //
   std::vector<string> result;
   gInterpreter->CodeComplete(line, cur, result);
   for(auto& res : result)
   {
       //todo append to output window
   }
}
```

**Comment by bellenot** [comment]
@ferdymercury I updated the PR. Please check and let me know. Thanks!

**Comment by ferdymercury** [comment]
Looks really great, thank you very much.

There is only one issue. The history is not being added. I tracked it down to here:

![image](https://user-images.githubusercontent.com/10653970/108262954-990d7980-7133-11eb-8a03-e76a0c8e9619.png)

The command is about to be added, but the history file name is empty, thus it returns.

`fContext->GetHistory()` on TextInput.cpp has an empty history filename.

I would suggest that, if SetHistAdd() is called, then it would set the default hist file name in the fContext. Or alternatively, a second parameter in the SetHistAdd function in order to set a custom hist file name.

**Comment by bellenot** [comment]
Yes, I know, but since this is quite a high level change, I don't think I will introduce it in the `TGCommandPlugin` class. You should do that in your own application. For example, you can simply copy and paste what is done in `TRint.cxx`:
```
   // Goto into raw terminal input mode
   char defhist[kMAXPATHLEN];
   snprintf(defhist, sizeof(defhist), "%s/.root_hist", gSystem->HomeDirectory());
   logon = gEnv->GetValue("Rint.History", defhist);
   // In the code we had HistorySize and HistorySave, in the rootrc and doc
   // we have HistSize and HistSave. Keep the doc as it is and check
   // now also for HistSize and HistSave in case the user did not use
   // the History versions
   int hist_size = gEnv->GetValue("Rint.HistorySize", 500);
   if (hist_size == 500)
      hist_size = gEnv->GetValue("Rint.HistSize", 500);
   int hist_save = gEnv->GetValue("Rint.HistorySave", 400);
   if (hist_save == 400)
      hist_save = gEnv->GetValue("Rint.HistSave", 400);
   const char *envHist = gSystem->Getenv("ROOT_HIST");
   if (envHist) {
      hist_size = atoi(envHist);
      envHist = strchr(envHist, ':');
      if (envHist)
         hist_save = atoi(envHist+1);
   }
   Gl_histsize(hist_size, hist_save);
   Gl_histinit((char *)logon);
```
You can even specify your own history file, if you don't want to use the default.

**Comment by ferdymercury** [comment]
Thank you very much Bertrand for the explanation. I tried with this one-liner in my code, and now it works perfectly:

`Gl_histinit(gEnv->GetValue("Rint.History", gSystem->HomeDirectory()));`

The problem I see if it is not introduced in the plugin is that the SetHistAdd() function has no effect. To avoid confusion, I would suggest to add the following in the documentation:

```
// The function SetHistAdd() is needed for a standalone TApplication to log the TGCommandPlugin commands into a ROOT history file.
// However, this function has no effect if the user does not explictly set on his standalone application the name of the ROOT history file.
// To log into the default ROOT history file, call this on the user-side of the code:
// Gl_histinit(gEnv->GetValue("Rint.History", gSystem->HomeDirectory()));
// Otherwise, replace the argument of Gl_histinit with a text file name you want to use for application-specific logging.
```

After that addition, it looks great and ready to merge in my opinion :)

**Comment by bellenot** [comment]
Right, I agree, I will add those lines in the doc. Thanks!
