### ISSUE TITLE
RDataFrame Snapshot of friend trees

### ISSUE THREAD

**Issue by dudarboh** [root-project/root#7181]
### Encountered problem
Snapshoting the RDataFrame with friend trees does not store variables of the friends.
This is very unfortunate for skimming multiple friend trees if the skimming time consuming and running it only once and storing results would help.

### Feature that could help
Automatically store friend trees / variables into the output file.

### Current workaround
Defining all branches explicitly in the Snapshot argument is very clumsy.

### Additional context
This was briefly discussed on the forum [here](https://root-forum.cern.ch/t/snapshot-friend-trees-after-filtering/43507)

**Comment by eguiraud** [comment]
Thank you for creating the issue, there are a few higher-priority items I'd like to get done before releasing 6.24, then I will look at this. I.e. I totally agree we want this, let's see if I make it for this release or not.

In case someone feels like giving this a shot: the relevant logic is at the following line, `GetTopLevelBranchNames` should also return the names of friend branches:

https://github.com/root-project/root/blob/0399cde3718b2571ad4a4d2285bbc563c9b9453e/tree/dataframe/inc/ROOT/RDF/RInterface.hxx#L521

**Comment by eguiraud** [comment]
While writing a regression test for this, I realized that friend branches, which are called e.g. `tree2.x`, will be saved as `tree2_x` (`Snapshot` always converts dots to underscores when writing out variables -- and in this case writing it as `tree2.x` would be fairly confusing (the `.` has semantic meaning in other cases). So I think that's the best we can do.

**Comment by eguiraud** [comment]
@dudarboh as far as I can tell, `Snapshot` already works for branches in the friend tree that are not present in the main tree.

I guess in your case the branches in the friend and in the main tree have the same names?

**Comment by dudarboh** [comment]
> 
> 
> @dudarboh as far as I can tell, `Snapshot` already works for branches in the friend tree that are not present in the main tree.
> 
> I guess in your case the branches in the friend and in the main tree have the same names?

Yes. This was an important detail I forgot to add
