### ISSUE TITLE
TBrowser get stuck when too many files/directories are presented in the upper directories

### ISSUE THREAD

**Issue by ShamrockLee** [root-project/root#7213]
- [X] Checked for duplicates

### Describe the bug

When `TBrowser` is opened, all the child items (files and folders) of the super-directories will be shown. This cause it to get stuck when one of them contains a huge amount of files and directories.

### Expected behavior

`TBrowser` is opened smoothly without being overwhelmed by the upstream folders.

Possible solutions include:
* Provide an option not to follow the symlink
* Provide an option to specify the number of super-directory to show

These solution would require changes of User Interface or even the TBrowser API, but it might be useful when moving the files to somewhere with thinner directory tree is inconvenient/impossible.

### To Reproduce

Easy:

1. `cd` into a temporary directory (`/dev/shm` would be convenient)
2. ```bash
   mkdir testdir
   cd testdir
   for i in {1..100000}; do mkdir $i; done
   cd 50000
   cp /path/to/root/tutorial/hsimple.root .
   root
   ```
3. Inside the ROOT interpreter,
   ```ROOT
   TBrowser tb
   ```

Practical:
1. Install [Nix package manager](https://nixos.org/) by executing the installation script, by setting up a NixOS, or by using the docker image.
2. Fill `/nix/store` with packages by installing packages, `nix-shell` or `nix-build`
2. Install ROOT by `nix-env -iA root`
3. ```bash
   cd ~/.nix-profile/tutorials
   root
   ```
4. Inside the ROOT interpreter
   ```ROOT
   TBrowser tb
   ```
 5. Since the `tutorials` is a symlink to `/nix/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-root-6.18.04/tutorials`, `TBrowser` will follow the symlink, try to expand `/nix/store` (where all the packages are stored), and get stuck there.
### Setup

ROOT Version: 6.18/04
Built for linuxx8664gcc on Sep 11 2019, 15:38:23
From tags/v6-18-04@v6-18-04

Installed using nix package manager on NixOS

**Comment by bellenot** [comment]
We had the same kind of issue with network file systems, but I'm afraid that the only solution I see would be to add an entry in `system.rootrc`. I will investigate what can be done

**Comment by bellenot** [comment]
@ShamrockLee there is already a `Browser.ExpandDirectories` entry in `system.rootrc`, you can simply set it to false. Otherwise I can also add something like:
```
   // always prevent expanding the parent directory tree on nix/store
   if (first == "nix" && second == "store")
      expand = kFALSE;
```
But I would prefer not to add such special case...

**Comment by bellenot** [comment]
@ShamrockLee can you tell me if the given solution (setting `Browser.ExpandDirectories` to `false` in `system.rootrc`) is good enough for you? (so I can close this issue). Thanks!

**Comment by ShamrockLee** [comment]
@bellenot Sorry for late reply.

I'm building the nix expression for the solution now. The result will come up later.

(Since `/nix/store/` is read-only, a wrapper is needed to apply the changes on `system.rootrc`.)

**Comment by bellenot** [comment]
FYI, you can also have a `${HOME}/.rootrc` file, being your own, custom version of `system.rootrc`

**Comment by ShamrockLee** [comment]
@bellenot I finally realized that it should be
`Browser.ExpandDirectories: false`
in stead of
`Browser.ExpandDirectories = false`
in `$HOME/.rootrc`

Problem solved. :tada: 

![Screenshot_20210218_233311](https://user-images.githubusercontent.com/44064051/108380300-afa1f680-7241-11eb-9515-57eb35b17cbd.png)

**Comment by bellenot** [comment]
Very good! Thanks for letting me know! 👍
