### ISSUE TITLE
TThread documentation outdated

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#7216]
### Explain what you would like to see improved
The TThread HTML documentation speaks about having to compile with special ./configure flags, see

https://github.com/root-project/root/blob/f8efb11a51cbe5b5152ebef19a4f7b78744ca2fa/documentation/users-guide/Threads.md

### Optional: share how it could be improved
Change it to the corresponding CMake flags, or clarify if it is still needed.

### To Reproduce
Open https://root.cern.ch/root/htmldoc/guides/users-guide/Threads.html and check the "Installation section"

**Comment by eguiraud** [comment]
Hi, I think `TThread` is deprecated in favour of `std::thread` (this is not to say that we shouldn't update its docs).

**Comment by ferdymercury** [comment]
Oh, I see, thanks.

Maybe it would be also interesting then to add a section on how to "migrate" from TThread to std::thread, I would be happy to upgrade my classes if there would be an example on the correspondence between functions.

**Comment by ferdymercury** [comment]
See also https://root-forum.cern.ch/t/error-in-treentrantrwlock-writeunlock-write-lock-already-released-tthread-member-function/43663/6
ROOT::EnableThreadSafety() could be added to the manual.

**Comment by couet** [comment]
By the way, you are referring to the old "User's Guide". This Guide is now out dated. We do not update it anymore. The the two main sources of documentation are the [Reference Guide](https://root.cern/doc/master/index.html) and the [Manual](https://root.cern/manual/). If some update is needed I guess it should be done in the[ reference of TThread](https://root.cern/doc/master/classTThread.html). May be the TThread in the user guide should be updated and move into the reference guide.

**Comment by couet** [comment]
Let see with @pcanal what to do with the doc in the User's Guide . Should it be moved to the Reference Guide ? Ignored ? I am happy to help to do some editing but I do not have the expertise to decide what to do.

**Comment by pcanal** [comment]
> See also [root-forum.cern.ch/t/error-in-treentrantrwlock-writeunlock-write-lock-already-released-tthread-member-function/43663/6](https://root-forum.cern.ch/t/error-in-treentrantrwlock-writeunlock-write-lock-already-released-tthread-member-function/43663/6) ROOT::EnableThreadSafety() could be added to the manual.

I think it is already mentioned toward the end of https://root.cern/manual/multi_threading/

**Comment by ferdymercury** [comment]
Yes, but we meant it would be useful to add also a note or link to it in the Users Guide: https://root.cern.ch/root/htmldoc/guides/users-guide/Threads.html

**Comment by pcanal** [comment]
> what to do with the doc in the User's Guide . Should it be moved to the Reference Guide ? 

Some of the information is still relevant (beside the mention of TThread) in particular 25.2.    The rest looks like it is all not longer recommended to use.
