### ISSUE TITLE
[RF] Pythonisations for RooFit

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#7217]
Many C++-like workflows in RooFit can be beautified on the Python side.
Currently:
```py
pdf.fitTo(data, ROOT.RooFit.Range("sideband"))
```

Propose:
```py
pdf.fitTo(data, range="sideband")
```

Overall, this is not difficult once one figures this out for the first function. Good for e.g. a summer student project. A few candidates that could be pythonised:
- [ ] RooAbsPdf::fitTo
- [ ] RooAbsPdf::chi2FitTo
- [ ] RooAbsReal::plotOn
- [ ] RooAbsPdf::createNLL
- [ ] RooDataHist::RooDataHist
- [ ] RooDataSet::RooDataSet
- [ ] RooAbsPdf::paramOn
- [ ] ...

**Comment by hcmidt** [comment]
Hi,

I am new to root and trying to wrap my head around some of its features. I thought a good place to start would be to work on this issue. I started by pythonizing `fitTo` and I'd like to send you a pull request. I take it that I should provide some tests for the feature, but I could not find any resources regarding the testing conventions in python for root. If there are any specific guidelines, please let me know, otherwise I'll just send you a pull request and you can take a look if it is really necessary.

Cheers

**Comment by hageboeck** [comment]
Hi @hcmidt,

I'm not working on RF, any more, but it's great to see someone offering help!

Regarding tests, see here:
https://github.com/root-project/root/blob/master/bindings/pyroot/pythonizations/test/roodatahist_ploton.py

In this folder, you have all the tests for the Pythonisations. If you have something, include a test here (I guess it makes sense to create a new file for `RooAbsPdf` etc. @etejedor is the expert on PyROOT, so make sure to request him as a reviewer when there's something to look at. And request @guitargeek for the RooFit part as well!

**Comment by hageboeck** [comment]
PS:
Maybe this test is more representative of how a test for a Pythonisation would look like:
https://github.com/root-project/root/blob/master/bindings/pyroot/pythonizations/test/rooabscollection_len.py

And here the corresponding pythonisation:
https://github.com/root-project/root/blob/master/bindings/pyroot/pythonizations/python/ROOT/pythonization/_rooabscollection.py

**Comment by hcmidt** [comment]
Thanks @hageboeck, the pull request is now open.

**Comment by guitargeek** [comment]
To collect some info in this issue, here is the link to an interesting post in the forum that shows an example for why pythonization of the [RooDataSet](https://root.cern.ch/doc/master/classRooDataSet.html#aeea71f616bd2cc6743f6869d31a4dbd5) is really needed:

https://root-forum.cern.ch/t/combining-roodatasets-in-pyroot/43615

**Comment by guitargeek** [comment]
Another Pythonization idea that occured to me in the PR reviews: implement `+=` for RooArgLists.

So instead of doing this:
```Python
l = ROOT.RooArgList()
l.add(x)
l.add(y)
```
One can also do this, just like with Python lists:
```Python
l = ROOT.RooArgList()
l += [x, y]
```

**Comment by etejedor** [comment]
> l += [x, y]

Would it be also interesting to implement `l1 + l2` ?

**Comment by guitargeek** [comment]
The pythonizations suggested in this issue have been implemented, so it can be closed. For any further specific RooFit pythonization ideas, please open a new issue or a PR directly.

**Comment by guitargeek** [comment]
Reopened, because there are new ideas for Pythonizations mentioned in this comment:
https://github.com/root-project/root/issues/11421#issuecomment-1257015302

To quote that comment:

> - sometimes I would have found useful to be able to pass python number anywhere a `RooAbsReal` is required, although I suspect this may require a pythonization for each pdf.
> - `RooSimultaneous` map constructor does not accept a python dictionary yet
> - one thing that surprised me a couple of times at the beginning is that `RooAbsArg` does not keep its servers alive from the python GC so you actually need the same workarounds as in C++ (importing frequently to a workspace).
However, I suspect that if they did keep servers alive, server redirection would likely lead to desync between the C++ and python views of the graph.

**Comment by guitargeek** [comment]
Another idea we discussed in the RooFit developers meeting: often a `RooLinkedList` is used to pass around RooFit command arguments, so it would be nice if it could be implicitly created from a Python dictionary to be used in any function that takes a RooLinkedList.

**Comment by guitargeek** [comment]
The remaining Pythonization suggestions in my last two posts were either implemented or deemed not relevant enough to do so. I'll re-close this issue.
