### ISSUE TITLE
[RF] RDataFrame to RooDataSet/RooDataHist conversion

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#7223]
## Is your feature request related to a problem? Please describe.
You could call it a "problem", yes.

What we want basically is to drop out an RooDataSet directly from RDataFrame. There's two ways to do it:
#### Easy way:
- Create a loopable collection of events that drops out of RDF. Could be a std::vector, a snapshot, etc
- One by one, fill those events into RooDataSet à la https://root.cern/doc/master/rf402__datahandling_8C.html
```c++
   // Fill d with dummy values
   Int_t i;
   for (i = 0; i < 1000; i++) {
      x = i / 50 - 10;
      y = sqrt(1.0 * i);
      c.setLabel((i % 2) ? "Plus" : "Minus");
 
      // We must explicitly refer to x,y,c here to pass the values because
      // d is not linked to them (as explained above)
      d.add(RooArgSet(x, y, c));
   }
```

This is going to be slow, and not so elegant.

#### Requires more development, but better:
- RooDataSet should accept collections when you construct it
- Since data is stored in a `std::vector` internally, it could even `std::swap` with an external vector!
- RDataFrame should directly spit out such a collection or it should be easy to connect the two.
  - It is clear that MT runs are not trivial, but maybe not a priority.
  - @eguiraud what is the easiest to spit out from RDF, which is loopable, maybe even adopt the memory?

**Comment by eguiraud** [comment]
I think you want a dedicated custom action that users can [Book](https://root.cern/doc/master/classROOT_1_1RDF_1_1RInterface.html#a9ed8313806398d106bfc2390301c0408).

In general you can also just `Take` std::vectors (or other collections) out of a RDataFrame.

**Comment by hageboeck** [comment]
Book is good-ish, it would fill the dataset one-by-one, but RF can do better.

I think `Take` is exactly what's needed!

Eventually, this could look like:
```c++
auto rooDataSet = rdf.RooDataSet("datasetname", {"x", "y", "z"});
pdf.fitTo(*rooDataSet);
```
Internally, this would do something like:
```c++
RooRealVar x(...);
RooRealVar y(...);
RooRealVar z(...);

auto xData = rdf.Take("x");
auto yData = rdf.Take("y");
auto zData = rdf.Take("z");

return RooDataSet(datasetname, RooArgSet(x, y, z), {std::move(*xData), std::move(*yData), std::move(*zData)}); // This constructor doesn't exist
```
There is lots of details missing, but that's what it could do eventually. Maybe the `RooRealVars` have to be passed into whatever it is I wrote above, because they have ranges and binnings and labels ...
In general, the thing is just supposed to connect those `RooRealVar` objects with the data that's taken from RDF.

Possible?

**Comment by eguiraud** [comment]
> Book is good-ish, it would fill the dataset one-by-one, but RF can do better.

Uhm, `Book` exposes the exact same mechanics that RDF uses for its own actions like `rdf.RooDataSet`, so anything you would like to do in there, you can do in the helper type you pass to `Book`.

Then it's a small step to go from `df.Book(RooDataSetMaker(...), {"x", "y", "z"})` to `df.MakeRooDataSet`, basically just syntactic sugar.

**Comment by hageboeck** [comment]
Ok, for single value filling, this may be achievable in a few days, nice.

**Comment by hageboeck** [comment]
Reopening, because weights should be tested (and supported). What's needed:
- [x] Creating and filling bare dataset / datahist
- [ ] A way to select the a weight column in RDataFrame, and tell the RooDataHist/RooDataSet instances about what's the weight.
- [ ] Passing of the weight in the `add` call.
- [ ] Test of weighted filling.
