### ISSUE TITLE
Update the copyright year from 2020 to 2021 (good first issue)

### ISSUE THREAD

**Issue by AdvaitDhingra** [root-project/root#7227]
### Explain what you would like to see improved

Update the copyright years from 2020 to 2021

### Optional: share how it could be improved

Someone just needs to go to each file that has Copyright (C) 2020 and change it 2021. 

### Additional context

Add the Good-first-issue label so newcomers have something to do.

**Comment by AdvaitDhingra** [comment]
I'm personally not going to do this, but a newcomer might like to do it as a first issue.

**Comment by etejedor** [comment]
@Axel-Naumann can perhaps reassign.

**Comment by Axel-Naumann** [comment]
That's not how we do this. Any file that receives at least non-trivial edits needs to have the copyright year updated. As such it can be automatized, but it's for now part of the developers' task.
