### ISSUE TITLE
[RF] Use integral of PDF curves for pull plots and residuals

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#7239]
## Explain what you would like to see improved
When using [pullHist](https://root.cern.ch/doc/master/classRooPlot.html#a0d3911db1f4e0ba5cfcf9e182eea3ed0), don't take curve at bin centre, but integrate curve over the bin. That should fix the following pull plot:
| Wrong | Correct |
| ---- | ---- |
| ![oneToy_old](https://user-images.githubusercontent.com/16205615/108328256-acb8ee80-71cc-11eb-9eb1-f3edb2a3b855.png) |  ![oneToy_new](https://user-images.githubusercontent.com/16205615/108328286-b5112980-71cc-11eb-9fa0-67ccba717d9b.png) |

### Optional: share how it could be improved
- Alter this part of the function:
https://github.com/root-project/root/blob/478d84e4035c74d55511a01372e2bd0b7c8b60a7/roofit/roofitcore/src/RooHist.cxx#L777-L787
- Instead of interpolating the curve to the middle of the bin, find the bin edges from RooHist using the x errors. (Note that RooHist inherits from [TGraphAsymErrors](https://root.cern.ch/doc/master/classTGraphAsymmErrors.html)).
- Then, find the corresponding points on the PDF curve.
- Then, [integrate](https://root.cern.ch/doc/master/classTGraph.html#a06b6dfc69d4fe9336ade71a47864f974) the PDF curve from the first to the last point from above step.

### Code to produce such a plot
From [here](https://github.com/hageboeck/rootNotebooks/blob/master/BinSamplingPdf.ipynb)
```c++
RooRealVar x("x", "x", -10, 10);
x.setBins(20);
RooRealVar m("m", "mean",  1.5, -10, 10);
RooRealVar s("s", "sigma", 0.5, -10, 10);
RooGaussian gaus("gaus", "Gaussian distribution", x, m, s);

RooDataSet* dataset = gaus.generate(x, 10000);
RooDataHist binnedDataset("binnedData", "BinnedData", x, *dataset);

TCanvas c("c", "Pull demo", 1200, 800);
c.Divide(2,2);

c.cd(1);
auto frame = x.frame();
dataset->plotOn(frame);
gaus.plotOn(frame);
frame->Draw();

c.cd(3);
auto pulls = frame->pullHist();
pulls->Draw("P");
c.Draw();
```

**Comment by olantwin** [comment]
Thanks @hageboeck ! I will give this a go, when I find some time.

**Comment by etejedor** [comment]
@olantwin do you want this to be assigned to you then?

**Comment by olantwin** [comment]
I can't promise being able to look at this soon, but as long as that is understood, feel free to do so.

**Comment by hageboeck** [comment]
Stop, stop, stop!

It's much easier, all the code is already there! See this:

| `auto pulls = frame->pullHist();` | `auto pulls = frame->pullHist(nullptr, nullptr, true);` |
| ---- | ---- |
| ![canvas-2](https://user-images.githubusercontent.com/16205615/108338626-c2cbac80-71d6-11eb-8858-d239bf1a74ab.png) | ![canvas](https://user-images.githubusercontent.com/16205615/108338402-80a26b00-71d6-11eb-831d-6d815858616a.png) |

So,

## Revised version of what has to happen
- Change the default arguments of [pullHist](https://root.cern.ch/doc/master/classRooPlot.html#a7d216156856479ed6b7952823d987532) and [residHist](https://root.cern.ch/doc/master/classRooPlot.html#a0d3911db1f4e0ba5cfcf9e182eea3ed0) to `average = true`.
- Update documentation to clarify that by default, the curve will be integrated over all bins.
- Mention the change in the [Release notes](https://github.com/root-project/root/blob/master/README/ReleaseNotes/v624/index.md)

**Comment by guitargeek** [comment]
Thanks @hageboeck! I'll take care of it.

**Comment by olantwin** [comment]
Thanks Jonas, Stephan!
