### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by meena382** [root-project/root#7256]
#5  __cxxabiv1::__dynamic_cast (src_ptr=0x7fffd5147510, src_type=0x7f1637f9b028 <typeinfo for TObject>, dst_type=0x7f162ae18df0 <typeinfo for RooAbsArg>, src2dst=0) at ../../../../libstdc++-v3/libsupc++/dyncast.cc:68
#6  0x00007f162ac6a00e in RooLinkedList::Add(TObject*, int) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libRooFitCore.so
#7  0x00007f162ab62f3b in RooAbsCollection::add(RooAbsArg const&, bool) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libRooFitCore.so
#8  0x00007f162abcfe1d in RooArgSet::RooArgSet(RooAbsArg const&, RooAbsArg const&, RooAbsArg const&, char const*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libRooFitCore.so
#9  0x00007f16380570c7 in ?? ()
#10 0x00007fffd5136ff8 in ?? ()
#11 0x00000000066a53f8 in ?? ()
#12 0x00007f163591d370 in clang::DeclContextLookupResult::SingleElementDummyList () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#13 0x0000000003eb3e90 in ?? ()
#14 0x00000000066a53f8 in ?? ()
#15 0x00007f1635197480 in clang::DeclContext::isDependentContext() const () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#16 0x000000003388f98c in ?? ()
#17 0x0000000000678d18 in ?? ()
#18 0x00000000066a53f8 in ?? ()
#19 0x000000000065cef0 in ?? ()
#20 0x00007f16337b758d in clang::CodeGeneratorImpl::HandleTagDeclDefinition(clang::TagDecl*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#21 0x0000000000000000 in ?? ()
================================

**Comment by etejedor** [comment]
@meena382 could you please add a proper issue message? When you open an issue, there's a template that you can follow. Here we just see partially a stack trace.

**Comment by etejedor** [comment]
@meena382 I suggest that you open a new issue, please follow the template and provide a proper description, thank you very much!
