### ISSUE TITLE
RDataFrame is slow

### ISSUE THREAD

**Issue by dcervenkov** [root-project/root#7273]
### Explain what you would like to see improved

I prepared two short MWEs assigning bin numbers to events in a dataset of 10000 events and printing the number of events in each bin. One is C++ using `RDataFrame`, the other is Python using Pandas. The Pandas one is 3x faster; see the output from `hyperfine`.

```
Benchmark #1: ./mwe ../data/D0_sample_5.root
  Time (mean ± σ):      1.338 s ±  0.010 s    [User: 1.233 s, System: 0.093 s]
  Range (min … max):    1.321 s …  1.349 s    10 runs
```
```
Benchmark #1: python3 mwe.py ../data/D0_sample_5.root
  Time (mean ± σ):     431.3 ms ±   4.6 ms    [User: 469.8 ms, System: 153.6 ms]
  Range (min … max):   423.9 ms … 436.5 ms    10 runs
```

This is the first time I attempted to use `RDataFrame` and I might very well be doing it wrong. Advice would be appreciated.

### To Reproduce

1. Download [D0_sample_5.root](http://ipnp.cz/~cervenkov/data/D0_sample_5.root) (1.6MB)
2. Compile `RDataFrame` MWE using `g++ mwe.cc $(root-config --cflags) $(root-config --glibs) -o mwe`
3. Run `./mwe D0_sample_5.root` and `python3 mwe.py D0_sample_5.root`

#### `mwe.cc`:
```cpp
#include <iostream>
#include <vector>

#include "ROOT/RDataFrame.hxx"

int which_time_bin(const double time) {
    const double bin_edges[] = {0,           0.00025 * 1, 0.00025 * 2,
                                0.00025 * 3, 0.00025 * 4, 0.00025 * 5,
                                0.00025 * 6, 0.00025 * 7, 0.00025 * 8};
    int bin = -1;
    for (int i = 0; i < 9; i++) {
        if (time < bin_edges[i])
        return bin;
        bin++;
    }
    return bin;
}

int main(int argc, char *argv[]) {
    ROOT::RDataFrame df_raw("DalitzEventList", argv[1]);
    auto df = df_raw.Define("time_bin", which_time_bin, {"D_decayTime"});

    const int time_bins = 8;
    ROOT::RDF::RResultPtr<ULong64_t> counts[time_bins];
    std::string cut;
    for (int time_bin = 0; time_bin < time_bins; time_bin++) {
        cut = "time_bin == ";
        cut += std::to_string(time_bin);
        counts[time_bin] = df.Filter(cut).Count();
    }

    for (int time_bin = 0; time_bin < time_bins; time_bin++) {
        std::cout << *counts[time_bin] << std::endl;
    }

    return 0;
}
```

#### `mwe.py`:
```python
import uproot
import pandas as pd
import sys

df = uproot.open(sys.argv[1])["DalitzEventList"].arrays(library="pd")
time_bin_edges = [0.00025 * i for i in range(9)]
df["time_bin"] = pd.cut(
    df["D_decayTime"],
    time_bin_edges,
    include_lowest=True,
    labels=range(len(time_bin_edges) - 1),
)
print(df.groupby("time_bin").size())
```

### Setup

ROOT 6.22.06
Linux 5.4.0, Ubuntu 18.04-like
Binary download of ROOT

**Comment by eguiraud** [comment]
Hi @dcervenkov , I believe you are counting the time spent just-in-time compiling ("jitting") the cuts as if it was part of the event loop: RDataFrame, when strings are used as filters or defines, has a non-negligible start-up time because it's actually compiling those strings into C++ code. With ROOT master branch (and in v6.24, coming soon), you can retrieve the jitting time and the event loop time separately by adding the following line at the beginning of `main`:

```cpp
auto verbosity = ROOT::Experimental::RLogScopedVerbosity(ROOT::Detail::RDF::RDFLogChannel(), ROOT::Experimental::ELogLevel.kInfo);
```

Here is a version without jitting that should run faster than the python version (make sure to add `-O2` to the compilation flags though -- C++ code needs those sweet compiler optimizations):

```cpp
#include <iostream>
#include <vector>

#include "ROOT/RDataFrame.hxx"

int which_time_bin(const double time) {
    const double bin_edges[] = {0,           0.00025 * 1, 0.00025 * 2,
                                0.00025 * 3, 0.00025 * 4, 0.00025 * 5,
                                0.00025 * 6, 0.00025 * 7, 0.00025 * 8};
    int bin = -1;
    for (int i = 0; i < 9; i++) {
        if (time < bin_edges[i])
        return bin;
        bin++;
    }
    return bin;
}

int main(int argc, char *argv[]) {
    ROOT::RDataFrame df_raw("DalitzEventList", argv[1]);
    auto df = df_raw.Define("time_bin", which_time_bin, {"D_decayTime"});

    const int time_bins = 8;
    ROOT::RDF::RResultPtr<ULong64_t> counts[time_bins];
    for (int time_bin = 0; time_bin < time_bins; time_bin++) {
        counts[time_bin] = df.Filter([=](int tb) { return tb == time_bin; }, {"time_bin"}).Count();
    }

    for (int time_bin = 0; time_bin < time_bins; time_bin++) {
        std::cout << *counts[time_bin] << std::endl;
    }

    return 0;
}
```

For larger datasets, with `RDataFrame` you can also easily run on multiple threads by adding `ROOT::EnableImplicitMT()` which will provide further speed-ups. For these few datapoints it won't really be beneficial.

**Comment by eguiraud** [comment]
On my workstation:

```
original C++: ~1.6s
original Python: ~0.54s
C++ without jitting: ~0.38s
```

**Comment by dcervenkov** [comment]
Hi @eguiraud, awesome! It would be great if a filter example similar to `df.Filter([=](int tb) { return tb == time_bin; }, {"time_bin"}).Count();` could be added to the docs (or is it already there and I missed it?).

**Comment by eguiraud** [comment]
@dcervenkov sorry for never replying, please feel free to suggest improvements to the docs via another issue or even better a pull request :smile:
