### ISSUE TITLE
Update User's Guide pdf

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7279]
### Describe the bug
PDF of the User's Guide downloaded from https://root.cern/d/guides/users-guide.html is outdated. On the title page it shows the date of May 2018. On the html page of TTree in User's Guide I can see that it has changed since that time (which is not reflected in the pdf version).

I looked for other reports, but they were either closed or referred to a part of the Guide, not the complete document.

### Expected behavior
PDF and HTML documentation should be in sync. Maybe you should try Readthedocs? They have a nice system to store various formats of documentation even for different program versions.

**Comment by ynikitenko** [comment]
Could you please make the file name to contain the ROOT version? When I download "Complete User's Guide in A4 format" from http://root.cern.ch/root/htmldoc/guides/users-guide/ROOTUsersGuideA4.pdf, I've no idea whether it was changed in 2018 or in 2021.

**Comment by couet** [comment]
The ROOT user guide is consider as frozen and the "d" URL should not be considered. This ia a copy of the old web site.
The new web site is: https://root.cern

**Comment by ynikitenko** [comment]
@couet - it seems that the html version is still updated. What do you mean by "The ROOT user guide is consider as frozen"? Do you plan to stop supporting it?

I still find it the best documentation about ROOT. This is pretty detailed and written better than class documentation would be (this is a manual for reading, not a technical reference of existing functions).

**Comment by couet** [comment]
It has not been updated since a long time ... and new feature like RDataFrame are not in it ....And yes we do not put any effort into it. See: https://root.cern/manual/. This is the top page of the ROOT documentation now. On the opposite the ref-guide (class doc) is constantly updated ....

**Comment by couet** [comment]
See explanation about the User's Guide here: https://github.com/root-project/root/issues/7284

**Comment by ynikitenko** [comment]
I submitted several corrections to the Guide on https://github.com/root-project/root/issues/7284, but that was closed - so probably this one should be closed too if you don't intend to update the User's Guide.

**Comment by couet** [comment]
Yes I close it.
