### ISSUE TITLE
Trailing dot dropped in top level branch name

### ISSUE THREAD

**Issue by pcanal** [root-project/root#7281]
See https://root-forum.cern.ch/t/root-6-23-changing-name-of-branch-with-tclonesarray/43626/4

A recent change to improve GetBranch's behavior lead to an improvement of the sub-branch name but also (inadvertently?) to a change of the top level name.  We need to either confirm that we want to change or revert the top level name part.

**Comment by eguiraud** [comment]
Hi, please add a "fixed in" project to this issue

**Comment by pcanal** [comment]
A a side note, the "fixed in" is a bit misleading here ... because the bug does not exist in any tagged version :)
