### ISSUE TITLE
Refactor links hierarchy of the site, including documentation links

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7282]
Today I searched for User's guide on the site, and wanted to share several ideas for improvement.

1\) Remove duplicate links.
In modern Web Development it's appreciated that same content has only one link on the site, and a link is meaningful in itself (see Django guidelines).
For example: from the main page I can see a link to the documentation,
https://root.cern/d/documentation.html
If I delete the last part, I get
https://root.cern/d/
which is a) meaningless b) same as the main page. 
The third link to that same page is 
https://root.cern/d/index.html

Surprisingly, the link
https://root.cern/index.html
has different contents!

Probably there is little surprise that there exists the 2nd version of the site,
https://root.cern.ch/ (with its own index.html, and all these links).
I think there should be one canonical link, and other links should redirect to that. 

2a) https://root.cern/d/documentation.html 
should ideally become just 
https://root.cern/documentation

2b) or all documentation should be put into one directory with a clearer name, like
https://root.cern/doc/
In that case the manual (and other docs) should also be in that directory, not at
https://root.cern/manual/

3a) User Guide is located at
https://root.cern/d/guides/users-guide.html
On parent path
https://root.cern/d/guides/
there is an automatic list of guides (which is better than nothing/forbidden), but it would be better if it was not automatic (had the same design as the other site).

3b) the same for
https://root.cern/doc/
(automatic list)

4\) As I understand, the main page for documentation is
https://root.cern.ch/d/documentation.html
There is also
https://root.cern/doc/master/
these two pages should probably be one page.

5\) Rearrange "Provide your feedback"
I think github issues should go before the Forum in the list of options (if there are really two ways), because one can see closed and open issues (on the Forum I found several complaints about the links, but it's not clear whether they are open or closed without opening them).

6\) From the documentation page "A number of topical User Guides and Manuals for various components of the system." leads to
https://root.cern/get_started/
which, in turn, repeats description of some existing resources. Could you please refactor these two pages into one, trying to repeat as little information as possible?

7\) On the page https://root.cern/about/
there is no link to the documentation. This is some other version of the site, not the version at https://root.cern/d/

8\) I found this page using the search window,
https://root.cern/d/root-user-guides-and-manuals.html
I think this is a very good reference page for documentation. Could you link this from the main documentation overview page?  (or just use this page instead of that)

**Comment by ynikitenko** [comment]
https://root.cern/root/htmldoc/guides/users-guide/Trees.html
\- probably should be in the documentation hierarchy.
https://root.cern/root/
\- an absolutely empty page (check other pages on that path though).

**Comment by couet** [comment]
https://root.cern/d/ is the old web site and should not be taken into account.

**Comment by ynikitenko** [comment]
I think that since you own and support these two sites, and they can be found, this report is valid.
I can see that you assigned a person for this issue - does it mean you accept that?
Or should I move this issue to the ROOT site repository?

**Comment by couet** [comment]
Johannes is the person who initiate the new Manual structure. Yes this issue would better apply on the ROOT site repository.  May be we can close it here in that case ?

**Comment by ynikitenko** [comment]
1) I spent some time to show that your site structure is bad for users and wrote that in details and with links.
2) When I made an issue, it was not suggested on the site or here that I should make it in another repository.
I think that to show some respect to people who signal issues and to your project would be for you to at least copy this issue to the appropriate repository.

**Comment by couet** [comment]
Ok I will.
Yes tardy we made an issue to remember to check the TTree User's Guide

**Comment by couet** [comment]
I asked you to make it yourself because if I do it the authorship will be my ... you will lost the authorship. Is it ok for you ?

**Comment by couet** [comment]
Ok done. https://github.com/root-project/web/issues/510 I put your name on top.

**Comment by ynikitenko** [comment]
I see. Thank you! I subscribed to notifications there.
I don't care much about the authorship. I was confused by the current sites structure, and if when I visit the site next year all is clear, I will be glad! :)

**Comment by couet** [comment]
Ok ;-)
