### ISSUE TITLE
Allow ROOT to work with both Python 2 and 3 

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7289]
### Is your feature request related to a problem? Please describe.
When I run 

    $ python -c 'import ROOT'

in Python 3.9.1 on Arch Linux with ROOT 6.20/02, I get an error

> ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  ccache  -O2 -DNDEBUG -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
With exit code 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/root/cur/lib/ROOT.py", line 24, in <module>
    import cppyy
  File "/opt/root/cur/lib/cppyy.py", line 61, in <module>
    import libPyROOT as _backend
ImportError: dynamic module does not define module export function (PyInit_libPyROOT)

I found a post on ROOT Forum that ROOT can only be compiled to support Python 2 OR Python 3.
People suppose that this is [a limitation of the build and the way the bindings are created](https://root-forum.cern.ch/t/pyroot-import-error-pyinit-libpyroot/16263/11).

### Describe the solution you'd like
The solution could be:
- to make bindings work both for Python 2 and 3, or
- to allow separate compilation for Python 2 and 3 in one ROOT installation (preferably created by default during the installation, not when the need arises).

### Additional context

I'm not sure whether this is a feature request or an improvement. As I wrote, this was already suggested, but I searched the Jira and the issues here, and didn't find a ticket for this. I think this would be better to fix this request as an issue (so it's not lost on the forum).

**Comment by etejedor** [comment]
I'm glad to say that MultiPython ROOT is already a feature since 6.22 :smiley: 

You can find information on how to build ROOT for both Python2 and Python3 here:
https://root.cern/install/build_from_source/#root-python-and-pyroot

By default, if CMake finds both a Python2 and a Python3 installation in the system, PyROOT will be built for both Python versions.

**Comment by ynikitenko** [comment]
Excellent, I'm very glad about this! I'll try this ASAP.

**Comment by smuzaffar** [comment]
sorry to hijack this issue, I am trying to build latest root 6.22 with python2 only but I get build errors [a]. cmake is configured to use python2 [b]. Any idea why it fails to build? 

[a]
```
FAILED: bindings/pyroot/cppyy/CPyCppyy/CMakeFiles/cppyy2_7.dir/src/CPPDataMember.cxx.o
/build/muz/dqm/w/slc7_amd64_gcc630/external/gcc/6.3.0/bin/g++  -Dcppyy2_7_EXPORTS -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/core/foundation/inc -I/build/muz/dqm/w/slc7_amd64
_gcc630/external/python/2.7.13-comp2/include/python2.7 -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/bindings/pyroot/cppyy/CPyCppyy/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc63
0/lcg/root/6.22.07/root-6.22.07/bindings/pyroot/cppyy/CPyCppyy/src -Iginclude -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/core/base/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc
630/lcg/root/6.22.07/root-6.22.07/core/cont/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/core/gui/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.
07/core/meta/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/core/clib/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/core/rint/inc -I/build/muz/
dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/core/zip/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/core/thread/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630
/lcg/root/6.22.07/root-6.22.07/core/textinput/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/core/base/v7/inc -I/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root
-6.22.07/core/unix/inc -D__ROOFIT_NOBANNER -std=c++1z -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -O3 -DNDEBUG -fPIC   -Wno-shadow -Wno-strict-aliasing -Wno-unused-but-set-paramet
er -Wno-register -std=c++1z -MD -MT bindings/pyroot/cppyy/CPyCppyy/CMakeFiles/cppyy2_7.dir/src/CPPDataMember.cxx.o -MF bindings/pyroot/cppyy/CPyCppyy/CMakeFiles/cppyy2_7.dir/src/CPPDataMember.cxx.o.d -o b
indings/pyroot/cppyy/CPyCppyy/CMakeFiles/cppyy2_7.dir/src/CPPDataMember.cxx.o -c /build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/bindings/pyroot/cppyy/CPyCppyy/src/CPPDataMember.cxx
In file included from /build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/bindings/pyroot/cppyy/CPyCppyy/src/CPPDataMember.cxx:6:0:
/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.h:36:30: error: 'PyObject* CPyCppyy::CreateLowLevelView' redeclared as different kin
d of symbol
 CPPYY_DECL_VIEW_CREATOR(std::byte);
                              ^
/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.h:29:34: note: in definition of macro 'CPPYY_DECL_VIEW_CREATOR'
     PyObject* CreateLowLevelView(type*,  Py_ssize_t* shape = nullptr);       \
                                  ^~~~
/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.h:30:15: note: previous declaration 'PyObject* CPyCppyy::CreateLowLevelView(unsigned
 char**, Py_ssize_t*)'
     PyObject* CreateLowLevelView(type**, Py_ssize_t* shape = nullptr)
               ^
/build/muz/dqm/w/BUILD/slc7_amd64_gcc630/lcg/root/6.22.07/root-6.22.07/bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.h:34:1: note: in expansion of macro 'CPPYY_DECL_VIEW_CREATOR'
 CPPYY_DECL_VIEW_CREATOR(unsigned char);
 ^~~~~~~~~~~~~~~~~~~~~~~
``` 

[b]
```
-- Looking for Python
-- Found Python2: /build/muz/dqm/w/slc7_amd64_gcc630/external/python/2.7.13-comp2/bin/python (found version "2.7.13") found components: Interpreter Development NumPy
-- ROOT default compression algorithm: zlib
-- PyROOT will be built for version 2.7.13
```

**Comment by smuzaffar** [comment]
looks like issue is with gcc 6.3.0 version

**Comment by etejedor** [comment]
Hi @smuzaffar sorry for the late reply. I believe the issue here is that the build is compiled with C++17 (-std=c++1z), which enables some code that uses `std::byte` in cppyy, but gcc 6.3.0 did not have support for it, it was only introduced in gcc 7:

https://gcc.gnu.org/gcc-7/changes.html
