### ISSUE TITLE
Add an option to disable TBB warning of specific type

### ISSUE THREAD

**Issue by mrodozov** [root-project/root#7291]
Dears,

we are having excessive number of warnings coming from ROOT of this type:
```
%MSG-i Root_Information:  DTGeometryValidate:valid@ctor TThreadExecutor::ParallelFor() 22-Feb-2021 23:50:26 CET pre-events
tbb::global_control is limiting the number of parallel workers. Proceeding with 1 threads this time
```
see, https://github.com/cms-sw/cmssw/issues/32977 . 
The warnings are as described but this is an intentional limitation in CMSSW (as from what I understood)
One possibility we discussed was to ask ROOT devs to put a cmake flag to silence it or anything similar you can propose (such that we turn it on and the warning disappears)

Please see the issue on cmssw for more info

**Comment by oshadura** [comment]
@mrodozov I am not sure it is a 'pure' build system issue (I started a discussion in https://github.com/cms-sw/cmssw/issues/32977#issuecomment-786503374). Adding in CC: @eguiraud @Axel-Naumann

**Comment by eguiraud** [comment]
See my suggestion [here](https://github.com/cms-sw/cmssw/issues/32977#issuecomment-786549791), as mentioned the warnings are desired and correct (although for some reason cmssw is triggering too many of them), so the best fix would be one that gets rid of the warnings rather than silence them.

**Comment by mrodozov** [comment]
closing this
