### ISSUE TITLE
compilation fails on xrootd: _STAT_VER was not declared 

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7292]
### Describe the bug
I'm installing the most recent ROOT 6.22.06 from source archive on Arch Linux. At progress around 60% the compilation fails suggesting to look for details in 

    XROOTD-prefix/src/XROOTD-stamp/XROOTD-build-err.log

> CMake Error at /opt/root/build-root-6.22.06/XROOTD-prefix/src/XROOTD-stamp/XROOTD-build-Release.cmake:49 (message):
  Command failed: 2
   '/usr/bin/make'
  See also
    /opt/root/build-root-6.22.06/XROOTD-prefix/src/XROOTD-stamp/XROOTD-build-*.log
  make[2]: *** [CMakeFiles/XROOTD.dir/build.make:131: XROOTD-prefix/src/XROOTD-stamp/XROOTD-build] Error 1 
  make[1]: *** [CMakeFiles/Makefile2:7256: CMakeFiles/XROOTD.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....

The file contains this infomation:

> [I] No git repository info found. Trying to interpret VERSION_INFO
[I] src/XrdVersion.hh successfully generated
/opt/root/build-root-6.22.06/XROOTD-prefix/src/XROOTD/src/XrdPosix/XrdPosix.cc: In function ‘int XrdPosix_Fstat(int, stat*)’:
/opt/root/build-root-6.22.06/XROOTD-prefix/src/XROOTD/src/XrdPosix/XrdPosix.cc:379:27: error: ‘_STAT_VER’ was not declared in this scope
  379 |           : Xunix.Fstat64(_STAT_VER, fildes, (struct stat64 *)buf));
      |                           ^~~~~~~~~
/opt/root/build-root-6.22.06/XROOTD-prefix/src/XROOTD/src/XrdPosix/XrdPosix.cc: In function ‘int XrdPosix_Lstat(const char*, stat*)’:
/opt/root/build-root-6.22.06/XROOTD-prefix/src/XROOTD/src/XrdPosix/XrdPosix.cc:563:27: error: ‘_STAT_VER’ was not declared in this scope
  563 |           ? Xunix.Lstat64(_STAT_VER, path, (struct stat64 *)buf)
      |                           ^~~~~~~~~
/opt/root/build-root-6.22.06/XROOTD-prefix/src/XROOTD/src/XrdPosix/XrdPosix.cc: In function ‘int XrdPosix_Stat(const char*, stat*)’:
/opt/root/build-root-6.22.06/XROOTD-prefix/src/XROOTD/src/XrdPosix/XrdPosix.cc:891:26: error: ‘_STAT_VER’ was not declared in this scope
  891 |           ? Xunix.Stat64(_STAT_VER, path, (struct stat64 *)buf)
      |                          ^~~~~~~~~
make[5]: *** [src/CMakeFiles/XrdPosixPreload.dir/build.make:108: src/CMakeFiles/XrdPosixPreload.dir/XrdPosix/XrdPosix.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:1838: src/CMakeFiles/XrdPosixPreload.dir/all] Error 2
make[3]: *** [Makefile:149: all] Error 2

I [disabled xrootd](https://root-forum.cern.ch/t/build-problem-with-xrootd-on-root-v6-22-00/40255/7) as was suggested on the forum with

    cmake -Dxrootd=OFF -Dbuiltin_xrootd=OFF <source_dir>

### Expected behavior
`xrootd` should compile or, if it's not needed, be optional (not default). I'm not sure whether I need that.

### To Reproduce
1. Download and unpack a source .tar.gz, create and cd the build directory.
2. cmake --build . --target install -- -j15

### Setup
1. 6.22.06
2. Arch Linux.
3. Source package from site, root_v6.22.06.source.tar.gz 

### Additional context
There exist reports on xrootd, but not connected to this variable.
I have to say that I failed to compile without xrootd, but it is probably another issue.

**Comment by linev** [comment]
I see same problem.  It is connected with libc changes:
https://github.com/bminor/glibc/commit/8ed005daf0ab03e142500324a34087ce179ae78e
Unfortunately, latest 4.x XROOTD 4.12.6 does not solve the problem.
I guess, it is blocker for the release

**Comment by Axel-Naumann** [comment]
IIUC that should have been addressed by https://github.com/xrootd/xrootd/commit/1f2d48fa23ba220ce92bf8ec6c15305ebbf19564 part of Xrootd 5.0.3 https://github.com/xrootd/xrootd/issues/1321

I don't see that commit in the 5.1 branch. @simonmichal is my diagnosis ccorrect?

**Comment by linev** [comment]
@Axel-Naumann 
Seems to be xrootd 5.1 fine in this respect - I can build it normally.
After small adjustments we need to apply https://github.com/root-project/root/pull/7335

**Comment by simonmichal** [comment]
Yes, the patch is included in 5.1.x series: https://github.com/xrootd/xrootd/commit/5298c732c394d7ac3c24abc7d01a4631f573e692, I has been also bckported to XRootD4 in 4.12.8

**Comment by linev** [comment]
@simonmichal Does xrootd 4.12.8 was released? I cannot find such release on https://xrootd.slac.stanford.edu/
And also not on https://lcgpackages.web.cern.ch
@oshadura May be 4.12.8 would be better choice for ROOT 6.24 release?

**Comment by simonmichal** [comment]
@linev : yes it has been tagged: https://github.com/xrootd/xrootd/releases/tag/v4.12.8 (it seems I must have forgotten to send an announcement, my apologies), I would recommend though going for XRootD5, we are currently backporiting patches to XRootD4 not proactively but only on user request

**Comment by linev** [comment]
Latest xrood 4.12.8 merged into master, 6.24 and 6.22 branches and fixes compilation problem.
Upgrade to xroot 5.1 needs more investigation
