### ISSUE TITLE
Installation fails with libvectorDict.so: no such file or directory

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7293]
### Describe the bug
I'm installing the most recent ROOT 6.22.06 from a source archive on Arch Linux. At the install phase (progress 100%) the compilation fails with

> CMake Error at core/clingutils/cmake_install.cmake:56 (file):
  file INSTALL cannot find
  "/opt/root/build-root-6.22.06/lib/libvectorDict.so": No such file or
  directory.
Call Stack (most recent call first):
  core/cmake_install.cmake:75 (include)
  cmake_install.cmake:200 (include)
make: *** [Makefile:148: install] Error 1

I had `libvectorDict.so` from the previous installation (also it is present at /usr/lib/root/libvectorDict.so, I don't know why), so I linked that file to the needed one

    ln -s `realpath ../build-root-6.20.02/lib/libvectorDict.so` lib/

it was linked fine (existed). However, when I re-run `cmake`, it outputs the same error and the file is removed.

I found that it's possible to [generate this file separately](https://root-forum.cern.ch/t/root-6-22-02-installation-error-cannot-find-libvectordict-so/42162/9) with

    cmake --build . -- vectorDict 

However, I can't be sure that this makes it a good installation (when I run `cmake --build . --target install -- -j15` after that, it fails to find the file again). `root` binary exists and can be run, so I hope it solves the problem for me.

### Expected behavior
`cmake` should not delete this file.

### To Reproduce
1. Download and unpack a source .tar.gz, create and cd the build directory.
2. cmake -Dxrootd=OFF -Dbuiltin_xrootd=OFF <source_dir> (I had to got rid of `xrootd` as I wrote in [another issue](https://github.com/root-project/root/issues/7292)).
3. cmake --build . --target install -- -j15

### Setup
1. 6.22.06
2. Arch Linux.
3. Source package from site, root_v6.22.06.source.tar.gz

### Additional context
There are really many reports with this problem. An existing issue most close to this may be https://github.com/root-project/root/issues/7108 (it was suggested by git search).
1. https://root-forum.cern.ch/t/installation-issues-of-new-version-root-6-06-00/20523/8
2. https://root-forum.cern.ch/t/error-file-install-can-not-find/37552
3. https://root-forum.cern.ch/t/error-with-libvectordict-so/39097
4. https://root-forum.cern.ch/t/root-6-22-02-installation-error-cannot-find-libvectordict-so/42162

**Comment by ynikitenko** [comment]
I found that I also had ROOT installed by Arch Linux package manager (that's why the file was in /usr/lib/root).

**Comment by mhemmer-cern** [comment]
I just tried to install root5 and encountered the same problem. Since this issue is from 2021, is there a known solution?

**Comment by dpiparo** [comment]
I am closing this issue. ROOT5 is not supported any more: we are happy to give a hand to migrate to ROOT 6 where necessary. Moreover it seems the original issue was due to a misconfiguration somewhere in the installations on the machine.
