### ISSUE TITLE
Errors during the generation of html docs; no TTree docs generated

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7295]
- [x ] Checked for duplicates

### Describe the bug
I'm trying to generate html documentation for ROOT. Most files are created, but it reports several issues:

> Warning in <THtml::CreateListOfClasses>: Cannot find the header for the following classes [reason]:
Warning in <THtml::CreateListOfClasses>:    TVirtualPaveStats [header TVirtualPaveStats.h not found]
Warning in <THtml::CreateListOfClasses>: THtml cannot find all headers and sources. 
Warning in <THtml::CreateListOfClasses>: You might need to adjust the input path (currently ./:src/:include/:/opt/root/cur) by calling THtml::SetInputDir()
Warning in <THtml::CreateListOfClasses>: Product not set. You should call gHtml->SetProduct("MyProductName");

> 578 htmldoc/ROOT__Math__IParametricGradFunctionMultiDimTempl_double_.html
Error: segment [(31.517,476.17),(22,480)] does not intersect box ll=(22,328),ur=(70,681)
dot: compound.c:78: boxIntersectf: Assertion `0' failed.
Error in <TClassDocOutput::RunDot>: Error running dot -q1 -Tpng -ohtmldoc/inhmem/ROOT__Math__IParametricGradFunctionMultiDimTempl_double__InhMem.png -Tcmap -ohtmldoc/inhmem/ROOT__Math__IParametricGradFunctionMultiDimTempl_double__InhMem.map htmldoc/inhmem/ROOT__Math__IParametricGradFunctionMultiDimTempl_double__InhMem.dot!

Which is worse, it doesn't create html documentation for TTree (and it's missing in the index). 

I try to generate it separately:

    root [4] h.SetInputDir("$(ROOTSYS)");
    root [5] h.MakeClass("TTree");

> Info in <THtml::CreateListOfClasses>: Initializing - DONE.
Error in <THtml::MakeClass>: Unknown class 'TTree'!

    root [6] TTree t;

works fine.

### Expected behavior
Should report no errors, should create TTree documentation.

### To Reproduce
My ~/.rootrc is

> \# THtml specific settings.
Root.Html.OutputDir:         htmldoc/
Root.Html.SourcePrefix:
Unix.*.Root.Html.SourceDir:  ./:src/:include/:/opt/root/cur

(I copied it from https://root.cern.ch/doc/master/classTHtml.html (MakeAll) and https://root.cern.ch/root/roottalk/roottalk01/0059.html)

I run these commands from root interpreter:

> {
     THtml html;
     html.CreateHierarchy();
     html.MakeAll();
}

It produces the output I mentioned. 

### Setup
1. ROOT 6.22/06 compiled from source. However, I produced html with ROOT 6.20.02 earlier, and *TTree* was missing there as well (that's why I tried to regenerate docs with the most recent version).
2. Arch Linux.
3. Built from .tar.gz package.

### Additional context
TTree documentation exists on the site, but I very much want to have offline documentation.
First I wanted to post this on ROOT Forum, but during post creation the system wrote that bugs should be reported to the tracking system (Jira). If this is more convenient for you here, I post it here, though I wrote many reports here already.

**Comment by ynikitenko** [comment]
It also turns out that some documentation is not created. For example, I have a TFile.html (note that on the site it's [classTFile.html](https://root.cern/doc/master/classTFile.html)). I have empty documentation for

> TFile()
virtual ~TFile()

even though for other methods documentation is created. I can also see documentation comments in the source file from that generated html file.

**Comment by Axel-Naumann** [comment]
Hi @ynikitenko - we keep `THtml` for those who still need it for legacy use cases. ROOT has since several years moved to doxygen as documentation generator. https://root.cern/doc/master/classTHtml.html does not mention this and that's a bug. @couet could you fix that, please - make it visible that `THtml` is legacy code, and people should use `doxygen`?

@ynikitenko you can just download the ROOT documentation for a specific version here: https://root.cern/reference/ Is that enough for your use case?

**Comment by ynikitenko** [comment]
Hi @Axel-Naumann ! Thanks for the information. I think I read about that several years ago, but forgot. Now I'll fix that in my notes.

This is perfect, thank you! Maybe it's good that ROOT relies more on existing developed software instead of its own domestic tools. But it's still a pity that functionality decreases (though this is not essential for the main task, of course).

I know why I couldn't find that: the link from https://root.cern/doc/master/ is broken (which is already reported on the site repository).

**Comment by ynikitenko** [comment]
And one more thing: if it's not hard for users, maybe a recipe could be added to THtml (or to the page with all reference guides) on how to generate ROOT documentation using `doxygen`?

**Comment by ynikitenko** [comment]
The documentation is pretty large (774 Mb) vs 166MB for the whole source (which, as I understand, includes all docs in docstrings, and more), though both are tar.gz. Maybe I'll download it another time. 

Maybe it could use a better compression, like .xz or .bz2? Open a feature request or I could do that if you find it reasonable.

**Comment by Axel-Naumann** [comment]
> the link from https://root.cern/doc/master/ is broken (which is already reported on the site repository).

Which bug report is that? Which link is broken exactly?

**Comment by Axel-Naumann** [comment]
> Maybe it could use a better compression, like .xz or .bz2?

That will make it less accessible for some users, and it will reduce the file size by ~10%, not 50%. That doesn't seem like a worthwhile investment. The large size stems from the large amount of html-ified sources, mostly, as well as lots of actual documentation, and pictures.

**Comment by ynikitenko** [comment]
> > the link from https://root.cern/doc/master/ is broken (which is already reported on the site repository).
> 
> Which bug report is that? Which link is broken exactly? I found one that we can _improve_ - #7307

https://github.com/root-project/web/issues/510

The link "You can find in the reference documentation page pointers to reference manuals for all ROOT versions." is http://root.cern/guides/reference-guide, and it redirects to that same page.

**Comment by ynikitenko** [comment]
> That will make it less accessible for some users

Maybe you are right that the benefit in size would be small. However, .xz is a modern format, and it offers a rather good compression. Maybe it could be offered together with .gz files. For example, for me currently the bandwidth is slow and precious, but it turns out that the generation of many notebooks in the documentation is pretty slow (already takes more than an hour, though I forgot about -j key to make).

I see that there are many pictures generated, so probably you are right that it's not easy to compress these docs.

**Comment by ynikitenko** [comment]
There is another possibility to decrease the size of file: create a version without tutorials. Currently during my incomplete generation I see that there are

> 399M	html
6,6M	macros
561M	notebooks

I don't use Jupyter notebooks, and I read ROOT tutorials directly from the source directory. I found how to disable their generation in the *Doxyfile*, but the archive size could be lowered as well.

**Comment by ynikitenko** [comment]
I find doxygen really slow. I tried to optimize that and found many complaints (https://stackoverflow.com/questions/28628348/why-does-doxygen-always-reprocess-every-file). Maybe THtml still *could* be useful, at least partially.

**Comment by ynikitenko** [comment]
So I produced the documentation locally, and compressed that (gz took less than 5 minutes, while xz around 20 minutes). File sizes are different:

> 701M rootdoc.tar.gz
458M rootdoc.tar.xz

so the latter is 240Mb (35\%) less than the former. It seems that .xz is worthy to be offered for download. I'm pretty sure that is present in most recent distributions (it was in Fedora already several years ago when I used that). If we talk about usability, bandwidth is an important parameter too.

**Comment by couet** [comment]
The following PR makes clear THTML is legacy code:
https://github.com/root-project/root/pull/7312

**Comment by Axel-Naumann** [comment]
> the latter is 240Mb (35%) less than the former.

Thanks for trying, @ynikitenko , much appreciated! @couet shall we replace the tar.gz files with xz files? @bellenot can xz files be decompressed without pain on Windows, or does tar.gz work out of the box, and xz needs a tool to be installed?

**Comment by couet** [comment]
> I find doxygen really slow. I tried to optimize that and found many complaints (https://stackoverflow.com/questions/28628348/why-does-doxygen-always-reprocess-every-file). Maybe THtml still _could_ be useful, at least partially.
> UPD: I opened a feature request for `doxygen`.

Yes it takes time to generate the full documentation. But ROOT is huge. I never do it fully. Only the nightlies build it completely regularly. It takes several hours. As said [here](https://root.cern/for_developers/doxygen/#how-to-generate-the-doxygen-documentation) look at the list of folders scanned to build the reference guide. It is quite big. When I modify a piece of documentation I shorten this list to generate only what I am working on.

**Comment by Axel-Naumann** [comment]
Regarding:

> Maybe THtml still could be useful, at least partially.

It's not a question whether `THtml` could be useful or not. It's whether our investment in `THtml` is better than our investment in other areas, better for the quality of physics analyses. And here we decided, no; we better invest in other areas.

**Comment by ynikitenko** [comment]
Thanks for your work, @Axel-Naumann . 

> can xz files be decompressed without pain on Windows

I also tried `gzip --best ` compression option, but the benefit is negligible (692 Mb vs 702 Mb, though `--best` still runs rather quickly). 

When I used Windows years ago, there was no tar or gzip. So probably Windows users can install xz in the same way as them. In this article they say that the [native format on Windows is zip](https://itsfoss.com/tar-vs-zip-vs-gz/). In the table of comparison it's shown that zip  + compression archive occupies almost the same space as tar + gz. 

BTW: does anyone know what OS are most popular among ROOT users? During my work in collaborations in Italy and France, we almost exclusively used UNIX-like systems (the only exceptions could be some LabView programs, but I didn't use them and not sure). 

However, I would not search for a "best" format for everyone; I think the best option would be just to have several formats for those who prefer them (CPU time vs bandwidth and other considerations). Ideally it could be written how large is each corresponding file (but those who know the formats would be able to guess anyway).

**Comment by ynikitenko** [comment]
> But ROOT is huge.

@couet you are right, but THtml ran in several minutes, while to compile the entire ROOT from source takes me about an hour (vs 5 hours to get the docs with `doxygen`). The only difference is probably that to compile ROOT is quicker than to run all of its examples / tutorials.

I looked at your push request, which fixes this issue, this is rather nice, thank you.

**Comment by couet** [comment]
> I looked at your push request, which fixes this issue, this is rather nice, thank you.

Thanks ! It uses the "deprecated" doxygen keyword which also build the list of all deprecated features.
Does the PR I just pushed (7312) allows us to close this issue ?

**Comment by ynikitenko** [comment]
If you're asking me, then I don't care about closing: this is how your
internal accounting goes. Do you close it when you create a PR, or do
you close it after that is accepted? I don't know.

2021-03-01 17:18 GMT+03:00, Olivier Couet <notifications@github.com>:
>> I looked at your push request, which fixes this issue, this is rather
>> nice, thank you.
>
> Thanks ! It uses the "deprecated" doxygen keyword which also build the list
> of all deprecated features.
> Does the PR I just pushed (7312) allows us to close this issue ?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/root-project/root/issues/7295#issuecomment-787983218


-- 
С уважением,
Ярослав Никитенко
+7 916 743 3759

**Comment by couet** [comment]
If a PR seems to answers the question, yes we close...

**Comment by ynikitenko** [comment]
> If a PR seems to answers the question, yes we close...

There was a question above to @bellenot . Maybe that should be copied to a separate issue now.

**Comment by bellenot** [comment]
> > the latter is 240Mb (35%) less than the former.
> 
> Thanks for trying, @ynikitenko , much appreciated! @bellenot can xz files be decompressed without pain on Windows, or does tar.gz work out of the box, but xz needs a tool to be installed?

No idea, will have to try

**Comment by bellenot** [comment]
It looks like 7-Zip supports the `.xz` format.

**Comment by ynikitenko** [comment]
Since THtml is now deprecated, as written in its documentation, I created a new issue for .xz archives. It seems no other issues were discussed here, so I close this one.
Thanks to @couet and @Axel-Naumann for the fix and to everyone for the discussion!
