### ISSUE TITLE
RFitPanel missing from reference guide

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7304]
### Describe the bug
`ROOT::Experimental::RFitPanel` is missing in the reference guide.

### Expected behavior

https://root.cern.ch/doc/master/classROOT_1_1Experimental_1_1RFitPanel.html links to the doc page

**Comment by couet** [comment]
Indeed the whole "gui" documentation is not structured properly. Doxyfile has:

                         ../../gui/fitpanel/ \
                         ../../gui/ged/ \
                         ../../gui/gui/ \
                         ../../gui/guibuilder/ \
                         ../../gui/guihtml/ \
                         ../../gui/recorder/ \
                         ../../gui/sessionviewer/ \
                         ../../gui/webdisplay 

May the "7" part is missing ..
I can restructure and propose a PR...

**Comment by couet** [comment]
Fixed by https://github.com/root-project/root/pull/7403
