### ISSUE TITLE
TTree:Write should write to TTree's file

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7308]
### Explain what you would like to see improved
There is a [TTree constructor](https://root.cern/doc/master/classTTree.html#a072dbaea957b66fe33f136e7319ed724),

    TTree::TTree (const char *name, const char * title, Int_t splitlevel = 99, TDirectory *dir = gDirectory)

(it's easy to learn that a TDirectory object can be a TFile, which is used very often).

There is a [TTree:Write](https://root.cern/doc/master/classTTree.html#af6f2d9ae4048ad85fcae5d2afa05100f) method (actually there are two of them; when I read the code I found that the non-const just calls a const method, so it looks like an ugly patch; but anyway). In the documentation it's said that it writes to the current directory (which is correct). I found an explanation by pcanal, that [TObject::Write semantically is explicitly to store the current object in the current TFile](https://root-forum.cern.ch/t/writing-trees-to-different-files/5640/3?u=ynikitenko).

Why I was looking for that: I remembered from the old good User's Guide that there is a 'global directory' and many other global variables in ROOT. I wanted to have two trees written to two different files in one session from Python. But the trees (as now is clear) were written to the most recently opened file, not to those with which they were initialized. In the link above, I found the way to solve this:

    TFile.Write()

would save its objects.

I find this very non-straightforward. I think that if a file is associated with TTree, it should be written to that file.

On the line 891 of [TTree.cxx](https://root.cern/doc/master/TTree_8cxx_source.html) there is a fixme comment:

> // Insert ourself into the current directory.
    // FIXME: This is very annoying behaviour, we should
    //        be able to choose to not do this like we
    //        can with a histogram.

That comment was misleading for me, I thought that was not implemented and was looking for hackish ways not to do that.

### Optional: share how it could be improved
I see several ways how it could be improved:

1) make Write use TTree's file if that was set in the constructor. This is natural and doesn't contradict inheritance from TObject, because a) not all ROOT objects belong to the global directory b) virtual functions can be reimplemented in daughter classes; this is fine when the general behaviour is the same.
2) add to TTree:Write documentation the way to write to a given file instead of the current file (this might be easier to find and understand than in the vast docs of TTree).
3) maybe create a method Write(file) of TTree with an argument TFile/(its parent). In the [program of work for 2020](https://indico.cern.ch/event/875784/contributions/3690258/attachments/1975740/3288395/ROOT-PoW2020-EP-SFT.pdf) on page 10 Axel Naumann proposes: "Keep interfaces readable for current ROOT users. canv->cd(); hist->Draw(); becomes canv->Draw(hist)." I think this is very much in line with this suggestion, and it's just a good design.

### Setup
1. ROOT 6.22/06

### Additional context
I found a question [TTree.Write() vs. TFile.Write()](https://root-forum.cern.ch/t/ttree-write-vs-tfile-write/82) on the Forum, so it may be better to explain (or implement) it more explicitly in docs. There are really many questions about how to write one/two trees to one/several different files.

**Comment by pcanal** [comment]
> make Write use TTree's file if that was set in the constructor ... and doesn't contradict inheritance from TObject,

It does contradict the contracts from the inheritance.  `TObject::Write` (as you quoted me saying ) ) is an explicitly request to write to the current directory.   With the proposed change `TTree::Write` would behave unlike any other overload of `TObject::Write`

That said we agree that this is confusing and as you quoted Axel saying, we are change this radically in the API redesign (nicknamed ROOT v7) and in particular will remove all the implicit ownership sharing and attachment to files.    We did not find a practical way to evolve the current interface in place without significant backward incompatibility.

Note that there is "already" an equivalent to `Write(file)` which is `file->WriteObject(tree)`

**Comment by ynikitenko** [comment]
I see, thanks.

It's reported that ROOT 7 will come "in following years", https://root.cern/for_developers/root7/, but I can't see the date of that publication.

**Comment by ynikitenko** [comment]
Anyway it would be good to add deprecation warnings to existing interfaces.
Close this issue when you feel appropriate, please.
