### ISSUE TITLE
When using the slider in Fit Panel we get Warnings

### ISSUE THREAD

**Issue by couet** [root-project/root#7340]
### Describe the bug

https://root-forum.cern.ch/t/bugs-in-tfit-errors-when-trying-to-fit-a-histogram/43789

### To Reproduce

Open the fit Panel on a TH1 and move the range slider

### Setup

On Mac

**Comment by bellenot** [comment]
FYI, this work fine on Linux and Windows, and one should check if the issue comes from the GUI or from the graphics...

**Comment by couet** [comment]
It is a Mac/ Cocoa thing. I emailed Timur. He did a fix in crosshair recently. May be it is connected. He may have an idea.

**Comment by couet** [comment]
This PR fixes the issue: https://github.com/root-project/root/pull/7492

**Comment by couet** [comment]
Fixed https://github.com/root-project/root/pull/7492
