### ISSUE TITLE
Issue building built-in libafterimage

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#7345]
- [X] Checked for duplicates

### Describe the bug

When configuring ROOT with builtin_afterimage, building libAfterImage fails with the following errors:

```
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
/bin/sh: line 30: -m: command not found
gmake[3]: m: No such file or directory
/bin/sh: line 2: -m: command not found
gmake[3]: *** [Makefile:145: install.static] Error 127
```

The error message seems to indicate that the `${INSTALL}` makefile variable expands to nothing rather than to `install` as it should, but I do have `install` available on my system.

This happens both on Fedora and Arch.

### To Reproduce

Probably just start a Docker container with Arch or Fedora 33 and try to build ROOT with builtin_libafterimage.

### Additional context

Installing a system version of libafterimage works around the issue.

**Comment by linev** [comment]
I have other problem building libAfterImage - in error output I see following message
```
ar: libdeps specified more than once
```
It caused by argument `l` in `ar clq` command. 
Argument `l` means library linking to static `libAfterImage.a` library, but there is no any library linked.
Seems to be `ar` on my latest OpenSUSE installation is too strict about this.

**Comment by linev** [comment]
@eguiraud 

Can you post content of Makefile, which is created in `AFTERIMAGE-prefix/src/AFTERIMAGE-stamp/` sub-directory.
Most probably, some of standard `MV` or `CP` commands were not correctly translated by the build system

**Comment by eguiraud** [comment]
@linev yes, it's the `INSTALL` variable that expands to nothing (will post the makefile in a sec)

**Comment by linev** [comment]
Question - why `INSTALL` does not defined on your system. 
Maybe it should be specified in configure command here:
https://github.com/root-project/root/blob/master/cmake/modules/SearchInstalledSoftware.cmake#L471

Can you try to add there: `INSTALL=/usr/bin/install`

**Comment by eguiraud** [comment]
Uhm now I'm getting your same error, `ar: libdeps specified more than once`

**Comment by linev** [comment]
Yes, I also observing such error only when build stops and I trying to continue the run.
Try to apply patch from pr: https://github.com/root-project/root/pull/7346

**Comment by eguiraud** [comment]
@linev you patch fixes that problem, and unfortunately I cannot reproduce the original problem anymore. I think in the meanwhile I must have installed some packages the fixed the empty INSTALL variable.
