### ISSUE TITLE
ACLiC compilation confuses compiled binaries with shared objects, breaking compilation in some cases

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#7366]
- [X] Checked for duplicates

### Describe the bug

Building ROOT on Arch Linux and then running `ctest -R "(dataframe|datasource)" -- -j8` results in several test failures.
There are various possible failure modes -- the command above typically results in these kind of errors:

```
1369: Processing /home/jalopezg/CERN/roottest/root/dataframe/test_snapshot.C+...
1369: Info in <TUnixSystem::ACLiC>: creating shared library /home/jalopezg/CERN/build/roottest/root/dataframe/test_snapshot_C.so
1369: /usr/bin/ld: /home/jalopezg/CERN/build/roottest/root/dataframe/test_readFcc: _ZSt4cout: invalid version 6 (max 0)
1369: /usr/bin/ld: /home/jalopezg/CERN/build/roottest/root/dataframe/test_readFcc: error adding symbols: bad value
1369: collect2: error: ld returned 1 exit status
1369: Error in <ACLiC>: Executing 'cd "/home/jalopezg/CERN/build/roottest/root/dataframe" ; c++ -fPIC -c -O3 -DNDEBUG -std=c++14 -Wno-implicit-fallthrough -Wno-noexcept-type -pipe -W -Woverloaded-virtual -fsigned-char -pthread  -I$ROOTSYS/include -I/home/jalopezg/CERN/build/roottest/root/dataframe -I"/home/jalopezg/CERN/build/etc/" -I"/home/jalopezg/CERN/build/etc//cling" -I"/home/jalopezg/CERN/build/include/" -I"/home/jalopezg/CERN/build/include" -I"/home/jalopezg/CERN/build/roottest/root/dataframe"   -D__ACLIC__ "/home/jalopezg/CERN/build/roottest/root/dataframe/test_snapshot_C_ACLiC_dict.cxx" ; c++ -O3 -DNDEBUG "/home/jalopezg/CERN/build/roottest/root/dataframe/test_snapshot_C_ACLiC_dict.o" -shared   "/usr/lib/libdl.so" "/usr/lib/libc.so" "/usr/lib/libgcc_s.so" "/usr/lib/libm.so" "/usr/lib/libstdc++.so" "/home/jalopezg/CERN/build/lib/libRint.so" "/home/jalopezg/CERN/build/lib/libCore.so" "/usr/lib/libpthread.so.0" "/usr/lib/libpcre.so.1" "/usr/lib/liblzma.so.5" "/usr/lib/liblz4.so.1" "/usr/lib/libz.so.1" "/usr/lib/libzstd.so.1" "/usr/lib/libnss_files.so.2" "/home/jalopezg/CERN/build/lib/libRIO.so" "/home/jalopezg/CERN/build/lib/libThread.so" "/home/jalopezg/CERN/build/lib/libCling.so" "/usr/lib/librt.so.1" "/usr/lib/libncursesw.so.6" "/usr/lib/ld-2.33.so" "/home/jalopezg/CERN/build/lib/libMathCore.so" "/home/jalopezg/CERN/build/lib/libImt.so" "/home/jalopezg/CERN/build/lib/libMultiProc.so" "/home/jalopezg/CERN/build/lib/libNet.so" "/usr/lib/libtbb.so.2" "/usr/lib/libssl.so.1.1" "/usr/lib/libcrypto.so.1.1" "/usr/lib/libnss_systemd.so.2" -o "/home/jalopezg/CERN/build/roottest/root/dataframe/test_snapshot_C.so" /home/jalopezg/CERN/build/lib/libROOTDataFrame.so /home/jalopezg/CERN/build/lib/libTreePlayer.so /home/jalopezg/CERN/build/lib/libTree.so /home/jalopezg/CERN/build/roottest/root/dataframe/test_readFcc /home/jalopezg/CERN/build/roottest/root/dataframe/par' failed!
1369: terminate called after throwing an instance of 'std::logic_error'
1369:   what():  basic_string::_M_construct null not valid
```

I did not manage to reproduce the problem outside of ctest and without running multiple tests concurrently -- it also seems that one of the tests "has" to be `roottest-root-dataframe-test_snapshot_manytasks`.

### To Reproduce

The following repository provides a Dockerfile to reproduce the issue in a container https://gitlab.cern.ch/eguiraud/arch_aclic_bug .

### Setup

ROOT master (but 6.22 also has issues) and arch linux.

I tried building from source (6.22 and master) as well as installing from the system repos -- failure modes are different but none can run all tests without problems.

Gentoo seems to also be affected.

**Comment by eguiraud** [comment]
i think there is a bug in how the aclic compilation command is built

i see this compilation command for one of the RDF roottests:

```
c++ -O3 -DNDEBUG "/home/blue/ROOT/master/_build/roottest/root/dataframe/writeFcc_C_ACLiC_dict.o" -shared   "/usr/lib/libdl.so" "/usr/lib/libc.so" "/usr/lib/libgcc_s.so" "/usr/lib/libm.so" "/usr/lib/libstdc++.so" "/home/blue/ROOT/master/_build/lib/libRint.so" "/home/blue/ROOT/master/_build/lib/libCore.so" "/usr/lib/libpthread.so.0" "/usr/lib/libpcre.so.1" "/usr/lib/liblzma.so.5" "/usr/lib/libxxhash.so.0" "/usr/lib/liblz4.so.1" "/usr/lib/libz.so.1" "/usr/lib/libzstd.so.1" "/usr/lib/libnss_files.so.2" "/home/blue/ROOT/master/_build/lib/libRIO.so" "/home/blue/ROOT/master/_build/lib/libThread.so" "/home/blue/ROOT/master/_build/lib/libCling.so" "/usr/lib/librt.so.1" "/usr/lib/libncursesw.so.6" "/usr/lib/ld-2.33.so" "/home/blue/ROOT/master/_build/lib/libMathCore.so" "/home/blue/ROOT/master/_build/lib/libImt.so" "/home/blue/ROOT/master/_build/lib/libMultiProc.so" "/home/blue/ROOT/master/_build/lib/libNet.so" "/usr/lib/libtbb.so.2" "/usr/lib/libssl.so.1.1" "/usr/lib/libcrypto.so.1.1" "/usr/lib/libnss_systemd.so.2" "/usr/lib/libcrypt.so.2" "/usr/lib/libp11-kit.so.0" "/usr/lib/libffi.so.7" -o "/home/blue/ROOT/master/_build/roottest/root/dataframe/writeFcc_C.so" /home/blue/ROOT/master/_build/lib/libROOTDataFrame.so /home/blue/ROOT/master/_build/lib/libTreePlayer.so /home/blue/ROOT/master/_build/lib/libTree.so /home/blue/ROOT/master/_build/roottest/root/dataframe/branchoverwrite /home/blue/ROOT/master/_build/roottest/root/dataframe/test_readerarray
```

i.e.

```
c++ <bunch of irrelevant stuff> -o "/home/blue/ROOT/master/_build/roottest/root/dataframe/writeFcc_C.so" /home/blue/ROOT/master/_build/lib/libROOTDataFrame.so /home/blue/ROOT/master/_build/lib/libTreePlayer.so /home/blue/ROOT/master/_build/lib/libTree.so /home/blue/ROOT/master/_build/roottest/root/dataframe/branchoverwrite /home/blue/ROOT/master/_build/roottest/root/dataframe/test_readerarray
```

The last two arguments are bogus, `/home/blue/ROOT/master/_build/roottest/root/dataframe/branchoverwrite` should not be there nor `/home/blue/ROOT/master/_build/roottest/root/dataframe/test_readerarray`

SImilarly for the failure reported in the issue description: there are 2 weird extra arguments appended to the compiler invocation that end up causing obscure aclic compilation failures.

**Comment by eguiraud** [comment]
At TSystem.cxx:3340, in `TSystem::CompileMacro`, the following call:

```
gInterpreter->GetSharedLibDeps("/home/blue/ROOT/master/roottest/root/dataframe/writeFcc_C.so", /*tryDyld*/ true);
```

returns

```
"writeFcc_C.so libROOTDataFrame.so libTreePlayer.so libTree.so branchoverwrite test_readerarray "
```

where I'm pretty sure the last two argument shouldn't be present.

**Comment by eguiraud** [comment]
In `TInterpreter::GetSharedLibDeps`, at some point we call `interp->getDynamicLibraryManager()->searchLibrariesForSymbol("__libc_single_threaded@GLIBC_2.32", /*searchSystem*/false)` and that returns `"/home/blue/ROOT/master/_build/roottest/root/dataframe/branchoverwrite"` in this broken usecase.

As `branchoverwrite` is a completely unrelated test, the linking of which actually breaks the ACLiC compilation of this macro, I guess we don't want to pick `"__libc_single_threaded@GLIBC_2.32"` from `"/home/blue/ROOT/master/_build/roottest/root/dataframe/branchoverwrite"`

**Comment by eguiraud** [comment]
Assigning to @vgvassilev as the problem seems to be that `interp->getDynamicLibraryManager()->searchLibrariesForSymbol` picks up unrelated executables as if they were libraries providing certain symbols

**Comment by vgvassilev** [comment]
@eguiraud, thanks for the detailed analysis. Unfortunately this works as designed and I am not sure if we can fix that behavior in a way that is reasonable when running the tests while keeping it working for the rest.

If the issue is just for the test suite, I'd propose slitting these tests into subfolders.

**Comment by pcanal** [comment]
@vgvassilev I am confused, why does `getDynamicLibraryManager` returns the names of executables?  What is the purpose and/or why would an executable be used to provide symbols for other executables?

**Comment by Axel-Naumann** [comment]
> Unfortunately this works as designed

That would mean the design is broken and needs to be reconsidered, possibly by re-introducing rootmap files.

**Comment by eguiraud** [comment]
Also note that this is (or seems to be) a relatively recent problem, we only see it on Arch and Gentoo since a few months.

**Comment by vgvassilev** [comment]
> @vgvassilev I am confused, why does `getDynamicLibraryManager` returns the names of executables? What is the purpose and/or why would an executable be used to provide symbols for other executables?

Ah, if those are executables and not shared objects that’s indeed a bug that can be fixed.

**Comment by vgvassilev** [comment]
> In `TInterpreter::GetSharedLibDeps`, at some point we call `interp->getDynamicLibraryManager()->searchLibrariesForSymbol("__libc_single_threaded@GLIBC_2.32", /*searchSystem*/false)` and that returns `"/home/blue/ROOT/master/_build/roottest/root/dataframe/branchoverwrite"` in this broken usecase.
> 
> As `branchoverwrite` is a completely unrelated test, the linking of which actually breaks the ACLiC compilation of this macro, I guess we don't want to pick `"__libc_single_threaded@GLIBC_2.32"` from `"/home/blue/ROOT/master/_build/roottest/root/dataframe/branchoverwrite"`

Is the `branchoverwrite` the executable which runs the `TInterpreter::GetSharedLibDeps`? If that is not the case then for some reason, on Arch, the implementation thinks `branchoverwrite` is a shared object and not an executable..

**Comment by eguiraud** [comment]
`branchoverwrite` is a completely unrelated executable, see `roottest/root/dataframe/CMakeLists.txt`

**Comment by vgvassilev** [comment]
Unfortunately I do not have access to such a system but if you can build with `-DLLVM_BUILD_TYPE=Debug` the function `isSharedLibrary` [here](https://github.com/root-project/root/blob/d75ee349cb75d743d41e99cca97d5ef230f9207e/interpreter/cling/lib/Interpreter/DynamicLibraryManager.cpp#L248) should return `true` for `branchoverwrite`.

If that is the case then there might be a problem with the Elf representation (or ACLiC is missing some compiler/linker flag).

**Comment by eguiraud** [comment]
The issue description links to a dockerfile that reproduces the problem

**Comment by vgvassilev** [comment]
The link seems broken for me.

**Comment by eguiraud** [comment]
Sorry, gitlab makes projects private by default. Now fixed :sweat:

**Comment by eguiraud** [comment]
Hi @vgvassilev , could you suggest a workaround for this? It prevents me from running certain tests locally :sweat_smile:

**Comment by vgvassilev** [comment]
Sorry I can look at that soon. I am not really sure if that can be worked around.

**Comment by vgvassilev** [comment]
Some updates:

> Unfortunately I do not have access to such a system but if you can build with `-DLLVM_BUILD_TYPE=Debug` the function `isSharedLibrary` [here](https://github.com/root-project/root/blob/d75ee349cb75d743d41e99cca97d5ef230f9207e/interpreter/cling/lib/Interpreter/DynamicLibraryManager.cpp#L248) should return `true` for `branchoverwrite`.


> 
> If that is the case then there might be a problem with the Elf representation (or ACLiC is missing some compiler/linker flag).


```1: libFullPath = {static npos = 18446744073709551615, Data = 0x5555579a44b0 "/build_root/roottest/root/dataframe/test_snapshot_manytasks", Length = 59}
(gdb) p Error
$6 = {_M_value = 0, _M_cat = 0x7ffff7917180 <(anonymous namespace)::system_category_instance>}
(gdb) list
260	    file_magic Magic;
261	    const std::error_code Error = identify_magic(libFullPath, Magic);
262	    if (exists)
263	      *exists = !Error;
264	
265	    return !Error &&
266	#ifdef __APPLE__
267	      (Magic == file_magic::macho_fixed_virtual_memory_shared_lib
268	       || Magic == file_magic::macho_dynamically_linked_shared_lib
269	       || Magic == file_magic::macho_dynamically_linked_shared_lib_stub
(gdb) p Magic
$7 = {V = llvm::file_magic::elf_shared_object}
```

There is nothing wrong with the implementation per se. For some reason the system compiles the `test_snapshot_manytasks` executable with a file magic which corresponds to a shared object. Although, bash correctly recognizes the right kind:
```file $ROOTSYS/lib/libCore.so
/build_root/lib/libCore.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=e29464343a374abe0b0e4149350d4a57f8383b3a, with debug_info, not stripped
[root@39b36d564292 dataframe]# file -i /build_root/roottest/root/dataframe/test_snapshot_manytasks
/build_root/roottest/root/dataframe/test_snapshot_manytasks: application/x-pie-executable; charset=binary```

**Comment by eguiraud** [comment]
Possibly relevant (this or one of the related questions): https://stackoverflow.com/questions/34519521/why-does-gcc-create-a-shared-object-instead-of-an-executable-binary-according-to

Looks like the file magic being checked is not sufficient to distinguish between shared objs and executables (anymore)?

**Comment by vgvassilev** [comment]
Link right on target. Yeah, looks like pie is to enable address space randomization for executables. I am not sure if that’s important for ACLIC binaries. A fix/workaround of the problem would be to pass -fno-pie to the aclic command.

**Comment by eguiraud** [comment]
Hi, little ping :) Could we just add `-fno-pie` to ACLiC's compilation flag?

**Comment by eguiraud** [comment]
@vgvassilev @Axel-Naumann [adding `-fno-pie` to the ACLiC compilation command](https://github.com/eguiraud/root/commit/615f0a670054c79924e5b5260218e402ebd52bb6) does not seem to help, because _other_ executables, not produced by ACLiC (but, in my case, by cmake/ctest itself) are still picked up as shared libraries.

I think LLVM/cling needs to change the way they decide if a file is a shared object or not? (as `/usr/bin/file` seems to get it right even without `-fno-pie`)

**Comment by vgvassilev** [comment]
I will check if the relevant code is modified in llvm 13 and then see who to ask for advice from the llvm community

**Comment by eguiraud** [comment]
If I understand correctly, this means that ACLiC is pretty much broken (currently on Arch and Gentoo, likely more platforms in the future).

It's not just an issue of the test suite: `interp->getDynamicLibraryManager()->searchLibrariesForSymbol` picks up unrelated binaries from the current directory if they happen to contain the symbol that is being searched, breaking compilation down the road.

**Comment by vgvassilev** [comment]
I cannot seem to reproduce it in the ubuntu environment. Can you put your failing environment in some docker container we could use?

**Comment by eguiraud** [comment]
See my first post here :D

**Comment by vgvassilev** [comment]
@eguiraud, could you test https://github.com/root-project/root/pull/9404 on your setup?

**Comment by jalopezg-r00t** [comment]
> @eguiraud, could you test #9404 on your setup?

@vgvassilev I have a similar setup (Arch Linux x86_64) and I can confirm that the patch fixes the problem.  :-)

**Comment by eguiraud** [comment]
Hi, works for me as well! It would be nice to have confirmation for Gentoo as well if and when @amadio has time to try this out, but the patch is a fix for the original issue.

**Comment by amadio** [comment]
Sorry, I missed this before, please ping me in the issue description or add me as assignee next time to ensure I see it. Gentoo has `-fPIE` enabled by default in GCC, and I've had to make changes in ROOT already because of some tests failing due to that. If the patch fixes it for Arch, it should fix it for Gentoo. I can pick up the patch in 6.24.06, but I think this is important enough that a new patch release would be nice to make sure the fix hits as many people as possible. If there's a quick way to test this, let me know, I can test and report on the results.

**Comment by eguiraud** [comment]
Thank you Guilherme, afaik it's enough to run `ctest -j8` to test this, see your comment at https://github.com/root-project/root/issues/7936#issuecomment-825672249

**Comment by amadio** [comment]
Ok, I will build the latest master and (maybe) report which tests are failing for me in a new issue then. Thanks!

**Comment by amadio** [comment]
No dataframe tests fail for me, but a bunch of others do fail, so if this is in master, it should have fixed the problem in Gentoo.

**Comment by eguiraud** [comment]
I guess this needs a backport to v6-26-00-patches?

**Comment by eguiraud** [comment]
A v6.26 backport is at #9676
