### ISSUE TITLE
TPython not redirecting stdout and stderr to IDE's stderr and stdout

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#7372]
### Describe the bug
When executed in a ROOT console or on a normal terminal, TPython::Exec( "print \'Hello World!\'" );
prints correctly to stderr and stdout of the terminal.

When executed in QtCreator's IDE, it does not. If one selects the option 'run in terminal', it does print it corretly.

### Expected behavior
sys.stderr and sys.stdout are forwarded to the QtCreators IDE's stderr and stdout if not being run on terminal.

### To Reproduce
1. Open a ROOT terminal and call TPython::Exec( "print \'Hello World!\'" );
2. Create a standalone C++ program with CMake, open with QtCreator and call the same function.
3. In this same standalone C++ program, you can write std::cout and std::cerr, and those are correctly shown in the IDE window.

### Setup
1. ROOT version 6.23
2. Operating system Ubuntu 18
3. Self-built

### Additional context
Maybe this helps:
https://stackoverflow.com/questions/46632488/how-to-catch-python-3-stdout-in-c-code
https://stackoverflow.com/a/8335297/7471760

**Comment by jalopezg-r00t** [comment]
I don't know if it should be labeled as a `bug` in current functionality.  Changing it to `improvement`.

**Comment by etejedor** [comment]
> sys.stderr and sys.stdout are forwarded to the QtCreators IDE's stderr and stdout if not being run on terminal.

Is this something `TPython` should do? Does this happen if you run a regular Python application?

In the end what `TPython::Exec` does is executing Python code via a Python interpreter and the `PyRun_String` call, which will write to `sys.stdout` and `sys.stderr`, wherever they point to.

**Comment by ferdymercury** [comment]
Thanks for the answer :). It's weird, now I am trying from scratch and it redirects it fine in both modes.
Maybe last time I tried I was defining a TApplication and then it didn't redirect fine.

In any case, I had switched in the meanwhile to https://github.com/pybind/pybind11/ so I will close this.
