### ISSUE TITLE
In CompileMacro, the "g" option disables optimizations

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#7377]
- [X] Checked for duplicates

### Describe the bug

Calling `CompileMacro("macro.C", "gO")` only adds debug flags, not optimization flags. This is surprising as it is not the behavior of compilers (passing both `-g` and `-O2` is fine) and the lack of optimization is completely invisible to most users.

### Expected behavior

Compilers allow debug and optimization flags leaving side by side without issues, `CompileMacro` should do the same.  

### To Reproduce

Calling `CompileMacro("macro.C", "fO")` with a high enough `gDebug` value shows the problem.

### Additional context

I found an [old jira ticket](https://sft.its.cern.ch/jira/browse/ROOT-5803) where @pcanal suggests to use this behavior as a feature, explicitly passing "g" to disable optimizations in a case where they were not desired.

**Comment by pcanal** [comment]
Without some of the over-ridding behavior, there would be no (easy) way to disable optimization.The old behavior was:
```
+g -> -g (and default compiler optimization)
+O -> -O3 (or more exactly the optimization level select at ROOT configuration time)
+gO -> -g  (and default compiler optimization)
+ -> -g or -O3 depending on whether ROOT was build in debug mode ... except that this is broken since the move to CMake :( so actually always -O3
```
The new behavior could be:
```
+g -> -g (and default compiler optimization)
+O -> -O3 (or more exactly the optimization level select at ROOT configuration time)
+gO -> -g  -O3 
+ -> -g or -O3 depending on whether ROOT was build in debug mode ... except that this is broken since the move to CMake :( so actually always -O3
```
So this can be fine as we **MUST** have a way to completely disable optimization.
