### ISSUE TITLE
[DF] Reduce precision errors for `Mean` and `StdDev`

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#7395]
`RDF::Mean()` uses plain doubles. That's better than float, but far from stable. When you run with IMT, it's actually more accurate than without, because less numbers go into one accumulator, and each running sum remains smaller. So IMT/NoIMT can break your tests (even different TBB scheduling does).

It was creating problems already in this simple test (note that the precision threshold for testing the mean is pretty bad, 1.E-2):
https://github.com/root-project/root/blob/7e1c74b764a60f811e898c3f6b55c0234b2b307d/roofit/RDataFrameHelpers/test/testActionHelpers.cxx#L28-L33

Maybe it's worth to increase the precision of
https://github.com/root-project/root/blob/7e1c74b764a60f811e898c3f6b55c0234b2b307d/tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx#L917

with a Kahan or Neumaier sum.

Same for StdDev, maybe go for Knuth's algo or the parallel weighted variance.
https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance

For Kahan, you can use
https://root.cern.ch/doc/master/classROOT_1_1Math_1_1KahanSum.html

**Comment by Neel-Shah-29** [comment]
Hello I am interested in working on this issue can you assign it to me if no one is working on it

**Comment by hageboeck** [comment]
Nice, good luck! 👍 We will be here if you have questions.

**Comment by Neel-Shah-29** [comment]
Hello can you just give some resources to start with the Root as i am just a beginner in open source but surely passionate to complete this issue .

**Comment by hageboeck** [comment]
The code locations were already given in the issue descriptions (but line numbers might have changed).
So instead of creating a vector of doubles here:
https://github.com/root-project/root/blob/7e1c74b764a60f811e898c3f6b55c0234b2b307d/tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx#L917

Create a vector of Kahan sums using the already existing Kahan summation class:
https://root.cern.ch/doc/master/classROOT_1_1Math_1_1KahanSum.html

Then, create a pull request on root's github where you mention this issue, and we can have a look.

The standard deviation is more complicated, so don't worry for the moment.

**Comment by Neel-Shah-29** [comment]
I have sent the PR kindly suggest the changes to be made if anything incorrect. 
Thankyou.

**Comment by eguiraud** [comment]
This was fixed by https://github.com/root-project/root/pull/11230
