### ISSUE TITLE
Make manual available offline

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7421]
### Is your feature request related to a problem? Please describe.
I want to use the manual offline. Ideally a pdf, but an archive of html pages is fine too.

### Describe the solution you'd like
Could it be added to the Reference Guide at https://root.cern/reference/ ? And give a link to that in some visible place.

### Describe alternatives you've considered
I know I can use `wget`, but I downloaded the Reference Guide from the site (oh no, I generated it myself - but I think there's no difference? If there is, maybe it could be included into doxygen data?), and regret that Manual is missing there. Thanks a lot.

**Comment by couet** [comment]
You would like to have the whole Reference Guide generated via Doxygen in pdf format ? 
Doxygen is able to generate Latex (then pdf) ... We can try but I am afraid that will be a monster file...

**Comment by ynikitenko** [comment]
I'm saying only about the Manual, not the reference guide.

пн, 15 мар. 2021 г., 17:54 Olivier Couet ***@***.***>:

**Comment by couet** [comment]
Ok, so the hierarchy of pages form this link: https://root.cern/manual/

**Comment by ynikitenko** [comment]
Yes, exactly.

**Comment by couet** [comment]
There is some tools to convert Jekyll pages to pdf like for instance https://github.com/abeMedia/jekyll-pdf
But I am not sure it will work for us as the pictures we have in the manual  are generated by jsroot and can be
interactively manipulated. For instance this one: https://root.cern/manual/graphs/#drawing-a-graph

**Comment by ynikitenko** [comment]
No, it seems I have no interactive (and maybe any) graphs. However, it's fine, because I need mostly only commands.

Just for reference, this is a command to download all pages until they are not made for download elsewhere:

    wget -c -np -E -p -r -l 0 -k -nH https://root.cern/manual/

**Comment by couet** [comment]
> this is a command to download all pages

So we can consider this issue as resolved as you have the command doing what you are looking for ? can we close it ?

**Comment by ynikitenko** [comment]
No, I'm afraid not. It would be nice if the manual could be downloaded easier from the site, preferably with images. Ideally it should be included into other documentation package (the lesser files to download, the better).

**Comment by couet** [comment]
Ok fine we leave it open. 

BTW I am not sure tu understand _"Ideally it should be included into other documentation package (the lesser files to download, the better)."_... What do you mean by "other documentation package" ????

**Comment by ynikitenko** [comment]
I mean e.g.

    the Reference Guide at https://root.cern/reference/ 

as I wrote in the topic.

**Comment by couet** [comment]
> I want to use the manual offline. Ideally a pdf

I search on the web but I did not find any easy way to convert the whole web tree under https://root.cern/manual/ into pdf. May be you know one ? If yes that might be easier for you to do it when you need. I do not see the added value of having that a such pdf file part of the root web site if you can easily convert the manual into pdf yourself: just do it when you need. In any case I do not know how to do it. Sorry.

**Comment by ynikitenko** [comment]
No, I don't know how to do that. I use sphinx when I have *rst* pages.
Pdf is not so necessary, html for downloading would be fine.

**Comment by couet** [comment]
It seems that can be easily done with [recipes like this one](https://www.hongkiat.com/blog/read-download-website-offline/#:~:text=In%20the%20Chrome%20for%20Android,page%20in%20your%20default%20browser.) . And again once you have the recipe, I do not see the point of providing a tar file with the static web site in it, as you can download it your self when you need.

**Comment by ynikitenko** [comment]
It can be done if you have Internet. Earlier User's Guide was available for download. It's much easier to download a prepared file. Especially if it is together with other documentation.

**Comment by couet** [comment]
Of course you need internet at least once to download the pages on your local machine. That's also true if we would provide a tar ball of the html pages. I pointed you some recipes to download the Manual locally. The Manual is Web only. If you want it locally use the tools available on the web (you need internet at least once...) . I will close this issue I guess.

**Comment by ynikitenko** [comment]
If you would provide a tar ball of the html pages, that would (hopefully) be changed from time to time. How do I know if I should re-download the manual or if I have the most up-to-date one? 
In my very first post when I opened this issue, I wrote about `wget`. So some recipes were known before, but anyway thanks for the links. The thing is that to download an archive is much easier than to use tools or recipes.
"I will close this issue I guess." - is it because you personally don't need this feature?
When there was User's Guide, it could be always downloaded as one pdf document (there was also an html archive of that). When you move to 'pure internet version', this is a revocation of an existing feature, and some users will not be happy with this.

I think if no one except me needs this feature, than probably it is not needed. Maybe other people except me and you should be asked about their opinion on this?

**Comment by couet** [comment]
You said you know you can use `wget` ... so you have a solution ? 
I do not see what I can bring more. We do not intend to generate an html version of the "Web site "called Manual" .... Since the beginning we decided it will be a web site in order to offer the most up to date version of the documentation. I think we are discussing in a loop here ....
