### ISSUE TITLE
[tree/treeplayer] Clang-Tidy Clazy Warnings

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#7430]
[treeplayer.txt](https://github.com/root-project/root/files/6111809/treeplayer.txt)

**Comment by linev** [comment]
~50% of warnings about usage of non-initialized array `tab` in TTreeFormula::EvalInstance.
To suppress them, one need to initialize array: 
```
T tab[kMAXFOUND];
```
Majority of rest of warnings is just about usage of nullptr, which are most probably `false positive`

**Comment by pcanal** [comment]
> To suppress them, one need to initialize array:

Note that this code path is 'performance critical'

**Comment by linev** [comment]
> Note that this code path is 'performance critical'

Yes. I see. And array too large (500 entries) to initialize it.

**Comment by linev** [comment]
@ferdymercury I look through the messages and did not found critical errors. 
Most of nullptr access or dereferencing are false positives, other did not checked due to performance reasons. 
But if I oversee memory leak or use of uninitialized variable (beside large block in TTreeFormula::EvalInstance), please let us know here

**Comment by ferdymercury** [comment]
Makes sense. What about adding a //NOLINT comment to suppress error on T tab[maxFound] ?

**Comment by linev** [comment]
> What about adding a //NOLINT comment to suppress error on T tab[maxFound] ?

While it is not array itself, but its usage. Mostly each of ~100 lines where it used should be provided with such comments - too ugly.

**Comment by ferdymercury** [comment]
> > What about adding a //NOLINT comment to suppress error on T tab[maxFound] ?
> 
> While it is not array itself, but its usage. Mostly each of ~100 lines where it used should be provided with such comments - too ugly.

Just fyi, Clang now supports multi-line NOLINTs:
https://llvm.discourse.group/t/clang-tidy-multi-line-nolint/3041
