### ISSUE TITLE
Canvas in gui_ex.py tutorial does not scale with window size

### ISSUE THREAD

**Issue by jblomer** [root-project/root#7435]
- [X] Checked for duplicates

### Describe the bug
When changing the window size of the gui_ex.py tutorial, the contents of the window do not scale.

### Expected behavior
The contents should adjust to the window size

### To Reproduce
```
cd $ROOTSYS/tutorials/pyroot
python -i gui_ex.py
```

### Setup

Arch Linux, compiled from latest source

### Additional context
See [ROOT forum](https://root-forum.cern.ch/t/pyroot-gui-tutorial-examples-problems-6-22-06/43891)

**Comment by bellenot** [comment]
This is not really a bug, the layout is simply not set to expand X & Y, The PR #7516 solves it.
