### ISSUE TITLE
TGText::AsString() deletes line buffers

### ISSUE THREAD

**Issue by evonreis** [root-project/root#7460]
- [X] Checked for duplicates

### Describe the bug

ROOT produces a double free error on TGText.Clear() after calling TGText.AsString()

### Setup
ROOT 6.22/06.  
OS: Linux Debian  10 Buster and Scientific Linux 7
Root is self-built on Debian.  Official redhat release is used on Scientific Linux

### Additional context
The problem can be traced to ```gui/gui/src/TGText.cxx:1250```  in ```TGText::AsString()```:

```
      char *txt = travel->GetText();
      ret += txt;
      delete [] txt;
```

txt is deleted, however it points at the text buffer to a line as returned by TGTextLine::GetText().

That there is an override, TGTextLine::GetText(Ulong_t, Ulong_t), that does return an allocated string that needs to be deleted bu the caller.

To fix the problem, only the 'delete' line needs to be deleted, but it's not good to have two methods with the same name that have different allocation behaviors on the return values.

Another possible fix would be to have TGTextLine::GetText() also allocate a new string for its return value.

**Comment by bellenot** [comment]
This should have been closed by the relevant commits...
