### ISSUE TITLE
[RF] Clang-Tidy Clazy Warnings

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#7536]
[roofit.txt](https://github.com/root-project/root/files/6148460/roofit.txt)

**Comment by linev** [comment]
Beside large number of memory leaks (which will be fixed), I try to fix many other issues reported by clang-tidy.
But  here https://github.com/root-project/root/blob/master/roofit/roofitcore/src/RooCurve.cxx#L388 I cannot decide.
May be here should be `x2 = *iter2;`, while only then this value will be somehow used and not ignored

**Comment by linev** [comment]
@guitargeek Can you try to check it?

**Comment by guitargeek** [comment]
Hi @linev! I would suggest to simply delete the line with `x1 = *iter2;` ([here a link to it](https://github.com/root-project/root/blob/master/roofit/roofitcore/src/RooCurve.cxx#L388)). The value of `x2` is already set correctly [a few lines before](https://github.com/root-project/root/blob/master/roofit/roofitcore/src/RooCurve.cxx#L373).

**Comment by linev** [comment]
I keep this place untouched in the PRs, you are free to modify as you want. 
And please check my (hepefully) last PR: https://github.com/root-project/root/pull/7642

**Comment by guitargeek** [comment]
Okay thanks! I'm reviewing it right now.
