### ISSUE TITLE
[DF] Add convenience function to describe the dataframe

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7561]
**Edit:** I'll post the newest version always at the bottom of the feed. The interface here at the top is not state-of-the-art!

---

I've created this issue to discuss how the feature should look like, see the attached PR for the impl.

My current interface looks as follows:

```python
import ROOT

df = ROOT.RDataFrame(1)\
         .Define('myInt', 'int(1)')\
         .Define('myFloat', 'float(1)')\
         .Define('myVec', 'ROOT::RVec<float>({1, 2, 3})')

print(df.GetSchema())
# Prints you this:
'''
Column  Type
------  ----
myInt   int
myFloat float
myVec   ROOT::VecOps::RVec<float>
'''
```

- ~Do we like the name of the function?~ Describe is better
- ~Do we like that it returns a string rather than printing to stdout?~ We like strings!
- ~Should we add a header to the table?~ Edit: Done, see above!
- ~Should we add any other information (see `TTree::Print`)?~ Yes, see below

**Comment by vepadulano** [comment]
I would go for something a bit more structured, like [pandas.DataFrame.info](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html) (Dask uses it as well). The word "schema" is more frequent in relational databases, so "info" sounds more generic and less confusing in this case too. It would be nice to show the following info:
1. TTree name
2. names of the columns (already provided in PR)
3. types of the columns (already provided in PR)
4. Total number of entries
5. For columns where entries are collections, show the number of elements per each entry if it's fixed, e.g. `Muon_pt      "Muon_pt[nMuon]/F"`
6. Nice to have: # "null" elements of each column (in our usecases it's a bit difficult to manage this because there's no consensus on "null")
7. Nice to have: size in memory of the TTree and the columns

**Comment by vepadulano** [comment]
Also I'm in doubt on how to treat friend trees in this context. Maybe adding an extra parameter `(show_friends=false)` to the function, not sure

**Comment by stwunsch** [comment]
Thanks for the suggestions! Very good points :)

We have to take into account that the operation should be close to "zero-cost", like `GetColumnNames()` and friends. So the total number of entries, size in memory, ... is potentially costly (?)

Regarding friends: I'd see them just as part of the dataset. Friend or not, the column is accessible. Or is there any special quirk of friends that we should consider?

**Comment by stwunsch** [comment]
> For columns where entries are collections, show the number of elements per each entry if it's fixed, e.g. Muon_pt "Muon_pt[nMuon]/F"

This is a very good point, but I think not directly doable from the RDF point of view since this is TTree specific and general for any datasource.

@eguiraud What do you think?

**Comment by stwunsch** [comment]
> Total number of entries

How cheap is this? I guess it's rather cheap if this info can be taken from the header and not via iterating of the data. How does this generalize to other datasources?

@eguiraud I bet you know all implementation details :)

**Comment by stwunsch** [comment]
Here the suggested example from pandas, with code example to play around:

```python
import pandas
data = {'myInt': [1, 2, 3], 'myFloat': [1., 2., 3.], 'myStr': ['a', 'b', 'c']}
df = pandas.DataFrame(data)
df.info()
```

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   myInt    3 non-null      int64  
 1   myFloat  3 non-null      float64
 2   myStr    3 non-null      object 
dtypes: float64(1), int64(1), object(1)
memory usage: 200.0+ bytes
```

Memory usage is really nice, the rest I find not very informative. Or is it just me?

**Comment by eguiraud** [comment]
>  Do we like the name of the function?

Yes, I'm pretty sure all physicists understand "schema" as "the structure of the dataset/TTree" 

> Do we like that it returns a string rather than printing to stdout?

Yes, why not? It's more flexible than a printout

> Should we add a header to the table?

Yes, definitely

> Should we add any other information (see TTree::Print)?

Probably

* Friend branches: I agree with Stefan the should not be treated specially, they are just more columns.
* Total number of entries: does not generalize to datasources, it might not be cheap in general. However there is no reason why we cannot print a datasource-dependant heading, with a more complete heading for TTree/TChain and less info for other datasources.
* Size in memory of the TTree and the columns: that's not a thing, TTree knows at most the compressed size of branches
* null values are not a thing

**Comment by stwunsch** [comment]
What we learned from todays PPP:

- We probably want to call it better like `Describe`
- We have to document clearly that the output is subject to change and should not be parsed
- Add number of DF runs is useful
- We have to figure out what to show if there are hundreds of columns

**Comment by stwunsch** [comment]
The pretty printing of pandas dataframes is actually a very complex thing, see [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html). I doubt that this is feasible for us.

**Comment by stwunsch** [comment]
Here is my next proposal, it's actually the tutorial I've now added. Spot the physics! :)

```python
import ROOT

# Create a dataframe
path = 'root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/Run2012BC_DoubleMuParked_Muons.root'
df = ROOT.RDataFrame('Events', path)

# Describe the state of the dataframe.
# Note that this operation is not running the event loop.
print(df.Describe())

# Build a small analysis studying the invariant mass of dimuon systems.
# See tutorial df102_NanoAODDimuonAnalysis for more information.
df = df.Filter('nMuon == 2')\
       .Filter('Muon_charge[0] != Muon_charge[1]')\
       .Define('Dimuon_mass', 'InvariantMass(Muon_pt, Muon_eta, Muon_phi, Muon_mass)')\
       .Filter('Dimuon_mass > 70')\
       .Range(1000)

# Trigger the event loop by asking for the mean of the dimuon mass.
print('\nApproximate mass of the Z boson: {:.2f} GeV\n'.format(
    df.Mean('Dimuon_mass').GetValue()))

# Describe again the state of the dataframe.
print(df.Describe())
```

```
Number of
  run event loops: 0
  columns in total: 6
  columns from defines: 0

Column          Type                            Origin
------          ----                            ------
nMuon           UInt_t                          DataSource
Muon_pt         ROOT::VecOps::RVec<Float_t>     DataSource
Muon_eta        ROOT::VecOps::RVec<Float_t>     DataSource
Muon_phi        ROOT::VecOps::RVec<Float_t>     DataSource
Muon_mass       ROOT::VecOps::RVec<Float_t>     DataSource
Muon_charge     ROOT::VecOps::RVec<Int_t>       DataSource

Approximate mass of the Z boson: 91.44 GeV

Number of
  run event loops: 1
  columns in total: 7
  columns from defines: 1

Column          Type                            Origin
------          ----                            ------
Dimuon_mass     float                           Define
nMuon           UInt_t                          DataSource
Muon_pt         ROOT::VecOps::RVec<Float_t>     DataSource
Muon_eta        ROOT::VecOps::RVec<Float_t>     DataSource
Muon_phi        ROOT::VecOps::RVec<Float_t>     DataSource
Muon_mass       ROOT::VecOps::RVec<Float_t>     DataSource
Muon_charge     ROOT::VecOps::RVec<Int_t>       DataSource
```

**Comment by stwunsch** [comment]
@Axel-Naumann @eguiraud @vepadulano What do you think?

**Comment by vepadulano** [comment]
Really like the extra information present! I would still start with a first line stating the name of the tree where applicable for better clarity, e.g. what happens currently when the df is printed
```
RDataFrame built on top of the XXX dataset
Number of
...
```
As for the formatting of the table, I agree it's too farfetched to make it the same as pandas, still would be nice to adhere to a common syntax like markdown?
```
| Column      | Type               | Origin     |
|-------------|--------------------|------------|
| Dimuon_mass | float              | Define     |
| nMuon       | UInt_t             | DataSource |
| Muon_pt     | ROOT::VecOps::RVec | DataSource |
| Muon_eta    | ROOT::VecOps::RVec | DataSource |
| Muon_phi    | ROOT::VecOps::RVec | DataSource |
| Muon_mass   | ROOT::VecOps::RVec | DataSource |
| Muon_charge | ROOT::VecOps::RVec | DataSource |
```

**Comment by stwunsch** [comment]
Right, good point, the name of the tree (or let's call it dataset) is useful!

Personally I find the markdown syntax too heavy. But if we find a majority for it, I'm happy to implement it ;)

**Comment by stwunsch** [comment]
Discussion with @eguiraud and @vepadulano:
- Rename DataSource to Dataset
- Add type and name of dataset
- Add type of datasource
- Number of slots
- Make "Numbers of ..." a table

To do so we need an additional public API:
- GetDatasetInfo, returns string like `/path/to/file:name`, TBD

I may put in all information except the dataset info first and update the output of `Describe` later. `Describe` is API-wise fixed but it's documented that the content of the returned string can change since it's meant for interactive usage.

**Comment by stwunsch** [comment]
We also want a dedicated `GetDataSourceInfo`, because we have either `fDataSet->GetLabel()`, if there's a `fDataSource`, or a `TTree/TChain` type if there is a `df.GetTree` or it's a simple dataframe aka `RDataFrame(N)` if none if this is true.

**Comment by stwunsch** [comment]
The output of the tutorial shown above is now the following:

```
Property                Value
--------                -----
Columns in total            6
Columns from defines        0
Event loops run             0
Processing slots            1

Column          Type                            Origin
------          ----                            ------
nMuon           UInt_t                          Dataset
Muon_pt         ROOT::VecOps::RVec<Float_t>     Dataset
Muon_eta        ROOT::VecOps::RVec<Float_t>     Dataset
Muon_phi        ROOT::VecOps::RVec<Float_t>     Dataset
Muon_mass       ROOT::VecOps::RVec<Float_t>     Dataset
Muon_charge     ROOT::VecOps::RVec<Int_t>       Dataset

Approximate mass of the Z boson: 91.44 GeV

Property                Value
--------                -----
Columns in total            7
Columns from defines        1
Event loops run             1
Processing slots            1

Column          Type                            Origin
------          ----                            ------
Dimuon_mass     float                           Define
nMuon           UInt_t                          Dataset
Muon_pt         ROOT::VecOps::RVec<Float_t>     Dataset
Muon_eta        ROOT::VecOps::RVec<Float_t>     Dataset
Muon_phi        ROOT::VecOps::RVec<Float_t>     Dataset
Muon_mass       ROOT::VecOps::RVec<Float_t>     Dataset
Muon_charge     ROOT::VecOps::RVec<Int_t>       Dataset
```

@eguiraud The linked PR is ready for review!

**Comment by vepadulano** [comment]
It looks very nice now, thanks!

**Comment by vepadulano** [comment]
> To do so we need an additional public API:
    GetDatasetInfo, returns string like /path/to/file:name, TBD

> We also want a dedicated GetDataSourceInfo, because we have either fDataSet->GetLabel(), if there's a fDataSource, or a TTree/TChain type if there is a df.GetTree or it's a simple dataframe aka RDataFrame(N) if none if this is true.

Alright so I have different opinions for both things. First off, I would like to have a common nomenclature that we agree upon, and we can use as reference in the future for our users. This is what my mind first thinks off when reads the following different names:
* `data format` is the identifier name of the logical or in-memory layout of the dataset. For example, `TTree`, `RNTuple`, `CSV`, `Apache Arrow`. The data format specification also imposes some extra constraints, like a CSV table does not have an embedded name, while a TTree does.
* `dataset` is the concrete representation of the information carried by data contained somewhere in some data format, e.g. a flat table or a table with possible n-dimensional cell elements for our usecases.
* `data source` is kind of more blurred, but I see it as a combination of the two above. You can't have a source of data without a dataset and you need a data format to be able to reason about the dataset and run computations on it.

The nomenclature above might not be always true, but I still think it's worth to bring up the point that we should agree on one. It stems from my personal reasoning that:
* While I understand the utility of `GetDatasetInfo`, I see a lot of possible drawbacks which I described in [this comment](https://github.com/root-project/root/issues/7828#issuecomment-817820448) to what we currently call `GetDataSourceInfo` discussion
* I would more clearly understand `GetDataSourceInfo` if it were called `GetDataFormat` or `GetDataFormatName`. I still understand that we could keep this function name to be more aligned with existent RDataSource API, though I see little relevance with the other RDataFrame constructors that use TTree as the data format.
