### ISSUE TITLE
[DF] Very long jitting times with large DF graphs

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7604]
I've got my hands on a DF workflow, which produces in a pretty large DF graph around 10k histograms in a single event loop. The graph consists of roughly 130k nodes (I can tell from the jitted code) and is assembled in Python. Even though probably the actual solution would be slimming the DF graph, it poses a nice challenge for us to push jitting to its limits. See the file attached in the archive, simply jit it or compile it with `your_compiler compile.cxx $(root-config --cflags --libs)`.

The file has 130k lines and around 60 mio characters (60 MB file) and is extracted from the code, which is jitted by DF.

Stats I've collected so far:
- Jitting with current master (llvm9): 1.5h and >25GB maxres size
- Compiling with O0 and clang10: 1.5h and 20GB maxres size (fits the jitting)
- Compiling with O0 and gcc4.8.5 and gcc10: More than 12h compile time, more than 80GB maxres size at that time (I stopped it)
- Compiling with O1 and clang10: More than 10h in, I'll probably stop it soon

Here's the file:
[compile.tar.gz](https://github.com/root-project/root/files/6169676/compile.tar.gz)

**Comment by stwunsch** [comment]
See attached files with just 10k, 20k, 30k and 40k lines of code. It seems that the increase in compile time is not linear:

```
LOC  Runtime Memory
10k  30s     1.7G
20k  70s     3.3G
30k  180s    4.9G
40k  300s    6.5G
```

Measured with following setup on CentOS 7:

```bash
$ which clang++
/cvmfs/sft.cern.ch/lcg/releases/clang/10.0.0-62e61/x86_64-centos7/bin/clang++
$ /usr/bin/time clang++ -c compile_?0k.cxx $(root-config --cflags --libs)
```

Here the files:

[compile_x0k.tar.gz](https://github.com/root-project/root/files/6170297/compile_x0k.tar.gz)

**Comment by stwunsch** [comment]
Another hint is given by using clang10 and different STL versions:

```bash
$ /usr/bin/time clang++ -c compile_10k.cxx $(root-config --cflags)
28.55user 0.80system 0:29.55elapsed 99%CPU (0avgtext+0avgdata 1724760maxresident)k
150480inputs+37568outputs (677major+376065minor)pagefaults 0swaps

$ /usr/bin/time clang++ -c compile_10k.cxx $(root-config --cflags) -stdlib=libc++
19.33user 0.49system 0:20.00elapsed 99%CPU (0avgtext+0avgdata 1211416maxresident)k
148240inputs+24336outputs (661major+234808minor)pagefaults 0swaps
```

**Comment by stwunsch** [comment]
As pointed out by @eguiraud: We have to investigate the behaviour with different optimization levels. Here a test on just 1k LOC:

```
$ /usr/bin/time clang++ -O0 -c compile_1k.cxx $(root-config --cflags)
4.27user 0.18system 0:04.64elapsed 96%CPU (0avgtext+0avgdata 316668maxresident)k
146312inputs+5224outputs (652major+69301minor)pagefaults 0swaps

$ /usr/bin/time clang++ -O1 -c compile_1k.cxx $(root-config --cflags)
19.59user 0.27system 0:20.00elapsed 99%CPU (0avgtext+0avgdata 485228maxresident)k
152088inputs+3984outputs (681major+157387minor)pagefaults 0swaps

$ /usr/bin/time clang++ -O2 -c compile_1k.cxx $(root-config --cflags)
171.13user 0.82system 2:52.27elapsed 99%CPU (0avgtext+0avgdata 680344maxresident)k
153304inputs+2608outputs (688major+243079minor)pagefaults 0swap
```

Doing the same exercise with 10k LOC give 30s for O0 but already >12min (!) for O1.

**Take away:** This questions our plans to enable O1 optimizations within RDF. It may break any large-scale usage of RDF because the jit times are going through the roof.

**Comment by stwunsch** [comment]
Last investigation for now, using `g++ -ftime-report`:

```bash
$ /usr/bin/time g++ -ftime-report -O0 -c compile_10k.cxx $(root-config --cflags)
 preprocessing                      :   0.20 (  0%)   0.30 (  8%)   0.57 (  0%)    9696 kB (  1%)
 parser (global)                    :   0.17 (  0%)   0.35 (  9%)   0.56 (  0%)   84152 kB (  4%)
 parser struct body                 :   0.23 (  0%)   0.06 (  2%)   0.18 (  0%)   30489 kB (  2%)
 parser function body               :   2.16 (  1%)   0.41 ( 11%)   2.59 (  1%)  241801 kB ( 13%)
 parser inl. func. body             :   0.04 (  0%)   0.03 (  1%)   0.06 (  0%)    4215 kB (  0%)
 parser inl. meth. body             :   0.22 (  0%)   0.06 (  2%)   0.29 (  0%)   24817 kB (  1%)
 template instantiation             :   1.30 (  0%)   0.41 ( 11%)   1.76 (  1%)  216538 kB ( 11%)
 constant expression evaluation     :   0.04 (  0%)   0.00 (  0%)   0.02 (  0%)     323 kB (  0%)
 early inlining heuristics          :   0.01 (  0%)   0.00 (  0%)   0.01 (  0%)       0 kB (  0%)
 inline parameters                  :   0.49 (  0%)   0.00 (  0%)   0.49 (  0%)   18471 kB (  1%)
 tree gimplify                      :   0.73 (  0%)   0.03 (  1%)   0.77 (  0%)   97609 kB (  5%)
 tree eh                            :   0.77 (  0%)   0.05 (  1%)   0.83 (  0%)  146994 kB (  8%)
 tree CFG construction              :   0.35 (  0%)   0.00 (  0%)   0.35 (  0%)   78117 kB (  4%)
 tree CFG cleanup                   :   0.80 (  0%)   0.01 (  0%)   0.81 (  0%)       0 kB (  0%)
 tree PHI insertion                 :   0.46 (  0%)   0.01 (  0%)   0.49 (  0%)   30685 kB (  2%)
 tree SSA rewrite                   :   0.51 (  0%)   0.02 (  1%)   0.52 (  0%)   52404 kB (  3%)
 tree SSA other                     :   0.13 (  0%)   0.14 (  4%)   0.34 (  0%)     314 kB (  0%)
 tree SSA incremental               :   1.06 (  0%)   0.00 (  0%)   1.07 (  0%)       1 kB (  0%)
 tree operand scan                  :   0.21 (  0%)   0.15 (  4%)   0.31 (  0%)   26106 kB (  1%)
 tree switch lowering               :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)       0 kB (  0%)
 dominance frontiers                :   0.05 (  0%)   0.00 (  0%)   0.04 (  0%)       0 kB (  0%)
 dominance computation              :   0.80 (  0%)   0.01 (  0%)   0.83 (  0%)       0 kB (  0%)
 out of ssa                         :   0.39 (  0%)   0.01 (  0%)   0.36 (  0%)    3829 kB (  0%)
 expand vars                        :   0.05 (  0%)   0.00 (  0%)   0.06 (  0%)   14241 kB (  1%)
 expand                             :   1.28 (  0%)   0.08 (  2%)   1.37 (  0%)  323252 kB ( 17%)
 post expand cleanups               :   0.49 (  0%)   0.01 (  0%)   0.50 (  0%)   45997 kB (  2%)
 varconst                           :   0.01 (  0%)   0.00 (  0%)   0.01 (  0%)      31 kB (  0%)
 jump                               :   0.01 (  0%)   0.00 (  0%)   0.01 (  0%)       0 kB (  0%)
 loop init                          :   4.00 (  1%)   0.02 (  1%)   4.00 (  1%)   20377 kB (  1%)
 loop fini                          :   0.05 (  0%)   0.00 (  0%)   0.06 (  0%)       0 kB (  0%)
 mode switching                     :   0.01 (  0%)   0.00 (  0%)   0.01 (  0%)       0 kB (  0%)
 integrated RA                      : 172.04 ( 54%)   0.76 ( 20%) 173.04 ( 53%)  158446 kB (  8%)
 LRA non-specific                   :   3.26 (  1%)   0.10 (  3%)   3.35 (  1%)    8175 kB (  0%)
 LRA virtuals elimination           :   1.16 (  0%)   0.01 (  0%)   1.17 (  0%)   19987 kB (  1%)
 LRA reload inheritance             :   0.03 (  0%)   0.00 (  0%)   0.00 (  0%)      26 kB (  0%)
 LRA create live ranges             : 108.01 ( 34%)   0.14 (  4%) 108.24 ( 33%)    3724 kB (  0%)
 LRA hard reg assignment            :   0.18 (  0%)   0.00 (  0%)   0.19 (  0%)       0 kB (  0%)
 reload                             :   0.03 (  0%)   0.00 (  0%)   0.02 (  0%)       0 kB (  0%)
 thread pro- & epilogue             :   1.19 (  0%)   0.00 (  0%)   1.26 (  0%)    3682 kB (  0%)
 machine dep reorg                  :   0.03 (  0%)   0.00 (  0%)   0.05 (  0%)       0 kB (  0%)
 shorten branches                   :   0.75 (  0%)   0.01 (  0%)   0.77 (  0%)       0 kB (  0%)
 reg stack                          :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)       0 kB (  0%)
 final                              :   1.78 (  1%)   0.05 (  1%)   1.79 (  1%)   73058 kB (  4%)
 early local passes                 :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)       0 kB (  0%)
 rest of compilation                :   2.25 (  1%)   0.04 (  1%)   2.33 (  1%)   64482 kB (  3%)
 repair loop structures             :   0.01 (  0%)   0.00 (  0%)   0.02 (  0%)       0 kB (  0%)
 TOTAL                              : 320.48          3.74        324.68        1902063 kB
322.67user 3.97system 5:27.17elapsed 99%CPU (0avgtext+0avgdata 3751416maxresident)k
56328inputs+131416outputs (192major+1027012minor)pagefaults 0swaps
```

**Comment by eguiraud** [comment]
Results of running `perf record --call-graph dwarf -F 99 $ROOTSYS/interpreter/llvm/src/bin/clang++ -c compile_20k.cxx (root-config --cflags)` with and without the extra `-stdlib=libc++` option: [flamegraphs.tar.gz](https://github.com/root-project/root/files/6172953/flamegraphs.tar.gz).

In particular the diff flamegraph shows that the gain when using libc++ is in less time spent in `llvm::MachineFunction::getOrCreateLandingPadInfo`.

**Comment by Axel-Naumann** [comment]
Just to complete the round-trip and to have even more motivation for the GCC folks: do we have any timings of libstdc++ vs libc++ *with GCC*? (Apologies if I overlooked them!)

**Comment by eguiraud** [comment]
@Axel-Naumann I get a segfault when I try to compile `compile_20k.cxx` with gcc + libc++ following the instructions at https://releases.llvm.org/11.0.0/projects/libcxx/docs/UsingLibcxx.html#using-libc-with-gcc, i.e.:

```bash
$ g++ -nostdinc++ -I/usr/include/c++/v1 compile_20k.cxx -nodefaultlib
s -lc++ -lc++abi -lm -lc -lgcc_s -lgcc -c $(root-config --cflags)
<tons of compile warnings>
g++: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report, ...
```

**Comment by eguiraud** [comment]
So to sum up what we know so far:

- the kind of code that RDF needs to jit takes very long to compile for large computation graphs, and requires a large amount of RAM
- cling jitting times are consistent with `clang++ -O0` compile times
- compile times of the generated code increase quickly (much faster than linearly) w.r.t. the number of lines of code (which increase linearly with the size of the computation graph)
- clang++ compile times for this kind of code are much lower than gcc's, independently of the STL used and the gcc version
- compile times of clang++ are much lower if libc++ is used instead of libstdc++
- turning on optimizations, even just `-O1`, with libstdc++, is completely unfeasible for this amount of jitted code
- with libc++, `-O1` might be ok, but `-O2` is not
- performance profiling of clang++ shows that the gain in compile times come from less time spent in `llvm::MachineFunction::getOrCreateLandingPadInfo` (see flamegraphs above)

@stwunsch am I forgetting anything?

**Comment by stwunsch** [comment]
Perfect summary! 🎉

**Comment by stwunsch** [comment]
> @Axel-Naumann I get a segfault when I try to compile `compile_20k.cxx` with gcc + libc++ following the instructions at https://releases.llvm.org/11.0.0/projects/libcxx/docs/UsingLibcxx.html#using-libc-with-gcc, i.e.:
> 
> ```shell
> $ g++ -nostdinc++ -I/usr/include/c++/v1 compile_20k.cxx -nodefaultlib
> s -lc++ -lc++abi -lm -lc -lgcc_s -lgcc -c $(root-config --cflags)
> <tons of compile warnings>
> g++: internal compiler error: Segmentation fault signal terminated program cc1plus
> Please submit a full bug report, ...
> ```

I also tried and completely failed already at figuring out all the compiler flags to make this work. I would mark this as "not feasible" 😅

**Comment by Axel-Naumann** [comment]
```
$ . ~/build/root/master/opt17/bin/thisroot.fish 
$ g++ -fsyntax-only -nostdinc++ -isystem /usr/lib/llvm-11/include/c++/v1 -I$ROOTSYS/include compile_10k.cxx
```
I should be able to provide these numbers...

**Comment by stwunsch** [comment]
Ok, here a rather reproducible setup, without `root-config` magic. The libc++ with g++ is still failing for me. However, g++ needs an incredible 7 minutes to compile the 10k LOC version!

```bash
$ # Environment
$ source /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/latest/x86_64-centos7-clang10-opt/setup.sh
$ which g++
/cvmfs/sft.cern.ch/lcg/releases/gcc/9.2.0-afc57/x86_64-centos7/bin/g++
$ which clang++
/cvmfs/sft.cern.ch/lcg/releases/clang/10.0.0-62e61/x86_64-centos7/bin/clang++

$ # clang++, libstdc++ vs libc++, all O0 (O1 takes too long)
$ # Using 10k LOC, results are not as clear with 1k LOC
$ /usr/bin/time clang++ -I$ROOTSYS/include -c compile_10k.cxx -std=c++17
35.35user 1.20system 0:36.88elapsed 99%CPU (0avgtext+0avgdata 1718068maxresident)k
$ /usr/bin/time clang++ -I$ROOTSYS/include -c compile_10k.cxx -std=c++17 -stdlib=libc++
26.25user 0.83system 0:27.35elapsed 99%CPU (0avgtext+0avgdata 1211268maxresident)k

$ # clang++, libc++, cross-check with Axel's compiler commands (removed -fsyntax-only)
$ /usr/bin/time clang++ -nostdinc++ -isystem /cvmfs/sft.cern.ch/lcg/releases/clang/10.0.0-62e61/x86_64-centos7/include/c++/v1 -I$ROOTSYS/include -c compile_10k.cxx -std=c++17
26.35user 1.15system 0:27.81elapsed 98%CPU (0avgtext+0avgdata 1202140maxresident)k

$ $ # g++, libstdc++ vs libc++, all O0, using same flags as clang++ above for the libc++ compilation
$ /usr/bin/time g++ -I$ROOTSYS/include -c compile_10k.cxx -std=c++17 -O0
460.24user 4.10system 7:45.41elapsed 99%CPU (0avgtext+0avgdata 3733544maxresident)k
$ /usr/bin/time g++ -nostdinc++ -isystem /cvmfs/sft.cern.ch/lcg/releases/clang/10.0.0-62e61/x86_64-centos7/include/c++/v1 -I$ROOTSYS/include -c compile_10k.cxx -std=c++17
g++: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
27.26user 2.31system 0:29.76elapsed 99%CPU (0avgtext+0avgdata 3381072maxresident)k
```

**Comment by eguiraud** [comment]
Thanks to Axel digging into clang's code generation, we understood that what clang doesn't deal with very well is a large amount of variable instantiations of types with non-trivial destructors in the same function body. In this scenario the list of exception-handling "landing pads"  grows to sizes that make compilation times blow up when generating code that deals with calling the destructors of these variables in case an exception is thrown in the function body. Presumably gcc suffers from a similar issue.

* on our side, a workaround seems possible: we can avoid allocating many temporary `std::string`s and `std::vector<std::string>`s by generating code of the form `Jit{Filter,Define}Helper(..., const char*[]{"col1", "col2"}, ...)` rather than `Jit{Filter,Define}Helper(..., std::vector<std::string>{"col1", "col2"}, ...)`. I'm working on a patch so Stefan can try this out on the original usecase.
* now that the mechanism behind the long compile times is understood, Axel will work on a standalone reproducer to try to push for a fix in upstream clang (and possibly gcc if we see the patch reduces gcc compile times too)

**Comment by stwunsch** [comment]
Here some first numbers benchmarking @eguiraud fix in #7651:

```bash
$ # Here the baseline, current master and a DF graph with about 20k nodes (note the ref in compile_ref.cxx!)
$ /usr/bin/time clang++ -c compile_ref.cxx $(root-config --cflags) -O0
2640.24user 13.10system 44:20.90elapsed 99%CPU (0avgtext+0avgdata 11602708maxresident)k

$ # The fix reduces the compile time massively! Note the opt in compile_opt.cxx!
$ /usr/bin/time clang++ -c compile_opt.cxx $(root-config --cflags) -O0
17.66user 0.73system 0:18.59elapsed 98%CPU (0avgtext+0avgdata 1366888maxresident)k

$ # O1 is still super slow, even with the fix
$ /usr/bin/time clang++ -c compile_opt.cxx $(root-config --cflags) -O1
2465.57user 4.72system 41:14.77elapsed 99%CPU (0avgtext+0avgdata 2146924maxresident)k
```

Here are the files and the diff bettween the ROOT versions:
[compile.tar.gz](https://github.com/root-project/root/files/6190560/compile.tar.gz)

**Comment by eguiraud** [comment]
Current status: O0 jitting times are fixed for master and 6.24. O1 jitting times are still high, to be investigated.

**Comment by eguiraud** [comment]
Work on reducing jitting times of large RDF computation graphs when cling is using O1 is being done at:

- https://github.com/root-project/root/pull/9328
- https://github.com/root-project/root/pull/9329
- https://github.com/root-project/root/pull/9342

Once these are all in we can re-check what the situation is in terms of O0 vs O1 but also clang++ vs cling (we have seen that in some cases cling is suspiciously slower to compile than clang++ -- to be reproduced with same underlying LLVM version and with the fixes above merged).

**Comment by eguiraud** [comment]
O1 jitting times are back to reasonable levels thanks to the PRs mentioned above, see https://rootbnch-grafana-test.cern.ch/d/G2qrd2SWk/rdataframe?orgId=1&viewPanel=42&from=1616924807235&to=1649407773511 . To improve RDF jitting times we would still like to see https://github.com/root-project/cling/issues/443 fixed.

Closing this.
