### ISSUE TITLE
Fix TMVA group links

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7627]
- [x] Checked for duplicates

### Describe the bug
In TMVA documentation at 
https://root.cern/doc/master/group__TMVA.html
there is a link "The full description of the Multi Variate Analysis package", which leads to 
http://tmva.sourceforge.net/

On that site it's written: "In 2013, TMVA was completely integrated into ROOT and is now released as part of it. The new official home can be found at the ROOT website (here). ", where the link "here" leads to
https://root.cern/tmva/
which doesn't exist. The same link is in TMVA's sourceforge page as "Project Page".

Also I note that in the [TMVA Reference guide](https://root.cern/doc/master/group__TMVA.html) there are links to 
The TMVA Users Guide.
The TMVA Options Reference,
that all lead to sourceforge.net (and they are both broken). Probably they should be moved to root.cern?

### Expected behavior
If the sourceforge link should be deleted, remove that. If it is relevant, then please fix the link to root.cern there or the page at root.cern/tmva .

**Comment by couet** [comment]
@lmoneta is there a way to modify the wrong links on: http://tmva.sourceforge.net/ ?

**Comment by ferdymercury** [comment]
maybe @helgevoss has access to https://sourceforge.net/projects/tmva/

**Comment by lmoneta** [comment]
I think we should remove any links to  http://tmva.sourceforge.net/ from the ROOT reference documentation

**Comment by guitargeek** [comment]
Yes, that's for sure, but what about the part of us changing the ROOT links on sourceforge? Do you have access to that?
