### ISSUE TITLE
[Doc] No syntax highlighting for Python in Doxygen

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7632]
We are missing syntax highlighting for Python code blocks in Doxygen, see the snippet from the RDataFrame docs below:

<img width="1062" alt="Screenshot 2021-03-22 at 09 12 19" src="https://user-images.githubusercontent.com/6951222/111959557-ec863500-8aee-11eb-8285-76e2557c40d1.png">

Afaik, the code block is correctly tagged with the language:

https://github.com/root-project/root/blob/master/tree/dataframe/src/RDataFrame.cxx#L447

**Comment by vepadulano** [comment]
I tried with  `~~~{.py}` on my local machine and it rendered the python blocks with highlighted syntax. It's still is quite poorly done compared to the cpp blocks, but I think that's just how doxygen does it

**Comment by vepadulano** [comment]
If you want I can open a PR with the changes

**Comment by stwunsch** [comment]
Ah nice, so it's the wrong keyword 😬 Thanks for pointing this out! I'll take care of it :)
