### ISSUE TITLE
`rootbench-benchJohnson` fills log with "use fixCoefNormalization!"

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7639]
### Describe the bug
Run rootbench's `rootbench-benchJohnson` and you will see plenty of
```
[#0] WARNING:Eval -- Evaluating RooAddPdf without a defined normalization set. This can lead to ambiguos coefficients definition and incorrect results. Use RooAddPdf::fixCoefNormalization(nset) to provide a normalization set for defining uniquely RooAddPdf coefficients!
```

### Expected behavior

No warnings.

### To Reproduce
`ctest -V -R rootbench-benchJohnson`

### Setup
Linux, master

**Comment by lmoneta** [comment]
See https://github.com/root-project/rootbench/pull/217
