### ISSUE TITLE
Provide in the cmake configuration the C++ standard which was used to compile ROOT

### ISSUE THREAD

**Issue by andriish** [root-project/root#7644]
Hi all,

It makes sense to compile software with ROOT using exactly the same C++ standard.
However, there is no nice way to obtain this information from ROOT cmake config.
Everything that is provided is a list of C++ flags.

### Describe the solution you'd like
Have a CMake variable ROOT_CXX_STANDARD in ROOT cmake config.

### Describe alternatives you've considered
Parsing the ROOT_CXX_FLAGS and hoping for the best.

Best regards,

Andrii

**Comment by amadio** [comment]
The better solution would be to improve `ROOTConfig.cmake` such that a given standard can be required when calling `find_package`, like `find_package(ROOT REQUIRED cxx17)`. That way, the extra steps of checking the variable are not needed, and ROOT won't be considered found if it uses C++11, for example.

**Comment by andriish** [comment]
Hi @amadio ,

that is an "active requirement". What I actually needed at some point is a "passive" information, an answer to a quaestion "What standard was used?". So these are similar, but yet different things.

Best regards,

Andrii

**Comment by andriish** [comment]
Hi @amadio ,

just found another code where people would benefit from this feature

https://github.com/acts-project/acts/blob/main/CMakeLists.txt

Best regards,

Andrii

**Comment by eguiraud** [comment]
+1. Since ROOT requires that downstream projects be compiled with the same C++ standard that was used for ROOT, ROOT should expose that standard as `ROOT_CXX_STANDARD`.

Many projects have to extract that information by regex-matching, e.g. https://gitlab.cern.ch/hepmc/HepMC3/-/blob/master/CMakeLists.txt#L153-171 .

**Comment by amadio** [comment]
ROOT's targets already export the C++ standard they were built with, so if you just link your project with ROOT using those targets, you already get the same C++ standard used in your code. Worst case, you can call `get_property` on a target to check this. However, exporting this in a variable as well can make it easier for users indeed, as calling `get_property` is a bit cumbersome.

**Comment by eguiraud** [comment]
> if you just link your project with ROOT using those targets

in reality most projects set their `CMAKE_CXX_STANDARD` which trumps the target's property.

>  you can call get_property on a target to check this

ah, that's already way better than regex-matching, thanks!

> exporting this in a variable as well can make it easier for users indeed

:+1:

**Comment by dpiparo** [comment]
hi @bellenot : would it be hard to expose the standard in a potential new ROOT_CXX_STANDARD variable in your opinion?

**Comment by amadio** [comment]
@bellenot If I understand correctly, what @dpiparo is suggesting is a simple

```cmake
set(ROOT_CXX_STANDARD @CMAKE_CXX_STANDARD@)
```
somewhere in `ROOTConfig.cmake.in`.

**Comment by bellenot** [comment]
@amadio Oh! You're right, sorry, I misunderstood the requirement... Will make a PR now. Thanks!

**Comment by bellenot** [comment]
> (P.S. don't forget to update https://root.cern/manual/integrate_root_into_my_cmake_project )

Right, thanks Enrico!

**Comment by bellenot** [comment]
@eguiraud Here is the PR for the doc: https://github.com/root-project/web/pull/938
