### ISSUE TITLE
Feature request: allow TH2Poly to be drawn with "AXIS" option

### ISSUE THREAD

**Issue by aaduszki** [root-project/root#7673]
I'd like to request option "AXIS" to be recognized when drawing TH2Poly objects, similarly to how it is recognized by other 2D histograms.
This option is useful, as when drawing 2D histogram with "col" option the top frame of the histogram becomes obscured with data. Redrawing it with "AXIS" seems to be a standard workaround.

**Comment by couet** [comment]
So in the following example it should draw only the axis. not the bin.
```
root [0] TH2Poly* h2pol = new TH2Poly("p2","p2",0,4,0,4);
root [1] Double_t x[4] = {0.,0.,2.,2.};
root [2] Double_t y[4] = {0.,2.,2.,0.};
root [3] TGraph *g = new TGraph(4,x,y);
root [4] h2pol->AddBin(g);
root [5] h2pol->Fill(1.,1.,-3);
root [6] h2pol->Draw("axis")
```

**Comment by aaduszki** [comment]
See https://root.cern/doc/master/classTHistPainter.html#HP20a 
AXIS option is not listed for TH2Poly.
If I run your code under ROOT 6.22/06 I get the attached figure (c1.png)
![c1](https://user-images.githubusercontent.com/55505042/112357480-91467500-8c9d-11eb-9f04-4bbf630ecafe.png)
As you can see, a frame is drawn around the bin. What happens in fact, and what is not seen, since the code example fills the histogram with a negative value, is that what is drawn is a scatter plot. If I extend the code as follows:
`TH2Poly* h2pol = new TH2Poly("p2","p2",0,4,0,4);
Double_t x[4] = {0.,0.,2.,2.};
Double_t y[4] = {0.,2.,2.,0.};
TGraph *g = new TGraph(4,x,y);
h2pol->AddBin(g);
h2pol->Fill(1.,1.,-3);

Double_t x2[4] = {1.,1.,3.,3.};
Double_t y2[4] = {2.,4.,4.,2.};
TGraph *g2 = new TGraph(4,x2,y2);
h2pol->AddBin(g2);
h2pol->Fill(2.,3.,3);
h2pol->Draw("axis")`
I get the following picture which clearly demonstrates it
![c2](https://user-images.githubusercontent.com/55505042/112357745-ceab0280-8c9d-11eb-8167-3b3b2cd603bb.png)
So if I draw h2pol with "AXIS" option, it is simply ignored, and a scatter plot is drawn.

**Comment by couet** [comment]
[This PR](https://github.com/root-project/root/pull/7690) implements the option AXIS for TH2Poly.
