### ISSUE TITLE
Potential double-deletion in `CPyCppyy::CPPMethod::Destroy_`

### ISSUE THREAD

**Issue by linev** [root-project/root#7692]
This method called from `CPyCppyy::CPPMethod` destructor, but also from assign operator.
Means it is strongly advisable to clear pointers to avoid potential use of destroyed objects.
Also `fConverters` must be cleaned.

Indirectly discovered via DeepCode analyzers:

**Comment by linev** [comment]
Same problem exists in pyroot_lagcy/src/TMethodHolder.cxx,
seems to be same problem was inherited into new code

**Comment by eguiraud** [comment]
@linev @etejedor please add a "fixed in:" project here

**Comment by linev** [comment]
It will be fixed in 6.26, but there is no such tag

**Comment by eguiraud** [comment]
There is, added :+1:

**Comment by linev** [comment]
Sorry, I was looking in labels
