### ISSUE TITLE
[VecOps] Make free functions in VecOps better visible

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7699]
- If I understood correctly we have to add the functions correctly to a VecOps group in Doxygen so that they show up if you use the search.
- Add more information in the `\defgroup` section.

**Comment by stwunsch** [comment]
Reopening, we have to check that the PR behaves as expected.

**Comment by stwunsch** [comment]
@eguiraud What do you thinks, good like that? -> https://root.cern/doc/master/group__vecops.html

**Comment by stwunsch** [comment]
I've no idea how to make the preproc macros look nicer or even expand them properly :/

**Comment by eguiraud** [comment]
We can either "expand" the macros manually (i.e. get rid of the macros), or maybe better we can explicitly write doxygen strings for them using the `\fn` Doxygen command and similar

**Comment by stwunsch** [comment]
Expanding the macros would result in a massive code duplication, see https://github.com/root-project/root/blob/master/math/vecops/inc/ROOT/RVec.hxx#L607-L695

So adding manual docs would be the solution, i guess!

**Comment by dpiparo** [comment]
Fixed by https://github.com/root-project/root/pull/15277
