### ISSUE TITLE
Add a Tutorial for IntegratorMultiDim

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7740]
### Explain what you would like to see improved
There is a class for multidimensional integration, [IntegratorMultiDim](https://root.cern/doc/master/classROOT_1_1Math_1_1IntegratorMultiDim.html).
From that it's very hard to understand how to use that (in particular, what function should be passed to that and how). 

### Optional: share how it could be improved
Please add examples how to use that. 
In its class description and probably to tutorials (they don't contain any code with that class).

### Additional context
There was a [discussion on the ROOT Forum](https://root-forum.cern.ch/t/multi-dimensional-adaptive-integration/7663/3) with a ready good example. It was promised that people are working on the documentation, but it seems to be forgotten since then.

**Comment by couet** [comment]
What about including [this](https://root.cern/root/htmldoc/guides/users-guide/ROOTUsersGuide.html#numerical-integration) in the reference guide on [this page](https://root.cern/doc/master/group__Integration.html). @lmoneta what do you think ?

**Comment by lmoneta** [comment]
Hi, 
There is some documentation in the ROOT Users guide, see 
https://root.cern.ch/root/htmldoc/guides/users-guide/ROOTUsersGuide.html#numerical-integration

Maybe it is not too visible, and I agree @couet we should probably include in the DOxygen description of the Integration classes. 
We are also missing a tutorial on the INtegratorMultiDim and we should add one befoe closing this issue
