### ISSUE TITLE
[DF] Add Open Data benchmarks

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7745]
We should add the infamous Open Data benchmarks to rootbench. Originally meant to showcase the DF programming model (see https://github.com/stwunsch/opendata-benchmarks), it went now a little bit out of hand and it's used for measuring ROOT performance (see the fork here https://github.com/masonproffitt/opendata-benchmarks and the forum entry here https://root-forum.cern.ch/t/scalability-of-rdataframes-on-16-cores/44222).

At the end, they have nice properties, which we should profile, like a significant amount of jitted code and quite a lot of allocations due to the missing SBO in RVec.

**Comment by eguiraud** [comment]
Shouldn't this issue be in rootbench?
