### ISSUE TITLE
[RF] Correlation plot from RooFitResult

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#7821]
### Is your feature request related to a problem? Please describe.
When users fit something, they always have read off correlations from the terminal after printing the fit result.

### Describe the solution you'd like
`RooFitResult::createCorrelationPlot()` or similar.
Create a 2D histogram, fill it with the correlation values. Label the axes with the parameter names, and plot them using coloured bins and text. Or just create the histogram and users can plot it themselves.
You can take inspiration from the TMVA Gui.

### Describe alternatives you've considered
Maybe one can plot the TMatrix that RooFitResult can produce, but I didn't investigate.

**Comment by cburgard** [comment]
RooFitResult already has the `correlationHist` method - what's wrong with that?

**Comment by hageboeck** [comment]
I didn't find it in the docs ...
