### ISSUE TITLE
[DF] Introduce GetDataSourceInfo and add info to Describe

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7828]
The idea is to have an identifier that describes the used datasource (or TTree or simple DF), make this info accessible as public API and also add it to `Describe`. See the discussion here:

https://github.com/root-project/root/issues/7561#issuecomment-817629082

https://github.com/root-project/root/issues/7561#issuecomment-817717882

Remember to make the identifier returned by this API subject to change because it's for interactive use and not to be parsed automatically.

**Comment by stwunsch** [comment]
@eguiraud @vepadulano What do you think about `GetDataSourceInfo`? Look here at the test of the linked PR:

```cpp
TEST(RDataFrameInterface, GetDataSourceInfo)
{
   // trivial/empty datasource
   ROOT::RDataFrame df1(1);
   EXPECT_EQ(df1.GetDataSourceInfo(), "trivial datasource");

   // ttree/tchain datasource
   TTree tree("tree", "tree");
   ROOT::RDataFrame df2(tree);
   EXPECT_EQ(df2.GetDataSourceInfo(), "TTree datasource");

   // others with an actual fDataSource, like csv
   auto df3 = ROOT::RDF::MakeCsvDataFrame("RCsvDS_test_headers.csv");
   EXPECT_EQ(df3.GetDataSourceInfo(), "RCsv");
}
```

**Comment by vepadulano** [comment]
I think it's the right way to go, maybe the ttree datasource could be further specialized to distinguish between TTree and TChain.
But, a more notable absence in this logic is horizontal extensions to the dataset, e.g. friends in the case of TTree.

So if we imagine this function to be just "giving an hint about the type of container for the dataset of this RDataFrame", then it's already good as it is imho.

If we want something more detailed, like "this dataframe will run its computations on a dataset named XXX, stored in a container of type YYY placed at ZZZ", then we're looking for more. For a ttree without friends, this would translate to

    XXX = name of the tree
    YYY = ROOT file / TFile
    ZZZ = path to the ROOT file
    And for a csv table it would be
    XXX = None
    YYY = CSV file
    ZZZ = path to the csv file

If the dataset is horizontally extended through e.g. friends, then the information above is not sufficient to identify the full dataset RDataFrame will run its computations on. For a ttree, we would also need to print out XXX,YYY,ZZZ for any friend of the tree. So what I'm saying is that we either give very high level info about data (which I would prefer), or we have to go really deep down to be consistent with any datasource type

**Comment by stwunsch** [comment]
Take care, we want to split the info about the datasource and the dataset! So the datasource could distinguish between TTree and TChain, I think, and then other info should go into the dataset. Also full paths are potentially quite long and bulky, I'm not sure we want to put this in right there.

**Comment by stwunsch** [comment]
As an example, a typical filename you'll find, even without any xrootd/whatever identifier in front: `/ceph/htautau/deeptau_eoy/2018/ntuples/GluGluHToTauTauHTXSFilterSTXS1p1Bin101M125_RunIIAutumn18MiniAOD_102X_13TeV_MINIAOD_powhegpythia8_v2/GluGluHToTauTauHTXSFilterSTXS1p1Bin101M125_RunIIAutumn18MiniAOD_102X_13TeV_MINIAOD_powheg-pythia8_v2.root`

**Comment by vepadulano** [comment]
You are right, indeed I got confused between the names of the two different functions we want to add to the API. According to the reasoning I made in [this comment](https://github.com/root-project/root/issues/7561#issuecomment-817863318), I think the function described in this issue should just return the name of the data format for the current dataset.
Which means that in my opinion:
* For a TTree/TChain, this function should return "TTree"
* For an empty RDF with entries, it should return "None" or "Trivial" or "SequentialEntries"
* For an RNTuple it should return "RNTuple"
* For a dictionary of numpy arrays, something like "NumpyArrays"
* For an arrow file, "ApacheArrow"

and so on

**Comment by stwunsch** [comment]
All `RDataSource` based datasources are responsible by themselves to return something feasible via the `RDataSource::GetLabel` interface. I can only put the `TTree` and `trivial/empty/whatever` return values.

**Comment by stwunsch** [comment]
Moving the discussion to #7829, merging those two feature requests into one.
