### ISSUE TITLE
[DF] Introduce GetDatasetInfo and add info to Describe

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7829]
The idea is to have an identifier that describes the used dataset (name of the TTree or similar), make this info accessible as public API and also add it to `Describe`. See the discussion here:

https://github.com/root-project/root/issues/7561#issuecomment-817629082

https://github.com/root-project/root/issues/7561#issuecomment-817717882

Remember to make the identifier returned by this API subject to change because it's for interactive use and not to be parsed automatically.

**Comment by stwunsch** [comment]
@vepadulano @eguiraud Same story here, what do you think about `GetDataSetInfo`? See the test here:

```cpp
TEST(RDataFrameInterface, GetDataSetInfo)
{
   // trivial/empty datasource
   ROOT::RDataFrame df1a(1);
   EXPECT_EQ(df1a.GetDataSetInfo(), "1 empty row");

   ROOT::RDataFrame df1b(2);
   EXPECT_EQ(df1b.GetDataSetInfo(), "2 empty rows");

   // ttree/tchain datasource
   TTree tree("some name", "some title");
   ROOT::RDataFrame df2(tree);
   EXPECT_EQ(df2.GetDataSetInfo(), "some name");

   // others with an actual fDataSource, like csv
   auto df3 = ROOT::RDF::MakeCsvDataFrame("RCsvDS_test_headers.csv");
   EXPECT_EQ(df3.GetDataSetInfo(), "not available");
}
```

What about the name `GetDataSetInfo`, note the capitalising! What should we return for an `fDataSource`?

**Comment by vepadulano** [comment]
Ok so I was previously a bit confused about the differences between this issue and https://github.com/root-project/root/issues/7828, the [comment](https://github.com/root-project/root/issues/7828#issuecomment-817820448) I posted there is more relevant here indeed. Please also see [this comment](https://github.com/root-project/root/issues/7561#issuecomment-817863318) that is relevant for both issues.

**Comment by stwunsch** [comment]
But what should we return for `RDataSource` based datasets? We don't have any information there!

**Comment by stwunsch** [comment]
We agreed that we want `GetDataSourceInfo` (or a function with another name?) should return info about the datasource **and** the dataset, like `Dataset "Events" from the TTree "/path/to/my/tree.root"`.

**Comment by stwunsch** [comment]
@eguiraud @vepadulano New proposal is up! Here a summary:

```python
df = ROOT.RDataFrame(42)
print(df.GetDataSetInfo())
```

```
Empty dataframe filling 42 rows
```

```python
df = ROOT.RDF.MakeCsvDataFrame("foo.csv")
print(df.GetDataSetInfo())
```

```
Dataframe from datasource RCsv
```

```python
df = ROOT.RDataFrame("tree", "file1.root")
print(df.GetDataSetInfo())
```

```
Dataframe from TChain tree in file file1.root
```

```python
df = ROOT.RDataFrame("tree", ("file1.root", "file2.root"))
print(df.GetDataSetInfo())
```

```
Dataframe from TChain tree in files
  file1.root
  file2.root
```

```python
def get_tree(filename):
    f = ROOT.TFile(filename)
    t = f.Get("tree")
    return f, t

f1, t1 = get_tree("file1.root")
f2, t2 = get_tree("file2.root")
f3, t3 = get_tree("file3.root")

t1.AddFriend(t2)
t1.AddFriend(t3, "myAlias")
c = ROOT.TChain("tree")
c.AddFile("file4.root")
c.AddFile("file5.root")
t1.AddFriend(c, "anotherAlias")
df = ROOT.RDataFrame(t1)
print(df.GetDataSetInfo())
```

```
Dataframe from TTree tree in file file1.root
with friends
  tree file2.root
  tree (myAlias) file3.root
  tree (anotherAlias) file4.root file5.root
```

**Comment by vepadulano** [comment]
Nice additions! Two comments
1. I believe the csv data source should also show the filename, in accordance with the ttree. This really should be the same for all data sources
2. Once the dataset is scattered along many files, the printed output is gonna become very heavy (possibly also costly to retrieve?). I'm thinking for example at a tree made of 100s of files on EOS

**Comment by stwunsch** [comment]
> Nice additions! Two comments
> 
> 1. I believe the csv data source should also show the filename, in accordance with the ttree. This really should be the same for all data sources

Regarding the CSV datasource: AFAIK, the datasource does not publish this information. I won't change this in this PR.

> 2. Once the dataset is scattered along many files, the printed output is gonna become very heavy (possibly also costly to retrieve?). I'm thinking for example at a tree made of 100s of files on EOS

To my understanding, we don't go to the file (or remote to EOS) at all, all the information is already around in RDataFrame. SO it's not really costly.

**Comment by stwunsch** [comment]
@vepadulano I've integrated the support for subnames in TChains, see the adapted output at the bottom of the summary above.

**Comment by stwunsch** [comment]
Finally, I would add this to the top of `Describe`. What do you think?

**Comment by vepadulano** [comment]
> @vepadulano I've integrated the support for subnames in TChains, see the adapted output at the bottom of the summary above.

Looks ok thanks!

> Finally, I would add this to the top of Describe. What do you think?

I think it's the correct place, although my previous doubt still stands: if a tree has 100s of files the output would become very long, although it's a similar problem to the case where the dataset has 1000s of columns that we already discussed

**Comment by stwunsch** [comment]
Yep true. In these extreme cases the output will explode. But then you probably want to put the string anyway in a file, or add it to your logs.

Eventually, we could add a flag like `Describe(bool reducedOutput=true)` and `GetDataSetInfo(bool reducedOutput=true)`. Like for printing `pandas.DataFrame` or similar. But that can be added also in the future.

**Comment by stwunsch** [comment]
@Axel-Naumann @eguiraud @vepadulano I would love to trigger a last discussion about the name. We have up to now two options:

- `GetDataSetInfo`
- `DescribeDataset`

Note that we plan to put the output of this function in front of the current output of `Describe`. Therefore the specialized `DescribeDataset` makes sense.

What's your opinion?

**Comment by eguiraud** [comment]
I like `DescribeDataset`

**Comment by vepadulano** [comment]
After the latest additions to the output of this function, I would agree with `DescribeDataset` as well. What about the capitalization `DataSet` vs `Dataset` :sweat_smile: ? I would lean towards the second

**Comment by eguiraud** [comment]
both "dataset" and "data set" are valid spellings, so both `DescribeDataset` and `DescribeDataSet` are valid method names. On one hand we have the precedent of `MakeCsvDataFrame` & similar, on the other that was maybe not the best choice of capitalization. `DescribeDataset` is easier to read and type, I'd go for that.

**Comment by stwunsch** [comment]
I'm also for `DescribeDataset`, with this spelling.

**Comment by stwunsch** [comment]
@Axel-Naumann @etejedor I give you today to make up your mind ;) Tomorrow at this time it's in!

**Comment by etejedor** [comment]
I second your decision :smile:
