### ISSUE TITLE
Improve TMatrix reference documentation

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#7845]
As reported in https://root-forum.cern.ch/t/tmatrixd-documentation/44389the documentation of TMatrix needs to be improved. We need to: 

- Add a link from TMatrixD and TMatrixF (typedef definition pages, see  https://root.cern.ch/doc/master/TMatrixDfwd_8h.html#aa2e948a208b6c139cf8a93eed078edbb ) to the documentation page of the template class TMatrixT (see https://root.cern.ch/doc/master/classTMatrixT.html)
- Improve the TMatrixT doc page and fix the link to the Matrix Web page doc (see https://root.cern.ch/doc/master/group__Matrix.html)

**Comment by dpiparo** [comment]
This has been addressed, e.g. looking at the documentation https://root.cern.ch/doc/master/classTMatrixT.html
