### ISSUE TITLE
TExecutorCRTP::Map() should support void

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#7872]
### Explain what you would like to see improved
You are always forced to return a dummy value when using TExecutorCRTP::Map().

### Optional: share how it could be improved
- `void` should be supported.
- Alternatively, add a `static_assert` somewhere, because the instantiation failures are spectacularly long for such a simple mistake.

### To Reproduce
```c++
void runParallel() {
  ROOT::Internal::TExecutor ex; 
  constexpr std::size_t nTotal = 101;

  const auto nChunk = ROOT::IsImplicitMTEnabled() ? ex.GetPoolSize() : 1u; 
  auto printRange = [=](std::size_t i) {
    const auto nEvent = nTotal / nChunk + (nTotal%nChunk != 0); 
    const auto begin = nEvent * i;
    const auto end = std::min( nEvent * (i+1), nTotal);

    std::cout << "[" << i << "] does " << begin << "\t" << end << std::endl; sleep(1);

    // Comment in to make it compile
    //return 0;
  };  
  ex.Map(printRange, ROOT::TSeq<std::size_t>(0, nChunk));
}
```

**Comment by eguiraud** [comment]
I think in ROOT we call things that do N -> N "Map" and things that do N -> void "Foreach". TExecutor should expose a `Foreach`, I am not sure why it does not (e.g. `TSequentialExecutor` and `TThreadExecutor` have it).

**Comment by hageboeck** [comment]
Yes, `ForEach` would be OK as well.

**Comment by hahnjo** [comment]
https://github.com/root-project/root/pull/14694 adds a check that the return type is not `void`. For `TExecutorCRTP::ForEach`, I guess the reason is that `TProcessExecutor` doesn't implement it right now. I personally think, until there is more popular demand, I think it's fine to have this only in `TThreadExecutor`.
