### ISSUE TITLE
Invalid read in TClassEdit

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#7903]
- [x] Checked for duplicates

### Describe the bug
TClassEdit reads behind the end of a static string to find the type of an STL container.
This breaks address sanitizer builds, because asan immediately stops at the invalid read when rootcling runs.

### Expected behavior
It shouldn't read after the end of the string.

### To Reproduce
Apply this patch:
```
--- a/core/foundation/src/TClassEdit.cxx
+++ b/core/foundation/src/TClassEdit.cxx
@@ -13,6 +13,7 @@
  * For the list of contributors see $ROOTSYS/README/CREDITS.             *
  *************************************************************************/
 
+#include <array>
 #include <cstdio>
 #include <cstdlib>
 #include <cassert>
@@ -557,7 +558,9 @@ ROOT::ESTLType TClassEdit::STLKind(std::string_view type)
 
 int   TClassEdit::STLArgs(int kind)
 {
-   static const char  stln[] =// min number of container arguments
+   constexpr int nKind = 14;
+   assert(kind < nKind);
+   static constexpr std::array<char, nKind> stln = // min number of container arguments
       //     vector, list, deque, map, multimap, set, multiset, bitset,
       {    1,     1,    1,     1,   3,        3,   2,        2,      1,
       // forward_list, unordered_set, unordered_multiset, unordered_map, unordered_multimap
```

Then build in debug mode. The assertion will fail when RVec shows up in this function, since it is not an STL container.

### Setup
master

Sorry, I didn't check which other versions are affected.

**Comment by pcanal** [comment]
> TClassEdit reads behind the end of a static string to find the type of an STL container.

Do you mean that it **does** read behind the end of that the address sanitizer "fears" the code "might"?   If it is the earlier then I am missing how the patch (which it self seem fine) would change anything.

**Comment by eguiraud** [comment]
IIUC the patch is not a fix, it's to expose the problem even without using asan.

I guess we need to update `TClassEdit::STLArgs` to support RVec, we forgot when moving it to the collection proxy mechanism.

**Comment by eguiraud** [comment]
This is probably a fix:

```patch
diff --git a/core/foundation/src/TClassEdit.cxx b/core/foundation/src/TClassEdit.cxx
index a45b431a5d..bb3d06b4b5 100644
--- a/core/foundation/src/TClassEdit.cxx
+++ b/core/foundation/src/TClassEdit.cxx
@@ -560,8 +560,8 @@ int   TClassEdit::STLArgs(int kind)
    static const char  stln[] =// min number of container arguments
       //     vector, list, deque, map, multimap, set, multiset, bitset,
       {    1,     1,    1,     1,   3,        3,   2,        2,      1,
-      // forward_list, unordered_set, unordered_multiset, unordered_map, unordered_multimap
-                    1,             3,                  3,             4,                  4};
+      // forward_list, unordered_set, unordered_multiset, unordered_map, unordered_multimap, ROOT::RVec
+                    1,             3,                  3,             4,                  4,          1};

    return stln[kind];
 }
```

**Comment by hageboeck** [comment]
> IIUC the patch is not a fix, it's to expose the problem even without using asan.
> 
> I guess we need to update `TClassEdit::STLArgs` to support RVec, we forgot when moving it to the collection proxy mechanism.

That's exactly right. I propose to leave the assert in place. It may get ugly if something like this gets forgotten again.

**Comment by hageboeck** [comment]
> > TClassEdit reads behind the end of a static string to find the type of an STL container.
> 
> Do you mean that it **does** read behind the end of that the address sanitizer "fears" the code "might"? If it is the earlier then I am missing how the patch (which it self seem fine) would change anything.

Address sanitizer doesn't fear, the algorithm cannot create false positives according to their paper. Here, we indeed read at index 14 in a string of 14 chars.

**Comment by pcanal** [comment]
> the algorithm cannot create false positives according to their paper

Except for implementation bugs on their part ... and developer ingenuity to create code that looks and smell wrong but is intentiona (ly evil :) )  :)

> IIUC the patch is not a fix, it's to expose the problem even without using asan.

hack .. I overlooked the "title" ('To reproduce')

**Comment by pcanal** [comment]
@eguiraud Can you propose a PR that add RVec and add an assert?

**Comment by eguiraud** [comment]
I'll put it on the pile...
