### ISSUE TITLE
TStreamerInfo Crash - V5 File Backward incompatibility introduced somewhere since 6.22.00

### ISSUE THREAD

**Issue by will-cern** [root-project/root#7912]
We've discovered a bug in the backward compatibility of ROOT, which we hope can be fixed ASAP.

Simply opening the attached root file (`root workspace
[workspace.root.zip](https://github.com/root-project/root/files/6334250/workspace.root.zip)
.root` or otherwise) works fine in 6.22.00 but fails in 6.22.06 and master. **ROOT Crashes** which is definitely a bug, right?

I've traced the problem to https://github.com/root-project/root/blob/94a9ef70c5df97b4144a2963111702a0dcb65214/io/io/src/TStreamerInfo.cxx#L1594 ... the problem is that `old->GetValueClass()` ends up being a nullptr.

Something was introduced into 6.22 branch and master branch in the past 12 months that makes this null. I am hoping a developer working on this area of the project will have an idea what's happened here!

Thanks!
Will

**Comment by pcanal** [comment]
I can reproduce the problem.  The fix will be available shortly.

**Comment by pcanal** [comment]
The problem was introduced when we stopped creating `TClass` for pair of 'unknown' types (as those type could be enums or classes, or who knows what :) ).
