### ISSUE TITLE
Memory leak when using MemPoolForRooSets

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#7933]
The memory leak reported in #7890 is related to use MemPoolForRooSets.

This simple code shows the increase of memory when using MemPoolForRooSets. 
```
void testMemPool() {

   RooRealVar x("x","x",0,10);
   RooRealVar y("y","x",0,10);

   ProcInfo_t pinfo; 

   for (int i = 0; i < 1000000000; ++i) {
      if (i % 100000 == 0) {
         gSystem->GetProcInfo(&pinfo);
         std::cout << i << "  memory usage " << pinfo.fMemResident << "  " << pinfo.fMemVirtual << std::endl;
      }
      auto s1 = new RooArgSet(x,y);

      delete s1;

   }

}

```

**Comment by guitargeek** [comment]
A solution is proposed in https://github.com/root-project/root/pull/7935.

For the minimum example to reproduce the error, one doesn't need the linked list and it's helpful to do the print every 60000 iterations to be a multiple of the arena size (otherwise one also observes cyclic memory increase that is difficult to distinguish from the leak).

```C++
void testDelete(int nmon = 6000, int offset = 0) {

   RooRealVar x("x","x",0,10);
   RooRealVar y("y","x",0,10);

   ProcInfo_t pinfo;

   for (int i = 0; i < 1000000000; ++i) {
      if (i % 60000 == offset) {
         gSystem->GetProcInfo(&pinfo);
         std::cout << i << "  memory usage " << pinfo.fMemResident << "  " << pinfo.fMemVirtual << std::endl;
      }
      auto s1 = new RooArgSet{x,y};
      delete s1;
      s1 = nullptr;
   }
}
```

**Comment by guitargeek** [comment]
After the PR, there are still occasional memory increases left when the vector holding the arena is resized. this can be verified by adding some debug output to [MemPoolForRooSets::addArena](https://github.com/guitargeek/root/blob/master/roofit/roofitcore/src/MemPoolForRooSets.h#L267):
```C++
  void newArena() {
    std::vector<Arena> failedAllocs;
    while (true) {
      Arena ar;
      if (std::none_of(fArenas.begin(), fArenas.end(),
          [&ar](Arena& other){return ar.memoryOverlaps(other);})) {
        auto oldCapacity = fArenas.capacity();
        fArenas.push_back(std::move(ar));
        if(fArenas.capacity() != oldCapacity) {
          std::cout << "fArenas capcity increased from " << oldCapacity << " to "
                    << fArenas.capacity() << " (sizeof(Arena) = "
                    << sizeof(Arena) << ")" << std::endl;
        }
        break;
      }
      else {
        failedAllocs.push_back(std::move(ar));
      }
    }
  }
```

**Comment by lmoneta** [comment]
HI, 
Still after #7935, without any memory leak, as shown in the code above after this commit,  the number of arena created over time will continue to increase and also the used memory. 
I see now  2 possible solutions: 
- call RooArgSet::cleanup() more often (for example every toy  generated and analysed in ToyMCSampler). This is ok for RooStats but we cannot control user code. 
- revert #2866.  This will cause probably some crashes on exiting, are these acceptable ?

**Comment by guitargeek** [comment]
This issue can be closed once all the backports are merged:
* 6.18: https://github.com/root-project/root/pull/7972
* 6.20: https://github.com/root-project/root/pull/7973
* 6.22: https://github.com/root-project/root/pull/7974
* 6.24: https://github.com/root-project/root/pull/7975
