### ISSUE TITLE
RColor must be able to be constructed as "0.2" from RPalette

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7959]
### Explain what you would like to see improved

`RColor` currently has rgb etc - but it cannot reference a value from 0..1 ("ordinal") from the `RPad`'s `RPalette` - and it should! This should *not* set rgb - it should just be a different `RColor` "identity" and only use the ordinal.

**Comment by linev** [comment]
Issue was resolved by: https://github.com/root-project/root/pull/8109
