### ISSUE TITLE
RooAddPdf constructor not properly picked up by RooWSFactoryTool

### ISSUE THREAD

**Issue by cburgard** [root-project/root#7965]
Consider the following code snippet:

    nbkg = 10000
    nsig = 100
    masses = [125,400]
    
    import ROOT
    ws = ROOT.RooWorkspace("workspace")
    m = ws.factory("m[0,1000]")
    bkg_shape = ws.factory("RooExponential::bkg_shape(m,c_bkg[-0.005])")
    bkg = ws.factory("RooExtendPdf::bkg(bkg_shape,n_bkg[{:f},0,{:f}])".format(nbkg,2*nbkg))
    
    bkgdata = bkg.generate(m,nbkg)
    bkgdata.SetName("asimov_0")
    ws.Import(bkgdata)
    
    funcs = ROOT.RooArgList()
    funcs.add(bkg)
    for i in range(0,len(masses)):
        sig_shape = ws.factory("RooGaussian::sig_shape_{:d}(m,m_{:d}[{:f},0,1000],sigma_{:d}[10,1e-6,100])".format(i,i,masses[i],i))
        sig = ws.factory("RooExtendPdf::sig_{:d}(sig_shape_{:d},n_sig_{:d}[{:f},0,{:f}])".format(i,i,i,nsig,2*nsig))
        funcs.add(sig)
    mainPdf = ws.factory("RooAddPdf({"+",".join([f.GetName() for f in funcs])+"})")

The last line results in 

    [#0] ERROR:ObjectHandling -- RooFactoryWSTool::createArg() ERROR number of arguments provided (1) for class is invalid, RooAddPdf expects 3
    [#0] ERROR:ObjectHandling -- RooFactoryWSTool::processExpression() ERRORS detected, transaction to workspace aborted, no objects committed

despite this constructor being available for RooAddPdf:

    RooAddPdf (const char *name, const char *title, const RooArgList &pdfList)

**Comment by lmoneta** [comment]
Similar problem is reported in 
https://root-forum.cern.ch/t/rooworkspace-with-overloaded-functions/46355

It looks like the internal function defined in RooWSFactoryTool.cxx:
  
`pair<list<string>,unsigned int> ctorArgs(const char* classname, UInt_t nMinArg)`

works only for the first non trivial constructor .
