### ISSUE TITLE
TColor doc html tag issues "a name"

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#7996]
### Describe the bug
TColor shows several HTML rendering issues in the documentation:
https://root.cern.ch/doc/master/classTColor.html

![image](https://user-images.githubusercontent.com/10653970/116068598-68c4e880-a658-11eb-8089-4c28efa0ca9c.png)

### Expected behavior
no HTML tags are visible.

### To Reproduce
1. Enter https://root.cern.ch/doc/master/classTColor.html
2. Search for "<a name"

**Comment by couet** [comment]
This is fixed by https://github.com/root-project/root/pull/7951 . Just wait the ref guide is rebuild. It is building now.
