### ISSUE TITLE
RooAddPdf fails if pdfs have the same name

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#8000]
- [V] Checked for duplicates

### Describe the bug
RooAddPdf, if initialized with pdfs with the same name, is evaluated wrongly. It interprets all pdfs with the same name as the first of them (function and parameters are the same for all pdfs, while the coefficient is the proper one, as should be if that pdf was the corresponding pdf).

### Expected behavior

- pdfs must be operated as different C++ objects/pointers, not based on name. Otherwise
- pdfs with the same name must be forbidden. RooAddPdf must fail to initialize if some pdfs have the same name. RooAddPdf class description should specify that pdfs with the same name are not allowed.

### To Reproduce
I make a 3-dimensional parametric fit of the detector. I model its parts as cylinders, and there are many of them, so I simply copied some common initialization code. The reused pdfs were not simply summed in RooAddPdf, but they were inside RooProdPdf-s (those had distinct names).

Pdfs were different C++ objects and had different parameters. For different types of pdfs all converged well, but when I used 2 same pdfs (with the same name, but in absolutely different regions), the fit did not converge, and the plot was wrong.

When I plotted (separate pdf or with RooFit::Component of the total sum), it showed that one pdf got parameters of another pdf (even though it was outside its allowed range), though its normalization was as it should probably be. The total sum (the pdf I fitted) was also plotted wrongly.

I used RooAddPdf [constructor with RooArgList PdfList and RooArgList CoefList](https://root.cern.ch/doc/master/classRooAddPdf.html#acafcca576f7839c046bea7c9edf31c22), if that is important.

I think the easiest would be to create a new example from scratch. I can copy some code here if needed.

### Setup
1. ROOT version 6.22/06.
2. Arch Linux.
3. Built it myself.

**Comment by ynikitenko** [comment]
8000-th bug, congratulations, dear ROOTers! :)

**Comment by guitargeek** [comment]
Hi @ynikitenko, thanks for opening the issue!

Eventually, we want to find a general solution to this problem (see https://github.com/root-project/root/issues/7417), but this will be more complicated because of various cases that need to be considered (cloned pdfs with the same name for example).

In the meantime, I think it's fair to address this issue directly so we can exclude that `RooAddPdf` causes further confusion.
I have opened a PR where the last commit changes `RooAddPdf` such that it throws an exception when you pass it two distinct input pdfs with the same name: https://github.com/root-project/root/pull/8004.

**Comment by ynikitenko** [comment]
Hi, @guitargeek (Jonas)! Great news, I never imagined this would be fixed so soon! I understand that an architectural change will require big work and much testing (depending on how much is already covered).
I don't know whether I shall close it now or when you PR is accepted; feel free to close. Thanks again!

**Comment by guitargeek** [comment]
Hi Yaroslav! We usually keep the issues open until the PR that solves the issue got merged.

**Comment by ynikitenko** [comment]
Now I'm doing another thing, and return again to this issue.

I want to make a 3-dimensional fit, but some pdfs depend only on z, so I multiply them by uniform pdfs on x and y. I mean RooUniform for the whole domain of a variable, not what I proposed in https://github.com/root-project/root/issues/7880. So I create a uniform distribution like that

    RooUniform u_nt_x("u_nt_x", "u_nt_x", x);
    RooUniform u_nt_y("u_nt_y", "u_nt_y", y);
    RooProdPdf uxy_nt("uxy_nt", "uxy_nt", RooArgList(u_nt_x, u_nt_y));

So I have 5 pdfs for which I need to create a separate uniform distribution on (x, y), which in turn requires creation of new pdfs on x (and on y), which are all uniform and absolutely the same. This leads to 15 new lines of code, which is not that much, but seems redundant (as names and titles of the uniform distribution on all x) and even more error-prone (because of very similar code).

Maybe there must be a way to explicitly allow same pdfs, if you know that they are really identical ones with same parameters? Say a new class, RooRefPdf, RooCopyPdf, ... .
