### ISSUE TITLE
Impossible to understand what to `#include` for `ROOT::Math::PtEtaPhiMVector` etc

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#8051]
### Describe the bug

Entering `PtEtaPhiMVector` in Doxygen's search brings us here: https://root.cern/doc/master/namespaceROOT_1_1Math.html#a6cea5921731c7ac99dea921fb188df31 - the documentation of the typedef, which happens to be in `Vector4Dfwd.h`. That header cannot be included as `Vector4Dfwd.h` (but only as `ROOT/Vector4Dfwd.h` - *and* it doesn't provide the definition of this type!

### Expected behavior

Instead, the forward header should be reserved for the specialists, and documentation should point to `Vector4D.h`. It's fine if this header repeats the `typedef`s, and those in `Vector4Dfwd.h` are hidden from Doxygen. In the end, Doxygen's search should get me to the header that I need to `#include`, as a user, to access `PtEtaPhiMVector`, and it should be obvious how to see `PtEtaPhiMVector`'s members.

**Comment by ynikitenko** [comment]
I had similar but different issues with includes:

- impossible to understand what class is included, https://github.com/root-project/root/issues/7440#issuecomment-820603357,
- impossible to understand from what namespace it comes (MathCore or Mathmore), https://github.com/root-project/root/issues/7440#issuecomment-821018950.

**Comment by Axel-Naumann** [comment]
Thanks, better! Still, I'd like to hear your counterargument on:

> Instead, the forward header should be reserved for the specialists, and documentation should point to Vector4D.h. It's fine if this header repeats the typedefs, and those in Vector4Dfwd.h are hidden from Doxygen. In the end, Doxygen's search should get me to the header that I need to #include, as a user, to access PtEtaPhiMVector, and it should be obvious how to see PtEtaPhiMVector's members.

**Comment by lmoneta** [comment]
@Axel-Naumann : see my comment in #8224. I will not merge it and then close this issue

**Comment by dpiparo** [comment]
Adter looking at the doc online and after discussing with @lmoneta , I understand this is now fixed and the issue can be closed.
