### ISSUE TITLE
[JupyROOT] Notebook hangs when importing ROOT first from a secondary process

### ISSUE THREAD

**Issue by etejedor** [root-project/root#8055]
To reproduce, in a Python notebook:

```python
def foo():
  import JupyROOT  # or import ROOT
  print("foo")

import multiprocessing
p = multiprocessing.Process(target=foo)
p.start()
p.join() # hangs here
```

If ROOT is imported in the main kernel process of Jupyter, the issue does not happen. This might have to do with initializing JupyROOT in a process that is not the main kernel process.

EDIT: reported by @daritter

**Comment by daritter** [comment]
Ok, I think I found the issue. It's the `StreamCapture` IO `Poller`. Not sure what exactly is going wrong but adding `daemon=True` to the Thread constructor arguments in `handlers.py:79` seems to fix it for me.

`daemon=True` will cause python3 to exit automatically if that is the last remaining thread so something is not shutdown correctly if it's not the main thread.
