### ISSUE TITLE
Terminal flooded with cmake warnings when building with ninja+cmake 3.20

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#8060]
### Describe the bug

The warnings look like this:

```
CMake Warning (dev) at interpreter/llvm/src/cmake/modules/TableGen.cmake:70 (add_custom_command):
  Policy CMP0116 is not set: Ninja generators transform DEPFILEs from
  add_custom_command().  Run "cmake --help-policy CMP0116" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.
Call Stack (most recent call first):
  interpreter/llvm/src/include/llvm/IR/CMakeLists.txt:2 (tablegen)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by vgvassilev** [comment]
Could you try this patch https://reviews.llvm.org/rG638d84b60b7e7b7fa9099939ab4de2ec1e0c52c3 ?

**Comment by eguiraud** [comment]
Hi, I'll check as soon as possible, however, `cmake_policy` is exactly what is used to silence such warnings so I bet it does the job.

**Comment by vgvassilev** [comment]
@eguiraud if you have it already, could you open a PR?

**Comment by eguiraud** [comment]
@vgvassilev so is it ok to add `cmake_policy(SET CMP0116 OLD)` to `interpreter/llvm/src/cmake/modules/TableGen.cmake`?

**Comment by vgvassilev** [comment]
As long as it is a backport from LLVM (which I think it is) it is totally fine as this won't increase our llvm technical debt.

**Comment by eguiraud** [comment]
Ok then we should try to make this an actual backport of that patch. The llvm patch adds the `cmake_policy` command to `llvm/CMakeLists.txt`. Is the corresponding file in our source tree `interpreter/llvm/src/CMakeLists.txt`?

**Comment by vgvassilev** [comment]
Yep, that is it.
