### ISSUE TITLE
Gracefully error out if application compiling against ROOT is using a different C++ standard than the one with which ROOT was built

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#8063]
A very common source of confusion for users is compilation errors coming from ROOT when the C++ standard they use to compile their application is different from the C++ standard with which ROOT was compiled. Some examples:

- https://root-forum.cern.ch/t/solution-for-rstringview-hxx37-error/44639
- https://mattermost.web.cern.ch/root/pl/xiyid5urd7nqtgt381czew1wso
- https://root-forum.cern.ch/t/compiler-error-related-to-c-17-string-view-with-gcc9-1/34727

It would be nice if we could catch this case in a frequently-included header or similar and provide a human-friendly error message instead.

**Comment by Axel-Naumann** [comment]
We might not need a general version compat check - but we absolutely need it for our backports - i.e. checking whether the selection "libstd vs backport" is identical for ROOT's configuration time and user code include.

**Comment by andriish** [comment]
Related to #7644
