### ISSUE TITLE
[cling] The interpreter requires a `;` after `using namespace ROOT`

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#8064]
- [X] Checked for duplicates

The interpreter's behavior w.r.t. putting `;` at the end of a line is inconsistent:

```bash
~ root -b
   ------------------------------------------------------------------
  | Welcome to ROOT 6.25/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Apr 30 2021, 13:01:03                 |
  | From heads/master@v6-25-01-813-g3ba13b74a1                       |
  | With c++ (GCC) 10.2.0                                            |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
root [0] struct A {}
root [1] using namespace ROOT
ROOT_prompt_1:1:21: error: expected ';' after namespace name
using namespace ROOT
                    ^
                    ;
root [2] int a, b
root (cont'ed, cancel with .@) [3]
```

I think if `;` is not required after `struct A {}`, it should not be required anywhere.
The issue with `int a, b` is tracked separately, as https://sft.its.cern.ch/jira/browse/ROOT-9202 .

**Comment by jalopezg-r00t** [comment]
Basically, this boils down to limitations in the current implementation of `cling::utils::getWrapPoint()`.  I will be working on this on the next few days.

**Comment by jalopezg-r00t** [comment]
https://sft.its.cern.ch/jira/browse/ROOT-9202 has been closed.

However, work on this issue has been delayed.  I will come back to it in a few weeks.

**Comment by guitargeek** [comment]
No user complained about this. What's the harm in enforcing a bit standard C++ here, even if it's not consistent?

In any case, this issue got generalized by #9171 so we can close it.

**Comment by guitargeek** [comment]
Marked as "not applicable" because duplicate
