### ISSUE TITLE
Clearer CMake output when Python2 is not found but Python3 is

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#8084]
### Explain what you would like to see improved

Currently, if our build system finds a suitable Python3 interpreter but does not find a Python2 interpreter, the CMake output looks like this:

```
-- Looking for Python
-- Could NOT find Python2 (missing: Python2_EXECUTABLE Python2_INCLUDE_DIRS Python2_LIBRARIES Python2_NumPy_INCLUDE_DIRS Interpreter Development NumPy Development.Module Development.Embed)
    Reason given by package:
        Interpreter: Wrong major version for the interpreter "/usr/bin/python"
```

The CMake output should mention that Python3 was found and things are just fine. The current message looks like ROOT searched for Python2, could not find it and that was it.

**Comment by SpectreVert** [comment]
Precision: this issue arises when updating the build files. 

An initial execution of the build system displays something like:
```
-- Looking for Python
-- Found Python3: /usr/bin/python3.8 (found version "3.8.9") found components: Interpreter Development NumPy Development.Module Development.Embed
-- Could NOT find Python2 (missing: Python2_EXECUTABLE Python2_INCLUDE_DIRS Python2_LIBRARIES Python2_NumPy_INCLUDE_DIRS Interpreter Development NumPy Development.Module Development.Embed)
 ```

If we rerun `cmake` afterwards we get the issue:
```
-- Looking for Python
-- Could NOT find Python2 (missing: Python2_EXECUTABLE Python2_INCLUDE_DIRS Python2_LIBRARIES Python2_NumPy_INCLUDE_DIRS Interpreter Development NumPy Development.Module Development.Embed)
```

**Comment by SpectreVert** [comment]
During the initial build file generation, CMake populates the CMakeCache.txt file. This is why subsequent cmake invokations fetch the variables from this file and do not display the "Found ...." messages.

If you want to see these messages when running a new build you could remove the CMakeCache.txt so as to populate the variables again.
