### ISSUE TITLE
X11 Display Depth 30 no fonts displayed

### ISSUE THREAD

**Issue by juw** [root-project/root#8086]
Hello,

by default I use a display depth of 30 set e.g. via `/etc/X11/xorg.conf.d/90-monitor.conf`
```
Section "Monitor"
	Identifier	"Internal Display"
	[…]
EndSection

Section "Screen"
	Identifier	"Screen0"
	Device		"…"
	Monitor		"Internal Display"
	DefaultDepth	30
EndSection
```
Then, doing the following:
```
$ root
root [0] TH1 *t = new TH1I("test", "test", 2, -.5, 1.5)
(TH1 *) 0x…
root [1] t->Fill(1)
(int) 2
root [2] t->Draw()
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
```
In the window, that opens, I would expect to see axis labels, a stat box etc. This is not the case. If I save the histogram, the labels are visible. The labels are also visible, if I do not set the display depth to 30 (but instead X11 uses a default depth of 24). Could ROOT be fixed, to also handle different display depths then 24 gracefully?

Best regards.

**Comment by couet** [comment]
I am not sure this can be fixed. If it works with 24 why not using 24 ?

**Comment by couet** [comment]
I do not have such configuration easily available. If you see something wrong and find a fix in TGX11TTF let me know. I'll be happy to apply the fix.

**Comment by juw** [comment]
From: Julian Wollrath ***@***.***>

When using a depth of 30 (10 bits per colour) bitmap_pad would have been
set to 30 leading to an incorrect quantum of a scanline (it should be
32). Due to this, text would not be displayed. Fix this by always
setting the correct value for the scanline quantum/bitmap_pad.
---
 graf2d/x11ttf/src/TGX11TTF.cxx | 11 ++++++++++-
 1 file changed, 10 insertions(+), 1 deletion(-)

diff --git a/graf2d/x11ttf/src/TGX11TTF.cxx b/graf2d/x11ttf/src/TGX11TTF.cxx
index 8927f55343..c8fc1923d0 100644
--- a/graf2d/x11ttf/src/TGX11TTF.cxx
+++ b/graf2d/x11ttf/src/TGX11TTF.cxx
@@ -479,10 +479,19 @@ void TGX11TTF::RenderString(Int_t x, Int_t y, ETextMode mode)

    // create the XImage that will contain the text
    UInt_t depth = fDepth;
+   Int_t bitmap_pad;
    XImage *xim  = 0;
+
+   if (depth <= 8)
+      bitmap_pad = 8;
+   else if (depth <= 16)
+      bitmap_pad = 16;
+   else
+      bitmap_pad = 32;
+
    xim = XCreateImage((Display*)fDisplay, fVisual,
                       depth, ZPixmap, 0, 0, w, h,
-                      depth == 24 ? 32 : (depth==15?16:depth), 0);
+                      bitmap_pad, 0);
    if (!xim) return;

    // use malloc since Xlib will use free() in XDestroyImage
--
2.32.0.rc0

**Comment by juw** [comment]
It seems, that GitHub does not work well with `git send-email`. You can also find the patch at `/afs/cern.ch/user/w/wollrath/public/0001-x11ttf-Set-correct-bitmap-padding-in-XCreateImage.patch`.
