### ISSUE TITLE
TColor palettes identify CVD-friendly

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8098]
### Explain what you would like to see improved
The TColor palettes are nicely described here: https://root.cern.ch/doc/master/classTColor.html
However, it is not clear which of these palettes are prone to artefacts, which are not CVD friendly, etc. Only the Rainbow one is mentioned and linked to https://root.cern.ch/rainbow-color-map

### Optional: share how it could be improved
- I think it would be helpful if they would be split into two separate sections, namely those that are CVD-friendly and those that are not. This would help the users in quickly knowing which to avoid.
- Maybe adding this link in the docu would be interesting: https://www.nature.com/articles/s41467-020-19160-7
- I would also suggest to implement the 'batlow' palette described in the link above into the predefined palettes. And potentially others described in Box2 of that article.
- These graphs here are also quite informative https://matplotlib.org/stable/tutorials/colors/colormaps.html

**Comment by couet** [comment]
The only ones, I think, are CVD friendly in the collection we have are [cividis and virids](https://www.cta-observatory.org/wp-content/uploads/2020/10/CTA_ColourBlindness_BestPractices-1.pdf ) . I am not sure about the others . Do you know ? The rainbow is surely the worst and we have that article explaining why. I will look at Batlow and box2

**Comment by couet** [comment]
Batlow looks very similar to [Cubehelix](https://root.cern/doc/master/classTColor.html#C06) if you remove the white top part of CubeHelix... isn't it ?

**Comment by ferdymercury** [comment]
Yes, it looks quite similar, (but comes from another source I think):
https://doi.org/10.5281/zenodo.4491293
https://www.fabiocrameri.ch/colourmaps/

**Comment by ferdymercury** [comment]
I wrote a script to read any color map, e.g. batlow.txt from https://doi.org/10.5281/zenodo.4491293

```
void color_palette(const TString palette = "batlow.txt")
{
    TTree tp;
    tp.ReadFile(palette,"r/D:g/D:b/D");
    //~ tp.Scan();

    const Int_t Number = tp.GetEntries();
    Double_t Red[Number];
    Double_t Green[Number];
    Double_t Blue[Number];
    Double_t Stops[Number];
    const Int_t nb=99;//max allowed by ROOT
    Double_t r, g, b;
    tp.SetBranchAddress("r", &r);
    tp.SetBranchAddress("g", &g);
    tp.SetBranchAddress("b", &b);
    for(Long64_t i = 0; i<Number; ++i)
    {
        tp.GetEntry(i);
        //std::cout << r << " " << g << " " << b << std::endl;
        Red[i] = r;
        Green[i] = g;
        Blue[i] = b;
        Stops[i] = i/(Number-1.);
    }

    TColor::CreateGradientColorTable(Number,Stops,Red,Green,Blue,nb);
```

For example, this is how batlow looks like:
![image](https://user-images.githubusercontent.com/10653970/117157527-f32aec00-adbe-11eb-825a-16e1e61be3de.png)

**Comment by couet** [comment]
I see. 256 is a bit too much data to pass to TColor::CreateGradientColorTable we usually use 9 in TColor::SetPalette. Ok we can extract the important ones and Create Gradient will do the job .. I mean if we follow the model we have now ...
Now do you have an idea how to separate in two those we have now ?
From ScientificColourMaps7 which ones would you like to have ? all ?

**Comment by ferdymercury** [comment]
To separate those we have now, a simple way is to use this add-on: https://addons.mozilla.org/en-US/firefox/addon/grayscale-browsing/

It will show https://root.cern.ch/doc/master/classTColor.html in grayscale mode.

![image](https://user-images.githubusercontent.com/10653970/117177407-47d76280-add1-11eb-9081-9bac9d4b4bd5.png)

You can immediately see that the color scale in rainbow is not continuous, which is then misleading for colour-blinded in a 2D plot (not so much in a 3D surf like this one). kCMYK is also not great because it's dark, then lighter, then half-dark again. Others like kAquamarine have almost no contrast, it would be almost impossible to see sth there. So that would be a quick way to separate them.

The idea is that the grayscale should be as proportional as possible, and monotonously increasing or decreasing. I guess one could do something similar for just removing red, green or blue from the image using GIMP, but for the moment with just grayscale it would be already a step.

**Comment by ferdymercury** [comment]
Concerning the ScientificColourMaps, more than having 'all of them', it would be useful to have them in a 'classified manner', clearly identified in the TColor documentation. Or maybe have one of each type.

- Centric value type (only use when symmetric bin contents) + "Inverted variant"
- Sequential type (usual case)  + "Inverted variant"
- Discrete variants
Here the full description: https://www.nature.com/articles/s41467-020-19160-7/figures/6

Another option I was thinking was that one could follow the approach of "Themes" used in many programs to define their color set. If a user downloads some themes from ScientificColourMaps and puts them in $HOME/.config/root/color-palettes/

then gStyle->SetPalette("batlow") would automatically load that one, if existing, using something like the script I posted above. This would make it pretty flexible.

**Comment by couet** [comment]
Thanks for you documented input. I will look closely at you suggestions and come with something.

**Comment by couet** [comment]
Also there is this example which allows to make a palette according to the histogram content. 
https://root.cern/doc/master/perceptualcolormap_8C.html
Here we defined a palette change at 0. This reproduce the example with "sea level" shown in the rainbow article. Now it is a macro may at some point it show be built in TColor.

**Comment by couet** [comment]
@ferdymercury do you think this PR can be merged ? or should we add more ? 
https://github.com/root-project/root/pull/9280

**Comment by ferdymercury** [comment]
Cool, thanks for the PR !

Maybe this link could be added, too? https://doi.org/10.1038/s41467-020-19160-7

**Comment by ferdymercury** [comment]
And maybe also adding this script in the "tutorials/graphics" section ?
[color_palette.cpp.zip](https://github.com/root-project/root/files/7539213/color_palette.cpp.zip)

**Comment by couet** [comment]
This example would need to be modified before being put in tutorials:

1. It should be formatted the proper way. See for instance [this one](https://github.com/root-project/root/blob/master/tutorials/graphics/arrows.C). The header should be formatted that way with a proper author name at the end.
2. The description of the macro should be more than just a brief. May be some explanation about the site it refers to would help. In particular the download link should be to ScientificColourMaps7.zip I guess.
3. You are using a TTree do read the .txt file. Why not, but that might be a bit "too much" just to read an ascii file of 3 columns. A standard C/C++ ASCII file reading is enough.
4. The files have already 255 colors. So you do not need CreateGradientColorTable to interpolate the colors simply build the palette with the colors you read.
5. Yes a static function in TColor would be also a possibiblity but the same comments apply.

**Comment by couet** [comment]
Is it fine for you to do it ?

**Comment by ferdymercury** [comment]
Sure, I can do it :)
