### ISSUE TITLE
BMP TASImage artefacts and crashes

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8125]
### Describe the bug
This script produces the following result:

```
#include "TCanvas.h"
#include "TASImage.h"

void test_asimage()
{
    new TCanvas("bmp","bmp");
    auto bmp = new TASImage("./screenshot.bmp");
    bmp->Draw();

    new TCanvas("png","png");
    auto png = new TASImage("./screenshot.png");
    png->Draw();
}
```

![image](https://user-images.githubusercontent.com/10653970/117480572-12ae4a00-af62-11eb-936b-0f8138e05af4.png)

### Expected behavior
Both PNG and BMP pictures should be the same. the left picture looks like it has some byte misalignment.

### To Reproduce
1. Download the screenshot files [screenshots.zip](https://github.com/root-project/root/files/6443072/screenshots.zip)
2. Run the code snippet above

### Setup
ROOT 6.22/02 on Ubuntu18

**Comment by ferdymercury** [comment]
The reason might be that it is not handling the negative height correctly. See https://docs.microsoft.com/en-us/previous-versions//dd183376(v=vs.85)?redirectedfrom=MSDN
```
biHeight
The height of the bitmap, in pixels. If biHeight is positive, the bitmap is a bottom-up DIB and its origin is the lower-left corner. If biHeight is negative, the bitmap is a top-down DIB and its origin is the upper-left corner.
```

**Comment by couet** [comment]
I see the issue too on my Mac. Not sure how to fix it. I will investigate what you suggest here.

**Comment by ferdymercury** [comment]
Thanks. One side comment. There is a problem in the way libAfterImage is built. Even if I build ROOT in 'debug mode', libAfterImage is built with -O3 optimization flag. I think the build mode should be propagated also to libAfterImage.

Otherwise it's much more difficult to debug this issue.

**Comment by ferdymercury** [comment]
See:
```
2004-09-21  sasha

	* added mandatory -O3 in libAfterImage and libAfterBase improving
	  performance significantly;
```

I think it would be better if this only happened in 'Release Mode'. In debug mode, other flags like -g should be passed instead.

**Comment by ferdymercury** [comment]
I confirm that with a positive height BMP, the result is rendered correctly by ROOT:

https://www.fileformat.info/format/bmp/sample/7ce642a25ca34f2087f2e8ec0f97713c/download

![image](https://user-images.githubusercontent.com/10653970/118337195-4567bd80-b4e1-11eb-8c06-dfb1243a6050.png)

**Comment by couet** [comment]
> I confirm that with a positive height BMP, the result is rendered correctly by ROOT

Do you have a fix ?

**Comment by ferdymercury** [comment]
Nope, unfortunately the BPMs are generated by a Pulse Generator, and they are always with negative height :S

**Comment by ferdymercury** [comment]
If #define DEBUG_LOCAL here https://github.com/root-project/root/blob/87a998d48803bc207288d90038e60ff148827664/graf2d/asimage/src/libAfterImage/bmp.c#L21, I get the culprit:

biHeight is being set to something huge because of the operation uint(-272)

```
bmp.info.biSize = 40(0x28)
bmp.info.biWidth = 480
bmp.info.biHeight = 4294967024
bmp.info.biPlanes = 1
bmp.info.biBitCount = 16
bmp.info.biCompression = 0
bmp.info.biSizeImage = 261120
bmp.header.bfType = 0x4D42
bmp.header.bfSize = 261174
bmp.header.bfOffBits = 54(0x36)

```

**Comment by ferdymercury** [comment]
I think it might not be related at all to the height, but to the file format.

Can you check if the attached BMP file crashes for you also? It was generated with GIMP.

[screenshot.bmp.zip](https://github.com/root-project/root/files/6495918/screenshot.bmp.zip)

**Comment by couet** [comment]
Yes it crashes for me also.

**Comment by couet** [comment]
I did an other test. I opened the png image with the Paintbrush software on Mac, I modified it a bit and saved it as a bmp file. The bmp modified image (on the left on the attached picture) opens without problems with the macro you sent. So it might be the bmp files you sent are not properly formatted,
<img width="1406" alt="Screenshot 2021-05-26 at 10 49 52" src="https://user-images.githubusercontent.com/4697738/119631380-22f27000-be10-11eb-9fec-d49cb2b02d7a.png">

**Comment by ferdymercury** [comment]
Hmm, but if they are not properly formatted, how is it then possible that both GIMP and Paintbrush (and any other 10 viewers I tried) can open them?

**Comment by couet** [comment]
I do not know but it seems TASImage is able to open some bmp and not some other. Let me try yo save the png as bmp without modifying it and compare it with the one you sent.

**Comment by ferdymercury** [comment]
I think it might be because of the different BMP versions:
https://en.wikipedia.org/wiki/BMP_file_format#Bitmap_file_header

**Comment by couet** [comment]
BTW how did you generate the file screenshot.bmp ?

**Comment by ferdymercury** [comment]
It's automatically generated by a https://www.keysight.com/us/en/assets/7018-04123/data-sheets-archived/5991-3272.pdf
It transfers it to the computer via USB. (So nothing I can really change.)

**Comment by ferdymercury** [comment]
Here a comparison from the one generated by the PulseGenerator, and the one after open and re-export in GIMP.

The Gimp one has some "BGR" stuff that is not seen in the other.

![image](https://user-images.githubusercontent.com/10653970/119634030-50bfc080-bde0-11eb-8843-af0f452559e6.png)

They seem to have different DIB headers.
https://en.wikipedia.org/wiki/BMP_file_format#DIB_header_(bitmap_information_header)

**Comment by couet** [comment]
Here is the (working image) generated by Paintbrush on Mac.
[screenshot3.bmp.gz](https://github.com/root-project/root/files/6545400/screenshot3.bmp.gz)

**Comment by ferdymercury** [comment]
![image](https://user-images.githubusercontent.com/10653970/119635586-d5f7a500-bde1-11eb-9b88-c5aaf6047e3d.png)
It seems that it does not have the Blue Green Red stuff.

**Comment by couet** [comment]
So, I am not sure how to handle that .....

**Comment by ferdymercury** [comment]
Do you have by chance contact with any of the authors of Afterstep? https://github.com/afterstep/afterstep/
Maybe they have an insight on how to solve this.

**Comment by couet** [comment]
No ... but we can ask

**Comment by ferdymercury** [comment]
Otherwise, I would be happy to debug it and contribute to it, but first, I would need that the AFTERIMAGE subdirectory were built with the same flags than CMake, otherwise I cannot use the interactive debugger.

Is there a way that you can change the way AFTERIMAGE is compiled, so that it uses the CMake environment (in the same way as core, gui, etc. CMake submodules) instead of the old ./configure stuff behind the scenes with -O3 and no debug symbols, no matter what the ROOT build-type is?

**Comment by couet** [comment]
I just tried to use[ bpm.c from the afterstep repo](https://github.com/afterstep/afterstep/blob/master/libAfterImage/bmp.c) (despite the fact it has not changed for 9 years). It does not help. I will submit an issue on the afterstep GitHub with the .bmp image which does not work.

**Comment by couet** [comment]
well I see you did already ....

**Comment by couet** [comment]
It does not seem the issue https://github.com/afterstep/afterstep/issues/4 has been even looked at. I am not sure this repository is still active. I guess we won't get a fix fro there.

**Comment by ferdymercury** [comment]
Not sure if this should be closed, this is rather a bug with reading BMPs?

**Comment by couet** [comment]
TAsimage is frozen. This problem will not be fixed.

**Comment by ferdymercury** [comment]
Reopening since I plan to debug it using PR https://github.com/root-project/root/pull/21649

It seems that the negative pixel height is not the problem.

The issue seems to come from

`dib_data_to_scanline`

which may not copy correctly from the uint16 buffer to the uint32 buffer.
