### ISSUE TITLE
TGCommandLinePlugin autocomplete when single entry

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8127]
### Explain what you would like to see improved
In TGCommandLinePlugin, pressing tab shows a list of options. It would be nice that, if there is only one option, it gets automatically 'pasted' into the text entry.

### Optional: share how it could be improved
Parse and copy the content of the suggested code to the current text entry. (Removing the #Double_t stuff).

### To Reproduce
1. On the plugin, type TMath::QuietN and press tab.
2. [#Double_t#]QuietNaN() is suggested as single option.
3. Ideally, the text entry would be now: TMath::QuietNaN() as it happens in a normal ROOT Terminal for the analogous case.

### Setup
ROOT 6.25/01

**Comment by bellenot** [comment]
@ferdymercury FYI, I just created the PR #8312 implementing what you suggest

**Comment by ferdymercury** [comment]
you are awesome, thanks :)

**Comment by ferdymercury** [comment]
@bellenot I was trying out, and the autocompletion is failing in some cases:

- `gSystem->GetListOfT`   ---> returns `gSystem->GetListOfTOfTimers()[# const#]`
- `gSystem->GetListOfF`  ---> returns `gSystem->GetListOfF#]GetListOfFileHandlers()[# const#]`
