### ISSUE TITLE
Error opening remote root file LCG_100

### ISSUE THREAD

**Issue by omazapa** [root-project/root#8155]
- [ ] Checked for duplicates

### Describe the bug
Running our test on SWAN, I found that TFIile can not read anymore a remote ROOT file from github.
The code
`
TFile::Open("https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root");
`

produces
`
Error in <DavixOpen>: can not open file "https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root" with davix: Result HTTP 404 : File not found  after 3 attempts (18) 
`
The file exists and the code works with LCG_99.

I did an additional test with a ROOT different ROOT file inside the domain cern.ch and it works for LCG_100
`
TFile::Open("https://root.cern.ch/files/summer_student_tutorial_tracks.root");
`

### Expected behavior
TFIle should be able to read the file from github.

### To Reproduce
on lxplus
`
source /cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/setup.sh

[ozapatam@lxplus7103 ~]$ root -l -b

root [0] auto f=TFile::Open("https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root");

Error in <DavixOpen>: can not open file "https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root" with davix: Result HTTP 404 : File not found  after 3 attempts (18)
`

on LCG_99 it works
`
source /cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos7-gcc8-opt/setup.sh 

[ozapatam@lxplus7120 ~]$ root -l

root [0] auto f=TFile::Open("https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root");

root [1] f->ls();
TDavixFile**            https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root
 TDavixFile*            https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root
  KEY: TTree    TreeS;1 TreeS
  KEY: TTree    TreeB;1 TreeB
  KEY: TTree    Sig;1   TreeS
  KEY: TTree    Bkg;1   TreeB
`

### Setup
ROOT Version: 6.24/00
Built for linuxx8664gcc on Apr 14 2021, 14:33:50
From tags/v6-24-00@v6-24-00

LCG_100

**Comment by oshadura** [comment]
@omazapa in case I tried from lxplus with different file: 

```
-bash-4.2$ root -l https://root.cern/files/Event.root
root [0]
Attaching file https://root.cern/files/Event.root as _file0...
Warning in <TClass::Init>: no dictionary for class Event is available
Warning in <TClass::Init>: no dictionary for class EventHeader is available
Warning in <TClass::Init>: no dictionary for class Track is available
(TFile *) 0x3d4d680
root [1]
```

**Comment by Axel-Naumann** [comment]
I can also reproduce this with my build of v6-24-00-patches, outside the CERN network.

**Comment by Axel-Naumann** [comment]
```
$ curl -v http://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root
*   Trying 185.199.109.133:80...
* TCP_NODELAY set
* Connected to raw.githubusercontent.com (185.199.109.133) port 80 (#0)
> GET /iml-wg/tmvatutorials/master/inputdata.root HTTP/1.1
> Host: raw.githubusercontent.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: Varnish
< Retry-After: 0
< Location: https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root
< Content-Length: 0
< Accept-Ranges: bytes
< Date: Wed, 12 May 2021 07:40:00 GMT
< Via: 1.1 varnish
< Connection: close
< X-Served-By: cache-hhn4077-HHN
< X-Cache: HIT
< X-Cache-Hits: 0
< X-Timer: S1620805200.382251,VS0,VE0
< Access-Control-Allow-Origin: *
< Expires: Wed, 12 May 2021 07:45:00 GMT
< Vary: Authorization,Accept-Encoding
< 
* Closing connection 0
```
So it's probably the redirect.

**Comment by Axel-Naumann** [comment]
Progress (@oshadura ). When doing the request "does that file exist (and do I need to follow a redirect) in
```
#0  Davix::NEONRequest::negotiateRequest (this=0x555557146380, err=0x7fffffff90d0)
    at $ROOTSYS/builtins/davix/DAVIX-prefix/src/DAVIX/src/neon/neonrequest.cpp:425
```
with
```
(gdb) p *_req
$42 = {
  method = 0x55555822e440 "HEAD",
  uri = 0x55555822e460 "/iml-wg/tmvatutorials/master/inputdata.root",
  headers = 0x55555822e420,
```
v6.22 has:
```
$44 = {
  data = 0x555557bb6180 "User-Agent: ROOT/6.22/09 TDavixFile/0.2.0 davix/0.7.5 neon/0.0.29\r\nKeep-Alive: \r\nConnection: Keep-Alive\r\nTE: trailers\r\nHost: raw.githubusercontent.com\r\n",
```
while v6.24 has:
```
(gdb) p *_req->headers
$48 = {
  data = 0x555556bfa160 "User-Agent: ROOT/6.24/01 TDavixFile/0.2.0 davix/0.7.5 neon/0.0.29\r\nKeep-Alive: \r\nConnection: Keep-Alive\r\nTE: trailers\r\nHost: raw.githubusercontent.com\r\nAuthorization: Bearer \r\n",
```
I.e. adding `Authorization: Bearer` seems to break this. I can reproduce this with

```
curl -v -H 'Authorization: Bearer' https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root
```
giving 404, while not passing `-H` makes the redirect work. That's it from my side, more news from @oshadura after vCHEP!

**Comment by oshadura** [comment]
@Axel-Naumann thanks a lot for debugging! My suspicions were correct, I am building now debug ROOT build and will send PR as soon as possible...Interesting why we didn't catch it in any of the tests...

**Comment by Axel-Naumann** [comment]
Right, you need a server that is so upset about a "useless" `Authorization: Bearer` header that it responds with 404 :-)

**Comment by omazapa** [comment]
Thank you so much @Axel-Naumann and @oshadura for taking a look at this.
