### ISSUE TITLE
Branch latest-stable missing

### ISSUE THREAD

**Issue by kjp** [root-project/root#8188]
Hello, 

Instructions at https://root.cern/install/build_from_source/ suggest to run

```
git clone --branch latest-stable https://github.com/root-project/root.git root_src
```

However, the branch `latest-stable` doesn't seem to exist in this project. There is no branch with the keyword stable or latest in the project.

Cheers,
Karolos

**Comment by hahnjo** [comment]
@Axel-Naumann @jalopezg-r00t

**Comment by jalopezg-r00t** [comment]
That was foreseen for the next release, but to avoid further confusion we will create it now.

**Comment by jalopezg-r00t** [comment]
The command mentioned in the issue should now work.  Please, feel free to report any issues that you might have with the `latest-stable` branch.

Thanks!
