### ISSUE TITLE
Add a better test coverage (together with infrastructure) testing Bearer tokens for ROOT

### ISSUE THREAD

**Issue by oshadura** [root-project/root#8216]
Starting from ROOT 6.24.00 we support WLCG Bearer Tokens [1] through Davix, but we still are missing infrastructure for testing them.
[1] https://root.cern/releases/release-62400/

**Comment by dpiparo** [comment]
Should we get issues related to token auth in the future which are not caught by DAVIX or experiments, we can still add our own testing & diagnosis.
