### ISSUE TITLE
Test failures in tutorial-roofit when building without FFTW

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#8245]
On my system I get
```
The following tests FAILED:
        1061 - tutorial-roofit-rf208_convolution-py (Failed)
        1063 - tutorial-roofit-rf210_angularconv-py (Failed)
        1064 - tutorial-roofit-rf211_paramconv-py (Failed)
        1095 - tutorial-roofit-rf512_wsfactory_oper-py (Failed)
```

The reason seems to be that I'm building without FFTW, and while the macro versions of those tests are correctly vetoed:
https://github.com/root-project/root/blob/098dfcf94a3939597488fef9ee128b3d2e1e591f/tutorials/CMakeLists.txt#L191-L198
similar action is missing for the versions written in Python.

**Comment by hahnjo** [comment]
Note that there might be other vetoes missing, I didn't check...

**Comment by guitargeek** [comment]
Added the `Fixed in: not applicable` project since this issue never affected any release (only temporarily affected `master` in the 6.26 development cycle).
