### ISSUE TITLE
Root 6.20.06+ - New bug with compiled code using TClass / dictionaries

### ISSUE THREAD

**Issue by kkauder** [root-project/root#8250]
I'm creating a TTree with a class that inherits from a base class, without a problem. However, in the same program a couple lines later,
```
TClass branchClass(c->GetBranch("event")->GetClassName());
if (branchClass.InheritsFrom("dicttest::EventDis") {....}
```
fails with
```
Warning in <TClass::TClass>: no dictionary for class dicttest::EventPythia is available
Error in <TObjArray::At>: index 0 out of bounds (size: 1, this: 0x127faed70)
Error in <TObjArray::At>: index 0 out of bounds (size: 1, this: 0x127faed70)
```

It works fine interactively but not when compiled. I have a demonstrator that's pretty minimal here:
https://github.com/kkauder/rootbreaker

This behavior is new to root 6.24, tested on Apple M1 and Ubuntu. The same code worked fine in root 6.20.04; I haven't been able to test other versions.

**Comment by kkauder** [comment]
Just checked, it also breaks in 6.22.08.

**Comment by kkauder** [comment]
Update: After further testing, it works in 6.20.04 and breaks in in 6.20.06 and thereafter. I’ll look into the particular release notes for more information.

**Comment by kkauder** [comment]
@Axel-Naumann, shrunk it down a bit further too. 

In the release notes, I see three candidates.
https://sft.its.cern.ch/jira/browse/ROOT-10658 --> But looking further into it, the symptoms don't match to this affecting me

https://sft.its.cern.ch/jira/browse/ROOT-10663 --> This to me is the prime candidate, since it directly affects auto-loading which _seems_ to be at the core here. I took a look at the PR, https://github.com/root-project/root/pull/5713/files, but can't at a glance identify anything more.

On the surface, https://sft.its.cern.ch/jira/browse/ROOT-10798 could also apply, but the fix really seems to boil down to something completely different.

**Comment by Axel-Naumann** [comment]
Thanks, @kkauder - I'll hope to get to it early next week!

**Comment by Axel-Naumann** [comment]
Can you confirm that `TClass::GetClass` (instead of using the `TClass` constructor) works around the issue?

**Comment by kkauder** [comment]
Yes,
```
  // TClass branchClass(c->GetBranch("event")->GetClassName());
  // if (branchClass.InheritsFrom("dicttest::EventMC")) {
  TClass* branchClass = TClass::GetClass(c->GetBranch("event")->GetClassName());
  if (branchClass->InheritsFrom("dicttest::EventMC")) {
  ```
  works. 
  This workaround should be enough for my needs (although I can't confirm as of yet that other problems in the full code don't appear), but question: Is this expected? Then the ctor at least needs a warning or something...

**Comment by Axel-Naumann** [comment]
>  Is this expected?

No. Though `TClass::GetClass()` is the canonical interface, `TClass()` should work, too. I will have a look why it fails in your case.

**Comment by pcanal** [comment]
Not quite.  The TClass constructor is reserved for internal purpose and does give a fully functional TClass object.  I.e. don't use it :).

**Comment by kkauder** [comment]
Fair enough, Phillippe :) The description does say "Normally you would use TClass::GetClass("class") to get access to a TClass object for a certain class." In my defense, I didn't write it; it's inherited code. That said, the description doesn't say that it may fail, so I think if the behavior above can't be fixed, the warning language should be made stronger.

**Comment by Axel-Naumann** [comment]
Let's see whether we can improve the doc :-) https://github.com/root-project/root/pull/8384
