### ISSUE TITLE
-Wundef RStringView MSVC_LANG

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8267]
### Describe the bug
New warnings appearing when using ROOT in my projects:

`/opt/root/include/ROOT/RStringView.hxx: warning: "_MSVC_LANG" is not defined, evaluates to 0 [-Wundef]`

after the recent commits on https://github.com/root-project/root/commits/master/core/foundation/inc/ROOT/RStringView.hxx

### Expected behavior
No warnings

### Setup
1. ROOT git master
2. Ubuntu 20
3. Self-built

**Comment by andriish** [comment]
One can add 
```
#if !defined(_MSC_VER)
#define _MSC_VER 0
#endif
```
but in the current version there is no undefined behavior, so it is safe.
I would even blame the compiller/preprocessor as the offending code 
```
defined(_MSVC_LANG) && _MSVC_LANG >= 201703L
``` 
is very standard.

Best regards,

Andrii

**Comment by ferdymercury** [comment]
If I add those lines in my files (on Ubuntu), I get this error:
`#  error "ROOT requires Visual Studio 2017 or higher."`

> One can add
> 
> ```
> #if !defined(_MSC_VER)
> #define _MSC_VER 0
> #endif
> ```
> 
> but in the current version there is no undefined behavior, so it is safe.
> I would even blame the compiller/preprocessor as the offending code
> 
> ```
> defined(_MSVC_LANG) && _MSVC_LANG >= 201703L
> ```
> 
> is very standard.
> 
> Best regards,
> 
> Andrii

**Comment by andriish** [comment]
Uh, sorry.
```
#if !defined(_MSVC_LANG)
#define _MSVC_LANG 0
#endif
```

**Comment by ferdymercury** [comment]
That works, thanks :)

**Comment by Axel-Naumann** [comment]
Thanks for the report! I prefer https://github.com/root-project/root/pull/8311 rather than messing with compiler macros - who knows what other code is looking at `#ifdef _MSVC_LANG` which would be misled by us `#define`ing it.

**Comment by Axel-Naumann** [comment]
Can someone who actually sees this warning confirm that PR #8311 is fixing this?

**Comment by ferdymercury** [comment]
With your branch, I no longer see the warning. Thanks! :)
