### ISSUE TITLE
TGCommandPlugin TTimer

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8269]
### Explain what you would like to see improved
The TGCommandPlugin has an internal TTimer that I think is redundant. I don't understand why the function CheckRemote needs to be checked every one second, which also calls frame->Layout(). Shouldn't it be better to just check in the beginning with a TTimer::SingleShot? Or if gROOT->GetApplication() changes during lifetime, with a signal/slot ?

```
fTimer = new TTimer(this, 1000);
fTimer->Reset();
fTimer->TurnOn();
...
////////////////////////////////////////////////////////////////////////////////
/// Handle timer event.

Bool_t TGCommandPlugin::HandleTimer(TTimer *t)
{
   if ((fTimer == 0) || (t != fTimer)) return kTRUE;
   CheckRemote("");
   return kTRUE;
}
void TGCommandPlugin::CheckRemote(const char * /*str*/)
{
   Pixel_t pxl;
   TApplication *app = gROOT->GetApplication();
   if (!app->InheritsFrom("TRint"))
      return;
   TString sPrompt = ((TRint*)app)->GetPrompt();
   Int_t end = sPrompt.Index(":root [", 0);
   if (end > 0 && end != kNPOS) {
      // remote session
      sPrompt.Remove(end);
      gClient->GetColorByName("#ff0000", pxl);
      fLabel->SetTextColor(pxl);
      fLabel->SetText(Form("Command (%s):", sPrompt.Data()));
   }
   else {
      // local session
      gClient->GetColorByName("#000000", pxl);
      fLabel->SetTextColor(pxl);
      fLabel->SetText("Command (local):");
   }
   fHf->Layout();
}
```
Alternatively, it would be nice to provide a function to stop the timer by the user, when performance is needed and you are sure that TApplication is always the same.

### Setup
1. ROOT from git master
2. Ubuntu 20
3. Self-built

### Additional context
https://root-forum.cern.ch/t/trentrantrwlock-thread-lock-program-freezes/45116

**Comment by bellenot** [comment]
If I remember correctly, one can connect/disconnect/re-connect to a remote ROOT session, so I think this is the purpose of the timer. But I'll have to cross-check.

**Comment by ferdymercury** [comment]
Oh, I see, thanks for the explanation. Maybe like this: https://root.cern.ch/root/roottalk/roottalk07/0985.html or https://root-forum.cern.ch/t/root-on-lxplus/5167/5

In that case, replacing with a signal-slot on TApplicationRemote::Open, or an additional StopTimer() function, might be useful to reduce overhead for cases where one is sure he is going to stay local.

**Comment by bellenot** [comment]
> Oh, I see, thanks for the explanation. Maybe like this: https://root.cern.ch/root/roottalk/roottalk07/0985.html or https://root-forum.cern.ch/t/root-on-lxplus/5167/5

Exactly!

 
> In that case, replacing with a signal-slot on TApplicationRemote::Open, or an additional StopTimer() function, might be useful to reduce overhead for cases where one is sure he is going to stay local.

I'll check how this can be improved
