### ISSUE TITLE
TChain::AddClone failing for sub-branches of branch of type with ClassDef

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#8295]
- [X] Checked for duplicates

### To Reproduce

The following code, which emulates what happens inside a RDataFrame Snapshot, silently writes wrong data:

```cpp
// xy_t.h
#pragma once
#include <Rtypes.h>

class xy_t {
public:
  double x;
  double y;

  xy_t() : x(-1), y(-1) {}
  ~xy_t(){};
  ClassDef(xy_t, 1); // remove this to remove the problem
};
```
```cpp
// main.cpp
#include <TFile.h>
#include <TChain.h>
#include <TSystem.h>
#include <TTree.h>
#include <TTreeReader.h>
#include <iostream>
#include "xy_t.h"

void write_inputs() {
  xy_t xy;
  int i = 0;
  {
    TFile f("in1.root", "recreate");
    TTree t("t", "t");
    t.Branch("xy", &xy);
    t.Branch("i", &i);
    i = 1;
    xy.x = xy.y = 1;
    t.Fill();
    t.Write();
    f.Close();
  }
  {
    TFile f("in2.root", "recreate");
    TTree t("t", "t");
    t.Branch("xy", &xy);
    t.Branch("i", &i);
    i = 2;
    xy.x = xy.y = 2;
    t.Fill();
    t.Write();
    f.Close();
  }
}

int main() {
  write_inputs();

  TChain c("t");
  c.Add("in1.root");
  c.Add("in2.root");
  TTreeReader r(&c);
  TTreeReaderValue<int> ri(r, "i");
  TTreeReaderValue<double> rx(r, "x");
  TTreeReaderValue<xy_t> rxy(r, "xy");

  {
    r.Next();
    TFile f("out.root", "recreate");
    TTree t("t", "t");
    c.AddClone(&t);
    t.Branch("i", &(*ri));
    t.Branch("x", &(*rx));
    t.Branch("xy", &(*rxy));
    std::cout << "x: " << *rx << '\n';
    t.Fill();
    r.Next();
    *ri;
    *rx;
    *rxy;
    std::cout << "x: " << *rx << '\n';
    t.Fill();
    t.Write();
  }

  TFile f("out.root");
  f.Get<TTree>("t")->Scan();
}
```

Can be run with:

```
$ root -l -b -q xy_t.h+; g++ -o main main.cpp xy_t_h.so $(root-config --libs --cflags) && env LD_LIBRARY_PATH="$LD_LIBRARY_PATH:." ./main
```

Reading and writing of the `xy` branch can be removed, in which case a warning is printed but wrong data is still written to file.

Removing the `ClassDef` from `xy_t` removes the problem and the correct data is written out.

### Additional context

The original report is https://root-forum.cern.ch/t/rdataframe-multi-file-with-class-branch-bug-report/45156, in the context of RDataFrame::Snapshot.

**Comment by cxwx** [comment]
as for simple
using struct instead of class should focus on the issue
```
   struct xy_t{
       double x;
       double y;
       ClassDef(xy_t,1);
   };
```

**Comment by eguiraud** [comment]
Getting closer to the root cause.

- `TTree::CopyAddresses` is called when switching from the first input tree to the second, to update the branch addresses of the output tree
- `TBranch::GetAddress` returns the address of the value if `ClassDef` is omitted, otherwise it returns a slightly off address, which means that after `CopyAddresses` is called the output tree is reading values from the wrong address

The line at which `TTree::CopyAddresses` sets the wrong address for the output branch:

https://github.com/root-project/root/blob/master/tree/tree/src/TTree.cxx#L3361

**Comment by eguiraud** [comment]
Discussed and checked the problem with @pcanal . The root cause is that `TTree::CopyAddresses` has an implicit assumption that the input and output branches are of the same kind, while in this case we have a `TBranchElement` in input and a simple `TBranch` in output. In particular, `TBranchElement::SetAddress` would apply a correction to the wrong offset returned by `TBranchElement::GetAddress`, but `TBranch::SetAddress` does not.

This bug is absolutely terrible: if the input dataset consists of multiple trees, starting from the second tree data members of types that were saved as TBranchElements are written out wrongly by Snapshot.

The plan is the following:

1. add a check in `TTree::CopyAddresses` that input and output branches are of the same kind, print an error otherwise
2. refactor `Snapshot` so that instead of relying on `TChain::AddClone` and `TTree::CopyAddresses` to update the addresses of the output branches we instead reset the branches manually based on the addresses provided by TTreeReaderValue access -- we'll use the `TNotify` mechanism to reset the branches every time TChain switches input tree

**Comment by eguiraud** [comment]
The fix is in master. @cxwx it would be great if you could test it on your usecase, e.g. by using tomorrow's nightly builds.

A backport for 6.24 is up, I'll merge if the CI is green.

**Comment by eguiraud** [comment]
@cxwx your original reproducer should now work, let us know if you encounter any further issues.

**Comment by cxwx** [comment]
thanks
