### ISSUE TITLE
TTree::GetEntry should not take the entry number as default parameter

### ISSUE THREAD

**Issue by acampove** [root-project/root#8300]
### Explain what you would like to see improved

In:

https://root.cern.ch/doc/master/classTTree.html#a9fc48df5560fce1a2d63ecd1ac5b40cb

the entry number is zero by default, that should not be a default parameter. If I wanted to get the zeroth entry, I would just get the zeroth entry. On the other hand, If the user forgets to put the entry there, the compiler will be fine with it and we won't find the mistake until we check the outputs that will all correspond to the zeroth entry.

**Comment by pcanal** [comment]
Indeed, I see no reason to rely on this behavior (i.e. `GetEntry()` and `GetEvent()` returning the first entry)
