### ISSUE TITLE
TH2PolyBin should be able to store errors

### ISSUE THREAD

**Issue by acampove** [root-project/root#8340]
### Is your feature request related to a problem? Please describe.

Here:

https://root.cern.ch/doc/master/TH2Poly_8h_source.html#l00033

The code suggests that we cannot store in these bins neither the bin error nor the sum of the squares of the weights. Thus in order to keep track of the errors we need two TH2Poly instances, one for the values and the other for the errors. What is the logic behind this design? I do not think this makes sense. Can this be changed? 
### Describe the solution you'd like

Add setters and getters for errors, add members for the error and a member for the sum of squares of weights.

**Comment by couet** [comment]
This need to be checked closely. I added @lmoneta in the loop.

**Comment by acampove** [comment]
Hi,

After checking this more closely, I was wrong. As the example below shows, TH2Poly does store the errors as the sum of the squares of the weights. However the errors seem to be stored in the histogram itself, in `fSumw2.fArray`, while the TH2PolyBIn only stores the content, see:

https://root.cern.ch/doc/master/TH2Poly_8cxx_source.html#l00598

```python
import ROOT
import math

h=ROOT.TH2Poly('h', '', 0, 10, 0, 10) 
h.AddBin(0, 0,  4, 10) 
h.AddBin(4, 0,  8, 10) 
h.AddBin(8, 0, 10, 10) 

h.Fill(2, 1, 0.5)
h.Fill(2, 1, 0.3)
h.Fill(2, 1, 0.2)

h.Fill(6, 1, 0.5)
h.Fill(6, 1, 0.4)
h.Fill(6, 1, 0.1)

h.Fill(9, 1, 0.8)
h.Fill(9, 1, 0.6)
h.Fill(9, 1, 0.2)

c=ROOT.TCanvas('c', '', 600, 600)
h.Draw('text error')
c.SaveAs('plot.png')


err_1=math.sqrt(0.5**2 + 0.3**2 + 0.2**2)
err_2=math.sqrt(0.5**2 + 0.4**2 + 0.1**2)
err_3=math.sqrt(0.8**2 + 0.6**2 + 0.2**2)

print(err_1)
print(err_2)
print(err_3)
```

**Comment by acampove** [comment]
Hi,

I have thought of this and despite this is not technically a mistake from your side (i.e. we still can use errors, etc) this is bad design. I would put all the bin related quantities in the bin object, including the errors.

Cheers.

**Comment by lmoneta** [comment]
Hi, 

I agree is not good for the design, but the original problem is having TH2Poly deriving from a TH1 instead of  being a separate class.  Now that is released and used it is not worth changing it. 
Can I close this issue ? 

 Cheers

Lorenzo

**Comment by acampove** [comment]
Hi,

Yes, you can close it. I have seen a strange behaviour when trying to loop over the bin list and trying to access the errors and bin contents through the TH2Poly. However I am too busy to provide a script to reproduce it right now. 

Cheers.
