### ISSUE TITLE
RDataFrame::GraphAsymmErrors

### ISSUE THREAD

**Issue by cxwx** [root-project/root#8363]
### Describe the solution you'd like
add a member function `RDataFrame::GraphAsymmErrors`

**Comment by eguiraud** [comment]
Assigning to @ikabadzhov . It should be enough to copy what's done for the `Graph` action to implement this.

**Comment by ikabadzhov** [comment]
Hi @cxwx! The requested feature is now added to master. It should be added in Release Version 6.28 (scheduled for release in May).
