### ISSUE TITLE
Installation without internet access

### ISSUE THREAD

**Issue by erothe** [root-project/root#8424]
```
ROOT Version: root-5-34-00-patches
Platform: 4.18.0-193.6.3.el8_2.x86_64 (RHEL 8.2 Ootpa)
Compiler: gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
```

I have been asked to install ROOT v5-34 in a machine that does not have an internet connection.

My configure line is:
```
./configure --prefix=/software/root/5.34
```
But it fails to find the LZ4 library as shown below in the output of the `configure` command:
```
Checking whether to build included lz4 ... yes
```
Even if the library can be found in the PATH by the command `which`. This is a problem, because it will then try to download the package and it will fail.

So I try the following configure line:
```
./configure --prefix=/software/root/5.34 --disable-builtin-lz4
```
But the option is ignored and the output of the configure shows that it will build the builtin_lz4 (and therefore download it from internet):
```
Enabled support for asimage, astiff, builtin_afterimage, builtin_glew, builtin_lz4, cintex, explicitlink, fftw3, gviz, genvector, krb5, memstat, opengl, reflex, shadowpw, shared, ssl, tmva, vdt, x11, xft, xml.
```
I was able to bypass the behaviour for the version 6.24 using `cmake` with the following line:
```
cmake -DCMAKE_INSTALL_PREFIX=<some-path> -Dasimage=on -Dcocoa=on -Dvdt=off -Dxrootd=off -Dclad=off <path-to-source>
```
Again, for version 6.24, I was not able to use the `--disable` option, but somehow, this combination of options resulted in the bypassing of the builtin-lz4.

This issue was opened following a [suggestion in the root forum](https://root-forum.cern.ch/t/installation-without-internet-access/45361/2?u=eduardo) where the same question was posted earlier.

Regards,
Eduardo

**Comment by eguiraud** [comment]
Hi @erothe , 5.34 is not supported anymore other than for critical (i.e. physics-breaking) bugs.

For 6.24, configure/make is not available but cmake should let you disable what you want. You might need to pass `-Dfail-on-missing=ON` to prevent ROOT from turning things back on when it sees they are needed.

Assigning to our build system expert @oshadura , but if this is about 5.34 I am not sure we can offer a solution unfortunately.

**Comment by erothe** [comment]
I will use the `-Dfail-on-missing=ON` with version 6.24 and check if the behaviour changes.

**Comment by erothe** [comment]
I haven't been able to rerun the installation process with `-Dfail-on-missing=ON` for version 6.24 and as the system is under maintenance.

However, I would be glad to know if or where is it possible to manually switch back off the `builtin_lz4` option after having runned `cmake` ?

**Comment by pamputt** [comment]
Concerning ROOT 6.24, see also https://github.com/root-project/root/issues/8292 that is possibly a duplicate

**Comment by Axel-Naumann** [comment]
The cleanest way to switch build options on an existing, configured build is:
```
cat recmake_*
rm CMakeCache.txt
cmake -D....
```

The `recmake_*` files remind you how you invoked CMake before.
