### ISSUE TITLE
`thisroot.fish` does not set properly `JUPYTER*` env vars with `gnuinstall=ON`

### ISSUE THREAD

**Issue by cavfiumella** [root-project/root#8435]
- [X] Checked for duplicates

### Describe the bug
I built ROOT from source using option `gnuinstall=ON` and cloning `latest-stable` branch.
After the installation the script `/usr/local/bin/thisroot.fish` sets `JUPYTER*` environment variables as follows:
```
JUPYTER_PATH=ROOTSYS/etc/notebook
JUPYTER_CONFIG_DIR=ROOTSYS/etc/notebook
```

Commit [0be8bbe](https://github.com/root-project/root/commit/0be8bbee9570776d17196b32c82db1d25c6e3530) has already corrected `ROOTSYS` with `$ROOTSYS` (i.e. `/usr/local`) but still the path is not correct considering that `gnuinstall=ON`. 

### Expected behavior
The correct environment variables would be
```
JUPYTER_PATH=/usr/local/etc/root/notebook
JUPYTER_CONFIG_DIR=/usr/local/etc/root/notebook
```

### To Reproduce
1. Build and install `latest-stable` branch
2. Modify `/usr/local/bin/thisroot.fish` prepending a `$` to `ROOTSYS` at lines 50 and 51
3. Source `/usr/local/bin/thisroot.fish` and run `jupyter-lab`
4. At this point an error shows that `/usr/local/etc/notebook` is not a valid path

### Setup
1. ROOT version: 6.24/00
2. Operating system: openSUSE Tumbleweed -- release: 20210606
3. Compiler version: gcc (SUSE Linux) 11.1.1 20210510 [revision 23855a176609fe8dda6abaf2b21846b4517966eb]
3. ROOT built for linuxx8664gcc on Jun 12 2021, 01:11:00, from heads/latest-stable@e6a04a86, with options:
  a. `gnuinstall=ON`
  b. `imt=ON`
  c. `minuit2=ON`
  d. `rpath=ON`
  e. `pyroot=ON`

### Additional context
Post on ROOT forum: [link](https://root-forum.cern.ch/t/rootsys-folder-created-starting-jupyterlab/45358)

**Comment by bellenot** [comment]
I don't understand. Why do you need to source `/usr/local/bin/thisroot.fish`. Isn't the `gnuinstall=ON` option supposed to install ROOT in the system standard location and hence avoid the need of sourcing anything? (sorry if it's a stupid question, but I work on Windows...)

**Comment by cavfiumella** [comment]
> I don't understand. Why do you need to source `/usr/local/bin/thisroot.fish`. Isn't the `gnuinstall=ON` option supposed to install ROOT in the system standard location and hence avoid the need of sourcing anything? (sorry if it's a stupid question, but I work on Windows...)

That's true, in fact to execute ROOT, sourcing `thisroot` scripts is not necessary but Python module and Jupyter Lab kernel are not in the default search paths and because of this `PYTHONPATH` and `JUPYTER_*` variables must be set anyways.

Personally I prefer to do it manually because the script doesn't consider that having `gnuinstall=ON` it don't need to set some of the other variables (e.g.` PATH`).

**Comment by bellenot** [comment]
OK, thanks for the info. Then maybe @Axel-Naumann, the author of the script, can give some hints how to solve this

**Comment by Axel-Naumann** [comment]
Thanks. I've applied 0be8bbee9570776d17196b32c82db1d25c6e3530 also to v6-24-00-patches as 5a3cc900fa934ccf7de0fdb45972d09d470e0d9f; it will be released soon.

I agree it'd be nice to have `thisroot.*` work also with `gnuinstall=On` - right now, none of the `thisroot.*` scripts work, this doesn't seem to be specific to `fish`.

Does `/usr/local/bin/root-config --etcdir` state the right thing?

**Comment by cavfiumella** [comment]
> Does `/usr/local/bin/root-config --etcdir` state the right thing?

Yes, it states `/usr/local/etc/root`

**Comment by dpiparo** [comment]
Closing since the backport worked.
