### ISSUE TITLE
segmentation violation

### ISSUE THREAD

**Issue by sabiha84** [root-project/root#8453]
- [ ] Checked for duplicates

**Comment by couet** [comment]
I guess that needs more details or should be dropped.

**Comment by eguiraud** [comment]
Hi @sabiha84 ,
a segmentation violation is typically a symptom of a bug in user code that causes the program to access invalid memory regions.

Please post on root-forum.cern.ch to receive support with these issues, this is most likely not a bug in ROOT itself.
