### ISSUE TITLE
Jupyroot has problems loading JSRoot.core.js in jupyterhub/jupyterlab 3.0

### ISSUE THREAD

**Issue by joequant** [root-project/root#8459]
- [ X] Checked for duplicates

### Describe the bug

Right now JupyROOT/helpers/utils.py checks if it is in a jupyterlab environment by checking if requirejs exists.  
However, jupyterhub/jupyterlab 3.0 loads requirejs so that the check gets bypassed.

### Expected behavior

Jupyterhub/jupyterlab should load in the scripts/JSRoot.core.js file not does not.

### To Reproduce

Run jsroot in jupyterlab/jupyterhub 3.0

### Setup

Root 6.22.08

**Comment by joequant** [comment]
<pre>@@ -49,6 +49,14 @@
 &lt;/div&gt;
 &lt;script&gt;
 if (typeof require !== &apos;undefined&apos;) {{
+    try {{
+        var base_url = JSON.parse(document.getElementById(&apos;jupyter-config-data&apos;).innerHTML).baseUrl;
+    }} catch(_) {{
+        var base_url = &apos;/&apos;;
+    }};
+    require.config({{
+        baseUrl: base_url + &apos;static/&apos;
+    }});
 
     // All requirements met (we are in jupyter notebooks or we loaded requirejs before).
     display_{jsDivId}();
</pre>

**Comment by ellert** [comment]
Hi. Will back-porting the following commit to 6.22 work?

commit a8125384d7c3cc14b7922dcedf7ec8b821d79b8f

**Comment by etejedor** [comment]
> Hi. Will back-porting the following commit to 6.22 work?

Probably, @joequant can you confirm this works for you from 6.24 onwards?

**Comment by ellert** [comment]
Here is the patch I applied for the Fedora/EPEL build:
https://src.fedoraproject.org/rpms/root/blob/rawhide/f/root-jupyroot-jupyterlab-compat.patch

This corresponds to:
git diff v6-22-08..ca72f6287bc2660d7cf45a3bd2dd7e4ad51b2aec -- bindings/jupyroot/python/JupyROOT/helpers/utils.py

**Comment by etejedor** [comment]
The PR referenced above has been merged with fixes for JSROOT-JupyROOT in ROOT 6.22. @ellert please note that it includes more changes than the patch you applied (I still couldn't see the JSROOT graphics in JupyterLab with that patch alone).
