### ISSUE TITLE
Axis Title for TEveRGBAPaletteOverlay

### ISSUE THREAD

**Issue by AlexFinch** [root-project/root#8488]

**Comment by osschar** [comment]
Could you use TGLAnnotation and put it where you want it to be? See `tutorials/eve/annotation.C`.

If you set state to disabled, eg, ` ann->SetState(TGLOverlayElement::kDisabled);` it won't show the edit buttons and allow the user to move it around.

**Comment by osschar** [comment]
TGLAnnotation trick works.
