### ISSUE TITLE
ranluxpp code is using left shift of negative value -1 which is undefined per the C standard

### ISSUE THREAD

**Issue by jirka-h** [root-project/root#8503]
In ranluxpp code, there is a left shift of negative value (c == -1)
https://github.com/root-project/root/blob/master/math/mathcore/src/ranluxpp/mulmod.h#L169

Please note that this behavior is undefined per the C standard. See for example:
https://stackoverflow.com/questions/8415895/is-left-and-right-shifting-negative-integers-defined-behavior

You can rewrite the code like this:
```
int64_t t2 = t0 - (int64_t) ( (uint64_t)c << 48);
```

to solve the problem. It has no performance impact (verified on i7-8650U CPU with GCC v10.3.1).

Here is the code I have used:
https://github.com/jirka-h/ranluxpp-portable

**Comment by hahnjo** [comment]
You're right, this is undefined behavior until C++20. I'll submit a fix shortly.

**Comment by jirka-h** [comment]
Thank you, Jonas!
