### ISSUE TITLE
Documentation for RooChi2Var missing

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#8519]
- [github] Checked for duplicates
### Describe the bug
On the page

https://root.cern.ch/doc/master/classRooChi2Var.html

there is only one block:

    PyROOT
    Constructor of RooChi2Var takes a RooCmdArg as argument also supports keyword arguments.

In the [source code](https://root.cern.ch/doc/master/RooChi2Var_8cxx_source.html) (and previous documentation versions, e.g. in my downloaded html documentation archive for v. 6.24 and v. 6.22), you can see that there is a lot of documentation for that class (at least more than can be seen now).
Which is funny, there is no reference to PyROOT in the docstrings.

### Expected behavior
Documentation should be present.

### To Reproduce
Visit documentation site.

**Comment by couet** [comment]
Clearly a bug. I am investigating. Something should have changed since 6.24. You can see it is ok here:
https://root.cern/doc/v624/classRooChi2Var.html
