### ISSUE TITLE
Warnings when configuring with CUDA 11.3

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#8537]
- [x] Checked for duplicates

### Describe the bug
Configuring with `-DCUDA=ON` leads to
```
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
CMake Warning (dev) at /opt/cmake-3.19/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (CUDNN) does
  not match the name of the calling package (CuDNN).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindCuDNN.cmake:40 (find_package_handle_standard_args)
  cmake/modules/SearchInstalledSoftware.cmake:17 (_find_package)
  cmake/modules/SearchInstalledSoftware.cmake:1669 (find_package)
  CMakeLists.txt:219 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found CUDNN: /usr/include  
-- Found cuDNN: v?  (include: /usr/include, library: /usr/lib64/libcudnn.so)
```

### Expected behavior
Don't warn.

### To Reproduce
`cmake -Dcuda=ON <src>`.

### Setup
- centos8
- cuda 11.3 installed via yum.
- Manos' master branch. It branched off from master on 22. Jun @ d026b4918a .

### Additional context
--

**Comment by bellenot** [comment]
Hi @hageboeck , I cannot try, but it looks like renaming `CuDNN` to `CUDNN` in [SearchInstalledSoftware.cmake](https://github.com/root-project/root/blob/master/cmake/modules/SearchInstalledSoftware.cmake#L1667-L1669) should fix those warnings. Can you try and let me know? Thanks in advance!

**Comment by hageboeck** [comment]
> Hi @hageboeck , I cannot try myself, but it looks like renaming `CuDNN` to `CUDNN` in [SearchInstalledSoftware.cmake](https://github.com/root-project/root/blob/master/cmake/modules/SearchInstalledSoftware.cmake#L1667-L1669) should fix those warnings. Can you try and let me know? Thanks in advance!

If I have to try it, I thought I might as well directly submit the patch ... 🙂

**Comment by bellenot** [comment]
> If I have to try it, I thought I might as well directly submit the patch ... 🙂

Thanks @hageboeck !
