### ISSUE TITLE
Add ability to run `RBrowser` and similar commands in "server mode"

### ISSUE THREAD

**Issue by ntadej** [root-project/root#8554]
### Explain what you would like to see improved
Add ability to run `RBrowser` and similar commands in "server mode":
When using on remote machines spawning browsers is inefficient and not desired. What could be useful is to just print the URL, which can be then opened in a browser on a different machine.

I apologise if this has already been reported/implemented. I can not find any reference to this in the code or documentation.

### To Reproduce (ideal)
1. Run `root --web=url`.
2. Run `ROOT::Experimental::RBrowser b`.
3. Only URL will be printed which can be then used on another machine.

**Comment by linev** [comment]
Good idea. 
We already have such mode for the `REve`, one can introduce generic flag.
I will do it soon.

**Comment by linev** [comment]
I create PR: https://github.com/root-project/root/pull/8575
You can try it.
