### ISSUE TITLE
Preserve JSROOT when generating reference guide

### ISSUE THREAD

**Issue by linev** [root-project/root#8599]
Starting from current master, we generate JSON for different v7 tutorials and embed them into HTML pages to
provide interactive images like:

https://root.cern/doc/master/draw__rh1__twoaxes_8cxx.html

For these images we are using https://root.cern/js/dev/ version, which constantly changes.
To be on the safe side, we should preserve JSROOT version with generated reference guide.
Most easy way - just copy JSROOT from ROOT sources into directory with doxygen HTML files 
and use that version of JSROOT in reference guide.

**Comment by couet** [comment]
Hi Sergey. I will try locally on my machine and make a PR once it is working.
