### ISSUE TITLE
[RF] Remove "No RooMinimizer" code paths.

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#8604]
There is a large section of code that's never checked (compiled) related to a time before RooMinimizer.
For example:
https://github.com/root-project/root/blob/7c4f9321a3fcbda598da6b815409a9a5ed72a53e/roofit/roofitcore/src/RooAbsPdf.cxx#L1599-L1783

This, together with the minimiser option `OldMinuit` (see RooAbsPdf::fitTo) should be removed.

_Originally posted by @hageboeck in https://github.com/root-project/root/pull/8569#discussion_r662968457_

**Comment by guitargeek** [comment]
Good idea! We can also move the `RooMinuit` class to RooFitLegacy I suppose. I have opened a PR to deprecate RooMinuit.
