### ISSUE TITLE
TH2 palette tick length is silently modified when passed to TGLAxisPainter

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8618]
- [x] Checked for duplicates

### Describe the bug
In a divided canvas, after some filling and "update", I see some weird horizontal lines of the color palette reaching over a TH2:

![image](https://user-images.githubusercontent.com/10653970/124624102-dec9a500-de7c-11eb-9784-d65c87d26679.png)

### Expected behavior
Palette lines stay were they were in the beginning.
![image](https://user-images.githubusercontent.com/10653970/124624297-0e78ad00-de7d-11eb-82f8-a27d2d7222b3.png)

### To Reproduce
1. Download [bugpalette.zip](https://github.com/root-project/root/files/6771012/bugpalette.zip)
2. Run as `root -l compton_reco.cpp+(2,0,true,true)`
3. Click one on the "next event arrow"
4. Click again, artefact appears
5. If you keep clicking, you will see that the lines move with the palette as the scale gets recalculated.

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.25/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on May 17 2021, 10:49:42                 |
  | From heads/master@v6-25-01-861-g5ea261143f                       |
  | With                                                             |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

**Comment by couet** [comment]
These lines are the tick marks of the palette axis. That's weird. I need to investigate.
I never saw such thing.

**Comment by ferdymercury** [comment]
Thanks for checking. Me neither. Although I have seen weird artefacts before with divided canvases, see:
https://sft.its.cern.ch/jira/browse/ROOT-7969

**Comment by couet** [comment]
I went a bit further. Nothing to do with the canvas division. I pruned your macro to the minium (there is no divide at that level) reproducing the problem. Then, I saved the buggy canvas to a .C macro. Which also shows the issue. And I reduced that's saved macro to the following few lines:
```
{
   TH2F *ConeOverlap = new TH2F("ConeOverlap","ConeOverlap",200,-400,400,200,-400,400);
   ConeOverlap->SetBinContent(47,1);
   ConeOverlap->GetZaxis()->SetTickLength(1); // faulty line
   ConeOverlap->Draw("COLZ");
}
```
As your macro doesn't not set the tick length for the Z axis. I now need to understand why it has a such value.
I continue to debug .

**Comment by ferdymercury** [comment]
Thanks! Maybe here?

https://github.com/root-project/root/blob/master/graf3d/gl/src/TGLAxisPainter.cxx#L574

**Comment by couet** [comment]
Yes, it is the faulty one. If I comment it the tick are ok. But that's in the Gl/3D part and you are not using PreferGL for you 2D pad. We are progressing ....

**Comment by couet** [comment]
So commenting that line cures the problem with your initial macro . Now I need to understand why that line was put there and why it changes the axis attributes of your histogram ! ... I invite @osschar to this discussion as he is the author of this code (https://github.com/root-project/root/blob/master/graf3d/gl/src/TGLAxisPainter.cxx#L574) . I am temped to simply comment the line but that's weird as fAxis is [a member of TGLAxisPainterBox](https://github.com/root-project/root/blob/aa21d63ca3a1f4cdb2b559e4cb1c2c2d7eb65f34/graf3d/gl/inc/TGLAxisPainter.h#L145) and that should not affect the axis of your TH2F ... That's a real puzzle ...

**Comment by ferdymercury** [comment]
Yes... really weird. I see that TPaletteAxis calls a function `ImportAxisAttributes`
Could it be that the active histogram is the one on the 3D view instead of the 'current histogram' when that function is called?

**Comment by couet** [comment]
Something like that may be... I am looking.

**Comment by couet** [comment]
This axis is set in [TGLPainterBox::PLotStandard](https://github.com/root-project/root/blob/aa21d63ca3a1f4cdb2b559e4cb1c2c2d7eb65f34/graf3d/gl/src/TGLAxisPainter.cxx#L621). In that method the histogram passed is "ConeOverlap" so your TH2F. And PlotStandard is called [from TH2GL::DirectDraw()](https://github.com/root-project/root/blob/aa21d63ca3a1f4cdb2b559e4cb1c2c2d7eb65f34/graf3d/gl/src/TH2GL.cxx#L126). For some reason I do not understand yet the histogram pointer there : `fM` points to your histogram.

**Comment by ferdymercury** [comment]
Well, that's because I am drawing the same TH2 histogram in the 3D viewer as well as in the canvas.

See:
`x->SetPlot(h,"GLSURF2");`

h is the same TH2 histogram as drawn with COLZ in the canvas.

**Comment by couet** [comment]
I see, ... so that's clearly a bug in that case, the 3D viewer should not change the axis attributes silently ...
I am in favour to remove that line ..

**Comment by couet** [comment]
Fix here: https://github.com/root-project/root/pull/8621
