### ISSUE TITLE
PyROOT triggers a warning about [[nodiscard]] vector::empty with GCC11

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#8622]
### Describe the bug
```python
import ROOT

ROOT.gInterpreter.Declare(
    """
    struct S{
        std::vector<int> vec1;
    };
    """)

s = ROOT.S()
if (s.vec1.empty()):
    print("s vec1 is empty")
```
```
$ python struct_with_vec_empty_nodiscard.py 
input_line_38:10:7: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
      ((const vector<int>*)obj)->empty();
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
s vec1 is empty
```
### Expected behavior

No warning triggered.

### Setup
ROOT 6.25 built on Fedora34 with GCC 11

### Additional context
This is the behaviour at the root prompt
```
root [0] std::vector<int> vec1;
root [1] vec1.empty()
ROOT_prompt_1:1:1: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
vec1.empty()
^~~~~~~~~~
(bool) true
root [2] if (vec1.empty()) {}
```

**Comment by yipengsun** [comment]
I got a similar error when using `RDataFrame` in Python, presumably with the same problem:

I'm using ROOT 6.24.02 with gcc10, compiled w/ C++ 17 standard.

Here's a reproducer:
```
#!/usr/bin/env python

import ROOT

# Let's create a simple dataframe with ten rows and two columns
df = ROOT.RDataFrame(10) \
         .Define("x", "(int)rdfentry_") \
         .Define("y", "1.f/(1.f+rdfentry_)")

npy = df.AsNumpy()
``` 

The error messages are:
```
input_line_49:10:7: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
      ((const vector<int>*)obj)->empty();
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
input_line_56:10:7: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
      ((const vector<float>*)obj)->empty();
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by eguiraud** [comment]
I just encountered this. A minimal reproducer that makes use of the underlying code triggering this issue within `AsNumpy`:

```
import ROOT

v = ROOT.vector[float]()
hasattr(v, "__array_interface__")
```

**Comment by jalopezg-r00t** [comment]
> Does `root [0] .x foo.C` diagnose unused results in `foo.C`'s `foo()`, even if the `FilteringDiagConsumer` disables it _at the prompt_ (i.e. hopefully only for expressions / code entered at the prompt)?

Yes, we will be emitting warnings in that case -except for unnamed macros, whose contents are parsed as if they came from the prompt [see here](https://github.com/root-project/root/blob/master/core/metacling/src/TCling.cxx#L2575).  If that is good enough, we can go for it -just need changing some lines.

If not, a different, more precise implementation (requiring more work) would be to buffer diagnostics and selectively suppress `diag::warn_unused_result` from `Value{Printer,Extraction}Synthesizer` based on the SourceLocation.  @Axel-Naumann, what do you think?

**Comment by Axel-Naumann** [comment]
I think this is good enough. Thanks.

**Comment by jalopezg-r00t** [comment]
> I think your first option is good enough. Thanks.

Sorry, I was completely wrong with the origin of the problem.  The original issue came from wrapper functions generated by `TClingCallFunc`, which in turn ends up triggering warnings when used by cppyy/PyROOT.

The way to go is to supress `-Wunused-result` diagnostics only for `TClingCallFunc` wrapper functions.  See all the information in the linked PR.
