### ISSUE TITLE
ROOT recompilation speed with CMake and dependencies

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8624]
### Explain what you would like to see improved
When modifying ROOT source code (and even when not), it takes quite some time to recompile, even with ccache enabled. It seems that many things are re-compiled even if they do not depend directly on each other.

### Optional: share how it could be improved
Remove unneeded dependencies.

### To Reproduce
No-modification at all of the source code, ccache ON.
1. cd into build directory
2. Call `time make`
3. Takes 59 seconds with 1 core
4. Takes 7 seconds with 32 cores

Quite some time is spent on these lines, they seem to be rebuilt even if nothing was changed:
```
[ 76%] Built target X86CommonTableGen
[ 76%] Built target LLVMX86Info
[ 76%] Built target LLVMX86AsmParser
[ 76%] Built target LLVMX86Utils
[ 76%] Built target LLVMX86Disassembler
[ 76%] Built target LLVMX86Desc
[ 76%] Built target LLVMX86CodeGen
```

Now, an example with modification:
1. cd into build directory
2. Call `touch sourceDir/core/base/src/TROOT.cxx`
3. Call `time make`
4. Takes 485 seconds in 1 core
5. Takes 102 seconds in 32 cores

Many dictionaries `G__.cxx`, `.pcm` objects are being rebuilt and libraries relinked even if no header changed.

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.25/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jul 07 2021, 12:59:42                 |
  | From heads/master@v6-25-01-1572-gaa21d63ca3                      |
  | With c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0                    |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
Maybe related https://github.com/root-project/root/pull/791

**Comment by hahnjo** [comment]
Hi @ferdymercury,

at least for the first point (rebuilding without any change), you should try using Ninja via `cmake -G Ninja`. Makefiles are known inefficient to detect that no work has to be done - the `Built target [...]` lines don't actually do anything, it's the point where the build system detects that the target has already been built. With Ninja, a "build" takes only a split of a second if there's nothing to be done (even though I'd argue that's not really the important benchmark for a build system).

For the second point, I think `core/base/src/TROOT.cxx` is so fundamental that it needs to rebuild `root.exe` and `rootcling` which in turn triggers rebuilding of a whole bunch of other things. Not sure if it would be possible to do something about this, cc @Axel-Naumann?

**Comment by ferdymercury** [comment]
Thanks @hahnjo for the suggestion. Ninja improves things considerably:
- Recompile without modifications: 0-delay
- Recompile after touch TROOT: 120s

**Comment by hahnjo** [comment]
> Recompile after touch TROOT: 120s

Note that `ninja` uses many jobs by default, so it's actually worse than the initial time of 102 seconds with 32 cores

**Comment by ferdymercury** [comment]
Ok, I understand, thanks for the reply. What about the recompilation-time when nothing at all is modified in the source code (with CMake). Why is time spent re-building these files? (They take quite some time).

```
[ 38%] Building X86GenAsmMatcher.inc...
[ 38%] Building X86GenAsmWriter.inc...
[ 38%] Building X86GenAsmWriter1.inc...
[ 38%] Building X86GenCallingConv.inc...
[ 38%] Building X86GenDAGISel.inc...
[ 38%] Building X86GenDisassemblerTables.inc...
[ 38%] Building X86GenEVEX2VEXTables.inc...
[ 38%] Building X86GenExegesis.inc...
[ 38%] Building X86GenFastISel.inc...
[ 38%] Building X86GenGlobalISel.inc...
[ 38%] Building X86GenInstrInfo.inc...
[ 38%] Building X86GenRegisterBank.inc...
[ 39%] Building X86GenRegisterInfo.inc...
[ 39%] Building X86GenSubtargetInfo.inc...
[ 39%] Building NVPTXGenAsmWriter.inc...
[ 39%] Building NVPTXGenDAGISel.inc...
[ 39%] Building NVPTXGenInstrInfo.inc...
[ 39%] Building NVPTXGenRegisterInfo.inc...
[ 39%] Building NVPTXGenSubtargetInfo.inc...
```

**Comment by ferdymercury** [comment]
Here another CMake benchmark, touching TH1.cxx instead of TROOT.cxx

- touch `sourceDir/hist/hist/src/TH1.cxx`
- 327 seconds in 1 core
- 67 seconds in 32 cores

(Many dictionaries, e.g. in Roofit, TMVA, ... are being rebuilt, even if the header was not changed.)

**Comment by hahnjo** [comment]
> Ok, I understand, thanks for the reply. What about the recompilation-time when nothing at all is modified in the source code (with CMake). Why is time spent re-building these files? (They take quite some time).
> 
> ```
> [ 38%] Building X86GenAsmMatcher.inc...
> [ 38%] Building X86GenAsmWriter.inc...
> [ 38%] Building X86GenAsmWriter1.inc...
> [ 38%] Building X86GenCallingConv.inc...
> [ 38%] Building X86GenDAGISel.inc...
> [ 38%] Building X86GenDisassemblerTables.inc...
> [ 38%] Building X86GenEVEX2VEXTables.inc...
> [ 38%] Building X86GenExegesis.inc...
> [ 38%] Building X86GenFastISel.inc...
> [ 38%] Building X86GenGlobalISel.inc...
> [ 38%] Building X86GenInstrInfo.inc...
> [ 38%] Building X86GenRegisterBank.inc...
> [ 39%] Building X86GenRegisterInfo.inc...
> [ 39%] Building X86GenSubtargetInfo.inc...
> [ 39%] Building NVPTXGenAsmWriter.inc...
> [ 39%] Building NVPTXGenDAGISel.inc...
> [ 39%] Building NVPTXGenInstrInfo.inc...
> [ 39%] Building NVPTXGenRegisterInfo.inc...
> [ 39%] Building NVPTXGenSubtargetInfo.inc...
> ```

IIRC that might be another limitation of `make` which you can again get around with Ninja:
```
 $ ninja
ninja: no work to do.
```

**Comment by ferdymercury** [comment]
Closely related: https://github.com/root-project/root/issues/6432

**Comment by hahnjo** [comment]
I think we should close this issue, many / most of the dependencies are correct and `make` being slow when there is nothing to do is exactly the motivation to use Ninja. So not much to improve from the ROOT side of things.

**Comment by hahnjo** [comment]
We're building LLVM in `Release` mode (unless a developer explicitly asks for something else, and even that is only a subset of ROOT developers), so `LLVM_OPTIMIZED_TABLEGEN` will actually be *slower* because it requires an extra, internal CMake invocation. To give some context, this option is meant for upstream development if you have a `Debug` build of LLVM which makes `{llvm,clang}-tablegen` *very* slow, but aren't actually debugging the `tablegen` infrastructure.

**Comment by ferdymercury** [comment]
Oh, I see thanks.
And what about https://reviews.llvm.org/rGf7cf1a1a7353dc5c578dfc85eb963e61a4d406cd ?
Is that fix maybe appearing in later versions of ROOT?

**Comment by hahnjo** [comment]
The first commit goes back to LLVM 8, so it is included in ROOT's copy of the sources, see https://github.com/root-project/root/blob/f39eb0e98466830a547f0b66501c70794f0aa3c6/interpreter/llvm/src/lib/TableGen/Main.cpp#L117-L122 The revert only made it to LLVM 10, so it will come with the upgrade to LLVM 13 currently being prepared. However, I don't think this is a real problem because the support for nor rebuilding the files only toggled between CMake and `tablegen` itself.

The third commit you link is for MLIR, which we don't build for ROOT, and thus not relevant.

**Comment by ferdymercury** [comment]
> The third commit you link is for MLIR, which we don't build for ROOT, and thus not relevant.

I was just thinking that the same file is here in ROOT, and there might have been some updates inbetween changing something in the way it is built so that it does not rebuild every time.

https://github.com/root-project/root/blob/f39eb0e98466830a547f0b66501c70794f0aa3c6/interpreter/llvm/src/cmake/modules/TableGen.cmake

Related discussion also here https://mattermost.web.cern.ch/root/pl/gh9ueukejifcpxeba5mp3ncyyw
mentioning that this part also runs always even if nothing was touched:

```
[ 49%] Copying /home/blue/ROOT/master/tutorials/CMakeLists.txt
[ 49%] Copying /home/blue/ROOT/master/tutorials/dataframe/df017_vecOpsHEP.C
[ 49%] Copying /home/blue/ROOT/master/tutorials/dataframe/df103_NanoAODHiggsAnalysis.py
[ 49%] Copying /home/blue/ROOT/master/tutorials/image/hsumanim.C
```

**Comment by hahnjo** [comment]
> I was just thinking that the same file is here in ROOT, and there might have been some updates inbetween changing something in the way it is built so that it does not rebuild every time.

Sure, but if you look at https://github.com/llvm/llvm-project/commit/8eb4b3e2be008fc3455b3c2820b1b55d2a5c25f0 you see that the change to `TableGen.cmake` only adds an additional variable `LLVM_TARGET_DEPENDS` that the caller can set. This is done in one place of MLIR, but nowhere else in LLVM or ROOT so there won't be any difference.



> mentioning that this part also runs always even if nothing was touched:
> 
> ```
> [ 49%] Copying /home/blue/ROOT/master/tutorials/CMakeLists.txt
> [ 49%] Copying /home/blue/ROOT/master/tutorials/dataframe/df017_vecOpsHEP.C
> [ 49%] Copying /home/blue/ROOT/master/tutorials/dataframe/df103_NanoAODHiggsAnalysis.py
> [ 49%] Copying /home/blue/ROOT/master/tutorials/image/hsumanim.C
> ```

"Copying" files has nothing to do with TableGen. Furthermore, this looks like output from GNU Make. As I wrote above, *never* use GNU Make if you want fast incremental builds - use Ninja!
