### ISSUE TITLE
RooStats::HypoTestInverterResult::FindIndex fails if xvalue == 1

### ISSUE THREAD

**Issue by aemerman** [root-project/root#8641]
- [x] Checked for duplicates

### Describe the bug

In RooStats::HypoTestInverterResult::FindIndex( x ), if x == 1 then the return value is always -1 rather than the index of that xvalue. The problem is on L571-573 (in current master) of HypoTestInverterResult.cxx where the following if statement is used:
<pre>
if ( (std::abs(xvalue) > 1 && TMath::AreEqualRel( xvalue, xpoint, tol) ) ||
     (std::abs(xvalue) < 1 && TMath::AreEqualAbs( xvalue, xpoint, tol) ) )
  return i; 
</pre>

Please change the first piece of one of these two statements to include xvalue==1 (i.e. from &gt; to &ge; or &lt; to &le;). I don't think it matters which is changed.

### Expected behavior

FindIndex should return the index of requested xvalue in the internal results array.

### Setup

I am using ROOT 6.22/00 from LCG_98python3 but this is still in issue in the master branch (per online documentation).

**Comment by guitargeek** [comment]
Hi @aemerman, thank you for reporting this. I will fix this in ROOT master and also make backports to 6.24 and 6.22 since you are using this release. Do you need this fix in any older release?

**Comment by aemerman** [comment]
Thank you! No, I don't need any older release.
