### ISSUE TITLE
TGHtml restore from TBrowser TFile

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8647]
### Explain what you would like to see improved
TGHtml objects can be stored into a TFile. However, when opening a TBrowser, right click or double click leads to:
```
Error in <TQClass::New>: cannot create object of class TGHtml
Error in <TKey::ReadObj>: Cannot create new object of class TGHtml
```

It would be nice if it would be supported in the TBrowser.

### Optional: share how it could be improved
- Right click, dump, prints the HTML code to terminal
- Double click reproduces the TGHtml on a canvas?

### To Reproduce
1. Store TGHtml object to TFile
2. Open TFile with TBrowser and double-click

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.25/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on May 17 2021, 10:49:42                 |
  | From heads/master@v6-25-01-861-g5ea261143f                       |
  | With                                                             |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

**Comment by jalopezg-r00t** [comment]
@bellenot, I have assigned this issue to you, but I might be perfectly wrong...  Let me know if it should be assigned to someone else.

**Comment by bellenot** [comment]
@jalopezg-r00t no, you're right, that's for me, thanks!

**Comment by bellenot** [comment]
Well, the GUI classes are not meant to be stored in ROOT files. BTW, how did you save your TGHtml?

**Comment by ferdymercury** [comment]
I was using myHtml->Write(...)

**Comment by bellenot** [comment]
> I was using myHtml->Write(...)

OK, this doesn't work for me. And you should not try. As I said, all the GUI classes are not meant to be saved in ROOT files.

**Comment by bellenot** [comment]
Closing this issue: GUI classes are not meant to be saved
