### ISSUE TITLE
[RF] Remove accidentally introduced I/O capabilities of RooMinimizer.

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#8652]
@guitargeek @egpbos

Stop, stop!! e3b73a8 needs to be reverted before releasing ROOT.

`ClassDef(..., 0)` means: Don't support I/O.
In e3b73a8, you switched on I/O capabilities, so please revert! When people start writing minimiser states to files, you will have to support deserialisation in the future. It's better to not support that.

**That by the way also holds for any classes the are introduced in the MP-PRs. Please consider well wether they are allowed to support I/O or not.**

_Originally posted by @hageboeck in https://github.com/root-project/root/issues/8569#issuecomment-878850453_

**Comment by guitargeek** [comment]
Thanks bot, I put "not applicable" because the issue was arising during a development cycle only, and fixed within the same cycle.
