### ISSUE TITLE
GrabKey not working with kKeyControlMask on TGX11

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8665]
- [x] Checked for duplicates

### Describe the bug
In TGMainWindow, if I call:
`gVirtualX->GrabKey(GetId(), gVirtualX->KeysymToKeycode(kKey_c), kKeyControlMask, kTRUE); //capture CTRL+C`
and press CTRL+C, it never reaches the HandleKey function.
If I instead call:
`gVirtualX->GrabKey(GetId(), gVirtualX->KeysymToKeycode(kKey_c), kAnyModifier, kTRUE);`

it reaches the HandleKey function:
`event->fState = 20, event->fState & kKeyControlMask = 4`

This is also the reason why some of TRootGuiBuilder shortcuts are not working.
![image](https://user-images.githubusercontent.com/10653970/125503490-0ccae6c6-8757-42f7-aad4-acf563b0b9a6.png)

### Expected behavior
GrabKey works well with kKeyControlMask on TGX11.

### To Reproduce
1. new TRootGuiBuilder
2. Press CTRL+N
3. It does not do anything

**Comment by bellenot** [comment]
The code below works fine for me on Windows:
```
//______________________________________________________________________________
//
//
//______________________________________________________________________________
class MyMainFrame : public TGMainFrame {
public:
   MyMainFrame(const TGWindow *p, UInt_t w, UInt_t h);
   virtual ~MyMainFrame() { Cleanup(); }
   void     CloseWindow() { delete this; }
   Bool_t   HandleKey(Event_t *event);
   
   ClassDef(MyMainFrame, 0)
};

//______________________________________________________________________________
MyMainFrame::MyMainFrame(const TGWindow *p, UInt_t w, UInt_t h) : TGMainFrame(p, w, h)
{
   gVirtualX->GrabKey(GetId(), gVirtualX->KeysymToKeycode(kKey_c), kKeyControlMask, kTRUE);
   MapSubwindows();
   Layout();
   MapWindow();
   Resize(150,100);
}

//______________________________________________________________________________
Bool_t MyMainFrame::HandleKey(Event_t *event)
{
   char tmp[2];
   UInt_t keysym;
   gVirtualX->LookupString(event, tmp, sizeof(tmp), keysym);
   if (event->fType == kGKeyPress) {
      if (event->fState & kKeyControlMask) {   // Cntrl key modifier pressed
         switch ((EKeySym)keysym & ~0x20) {   // treat upper and lower the same
            case kKey_C:
               std::cout << "CTRL+C key pressed!" << std::endl;
               break;
            default:
               break;
         }
      }
   }
   return kTRUE;
}

//______________________________________________________________________________
void test_grab_key()
{
   MyMainFrame *main = new MyMainFrame(gClient->GetRoot(), 150, 100);
}
```
I'll try on Linux and let you know

**Comment by ferdymercury** [comment]
Thanks for the reproducer. I tried your code and nothing is printed in terminal for me when I press CTRL+C.

**Comment by bellenot** [comment]
And it works for me on Linux Mint 20.1

**Comment by bellenot** [comment]
Maybe your system catches the CTRL+Key events somehow

**Comment by ferdymercury** [comment]
Mmm pretty weird. But why should it recognize then as CTRL+C in the HandleKey function ?

**Comment by bellenot** [comment]
> But why should it recognize then as CTRL+C in the HandleKey function when using kAnyModifier ?

No idea... Try pressing `Shift+C` with `kAnyModifier`, it should work as well

**Comment by bellenot** [comment]
And `gVirtualX->GrabKey()` doesn't do much:
```
void TGX11::GrabKey(Window_t id, Int_t keycode, UInt_t modifier, Bool_t grab)
{
   UInt_t xmod;
   MapModifierState(modifier, xmod);
   if (grab)
      XGrabKey((Display*)fDisplay, keycode, xmod, (Window) id, True,
               GrabModeAsync, GrabModeAsync);
   else
      XUngrabKey((Display*)fDisplay, keycode, xmod, (Window) id);
}
```

**Comment by ferdymercury** [comment]
Nope, I tried, only CTRL+C prints the message "CTRL+C pressed". Shift+C does not.

`if (event->fState & kKeyControlMask)`

is evaluating to true only if Ctrl+C is pressed. But then it's a mistery why it does not work with GrabKey.

Could you point at which function in TUnixSystem should I run the debugger to see what happens?

**Comment by bellenot** [comment]
I just did

**Comment by ferdymercury** [comment]
Thanks Bertrand for the help. Here is what I see from the debugger:

with kKeyControlMask
![image](https://user-images.githubusercontent.com/10653970/125524664-42273c47-5c81-4412-b437-04c5288bb2e8.png)

with kAnyModifierMask
![image](https://user-images.githubusercontent.com/10653970/125524815-fb7dd292-cd64-4256-ad8f-410588aa9b91.png)


(Side note: There is one additional GrabKey called by TGMainFrame itself, but I skipped it):
![image](https://user-images.githubusercontent.com/10653970/125524240-89770473-95ab-4916-9501-3b2162819a95.png)

Side note 2: Playing around and halting the debugger, sometimes my keyboard key-repetition stops. gVirtualX calls in several places SetAutoRepeat(false)... Not sure if that has anything to do. I have then to reset it using `xset r on`.

**Comment by ferdymercury** [comment]
Does it work for you if you press CTRL+S in your test window?

![image](https://user-images.githubusercontent.com/10653970/125535842-ef2928b0-e337-4fa4-a523-b41adbab04da.png)

(It's not working for me, either)

**Comment by bellenot** [comment]
So the debug sessions look fine, the values are correct. And in order to properly handle the default `TGMainFrame` key events, you must replace `return kTRUE;` by `return TGMainFrame::HandleKey(event);` in `Bool_t MyMainFrame::HandleKey(Event_t *event)`

**Comment by ferdymercury** [comment]
Thanks for the suggestion. I have changed return kTRUE with:
```
   std::cout << event << " " << event->fType << " " << event->fState << std::endl;
   return TGMainFrame::HandleKey(event);
```

When I run it, pressing CTRL+C or pressing CTRL+S has no effect, nothing is printed.
If I change kKeyControlMask to kAnyModifier, CTRL+C works, but CTRL+S does not work.
```
CTRL+C key pressed!
0x7ffdaf78cda0 0 20
0x7ffdaf78cda0 1 20
```

**Comment by bellenot** [comment]
OK, that's weird, but since I cannot reproduce the issue, I don't know what else I can do, and I don't even know how I could fix that issue...

**Comment by ferdymercury** [comment]
Thanks for the help. Maybe I can use myself https://www.x.org/releases/X11R7.5/doc/man/man1/xscope.1.html to try to find out ? I tried to printout stuff in TGX11 but when I press CTRL+C or CTRL+S, nothing literally happens, unix is waiting in the `select()` function.

**Comment by bellenot** [comment]
It might be unrelated, but while trying to find a similar WM related issue, I found  https://askubuntu.com/questions/1024597/ubuntu-16-04-ctrlalts-doesnt-work

**Comment by bellenot** [comment]
> Thanks for the help. Maybe I can use myself https://www.x.org/releases/X11R7.5/doc/man/man1/xscope.1.html to try to find out ? I tried to printout stuff in TGX11 but when I press CTRL+C or CTRL+S, nothing literally happens, unix is waiting in the `select()` function.

I can't help, I'm working mostly on Windows

**Comment by ferdymercury** [comment]
I used "xtrace", and I got messages printed when I use kAnyModifier, but none without it.

```
_root [1] 000:<:0549: 12: Request(102): ChangeKeyboardControl values={auto-repeat-mode=On(0x01)}
000:>:0549: Event KeyPress(2) keycode=0x36 time=0x174cf013 root=0x00000185 event=0x07e000e7 child=None(0x00000000) root-x=939 root-y=542 event-x=54 event-y=38 state=Control,Mod2 same-screen=true(0x01)
CTRL+C key pressed!
0x7ffdd1322ea0 0 20
000:>:0549: Event KeyRelease(3) keycode=0x36 time=0x174cf0b3 root=0x00000185 event=0x07e000e7 child=None(0x00000000) root-x=939 root-y=542 event-x=54 event-y=38 state=Control,Mod2 same-screen=true(0x01)
0x7ffdd1322ea0 1 20_
```

Now to the funny part. I added the following to the mask:
`kKeyShiftMask | kKeyLockMask | kKeyControlMask | kKeyMod1Mask | kKeyMod2Mask | kKeyMod3Mask | kKeyMod4Mask | kKeyMod5Mask | kButton1Mask | kButton2Mask | kButton3Mask | kButton4Mask | kButton5Mask | kButton6Mask | kButton7Mask`

and it still didn't work.

Then I added `kAnyModifier`, and it worked.

Then I removed all of them and replace with just kKeyControlMask. And then it worked.

So now it works perfectly as it should and lets me even more confused. It seems there is something fishy going on with X11 being let in an undefined state that somehow playing around was enough to 'reset it'.

**Comment by bellenot** [comment]
So do we agree that it's not a bug in ROOT?

**Comment by ferdymercury** [comment]
Yes, thanks for the help :)

**Comment by ferdymercury** [comment]
I'm having the problem again now, and I am not sure how to 'reset' my keyboard so that it starts working again.

Searching a bit more, I think this might be related to this "feature" of X11:

https://bugs.freedesktop.org/show_bug.cgi?id=99280
https://stackoverflow.com/questions/18160792/python-xlib-xgrabkey-keyrelease-events-not-firing
https://github.com/zhanghai/xkeymacs/issues/1
https://stackoverflow.com/questions/39087079/detect-modifier-key-release-in-x11-root-window

Maybe it also explains why, randomly, my keyboard key repetition is 'deactivated'.

**Comment by ferdymercury** [comment]
Ok, never mind, I finally found out what was happening. The problem was that the kKeyControlMask 'fails' if NumLock key was activated. By changing it to 'any modifier', it was capturing it.

Side note: I also called gVirtualX->GrabKey(..., kFALSE) in my destructor classes, just to make sure everything goes back to normal after exiting.
