### ISSUE TITLE
RDF progress bar

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#8685]
### Is your feature request related to a problem? Please describe.

It would be great to have a progress bar for RDF, one that does not need to open all files before giving an estimate on the remaining processing time.

### Describe the solution you'd like

Similar to https://github.com/root-project/root/pull/8675 but with the approach sketched in https://github.com/root-project/root/pull/8675#discussion_r670348181

**Comment by eguiraud** [comment]
This depends on https://github.com/root-project/root/issues/6745

**Comment by vepadulano** [comment]
Closed by https://github.com/root-project/root/pull/13210
