### ISSUE TITLE
Documentation incorrect - default units are G4 not ROOT

### ISSUE THREAD

**Issue by knoepfel** [root-project/root#8695]
A commit from earlier this year (https://github.com/root-project/root/commit/3d545273d7763e09aa85449ba86be5d2493f7f13) adjusted the handling of default units in ROOT's geometry system.  Although this commit is an ostensible improvement, reducing points of maintenance, there are some consequences that were maybe not anticipated.

I refer to the [units README file](https://github.com/root-project/root/blob/master/geom/geom/README_units.md).  In that file it states:

> To ensure backwards compatibility ROOT's default system of units is - as it was before - based on centimeters, seconds and GigaElectronVolts, ie. the defaults are equivalent to:
> 
> ```c++
> TGeoManager::SetDefaultUnits(kRootUnits);
> ```

Unfortunately, this statement is not true.  As you see from the definition of the `TGeoManager::fgDefaultUnits` static data member https://github.com/root-project/root/blob/49d0be0b9455e026e6d68e2e651113af3f1e4654/geom/geom/src/TGeoManager.cxx#L302 the default units are G4 units, which it has been for some time (perhaps the beginning?).  There was thus an inconsistency with the default units and with those assumed by TGDMLParse, which, before the above commit, made an unconditional assumption of ROOT units.

The above commit addresses this inconsistency, but the neutrino community at Fermilab (specifically the LArSoft project and the experiments it supports) experienced an [unintended consequence](https://github.com/LArSoft/larcorealg/pull/18)--the default units are now honored by the TGDML parser, but they are simply G4 units instead of ROOT units.

In order to make ROOT units the default, we use the workaround:

```c++
TGeoManager::LockDefaultUnits(false);
TGeoManager::SetDefaultUnits(TGeoManager::kRootUnits);
TGeoManager::LockDefaultUnits(true);
```

as the units are locked upon library load: https://github.com/root-project/root/blob/612b68ea1f70c3f5ce7deb8a6b664b8a08987991/geom/geom/src/TGeoManager.cxx#L304

This issue requests two things:

- Please correct the README file to accurately state the default units (G4).
- Suggest a better mechanism to allow the user to establish the default units.

**Comment by jalopezg-r00t** [comment]
@agheata, I have assigned this to you (according to the CODEOWNERS file), but not really sure if you are responsible of this...  Please, let me know if it's not the case.

Cheers.

**Comment by agheata** [comment]
There were several fixes available now in the master for having consistent behavior when using Root versus Geant4 units, which can be set now once before defining any elements or materials without having to lock/unlock:
`TGeoManager::SetDefaultUnits(TGeoManager::kG4Units);`
The default units are Root ones (as described in the docs). Please modify this ticket if you observe any other inconsistency.
