### ISSUE TITLE
Documentation in C++ classes gets mixed with PyROOT doc box

### ISSUE THREAD

**Issue by etejedor** [root-project/root#8712]
The box that contains PyROOT documentation for a given class used to appear after the documentation that is written in the C++ file for that class. This is not the case anymore, for example:

https://root.cern.ch/doc/master/classTTree.html
https://root.cern.ch/doc/master/classTFile.html

Currently the first sentence of the C++ file docs appears first, after that there is the PyROOT box and finally the rest of the docs present in the C++ file.

**Comment by couet** [comment]
I am investigating why the Python panels are now coming first in the documentation. I think they came last just "by chance" before. Nothing indicates which `\class TFile` should be read first. Which by the way is something also a bit stange ie:  twice the same `\class` ... I suspect Doxygen behavior is undefined in that case. I did not find anything mentionning the fact we can have the same `\class` twice... I am investigating ... no solution yet.

**Comment by couet** [comment]
I opened an issue on the doxygen repository asking what the behaviour should be when `\class` is defined twice.
https://github.com/doxygen/doxygen/issues/8693

**Comment by etejedor** [comment]
This was fixed by https://github.com/root-project/root/pull/8971
