### ISSUE TITLE
TF1 Derivative of the whole Function with respect to any variable

### ISSUE THREAD

**Issue by AdvaitDhingra** [root-project/root#8735]
### Is your feature request related to a problem? Please describe.

Getting the derivative of a TF1 is not that simple. It's a common thing so it should be simple. 

### Describe the solution you'd like

At the moment it's not that simple to get the derivative of a TF1. There is a method to determine the derivative at a point but it would be nice if you could
- get the derivative of the whole function
- get the derivative with respect to any variable (d/dx, d/dy, d/dz ...) not just x.
### Describe alternatives you've considered

I read that there is a Derivator but it doesn't seem that easy to use. If a TF1 derivative method is not added, maybe the Derivator docs could be improved/tutorials made.

REASONING:

There are a lot of cool math functions that I would like to add and they rely on partial derivatives with respect to different variables and at the moment they are near impossible to make.

**Comment by AdvaitDhingra** [comment]
One solution for a general derivative function could be to simply pass "Function->Derivative(x)" in the second TF1. But there still needs to be a way to differentiate with respect to any variable.

**Comment by dpiparo** [comment]
TF1 only has one variable.

**Comment by lmoneta** [comment]
This is not completely correct since TF1 is a base class and also represents generic functions in the N-dimension. 
I think it would not be bad to have also a Gradient function as we have GradientPar. On the other hand, we have the Derivator class, which can be easily used.
