### ISSUE TITLE
ROOT 7 c++ standard not updated on documentation

### ISSUE THREAD

**Issue by SpectreVert** [root-project/root#8743]
The `CMAKE_CXX_STANDARD` value indicated for building ROOT7 is `c++14`, however it now requires `c++17` so documentation should be updated, namely (and maybe not limited to):

- https://root.cern/for_developers/root7/
- https://root.cern/install/build_from_source/#enabling-experimental-features-aka-root7

**Comment by couet** [comment]
Now fixed. Thank.
