### ISSUE TITLE
[TGaxis] secAxis->SetMaxDigits changes all other axes

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8774]
### Is your feature request related to a problem? Please describe.
A long-standing TGaxis issue is that calling secondaryXaxis->SetMaxDigits(N) affects all other X and Y axes in the current canvas.

### Describe the solution you'd like
TGaxis::SetMaxDigits, StripDecimals, etc. are all axes-dependent and don't affect the default state of other axes.

### Additional context
https://root-forum.cern.ch/t/tgaxis-setmaxdigits/11543/2?u=ferhue
https://sft.its.cern.ch/jira/browse/ROOT-35
https://root-forum.cern.ch/t/tgaxis-setmaxdigits-not-working-as-expected/2889/3
https://root-forum.cern.ch/t/tgaxis-and-setmaxdigits/19425/5

**Comment by ferdymercury** [comment]
Never mind, I found it was fixed in 2017 https://sft.its.cern.ch/jira/browse/ROOT-35

**Comment by ferdymercury** [comment]
Here an example. If I do not do anything on my secondary TGaxis, I get:
![image](https://user-images.githubusercontent.com/10653970/127576253-edbae2df-f8f2-472c-ac2f-979a4999ed32.png)

If I call on my custom TGaxis:
`secAxis->SetMaxDigits(2)`, I get:
![image](https://user-images.githubusercontent.com/10653970/127576321-f31bc836-5780-4877-9d20-a1541c52a4f1.png)

If I later explictly call
`histogram->GetYaxis()->SetMaxDigits(3);`

it has no effect, I still get 2 numbers and then an exponent on the y axis.

**Comment by ferdymercury** [comment]
(I think this should be rather labelled a bug than a new feature)

**Comment by couet** [comment]
`SetMaxDigits` now works on individual axis. It is not only global anymore as said in the Jira report you referred to (https://sft.its.cern.ch/jira/browse/ROOT-35) . I am not sure I fully understand  what this "new feature" is about . Can you post a small running macro reproducing the issue ?

**Comment by ferdymercury** [comment]
Sure, here a reproducer:

```
#include "TCanvas.h"
#include "TH1F.h"
#include "TGaxis.h"
#include "TF1.h"

void test_tgaxis(bool enableDigits = false)
{
    TCanvas* c = new TCanvas();
    TH1* h = new TH1F("h","h",10,44,54);
    h->SetBinContent(1,180);
    h->SetStats(kFALSE);
    h->Draw("hist");
    c->Modified();
    c->Update();

    TF1* f1 = new TF1("f1",TString(to_string(256))+"*1024*1024/(x*1e-3)/1024/1024/1024",256ULL*1024*1024/(44*1e-3)/1024/1024/1024,256ULL*1024*1024/(54*1e-3)/1024/1024/1024);
    TGaxis* A1 = new TGaxis(44,gPad->GetUymax(),54,gPad->GetUymax(),"f1",510,"-");
    if(enableDigits)
    {
        A1->SetMaxDigits(2);
    }
    A1->Draw();

}
```

If I set the boolean argument to true, the y axis gets affected.

**Comment by couet** [comment]
I see. I will investigate.

**Comment by couet** [comment]
Actually this functionality is already there but a bit hidden and not really documented. It was implemented to allow `SetMaxDigits` to work on individual `TAxis`. It is done via an extra field in the number of divisions. When the number of divisions is greater than 1000000 as shown in the following example:
```
void test_tgaxis()
{
    TCanvas* c = new TCanvas();
    TH1* h = new TH1F("h","h",10,44,54);
    h->SetBinContent(1,180);
    h->SetStats(kFALSE);
    h->Draw("hist");
    c->Modified();
    c->Update();

    TGaxis* A1 = new TGaxis(44,gPad->GetUymax(),54,gPad->GetUymax(), 0, 180, 2000510 ,"-");
    //--------------------------------------------------------------------^  MaxDigits = 2 for this TGaxis
    A1->Draw();
}
```

**Comment by ferdymercury** [comment]
Thanks for the clarification! I have created a PR proposing to detail this trick in the documentation

**Comment by couet** [comment]
Thanks for the PR. It is ready to be merged.
