### ISSUE TITLE
[RF] Migration from RooAbsCollection and RooLinkedList legacy iterators to range-based loops

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#8777]
**This migration is a great first issue for an enthusiastic open source contributor who wants to get started contributing to ROOT with a well-defined task!**

**This issue has already been addressed partially by many PRs, the only remaining iterator-creating function to look out for and replace is **`RooLinkedList::MakeIterator()`**!**

## Introduction

RooFit needs to be migrated to use range-based loops to iterate over RooArgLists, RooArgSets, and RooLinkedLists. The [deprecated iterator-creating functions](https://github.com/root-project/root/blob/master/roofit/roofitcore/inc/RooAbsCollection.h#L178) `RooAbsCollection::createIterator()`, `RooAbsCollection::iterator()`, and `RooAbsCollection::fwdIterator()` have some overhead both is code verbosity and performance. For the RooLinkedList, the relevant function calls to replace are `RooLinkedList::MakeIterator()`, `RooLinkedList::iterator()`, and `RooLinkedList::fwdIterator()`.

To do the migration, one could remove the deprecated functions from the code and try to recompile ROOT. From the compiler errors, one can see where a migration away from the legacy iterators is needed. Alternatively, one could mark the legacy functions as `[[deprecated]]` and get compiler warnings.

If the iteration involved a type casting of each item, one can also use the `static_range_cast` and `dynamic_range_cast` functions in RooFit to make the code more compact (introduced in https://github.com/root-project/root/pull/8769).

It is not expected that the full migration is done in one pull request, as these legacy iterations appear everywhere in RooFit. One can proceed with occasional PRs, migrating only one or a few RooFit classes at the time.

## Migration examples

Here are some examples on how the migration to range-based loops can look like

1. Basic example:
    ```C++
    // with legacy iterator
    TIterator* iter = comps->createIterator() ;
    while((arg=(RooAbsArg*)iter->Next())) { 
      // do something with arg
    }
   ```

   ```C++
    // with range-based loop
    for(auto const* arg : *comps) { 
      // do something with arg
    }
    ```

2. Example where one can make use of `static_dynamic_cast`
    ```C++
    // with legacy iterator
    RooFIter siter = fullPdfSet.fwdIterator() ;
    RooAbsPdf* pdf ;
    while((pdf=(RooAbsPdf*)siter.next())) {
      // do something with pdf
    }
   ```

   ```C++
    // with range-based loop
    for(auto const* pdf : static_range_cast<RooAbsPdf*>(fullPdfSet)) {
      // do something with pdf
    }
    ```

3. Example where one can make use of `static_dynamic_cast`
    ```C++
    // with legacy iterator
    TIterator* uIter = usedObs->createIterator() ;
    RooAbsArg* obs ;
    while((obs=(RooAbsArg*)uIter->Next())) {
      RooRealVar* rrv = dynamic_cast<RooRealVar*>(obs) ;
      if (rrv) {
        // ... do something with rrv
      }
    }
   ```

   ```C++
    // with range-based loop
    for(auto const* rrv : dynamic_range_cast<RooRealVar*>(*usedObs)) {
      if (rrv) {
        // ... do something with rrv
      }
    }
    ```

**Comment by guitargeek** [comment]
Hi @priyanshu1044! Sorry for the late reply, I was on vacation. Are you still available to work on that issue or did we miss that opportunity? If you confirm, I will assign the issue to you and take care of the label :)

Cheers,
Jonas

**Comment by subham73** [comment]
Hii , i want to contribute . Can u pls assign this problem to me .

**Comment by guitargeek** [comment]
Hi @subham73, thank you so much! If you have any questions, please let me know :+1:

**Comment by subham73** [comment]
Hii @guitargeek I have had issues when I am trying to compile, in vscode it shows `can't find source code`
and so started using visual studios c++ , on compiling or running  its showing 
>------ Build All started: Project: root, Configuration: x64-Debug ------
C:\Users\dell\Desktop\shared project\root\out\build\x64-Debug\ninja : error : 'LZMA/src/LZMA/lib/liblzma.lib', needed by 'bin/Core.dll', missing and no known rule to make it
Build All failed.


Can u help on this or can u suggest something so that I can compile stuff and see my code is running as expected or not?
I'm in windows 11. thank you

**Comment by guitargeek** [comment]
Hi @subham73, sorry for the late answer! In this case, you should build ROOT with the builtin LZMA library. This can be enabled with the `builtin_lzma` cmake option:

https://github.com/root-project/root/blob/master/cmake/modules/RootBuildOptions.cmake#L99

The call to cmake would look like `cmake -Dbuiltin_lzma=ON` then.

If you get further problems with the dependencies, you can try to just enable the build of all dependencies with the `builtin_all` option. By the way, you should consider also building with the `testing` to build the unit tests as well. I can let you know how to run the RooFit unit tests once you managed to build ROOT then. Let me know how it goes :+1:

**Comment by subham73** [comment]
hi @guitargeek , thanks a lot, but the above-mentioned methods didn't work out for me. Also, spend time with Cmake to understand the issue and reinstall everything quite a time, which also didn't work. Had the same issue.

So will try to figure out this for the next few days, and will surely reach out to you after building ROOT.
Just curious how you run your ROOT, I mean in which configuration, will try to build that way instead, or can give it a try that way :).

**Comment by guitargeek** [comment]
Hi @subham73! I use Arch Linux with the same CMake configuration used for the official packages of that Linux distribution:

https://github.com/archlinux/svntogit-community/blob/packages/root/trunk/settings.cmake

What CMake errors do you get exactly? Sorry, I will probably have a hard time to help you with visual studio details, because I haven't used Windows for over a decade! Do you maybe have a computer with Linux at hand?

**Comment by subham73** [comment]
Hii @guitargeek ! 
```
 `system runtime library file does not exist:
2> [CMake]   'MSVC_REDIST_DIR-NOTFOUND/x64/Microsoft.VC142.CRT/msvcp140.dll'`
```
```
system runtime library file does not exist:
2> [CMake]   'MSVC_REDIST_DIR-NOTFOUND/x64/Microsoft.VC142.CRT/vcruntime140.dll'
```
```
system runtime library file does not exist:
2> [CMake]   'MSVC_REDIST_DIR-NOTFOUND/x64/Microsoft.VC142.CRT/concrt140.dll'
```

**Comment by guitargeek** [comment]
Hi @subham73! I really have no idea about how to build ROOT on Windows, sorry.

To me it seems a good idea to come back to this later with the Linux system of your University once your exams are over :)  Thanks a lot!

**Comment by subham73** [comment]
Hello @guitargeek !! sorry for being late but, I am able to build with the `testing `:), can u please guide me on how to run unit tests of RootFit.

**Comment by guitargeek** [comment]
Reopened because the linked PR only partially addressed the issue

**Comment by guitargeek** [comment]
Reopened because the linked PR only partially addressed the issue

**Comment by guitargeek** [comment]
**Note**: this issue should not be picked up anymore as it is already been worked on by @HannaOlvhammar.

**Comment by guitargeek** [comment]
The PR is re-opened because there is still one legacy iterator function to replace: `RooLinkedList::MakeIterator()`.
