### ISSUE TITLE
Branch sync of roottest broken for latest-stable

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#8783]
https://root-forum.cern.ch/t/roottest-and-required-c-standard/46088/5

`cmake -Droottest-On` clones roottest and *is supposed* to check out the branch of the currently configured `root.git`. That fails apparently if `root.git` has `latest-stable` checked out.

**Comment by eguiraud** [comment]
I don't think the problem is `latest-stable`, this also doesn't work:

```
$ git clone --branch v6-24-02 https://github.com/root-project/root.git v624 && cd v624 && mkdir _build && cmake -Droottest=ON -B _build -S . && cd roottest && git status
```

prints 

```
~/R/v/roottest (master=) git status
On branch master
Your branch is up to date with 'origin/master'
```

**Comment by jalopezg-r00t** [comment]
Returning back to this...  I think the expected behavior is to checkout the corresponding tag in `roottest`, right?

**Comment by Axel-Naumann** [comment]
They have the same name. We would probably "just" need to also tag roottest as `latest_stable`, and update the tag whenever we update root.git's `latest_stable`.

**Comment by jalopezg-r00t** [comment]
> They have the same name. We would probably "just" need to also tag roottest as `latest_stable`, and update the tag whenever we update root.git's `latest_stable`.

That is one of the possible solutions.  The other is to add additional code in `CMakeLists.txt` to checkout the corresponding branch of `roottest`, if `latest-stable` has been checked out in the `root` repository, i.e. something similar to
```
$ git for-each-ref --points-at=latest-stable^2
d518697bebf3081a912017fc8f7df220131856b3 tag	refs/tags/v6-24-06
```
And then checkout `v6-24-06` in `roottest`, which is what `latest-stable` points to.

For the sake of a simpler release procedure, I vote for this option given that it should only require 3 additional lines in `CMakeLists.txt`.

**Comment by jalopezg-r00t** [comment]
> I don't think the problem is `latest-stable`, this also doesn't work:
> 
> ```
> $ git clone --branch v6-24-02 https://github.com/root-project/root.git v624 && cd v624 && mkdir _build && cmake -Droottest=ON -B _build -S . && cd roottest && git status
> ```
@eguiraud Given that `v6-24-02` should be on both, `root` and `roottest`, this might be a different issue.  Anyway, I will take a look.

**Comment by jalopezg-r00t** [comment]
> @eguiraud Given that `v6-24-02` should be on both, `root` and `roottest`, this might be a different issue. Anyway, I will take a look.

The problem you described only occurs if a tag is checked out in the `root` repository (i.e., in detached-HEAD).  The corresponding PR will fix both issues.
