### ISSUE TITLE
[GH] Issue and Improvement templates

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8795]
### Explain what you would like to see improved
In the GitHub templates for "Issue" and "Improvement", I think it could be interesting to replace these instructions

```
### Setup
<!--
1. ROOT version
2. Operating system
3. How you obtained ROOT, such as `dnf install` / binary download / you built it yourself.
-->
```

 with:
```
### Setup
'''
Suggested: Paste here the output of root -b -q
'''
```
(Maybe some more metadata had to be added to root -b in order to tag some builds as 'dnf' or 'binary prepackage'.)

It would be interesting to define a special command in the ROOT binary folder, like
`rootissue` or `rootfeature` that opens a web browser with an issue or feature template, with the field "Setup" already prepopulated with the current ROOT version. See below how KiCad does this.

### Additional context
KiCad already has this functionality. When one presses on "Report Bug" in the KiCaD GUI, it opens a webpage pre-filled with the version field, see https://gitlab.com/kicad/code/kicad/-/blob/master/common/tool/common_control.cpp#L50. It just opens a web browser with the following [link](https://gitlab.com/kicad/code/kicad/-/issues/new?issue[description]=%3C%21--%20Before%20Creating%20a%20New%20Issue%3A%0A%2A%20Search%20the%20issue%20tracker%20to%20verify%20the%20issue%20has%20not%20already%20been%20reported.%0A%2A%20Only%20report%20one%20problem%20per%20issue.%20--%3E%0A%0A%23%20Description%0A%3C%21--%20What%20is%20the%20current%20behavior%20and%20what%20is%20the%20expected%20behavior%3F%20--%3E%0A%3C%21--%20Please%20attach%20screenshots%20if%20they%20will%20help%20explain%20the%20problem.%20--%3E%0A%0A%23%20Steps%20to%20reproduce%0A%3C%21--%20Please%20include%20a%20screen%20recording%20if%20it%20will%20help%20explain%20how%20to%20reproduce.%20--%3E%0A%3C%21--%20If%20this%20issue%20is%20specific%20to%20a%20project%2C%20please%20attach%20it.%20--%3E%0A1.%0A2.%0A%23%20KiCad%20Version%0A%0A%60%60%60%0AApplication%3A%20KiCad%20PCB%20Editor%0A%0AVersion%3A%205.99.0-unknown-baf6798695~131~ubuntu18.04.1%2C%20release%20build%0A%0ALibraries%3A%0A%09wxWidgets%203.0.4%0A%0APlatform%3A%20Linux%205.4.0-77-generic%20x86_64%2C%2064%20bit%2C%20Little%20endian%2C%20wxGTK%2C%20mate%2C%20x11%0A%0A%09wxWidgets%3A%203.0.4%20%28wchar_t%2Cwx%20containers%2Ccompatible%20with%202.8%29%20GTK%2B%203.22%0A%09Boost%3A%201.65.1%0A%09OCC%3A%207.5.1%0A%09Curl%3A%207.58.0%0A%09ngspice%3A%2033%0A%09Compiler%3A%20GCC%207.5.0%20with%20C%2B%2B%20ABI%201011%0A%0ABuild%20settings%3A%0A%09KICAD_USE_OCC%3DON%0A%09KICAD_SPICE%3DON%0A%0A%60%60%60), that looks like this:

![image](https://user-images.githubusercontent.com/10653970/128146364-f40a992b-1730-40d8-996a-7d51a262aec7.png)

This homogenizes bug reports and saves time of the dev's asking what their current settings and versions are.

The KiCad gitlab bot also warns the user if it detects that no version info was added to the issue.

And they have a very nice webpage to aid users in reporting issues at the right repository: https://www.kicad.org/help/report-an-issue/

**Comment by eguiraud** [comment]
@Axel-Naumann does the discussion at #8805 imply that this issue can be closed?

**Comment by ferdymercury** [comment]
Side note: my suggestion was to make contribution less of a burocratic pain, not more ;)
For me, it takes more time to write the ROOT version and Operating System by hand like now, rather than copying root -b output, or to just call in the terminal "rootissue" which already prefills all fields and opens the browser.

**Comment by Axel-Naumann** [comment]
Replacing one by the other seems fine to me. I don't want our users to go through additional steps, and I'd like to keep this welcoming (i.e. no all caps "must" etc). I like the idea of having a tool that spits out version, platform, built-by / -machine / -directory which would allow us to guess whether it's Conda, a nightly, a custom build, or whatever.

**Comment by ferdymercury** [comment]
> of having a tool that spits out version, platform, built-by / -machine / -directory which would allow us to guess whether it's Conda, a nightly, a custom build, or whatever.


Another option instead of a "rootissue.exe" would be to create a custom ROOT prompt command,
`".issue"`
that does this part.
(Instead of adding a new executable).
