### ISSUE TITLE
coding conventions - Qtcreator xml config file

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8797]
### Is your feature request related to a problem? Please describe.
When I code contributions for ROOT within QtCreator, I have to manually edit the format to match the one required by ROOT (braces, indents, etc.).

### Describe the solution you'd like
A config file like this one would be perfect, as it would automatically format those things.
https://github.com/drewnoakes/settings/blob/master/qt-creator-code-style.xml

This file could be posted in this webpage below the clang and astyle config files.
https://root.cern/contribute/coding_conventions/

### Describe alternatives you've considered
clang, astyle

### Additional context
https://stackoverflow.com/a/59384396/7471760

**Comment by bellenot** [comment]
So apparently `QtCreator` has a plugin for `clang-format` and so can use the style from the ROOT `.clang-format` file

**Comment by ferdymercury** [comment]
Works great, I didn't know about it, thanks for the hint. The plugin also supports astylerc files. I followed https://www.vikingsoftware.com/using-clang-format-with-qtcreator/

Would it be maybe helpful to add a short sentence https://root.cern/contribute/coding_conventions/ mentioning this possibility?

**Comment by bellenot** [comment]
Here is the PR: https://github.com/root-project/web/pull/630

**Comment by bellenot** [comment]
Done by [commit #f68d91056](https://github.com/root-project/web/commit/f68d91056)
