### ISSUE TITLE
`root` command ignores unknown options - it should complain instead 

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#8850]
- [X] Checked for duplicates

### Describe the bug

This runs fine:
```
$ root --foobarbaz
```
Virtually all unix command line tools error out if an invalid option is passed. It's surprising that `root` does not and can lead to problems:

```
$ root --batch
```
does _not_ start `root` in batch mode, because there is no long spelling for `-b`.

### Expected behavior

`root --nonexistingoption` should error out.

**Comment by ferdymercury** [comment]
Maybe this could be cleanly handled with the CLI11 header-only library (as a git submodule):
https://github.com/CLIUtils/CLI11

**Comment by eguiraud** [comment]
Changing the way we do argument parsing is a much larger chunk of work but we welcome contributions in that direction, see e.g. the discussion at https://root-forum.cern.ch/t/command-line-argument-parsing/35783

**Comment by DrJanHartmann** [comment]
Actually, I found the old behaviour of root just ignoring unknown options extremely useful.
It allowed users to simply add their own command line options and parsing them in `.rootlogon.C`
A simple example I have been using for 15+ years:
```
int argc = gApplication->Argc();
	char** argv = gApplication->Argv();
	for (int i=1; i<argc; i++) {
		TString arg = argv[i];
		if (arg == "--browser") {
		}
	}
```

**Comment by eguiraud** [comment]
(as a side note, for the specific usecase of starting a TBrowser from the command line there is the dedicated `rootbrowse` command)

**Comment by DrJanHartmann** [comment]
Yes, I know about rootbrowse. The TBrowser was just the simplest example I have. It's not the only custom command line option I'm using, I also use this to manipulate gStyle, load .so files, etc. 

Of course I am fully aware that my complaint feels a lot like https://xkcd.com/1172/...
