### ISSUE TITLE
Exception in TGeoMixture::ComputeDerivedQuantities

### ISSUE THREAD

**Issue by andresailer** [root-project/root#8892]
Since this change https://github.com/root-project/root/pull/8556 in the root master
We see some failures in DD4hep tests against the LCG Dev3 installation, more details in https://github.com/AIDASoft/DD4hep/pull/857#issuecomment-904434545

Our tests are passing again if patching out the `!fElements &&` from this line

https://github.com/root-project/root/blob/5d536b29d7ce437aad79ff046788735a33fb1dbe/geom/geom/src/TGeoMaterial.cxx#L803

Ping @agheata

**Comment by MarkusFrankATcernch** [comment]
Please see https://github.com/root-project/root/pull/8900

**Comment by agheata** [comment]
Fixed by #8900
