### ISSUE TITLE
Weird messages from TInterpreter::AutoParse

### ISSUE THREAD

**Issue by andriish** [root-project/root#8904]
### Describe the bug
I have root installed from EPEL8-testing, version 6.24.02.
I also have installed a package called  perl-Unicode-Map, which provides a file /usr/bin/map.
When TInterpreter::AutoParse  finds 
```
#include    <map>  
```
in my headers it tries to parse /usr/bin/map.

```
In file included from /usr/include/zevis/ZStyleScheme.h:12:
/usr/bin/map:1:2: error: invalid preprocessing directive
#!/usr/bin/perl -w
 ^
/usr/bin/map:2:2: error: invalid preprocessing directive
#$Id: map,v 1.20 1998/02/11 23:58:27 schwartz Exp $
```

### Expected behavior
/usr/bin/map is not parsed.

### To Reproduce
Eh,  not sure if I can provide a short reproducer immediately.

### Setup
1. ROOT 6.24.02 from EPEL8 testing
2. CentSO8 Stream
3. `dnf install` / binary download / you built it yourself.

Best regards,

Andrii

**Comment by Axel-Naumann** [comment]
Are you running from `/usr/bin/`, i.e. is that your current working directory?

**Comment by andriish** [comment]
Hi @Axel-Naumann ,

no, I was running just from home directory.

But, let me have a look if 1) this behaviour will be seen after the recent updates of root in EPEL
2)if  I'm able to provide a simple reproducer.

Best regards,

Andrii

**Comment by andriish** [comment]
OK,

now I see I had /usr/bin appended to the ROOT_INCLUDE_PATH in the script that called the executable.
Removing /usr/bin from resolves the problem. Sorry for not reporting it earlier.
In theory, one could expect that build-in paths should take precedence over  ROOT_INCLUDE_PATH, so I'm not sure if this is 100% false alarm,  but "my problem" is resolved, so I would not object to closing this issue.


Best regards,

Andrii

**Comment by Axel-Naumann** [comment]
Thanks for your confirmation. I believe we're just following the precedence provided by clang (the compiler library cling is based upon), so I'll close this.
