### ISSUE TITLE
root/io/references tests fail with ASAN enabled

### ISSUE THREAD

**Issue by SpectreVert** [root-project/root#8909]
According to the console logs the tests did not execute successfully, probably because of a badly setup dependency on libEvent.

### How it could be improved
Tests should be remade using CMake with a proper Event generation library and then tested for correctness against libasan.

**Comment by ferdymercury** [comment]
@linev this is the original issue where it was hypothesized that the asan issue came from a missing dependency on libEvent.

> Tests should be remade using CMake with a proper Event generation library and then tested for correctness against libasan.

**Comment by linev** [comment]
Not sure if missing dependency for libEvent was a reason for original failure.
After converting to cmake I see no any external dependency in  `io/references` tests

**Comment by ferdymercury** [comment]
> Not sure if missing dependency for libEvent was a reason for original failure. After converting to cmake I see no any external dependency in `io/references` tests

Thanks!
To confirm that the failure is gone, could you rerun that test using:

```
set_target_properties(testname PROPERTIES COMPILE_FLAGS "-fsanitize=undefined -fsanitize=address")
target_link_options(testname BEFORE PUBLIC -fsanitize=undefined PUBLIC -fsanitize=address)
```

and then running with  ASAN_OPTIONS=halt_on_error=0 before exename.
