### ISSUE TITLE
root/io/perf tests fail with ASAN enabled

### ISSUE THREAD

**Issue by SpectreVert** [root-project/root#8910]
According to the console logs, the test crashed on execute due to bad linkage to asan functions. 

Also, perf contains a lot of old tests than seemingly never got run. There is a discussion about this ongoing at https://github.com/root-project/roottest/pull/732 ; any idea @bellenot @pcanal ?

**Comment by dpiparo** [comment]
Consolidated into https://github.com/root-project/root/issues/14682
