### ISSUE TITLE
[RF] Implement option to not apply bin-width correction to `RooHistPdf` when plotting

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#8935]
As discussed in https://root-forum.cern.ch/t/binned-likelihood-fit-with-variable-bin-sizes, it is not trivial in RooFit to make a plot where a data histogram and a `RooHistPdf` with non-uniform binning are compared: the data is given in event counts per bin, and the RooHistPdf gives the expected counts *per bin volume*.

A way to easily plot a RooHistPdf without bin-width correction should be implemented for such data comparisons. Possibly with a new RooFit command argument that could be named `BinVolumeCorrection`.

**Comment by bmjoshi** [comment]
Hi @guitargeek , I didn't get notification regarding your reply to the issue which I posted on the ROOT forum. Sorry about the late reply. The suggested work around works fine for me. Thank you very much for your helpful reply!

**Comment by guitargeek** [comment]
Okay! If the solution suggested on the forum worked for you, I will close this issue. There is no need to complicate RooFit even more by adding new options if there is no immediate need.
