### ISSUE TITLE
-DCMAKE_CXX_STANDARD=20 unsupported for branch `latest-stable`

### ISSUE THREAD

**Issue by bernd1995** [root-project/root#8939]
Although the [docs for building ROOT from source](https://root.cern/install/build_from_source/#setting-the-c-standard) suggest that the `C++20` standard should be supported, the software won't build with this setting.

The reason is that the file `cmake/modules/CheckCompiler.cmake` hasn't been updated on the `latest-stable` branch within a year. Only for the `master`-branch `C++20` support has been added in #8399.

So either the docs at https://github.com/root-project/web/blob/main/install/build_from_source.md#setting-the-c-standard should be fixed or the support for C++20 should be merged into `latest-stable` (which I personally would prefer, though I don't know if this would break something).

**Comment by Axel-Naumann** [comment]
That's more of a documentation issue. We don't actually support C++20 yet (clang too old). I hope https://github.com/root-project/web/pull/642 addresses this?

**Comment by bernd1995** [comment]
Okay that's fair enough.
Wasn't sure wether to put it to the docs or here.
