### ISSUE TITLE
[doc] Building Doxygen documentation pollutes source directory

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8947]
### Explain what you would like to see improved
To build the documentation using doxygen, one has to enter the (git) source directory and call Make. This creates some files in the source directory that are not part of the git tree.

### Optional: share how it could be improved
I can think of two alternative options:
- The documentation can be created in the build directory rather than in the source directory
- A .gitignore file is created in documentation/ so that the are ignored when calling git status

### To Reproduce
Build docu following https://root.cern/for_developers/doxygen/

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.25/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on May 17 2021, 10:49:42                 |
  | From heads/master@v6-25-01-861-g5ea261143f                       |
  | With                                                             |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

**Comment by ferdymercury** [comment]
Side note: calling make clean does not clean the directory in case the build failed. I get:

rm -r rootdoc filter htmlfooter.html dataset* ../../bindings/pyroot/pythonizations/python/ROOT/pythonization/*.pyzdoc
rm: cannot remove 'dataset*': No such file or directory
Makefile:56: recipe for target 'clean' failed
make: *** [clean] Error 1

**Comment by couet** [comment]
Yes that's known. We were lazy to fix that but we should.

**Comment by ferdymercury** [comment]
Here a good example on how ALICE's experiment generates the documentation within the build directory, using CMake:
https://github.com/AliceO2Group/Monitoring/blob/dev/doc/CMakeLists.txt#L22
