### ISSUE TITLE
JavaScript complains when displaying MultiGraph

### ISSUE THREAD

**Issue by SergueiEK** [root-project/root#8964]
Hello.

I have a multigraph displayed in a Web browser using ROOT JS and I have noticed many complains from the JS engine when I'm hovering mouse pointer above the multigraph object.  I think the errors come from the function that is supposed to display tooltips because they do not appear as this happens for a histogram object. Here is the stack trace of such an error:

`JSRoot.more.js:1502 Uncaught TypeError: Cannot read properties of undefined (reading 'second_x')
    at SVGGElement.<anonymous> (JSRoot.more.js:1502)
    at Pn.each (d3.min.js:2)
    at TGraphPainter.extractTooltip (JSRoot.more.js:1484)
    at TGraphPainter.processTooltipEvent (JSRoot.more.js:1576)
    at JSRoot.gpad.js:2960
    at Array.forEach (<anonymous>)
    at TCanvasPainter.TPadPainter.processPadTooltipEvent (JSRoot.gpad.js:2959)
    at TFramePainter.processFrameTooltipEvent (JSRoot.interactive.js:56)
    at SVGSVGElement.<anonymous> (d3.min.js:2)`

Cheers,

**Comment by linev** [comment]
Can you provide example with `TMultiGraph` which reproduces the problem.

Existing demos works fine for me:
https://root.cern/js/latest/examples.htm#tmultigraph_all

**Comment by linev** [comment]
I just need ROOT file with such TMultiGraph object.
Just for info - to put file here, just compress it with zip

**Comment by SergueiEK** [comment]
Indeed I also don't see a problem with the demo files. Please fin in the attachment a file that reproduces the problem. The multigraph object is called 'RootController;1/my transitions'
[test_case.root.zip](https://github.com/root-project/root/files/7120282/test_case.root.zip)

**Comment by linev** [comment]
I fixed problem in `master` branch - see  https://github.com/root-project/jsroot/commit/090bc0e421b895811f9c5c715681ef32484dd907
