### ISSUE TITLE
RooFit Python Tutorial Errors 

### ISSUE THREAD

**Issue by uzzielperez** [root-project/root#8973]
Hi! I have been trying to run several rooFit tutorials in Swan and also locally with ROOT v6.22.08 in MacOS. I am getting errors with some functions. There are multiple, but on example is `gauss.plotOn(xframe, LineColor="r")` and it doesn't seem to accept the `LineColor` argument. I get:

```
TypeError: RooAbsPdf::plotOn got an unexpected keyword argument 'LineColor'
```

I tried copying the code and running them in a cmslpc cluster and in my mac but I get the same error like in Swan.
I haven't seen any solution so far to this problem. Are there any updated sets of tutorials?

One can quickly reproduce the problem/s, by running some Swan notebooks. For example: https://root.cern.ch/doc/master/rf101__basics_8py.html

**Comment by etejedor** [comment]
The keyword arg functionality that you are trying to use has only been added recently (it's not in 6.22.08). @guitargeek can perhaps elaborate.

If you run the tutorial you mentioned in SWAN and you select as software stack "Bleeding Edge" (which has ROOT master), you will see that it runs fine.

**Comment by uzzielperez** [comment]
Thanks @etejedor. Indeed, it works for the "Bleeding Edge" (root v6.25). I tried to update my root version in my desktop but I see I could only download up to 6.24.06. Is there a way for me to run the bleeding edge version locally or in a cluster? (Apart from using SWAN?) 

I also see that the tutorial has been taken down. Perhaps someone is working on it?

**Comment by etejedor** [comment]
The feature will be released with 6.26, if you want to use it now in your local computer you can install ROOT master:

https://root.cern/install/nightlies/

The tutorial should be back now.

**Comment by guitargeek** [comment]
Thanks to @etejedor for explaining what's going on here! We can close this issue then.

**Comment by uzzielperez** [comment]
Thanks, a lot!
