### ISSUE TITLE
Output in Notebooks only shows after code block finishes

### ISSUE THREAD

**Issue by philippe554** [root-project/root#8989]
### Describe the bug
In a local jupyter notebook and SWAN, the output of a code block only shows after the block finishes execution.
This makes progress bars only display after completion, rendering them useless.

### Expected behavior
An std::flush should update the output of a code block of a notebook, even if the code block is still running.

### To Reproduce
For example:
```
std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();

for(long i = 0; i < 1000000000; i++)
{
    if(i % 100000000 == 0)
    {
        std::cout << i << "\n" << std::flush;
    }
}

std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
std::cout << "Time difference = " << std::chrono::duration_cast<std::chrono::milliseconds>(end - begin).count() << "ms\n";
```
This takes 7 seconds on my machine, thus long enough to see the numbers pop up sequentially in a ROOT console.
However, in a local notebook or on SWAN, all of the output is only shown after 7 seconds.

### Setup
ROOT version: ROOT 6.24/06
Operating system: Ubuntu on windows (Ubuntu 20.04.1 LTS)
How you obtained ROOT: Downloaded today via Conda
Jupyter Notebook 6.4.3 (ROOT kernel)

### Additional context
On Swan, progress bars work on SWAN software stack 97a, but not on 99 and 100.

**Comment by etejedor** [comment]
Hello @philippe554 ,
Indeed, we changed this behaviour a few releases ago, IIRC the reason was that the progressive output implementation had some problems, so we opted for capturing the output and releasing it only at the end, even at the expense of not covering cases such a progress bar.

**Comment by philippe554** [comment]
Thank you @etejedor for this update.
