### ISSUE TITLE
TMultiGraph wrong scale with logarithmic axes : regession introduced in 6.22

### ISSUE THREAD

**Issue by gregoireg1lles** [root-project/root#9011]
Hi, 

A regression was introduced in TMutiGraph with a log scale
I found a commit that seems to be linked to my problem [https://github.com/osschar/root/commit/d087f000322c7958f02c8e9ddce2a302502c8604](https://github.com/osschar/root/commit/d087f000322c7958f02c8e9ddce2a302502c8604)

my OS is  debian10 x86_64 with gcc8.3

here is sample script to reproduce the bug :

```
void multigraph()
{
   auto c1 = new TCanvas("c1","multigraph",700,500);
   c1->SetGrid();
   c1->SetLogx();
   c1->SetLogy();
   auto *mg = new TMultiGraph();
   std::vector<double> x1;
   std::vector<double> sig1;
   std::vector<double> sig2;
   for (double E=1e-4;E<2e7;E*=1.1)
    {
		x1.push_back(E);
		sig1.push_back(10*pow(E,-0.1));
		sig2.push_back(15*pow(E,-0.15));
		}
   auto g1 = new TGraph(x1.size(), x1.data(), sig1.data());
   mg->Add(g1);
   auto g2 = new TGraph(x1.size(), x1.data(), sig2.data());
   mg->Add(g2);
   mg->SetTitle("; E (eV);#sigma (b)");
   mg->GetXaxis()->CenterTitle(true);
   mg->GetYaxis()->CenterTitle(true);
   mg->Draw("AL");
   c1->SaveAs("multigraph.pdf");
}
```

It works fine on versions 6.14.08, 6.18.04 and 6.20.06
TMultiGraph scale is wrong with versions 6.22.08, 6.24.06.
There is also an error message at the console (negative value for log scale)

```
Processing multigraph.C...
Error in <THistPainter::PaintInit>: log scale requested with a negative argument (-1.720339)
Info in <TCanvas::Print>: pdf file multigraph.pdf has been created
```

I remove the patch [https://github.com/osschar/root/commit/d087f000322c7958f02c8e9ddce2a302502c8604](https://github.com/osschar/root/commit/d087f000322c7958f02c8e9ddce2a302502c8604) on version 6.24.06 and it works again

thanks in advance

**Comment by couet** [comment]
@osschar can you have a look ?

**Comment by osschar** [comment]
Hhhm, I don't know how you got to the merge commit in my repo :)

Here's the commit from root itself: https://github.com/root-project/root/commit/aef730659bebc6ec49bb6f62822b91781494daa6

PR: #5578

**Comment by couet** [comment]
Removing this patch will produce a problem with this macro:
```
{
   auto c1 = new TCanvas("c1","multigraph",700,500);
   c1->SetGrid();
   auto *mg = new TMultiGraph();
   std::vector<double> x1;
   std::vector<double> sig1;
   std::vector<double> sig2;
   for (double E=1e-4;E<2e7;E*=1.1) {
      x1.push_back(E);
      sig1.push_back(10*pow(E,-0.1));
      sig2.push_back(15*pow(E,-0.15));
   }
   auto g1 = new TGraph(x1.size(), x1.data(), sig1.data());
   mg->Add(g1);
   auto g2 = new TGraph(x1.size(), x1.data(), sig2.data());
   mg->Add(g2);
   mg->SetTitle("; E (eV);#sigma (b)");
   // comment or uncomment the following line to get diffrent plot
//   mg->GetXaxis()->CenterTitle(true);
   mg->Draw("AL");
}
```
Without this patch you get a different X range depending if you center the X title or not. I guess we should keep the patch and understand why in log scale it crashes (it should be protected).

**Comment by couet** [comment]
Actually it worked for you because you centred the X title. In the previous macro, remove the X title centring and go to log scale in Y and you will get the problem you discovered. So that's not a regression. The bug fix simply revealed a problem (?) which was hidden by the bug generated by the X title centring. To make it short, with a ROOT version without the patch, try:
```
{
   auto c1 = new TCanvas("c1","multigraph",700,500);
   c1->SetGrid();
   auto *mg = new TMultiGraph();
   std::vector<double> x1;
   std::vector<double> sig1;
   std::vector<double> sig2;
   for (double E=1e-4;E<2e7;E*=1.1) {
      x1.push_back(E);
      sig1.push_back(10*pow(E,-0.1));
      sig2.push_back(15*pow(E,-0.15));
   }
   auto g1 = new TGraph(x1.size(), x1.data(), sig1.data());
   mg->Add(g1);
   auto g2 = new TGraph(x1.size(), x1.data(), sig2.data());
   mg->Add(g2);
   mg->SetTitle("; E (eV);#sigma (b)");
   mg->Draw("AL");
   gPad->Update();
   c1->SetLogy();
}
```

**Comment by couet** [comment]
The problem has indeed nothing to do with TMultiGraph. It can be described as follow: "Turning Y log scale on a empty histogram with the minimum <=0 produce an error message". And it can be reproduce by the simple following code:
```
auto c = new TCanvas();
c->DrawFrame(-1,-1,1,1);
c->SetLogy();
```

**Comment by couet** [comment]
This PR https://github.com/root-project/root/pull/9229 fixes this issu. Thanks to have seen it.
