### ISSUE TITLE
glibc 2.34 has dropped `__malloc_hook` and `__free_hook` from the API

### ISSUE THREAD

**Issue by badshah400** [root-project/root#9031]
From the release notes of `glibc` 2.34 [[1]]:

> The deprecated memory allocation hooks __malloc_hook, __realloc_hook,
  __memalign_hook and __free_hook are now removed from the API.  Compatibility
  symbols are present to support legacy programs but new applications can no
  longer link to these symbols.  These hooks no longer have any effect on glibc
  functionality.  The malloc debugging DSO libc_malloc_debug.so currently
  supports hooks and can be preloaded to get this functionality back for older
  programs.  However this is a transitional measure and may be removed in a
  future release of the GNU C Library.  Users may port away from these hooks by
  writing and preloading their own malloc interposition library.

As a consequence, building root 6.24/06 against glibc 2.34 (for example on openSUSE Tumbleweed which already has the updated glibc) fails with the following errors:

~~~
[ 2135s] /home/abuild/rpmbuild/BUILD/root-6.24.06/misc/memstat/src/TMemStatHook.cxx: In static member function 'static void* (* TMemStatHook::GetMallocHook())(size_t, const void*)':
[ 2135s] /home/abuild/rpmbuild/BUILD/root-6.24.06/misc/memstat/src/TMemStatHook.cxx:51:11: error: '__malloc_hook' was not declared in this scope
[ 2135s]    51 |    return __malloc_hook;
[ 2135s]       |           ^~~~~~~~~~~~~
[ 2135s] /home/abuild/rpmbuild/BUILD/root-6.24.06/misc/memstat/src/TMemStatHook.cxx: In static member function 'static void (* TMemStatHook::GetFreeHook())(void*, const void*)':
[ 2135s] /home/abuild/rpmbuild/BUILD/root-6.24.06/misc/memstat/src/TMemStatHook.cxx:64:11: error: '__free_hook' was not declared in this scope
[ 2135s]    64 |    return __free_hook;
[ 2135s]       |           ^~~~~~~~~~~
[ 2135s] /home/abuild/rpmbuild/BUILD/root-6.24.06/misc/memstat/src/TMemStatHook.cxx: In static member function 'static void TMemStatHook::SetMallocHook(TMemStatHook::MallocHookFunc_t)':
[ 2135s] /home/abuild/rpmbuild/BUILD/root-6.24.06/misc/memstat/src/TMemStatHook.cxx:77:4: error: '__malloc_hook' was not declared in this scope
[ 2135s]    77 |    __malloc_hook = p;
[ 2135s]       |    ^~~~~~~~~~~~~
[ 2135s] /home/abuild/rpmbuild/BUILD/root-6.24.06/misc/memstat/src/TMemStatHook.cxx: In static member function 'static void TMemStatHook::SetFreeHook(TMemStatHook::FreeHookFunc_t)':
[ 2135s] /home/abuild/rpmbuild/BUILD/root-6.24.06/misc/memstat/src/TMemStatHook.cxx:88:4: error: '__free_hook' was not declared in this scope
[ 2135s]    88 |    __free_hook = p;
[ 2135s]       |    ^~~~~~~~~~~
~~~

Any suggestion to work around this would be highly appreciated. Thank you.

(1) https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html

[1]: https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html

**Comment by eguiraud** [comment]
Hi, I think you can build with `-Dmemstat=OFF`. Those classes have been completely removed in ROOT master.

**Comment by badshah400** [comment]
Thanks a lot. We had it turned on explicitly; turning it off fixed the compilation issue.
