### ISSUE TITLE
Trying to build root with nvhpc / nvc++

### ISSUE THREAD

**Issue by cgleggett** [root-project/root#9036]
I'm trying to build root (v6.24.06) with nvc++ from NVIDIA's nvhpc project (ver 21.9), as I get runtime segfaults when I build a project with nvc++ and link it against root built with gcc 9.3.0. However, building root fails during cmake (3.21.3) with
```
CMake Warning at cmake/modules/CheckCompiler.cmake:12 (message):
  Unsupported compiler: NVHPC.
Call Stack (most recent call first):
  CMakeLists.txt:130 (include)


nvc++-Error-Unknown switch: -
CMake Error at cmake/modules/CheckCompiler.cmake:129 (if):
  if given arguments:

    "STRGREATER" "201703L"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:130 (include)
```

so it looks like nvc++ doesn't know about the `__cplusplus` macro. If I hack around this, cmake finishes, but then the compilation dies with 
```
[ 27%] Building CXX object interpreter/llvm/src/lib/Support/CMakeFiles/LLVMSupport.dir/GraphWriter.cpp.o
"/bld4/atlas/root/src_6.24/interpreter/llvm/src/lib/Support/ErrorHandling.cpp", line 116: error: the global scope has no "write"
      ssize_t written = ::write(2, MessageStr.data(), MessageStr.size());
                          ^
```
and
```
NVC++-F-0000-Internal compiler error. get_call_sptr(): indirect call not via LDA/ACON     154  (/bld4/atlas/root/src_6.24/interpreter/llvm/src/lib/DebugInfo/DWARF/DWARFContext.cpp: 193)
NVC++/x86-64 Linux 21.9-0: compilation aborted
make[2]: *** [interpreter/llvm/src/lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/DWARFContext.cpp.o] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 52%] Built target obj.clang-tblgen
make[1]: *** [interpreter/llvm/src/lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/all] Error 2
CMake Error at /bld4/atlas/root/bld.v6-24-06_nvhpc_c17/TBB-prefix/src/TBB-stamp/TBB-build-Release.cmake:49 (message):
  Command failed: 2

   'make' 'cpp0x=1' 'CXXFLAGS= -mno-rtm' 'CPLUS=/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/compilers/bin/nvc++' 'CONLY=/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/compilers/bin/nvc' 'LDFLAGS='
```

Has anyone tried/succeeded building root with nvc++?

FWIW, nvc++ was configured with gcc 9.3.0.

**Comment by vgvassilev** [comment]
Can nvc++ build llvm?

**Comment by Axel-Naumann** [comment]
We have no experience with nvc++. Is that just an experiment or is there something we can help with? What's the motivation for using nvc++?

**Comment by cgleggett** [comment]
I have not yet tried building llvm. Will try later this week.

nvc++ has an implementation for std::par which allows seamless execution of both CPUs and NVIDIA GPUs (depending on a compile time flag). This could be a huge win for GPU portability (once other manufactures create the AMD/Intel backends), and allows much simpler user access to GPUs without having to learn CUDA (or hip, dpc++, etc).

I was trying to compile some parts of a project with gcc and the bits that use std::par with nvc++, but immediately got some runtime segfaults at startup, so tried to compile the whole thing (including ROOT) with nvc++.

**Comment by Axel-Naumann** [comment]
OK, then there's not much we can do here. Please reopen if you disagree :-)

**Comment by bernhardmgruber** [comment]
@Axel-Naumann, since I just revisited compiling root with nvc++, the issue still persists. With a couple of fixes (PR soon), `clang-tblgen` crashes when building ROOT's LLVM. The same crash happens when building upstream LLVM 17.0.6. So the blocker may be a bug in nvc++'s code generation or a bug in `clang-tblgen` that only manifests with nvc++.

**Comment by bernhardmgruber** [comment]
The crash does not happen, when we build LLVM in Debug (`-DLLVM_BUILD_TYPE=Debug -DCMAKE_BUILD_TYPE=Debug`). However, then `rootcling_stage1` will crash later with:
```
<FlagClass Prefixes:["/", "-"] Name:"/?" Group:<GroupClass Name:"<clang-cl options>">
 Alias:<FlagClass Prefixes:["-", "--"] Name:"-help">
>
<JoinedClass Prefixes:["-"] Name:"-A-" Group:<GroupClass Name:"<gfortran group>">
>
Options are not in order!
UNREACHABLE executed at /home/bgruber/dev/root/interpreter/llvm-project/llvm/lib/Option/OptTable.cpp:134!
```
