### ISSUE TITLE
How to read .root file in javascript?

### ISSUE THREAD

**Issue by iwangyuchun** [root-project/root#9055]
I want to draw some things using this Threejs, and the detailed information of the things is saved in a .root file. So I need to use JavaScript to read the data saved in the .root file, but the file is saved in binary format. So I can’t parse the content of the file, so I want to know if there is any way to parse the file using JavaScript

**Comment by Axel-Naumann** [comment]
That's not an issue, I don't see what you are reporting as broken in ROOT here. Could you instead post at https://root-forum.cern.ch? That way we keep bug fixes and discussions / "how do I" questions nicely separated. Much appreciated!
