### ISSUE TITLE
MacOS: `./root` cannot find `root.exe`

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#9062]
### Describe the bug

```
. .../bin/thisroot.sh
cd $ROOTSYS
./root
./root: can't start ROOT -- check that .../bin/bin/root.exe exists!
```
(note the double "bin")

As reported at https://root-forum.cern.ch/t/macos-11-5-cant-execute-root-through-terminal/47054

**Comment by dpiparo** [comment]
I (un?)fortunately cannot reproduce any more. Please feel free to re-open if this is still an issue.
