### ISSUE TITLE
[DF] Beauty fixes to Display 

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#9116]
Current output:

```
root [5] ROOT::RDataFrame(10).Define("x", "rdfentry_").Define("y", "rdfentry_*2").Display()->Print()
x | y |
0 | 0 |
1 | 2 |
2 | 4 |
3 | 6 |
4 | 8 |
```

Desired output is more like (suggestions welcome):

```
entry | x | y |
---------------
  0   | 0 | 0 |
---------------
  1   | 1 | 2 |
---------------
  2   | 2 | 4 |
---------------
  3   | 3 | 6 |
---------------
  4   | 4 | 8 |
---------------
```

**Comment by ikabadzhov** [comment]
Okay, having (`---`) between the lines looks good.

Now for the left-most column, naively I can simply count rows. Alternatively, I can store the length of the longest collection, say 3. And then my left column would contain [0,1,2,0,1,2,0,1,2,0...]. Which alternative would be more useful in your opinion?

**Comment by ikabadzhov** [comment]
Makes sense, my only concern now is `RDisplay::Print()` displays a "shortened" version of `fTable`, but `fTable` seems to have no clue of the variable `numEntries` in the `RDataFrame`.

I will try to get `numEntries` to be visible for `Print()`.

**Comment by vepadulano** [comment]
+1 if we make it standard markdown :smile: 

actual characters:
```
| entry | x | vec |
|-------|---|-----|
| 0     | 0 | 1   |
|       |   | 2   |
|       |   | 3   |
| 1     | 1 | 1   |
|       |   | 2   |
```

automatically converted to markdown (e.g. here in Github)

| entry | x | vec |
|-------|---|-----|
| 0     | 0 | 1   |
|       |   | 2   |
|       |   | 3   |
| 1     | 1 | 1   |
|       |   | 2   |
