### ISSUE TITLE
[tree] TTree/TChain silently return bogus data if friend is shorter than main tree

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#9137]
Reproducer at the prompt:

```cpp
root [0] ROOT::RDataFrame(10).Define("x", "42").Snapshot("main", "main.root");
root [1] ROOT::RDataFrame(2).Define("y", "rdfentry_").Snapshot("friend", "friend.root");
root [2] TChain ch("main");
root [3] ch.Add("main.root");
root [4] ch.AddFriend("friend", "friend.root")
(TFriendElement *) 0x561753db16a0
root [5] ROOT::RDataFrame(ch).Display({"x", "y"})->Print()
x  | y |
42 | 0 |
42 | 1 |
42 | 1 |
42 | 1 |
42 | 1 |
```

Analogous issue for _indexed_ friends: https://github.com/root-project/root/issues/7713

**Comment by ikabadzhov** [comment]
I see that this is a bug leading unwanted behaviour for TTree itself.

However, I *think* we should be able to apply a fix from the RDF side.
* The TTreeProcessorMT, and hence for RDF with EnableImplicitMT solution is very clear: in fact when we have friends, we will be creating the clusters globally, and hence we will be calling `GetFriendEntries` defined in TTreeProcessorMT.cxx. We can error out whenever there is a friend with less entries than the main chain. Clearly, the check would not require opening extra files. Additional benefit ==> this is checje
* For single threaded cases, it is not so obvious, but there are 2 steps that could be done:
* * Teach the RLoopManager to always understand the fFriendInfo (which was introduced by the RDatasetSpec) from InteralTreeUtils.
* * Once that is done, GetEntries(friend_chain_name) after the event loop ==> user pays the cost of (maybe erroring for) short friends in the end.

**Comment by hageboeck** [comment]
This was discussed again in the [PPP](https://indico.cern.ch/event/1213092/).
It's important that misaligned friend can be detected.

As a minimum, I would propose:
- Raise an error if the main tree/chain arrives at a certain index number, but the friend collection is smaller.
- If the main tree/chain is at the end, but the friend still has values, emit an informative warning.

Ping @pcanal @eguiraud

**Comment by vepadulano** [comment]
I proposed a fix in the linked PR, it implements the two scenarios as suggested by @hageboeck
