### ISSUE TITLE
Number of divisions of ratio plot

### ISSUE THREAD

**Issue by casaburf** [root-project/root#9172]
Hello, I wanted to set the number of divisions of a ratio plot, but it looks like that it isn't possible.
More details here https://root-forum.cern.ch/t/y-axis-resdual-plot/47364
Thank you

**Comment by belmakier** [comment]
This is also the case for the upper y axis, and x axes. 

It seems to be related to the distinction between 
a) fLowYaxis, fUpYaxis members, and 
b) the axes returned by GetLowerRefYaxis(), GetUpperRefYaxis() functions. 

The number of division in the drawn axes are taken from the former which can be accessed by GetLowYaxis() and GetUpYaxis() functions, i.e.

`rp1->GetLowYaxis()->SetNdivisions(2)`

There is nothing at the moment to sync the number of divisions for the two sets of axes (a and b), though I suppose this is possible?

**Comment by couet** [comment]
Yes this can be done.
