### ISSUE TITLE
TEfficiency constructors not appended to current directory

### ISSUE THREAD

**Issue by DLBacher** [root-project/root#9189]
The TEfficiency constructors for fixed or variable bin size are not appended to the current directory. The description of TEfficiency mentions that this should only happen for the constructor using two histograms (passed and total).

The following code does not save the TEfficiency object to the file in version 6.24
```
TFile* file = new TFile("test.root", "RECREATE");
TEfficiency* eff = new TEfficiency("eff", "eff", 1, 0, 1);
eff->Fill(true, 0);
file->Write();
```
Executing in version 6.18 (latest I have installed other than 6.24) does produce the expected behaviour. After adding `eff->Write();` the TEfficiency will also be written in v6.24.

I think the problem is the use of
`TDirectory::TContext ctx(nullptr);`
in TEfficiency.cxx (e. g. line 733), which was, as far as I see, implemented in version 6.24. I think in the scope after TContext the current directory is `nullptr` which is also passed to `Build(name, title);` as well.

### Setup:
ROOT v6.24 built from source
OS: Ubuntu 20.04

**Comment by pcanal** [comment]
This behavior is intentional and documented at https://root.cern.ch/doc/master/classTEfficiency.html, see example 1 and 2 for example.

**Comment by DLBacher** [comment]
This behavior is only intentional for the constructor `TEfficiency(const TH1& passed,const TH1& total)` with two, already filled histograms, as documented in the section you mentioned. All other constructors should be appended to the current directory as described a few sentences above in the same section. 

> You can then use one of the constructors for fixed or variable bin size and your desired dimension. These constructors append the created TEfficiency object to the current directory. So it will be written automatically to a file during the next TFile::Write command.

**Comment by pcanal** [comment]
@lmoneta Could confirm/inform whether the doc or the code (or neither) are matching the intent?

**Comment by lmoneta** [comment]
It is true that in the past versions TEfficiency was added automatically to gDIrectory. 
Although I am not keen on this, I think it would be better to maintain the past behavior.
The commit causing this was   https://github.com/root-project/root/commit/ab9b80a651d458f5cf64d8d9aa5708495c00da4e
which was done to fix some thread issue and to avoid using the global `TH1::AddDirectoryStatus`.

**Comment by lmoneta** [comment]
I will commit a simple fix for this
