### ISSUE TITLE
[Feature][DF] `Snapshot()` to a `TDirectory`

### ISSUE THREAD

**Issue by ShamrockLee** [root-project/root#9225]
### Is your feature request related to a problem? Please describe.
When taking a snapshot (generating a `TTree`) of an `RInterface` with RDataFrame, I need to close the current file, write to it, and open it up again.

### Describe the solution you'd like
Aside from the file name, I also hope to be able to feed a `TDirectory` to the `Snapshot()` method of an `RInterface`.

### Describe alternatives you've considered
The workaround is to close the file, write and reopen it. I havent tested if it's able to write to a sub-`TDirectory` inside a `TFile`.

### Additional context
I tried to add it myself, but failed to find the code that implements the snapshot functionality.

**Comment by eguiraud** [comment]
Hi @ShamrockLee , thank you for opening this, the request makes absolute sense, but this might be a bit complicated for multi-thread Snapshots, where we need to write to the file from multiple threads and to do so we have to wrap the TFile in a `unique_ptr` and pass it to `TBufferMerger` (which would then close the file when it's done..).

Can you elaborate on your usecase a bit more please? Why do you have the file where Snapshot writes already open, and why is it an annoyance to reopen it after Snapshot is done? Are you writing to the TDirectory before you pass it to Snapshot, or do you have it open in read mode?

**Comment by ShamrockLee** [comment]
@eguiraud I have little knowledge about multi-threading, and was just (naïvely) looking for an RDataFrame-anology of creating a TTree inside a TDirectory.

I currently create some TDirectories representing different stages of seloctions, and write histograms into it. For some reason, I would like to have TTree output also in some of the stages, and for that I need to use the `Snapshot` method.

The current way (haven't tested yet, sorr) would be creating all the directories first and close the file, snapshotting to that file (not sure if the sub-directory could be,  specified), and then open it for histogram writing.

If feasible, it would be great if the (official) way to create a snapshot and store into a certain directory of a TFile, along with the multi-threading consideration, could be documented, so that users switching from the imperative pattern would be easier to understand.

**Comment by eguiraud** [comment]
If you just want to Snapshot a tree in a sub-directory, it's enough to specify the path as part of the tree name:

```
/tmp root -l
root [0] ROOT::RDataFrame(1).Define("x", "42").Snapshot("subdir/t", "f.root");
root [1] TFile f("f.root")
(TFile &) Name: f.root Title:
root [2] f.ls()
TFile**		f.root	
 TFile*		f.root	
  KEY: TDirectoryFile	subdir;1	subdir
root [3] f.cd("subdir")
(bool) true
root [4] f.ls()
TFile**		f.root	
 TFile*		f.root	
  TDirectoryFile*		subdir	subdir
   KEY: TTree	t;1	t
  KEY: TDirectoryFile	subdir;1	subdir
```

Does that work for you?

**Comment by ShamrockLee** [comment]
Sorry for late reply.

How about adding it to the documentation?

**Comment by eguiraud** [comment]
> How about adding it to the documentation?

I did not realize this was not documented, thanks! Done in #9254 .

**Comment by eguiraud** [comment]
Marking this as closed now that we document the Snapshot feature.
