### ISSUE TITLE
Error creating SqliteDataFrame

### ISSUE THREAD

**Issue by radupopescu** [root-project/root#9231]
- [x] Checked for duplicates

### Describe the bug

ROOT script crashes when trying to read an SQLite file into an data frame:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  SQlite error: disk I/O error
```

### Expected behavior

Should not crash

### To Reproduce

```
root.exe -q 'generate_stats_plots.C+("stats.db", "stats.root")'
```

### Setup

ROOT 6.24/04

Linux lxcvmfs146.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Additional context

You can download the ROOT script and the SQLite database here: https://cernbox.cern.ch/index.php/s/JwjCMwnirmL8aX1

Thank you!

**Comment by jblomer** [comment]
Narrowed it town to the use of the custom Sqlite3 VFS module.  Apparently, in some case such as complex queries / many rows, sqlite would like to use a "temporary journal" and create a temporary file for it.  That is currently unsupported by the VFS module.

**Comment by jblomer** [comment]
We need to use `PRAGMA temp_store=2` on the database to make sqlite write temporary tables to memory.

**Comment by radupopescu** [comment]
Thank you!
