### ISSUE TITLE
TRatioPlot axes sync

### ISSUE THREAD

**Issue by belmakier** [root-project/root#9263]
Disclaimer: I'm new to this sort of thing but keen to contribute. Please let me know if I'm going about this the wrong way!

### Explain what you would like to see improved
At present, changing the x axis range on the lower panel of a TRatioPlot does not automatically zoom the top panel. The axes update but the histogram is not redrawn with the correct scale.

### Optional: share how it could be improved
As far as I can tell, what happens is this:

```
THistPainter::Paint() is called
    -> PaintInit() is called, this populates the Hparam structure with the old axis ranges
    -> PaintFrame() is called
          -> RecalculateRange() is called
                 -> gPad->RangeAxis() is called with the old ranges, and emits the RangeAxisChanged() signal
                 -> TRatioPlot::RangeAxisChanged() updates the axis ranges for the top panel
          -> The frame is painted with the old axis ranges
    -> The histogram is drawn with old ranges
```

The most straightforward way that I can see to fix this is to simply call PaintInit() and PaintFrame() again, directly after. This does solve the problem but seems quite inelegant. 

Another idea would be to emit the RangeAxisChanged() signal before PaintInit() so that all the painting proceeds with correct ranges. This could be done by overloading a TPad::RangeAxis() to have an implementation with no arguments that only emits the signal.

### To Reproduce
Simple macro - try zooming on the lower axis:
`
{
  TH1D* hist = new TH1D("hist", "hist", 512, -10, 10);
  hist->FillRandom("gaus", 10000);
  TF1 *func = new TF1("func", "gaus");
  hist->Fit(func);
  TRatioPlot *plot = new TRatioPlot(hist);
  plot->Draw();
}
`

### Setup
1. ROOT 6.25/01
2. macOS 11.4
3. build from git

### Additional context
There is a comment 
"// @TODO: Updating is not working when zooming on the lower plot. Axes update, but upper hist only on resize"
in TRatioPlot.cxx so I assume at least one other person knows about this behavior

**Comment by couet** [comment]
Thanks for your input. We will take it into account.

**Comment by belmakier** [comment]
calling `gPad->Update()` from the prompt after zooming does update the upper plot. However I'm not sure where the appropriate place to call this in the TRatioPlot class would be. I have tried
- at the end of TRatioPlot::Paint()
- at the end of TRatioPlot::RangeAxisChanged()
- at the end of TRatioPlot::CreateVisualAxes()

and none of these have the desired effect.

**Comment by couet** [comment]
I put `gPad->Modified(); gPad->Update()` in all possible places and none of them worked. I guess for the time being we keep that a "feature" as the workaround is simple:  it is enough to zoom on the X top Axis.

**Comment by belmakier** [comment]
Emitting the RangeAxisChanged() signal at line [4751](https://root.cern/doc/master/THistPainter_8cxx_source.html#l04571) of THistPainter.cxx does fix the behavior. The axes need to be synced before the call to PaintInit() and PaintFrame()

**Comment by couet** [comment]
Nice ! What’s the code exactly ?

**Comment by belmakier** [comment]
See here: https://github.com/belmakier/root/commit/a7175c4395323e29a435d969b21d8259c1e8c8d3

**Comment by couet** [comment]
Can you make a PR on the ROOT repository with this code ?
