### ISSUE TITLE
x-axis limits of TGraph do not change after SetLimits

### ISSUE THREAD

**Issue by ikabadzhov** [root-project/root#9325]
I would like to set a custom x axis limits of my plot.

Consider the following script:
```python
import ROOT
import numpy as np

arr = np.asarray([1,2], dtype=float)
c = ROOT.TCanvas("c", "", 800, 800)
g = ROOT.TGraph(2, arr, arr)
g.GetXaxis().SetLimits(-1, 3) # expect change
g.Draw()
c.Draw()
c.SaveAs("x_axis_did_not_change.png")
```
Here, `g.GetXaxis().SetLimits(-1, 3)` takes no effect.

**Comment by couet** [comment]
`SetLimits` is meant to change the axis Xlow and Xmax of an histogram. A graph is a set of discreet points.  The axis range is computed from the points themselves. You cannot change the limits in the sense of the Xlow and Xmax values of an histogram. If your goal is to  make a zoom on the graph you can use `SetRangeUser`.

**Comment by ikabadzhov** [comment]
I just tried `SetRangeUser`. My goal is to rather zoom out on the x axis. It seems that Xlow and Xmax are limitations. `g.GetXaxis().SetRangeUser(-1, 3)` takes no effect again. 

On the other hand, I can easily do that on the y axis, i.e. `g.GetYaxis().SetRangeUser(-1, 3)` and get zoom out on y axis.

**Comment by couet** [comment]
Yes you can zoom in with `SetRangeUser` . That's the goal of this method. To "zoom out" you need to define first a Frame with the limits you need and then draw the graph in it.
```
gPad->DrawFrame(...); 
graph->Draw("L"); // no option "A"
```

**Comment by ikabadzhov** [comment]
That solves the issue. I think this can be closed now.

Thanks for the quick response.
