### ISSUE TITLE
TBrowser's SetShowProjection fails under CentOS 8

### ISSUE THREAD

**Issue by nsjarvis** [root-project/root#9330]
- [ y] Checked for duplicates

### The bug
In TBrowser, SetShowProjectionY and then specifying the number of bins produces an error message and no projection.
Error in <TClingCallFunc::IFacePtr(kind)>: Attempt to get interface while invalid.
Error in <TClingCallFunc::Exec(address, interpVal)>: Called with no wrapper, not implemented!

### Expected behavior
It should open a new window containing the projection

### To Reproduce
Open a 2D histogram.  Right-click on it.  Select SetShowProjectionY.  Click Ok on the popup window to confirm the number of bins. 

### Setup
Root 6.24/04
CentOS 8.5.2111 
Built from source

### Additional context
It worked fine under Redhat 7.

**Comment by couet** [comment]
I just tried. It is fine for me. A new black canvas is opened and as soon as the mouse is moved on top of the 2Dplot the projection appears in the newly created canvas. I am using the ROOT master version.

**Comment by nsjarvis** [comment]
I'll try the master.  Thank you.

**Comment by nsjarvis** [comment]
I cannot install the master easily, but I installed 6.24.06 instead and this TBrowser bug has gone.  Yay!
