### ISSUE TITLE
TBranch::GetEntriesSerialized count_buf contains offsets in big endian ordering?

### ISSUE THREAD

**Issue by ktf** [root-project/root#9331]
It looks like TBranch::GetEntriesSerialized() for the case of VLAs fills the count_buf TBuffer with bigendian ordered ints. Is that expected?

**Comment by pcanal** [comment]
Yes.  The "Serialized" part in the function name indicates that the return buffer is "only" decompressed but is other-wise "as-on-file".  The idea is that doing the swapping at the usage site will avoid one scan through the buffer and "may" results in better performance.

**Comment by ktf** [comment]
ok, i think i finally understand what you meant in the other thread.

Ciao,
Giulio
