### ISSUE TITLE
TMap.IsFolder() should not be true

### ISSUE THREAD

**Issue by adriansev** [root-project/root#9339]
- [ ] Checked for duplicates
yes, not found

### Describe the bug
I would argue that, given the conceptual identity of 'folder' == 'directory'
only a TDirectory can be IsFolder, but a TMap that behaves completely different than a TDirectory, is not..  

### Expected behavior
TMap.IsFolder() == False

**Comment by pcanal** [comment]
In this context, "Folder" means "contains other (T)Objects", so all `TCollection` return `true` for `IsFolder`.

**Comment by adriansev** [comment]
oh.. well, unfortunate naming .. so, while now i got back to check if class name is TDirectory, maybe would be useful a isDirectory() ? to be able to check a list of keys in a TFile if is a TDirectory?

**Comment by pcanal** [comment]
For a `TKey` you can use:
```
key->TestBit(TKey::kIsDirectoryFile);
```
For a TObject you can use:
```
obj->InheritsFrom(TDirectory::Class);
```
Cheers,
Philippe.

**Comment by pcanal** [comment]
Yes, those 2 interface are accessible/similar in python.
