### ISSUE TITLE
Hit CMake Error when build root with msvc

### ISSUE THREAD

**Issue by wmyyy** [root-project/root#9347]
### Describe the bug
Hi All,

I have follow [Build from source](https://root.cern/install/#build-from-source) to build root project on Windows with VS 2019, but hit below CMake Error while building, it seems the error details are in FREETYPE-configure-out.log, and I have attached the log.
[FREETYPE-configure-out.log](https://github.com/root-project/root/files/7617109/FREETYPE-configure-out.log)
Could you please help have a look? Thanks a lot!

Error:
CMake Error at F:/root-project/root_build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-configure-Release.cmake:49 (message):
    Command failed: 1
  
     'C:/Program Files/CMake/bin/cmake.exe' '-G' 'Visual Studio 16 2019' '-DCMAKE_INSTALL_PREFIX=F:/root-project/root_install' '-GVisual Studio 16 2019' '-AWin32' '-Thost=x64' '-DCMAKE_GENERATOR_INSTANCE:INTERNAL=C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise' 'F:/root-project/root_build/FREETYPE-prefix/src/FREETYPE'
  
    See also
  
      F:/root-project/root_build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-configure-*.log
  
### Expected behavior
Successfully build root project without errors.

### To Reproduce
1. Open a x86 Native Tools Command Prompt for VS 2019
2. git clone --branch latest-stable https://github.com/root-project/root.git root_src
3. mkdir root_build root_install && cd root_build
4. cmake -G"Visual Studio 16 2019" -A Win32 -Thost=x64 -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=../root_install ../root_src
5. cmake --build . --config Release --target install

### Setup
1. Operating system: Windows 10
2. Visual studio version: 16.11.6
2. How you obtained ROOT: built it myself.

**Comment by bellenot** [comment]
@wmyyy  Could you attach the `F:/root-project/root_build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-configure-*.log` files?

**Comment by bellenot** [comment]
@wmyyy  It looks like there is a conflict with `C:/Strawberry/perl/bin/pkg-config.bat` (which is not needed). Can you remove `C:\Strawberry\perl\bin\` from the `PATH` and try again?

**Comment by bellenot** [comment]
@wmyyy BTW, this error comes from the `CMakeLists.txt` of `FREETYE`, not from ROOT itself.

**Comment by wmyyy** [comment]
@bellenot I have tried to remove C:\Strawberry\perl\bin\ from the PATH, ROOT can successfully build now. Thanks a lot for your helping!
