### ISSUE TITLE
Candle plot with low statistic histograms makes wrong output

### ISSUE THREAD

**Issue by linev** [root-project/root#9362]
Can be reproduced with following macro:
```
TFile::Open("https://root.cern/js/files/hsimple.root");
hpxpy->GetXaxis()->SetRange(0, 5);
hpxpy->GetYaxis()->SetRange(14, 26);
hpxpy->Draw("candle2");
```
![candle_bad](https://user-images.githubusercontent.com/4936580/144286427-c18d03d5-caf2-4879-b1d9-af224ac0a1e6.png)

For the first bins full interval drawn wrongly. 
Rectangle around 50% of counts shown ok, but lines which should show 99.9% of existing values are absolutely wrong - they are drawn inside of 50% rectangle. 

This happens while center of bin is used when searching for that interval. 
If there is only non-empty bin in the histogram,
interval is 0. If one uses lower and upper bin, picture will look:

![candle_new](https://user-images.githubusercontent.com/4936580/144287268-a9fb5eb6-c8d5-46e5-b899-25a29d6395cd.png)

PR will follow soon

**Comment by linev** [comment]
Another problem with candle plot drawing is so-called `kMedianNotched`. 
For low_stat histograms they make output:

![candle_bad2](https://user-images.githubusercontent.com/4936580/144408739-c4f9f694-c674-4b36-95dc-c9b6b43646b0.png)

Additional fix will be provided to the PR to get:

![candle4_good](https://user-images.githubusercontent.com/4936580/144409065-a64ec073-f342-4a15-b931-fd7042d0853b.png)

**Comment by couet** [comment]
I emailed the author of the code: georg.troska@uni-dortmund.de

**Comment by linev** [comment]
> The low statistics stuff at the notched candles were actually meant seriously!

ok, I will revert commit
