### ISSUE TITLE
[TGeo][Regression] RadLen and IntLen changed by factor of 10 (default unit system)

### ISSUE THREAD

**Issue by olifre** [root-project/root#9383]
- [x] Checked for duplicates

### Describe the bug
`TGeoMaterial::RadLen` and `TGeoMaterial::IntLen` are off by a factor of 10 since commit:
https://github.com/root-project/root/commit/69ecafae96c17de621f68966f6cb4af213734e6c#diff-d30f058e18d96b0e287376ae81abec13a0acabeff56793ceafdeaa258925fa1d

Example session with ROOT 6.14/02:
```
root [0] new TGeoManager();
root [1] gGeoManager->Material("Silicon",   28.0855,  14,  2.329, 1);
root [2] gGeoManager->GetListOfMaterials()->Print();
Collection name='THashList', class='THashList', size=1
 Material Silicon    A=28.0855 Z=14 rho=2.329 radlen=9.35362 intlen=45.7729 index=0
```

Example session with ROOT 6.24/06:
```
root [0] new TGeoManager();
root [1] gGeoManager->Material("Silicon",   28.0855,  14,  2.329, 1);
root [2] gGeoManager->GetListOfMaterials()->Print();
Collection name='THashList', class='THashList', size=1
 Material Silicon    A=28.0855 Z=14 rho=2.329 radlen=0.935361 intlen=4.57729 index=0
```

### Additional context
This is using the "default" unit system, i.e. `cm`. Checking [PDG data](https://pdg.lbl.gov/2020/AtomicNuclearProperties/HTML/silicon_Si.html), it seems that `9.37`, i.e. the old behaviour, was correct. 

Reading through the code, it seems the `cm2` factor was added to the denominator of the expression for the radiation length calculation and the `cm` factor was added multiplicatively, yielding a change by a factor of 10. I could not find the original Geant3 code, but it seems likely that the factors were absorbed in the constants there.

**Comment by couet** [comment]
I think @agheata should know what's going on here.

**Comment by agheata** [comment]
Hi, this is because the default unit was changed at the time to Geant4 units, which produced this changed behavior. Since v6-25-01 the default behavior of having by default CGS units was restored. In v6-14 you can try:
```
TGeoManager::LockDefaultUnits(false);
TGeoManager::SetDefaultUnits(TGeoManager::kRootUnits);
```
before creating any material.

**Comment by olifre** [comment]
@agheata Many thanks, indeed, that fixes it! 

So I think (for future reference), to get into a situation which can be used in an analysis framework which should work consistently across ROOT versions >= 6.00.00 to 6.25.00 and beyond, I have to use:
```cpp
#if ROOT_VERSION_CODE > ROOT_VERSION(6,19,02)
        // ROOT version supports unit switching, forcing usage of kRootUnits.
        if (TGeoManager::GetDefaultUnits() != TGeoManager::kRootUnits) {
                TGeoManager::LockDefaultUnits(false);
                /// This ROOT version uses TGeant4 units by default, switching back to ROOT units...
                TGeoManager::SetDefaultUnits(TGeoManager::kRootUnits);
                TGeoManager::LockDefaultUnits(true);
        }
#endif
// Create your TGeoManager here...
```
Correct?

**Comment by agheata** [comment]
@olifre yes this looks to behave correctly also for more recent versions, where the lines will have no effect.

**Comment by olifre** [comment]
@agheata Thanks for the confirmation! 
Since this is a rather breaking change in defaults which has cost one of us over a week to identify, I wonder whether a warning in the release notes would be possible. Checking at:
https://root.cern/doc/v620/release-notes.html
I don't find any warning that the units were changed in that release. What do you think?

**Comment by agheata** [comment]
@olifre this was an oversight so it does not appear in the release notes. I totally agree that we should avoid wasting other people time trying to debug the same thing, but the release notes of 6.20 may not be the first place people look, in particular since this affects several versions. I was thinking to put a short description of the incompatibility and fix in the reference guide of [TGeoMaterial](https://root.cern/doc/master/classTGeoMaterial.html) since this is the class where the users will actually see the different behaviour. What do you think?

**Comment by olifre** [comment]
@agheata That sounds like a reasonable location to add the documentation :-). I also talked to the user on our end who invested a signficant time to find the issue, and while of course the actual place to look for was unclear for most of the time (since he just saw that energy loss calculation in reconstruction had changed, but did not see why), [TGeoMaterial](https://root.cern/doc/master/classTGeoMaterial.html) then finally would have been the place he looked at. 
So I think this is the most visible location indeed. Thanks!

**Comment by agheata** [comment]
@olifre I digged a bit more and discovered that as the units were gradually introduced, the interface was not the same from the beginning. So the initial version switching to G4 units by default was v6-19-02 (backported also to v6-18-02) and there the interface to change the unit back to CGS was:
```
TGeoUnit::setUnitType(TGeoUnit::kTGeoUnits);
```
The system allowing to set the default unit via TGeoManager was introduced in v6-23-02 (and backported to v6-22-08) and was the same until v6-25-01:
```
TGeoManager::LockDefaultUnits(false);
TGeoManager::SetDefaultUnits(TGeoManager::kRootUnits);
TGeoManager::LockDefaultUnits(true);
```
So your logic will work for sure only starting from v6-23-02 included (6-23-01 seems to have the initial style)

**Comment by amorsch** [comment]
Please correct also the formula related to the Geant4 units in TGeoMaterial::SetRadLen(...)
The returned value is off by a factor of 100 (ie radlength in dm instead mm) if one uses density in g/cm^3.
Cheers Andreas

**Comment by agheata** [comment]
> Please correct also the formula related to the Geant4 units in TGeoMaterial::SetRadLen(...)
> The returned value is off by a factor of 100 (ie radlength in dm instead mm) if one uses density in g/cm^3.
> Cheers Andreas

@MarkusFrankATcernch and @petricm can you comment on this?

**Comment by ihrivnac** [comment]
@agheata , I have proposed a PR with a fix https://github.com/root-project/root/pull/9401
