### ISSUE TITLE
TPad::SaveAs .tex Standalone option

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#9384]
### Is your feature request related to a problem? Please describe.
When saving a canvas as .tex, I often have to later add the begin{document} and usepackages by hand.

### Describe the solution you'd like
- `SaveAs(".tex", "standalone")` adds the statements below in the output file:
- Default behaviour without arguments adds the statements below as comment (prepend %)

```
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{patterns,plotmarks}
\begin{document}
<----- here the current output
\end{document}
```

### Describe alternatives you've considered
To develop a bash script that modifies the text file using cat / echo. Or a c++ macro.
https://root-forum.cern.ch/t/colored-2d-histograms-in-pdf-output/13822/45

### Additional context
https://github.com/root-project/root/pull/9147

**Comment by couet** [comment]
Yes this option "standalone"  as you described it seems a good idea. Do you want to do a PR ?

**Comment by couet** [comment]
I'll do it.

**Comment by ferdymercury** [comment]
Thanks!
(And sorry for the late reply, it's a holiday in Spain).

**Comment by couet** [comment]
Now implemented

**Comment by ferdymercury** [comment]
Amazing! Thanks so much
