### ISSUE TITLE
Does ROOT support windows x64 platform?

### ISSUE THREAD

**Issue by wmyyy** [root-project/root#9389]
Hi All,

In the ROOT [release binary list](https://root.cern/releases/release-62406/), for windows, I see there is only root_v6.24.06.**win32**.vc16.exe/zip but no x64 binary. And I have follow below steps to build root project on Windows with VS 2019 to generate x64 binary, but hit below error, so I wonder if ROOT support generate x64 binary on windows? Could you please help have a look, thanks a lot!

1. Open a x64 Native Tools Command Prompt for VS 2019
2. git clone --branch master https://github.com/root-project/root.git
3. cd root
3. mkdir build_amd64 && cd build_amd64
4. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 ..
5. cmake --build . --config Release

Hit below error when build:
F:/root-project/root/build_amd64/include/RooDataHist.h(282,35): error GE639D5E5: constant expression evaluates to 18446744073709551615 which cannot be narrowed to type 'unsigned long' [-Wc++11-narrowing] [F:\root-project\root\build_amd64\roofit\roofitcore\G__RooFitCore.vcxproj]

Thanks

**Comment by ferdymercury** [comment]
https://github.com/root-project/root/pull/9387

**Comment by wmyyy** [comment]
@ferdymercury I have tried disabling roofit can successfully build now. Thanks a lot!
