### ISSUE TITLE
Why there is not a TFormula::Eval(Double_t* values) but I have to call TFormula::EvalPar()?

### ISSUE THREAD

**Issue by mattiasotgia** [root-project/root#9395]
Hi, 
I was trying to evaluate a N-dimensional function but found that the `TFormula::Eval()` method only accept `Double_t x, y, z, t` as arguments, and later passes them to a private method `DoEval()` as an array. I was wondering why there is not a `Eval()` methods which require a variable dimension array. 

Its implementation would be quite easy, for example could be:
```
Double_t TFormula::Eval(Double_t *x) const
{
   return EvalPar(x, nullptr);
}
```

**Comment by guitargeek** [comment]
Hi @mattiasotgia, I'm not sure, but I think the code owner of TFormula is @lmoneta. I have assigned the issue to him.

**Comment by lmoneta** [comment]
Hi, 
We could add this method, but we have already `TFormula::EvalPar` which has as default parameter a nullptr. I would then prefer avoiding adding this function. 
Any particular reason that you need it and you cannot use EvalPar ?

**Comment by mattiasotgia** [comment]
Hi, 
thanks for the response. No I just asked because I needed to evaluate a N-dimensional function in a point, but couldn't find any documentation on how to do it, and couldn't find any documentation on the `TFormula::EvalPar()` method, whereas lot of documentation is given for the `TFormula::Eval()` method. 
Other than this I don't have any other particular reason to need another implementationi of the Eval method. 
Anyway, thank you!

**Comment by lmoneta** [comment]
Hi, 
Note that TF1 implements also the `operator()(double * x, double * p = nullptr)`. You can do for example: 
```
TF2 f("f","x+y");
double x[] = {1,2};
cout << f(x) << endl;
```
