### ISSUE TITLE
GDML geometry import does not handle isotopes properly (6.24.6)

### ISSUE THREAD

**Issue by dwcasper** [root-project/root#9421]
GDML files exported from Geant4 include isotope information with correct abundances where appropriate.

When such a file is imported by TGeoManager::Import, the isotope information is not properly associated with the elements in question.

The problem seems to arise due to the attachment of isotopes being skipped when one of the default elements is "reused":

https://github.com/root-project/root/blob/dbfc076925ca25cee3033c795150e8f0e8c2d5f1/geom/gdml/src/TGDMLParse.cxx#L1129

https://github.com/root-project/root/blob/dbfc076925ca25cee3033c795150e8f0e8c2d5f1/geom/gdml/src/TGDMLParse.cxx#L1192

When a default element with isotope information in the GDML is found, it should be checked whether it has Nisotopes() == 0, and if so, the  loop "for (fractions f = ..." should run.

The attached GDML file exhibits the issue when imported.  There are a few elements in the file with non-standard names (e.g. "Lead_elm") which due to the name not being matched were created as "new" elements, and only these have the correct isotope information.

[FaserNu2.gdml.gz](https://github.com/root-project/root/files/7698415/FaserNu2.gdml.gz)

**Comment by agheata** [comment]
This is tricky to do because isotopes cannot be added to normal elements (see: TGeoElement::AddIsotope) because one may want to use both standard elements and elements having isotopes in the same geometry. Since the reusing mechanism relies on the element name, the easiest is to rename the elements having isotopes to something non-standard (e.g. HydrogenNat).  
Of course, the definition of such elements as having isotopes can be detected in the parser, forcing the creation of a new element,  but then using this element by name would not work (being identical to the standard one). I'm open to suggestions...

**Comment by dwcasper** [comment]
It would seem to me that by reading in a GDML file that redefines the default elements, the user has indicated that their intention is to ... redefine the default elements.

Perhaps the override of default elements (i.e. giving them isotopes) could be controlled by adding a boolean flag to the import call, or a static method of the TElement class.  You could make the default value of the flag agree with present behavior for backward compatibility, but allowing someone who wants the default elements to have isotopes to enable it.

**Comment by agheata** [comment]
A static flag that allows the user to explicitly override default elements sounds like a good compromise. This can be implemented indeed as a static method like: `TGeoElement::AllowElementOverride(true)` to be called by the user before reading the geometry file. If the user forgets to call it, importing the geometry would produce an exception (like in your case). Is this acceptable?

**Comment by dwcasper** [comment]
Yes, it's a good solution for me.

Thanks.

**Comment by agheata** [comment]
OK, I'll make a PR on that on a one week scale and add you as reviewer

**Comment by agheata** [comment]
Hi, I realized that other geometry files are affected by this, so this is a bug indeed, no need for an extra user flag. The PR #9602 is supposed to fix the issue. I cannot add you as reviewer for this, but you can comment here if you want.
