### ISSUE TITLE
Add RooFit::MultiProcess build to default CI matrix

### ISSUE THREAD

**Issue by egpbos** [root-project/root#9430]
### Explain what you would like to see improved
The current Jenkins build matrix doesn't have any builds with `RooFit::MultiProcess` activated currently. PRs that touch anything related to this may silently break things, because it is too easy to forget to manually pass the build flags to the Jenkins bot to activate it.

### Optional: share how it could be improved
Ideally, all builds, except the Windows one, would build with `RooFit::MultiProcess`. To do this, currently, the easiest option is to add `-Droofit_multiprocess=ON -Dbuiltin_zeromq=ON -Dbuiltin_cppzmq=ON` to the build matrix (except the Windows build, because `MultiProcess` is not supported on Windows).

A more minimalistic alternative would be to add the build flags to the `ROOT-performance-centos8-multicore/default` build only.

### Additional context
Note that the builtin options are necessary to avoid having to install ZeroMQ on the CI system as a dependency while still having `fail-on-missing` activated as well, as is currently the case.

**Comment by Axel-Naumann** [comment]
Which of the builtin packages can we use from the distro - are we waiting for the next release of cppzmq or zeromq, and can we use a current release for the other one? For testing we try to use distro packages wherever possible.

**Comment by egpbos** [comment]
For zeromq (libzmq): indeed, we have to wait for the next release, anything higher than 4.3.4 (not sure if it will be a patch or minor version bump).

For cppzmq: the most recent release works. Most distros package cppzmq together with libzmq though, so still need to wait for libzmq's next release. I didn't test what the oldest supported release was.

**Comment by Axel-Naumann** [comment]
Is cppzmq different from [zmqpp](https://github.com/zeromq/zmqpp)? That's what Ubuntu offers, while cppzmq is known...

**Comment by egpbos** [comment]
Yes, that's a different one, [cppzmq](https://github.com/zeromq/cppzmq) includes zmq.hpp, which is included in the Ubuntu dev package, e.g. this one: https://packages.ubuntu.com/impish/amd64/libzmq3-dev/filelist

**Comment by egpbos** [comment]
I see now that you added it to the build, that's great, thanks! We should keep the issue open then to revisit the builtin configuration later, right?

**Comment by Axel-Naumann** [comment]
I think we'll just revisit this as part of the ongoing inclusion of new distro versions; reviewing the available set of external packages is just part of that. Let's close this instead!
