### ISSUE TITLE
Failing tests in the master branch

### ISSUE THREAD

**Issue by amadio** [root-project/root#9436]
I had to run the tests to check the fix for the `-fPIE` issue, and decided it may be useful to report on the other test failures that I observe.

The full command line I used for the configuration is below
```
$ cmake  -DCMAKE_CXX_FLAGS="-O2 -march=native -pipe" -DPYTHON_EXECUTABLE="/usr/bin/python3.9" -Dalien="OFF" -Dall="ON" -Darrow="OFF" -Dclad="OFF" -Dclingtest="ON" -Dcuda="OFF" -Dcudnn="OFF" -Ddaos="OFF" -Ddcache="OFF" -Dfail-on-missing="ON" -Dgfal="OFF" -Dmonalisa="OFF" -Dr="OFF" -Droofit_multiprocess="OFF" -Droottest="ON" -Dtest_distrdf_dask="OFF" -Dtest_distrdf_pyspark="OFF" -Dtmva-gpu="OFF" -Dvecgeom="OFF" /srv/root/src/root
```
I am attaching here the [CMake configuration output](https://github.com/root-project/root/files/7709954/cmake.log), [CMakeCache.txt](https://github.com/root-project/root/files/7709963/CMakeCache.txt), the full [build log](https://github.com/root-project/root/files/7709957/build.log), and the [log for failed tests](https://github.com/root-project/root/files/7710157/ctest-failed.log). To save you some time looking over these files, here is the full list of tests that fail:

```
The following tests FAILED:
	  1 - clingtest-check-cling (Failed)
	 13 - pyunittests-pyroot-dependency-versions (Failed)
	 68 - pyunittests-pyroot-numbadeclare (Not Run)
	 69 - test-import-numba (Failed)
	160 - gtest-math-mathcore-test-stressMathCoreUnit (Failed)
	282 - test-stressmathcore (Failed)
	307 - test-TFormulaTests (Failed)
	800 - tutorial-pythia-pythiaExample (Failed)
	1142 - tutorial-pyroot-pyroot004_NumbaDeclare-py (Not Run)
	1143 - test-import-numba (Failed)
	1358 - roottest-cling-stl-dicts-build (Failed)
	1611 - roottest-root-dataframe-test_snapshot_copyaddresses (Failed)
	1753 - roottest-root-io-transient-base-WriteFile (Failed)
	1754 - roottest-root-io-transient-base-hadd_autoload (Failed)
	1799 - roottest-root-meta-countIncludePaths (Failed)
	1841 - roottest-root-meta-MakeProject-runaliceesd (Failed)
	1852 - roottest-root-meta-ROOT-7462-make (Failed)
	2229 - roottest-root-tree-cache-perfstattest-libevent-build (Failed)
	2230 - roottest-root-tree-cache-perfstattest (Failed)
```
* You can ignore the failures for numba, as I don't have that installed.
* The math tests seem to fail because of strict tolerances and errors related to SIMD being enabled (I used `-march=native` on a machine that has AVX2 support). I suggest enabling SIMD on at least one of the CI builds in Jenkins to cover that if that's not the case now. 
* The test `roottest-root-tree-cache-perfstattest-libevent-build` and some others fail because of a build type not being set (I just set `CMAKE_CXX_FLAGS` and not `CMAKE_BUILD_TYPE`, which should be a valid configuration). It's fine to require setting a build type for testing, but having a fallback for when it's not set is probably better. In CI a build type is usually set, so you won't see these failures in Jenkins.
* Some of the other tests fail due to `unresolved while linking` errors from cling, which could be something related to the `-fPIE` fixes.
* The test loadAllLibs may fail if `Loading library libVMCLibrary.so [rc = -1]` shows in the output, which can happen if VMC is installed as a separate package somewhere. Having VMC installed can also make other tests fail as well, as it will try to load wrong ROOT libraries from another build. I had to uninstall both ROOT and VMC on my machine to be able to run the tests, which is not great. I think it is a good idea to have ROOT (and maybe VMC) installed with yum on at least one of the build nodes to ensure this sort of problem doesn't happen (i.e. picking up wrong ROOT and other libraries from elsewhere while running roottest). This has been a recurring problem with roottest.

**Comment by amadio** [comment]
I've assigned people for cling and math test failures, please assign others as necessary for other failures.

**Comment by amadio** [comment]
FYI, after setting the build type to `Release` and rerunning, only these still fail:
```
The following tests FAILED:
	  1 - clingtest-check-cling (Failed)
	 13 - pyunittests-pyroot-dependency-versions (Failed)
	 68 - pyunittests-pyroot-numbadeclare (Not Run)
	 69 - test-import-numba (Failed)
	160 - gtest-math-mathcore-test-stressMathCoreUnit (Failed)
	282 - test-stressmathcore (Failed)
	307 - test-TFormulaTests (Failed)
	1143 - tutorial-pyroot-pyroot004_NumbaDeclare-py (Not Run)
	1852 - roottest-root-meta-ROOT-5694-execLoadLibs (Failed)
```
and the log of failures is [here](https://github.com/root-project/root/files/7710438/ctest-failed.log).

**Comment by Axel-Naumann** [comment]
You can get that down by a couple by addressing:
```
The 'numba>=0.47.0' distribution was not found and is required by the application
```

**Comment by amadio** [comment]
I did mention that I don't have numba installed and those should be ignored in the description...

**Comment by Axel-Naumann** [comment]
> those should be ignored in the description...

We really want you to install numba if you want to test ROOT.

**Comment by dpiparo** [comment]
@amadio , I believe this report was extremely useful at the time and that meanwhile all issues have been fixed. If I am not wrong, would you be so kind to close the issue?

**Comment by amadio** [comment]
Sure, I am closing. If I notice that some of the issues reported above are not fixed, I will open a new ticket. Cheers,
