### ISSUE TITLE
`TEfficiency::SetStatisticOption` not always set/reset `fBoundary` member

### ISSUE THREAD

**Issue by linev** [root-project/root#9455]
Here: https://github.com/root-project/root/blob/master/hist/hist/src/TEfficiency.cxx#L3444-L3494

For `kBJeffrey`, `kBUniform`,`kBBayesian` statistic options `fBoundary` not set.
It kept default or from previous settings - making output results non-determenistic.
In my mind, one should reset it to some predefined value like `fBoundary = &ClopperPearson;`

**Comment by lmoneta** [comment]
For the Bayesian statistics methods, kBJeffrey, kBUniform,kBBayesian, the function pointer fBoundary is not used, so it should not matter if it is not set. I think it will stay to the default constructed value, i.e. .a nullptr.
@linev , did you observe a problem using some of these 3 bayesian methods ?

**Comment by linev** [comment]
`fBoundary` is used for drawing

**Comment by lmoneta** [comment]
In JSROOT, I see it is used, but in TEfficiency.cxx is used only in GetEfficiencyErrorUp/Low.
The problem then is maybe in JSROOT.  Do you take care correctly of the Bayesian case there ?

**Comment by lmoneta** [comment]
I see in JSROOT : 
```
 TEfficiencyPainter.prototype.getEfficiencyErrorLow = function(bin) {
      let obj = this.getObject(),
          total = obj.fTotalHistogram.getBinContent(bin),
          passed = obj.fPassedHistogram.getBinContent(bin),
          eff = this.getEfficiency(bin);

      return eff - this[this.fBoundary](total,passed, obj.fConfLevel, false);
   }
```
so no handling of the Bayesian case. In the C++ case you have Ignoring the weighted case):
```
 if(TestBit(kIsBayesian))
      {
         // parameters for the beta prior distribution
         Double_t alpha = TestBit(kUseBinPrior) ? GetBetaAlpha(bin) : GetBetaAlpha();
         Double_t beta  = TestBit(kUseBinPrior) ? GetBetaBeta(bin)  : GetBetaBeta();
         return (eff - Bayesian(total,passed,fConfLevel,alpha,beta,false,TestBit(kShortestInterval)));
      }
      else
         return (eff - fBoundary(total,passed,fConfLevel,false));
```

**Comment by linev** [comment]
Ok, I see this now - thanks for explanation. 
There are too many flags around the code. 

In JSROOT I could not implement all options - only part of them.
Otherwise I need to copy lot of `MathCore`/`MathMore` code.
