### ISSUE TITLE
SofieCompileModels_PyTorch.vcxproj fails to compile on pytest version 6.2.5

### ISSUE THREAD

**Issue by wmyyy** [root-project/root#9487]
### Describe the bug
Hi All,

I am trying to build ROOT project as well as tests, but there is an error occurred when building, and it maybe related to pytest version. When I use same build steps but different pytest version, ROOT project build success with pytest version 6.1.1, but SofieCompileModels_PyTorch.vcxproj fails to compile with pytest version 6.2.5, the error as belows. I have checked if pytest version is 6.1.1, there is no pymva folder generated after cmake commands, and for pytest version 6.2.5, pymva folder generated after cmake commands. Could you please help have a look at this issue? Thanks a lot!
![image](https://user-images.githubusercontent.com/17844901/147636210-34c8102b-8380-4b92-828d-097a6af7829d.png)

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: The command "setlocal [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: .\emitFromPyTorch [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1 [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :VCEnd" exited with code 9009. [F:\gitP\root-project\root\build_amd64\tmva\pymva\test\SofieCompileModels_PyTorch.vcxproj]

### Expected behavior
Project build successfully.

### To Reproduce
1. Open a x64 Native Tools Command Prompt for VS 2019
2. git clone --branch master https://github.com/root-project/root.git
3. cd root
4. mkdir build_amd64 && cd build_amd64
5. pip install pytest
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -Droofit=off -Dtesting=ON -Droottest=ON ..
6. cmake --build . --config Release

### Setup
1. Operating system: Windows 10
2. How you obtained ROOT, built it myself.

**Comment by bellenot** [comment]
How did you enable `tmva-sofie`? This has not been tested on Windows

**Comment by wmyyy** [comment]
> How did you enable `tmva-sofie`? This has not been tested on Windows

Hi bellenot, I add -Dtesting=ON -Droottest=ON for cmake option.

**Comment by lmoneta** [comment]
For enabling the building of that test (SofieCompiledModels) you need only to have Python installed with PyTorch. Just do `pip install torch` for installing pytorch

**Comment by bellenot** [comment]
Thanks @lmoneta, I'll try

**Comment by bellenot** [comment]
So I created a PR that should fix this issue. It compiles and runs fine with VS 2022 (v17.0.4) and pytest 6.2.5:
```
C:\Users\sftnight\build\release>ctest -C Release -R "pytorch|PyTorch"
Test project C:/Users/sftnight/build/release
    Start  889: tutorial-tmva-TMVA_SOFIE_PyTorch
1/7 Test  #889: tutorial-tmva-TMVA_SOFIE_PyTorch ............................   Passed    6.68 sec
    Start 1109: test-import-torch
2/7 Test #1109: test-import-torch ...........................................   Passed    1.98 sec
    Start 1111: tutorial-tmva-pytorch-ClassificationPyTorch-py
3/7 Test #1111: tutorial-tmva-pytorch-ClassificationPyTorch-py ..............   Passed   12.76 sec
    Start 1108: tutorial-tmva-pytorch-ApplicationClassificationPyTorch-py
4/7 Test #1108: tutorial-tmva-pytorch-ApplicationClassificationPyTorch-py ...   Passed    6.30 sec
    Start 1113: tutorial-tmva-pytorch-RegressionPyTorch-py
5/7 Test #1113: tutorial-tmva-pytorch-RegressionPyTorch-py ..................   Passed   26.83 sec
    Start 1110: tutorial-tmva-pytorch-ApplicationRegressionPyTorch-py
6/7 Test #1110: tutorial-tmva-pytorch-ApplicationRegressionPyTorch-py .......   Passed    5.79 sec
    Start 1112: tutorial-tmva-pytorch-MulticlassPyTorch-py
7/7 Test #1112: tutorial-tmva-pytorch-MulticlassPyTorch-py ..................   Passed    9.45 sec

100% tests passed, 0 tests failed out of 7

Label Time Summary:
python_runtime_deps    =  61.12 sec*proc (5 tests)
tutorial               =  67.80 sec*proc (6 tests)

Total Test time (real) =  71.37 sec
```
