### ISSUE TITLE
(New) option “TEXTE”, for 1D histograms, with "± bin error"

### ISSUE THREAD

**Issue by mateus-vicente** [root-project/root#9505]
Hello,

following https://root-forum.cern.ch/t/option-texte-for-1d-histograms/48277/4, would it be possible to have a new drawing option for TH1s where, in addition to the error bar and bin content text, we also have the bin error text (as illustrated in red in the attached picture)?

Thank you!
Best,
Mateus

<img width="949" alt="Screenshot 2022-01-06 at 12 53 14" src="https://user-images.githubusercontent.com/18140784/148404609-fdea8d38-d99e-4cde-b328-8135bfd91342.png">

**Comment by couet** [comment]
Thanks for the PR. We will look how to implement this new option.

**Comment by couet** [comment]
Indeed, as said on the forum it is quite simple to reproduce this option with the current ROOT. See the script and plot I posted on the forum. If that enough for you we can close this issue.

**Comment by couet** [comment]
@mateus-vicente can I close this issue?

**Comment by mateus-vicente** [comment]
Yes, thank you!
