### ISSUE TITLE
Documentation of `RooAbsReal::getValues` is broken

### ISSUE THREAD

**Issue by hageboeck** [root-project/root#9523]
- A rebase or similar apparently cut the documentation in two, and a stray sentence now leads the documentation of the second overload.
- The first overload has no documentation at all ...

Please make it a habit immediately write a good docstring in the same commit where the interface is fixed defined.

https://github.com/root-project/root/blob/a8874141392745a4f9b35fa52d41ada66f203df5/roofit/roofitcore/inc/RooAbsReal.h#L126-L139

https://root.cern.ch/doc/master/classRooAbsReal.html#a3f4185c14daa089c29ae3ba1e90b5235

**Comment by guitargeek** [comment]
Removed from the milestone because this is now superseded by the actual PRs that are added to the milestone instead.
