### ISSUE TITLE
[Feature request] It would be great to have the ROOT build with VS 2022.

### ISSUE THREAD

**Issue by andriish** [root-project/root#9590]
### Is your feature request related to a problem? Please describe.
It would be great to have the ROOT build with VS 2022.

### Describe the solution you'd like
ROOT 6.24 binary build with VS 2022.

### Describe alternatives you've considered
ROOT 6.24 binary build with VS 2019. Does not work with VS 2022.

### Additional context
I'm not even sure if one can easily get older VS.

**Comment by bellenot** [comment]
We are planning to migrate to VS 2022 after the ROOT v6.26.00 release

**Comment by dwcasper** [comment]
FYI, older VStudio versions, are available for free (registration required) here:

https://visualstudio.microsoft.com/dev-essentials/

**Comment by andriish** [comment]
Hi @bellenot ,

are there updates? I assume everything should be fine now, right?

Andrii

**Comment by bellenot** [comment]
Hi @andriish, yes, the Win64 builds are made with VS 2022, and the Win32 with latest VS 2019. But they are fully compatible, so that should not be an issue anyway. 
Cheers, Bertrand

**Comment by bellenot** [comment]
@andriish FYI we switched all our builds to VS 2022.
