### ISSUE TITLE
doxygen gets confused with ClassDef and Streamer

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#9596]
- [x] Checked for duplicates

### Describe the bug
ClassDef macro implements the ;:Streamer declaration in hundreds of classes. However, when generating the documentation, doxygen seems not to be able to detect its presence, and gives thousands of warnings, see e.g. https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-v624/96/consoleFull. 

of the type:
```
geom/geom/src/TGeoArb8.cxx:1280: warning: no uniquely matching class member found for 
  void TGeoArb8::Streamer(TBuffer &R__b)
```

### Expected behavior
- Maybe the ClassDef macro can be tweaked so that doxygen finds correctly the link.
- Or if it is a bug in doxygen, I could file a report to them. 
- If none of the above solutions work, maybe hide this functions from doxygen?

### To Reproduce
https://root.cern/for_developers/doxygen/

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 12 2022, 10:17:19                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
https://github.com/root-project/root/issues/8781

**Comment by couet** [comment]
> Maybe the ClassDef macro can be tweaked so that doxygen finds correctly the link.

ClassDel is already in the `PREDEFINED` variable in Doxyfile (line 2257). So I think doxygen should instructed about its existence. my be that's not the right way to declare it. I am not sure.

**Comment by ferdymercury** [comment]
I created a minimal example for testing purposes.

[streamer.zip](https://github.com/root-project/root/files/7885164/streamer.zip)

It issues this warning:
`streamer/TGeoArb8.cxx:22: warning: documented symbol 'void TGeoArb8::Streamer' was not declared or defined.`

and the output does not show the function.

![image](https://user-images.githubusercontent.com/10653970/149848810-daba8c17-11b6-459d-aa66-02229cbb1afa.png)

If I change in the Doxyfile PREDEFINED to empty, and EXPAND_ONLY_PREDEF     = NO, then the warning disappears and the doxygen output looks correct.

![image](https://user-images.githubusercontent.com/10653970/149848761-52c81fd7-5cc1-491f-b59b-8fbb19793f46.png)

However, I saw that in the full docu build we get still some other message even when changing that:
```
/opt/root_src/core/meta/src/TStreamerElement.cxx:1085: warning: no uniquely matching class member found for 
  void TStreamerLoop::Streamer(TBuffer &R__b)
```

So not sure either...

**Comment by couet** [comment]
So we have on or the other. Could it be a doxygen issue in that case ?

**Comment by ferdymercury** [comment]
It could be a doxygen issue, but in the small reproducer I prepared, I do not get the second error. It runs without any errors.
Not however in the full ROOT build :S

**Comment by couet** [comment]
if I remove `"ClassDef(x,y)=//" from `PREDEFINED` and set  `EXPAND_ONLY_PREDEF = NO` The warning disappear bu then a full list of (useless) functions appear in the `TGeoArb8` documentation:
<img width="729" alt="Screenshot 2022-01-18 at 13 42 14" src="https://user-images.githubusercontent.com/4697738/149939750-c8ad116e-85f9-4422-8621-6693e84d4bd9.png">
I am not sure we want that. May be we can survive with this warning ?

**Comment by ferdymercury** [comment]
Mmm and if you let expand only predef to YES, but add ClassDefOutline to PREDEFINED, what happens? Because ClassDef calls itself another macro, so maybe it is not expanding enough subnested macros. ?

**Comment by couet** [comment]
I am not sure what you are suggesting for `PREDEFINED` ? can you copy/paste here what it should be ?

**Comment by ferdymercury** [comment]
What I was suggesting is:
ClassDef contains a nested call to _ClassDefOutline_ macro.

Thus, I was suggesting that both ClassDef and ClassDefOutline should be in the PREDEFINED variable. However, I am not sure about the syntax.

**Comment by couet** [comment]
I would say:

```
PREDEFINED             = "ClassDef(x,y)=//" \
                         "_ClassDefOutline_(x,y,z)=//" \
                         ClassImp(x)=// \
                         ClassImpQ(x)=// \
                         templateClassImp(x)=// \
                         NamespaceImp(x)=// \
                         R__CLING_PTRCHECK \
                         R__USE_IMT \
                         R__SUGGEST_ALTERNATIVE(x)=
```
But then I am not sure what is the best way combination ....

**Comment by ferdymercury** [comment]
I think that ClassDef and ClassDefOutline should be moved from the `PREDEFINED` to the `EXPAND_AS_DEFINED` tag below.
Otherwise, we are now replacing ClassDef with a `//` comment.

**Comment by couet** [comment]
Can you propose something ? I guess you are more advanced than me on that topic ....

**Comment by ferdymercury** [comment]
I'll try :)

**Comment by ferdymercury** [comment]
I've filed a bug report https://github.com/doxygen/doxygen/issues/9049

**Comment by ferdymercury** [comment]
Albert provided a solution.

```
EXPAND_ONLY_PREDEF     = NO
SEARCH_INCLUDES        = YES
INCLUDE_PATH           = ../../core/base/inc
PREDEFINED             = 
                         R__CLING_PTRCHECK \
                         R__USE_IMT \
                         R__SUGGEST_ALTERNATIVE(x)=
```

**Comment by couet** [comment]
Did you try it ? if it works can you provide a PR ?

**Comment by ferdymercury** [comment]
Yes, it works. I'll provide a PR.

**Comment by ferdymercury** [comment]
I am preparing a PR, but will wait first for https://github.com/root-project/root/pull/9615 to be merged in order to prevent more conflicts.

I will hide these functions from doxygen:
HashConsistency, Class, DeclareFileName, DeclareFileLine, Dictionary, ImplFileName, ImplFileLine, IsA, ShowMembers

They can be easily re-enabled by changing in the Doxyfile:
ENABLED_SECTIONS = HIDDEN_SYMBOLS

**Comment by couet** [comment]
PR #9615 merged

**Comment by ferdymercury** [comment]
Thanks :)
