### ISSUE TITLE
Possible incomplete installation of internal TBB

### ISSUE THREAD

**Issue by sawenzel** [root-project/root#9599]
### Describe the bug
ALICE is building ROOT without external TBB. The resulting TBB libs are correctly installed in the installation directories. However, for the TBB headers, this is not true.

### Expected behavior
In order to just use one TBB version within our software stack, it would be good and convenient if headers could be (optionally) distributed, too.

### To Reproduce
Searching through the ROOT installation path, I find:
```
find ./ -name "*tbb*"
./lib/libtbb.so
./lib/libtbb.so.2
./lib/libtbbmalloc.so
./lib/libtbbmalloc.so.2
./lib/libtbbmalloc_proxy.so
./lib/libtbbmalloc_proxy.so.2
```

### Setup
ROOT version `v6-24-06`

### Additional context
Built with `alibuild` (build recipe is here: https://github.com/alisw/alidist/blob/master/root.sh)

**Comment by Axel-Naumann** [comment]
Just FYI, making sure we're on the same page here: you can always build ROOT against an external tbb.

**Comment by sawenzel** [comment]
Sure. However, we currently don't have tbb in our software stack. Since ROOT builds/installs tbb in any case, I was just hoping to be able to use this internal version. In other similar cases (vdt), the headers seem to be installed correctly.

**Comment by sawenzel** [comment]
Update: Meanwhile, I spoke with our software distribution team and we now build a standalone TBB in our software stack. So this issue is no longer relevant for us. You may decide to close it or follow up on it for other clients at your own discretion.

**Comment by bellenot** [comment]
@sawenzel thanks for the update! We'll try to find the best solution to fix this issue...

**Comment by guitargeek** [comment]
Hi @sawenzel, I'm happy that you found a solution! Indeed, the builtin dependencies of ROOT are not really meant to be used externally, and you did the right thing by adding an external TBB to your environment!
