### ISSUE TITLE
[MSVC][std:c++latest][permissive-] root failed to build on MSVC

### ISSUE THREAD

**Issue by xiaoxiao-Xu** [root-project/root#9607]
### Describe the bug
The MSVC team recently added root as part of RWC testing. And we found some errors when building root with '/std:c++latest' and '/permissive-'. Could you please help look at this issue or provide some workarounds? Thanks in advance.
### Expected behavior
root project could build successfully under '/std:c++latest' and '/permissive-' mode.
### To Reproduce
1. git clone https://github.com/root-project/root F:\gitP\root-project\root
2. mkdir F:\gitP\root-project\root\build_amd64
2. set CL= /std:c++latest or set CL= /permissive-
3. set PATH=%PATH:C:\Strawberry\perl\bin;=%
4. msbuild /m /p:Platform=x64 /p:Configuration=Release ALL_BUILD.vcxproj /t:Rebuild
### Setup
Visual Studio 2019 16.11.8
### Additional context
Build.log:
/std:c++latest: [build.log](https://github.com/root-project/root/files/7889383/build.log)
/permissive-: [build.log](https://github.com/root-project/root/files/7889386/build.log)

**Comment by bellenot** [comment]
1) `/std:c++latest` is not yet supported. The `std:c++17` is the latest supported standard. That should change when upgrading LLVM & Clang.
2) I see a couple of errors when compiling with the `/permissive-`. flag. They can be fixed, but do you really need this flag when building ROOT? What is the motivation for it?
BTW, the [build.log](https://github.com/root-project/root/files/7889386/build.log) for `/permissive-` has nothing to do with ROOT, the errors are in `F:\gitP\baldurk\renderdoc\`

And FYI, according to [Microsoft](https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170):
> The /permissive- option is implicitly set by the /std:c++latest option starting in Visual Studio 2019 version 16.8

And this is not needed:
> 3. set PATH=%PATH:C:\Strawberry\perl\bin;=%

**Comment by xiaoxiao-Xu** [comment]
do you really need this flag when building ROOT? What is the motivation for it?
--> Yes, we need to build ROOT with '/permissive-'. Although our team are testing MSVC compiler, we also need to test the compiler under the behavior of '/permissive-' and '/std:c++latest'.

BTW, the build.log for /permissive- has nothing to do with ROOT, the errors are in F:\gitP\baldurk\renderdoc\
--> I'm so sorry. I attached a mismatched build log under '/permissive-'. This is real build log
[build.log](https://github.com/root-project/root/files/7895875/build.log).

**Comment by bellenot** [comment]
So sorry, but we cannot fix the `/std:c++latest` issue, since it is not supported by our version of LLVM & Clang. You'll have to wait for the upgrade.
>Although our team are testing MSVC compiler, we also need to test the compiler under the behavior of '/permissive-' and '/std:c++latest'.

Well, if it's only for testing the compiler, I suppose we cannot consider that as a ROOT bug, or do I miss something?

**Comment by xiaoxiao-Xu** [comment]
error message under permissive-:
 `F:\gitP\root-project\root\hist\hist\inc\TF1.h(463,1): error C2445: result type of conditional expression is ambiguous: types 'TString' and 'const char [1]' can be converted to multiple common types `

If the issue is not a ROOT bug, could you please help provide a workarounds aiming at the error above? Thanks a lot.

**Comment by bellenot** [comment]
I've seen those errors and I'll fix them. The only workaround for the time being is not to use `/permissive-` flag, unless you really need it, which is still not clear to me.

**Comment by xiaoxiao-Xu** [comment]
Ok, I got it. I will disable the project under '/permissive-' temperarily. Thanks for your quick reply and attention for the issue.

**Comment by bellenot** [comment]
You're welcome. I'll create a PR linking to this issue so you'll be updated about the progress on this issue.

**Comment by bellenot** [comment]
See PR https://github.com/root-project/root/pull/9630

**Comment by xiaoxiao-Xu** [comment]
Ok. Thanks for your quick fix.

**Comment by bellenot** [comment]
@xiaoxiao-Xu  Fixed in master by commit [8719f0f](https://github.com/root-project/root/commit/8719f0f8437c96792455c8dd876d9703c2bccebf)

**Comment by xiaoxiao-Xu** [comment]
@bellenot Thanks a lot. The error has disappeared.
