### ISSUE TITLE
THStack docu broken link and TSpectrum TGeoMatrix

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#9626]
- [x] Checked for duplicates

### Describe the bug
THStack::Paint function documentation has a broken link:
https://root.cern/doc/master/classTHStack.html#HS00

I guess this was overlooked when reformatting here: https://github.com/root-project/root/commit/830ba5364ad60f287932f002c1c676dd8d6e2aa6#diff-82b523bd29fb2b8da2dc50dfdb01386a70504d8de4b2dc71fd8d6ac14354b5a6

### Expected behavior
Fix link using this:
```
\anchor HS00
### Stack painting
...
/// [Paint the list of histograms.](\ref HS00)
```
### To Reproduce
Go to 
https://root.cern/doc/master/classTHStack.html#a6294f58bebce2f1ce5d6dced8e22bc1e
and click on `Paint list of histograms`

**Comment by ferdymercury** [comment]
https://root.cern.ch/doc/master/classTSpectrum.html Fig.27 image source is also broken.

**Comment by ferdymercury** [comment]
Another broken image is in `TGeoMatrix.cxx \image html geom_transf.jpg` maybe due to https://github.com/root-project/root/commit/fd87047587ef005867f79ff24203c6ff09db769a

**Comment by couet** [comment]
Thanks !
This PR fixes these problems:
https://github.com/root-project/root/pull/9627

**Comment by ferdymercury** [comment]
Thanks!

I found a couple more:

https://root.cern.ch/doc/master/group__fitpanel.html fitpanel.png not found
https://github.com/root-project/root/commit/b4566d45f8ca440b0052cef043527b368b5a0048#diff-8cf7157250c3cd8551d13f6afe0ab3778ed526e3881b34a28a697ca38c5d1512R8

https://root.cern/doc/master/group__ged.html ged.png not found
https://github.com/root-project/root/commit/b4566d45f8ca440b0052cef043527b368b5a0048#diff-ea429a54aef8e660549dedd39d919a121eaaabd24074e7ac6a6abf38b2eda8c2R64
