### ISSUE TITLE
Iteration on `std.vector['char']` is broken

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#9632]
- [x] Checked for duplicates

First reported as a problem in `RDataFrame.AsNumpy` [on the forum](https://root-forum.cern.ch/t/pyroot-read-tree-asnumpy/48426).

The following code:

```python
#!/usr/bin/env python3
import ROOT

vec = ROOT.std.vector['char'](['a','b','c'])
for _ in vec:
    pass
```

produces:

```
TypeError: function takes exactly 5 arguments (1 given)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/blue/Scratchpad/work/forum-pyroot-error/reproducer.py", line 5, in <module>
    for _ in vec:
SystemError: <cppyy.CPPOverload object at 0x7f0b0348c1c0> returned a result with an exception set
```

Notably, _sometimes_ it seems to run without errors.

**Comment by etejedor** [comment]
An even slimmer reproducer (also fails intermittently):
```python
import cppyy
vec = cppyy.gbl.std.vector['char'](['a'])
vec.__real_data()
```
where `__real_data()` is the original `data()` of the vector.

I can't reproduce with e.g. a `vector[int]`, so the problem could be in the wrapping of the result of `__real_data()` into a Python string.

**Comment by etejedor** [comment]
The issue was indeed in the conversion of the `char*` result of `data()` into a Python string, see PR linked above for more details.
