### ISSUE TITLE
`TGraph::Add(TF1 *f)` method like for `TH1`'s

### ISSUE THREAD

**Issue by mattiasotgia** [root-project/root#9637]
### Explain what you would like to see improved
There is not a `TGraph::Add(TF1 *f)` like in `TH1::Add(TF1 *f)` to add the value of the function f evaluated in each point to the y value of the TGraphErrors. It surely would be useful especially to compute ratios and residuals for `TGraph`'s, other than `TH1`'s

For example if there is a `TGrapherror *graph` object, and a `TF1 *fit` function fitted on this very data. To create the residual graph, or the data - bkg  graph the only thing needed is `TGraphErrors *residuals = (TGraphErrors*)graph->Clone();` then `residual->Add(fit, -1);` will make residual graph with fitted funtion removed. 

Also for data-bkg case (here the TF1 function is `bkg`):
```cpp
TGraphErrors *data_bkg = (TGraphErrors*)graph->Clone();
data_bkg->Add(bkg, -1);
```

### Setup
I'm using ROOT version 6.24/02 on macOS mojave, version 10.14.6.

**Comment by ferdymercury** [comment]
I proposed a PR https://github.com/root-project/root/pull/16148
