### ISSUE TITLE
Pyroot TCanvas unresponsive [6.24/06 precompiled, Win11, VStudio 2019 or 2022, python 3.8.10 (32-bit)]

### ISSUE THREAD

**Issue by dwcasper** [root-project/root#9645]
- [X] Checked for duplicates

### Describe the bug
After creating a new TCanvas with Pyroot, moving the cursor over the TCanvas window displays the Windows wait-cursor, and clicking the window makes it hang and show "Not Responding" in the title bar.

### Expected behavior
The newly created TCanvas should be responsive, as it is when created from the ROOT command prompt instead of in Pyroot.

### To Reproduce (in VStudio x86 native tools command window)
> c:\root_v6.24.06\bin\thisroot.bat
> python
>>> import ROOT
>>> c1 = ROOT.TCanvas("blah", "blah blah", 800, 600)

(canvas opens but is unresponsive)

### Setup
ROOT 6.24.06 precompiled binaries (built Sep 02 2021, 14:20:23)
Windows 11 Pro
Python 3.8.10 (32-bit) 
VStudio 2019 (16.11.9) or 2022 (17.0.5) Community edition

### Additional context
ROOT appears to behave properly when launched from the command prompt.

**Comment by couet** [comment]
It looks like a Windows issue. May be @bellenot has some ideas about it.
Also it might be something connected to Python and in that case @etejedor can also help.

**Comment by bellenot** [comment]
Yes, this is a known issue, and there is no solution for the time being,

**Comment by dwcasper** [comment]
Does your example work with 6.24.06?

I have changed .rootrc, and the environment shows

`Gui.Factory:              web                            [Local]`

as expected, but when I run your commands, no http server creation message is displayed.

**Comment by bellenot** [comment]
@dwcasper sorry, you're right, it doesn't work with v6.24.06. If you want to try, you can either take a [nightly build](https://root.cern/download/nightly/?C=M;O=D), or wait for the upcoming v6.26.00.

**Comment by dpiparo** [comment]
I think this has been fixed in 28,30 and master: am I right?

**Comment by dpiparo** [comment]
I am closing the issue. Feel free to re-open it in case this is still an issue.

**Comment by bellenot** [comment]
It still doesn't work on Windows

**Comment by bellenot** [comment]
So the WebGUI (in master) works, or adding the following lines make it work as well:
```
try:
   while not gSystem.ProcessEvents():
      time.sleep(0.02)
except KeyboardInterrupt:
    print('interrupted!')
```
For example:
```
>>> import time
>>> import ROOT
>>> f = ROOT.TFile.Open("hsimple.root")
>>> hpx=f.Get("hpx")
>>> hpx.Draw()
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
>>> try:
...    while not ROOT.gSystem.ProcessEvents():
...       time.sleep(0.02)
... except KeyboardInterrupt:
...     print('interrupted!')
```
