### ISSUE TITLE
When working on a Windows partition from Linux, rootcling is not able to rename an output file

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#9730]
See the discussion at https://root-forum.cern.ch/t/rootcint-cannot-create-dictionary-in-a-vm/48580 .

In short, in certain situations in which the platform is Linux but the working directory belongs to a Windows file system, [this call to std::rename](https://github.com/root-project/root/blob/7a2612dc7ae62832c7683081020e190c49b75569/core/dictgen/src/rootcling_impl.cxx#L2956-L2958) fails because "Windows" does not allow renaming files that are currently in use.

Something like the logic that we already apply for Windows at https://github.com/root-project/root/blob/7a2612dc7ae62832c7683081020e190c49b75569/core/dictgen/src/rootcling_impl.cxx#L2944-L2955 might be needed on Linux as well.

**Comment by Axel-Naumann** [comment]
Bertrand, could you do "what's necessary" here? I suppose following @eguiraud 's suggestion is the way to go, and you can probably validate this with WileE.
