### ISSUE TITLE
Image artifact with zoombox on 1D hist if SetFillStyle 0 on Ubuntu

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#9763]
- [x] Checked for duplicates

### Describe the bug
![image](https://user-images.githubusercontent.com/10653970/151454753-44c1d81f-335a-4400-a703-966b70cd7087.png)
On a canvas with a histogram, if I zoom using right click, SetRangeUser, all works fine. If I zoom using the scroll wheel on the x-axis, it works well, too. If I zoom using press and hold, then release, I get an image artifact:

![image](https://user-images.githubusercontent.com/10653970/151454804-2b639659-8432-437c-9e2a-ffe62bf5e3df.png)
The artifact disappears after clicking once on the canvas.

I do not get the artifact at all if I call at script beginning: `gStyle->SetCanvasPreferGL()`

It seems that the image artifact has exactly the same pattern as the semi-transparent fill-style zooming window. See here:

While Zooming:
![image](https://user-images.githubusercontent.com/10653970/151596601-6749a23e-b22b-4000-a464-2b3cc3f9811d.png)

After Zooming:
![image](https://user-images.githubusercontent.com/10653970/151596998-b8aee660-4b45-48e1-97b6-bc4140897a8b.png)

The pattern in the old labels is slightly different:
![image](https://user-images.githubusercontent.com/10653970/151596825-6a40f470-724c-4c5f-afbc-31c32fb6442f.png)

### Expected behavior
No image artifact is shown.

### To Reproduce
- Download [test_zoom.zip](https://github.com/root-project/root/files/7954355/test_zoom.zip)
- root -l test_zoom.cpp+
- Zoom between 0 and 3000 via mouse press and hold on X axis.

### Setup
The issue appears with:
- [x] Master / Ubuntu 18 and 20
- [x] 6.20.06 / Ubuntu 20
- [x] 6.13.08 / Ubuntu 18
- [x] 5.34.19 / Ubuntu 14 (over ssh)

It does not appear with:
- [x] MacOS.
- [x] 5.34.18/Ubuntu 14 (over ssh)
- [x] 5.32.04/Ubuntu 14 (over ssh)

### Additional context
https://github.com/root-project/root/commit/3787e53acb1a61970f7c033338922214bfbee4c5
https://github.com/root-project/root/issues/9740

**Comment by couet** [comment]
Why do you think this is related to: 3787e53 ?

**Comment by ferdymercury** [comment]
> Why do you think this is related to: [3787e53](https://github.com/root-project/root/commit/3787e53acb1a61970f7c033338922214bfbee4c5) ? Does the artefact disappear if you turn off the move opaque mode ?

The artifact appeared at some point between 5.34/18 and 5.34/19, so I thought that these commits could be related.

**Comment by couet** [comment]
> The artifact appeared at some point between 5.34/18 and 5.34/19, so I thought that these commits could be related.

Ok, that's quite old. Does reverting this patch you pointed fixes it ?

**Comment by ferdymercury** [comment]
(I did not try yet reverting it.)

**Comment by couet** [comment]
The MoveOpaque issue pointed in 3787e53 is connected to TLine. But it seems the artefacts are coming from the shaded area used to highlight the zoomed interval. At least according to the screen captures you posted ....

**Comment by ferdymercury** [comment]
Yes, the shaded area might be the culprit.
It's also when it was included in the release note, fourth point: https://github.com/root-project/root/blob/master/gui/doc/v600/index.md

**Comment by couet** [comment]
> It's also when it was included in the release note, fourth point: https://github.com/root-project/root/blob/master/gui/doc/v600/index.md

That one is for 2D histograms. Your plot ia a 1D one...

**Comment by ferdymercury** [comment]
`The zoom on axis and on 2D histogram`
I think it applies to both 1D and 2D ?

**Comment by couet** [comment]
> I think it applies to both 1D and 2D ?

well ... yes may be I need to retrieve the patch...

**Comment by couet** [comment]
This mechanism is implemented in [THistPainter::ExecuteEvent](https://github.com/root-project/root/blob/5d69eca85a2be137684807446878f782e4a368eb/hist/histpainter/src/THistPainter.cxx#L3468).
In that code the TBox `zoombox` is used to draw this shaded area.

**Comment by ferdymercury** [comment]
Hmm not sure why here there is only a `->Delete` if `dimension==2`: https://github.com/root-project/root/blob/5d69eca85a2be137684807446878f782e4a368eb/hist/histpainter/src/THistPainter.cxx#L3681

**Comment by couet** [comment]
> Hmm not sure why here there is only a ->Delete if dimension==2:

me neither ... I do not remember... that's too old.

**Comment by couet** [comment]
Indeed that code is for 2D only it seems. I changed the boombox color to red and it appears red only  in the 2D case.

**Comment by couet** [comment]
Yes, the `zoombox` is for the 2D case. Do you see such artefact with a 2D histo also ?
Let me try to understand what is done in case of 1D.

**Comment by couet** [comment]
Indeed I was wrong . In case of 1D the[ zoom is done in TPad.cxx](https://github.com/root-project/root/blob/5d69eca85a2be137684807446878f782e4a368eb/graf2d/gpad/src/TPad.cxx#L2280)

**Comment by ferdymercury** [comment]
I don't remember having seen this problem for 2D histograms, but maybe is the interplay with TLines and TGaxis which causes it in my example, rather than it being 1D? Hard to say.

**Comment by couet** [comment]
In any case the `zoombox` for 1D is managed in `TPad.cxx`. I de-activated the alpha mode on Mac to be in the same configuration as yourself. But even with your example I do not see any artefact. May be you can deactivate the zoombox in  `TPad::ExecuteEventAxis` and see if the artefact remains ? By the way if you do a simple drawing of a 1D histogram and try to zoom it, do you also see the artefact ?

**Comment by ferdymercury** [comment]
Yes, I see it with a simple 1D histogram, too, no need for secondary axes.

But... Ok I found out the issue.

I do see the artifact only if I call:
`c->SetFillStyle(0);`

**Comment by ferdymercury** [comment]
You can reproduce it on a free online Ubuntu 20 browser-box:

- Go to https://www.onworks.net/os-distributions/ubuntu-based
- Select Ubuntu 20, Start
- Open a WebBrowser within it, google "cern ROOT install".
- Copy the line of the "required dependencies"
- Open a Terminal
- sudo apt update
- Paste the line of the required dependencies to install missing packages
- Go back to web browser
- Copy link to download binary release
- Back to terminal, paste it there
- tar -xzvf ...
- source root/bin/thisroot.sh
- Back to browser, search "cern root github", go to Issues
- Download the reproducer of this issue
- unzip
- root -l test_zoom.cpp
- Then zoom

**Comment by ferdymercury** [comment]
A more simple reproducer here shows the same effect on Ubuntu 18:
```
TCanvas* c = new TCanvas()
TH1* h = new TH1F("h","h",100,0,10)
c->SetFillStyle(0)
h->Draw()
```

![image](https://user-images.githubusercontent.com/10653970/151991662-805da339-fd11-4490-9d08-631526798254.png)

**Comment by couet** [comment]
.... well

> Copy the line of the "required dependencies"

I am not sure what line you mean

> Open a Terminal

ok 

> sudo apt update

ask me for a password I do not know ...
Never mind ..

**Comment by ferdymercury** [comment]
> > Copy the line of the "required dependencies"

![image](https://user-images.githubusercontent.com/10653970/151994837-3b55785f-dc11-4776-bcfa-a1e8796ffd19.png)
 

> ask me for a password I do not know ... Never mind ..

pwd is 123456

**Comment by couet** [comment]
Ok ... that's too painful ... not stable ... it disconnect ... I don't spend more time on that. Thanks for the recipe anyway

**Comment by ferdymercury** [comment]
> May be you can deactivate the zoombox in `TPad::ExecuteEventAxis` and see if the artifact remains ?

If I deactivate the 'removal' of the zoombox after button release, I get this on Ubuntu 20:
![image](https://user-images.githubusercontent.com/10653970/151999027-9261c038-1725-42d9-bb89-4aa43333c7fd.png)

I can move around with the zoombox, make it smaller, etc. and the artifact is still there. Touching on the canvas does not clear the artifacts, which surprises me!

![image](https://user-images.githubusercontent.com/10653970/151999166-f26ae15b-53d9-4b9e-a08d-fe6afa784214.png)

Only if I right click on the box, "Delete", the artifacts go away. (without having to click on the canvas)

**Comment by ferdymercury** [comment]
If I completely disable the zoombox creation in TPad.cxx, I can still zoom 'invisibly' on the canvas, and the artifact does not appear :)

**Comment by ferdymercury** [comment]
I found a solution. Not sure if the difference is that when releasing the mouse, in MacOS another 'button' is detected which already calls the Modified/Update sequence, in comparison to with Ubuntu.

**Comment by couet** [comment]
All the problems mentioned in this issue are fixed. I close it.
@ferdymercury: thanks again for the debugging and fixes !
