### ISSUE TITLE
[RF] Avoid printing false warning when passing both `FillColor/FillStyle` and `VisualizeError` to RooAbsReal::plotOn()

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#9859]
If one uses the `VisualizeError` and `FillColor` options of [RooAbsReal::plotOn()](https://root.cern.ch/doc/master/classRooAbsReal.html#a5d22644c9cc8178ea1c9dca93fdab48e), for example like this:
```C++
using namespace RooFit;
model.plotOn(frame, VisualizeError(*r, 1), FillColor(kOrange));
```
You get a false warning:
```
WARNING:Plotting -- Fill color or style was set for plotting "model", but these only have an effect when
                    'DrawOption("F")' for fill is used at the same time.
```
That warning should not appear there, because `FillColor` or `FillStyle` actually have an effect because the define the filling of the error band enabled by `VisualizeError`.

The expected behavior is:
* the warning should only appear if `VisualizeError` is not given as a command argument.

To reproduce the problem: run the [rf610_visualerror.C tutorial](https://github.com/root-project/root/blob/master/tutorials/roofit/rf610_visualerror.C).

**Comment by Harshalzzzzzzz** [comment]
@guitargeek Sir How Can I fix this?
I'd like to work on this issue
