### ISSUE TITLE
TF2::Draw crashes when called with "col" draw option

### ISSUE THREAD

**Issue by linev** [root-project/root#9869]
To reproduce, just replace draw option in `tutorials/graphs/waves.C` macro 

    f0->Draw("col");

**Comment by couet** [comment]
Nothing to do with the drawing option of f0. It s a combination of pad creation and function drawing ... the minimal reproducer is:

```
Double_t interference( Double_t *x, Double_t *par)
{
   Double_t x_p2 = x[0] * x[0];
   Double_t d_2 = 0.5 * par[2];
   Double_t ym_p2 = (x[1] - d_2) * (x[1] - d_2);
   Double_t yp_p2 = (x[1] + d_2) * (x[1] + d_2);
   Double_t  tpi_l = TMath::Pi() /  par[1];
   Double_t amplitude = par[0] * (cos(tpi_l  * sqrt(x_p2 + ym_p2))
                      + par[3] * cos(tpi_l  * sqrt(x_p2 + yp_p2)));
   return amplitude * amplitude;
}

void w( Double_t d = 3, Double_t lambda = 1, Double_t amp = 10)
{
   auto c1 = new TCanvas();
   auto pad = new TPad("p","p",  0.5, 0 , 1., 1);
   pad->Draw();

   auto f0 = new TF2("f0",interference, 0.02, 15, -8, 8, 4);
   f0->SetParameters(amp, lambda, 0, 0);
   f0->Draw("col");

//   pad ->cd(); // uncomment this line an it will crash

   auto finter = new TF2("finter",interference, 0.01, 14, -10, 10, 4);
   finter->SetParameters(amp, lambda, d, 1);
   finter->Draw("samecol");
}
```

**Comment by couet** [comment]
I have not completely understood why it crashed but that 's not "simply" because of the Drawing option. For instance if you move the `pad` creation and the `pad` Draw just before the `pad->cd() ` then it does not crash.

**Comment by linev** [comment]
Maybe something wrong with TF2 itself and how function is used?

**Comment by couet** [comment]
Indeed, nothing to do with TF2. An even simpler reproducer is:
```
void w()
{
   auto c1 = new TCanvas();
   auto pad = new TPad("p","p",  0.5, 0 , 1., 1);
   pad->Draw();

   auto h0 = new TH2F("h0","h0", 10, 0.02, 15, 10, -8, 8);
   h0->Draw();

   // pad ->cd(); // uncomment this line an it will crash

   auto h1 = new TH2F("h1","h1", 10, 0.01, 14, 10, -10, 10);
   h1->Draw("same");
}
```

**Comment by linev** [comment]
After drawing in the canvas `pad->GetPainter()` crashes?

I just add in several places:
```
   printf("pad %p painter %p\n", pad, pad->GetPainter());
```

**Comment by linev** [comment]
I have no idea, but after drawing of histogram pad object is corrupted

**Comment by couet** [comment]
Even smaller:
```
void w()
{
   auto c = new TCanvas();
   auto h = new TH2F("h","h", 10, 0., 1., 10, 0., 1.);
   auto p = new TPad("p","p",  0., 0 , 1., 1.);

   p->Draw();
   h->Draw();
// p->cd(); // uncomment this line an it will crash
   h->Draw();
}
```

**Comment by couet** [comment]
And that can be reduced to:

```
void w()
{
   auto c = new TCanvas();
   auto h = new TH2F("h","h", 10, 0., 1., 10, 0., 1.);
   auto p = new TPad("p","p",  0., 0 , 1., 1.);

   p->Draw();
   h->Draw();
   gPad->Update(); // comment this line an it will crash
   p->cd();
}
```

**Comment by linev** [comment]
I found in TH1::Draw(), line 3096.

    gPad->Clear();

If "same" not specified as draw option, pad is cleared.
Mean TPad object will be deleted.

Not a nice feature, one always should draw histogram with care.

**Comment by couet** [comment]
Yes that line is the faulty one. That the feature allowing to Draw histogram one after each other and automatically replace the previous one. I guess histogram is the only object doing that. But that's like that since ROOT exits. Difficult to change this behaviour now. Of course the right way is to use option same.
