### ISSUE TITLE
By default, bars are invisible in bar plots 

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#9870]
Reproducer:

```cpp
void repro() {
   double xs[] = {0,1,2}, ys[] = {1,2,3};
   auto *g = new TGraph(3, xs, ys);
   //g->SetFillColor(kBlue);
   g->Draw("AB");
}
```
shows:

![image](https://user-images.githubusercontent.com/10999034/153621641-2cc3ce91-3240-40c7-b342-8a13efad09f7.png)

Uncommenting the `SetFillColor` fixes the problem, but the first and last bars are now cut by the axes limits (a separate issue, but maybe worth pointing out):

![image](https://user-images.githubusercontent.com/10999034/153621784-cefe215a-6de9-4905-b38c-786e2d1e9c45.png)

**Comment by couet** [comment]
PR here: https://github.com/root-project/root/pull/9885
