### ISSUE TITLE
Disable `RooFit` banner with `CMAKE_CXX_FLAGS` option `__ROOFIT_NOBANNER` by default

### ISSUE THREAD

**Issue by matthewfeickert** [root-project/root#9954]
### Explain what you would like to see improved

When RooFit code is run it will print a copyright "banner"

https://github.com/root-project/root/blob/87a998d48803bc207288d90038e60ff148827664/roofit/roofitcore/src/Initialisation.cxx#L16-L31

```console
$ python -c 'from ROOT import RooFit'  # Get banner

RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt
```

when RooFit was being developed in the early 2000s this might have been about the only way to get open source software recognized and (hopefully!) cited (I was not involved with scientific open source then, so someone who was should feel free to correct me if I have the history wrong). However, in the time since there has been significant improvements in the citation and scholarship of open source software (e.g., some key points being the existence of [JOSS](https://joss.theoj.org/) and [`CITATION.cff`](https://citation-file-format.github.io/) native support on GitHub). As RooFit is also effectively absorbed into ROOT (I hope this is safe to say given the [development history on the `rootfit` module in ROOT](https://github.com/root-project/root/tree/master/roofit) and that the [RooFit development GitHub org](https://github.com/roofit-dev) does their development in a fork of ROOT) and any development as a [solo project on SourceForge](https://sourceforge.net/projects/roofit/) has long halted, the banner is a recurring pain point and nuisance for many users.

The banner can be [disabled at runtime](https://github.com/root-project/root/commit/43b6c775123c371bf02fe7d744e0be8612499f27) through adding `RooFit.Banner: no` to `.rootrc`

```console
$ python -c 'from ROOT import RooFit'  # Get banner

RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt

$ echo 'RooFit.Banner: no' > ~/.rootrc
$ python -c 'from ROOT import RooFit'  # No banner now
```

or [permanently disabled by passing the compile flag `-D__ROOFIT_NOBANNER` **to RooFit** at compile time](https://root-forum.cern.ch/t/how-to-switch-off-roofit-banner/6357/4) and if building ROOT with CMake you can [pass this flag to RooFit through the `CMAKE_CXX_FLAGS` option](https://root-forum.cern.ch/t/roofit-nobanner-on-cmake-option-seems-to-have-no-effect/48828).

Disabling the RooFit banner with

```
-DCMAKE_CXX_FLAGS=-D__ROOFIT_NOBANNER
```

as a default and finding a more constructive and useful form of attribution to the RooFit developers seems like a much better solution then continuing to keep it around as a default. (Altering the `.rootrc` seems like a nice way to deal with legacy versions of ROOT, but is not a good reason to keep the banner.)

### Optional: share how it could be improved

Make the CMake build option

```
-DCMAKE_CXX_FLAGS=-D__ROOFIT_NOBANNER
```

the default to disable the RooFit banner from being enabled by default.

In addition to disabling the banner, there should be some additional action to preserve the copyright and attribution to Wouter and David in a more useful manner, as well as update it to reflect the huge amount of work that has happened since 2013 (here I would suggest a [`CITATION.cff` file](https://citation-file-format.github.io/). I also think ROOT should get one too, but that's another Issue.).

As Wouter doesn't appear to have a GitHub account (**edit**: I'm wrong, he's @wverkerke), I'll tag @egpbos as a public member of the RooFit development team (apologies if I should have tagged someone else) as well as @dkirkby to see if they have any particular thoughts on the matter.

### To Reproduce

To trigger the RooFit banner simply run any piece of code that uses any part of RooFit. Example:

```console
$ python -c 'from ROOT import RooFit'  # Get banner

RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt
```

### Setup

For the examples I've shown above are using ROOT `v6.24/06` built from source

```console
$ root --version
ROOT Version: 6.24/06
Built for linuxx8664gcc on Feb 18 2022, 00:26:00
From tags/v6-24-06@v6-24-06
```

### Additional context

* [ROOT Forum: How to switch off RooFit banner?](https://root-forum.cern.ch/t/how-to-switch-off-roofit-banner/6357/4)
* [ROOT Forum: RooFit Banner - can we switch it off somehow?](https://root-forum.cern.ch/t/roofit-banner-can-we-switch-it-off-somehow/13574)
* [ROOT Forum: `__ROOFIT_NOBANNER=ON` CMake option seems to have no effect](https://root-forum.cern.ch/t/roofit-nobanner-on-cmake-option-seems-to-have-no-effect/48828)
* https://gitlab.cern.ch/atlas-amglab/atlstats/-/merge_requests/63
* https://github.com/conda-forge/root-feedstock/issues/160

**Comment by dantrim** [comment]
I +1 the idea that the banner should be disabled by default.

**Comment by jpivarski** [comment]
I generally expect libraries to be silent and applications to write log files. If an application uses a dozen libraries, users don't want to see a dozen banners scroll past their terminal whenever they run it.

A mark of a library's success is when it gets into the infrastructure in ways that downstream users might not even know about. If that's the goal here—for RooFit to be a library that other libraries or applications are built upon—then it shouldn't print its banner on startup.

Although RooFit's API was designed with data analysts in mind (i.e. as an application), in recent years it has de-facto become a library with the likes of HistFactory, Combine, and lots of mini-frameworks built on top of it. If it were me, I would take that as a good sign and embrace it by becoming more library-like.

(I have the same opinion of FastJet's banner, but that's another story.)

**Comment by dkirkby** [comment]
I am fine with suppressing the banner by default.  Thanks for checking.
I will email Wouter to make sure he is aware of this thread.

**Comment by Axel-Naumann** [comment]
Thanks, @dkirkby !

**Comment by lmoneta** [comment]
Thank you all for your comments. I will discuss also with Wouter and the other RooFit developers next week and we will then fix this.

**Comment by dkirkby** [comment]
> No serious library nowadays has such a banner, why should RooFit have it.

I agree with that assessment today, but the open-source landscape was quite different when that banner originated, over 20 years ago.

**Comment by matthewfeickert** [comment]
> I agree with that assessment today, but the open-source landscape was quite different when that banner originated, over 20 years ago.

Indeed. I really think that there should be a discussion (maybe in another Issue?) of making sure that we credit RooFit in a nicer more modern format. Its been a workhorse for the community for a long time and we should be citing it more!

**Comment by guitargeek** [comment]
Fixed by https://github.com/root-project/root/pull/9965 in the 6.28 development cycle.
