### ISSUE TITLE
Update builtin XRootD to v5.4.1

### ISSUE THREAD

**Issue by matthewfeickert** [root-project/root#9967]
### Explain what you would like to see improved

The current builtin version of XRootD is [`v5.3.1`](https://github.com/xrootd/xrootd/releases/tag/v5.3.1) (last updated by @oshadura in PR #7335)

https://github.com/root-project/root/blob/a940bdbc40d9a0cdac8975c287e1cb7ada0d0c65/builtins/xrootd/CMakeLists.txt#L11

However, in versions of XRootD **pre** [`v5.4.1`](https://github.com/xrootd/xrootd/releases/tag/v5.4.1) (released today 2022-02-23) if XRootD is built with the Python bindings enabled with a modern version of `setuptools` (specifically [`setuptools` v0.60.0+](https://pypi.org/project/setuptools/60.0.0/)) there will be build warnings from `setuptools` and an atypical install path given a dependence on the now deprecated `easy-install.pth`. (c.f. https://github.com/xrootd/xrootd/issues/1579 for lots more details.)

At the moment, this does not affect ROOT at all as ROOT's builtin XRootD explicitly disables the Python bindings

https://github.com/root-project/root/blob/a940bdbc40d9a0cdac8975c287e1cb7ada0d0c65/builtins/xrootd/CMakeLists.txt#L43

given 2c23502137acd9276fc21da300ab3d562278d57f (from @peremato in 2015). I am unclear on the specifics of explicitly disabling the Python bindings from being built as there is no associated PR for the commit.

If there is not a modern reason for this to stay disabled (my assumption is that there is and I am missing it), updating to XRootD `v5.4.1` would allow for the Python bindings to be optionally enabled and to be build safely with the improvements to the Python bindings build process (and also bring along new features and bug fixes).

If there are reasons to keep XRootD below `v5.4.X` then this Issue can get closed.

### Optional: share how it could be improved

Make a PR similar to PR #7335 that would update the builtin to XRootD [`v5.4.1`](https://github.com/xrootd/xrootd/releases/tag/v5.4.1).

### To Reproduce

There isn't a bug explicitly here, but for a discussion on the Python 3 binding and modern `setuptools` issue that was resolved in XRootD `v5.4.1` see the links in additional context.

### Setup

Not relevant for this issue, but all instances related to the XRootD issues were tested in ROOT `v6.24/06`.

### Additional context

* https://github.com/xrootd/xrootd/issues/1579
* https://gitlab.cern.ch/atlas-amglab/atlstats/-/merge_requests/58
* https://gitlab.cern.ch/atlas-amglab/atlstats/-/merge_requests/64

**Comment by Axel-Naumann** [comment]
We saw builtin-xrootd as an internal library, not exposed to the users, and as ROOT doesn't need the Python bindings we have disabled them. I'd still prefer that if you need something from xrootd that ROOT doesn't use / need that you built xrootd yourself, and make that build available to ROOT.

**Comment by matthewfeickert** [comment]
> We saw builtin-xrootd as an internal library, not exposed to the users, and as ROOT doesn't need the Python bindings we have disabled them. I'd still prefer that if you need something from xrootd that ROOT doesn't use / need that you built xrootd yourself, and make that build available to ROOT.

Thanks. XRootD is very easy to build so that's reasonable. Just seemed strange that it couldn't be a CMake flag.

**Comment by Axel-Naumann** [comment]
We have bumped the builtin xrootd to 5.4.1 in master and v6-26-00-patches!
